// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_extentityaccess.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the EXCR_ExtEntityAccess module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ExtEntityDataViewer_Page_InitializeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_ExtEntityAccess.ACT_ExtEntityDataViewer_Page_Initialize");
		return builder;
	}

	public static void aCT_ExtEntityDataViewer_Page_Initialize(IContext context)
	{
		aCT_ExtEntityDataViewer_Page_InitializeBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cONF_ODataService_EntityFactoryConfigBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_ExtEntityAccess.CONF_ODataService_EntityFactoryConfig");
		return builder;
	}

	public static system.proxies.ConsumedODataConfiguration cONF_ODataService_EntityFactoryConfig(IContext context)
	{
		Object result = cONF_ODataService_EntityFactoryConfigBuilder().execute(context);
		return result == null ? null : system.proxies.ConsumedODataConfiguration.initialize(context, (IMendixObject) result);
	}
}
