// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package disw_designsystem.proxies;

public class AccountExtension implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject accountExtensionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DISW_DesignSystem.AccountExtension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Initials("Initials"),
		AccountProfilePicture_AccountExtension("DISW_DesignSystem.AccountProfilePicture_AccountExtension");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AccountExtension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AccountExtension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountExtensionMendixObject)
	{
		if (accountExtensionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!accountExtensionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.accountExtensionMendixObject = accountExtensionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static disw_designsystem.proxies.AccountExtension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new disw_designsystem.proxies.AccountExtension(context, mendixObject);
	}

	public static disw_designsystem.proxies.AccountExtension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return disw_designsystem.proxies.AccountExtension.initialize(context, mendixObject);
	}

	public static java.util.List<disw_designsystem.proxies.AccountExtension> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> disw_designsystem.proxies.AccountExtension.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Initials
	 */
	public final java.lang.String getInitials()
	{
		return getInitials(getContext());
	}

	/**
	 * @param context
	 * @return value of Initials
	 */
	public final java.lang.String getInitials(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Initials.toString());
	}

	/**
	 * Set value of Initials
	 * @param initials
	 */
	public final void setInitials(java.lang.String initials)
	{
		setInitials(getContext(), initials);
	}

	/**
	 * Set value of Initials
	 * @param context
	 * @param initials
	 */
	public final void setInitials(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String initials)
	{
		getMendixObject().setValue(context, MemberNames.Initials.toString(), initials);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AccountProfilePicture_AccountExtension
	 */
	public final disw_designsystem.proxies.AccountProfilePicture getAccountProfilePicture_AccountExtension() throws com.mendix.core.CoreException
	{
		return getAccountProfilePicture_AccountExtension(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountProfilePicture_AccountExtension
	 * @throws com.mendix.core.CoreException
	 */
	public final disw_designsystem.proxies.AccountProfilePicture getAccountProfilePicture_AccountExtension(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		disw_designsystem.proxies.AccountProfilePicture result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AccountProfilePicture_AccountExtension.toString());
		if (identifier != null) {
			result = disw_designsystem.proxies.AccountProfilePicture.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AccountProfilePicture_AccountExtension
	 * @param accountprofilepicture_accountextension
	 */
	public final void setAccountProfilePicture_AccountExtension(disw_designsystem.proxies.AccountProfilePicture accountprofilepicture_accountextension)
	{
		setAccountProfilePicture_AccountExtension(getContext(), accountprofilepicture_accountextension);
	}

	/**
	 * Set value of AccountProfilePicture_AccountExtension
	 * @param context
	 * @param accountprofilepicture_accountextension
	 */
	public final void setAccountProfilePicture_AccountExtension(com.mendix.systemwideinterfaces.core.IContext context, disw_designsystem.proxies.AccountProfilePicture accountprofilepicture_accountextension)
	{
		if (accountprofilepicture_accountextension == null) {
			getMendixObject().setValue(context, MemberNames.AccountProfilePicture_AccountExtension.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AccountProfilePicture_AccountExtension.toString(), accountprofilepicture_accountextension.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return accountExtensionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final disw_designsystem.proxies.AccountExtension that = (disw_designsystem.proxies.AccountExtension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
