// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class CalledByTransactionTask implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject calledByTransactionTaskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.CalledByTransactionTask";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		CalledByTransactionTask_ReqComponentIssueTxnRoot("EXCR_ContainerManagement_API.CalledByTransactionTask_ReqComponentIssueTxnRoot"),
		Parent_CalledByTransactionTask("EXCR_ContainerManagement_API.Parent_CalledByTransactionTask"),
		CalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot("EXCR_ContainerManagement_API.CalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject calledByTransactionTaskMendixObject)
	{
		if (calledByTransactionTaskMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!calledByTransactionTaskMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.calledByTransactionTaskMendixObject = calledByTransactionTaskMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.CalledByTransactionTask initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.CalledByTransactionTask(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.CalledByTransactionTask load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.CalledByTransactionTask.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CalledByTransactionTask_ReqComponentIssueTxnRoot
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot getCalledByTransactionTask_ReqComponentIssueTxnRoot() throws com.mendix.core.CoreException
	{
		return getCalledByTransactionTask_ReqComponentIssueTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of CalledByTransactionTask_ReqComponentIssueTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot getCalledByTransactionTask_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CalledByTransactionTask_ReqComponentIssueTxnRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CalledByTransactionTask_ReqComponentIssueTxnRoot
	 * @param calledbytransactiontask_reqcomponentissuetxnroot
	 */
	public final void setCalledByTransactionTask_ReqComponentIssueTxnRoot(excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot calledbytransactiontask_reqcomponentissuetxnroot)
	{
		setCalledByTransactionTask_ReqComponentIssueTxnRoot(getContext(), calledbytransactiontask_reqcomponentissuetxnroot);
	}

	/**
	 * Set value of CalledByTransactionTask_ReqComponentIssueTxnRoot
	 * @param context
	 * @param calledbytransactiontask_reqcomponentissuetxnroot
	 */
	public final void setCalledByTransactionTask_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot calledbytransactiontask_reqcomponentissuetxnroot)
	{
		if (calledbytransactiontask_reqcomponentissuetxnroot == null) {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqComponentIssueTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqComponentIssueTxnRoot.toString(), calledbytransactiontask_reqcomponentissuetxnroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_CalledByTransactionTask
	 */
	public final excr_containermanagement_api.proxies.Parent getParent_CalledByTransactionTask() throws com.mendix.core.CoreException
	{
		return getParent_CalledByTransactionTask(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_CalledByTransactionTask
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.Parent getParent_CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.Parent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_CalledByTransactionTask.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.Parent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_CalledByTransactionTask
	 * @param parent_calledbytransactiontask
	 */
	public final void setParent_CalledByTransactionTask(excr_containermanagement_api.proxies.Parent parent_calledbytransactiontask)
	{
		setParent_CalledByTransactionTask(getContext(), parent_calledbytransactiontask);
	}

	/**
	 * Set value of Parent_CalledByTransactionTask
	 * @param context
	 * @param parent_calledbytransactiontask
	 */
	public final void setParent_CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.Parent parent_calledbytransactiontask)
	{
		if (parent_calledbytransactiontask == null) {
			getMendixObject().setValue(context, MemberNames.Parent_CalledByTransactionTask.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_CalledByTransactionTask.toString(), parent_calledbytransactiontask.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueMaterialsRequirementsRoot getCalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot() throws com.mendix.core.CoreException
	{
		return getCalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of CalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueMaterialsRequirementsRoot getCalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqComponentIssueMaterialsRequirementsRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqComponentIssueMaterialsRequirementsRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot
	 * @param calledbytransactiontask_reqcomponentissuematerialsrequirementsroot
	 */
	public final void setCalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot(excr_containermanagement_api.proxies.ReqComponentIssueMaterialsRequirementsRoot calledbytransactiontask_reqcomponentissuematerialsrequirementsroot)
	{
		setCalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot(getContext(), calledbytransactiontask_reqcomponentissuematerialsrequirementsroot);
	}

	/**
	 * Set value of CalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot
	 * @param context
	 * @param calledbytransactiontask_reqcomponentissuematerialsrequirementsroot
	 */
	public final void setCalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqComponentIssueMaterialsRequirementsRoot calledbytransactiontask_reqcomponentissuematerialsrequirementsroot)
	{
		if (calledbytransactiontask_reqcomponentissuematerialsrequirementsroot == null) {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqComponentIssueMaterialsRequirementsRoot.toString(), calledbytransactiontask_reqcomponentissuematerialsrequirementsroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return calledByTransactionTaskMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.CalledByTransactionTask that = (excr_containermanagement_api.proxies.CalledByTransactionTask) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
