// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class CaptureDetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject captureDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.CaptureDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CaptureDetails_ESigDetail("EXCR_ContainerManagement_API.CaptureDetails_ESigDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CaptureDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CaptureDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject captureDetailsMendixObject)
	{
		if (captureDetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!captureDetailsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.captureDetailsMendixObject = captureDetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.CaptureDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.CaptureDetails(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.CaptureDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.CaptureDetails.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CaptureDetails_ESigDetail
	 */
	public final excr_containermanagement_api.proxies.ESigDetail getCaptureDetails_ESigDetail() throws com.mendix.core.CoreException
	{
		return getCaptureDetails_ESigDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of CaptureDetails_ESigDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ESigDetail getCaptureDetails_ESigDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ESigDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CaptureDetails_ESigDetail.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ESigDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CaptureDetails_ESigDetail
	 * @param capturedetails_esigdetail
	 */
	public final void setCaptureDetails_ESigDetail(excr_containermanagement_api.proxies.ESigDetail capturedetails_esigdetail)
	{
		setCaptureDetails_ESigDetail(getContext(), capturedetails_esigdetail);
	}

	/**
	 * Set value of CaptureDetails_ESigDetail
	 * @param context
	 * @param capturedetails_esigdetail
	 */
	public final void setCaptureDetails_ESigDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ESigDetail capturedetails_esigdetail)
	{
		if (capturedetails_esigdetail == null) {
			getMendixObject().setValue(context, MemberNames.CaptureDetails_ESigDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CaptureDetails_ESigDetail.toString(), capturedetails_esigdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return captureDetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.CaptureDetails that = (excr_containermanagement_api.proxies.CaptureDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
