// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class Containers implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject containersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.Containers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Containers_Root("EXCR_ContainerManagement_API.Containers_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Containers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Containers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject containersMendixObject)
	{
		if (containersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!containersMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.containersMendixObject = containersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.Containers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.Containers(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.Containers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.Containers.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Containers_Root
	 */
	public final excr_containermanagement_api.proxies.Root getContainers_Root() throws com.mendix.core.CoreException
	{
		return getContainers_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Containers_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.Root getContainers_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Containers_Root.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Containers_Root
	 * @param containers_root
	 */
	public final void setContainers_Root(excr_containermanagement_api.proxies.Root containers_root)
	{
		setContainers_Root(getContext(), containers_root);
	}

	/**
	 * Set value of Containers_Root
	 * @param context
	 * @param containers_root
	 */
	public final void setContainers_Root(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.Root containers_root)
	{
		if (containers_root == null) {
			getMendixObject().setValue(context, MemberNames.Containers_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Containers_Root.toString(), containers_root.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return containersMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.Containers that = (excr_containermanagement_api.proxies.Containers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
