// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class IssueDetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject issueDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.IssueDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		InstanceID("InstanceID"),
		ActualQty2Issued("ActualQty2Issued"),
		ActualQtyIssued("ActualQtyIssued"),
		AllowManualWeighOverride("AllowManualWeighOverride"),
		AllowSubstitution("AllowSubstitution"),
		CloseWhenEmpty("CloseWhenEmpty"),
		IsManualReadingOnly("IsManualReadingOnly"),
		IsRecipeQtyEvaluated("IsRecipeQtyEvaluated"),
		IssueControl("IssueControl"),
		IssueControlName("IssueControlName"),
		NetQty2Required("NetQty2Required"),
		NetQtyRequired("NetQtyRequired"),
		Qty2Issued("Qty2Issued"),
		QtyIssued("QtyIssued"),
		QtyRequired("QtyRequired"),
		ValidateQtyDifference("ValidateQtyDifference"),
		ValidSequence("ValidSequence"),
		ReferenceDesignator("ReferenceDesignator"),
		IssueDetails_ResComponentIssueInquiryRoot("EXCR_ContainerManagement_API.IssueDetails_ResComponentIssueInquiryRoot"),
		BOMLineItem_IssueDetails("EXCR_ContainerManagement_API.BOMLineItem_IssueDetails"),
		IssueActualsHistory_IssueDetails("EXCR_ContainerManagement_API.IssueActualsHistory_IssueDetails"),
		Product_IssueDetails("EXCR_ContainerManagement_API.Product_IssueDetails"),
		ProductSubstitutes_IssueDetails("EXCR_ContainerManagement_API.ProductSubstitutes_IssueDetails"),
		RemovalHistoryDetails_IssueDetails("EXCR_ContainerManagement_API.RemovalHistoryDetails_IssueDetails"),
		UOM_IssueDetails("EXCR_ContainerManagement_API.UOM_IssueDetails"),
		UOM2_IssueDetails("EXCR_ContainerManagement_API.UOM2_IssueDetails");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IssueDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected IssueDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject issueDetailsMendixObject)
	{
		if (issueDetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!issueDetailsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.issueDetailsMendixObject = issueDetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.IssueDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.IssueDetails(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.IssueDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.IssueDetails.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID()
	{
		return getInstanceID(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceID.toString());
	}

	/**
	 * Set value of InstanceID
	 * @param instanceid
	 */
	public final void setInstanceID(java.lang.String instanceid)
	{
		setInstanceID(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceID
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceID.toString(), instanceid);
	}

	/**
	 * @return value of ActualQty2Issued
	 */
	public final java.math.BigDecimal getActualQty2Issued()
	{
		return getActualQty2Issued(getContext());
	}

	/**
	 * @param context
	 * @return value of ActualQty2Issued
	 */
	public final java.math.BigDecimal getActualQty2Issued(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ActualQty2Issued.toString());
	}

	/**
	 * Set value of ActualQty2Issued
	 * @param actualqty2issued
	 */
	public final void setActualQty2Issued(java.math.BigDecimal actualqty2issued)
	{
		setActualQty2Issued(getContext(), actualqty2issued);
	}

	/**
	 * Set value of ActualQty2Issued
	 * @param context
	 * @param actualqty2issued
	 */
	public final void setActualQty2Issued(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal actualqty2issued)
	{
		getMendixObject().setValue(context, MemberNames.ActualQty2Issued.toString(), actualqty2issued);
	}

	/**
	 * @return value of ActualQtyIssued
	 */
	public final java.math.BigDecimal getActualQtyIssued()
	{
		return getActualQtyIssued(getContext());
	}

	/**
	 * @param context
	 * @return value of ActualQtyIssued
	 */
	public final java.math.BigDecimal getActualQtyIssued(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ActualQtyIssued.toString());
	}

	/**
	 * Set value of ActualQtyIssued
	 * @param actualqtyissued
	 */
	public final void setActualQtyIssued(java.math.BigDecimal actualqtyissued)
	{
		setActualQtyIssued(getContext(), actualqtyissued);
	}

	/**
	 * Set value of ActualQtyIssued
	 * @param context
	 * @param actualqtyissued
	 */
	public final void setActualQtyIssued(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal actualqtyissued)
	{
		getMendixObject().setValue(context, MemberNames.ActualQtyIssued.toString(), actualqtyissued);
	}

	/**
	 * @return value of AllowManualWeighOverride
	 */
	public final java.lang.Boolean getAllowManualWeighOverride()
	{
		return getAllowManualWeighOverride(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowManualWeighOverride
	 */
	public final java.lang.Boolean getAllowManualWeighOverride(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AllowManualWeighOverride.toString());
	}

	/**
	 * Set value of AllowManualWeighOverride
	 * @param allowmanualweighoverride
	 */
	public final void setAllowManualWeighOverride(java.lang.Boolean allowmanualweighoverride)
	{
		setAllowManualWeighOverride(getContext(), allowmanualweighoverride);
	}

	/**
	 * Set value of AllowManualWeighOverride
	 * @param context
	 * @param allowmanualweighoverride
	 */
	public final void setAllowManualWeighOverride(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allowmanualweighoverride)
	{
		getMendixObject().setValue(context, MemberNames.AllowManualWeighOverride.toString(), allowmanualweighoverride);
	}

	/**
	 * @return value of AllowSubstitution
	 */
	public final java.lang.Boolean getAllowSubstitution()
	{
		return getAllowSubstitution(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowSubstitution
	 */
	public final java.lang.Boolean getAllowSubstitution(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AllowSubstitution.toString());
	}

	/**
	 * Set value of AllowSubstitution
	 * @param allowsubstitution
	 */
	public final void setAllowSubstitution(java.lang.Boolean allowsubstitution)
	{
		setAllowSubstitution(getContext(), allowsubstitution);
	}

	/**
	 * Set value of AllowSubstitution
	 * @param context
	 * @param allowsubstitution
	 */
	public final void setAllowSubstitution(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allowsubstitution)
	{
		getMendixObject().setValue(context, MemberNames.AllowSubstitution.toString(), allowsubstitution);
	}

	/**
	 * @return value of CloseWhenEmpty
	 */
	public final java.lang.Boolean getCloseWhenEmpty()
	{
		return getCloseWhenEmpty(getContext());
	}

	/**
	 * @param context
	 * @return value of CloseWhenEmpty
	 */
	public final java.lang.Boolean getCloseWhenEmpty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CloseWhenEmpty.toString());
	}

	/**
	 * Set value of CloseWhenEmpty
	 * @param closewhenempty
	 */
	public final void setCloseWhenEmpty(java.lang.Boolean closewhenempty)
	{
		setCloseWhenEmpty(getContext(), closewhenempty);
	}

	/**
	 * Set value of CloseWhenEmpty
	 * @param context
	 * @param closewhenempty
	 */
	public final void setCloseWhenEmpty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean closewhenempty)
	{
		getMendixObject().setValue(context, MemberNames.CloseWhenEmpty.toString(), closewhenempty);
	}

	/**
	 * @return value of IsManualReadingOnly
	 */
	public final java.lang.Boolean getIsManualReadingOnly()
	{
		return getIsManualReadingOnly(getContext());
	}

	/**
	 * @param context
	 * @return value of IsManualReadingOnly
	 */
	public final java.lang.Boolean getIsManualReadingOnly(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsManualReadingOnly.toString());
	}

	/**
	 * Set value of IsManualReadingOnly
	 * @param ismanualreadingonly
	 */
	public final void setIsManualReadingOnly(java.lang.Boolean ismanualreadingonly)
	{
		setIsManualReadingOnly(getContext(), ismanualreadingonly);
	}

	/**
	 * Set value of IsManualReadingOnly
	 * @param context
	 * @param ismanualreadingonly
	 */
	public final void setIsManualReadingOnly(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ismanualreadingonly)
	{
		getMendixObject().setValue(context, MemberNames.IsManualReadingOnly.toString(), ismanualreadingonly);
	}

	/**
	 * @return value of IsRecipeQtyEvaluated
	 */
	public final java.lang.Boolean getIsRecipeQtyEvaluated()
	{
		return getIsRecipeQtyEvaluated(getContext());
	}

	/**
	 * @param context
	 * @return value of IsRecipeQtyEvaluated
	 */
	public final java.lang.Boolean getIsRecipeQtyEvaluated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsRecipeQtyEvaluated.toString());
	}

	/**
	 * Set value of IsRecipeQtyEvaluated
	 * @param isrecipeqtyevaluated
	 */
	public final void setIsRecipeQtyEvaluated(java.lang.Boolean isrecipeqtyevaluated)
	{
		setIsRecipeQtyEvaluated(getContext(), isrecipeqtyevaluated);
	}

	/**
	 * Set value of IsRecipeQtyEvaluated
	 * @param context
	 * @param isrecipeqtyevaluated
	 */
	public final void setIsRecipeQtyEvaluated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isrecipeqtyevaluated)
	{
		getMendixObject().setValue(context, MemberNames.IsRecipeQtyEvaluated.toString(), isrecipeqtyevaluated);
	}

	/**
	 * @return value of IssueControl
	 */
	public final java.lang.Integer getIssueControl()
	{
		return getIssueControl(getContext());
	}

	/**
	 * @param context
	 * @return value of IssueControl
	 */
	public final java.lang.Integer getIssueControl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IssueControl.toString());
	}

	/**
	 * Set value of IssueControl
	 * @param issuecontrol
	 */
	public final void setIssueControl(java.lang.Integer issuecontrol)
	{
		setIssueControl(getContext(), issuecontrol);
	}

	/**
	 * Set value of IssueControl
	 * @param context
	 * @param issuecontrol
	 */
	public final void setIssueControl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer issuecontrol)
	{
		getMendixObject().setValue(context, MemberNames.IssueControl.toString(), issuecontrol);
	}

	/**
	 * @return value of IssueControlName
	 */
	public final java.lang.String getIssueControlName()
	{
		return getIssueControlName(getContext());
	}

	/**
	 * @param context
	 * @return value of IssueControlName
	 */
	public final java.lang.String getIssueControlName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IssueControlName.toString());
	}

	/**
	 * Set value of IssueControlName
	 * @param issuecontrolname
	 */
	public final void setIssueControlName(java.lang.String issuecontrolname)
	{
		setIssueControlName(getContext(), issuecontrolname);
	}

	/**
	 * Set value of IssueControlName
	 * @param context
	 * @param issuecontrolname
	 */
	public final void setIssueControlName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issuecontrolname)
	{
		getMendixObject().setValue(context, MemberNames.IssueControlName.toString(), issuecontrolname);
	}

	/**
	 * @return value of NetQty2Required
	 */
	public final java.math.BigDecimal getNetQty2Required()
	{
		return getNetQty2Required(getContext());
	}

	/**
	 * @param context
	 * @return value of NetQty2Required
	 */
	public final java.math.BigDecimal getNetQty2Required(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NetQty2Required.toString());
	}

	/**
	 * Set value of NetQty2Required
	 * @param netqty2required
	 */
	public final void setNetQty2Required(java.math.BigDecimal netqty2required)
	{
		setNetQty2Required(getContext(), netqty2required);
	}

	/**
	 * Set value of NetQty2Required
	 * @param context
	 * @param netqty2required
	 */
	public final void setNetQty2Required(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal netqty2required)
	{
		getMendixObject().setValue(context, MemberNames.NetQty2Required.toString(), netqty2required);
	}

	/**
	 * @return value of NetQtyRequired
	 */
	public final java.math.BigDecimal getNetQtyRequired()
	{
		return getNetQtyRequired(getContext());
	}

	/**
	 * @param context
	 * @return value of NetQtyRequired
	 */
	public final java.math.BigDecimal getNetQtyRequired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NetQtyRequired.toString());
	}

	/**
	 * Set value of NetQtyRequired
	 * @param netqtyrequired
	 */
	public final void setNetQtyRequired(java.math.BigDecimal netqtyrequired)
	{
		setNetQtyRequired(getContext(), netqtyrequired);
	}

	/**
	 * Set value of NetQtyRequired
	 * @param context
	 * @param netqtyrequired
	 */
	public final void setNetQtyRequired(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal netqtyrequired)
	{
		getMendixObject().setValue(context, MemberNames.NetQtyRequired.toString(), netqtyrequired);
	}

	/**
	 * @return value of Qty2Issued
	 */
	public final java.math.BigDecimal getQty2Issued()
	{
		return getQty2Issued(getContext());
	}

	/**
	 * @param context
	 * @return value of Qty2Issued
	 */
	public final java.math.BigDecimal getQty2Issued(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Qty2Issued.toString());
	}

	/**
	 * Set value of Qty2Issued
	 * @param qty2issued
	 */
	public final void setQty2Issued(java.math.BigDecimal qty2issued)
	{
		setQty2Issued(getContext(), qty2issued);
	}

	/**
	 * Set value of Qty2Issued
	 * @param context
	 * @param qty2issued
	 */
	public final void setQty2Issued(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal qty2issued)
	{
		getMendixObject().setValue(context, MemberNames.Qty2Issued.toString(), qty2issued);
	}

	/**
	 * @return value of QtyIssued
	 */
	public final java.math.BigDecimal getQtyIssued()
	{
		return getQtyIssued(getContext());
	}

	/**
	 * @param context
	 * @return value of QtyIssued
	 */
	public final java.math.BigDecimal getQtyIssued(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.QtyIssued.toString());
	}

	/**
	 * Set value of QtyIssued
	 * @param qtyissued
	 */
	public final void setQtyIssued(java.math.BigDecimal qtyissued)
	{
		setQtyIssued(getContext(), qtyissued);
	}

	/**
	 * Set value of QtyIssued
	 * @param context
	 * @param qtyissued
	 */
	public final void setQtyIssued(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal qtyissued)
	{
		getMendixObject().setValue(context, MemberNames.QtyIssued.toString(), qtyissued);
	}

	/**
	 * @return value of QtyRequired
	 */
	public final java.math.BigDecimal getQtyRequired()
	{
		return getQtyRequired(getContext());
	}

	/**
	 * @param context
	 * @return value of QtyRequired
	 */
	public final java.math.BigDecimal getQtyRequired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.QtyRequired.toString());
	}

	/**
	 * Set value of QtyRequired
	 * @param qtyrequired
	 */
	public final void setQtyRequired(java.math.BigDecimal qtyrequired)
	{
		setQtyRequired(getContext(), qtyrequired);
	}

	/**
	 * Set value of QtyRequired
	 * @param context
	 * @param qtyrequired
	 */
	public final void setQtyRequired(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal qtyrequired)
	{
		getMendixObject().setValue(context, MemberNames.QtyRequired.toString(), qtyrequired);
	}

	/**
	 * @return value of ValidateQtyDifference
	 */
	public final java.lang.Boolean getValidateQtyDifference()
	{
		return getValidateQtyDifference(getContext());
	}

	/**
	 * @param context
	 * @return value of ValidateQtyDifference
	 */
	public final java.lang.Boolean getValidateQtyDifference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ValidateQtyDifference.toString());
	}

	/**
	 * Set value of ValidateQtyDifference
	 * @param validateqtydifference
	 */
	public final void setValidateQtyDifference(java.lang.Boolean validateqtydifference)
	{
		setValidateQtyDifference(getContext(), validateqtydifference);
	}

	/**
	 * Set value of ValidateQtyDifference
	 * @param context
	 * @param validateqtydifference
	 */
	public final void setValidateQtyDifference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean validateqtydifference)
	{
		getMendixObject().setValue(context, MemberNames.ValidateQtyDifference.toString(), validateqtydifference);
	}

	/**
	 * @return value of ValidSequence
	 */
	public final java.lang.Boolean getValidSequence()
	{
		return getValidSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of ValidSequence
	 */
	public final java.lang.Boolean getValidSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ValidSequence.toString());
	}

	/**
	 * Set value of ValidSequence
	 * @param validsequence
	 */
	public final void setValidSequence(java.lang.Boolean validsequence)
	{
		setValidSequence(getContext(), validsequence);
	}

	/**
	 * Set value of ValidSequence
	 * @param context
	 * @param validsequence
	 */
	public final void setValidSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean validsequence)
	{
		getMendixObject().setValue(context, MemberNames.ValidSequence.toString(), validsequence);
	}

	/**
	 * @return value of ReferenceDesignator
	 */
	public final java.lang.String getReferenceDesignator()
	{
		return getReferenceDesignator(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceDesignator
	 */
	public final java.lang.String getReferenceDesignator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReferenceDesignator.toString());
	}

	/**
	 * Set value of ReferenceDesignator
	 * @param referencedesignator
	 */
	public final void setReferenceDesignator(java.lang.String referencedesignator)
	{
		setReferenceDesignator(getContext(), referencedesignator);
	}

	/**
	 * Set value of ReferenceDesignator
	 * @param context
	 * @param referencedesignator
	 */
	public final void setReferenceDesignator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String referencedesignator)
	{
		getMendixObject().setValue(context, MemberNames.ReferenceDesignator.toString(), referencedesignator);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IssueDetails_ResComponentIssueInquiryRoot
	 */
	public final excr_containermanagement_api.proxies.ResComponentIssueInquiryRoot getIssueDetails_ResComponentIssueInquiryRoot() throws com.mendix.core.CoreException
	{
		return getIssueDetails_ResComponentIssueInquiryRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of IssueDetails_ResComponentIssueInquiryRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ResComponentIssueInquiryRoot getIssueDetails_ResComponentIssueInquiryRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ResComponentIssueInquiryRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IssueDetails_ResComponentIssueInquiryRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ResComponentIssueInquiryRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IssueDetails_ResComponentIssueInquiryRoot
	 * @param issuedetails_rescomponentissueinquiryroot
	 */
	public final void setIssueDetails_ResComponentIssueInquiryRoot(excr_containermanagement_api.proxies.ResComponentIssueInquiryRoot issuedetails_rescomponentissueinquiryroot)
	{
		setIssueDetails_ResComponentIssueInquiryRoot(getContext(), issuedetails_rescomponentissueinquiryroot);
	}

	/**
	 * Set value of IssueDetails_ResComponentIssueInquiryRoot
	 * @param context
	 * @param issuedetails_rescomponentissueinquiryroot
	 */
	public final void setIssueDetails_ResComponentIssueInquiryRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ResComponentIssueInquiryRoot issuedetails_rescomponentissueinquiryroot)
	{
		if (issuedetails_rescomponentissueinquiryroot == null) {
			getMendixObject().setValue(context, MemberNames.IssueDetails_ResComponentIssueInquiryRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IssueDetails_ResComponentIssueInquiryRoot.toString(), issuedetails_rescomponentissueinquiryroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BOMLineItem_IssueDetails
	 */
	public final excr_containermanagement_api.proxies.BOMLineItem getBOMLineItem_IssueDetails() throws com.mendix.core.CoreException
	{
		return getBOMLineItem_IssueDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of BOMLineItem_IssueDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.BOMLineItem getBOMLineItem_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.BOMLineItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BOMLineItem_IssueDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.BOMLineItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BOMLineItem_IssueDetails
	 * @param bomlineitem_issuedetails
	 */
	public final void setBOMLineItem_IssueDetails(excr_containermanagement_api.proxies.BOMLineItem bomlineitem_issuedetails)
	{
		setBOMLineItem_IssueDetails(getContext(), bomlineitem_issuedetails);
	}

	/**
	 * Set value of BOMLineItem_IssueDetails
	 * @param context
	 * @param bomlineitem_issuedetails
	 */
	public final void setBOMLineItem_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.BOMLineItem bomlineitem_issuedetails)
	{
		if (bomlineitem_issuedetails == null) {
			getMendixObject().setValue(context, MemberNames.BOMLineItem_IssueDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BOMLineItem_IssueDetails.toString(), bomlineitem_issuedetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IssueActualsHistory_IssueDetails
	 */
	public final excr_containermanagement_api.proxies.IssueActualsHistory getIssueActualsHistory_IssueDetails() throws com.mendix.core.CoreException
	{
		return getIssueActualsHistory_IssueDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of IssueActualsHistory_IssueDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.IssueActualsHistory getIssueActualsHistory_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.IssueActualsHistory result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IssueActualsHistory_IssueDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.IssueActualsHistory.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IssueActualsHistory_IssueDetails
	 * @param issueactualshistory_issuedetails
	 */
	public final void setIssueActualsHistory_IssueDetails(excr_containermanagement_api.proxies.IssueActualsHistory issueactualshistory_issuedetails)
	{
		setIssueActualsHistory_IssueDetails(getContext(), issueactualshistory_issuedetails);
	}

	/**
	 * Set value of IssueActualsHistory_IssueDetails
	 * @param context
	 * @param issueactualshistory_issuedetails
	 */
	public final void setIssueActualsHistory_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.IssueActualsHistory issueactualshistory_issuedetails)
	{
		if (issueactualshistory_issuedetails == null) {
			getMendixObject().setValue(context, MemberNames.IssueActualsHistory_IssueDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IssueActualsHistory_IssueDetails.toString(), issueactualshistory_issuedetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Product_IssueDetails
	 */
	public final excr_containermanagement_api.proxies.Product getProduct_IssueDetails() throws com.mendix.core.CoreException
	{
		return getProduct_IssueDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of Product_IssueDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.Product getProduct_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Product_IssueDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.Product.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Product_IssueDetails
	 * @param product_issuedetails
	 */
	public final void setProduct_IssueDetails(excr_containermanagement_api.proxies.Product product_issuedetails)
	{
		setProduct_IssueDetails(getContext(), product_issuedetails);
	}

	/**
	 * Set value of Product_IssueDetails
	 * @param context
	 * @param product_issuedetails
	 */
	public final void setProduct_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.Product product_issuedetails)
	{
		if (product_issuedetails == null) {
			getMendixObject().setValue(context, MemberNames.Product_IssueDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Product_IssueDetails.toString(), product_issuedetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ProductSubstitutes_IssueDetails
	 */
	public final excr_containermanagement_api.proxies.ProductSubstitutes getProductSubstitutes_IssueDetails() throws com.mendix.core.CoreException
	{
		return getProductSubstitutes_IssueDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductSubstitutes_IssueDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ProductSubstitutes getProductSubstitutes_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ProductSubstitutes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductSubstitutes_IssueDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ProductSubstitutes.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ProductSubstitutes_IssueDetails
	 * @param productsubstitutes_issuedetails
	 */
	public final void setProductSubstitutes_IssueDetails(excr_containermanagement_api.proxies.ProductSubstitutes productsubstitutes_issuedetails)
	{
		setProductSubstitutes_IssueDetails(getContext(), productsubstitutes_issuedetails);
	}

	/**
	 * Set value of ProductSubstitutes_IssueDetails
	 * @param context
	 * @param productsubstitutes_issuedetails
	 */
	public final void setProductSubstitutes_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ProductSubstitutes productsubstitutes_issuedetails)
	{
		if (productsubstitutes_issuedetails == null) {
			getMendixObject().setValue(context, MemberNames.ProductSubstitutes_IssueDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ProductSubstitutes_IssueDetails.toString(), productsubstitutes_issuedetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RemovalHistoryDetails_IssueDetails
	 */
	public final excr_containermanagement_api.proxies.RemovalHistoryDetails getRemovalHistoryDetails_IssueDetails() throws com.mendix.core.CoreException
	{
		return getRemovalHistoryDetails_IssueDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of RemovalHistoryDetails_IssueDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.RemovalHistoryDetails getRemovalHistoryDetails_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.RemovalHistoryDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RemovalHistoryDetails_IssueDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.RemovalHistoryDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RemovalHistoryDetails_IssueDetails
	 * @param removalhistorydetails_issuedetails
	 */
	public final void setRemovalHistoryDetails_IssueDetails(excr_containermanagement_api.proxies.RemovalHistoryDetails removalhistorydetails_issuedetails)
	{
		setRemovalHistoryDetails_IssueDetails(getContext(), removalhistorydetails_issuedetails);
	}

	/**
	 * Set value of RemovalHistoryDetails_IssueDetails
	 * @param context
	 * @param removalhistorydetails_issuedetails
	 */
	public final void setRemovalHistoryDetails_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.RemovalHistoryDetails removalhistorydetails_issuedetails)
	{
		if (removalhistorydetails_issuedetails == null) {
			getMendixObject().setValue(context, MemberNames.RemovalHistoryDetails_IssueDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RemovalHistoryDetails_IssueDetails.toString(), removalhistorydetails_issuedetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UOM_IssueDetails
	 */
	public final excr_containermanagement_api.proxies.UOM getUOM_IssueDetails() throws com.mendix.core.CoreException
	{
		return getUOM_IssueDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of UOM_IssueDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.UOM getUOM_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.UOM result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UOM_IssueDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.UOM.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UOM_IssueDetails
	 * @param uom_issuedetails
	 */
	public final void setUOM_IssueDetails(excr_containermanagement_api.proxies.UOM uom_issuedetails)
	{
		setUOM_IssueDetails(getContext(), uom_issuedetails);
	}

	/**
	 * Set value of UOM_IssueDetails
	 * @param context
	 * @param uom_issuedetails
	 */
	public final void setUOM_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.UOM uom_issuedetails)
	{
		if (uom_issuedetails == null) {
			getMendixObject().setValue(context, MemberNames.UOM_IssueDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UOM_IssueDetails.toString(), uom_issuedetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UOM2_IssueDetails
	 */
	public final excr_containermanagement_api.proxies.UOM2 getUOM2_IssueDetails() throws com.mendix.core.CoreException
	{
		return getUOM2_IssueDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of UOM2_IssueDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.UOM2 getUOM2_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.UOM2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UOM2_IssueDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.UOM2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UOM2_IssueDetails
	 * @param uom2_issuedetails
	 */
	public final void setUOM2_IssueDetails(excr_containermanagement_api.proxies.UOM2 uom2_issuedetails)
	{
		setUOM2_IssueDetails(getContext(), uom2_issuedetails);
	}

	/**
	 * Set value of UOM2_IssueDetails
	 * @param context
	 * @param uom2_issuedetails
	 */
	public final void setUOM2_IssueDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.UOM2 uom2_issuedetails)
	{
		if (uom2_issuedetails == null) {
			getMendixObject().setValue(context, MemberNames.UOM2_IssueDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UOM2_IssueDetails.toString(), uom2_issuedetails.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return issueDetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.IssueDetails that = (excr_containermanagement_api.proxies.IssueDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
