// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class Parent implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject parentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.Parent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		InstanceId("InstanceId"),
		CDOTypeName("CDOTypeName"),
		Name("Name"),
		Revision("Revision"),
		UseROR("UseROR"),
		Parent_BOMLineItem("EXCR_ContainerManagement_API.Parent_BOMLineItem"),
		Parent_CalledByTransactionTask("EXCR_ContainerManagement_API.Parent_CalledByTransactionTask"),
		Parent_ESigReqDetail("EXCR_ContainerManagement_API.Parent_ESigReqDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Parent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Parent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject parentMendixObject)
	{
		if (parentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!parentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.parentMendixObject = parentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.Parent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.Parent(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.Parent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.Parent.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName()
	{
		return getCDOTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CDOTypeName.toString());
	}

	/**
	 * Set value of CDOTypeName
	 * @param cdotypename
	 */
	public final void setCDOTypeName(java.lang.String cdotypename)
	{
		setCDOTypeName(getContext(), cdotypename);
	}

	/**
	 * Set value of CDOTypeName
	 * @param context
	 * @param cdotypename
	 */
	public final void setCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cdotypename)
	{
		getMendixObject().setValue(context, MemberNames.CDOTypeName.toString(), cdotypename);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @return value of UseROR
	 */
	public final java.lang.String getUseROR()
	{
		return getUseROR(getContext());
	}

	/**
	 * @param context
	 * @return value of UseROR
	 */
	public final java.lang.String getUseROR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseROR.toString());
	}

	/**
	 * Set value of UseROR
	 * @param useror
	 */
	public final void setUseROR(java.lang.String useror)
	{
		setUseROR(getContext(), useror);
	}

	/**
	 * Set value of UseROR
	 * @param context
	 * @param useror
	 */
	public final void setUseROR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String useror)
	{
		getMendixObject().setValue(context, MemberNames.UseROR.toString(), useror);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_BOMLineItem
	 */
	public final excr_containermanagement_api.proxies.BOMLineItem getParent_BOMLineItem() throws com.mendix.core.CoreException
	{
		return getParent_BOMLineItem(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_BOMLineItem
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.BOMLineItem getParent_BOMLineItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.BOMLineItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_BOMLineItem.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.BOMLineItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_BOMLineItem
	 * @param parent_bomlineitem
	 */
	public final void setParent_BOMLineItem(excr_containermanagement_api.proxies.BOMLineItem parent_bomlineitem)
	{
		setParent_BOMLineItem(getContext(), parent_bomlineitem);
	}

	/**
	 * Set value of Parent_BOMLineItem
	 * @param context
	 * @param parent_bomlineitem
	 */
	public final void setParent_BOMLineItem(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.BOMLineItem parent_bomlineitem)
	{
		if (parent_bomlineitem == null) {
			getMendixObject().setValue(context, MemberNames.Parent_BOMLineItem.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_BOMLineItem.toString(), parent_bomlineitem.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_CalledByTransactionTask
	 */
	public final excr_containermanagement_api.proxies.CalledByTransactionTask getParent_CalledByTransactionTask() throws com.mendix.core.CoreException
	{
		return getParent_CalledByTransactionTask(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_CalledByTransactionTask
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.CalledByTransactionTask getParent_CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.CalledByTransactionTask result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_CalledByTransactionTask.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.CalledByTransactionTask.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_CalledByTransactionTask
	 * @param parent_calledbytransactiontask
	 */
	public final void setParent_CalledByTransactionTask(excr_containermanagement_api.proxies.CalledByTransactionTask parent_calledbytransactiontask)
	{
		setParent_CalledByTransactionTask(getContext(), parent_calledbytransactiontask);
	}

	/**
	 * Set value of Parent_CalledByTransactionTask
	 * @param context
	 * @param parent_calledbytransactiontask
	 */
	public final void setParent_CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.CalledByTransactionTask parent_calledbytransactiontask)
	{
		if (parent_calledbytransactiontask == null) {
			getMendixObject().setValue(context, MemberNames.Parent_CalledByTransactionTask.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_CalledByTransactionTask.toString(), parent_calledbytransactiontask.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_ESigReqDetail
	 */
	public final excr_containermanagement_api.proxies.ESigReqDetail getParent_ESigReqDetail() throws com.mendix.core.CoreException
	{
		return getParent_ESigReqDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_ESigReqDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ESigReqDetail getParent_ESigReqDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ESigReqDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_ESigReqDetail.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ESigReqDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_ESigReqDetail
	 * @param parent_esigreqdetail
	 */
	public final void setParent_ESigReqDetail(excr_containermanagement_api.proxies.ESigReqDetail parent_esigreqdetail)
	{
		setParent_ESigReqDetail(getContext(), parent_esigreqdetail);
	}

	/**
	 * Set value of Parent_ESigReqDetail
	 * @param context
	 * @param parent_esigreqdetail
	 */
	public final void setParent_ESigReqDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ESigReqDetail parent_esigreqdetail)
	{
		if (parent_esigreqdetail == null) {
			getMendixObject().setValue(context, MemberNames.Parent_ESigReqDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_ESigReqDetail.toString(), parent_esigreqdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return parentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.Parent that = (excr_containermanagement_api.proxies.Parent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
