// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqAdjustReasonListFetchRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqAdjustReasonListFetchRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqAdjustReasonListFetchRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot("EXCR_ContainerManagement_API.ReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot"),
		ReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot("EXCR_ContainerManagement_API.ReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqAdjustReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqAdjustReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqAdjustReasonListFetchRootMendixObject)
	{
		if (reqAdjustReasonListFetchRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqAdjustReasonListFetchRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqAdjustReasonListFetchRootMendixObject = reqAdjustReasonListFetchRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqAdjustReasonListFetchRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqAdjustReasonListFetchRoot(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqAdjustReasonListFetchRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqAdjustReasonListFetchRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqAdjustReasonListFetchOperation getReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqAdjustReasonListFetchOperation getReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqAdjustReasonListFetchOperation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqAdjustReasonListFetchOperation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot
	 * @param reqadjustreasonlistfetchoperation_reqadjustreasonlistfetchroot
	 */
	public final void setReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot(excr_containermanagement_api.proxies.ReqAdjustReasonListFetchOperation reqadjustreasonlistfetchoperation_reqadjustreasonlistfetchroot)
	{
		setReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot(getContext(), reqadjustreasonlistfetchoperation_reqadjustreasonlistfetchroot);
	}

	/**
	 * Set value of ReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot
	 * @param context
	 * @param reqadjustreasonlistfetchoperation_reqadjustreasonlistfetchroot
	 */
	public final void setReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqAdjustReasonListFetchOperation reqadjustreasonlistfetchoperation_reqadjustreasonlistfetchroot)
	{
		if (reqadjustreasonlistfetchoperation_reqadjustreasonlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqAdjustReasonListFetchOperation_ReqAdjustReasonListFetchRoot.toString(), reqadjustreasonlistfetchoperation_reqadjustreasonlistfetchroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqAdjustReasonListFetchServiceDetails getReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqAdjustReasonListFetchServiceDetails getReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqAdjustReasonListFetchServiceDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqAdjustReasonListFetchServiceDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot
	 * @param reqadjustreasonlistfetchservicedetails_reqadjustreasonlistfetchroot
	 */
	public final void setReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot(excr_containermanagement_api.proxies.ReqAdjustReasonListFetchServiceDetails reqadjustreasonlistfetchservicedetails_reqadjustreasonlistfetchroot)
	{
		setReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot(getContext(), reqadjustreasonlistfetchservicedetails_reqadjustreasonlistfetchroot);
	}

	/**
	 * Set value of ReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot
	 * @param context
	 * @param reqadjustreasonlistfetchservicedetails_reqadjustreasonlistfetchroot
	 */
	public final void setReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqAdjustReasonListFetchServiceDetails reqadjustreasonlistfetchservicedetails_reqadjustreasonlistfetchroot)
	{
		if (reqadjustreasonlistfetchservicedetails_reqadjustreasonlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqAdjustReasonListFetchServiceDetails_ReqAdjustReasonListFetchRoot.toString(), reqadjustreasonlistfetchservicedetails_reqadjustreasonlistfetchroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqAdjustReasonListFetchRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqAdjustReasonListFetchRoot that = (excr_containermanagement_api.proxies.ReqAdjustReasonListFetchRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
