// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqBuyReasonListFetchServiceDetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqBuyReasonListFetchServiceDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqBuyReasonListFetchServiceDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot("EXCR_ContainerManagement_API.ReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqBuyReasonListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqBuyReasonListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqBuyReasonListFetchServiceDetailsMendixObject)
	{
		if (reqBuyReasonListFetchServiceDetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqBuyReasonListFetchServiceDetailsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqBuyReasonListFetchServiceDetailsMendixObject = reqBuyReasonListFetchServiceDetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqBuyReasonListFetchServiceDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqBuyReasonListFetchServiceDetails(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqBuyReasonListFetchServiceDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqBuyReasonListFetchServiceDetails.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqBuyReasonListFetchRoot getReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqBuyReasonListFetchRoot getReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqBuyReasonListFetchRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqBuyReasonListFetchRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot
	 * @param reqbuyreasonlistfetchservicedetails_reqbuyreasonlistfetchroot
	 */
	public final void setReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot(excr_containermanagement_api.proxies.ReqBuyReasonListFetchRoot reqbuyreasonlistfetchservicedetails_reqbuyreasonlistfetchroot)
	{
		setReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot(getContext(), reqbuyreasonlistfetchservicedetails_reqbuyreasonlistfetchroot);
	}

	/**
	 * Set value of ReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot
	 * @param context
	 * @param reqbuyreasonlistfetchservicedetails_reqbuyreasonlistfetchroot
	 */
	public final void setReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqBuyReasonListFetchRoot reqbuyreasonlistfetchservicedetails_reqbuyreasonlistfetchroot)
	{
		if (reqbuyreasonlistfetchservicedetails_reqbuyreasonlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqBuyReasonListFetchServiceDetails_ReqBuyReasonListFetchRoot.toString(), reqbuyreasonlistfetchservicedetails_reqbuyreasonlistfetchroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqBuyReasonListFetchServiceDetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqBuyReasonListFetchServiceDetails that = (excr_containermanagement_api.proxies.ReqBuyReasonListFetchServiceDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
