// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqContainerReleasesTxnContainers implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerReleasesTxnContainersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqContainerReleasesTxnContainers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot("EXCR_ContainerManagement_API.ReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerReleasesTxnContainers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerReleasesTxnContainers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerReleasesTxnContainersMendixObject)
	{
		if (reqContainerReleasesTxnContainersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerReleasesTxnContainersMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerReleasesTxnContainersMendixObject = reqContainerReleasesTxnContainersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqContainerReleasesTxnContainers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqContainerReleasesTxnContainers(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqContainerReleasesTxnContainers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqContainerReleasesTxnContainers.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot
	 */
	public final excr_containermanagement_api.proxies.ReqContainerReleasesTxnRoot getReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqContainerReleasesTxnRoot getReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqContainerReleasesTxnRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqContainerReleasesTxnRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot
	 * @param reqcontainerreleasestxncontainers_reqcontainerreleasestxnroot
	 */
	public final void setReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot(excr_containermanagement_api.proxies.ReqContainerReleasesTxnRoot reqcontainerreleasestxncontainers_reqcontainerreleasestxnroot)
	{
		setReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot(getContext(), reqcontainerreleasestxncontainers_reqcontainerreleasestxnroot);
	}

	/**
	 * Set value of ReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot
	 * @param context
	 * @param reqcontainerreleasestxncontainers_reqcontainerreleasestxnroot
	 */
	public final void setReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqContainerReleasesTxnRoot reqcontainerreleasestxncontainers_reqcontainerreleasestxnroot)
	{
		if (reqcontainerreleasestxncontainers_reqcontainerreleasestxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerReleasesTxnContainers_ReqContainerReleasesTxnRoot.toString(), reqcontainerreleasestxncontainers_reqcontainerreleasestxnroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerReleasesTxnContainersMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqContainerReleasesTxnContainers that = (excr_containermanagement_api.proxies.ReqContainerReleasesTxnContainers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
