// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqChangeQtyTypeListFetchServiceDetailsData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqChangeQtyTypeListFetchServiceDetailsDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqChangeQtyTypeListFetchServiceDetailsData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails("EXCR_ContainerManagement_API.ReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqChangeQtyTypeListFetchServiceDetailsData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqChangeQtyTypeListFetchServiceDetailsData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqChangeQtyTypeListFetchServiceDetailsDataMendixObject)
	{
		if (reqChangeQtyTypeListFetchServiceDetailsDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqChangeQtyTypeListFetchServiceDetailsDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqChangeQtyTypeListFetchServiceDetailsDataMendixObject = reqChangeQtyTypeListFetchServiceDetailsDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetailsData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetailsData(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetailsData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetailsData.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails
	 */
	public final excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails getReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails() throws com.mendix.core.CoreException
	{
		return getReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails getReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails
	 * @param reqchangeqtytypelistfetchservicedetailsdata_reqchangeqtytypelistfetchservicedetails
	 */
	public final void setReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails(excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails reqchangeqtytypelistfetchservicedetailsdata_reqchangeqtytypelistfetchservicedetails)
	{
		setReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails(getContext(), reqchangeqtytypelistfetchservicedetailsdata_reqchangeqtytypelistfetchservicedetails);
	}

	/**
	 * Set value of ReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails
	 * @param context
	 * @param reqchangeqtytypelistfetchservicedetailsdata_reqchangeqtytypelistfetchservicedetails
	 */
	public final void setReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails reqchangeqtytypelistfetchservicedetailsdata_reqchangeqtytypelistfetchservicedetails)
	{
		if (reqchangeqtytypelistfetchservicedetailsdata_reqchangeqtytypelistfetchservicedetails == null) {
			getMendixObject().setValue(context, MemberNames.ReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqChangeQtyTypeListFetchServiceDetailsData_ReqChangeQtyTypeListFetchServiceDetails.toString(), reqchangeqtytypelistfetchservicedetailsdata_reqchangeqtytypelistfetchservicedetails.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqChangeQtyTypeListFetchServiceDetailsDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetailsData that = (excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetailsData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
