// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqComponentIssueProduct implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqComponentIssueProductMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqComponentIssueProduct";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Revision("Revision"),
		ReqComponentIssueProduct_ReqComponentIssueActualDetail("EXCR_ContainerManagement_API.ReqComponentIssueProduct_ReqComponentIssueActualDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqComponentIssueProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqComponentIssueProduct(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqComponentIssueProductMendixObject)
	{
		if (reqComponentIssueProductMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqComponentIssueProductMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqComponentIssueProductMendixObject = reqComponentIssueProductMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqComponentIssueProduct initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqComponentIssueProduct(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqComponentIssueProduct load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqComponentIssueProduct.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqComponentIssueProduct_ReqComponentIssueActualDetail
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueActualDetail getReqComponentIssueProduct_ReqComponentIssueActualDetail() throws com.mendix.core.CoreException
	{
		return getReqComponentIssueProduct_ReqComponentIssueActualDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqComponentIssueProduct_ReqComponentIssueActualDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueActualDetail getReqComponentIssueProduct_ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqComponentIssueActualDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqComponentIssueProduct_ReqComponentIssueActualDetail.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqComponentIssueActualDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqComponentIssueProduct_ReqComponentIssueActualDetail
	 * @param reqcomponentissueproduct_reqcomponentissueactualdetail
	 */
	public final void setReqComponentIssueProduct_ReqComponentIssueActualDetail(excr_containermanagement_api.proxies.ReqComponentIssueActualDetail reqcomponentissueproduct_reqcomponentissueactualdetail)
	{
		setReqComponentIssueProduct_ReqComponentIssueActualDetail(getContext(), reqcomponentissueproduct_reqcomponentissueactualdetail);
	}

	/**
	 * Set value of ReqComponentIssueProduct_ReqComponentIssueActualDetail
	 * @param context
	 * @param reqcomponentissueproduct_reqcomponentissueactualdetail
	 */
	public final void setReqComponentIssueProduct_ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqComponentIssueActualDetail reqcomponentissueproduct_reqcomponentissueactualdetail)
	{
		if (reqcomponentissueproduct_reqcomponentissueactualdetail == null) {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueProduct_ReqComponentIssueActualDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueProduct_ReqComponentIssueActualDetail.toString(), reqcomponentissueproduct_reqcomponentissueactualdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqComponentIssueProductMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqComponentIssueProduct that = (excr_containermanagement_api.proxies.ReqComponentIssueProduct) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
