// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqChangeQtyTypeListFetchServiceDetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqChangeQtyTypeListFetchServiceDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqChangeQtyTypeListFetchServiceDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot("EXCR_ContainerManagement_API.ReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqChangeQtyTypeListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqChangeQtyTypeListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqChangeQtyTypeListFetchServiceDetailsMendixObject)
	{
		if (reqChangeQtyTypeListFetchServiceDetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqChangeQtyTypeListFetchServiceDetailsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqChangeQtyTypeListFetchServiceDetailsMendixObject = reqChangeQtyTypeListFetchServiceDetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot getReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot getReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot
	 * @param reqchangeqtytypelistfetchservicedetails_reqchangeqtytypelistfetchroot
	 */
	public final void setReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot(excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot reqchangeqtytypelistfetchservicedetails_reqchangeqtytypelistfetchroot)
	{
		setReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot(getContext(), reqchangeqtytypelistfetchservicedetails_reqchangeqtytypelistfetchroot);
	}

	/**
	 * Set value of ReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot
	 * @param context
	 * @param reqchangeqtytypelistfetchservicedetails_reqchangeqtytypelistfetchroot
	 */
	public final void setReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot reqchangeqtytypelistfetchservicedetails_reqchangeqtytypelistfetchroot)
	{
		if (reqchangeqtytypelistfetchservicedetails_reqchangeqtytypelistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqChangeQtyTypeListFetchServiceDetails_ReqChangeQtyTypeListFetchRoot.toString(), reqchangeqtytypelistfetchservicedetails_reqchangeqtytypelistfetchroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqChangeQtyTypeListFetchServiceDetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails that = (excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchServiceDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
