// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqContainerHoldTxnHoldReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerHoldTxnHoldReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqContainerHoldTxnHoldReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot("EXCR_ContainerManagement_API.ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerHoldTxnHoldReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerHoldTxnHoldReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerHoldTxnHoldReasonMendixObject)
	{
		if (reqContainerHoldTxnHoldReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerHoldTxnHoldReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerHoldTxnHoldReasonMendixObject = reqContainerHoldTxnHoldReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot
	 */
	public final excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot getReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot getReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot
	 * @param reqcontainerholdtxnholdreason_reqcontainerholdtxnroot
	 */
	public final void setReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot reqcontainerholdtxnholdreason_reqcontainerholdtxnroot)
	{
		setReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(getContext(), reqcontainerholdtxnholdreason_reqcontainerholdtxnroot);
	}

	/**
	 * Set value of ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot
	 * @param context
	 * @param reqcontainerholdtxnholdreason_reqcontainerholdtxnroot
	 */
	public final void setReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot reqcontainerholdtxnholdreason_reqcontainerholdtxnroot)
	{
		if (reqcontainerholdtxnholdreason_reqcontainerholdtxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot.toString(), reqcontainerholdtxnholdreason_reqcontainerholdtxnroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerHoldTxnHoldReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason that = (excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
