// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqComponentIssueTxnRoot extends excr_commons_api.proxies.ReqCommonDetailsRoot
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqComponentIssueTxnRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TaskTime("TaskTime"),
		ReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot("EXCR_ContainerManagement_API.ReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot"),
		ReqComponentIssueActualDetails_ReqComponentIssueTxnRoot("EXCR_ContainerManagement_API.ReqComponentIssueActualDetails_ReqComponentIssueTxnRoot"),
		TaskContainer_ReqComponentIssueTxnRoot("EXCR_ContainerManagement_API.TaskContainer_ReqComponentIssueTxnRoot"),
		CalledByTransactionTask_ReqComponentIssueTxnRoot("EXCR_ContainerManagement_API.CalledByTransactionTask_ReqComponentIssueTxnRoot"),
		ESigDetails_ReqCommonDetailsRoot("EXCR_Commons_API.ESigDetails_ReqCommonDetailsRoot"),
		ReqCommonDetailsRoot_ESigProcessTimerDetails("EXCR_Commons_API.ReqCommonDetailsRoot_ESigProcessTimerDetails");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqComponentIssueTxnRootMendixObject)
	{
		super(context, reqComponentIssueTxnRootMendixObject);
		if (!reqComponentIssueTxnRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot.initialize(context, mendixObject);
	}

	/**
	 * @return value of TaskTime
	 */
	public final java.math.BigDecimal getTaskTime()
	{
		return getTaskTime(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskTime
	 */
	public final java.math.BigDecimal getTaskTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TaskTime.toString());
	}

	/**
	 * Set value of TaskTime
	 * @param tasktime
	 */
	public final void setTaskTime(java.math.BigDecimal tasktime)
	{
		setTaskTime(getContext(), tasktime);
	}

	/**
	 * Set value of TaskTime
	 * @param context
	 * @param tasktime
	 */
	public final void setTaskTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal tasktime)
	{
		getMendixObject().setValue(context, MemberNames.TaskTime.toString(), tasktime);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueTxnContainer getReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueTxnContainer getReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqComponentIssueTxnContainer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqComponentIssueTxnContainer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot
	 * @param reqcomponentissuetxncontainer_reqcomponentissuetxnroot
	 */
	public final void setReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot(excr_containermanagement_api.proxies.ReqComponentIssueTxnContainer reqcomponentissuetxncontainer_reqcomponentissuetxnroot)
	{
		setReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot(getContext(), reqcomponentissuetxncontainer_reqcomponentissuetxnroot);
	}

	/**
	 * Set value of ReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot
	 * @param context
	 * @param reqcomponentissuetxncontainer_reqcomponentissuetxnroot
	 */
	public final void setReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqComponentIssueTxnContainer reqcomponentissuetxncontainer_reqcomponentissuetxnroot)
	{
		if (reqcomponentissuetxncontainer_reqcomponentissuetxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueTxnContainer_ReqComponentIssueTxnRoot.toString(), reqcomponentissuetxncontainer_reqcomponentissuetxnroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqComponentIssueActualDetails_ReqComponentIssueTxnRoot
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueActualDetails getReqComponentIssueActualDetails_ReqComponentIssueTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqComponentIssueActualDetails_ReqComponentIssueTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqComponentIssueActualDetails_ReqComponentIssueTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueActualDetails getReqComponentIssueActualDetails_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqComponentIssueActualDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqComponentIssueActualDetails_ReqComponentIssueTxnRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqComponentIssueActualDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqComponentIssueActualDetails_ReqComponentIssueTxnRoot
	 * @param reqcomponentissueactualdetails_reqcomponentissuetxnroot
	 */
	public final void setReqComponentIssueActualDetails_ReqComponentIssueTxnRoot(excr_containermanagement_api.proxies.ReqComponentIssueActualDetails reqcomponentissueactualdetails_reqcomponentissuetxnroot)
	{
		setReqComponentIssueActualDetails_ReqComponentIssueTxnRoot(getContext(), reqcomponentissueactualdetails_reqcomponentissuetxnroot);
	}

	/**
	 * Set value of ReqComponentIssueActualDetails_ReqComponentIssueTxnRoot
	 * @param context
	 * @param reqcomponentissueactualdetails_reqcomponentissuetxnroot
	 */
	public final void setReqComponentIssueActualDetails_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqComponentIssueActualDetails reqcomponentissueactualdetails_reqcomponentissuetxnroot)
	{
		if (reqcomponentissueactualdetails_reqcomponentissuetxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueActualDetails_ReqComponentIssueTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueActualDetails_ReqComponentIssueTxnRoot.toString(), reqcomponentissueactualdetails_reqcomponentissuetxnroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskContainer_ReqComponentIssueTxnRoot
	 */
	public final excr_containermanagement_api.proxies.TaskContainer getTaskContainer_ReqComponentIssueTxnRoot() throws com.mendix.core.CoreException
	{
		return getTaskContainer_ReqComponentIssueTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskContainer_ReqComponentIssueTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.TaskContainer getTaskContainer_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.TaskContainer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskContainer_ReqComponentIssueTxnRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.TaskContainer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskContainer_ReqComponentIssueTxnRoot
	 * @param taskcontainer_reqcomponentissuetxnroot
	 */
	public final void setTaskContainer_ReqComponentIssueTxnRoot(excr_containermanagement_api.proxies.TaskContainer taskcontainer_reqcomponentissuetxnroot)
	{
		setTaskContainer_ReqComponentIssueTxnRoot(getContext(), taskcontainer_reqcomponentissuetxnroot);
	}

	/**
	 * Set value of TaskContainer_ReqComponentIssueTxnRoot
	 * @param context
	 * @param taskcontainer_reqcomponentissuetxnroot
	 */
	public final void setTaskContainer_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.TaskContainer taskcontainer_reqcomponentissuetxnroot)
	{
		if (taskcontainer_reqcomponentissuetxnroot == null) {
			getMendixObject().setValue(context, MemberNames.TaskContainer_ReqComponentIssueTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskContainer_ReqComponentIssueTxnRoot.toString(), taskcontainer_reqcomponentissuetxnroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CalledByTransactionTask_ReqComponentIssueTxnRoot
	 */
	public final excr_containermanagement_api.proxies.CalledByTransactionTask getCalledByTransactionTask_ReqComponentIssueTxnRoot() throws com.mendix.core.CoreException
	{
		return getCalledByTransactionTask_ReqComponentIssueTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of CalledByTransactionTask_ReqComponentIssueTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.CalledByTransactionTask getCalledByTransactionTask_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.CalledByTransactionTask result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CalledByTransactionTask_ReqComponentIssueTxnRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.CalledByTransactionTask.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CalledByTransactionTask_ReqComponentIssueTxnRoot
	 * @param calledbytransactiontask_reqcomponentissuetxnroot
	 */
	public final void setCalledByTransactionTask_ReqComponentIssueTxnRoot(excr_containermanagement_api.proxies.CalledByTransactionTask calledbytransactiontask_reqcomponentissuetxnroot)
	{
		setCalledByTransactionTask_ReqComponentIssueTxnRoot(getContext(), calledbytransactiontask_reqcomponentissuetxnroot);
	}

	/**
	 * Set value of CalledByTransactionTask_ReqComponentIssueTxnRoot
	 * @param context
	 * @param calledbytransactiontask_reqcomponentissuetxnroot
	 */
	public final void setCalledByTransactionTask_ReqComponentIssueTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.CalledByTransactionTask calledbytransactiontask_reqcomponentissuetxnroot)
	{
		if (calledbytransactiontask_reqcomponentissuetxnroot == null) {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqComponentIssueTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqComponentIssueTxnRoot.toString(), calledbytransactiontask_reqcomponentissuetxnroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot that = (excr_containermanagement_api.proxies.ReqComponentIssueTxnRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
