// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqContainerSplitFactory implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerSplitFactoryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqContainerSplitFactory";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ReqContainerSplitFactory_ReqContainerSplitRoot("EXCR_ContainerManagement_API.ReqContainerSplitFactory_ReqContainerSplitRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerSplitFactory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerSplitFactory(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerSplitFactoryMendixObject)
	{
		if (reqContainerSplitFactoryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerSplitFactoryMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerSplitFactoryMendixObject = reqContainerSplitFactoryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqContainerSplitFactory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqContainerSplitFactory(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqContainerSplitFactory load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqContainerSplitFactory.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerSplitFactory_ReqContainerSplitRoot
	 */
	public final excr_containermanagement_api.proxies.ReqContainerSplitRoot getReqContainerSplitFactory_ReqContainerSplitRoot() throws com.mendix.core.CoreException
	{
		return getReqContainerSplitFactory_ReqContainerSplitRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerSplitFactory_ReqContainerSplitRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqContainerSplitRoot getReqContainerSplitFactory_ReqContainerSplitRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqContainerSplitRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerSplitFactory_ReqContainerSplitRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqContainerSplitRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerSplitFactory_ReqContainerSplitRoot
	 * @param reqcontainersplitfactory_reqcontainersplitroot
	 */
	public final void setReqContainerSplitFactory_ReqContainerSplitRoot(excr_containermanagement_api.proxies.ReqContainerSplitRoot reqcontainersplitfactory_reqcontainersplitroot)
	{
		setReqContainerSplitFactory_ReqContainerSplitRoot(getContext(), reqcontainersplitfactory_reqcontainersplitroot);
	}

	/**
	 * Set value of ReqContainerSplitFactory_ReqContainerSplitRoot
	 * @param context
	 * @param reqcontainersplitfactory_reqcontainersplitroot
	 */
	public final void setReqContainerSplitFactory_ReqContainerSplitRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqContainerSplitRoot reqcontainersplitfactory_reqcontainersplitroot)
	{
		if (reqcontainersplitfactory_reqcontainersplitroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerSplitFactory_ReqContainerSplitRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerSplitFactory_ReqContainerSplitRoot.toString(), reqcontainersplitfactory_reqcontainersplitroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerSplitFactoryMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqContainerSplitFactory that = (excr_containermanagement_api.proxies.ReqContainerSplitFactory) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
