// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqChangeQtyTypeListFetchContainer implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqChangeQtyTypeListFetchContainerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqChangeQtyTypeListFetchContainer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot("EXCR_ContainerManagement_API.ReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot"),
		ReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext("EXCR_ContainerManagement_API.ReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqChangeQtyTypeListFetchContainer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqChangeQtyTypeListFetchContainer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqChangeQtyTypeListFetchContainerMendixObject)
	{
		if (reqChangeQtyTypeListFetchContainerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqChangeQtyTypeListFetchContainerMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqChangeQtyTypeListFetchContainerMendixObject = reqChangeQtyTypeListFetchContainerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchContainer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchContainer(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchContainer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchContainer.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot getReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot getReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot
	 * @param reqchangeqtytypelistfetchcontainer_reqchangeqtytypelistfetchroot
	 */
	public final void setReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot(excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot reqchangeqtytypelistfetchcontainer_reqchangeqtytypelistfetchroot)
	{
		setReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot(getContext(), reqchangeqtytypelistfetchcontainer_reqchangeqtytypelistfetchroot);
	}

	/**
	 * Set value of ReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot
	 * @param context
	 * @param reqchangeqtytypelistfetchcontainer_reqchangeqtytypelistfetchroot
	 */
	public final void setReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchRoot reqchangeqtytypelistfetchcontainer_reqchangeqtytypelistfetchroot)
	{
		if (reqchangeqtytypelistfetchcontainer_reqchangeqtytypelistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqChangeQtyTypeListFetchContainer_ReqChangeQtyTypeListFetchRoot.toString(), reqchangeqtytypelistfetchcontainer_reqchangeqtytypelistfetchroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext
	 */
	public final excr_resourcemanagement.proxies.ContainerChangeQtyContext getReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext() throws com.mendix.core.CoreException
	{
		return getReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ContainerChangeQtyContext getReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ContainerChangeQtyContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ContainerChangeQtyContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext
	 * @param reqchangeqtytypelistfetchcontainer_containerchangeqtycontext
	 */
	public final void setReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext(excr_resourcemanagement.proxies.ContainerChangeQtyContext reqchangeqtytypelistfetchcontainer_containerchangeqtycontext)
	{
		setReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext(getContext(), reqchangeqtytypelistfetchcontainer_containerchangeqtycontext);
	}

	/**
	 * Set value of ReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext
	 * @param context
	 * @param reqchangeqtytypelistfetchcontainer_containerchangeqtycontext
	 */
	public final void setReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ContainerChangeQtyContext reqchangeqtytypelistfetchcontainer_containerchangeqtycontext)
	{
		if (reqchangeqtytypelistfetchcontainer_containerchangeqtycontext == null) {
			getMendixObject().setValue(context, MemberNames.ReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqChangeQtyTypeListFetchContainer_ContainerChangeQtyContext.toString(), reqchangeqtytypelistfetchcontainer_containerchangeqtycontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqChangeQtyTypeListFetchContainerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchContainer that = (excr_containermanagement_api.proxies.ReqChangeQtyTypeListFetchContainer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
