// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqContainerSplitToContainerDetailList implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerSplitToContainerDetailListMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqContainerSplitToContainerDetailList";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqContainerSplitToContainerDetailList_ReqContainerSplitRoot("EXCR_ContainerManagement_API.ReqContainerSplitToContainerDetailList_ReqContainerSplitRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerSplitToContainerDetailList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerSplitToContainerDetailList(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerSplitToContainerDetailListMendixObject)
	{
		if (reqContainerSplitToContainerDetailListMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerSplitToContainerDetailListMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerSplitToContainerDetailListMendixObject = reqContainerSplitToContainerDetailListMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqContainerSplitToContainerDetailList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqContainerSplitToContainerDetailList(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqContainerSplitToContainerDetailList load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqContainerSplitToContainerDetailList.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerSplitToContainerDetailList_ReqContainerSplitRoot
	 */
	public final excr_containermanagement_api.proxies.ReqContainerSplitRoot getReqContainerSplitToContainerDetailList_ReqContainerSplitRoot() throws com.mendix.core.CoreException
	{
		return getReqContainerSplitToContainerDetailList_ReqContainerSplitRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerSplitToContainerDetailList_ReqContainerSplitRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqContainerSplitRoot getReqContainerSplitToContainerDetailList_ReqContainerSplitRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqContainerSplitRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerSplitToContainerDetailList_ReqContainerSplitRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqContainerSplitRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerSplitToContainerDetailList_ReqContainerSplitRoot
	 * @param reqcontainersplittocontainerdetaillist_reqcontainersplitroot
	 */
	public final void setReqContainerSplitToContainerDetailList_ReqContainerSplitRoot(excr_containermanagement_api.proxies.ReqContainerSplitRoot reqcontainersplittocontainerdetaillist_reqcontainersplitroot)
	{
		setReqContainerSplitToContainerDetailList_ReqContainerSplitRoot(getContext(), reqcontainersplittocontainerdetaillist_reqcontainersplitroot);
	}

	/**
	 * Set value of ReqContainerSplitToContainerDetailList_ReqContainerSplitRoot
	 * @param context
	 * @param reqcontainersplittocontainerdetaillist_reqcontainersplitroot
	 */
	public final void setReqContainerSplitToContainerDetailList_ReqContainerSplitRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqContainerSplitRoot reqcontainersplittocontainerdetaillist_reqcontainersplitroot)
	{
		if (reqcontainersplittocontainerdetaillist_reqcontainersplitroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerSplitToContainerDetailList_ReqContainerSplitRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerSplitToContainerDetailList_ReqContainerSplitRoot.toString(), reqcontainersplittocontainerdetaillist_reqcontainersplitroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerSplitToContainerDetailListMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqContainerSplitToContainerDetailList that = (excr_containermanagement_api.proxies.ReqContainerSplitToContainerDetailList) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
