// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqComponentIssueActualDetail implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqComponentIssueActualDetailMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqComponentIssueActualDetail";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		QtyIssued("QtyIssued"),
		FromLot("FromLot"),
		FromStockPoint("FromStockPoint"),
		EnteredQtyIssued("EnteredQtyIssued"),
		ReqComponentIssueActualDetail_ReqComponentIssueActualDetails("EXCR_ContainerManagement_API.ReqComponentIssueActualDetail_ReqComponentIssueActualDetails"),
		ReqComponentIssueFromContainer_ReqComponentIssueActualDetail("EXCR_ContainerManagement_API.ReqComponentIssueFromContainer_ReqComponentIssueActualDetail"),
		ReqComponentIssueProduct_ReqComponentIssueActualDetail("EXCR_ContainerManagement_API.ReqComponentIssueProduct_ReqComponentIssueActualDetail"),
		ReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail("EXCR_ContainerManagement_API.ReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqComponentIssueActualDetailMendixObject)
	{
		if (reqComponentIssueActualDetailMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqComponentIssueActualDetailMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqComponentIssueActualDetailMendixObject = reqComponentIssueActualDetailMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqComponentIssueActualDetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqComponentIssueActualDetail(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqComponentIssueActualDetail load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqComponentIssueActualDetail.initialize(context, mendixObject);
	}

	/**
	 * @return value of QtyIssued
	 */
	public final java.math.BigDecimal getQtyIssued()
	{
		return getQtyIssued(getContext());
	}

	/**
	 * @param context
	 * @return value of QtyIssued
	 */
	public final java.math.BigDecimal getQtyIssued(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.QtyIssued.toString());
	}

	/**
	 * Set value of QtyIssued
	 * @param qtyissued
	 */
	public final void setQtyIssued(java.math.BigDecimal qtyissued)
	{
		setQtyIssued(getContext(), qtyissued);
	}

	/**
	 * Set value of QtyIssued
	 * @param context
	 * @param qtyissued
	 */
	public final void setQtyIssued(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal qtyissued)
	{
		getMendixObject().setValue(context, MemberNames.QtyIssued.toString(), qtyissued);
	}

	/**
	 * @return value of FromLot
	 */
	public final java.lang.String getFromLot()
	{
		return getFromLot(getContext());
	}

	/**
	 * @param context
	 * @return value of FromLot
	 */
	public final java.lang.String getFromLot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FromLot.toString());
	}

	/**
	 * Set value of FromLot
	 * @param fromlot
	 */
	public final void setFromLot(java.lang.String fromlot)
	{
		setFromLot(getContext(), fromlot);
	}

	/**
	 * Set value of FromLot
	 * @param context
	 * @param fromlot
	 */
	public final void setFromLot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fromlot)
	{
		getMendixObject().setValue(context, MemberNames.FromLot.toString(), fromlot);
	}

	/**
	 * @return value of FromStockPoint
	 */
	public final java.lang.String getFromStockPoint()
	{
		return getFromStockPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of FromStockPoint
	 */
	public final java.lang.String getFromStockPoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FromStockPoint.toString());
	}

	/**
	 * Set value of FromStockPoint
	 * @param fromstockpoint
	 */
	public final void setFromStockPoint(java.lang.String fromstockpoint)
	{
		setFromStockPoint(getContext(), fromstockpoint);
	}

	/**
	 * Set value of FromStockPoint
	 * @param context
	 * @param fromstockpoint
	 */
	public final void setFromStockPoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fromstockpoint)
	{
		getMendixObject().setValue(context, MemberNames.FromStockPoint.toString(), fromstockpoint);
	}

	/**
	 * @return value of EnteredQtyIssued
	 */
	public final java.lang.String getEnteredQtyIssued()
	{
		return getEnteredQtyIssued(getContext());
	}

	/**
	 * @param context
	 * @return value of EnteredQtyIssued
	 */
	public final java.lang.String getEnteredQtyIssued(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EnteredQtyIssued.toString());
	}

	/**
	 * Set value of EnteredQtyIssued
	 * @param enteredqtyissued
	 */
	public final void setEnteredQtyIssued(java.lang.String enteredqtyissued)
	{
		setEnteredQtyIssued(getContext(), enteredqtyissued);
	}

	/**
	 * Set value of EnteredQtyIssued
	 * @param context
	 * @param enteredqtyissued
	 */
	public final void setEnteredQtyIssued(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String enteredqtyissued)
	{
		getMendixObject().setValue(context, MemberNames.EnteredQtyIssued.toString(), enteredqtyissued);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqComponentIssueActualDetail_ReqComponentIssueActualDetails
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueActualDetails getReqComponentIssueActualDetail_ReqComponentIssueActualDetails() throws com.mendix.core.CoreException
	{
		return getReqComponentIssueActualDetail_ReqComponentIssueActualDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqComponentIssueActualDetail_ReqComponentIssueActualDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueActualDetails getReqComponentIssueActualDetail_ReqComponentIssueActualDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqComponentIssueActualDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqComponentIssueActualDetail_ReqComponentIssueActualDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqComponentIssueActualDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqComponentIssueActualDetail_ReqComponentIssueActualDetails
	 * @param reqcomponentissueactualdetail_reqcomponentissueactualdetails
	 */
	public final void setReqComponentIssueActualDetail_ReqComponentIssueActualDetails(excr_containermanagement_api.proxies.ReqComponentIssueActualDetails reqcomponentissueactualdetail_reqcomponentissueactualdetails)
	{
		setReqComponentIssueActualDetail_ReqComponentIssueActualDetails(getContext(), reqcomponentissueactualdetail_reqcomponentissueactualdetails);
	}

	/**
	 * Set value of ReqComponentIssueActualDetail_ReqComponentIssueActualDetails
	 * @param context
	 * @param reqcomponentissueactualdetail_reqcomponentissueactualdetails
	 */
	public final void setReqComponentIssueActualDetail_ReqComponentIssueActualDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqComponentIssueActualDetails reqcomponentissueactualdetail_reqcomponentissueactualdetails)
	{
		if (reqcomponentissueactualdetail_reqcomponentissueactualdetails == null) {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueActualDetail_ReqComponentIssueActualDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueActualDetail_ReqComponentIssueActualDetails.toString(), reqcomponentissueactualdetail_reqcomponentissueactualdetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqComponentIssueFromContainer_ReqComponentIssueActualDetail
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueFromContainer getReqComponentIssueFromContainer_ReqComponentIssueActualDetail() throws com.mendix.core.CoreException
	{
		return getReqComponentIssueFromContainer_ReqComponentIssueActualDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqComponentIssueFromContainer_ReqComponentIssueActualDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueFromContainer getReqComponentIssueFromContainer_ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqComponentIssueFromContainer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqComponentIssueFromContainer_ReqComponentIssueActualDetail.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqComponentIssueFromContainer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqComponentIssueFromContainer_ReqComponentIssueActualDetail
	 * @param reqcomponentissuefromcontainer_reqcomponentissueactualdetail
	 */
	public final void setReqComponentIssueFromContainer_ReqComponentIssueActualDetail(excr_containermanagement_api.proxies.ReqComponentIssueFromContainer reqcomponentissuefromcontainer_reqcomponentissueactualdetail)
	{
		setReqComponentIssueFromContainer_ReqComponentIssueActualDetail(getContext(), reqcomponentissuefromcontainer_reqcomponentissueactualdetail);
	}

	/**
	 * Set value of ReqComponentIssueFromContainer_ReqComponentIssueActualDetail
	 * @param context
	 * @param reqcomponentissuefromcontainer_reqcomponentissueactualdetail
	 */
	public final void setReqComponentIssueFromContainer_ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqComponentIssueFromContainer reqcomponentissuefromcontainer_reqcomponentissueactualdetail)
	{
		if (reqcomponentissuefromcontainer_reqcomponentissueactualdetail == null) {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueFromContainer_ReqComponentIssueActualDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueFromContainer_ReqComponentIssueActualDetail.toString(), reqcomponentissuefromcontainer_reqcomponentissueactualdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqComponentIssueProduct_ReqComponentIssueActualDetail
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueProduct getReqComponentIssueProduct_ReqComponentIssueActualDetail() throws com.mendix.core.CoreException
	{
		return getReqComponentIssueProduct_ReqComponentIssueActualDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqComponentIssueProduct_ReqComponentIssueActualDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueProduct getReqComponentIssueProduct_ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqComponentIssueProduct result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqComponentIssueProduct_ReqComponentIssueActualDetail.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqComponentIssueProduct.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqComponentIssueProduct_ReqComponentIssueActualDetail
	 * @param reqcomponentissueproduct_reqcomponentissueactualdetail
	 */
	public final void setReqComponentIssueProduct_ReqComponentIssueActualDetail(excr_containermanagement_api.proxies.ReqComponentIssueProduct reqcomponentissueproduct_reqcomponentissueactualdetail)
	{
		setReqComponentIssueProduct_ReqComponentIssueActualDetail(getContext(), reqcomponentissueproduct_reqcomponentissueactualdetail);
	}

	/**
	 * Set value of ReqComponentIssueProduct_ReqComponentIssueActualDetail
	 * @param context
	 * @param reqcomponentissueproduct_reqcomponentissueactualdetail
	 */
	public final void setReqComponentIssueProduct_ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqComponentIssueProduct reqcomponentissueproduct_reqcomponentissueactualdetail)
	{
		if (reqcomponentissueproduct_reqcomponentissueactualdetail == null) {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueProduct_ReqComponentIssueActualDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueProduct_ReqComponentIssueActualDetail.toString(), reqcomponentissueproduct_reqcomponentissueactualdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueDifferenceReason getReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail() throws com.mendix.core.CoreException
	{
		return getReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqComponentIssueDifferenceReason getReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqComponentIssueDifferenceReason result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqComponentIssueDifferenceReason.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail
	 * @param reqcomponentissuedifferencereason_reqcomponentissueactualdetail
	 */
	public final void setReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail(excr_containermanagement_api.proxies.ReqComponentIssueDifferenceReason reqcomponentissuedifferencereason_reqcomponentissueactualdetail)
	{
		setReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail(getContext(), reqcomponentissuedifferencereason_reqcomponentissueactualdetail);
	}

	/**
	 * Set value of ReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail
	 * @param context
	 * @param reqcomponentissuedifferencereason_reqcomponentissueactualdetail
	 */
	public final void setReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqComponentIssueDifferenceReason reqcomponentissuedifferencereason_reqcomponentissueactualdetail)
	{
		if (reqcomponentissuedifferencereason_reqcomponentissueactualdetail == null) {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqComponentIssueDifferenceReason_ReqComponentIssueActualDetail.toString(), reqcomponentissuedifferencereason_reqcomponentissueactualdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqComponentIssueActualDetailMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqComponentIssueActualDetail that = (excr_containermanagement_api.proxies.ReqComponentIssueActualDetail) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
