// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqContainerHoldTxnRoot extends excr_commons_api.proxies.ReqCommonDetailsRoot
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqContainerHoldTxnRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Comments("Comments"),
		HoldMessage("HoldMessage"),
		ReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot("EXCR_ContainerManagement_API.ReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot"),
		ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot("EXCR_ContainerManagement_API.ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot"),
		ESigDetails_ReqCommonDetailsRoot("EXCR_Commons_API.ESigDetails_ReqCommonDetailsRoot"),
		ReqCommonDetailsRoot_ESigProcessTimerDetails("EXCR_Commons_API.ReqCommonDetailsRoot_ESigProcessTimerDetails");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerHoldTxnRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerHoldTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerHoldTxnRootMendixObject)
	{
		super(context, reqContainerHoldTxnRootMendixObject);
		if (!reqContainerHoldTxnRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot.initialize(context, mendixObject);
	}

	/**
	 * @return value of Comments
	 */
	public final java.lang.String getComments()
	{
		return getComments(getContext());
	}

	/**
	 * @param context
	 * @return value of Comments
	 */
	public final java.lang.String getComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comments.toString());
	}

	/**
	 * Set value of Comments
	 * @param comments
	 */
	public final void setComments(java.lang.String comments)
	{
		setComments(getContext(), comments);
	}

	/**
	 * Set value of Comments
	 * @param context
	 * @param comments
	 */
	public final void setComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comments)
	{
		getMendixObject().setValue(context, MemberNames.Comments.toString(), comments);
	}

	/**
	 * @return value of HoldMessage
	 */
	public final java.lang.String getHoldMessage()
	{
		return getHoldMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldMessage
	 */
	public final java.lang.String getHoldMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldMessage.toString());
	}

	/**
	 * Set value of HoldMessage
	 * @param holdmessage
	 */
	public final void setHoldMessage(java.lang.String holdmessage)
	{
		setHoldMessage(getContext(), holdmessage);
	}

	/**
	 * Set value of HoldMessage
	 * @param context
	 * @param holdmessage
	 */
	public final void setHoldMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdmessage)
	{
		getMendixObject().setValue(context, MemberNames.HoldMessage.toString(), holdmessage);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot
	 */
	public final excr_containermanagement_api.proxies.ReqContainerHoldTxnContainer getReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqContainerHoldTxnContainer getReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqContainerHoldTxnContainer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqContainerHoldTxnContainer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot
	 * @param reqcontainerholdtxncontainer_reqcontainerholdtxnroot
	 */
	public final void setReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot(excr_containermanagement_api.proxies.ReqContainerHoldTxnContainer reqcontainerholdtxncontainer_reqcontainerholdtxnroot)
	{
		setReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot(getContext(), reqcontainerholdtxncontainer_reqcontainerholdtxnroot);
	}

	/**
	 * Set value of ReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot
	 * @param context
	 * @param reqcontainerholdtxncontainer_reqcontainerholdtxnroot
	 */
	public final void setReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqContainerHoldTxnContainer reqcontainerholdtxncontainer_reqcontainerholdtxnroot)
	{
		if (reqcontainerholdtxncontainer_reqcontainerholdtxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerHoldTxnContainer_ReqContainerHoldTxnRoot.toString(), reqcontainerholdtxncontainer_reqcontainerholdtxnroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot
	 */
	public final excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason getReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason getReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot
	 * @param reqcontainerholdtxnholdreason_reqcontainerholdtxnroot
	 */
	public final void setReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason reqcontainerholdtxnholdreason_reqcontainerholdtxnroot)
	{
		setReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(getContext(), reqcontainerholdtxnholdreason_reqcontainerholdtxnroot);
	}

	/**
	 * Set value of ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot
	 * @param context
	 * @param reqcontainerholdtxnholdreason_reqcontainerholdtxnroot
	 */
	public final void setReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqContainerHoldTxnHoldReason reqcontainerholdtxnholdreason_reqcontainerholdtxnroot)
	{
		if (reqcontainerholdtxnholdreason_reqcontainerholdtxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerHoldTxnHoldReason_ReqContainerHoldTxnRoot.toString(), reqcontainerholdtxnholdreason_reqcontainerholdtxnroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot that = (excr_containermanagement_api.proxies.ReqContainerHoldTxnRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
