// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqDataCollectionColumnListFetchInputData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqDataCollectionColumnListFetchInputDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqDataCollectionColumnListFetchInputData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot("EXCR_ContainerManagement_API.ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot"),
		ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData("EXCR_ContainerManagement_API.ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData"),
		ReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData("EXCR_ContainerManagement_API.ReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqDataCollectionColumnListFetchInputData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqDataCollectionColumnListFetchInputData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqDataCollectionColumnListFetchInputDataMendixObject)
	{
		if (reqDataCollectionColumnListFetchInputDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqDataCollectionColumnListFetchInputDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqDataCollectionColumnListFetchInputDataMendixObject = reqDataCollectionColumnListFetchInputDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot getReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot getReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot
	 * @param reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot
	 */
	public final void setReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot)
	{
		setReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(getContext(), reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot);
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot
	 * @param context
	 * @param reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot
	 */
	public final void setReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot)
	{
		if (reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot.toString(), reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer getReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData() throws com.mendix.core.CoreException
	{
		return getReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer getReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData
	 * @param reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata
	 */
	public final void setReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata)
	{
		setReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(getContext(), reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata);
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData
	 * @param context
	 * @param reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata
	 */
	public final void setReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata)
	{
		if (reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata == null) {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData.toString(), reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchDataCollectionDef getReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData() throws com.mendix.core.CoreException
	{
		return getReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchDataCollectionDef getReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchDataCollectionDef result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchDataCollectionDef.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData
	 * @param reqdatacollectioncolumnlistfetchdatacollectiondef_reqdatacollectioncolumnlistfetchinputdata
	 */
	public final void setReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData(excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchDataCollectionDef reqdatacollectioncolumnlistfetchdatacollectiondef_reqdatacollectioncolumnlistfetchinputdata)
	{
		setReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData(getContext(), reqdatacollectioncolumnlistfetchdatacollectiondef_reqdatacollectioncolumnlistfetchinputdata);
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData
	 * @param context
	 * @param reqdatacollectioncolumnlistfetchdatacollectiondef_reqdatacollectioncolumnlistfetchinputdata
	 */
	public final void setReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchDataCollectionDef reqdatacollectioncolumnlistfetchdatacollectiondef_reqdatacollectioncolumnlistfetchinputdata)
	{
		if (reqdatacollectioncolumnlistfetchdatacollectiondef_reqdatacollectioncolumnlistfetchinputdata == null) {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchDataCollectionDef_ReqDataCollectionColumnListFetchInputData.toString(), reqdatacollectioncolumnlistfetchdatacollectiondef_reqdatacollectioncolumnlistfetchinputdata.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqDataCollectionColumnListFetchInputDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData that = (excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
