// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqDataCollectionColumnListFetchContainer implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqDataCollectionColumnListFetchContainerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqDataCollectionColumnListFetchContainer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData("EXCR_ContainerManagement_API.ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqDataCollectionColumnListFetchContainer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqDataCollectionColumnListFetchContainer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqDataCollectionColumnListFetchContainerMendixObject)
	{
		if (reqDataCollectionColumnListFetchContainerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqDataCollectionColumnListFetchContainerMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqDataCollectionColumnListFetchContainerMendixObject = reqDataCollectionColumnListFetchContainerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData getReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData() throws com.mendix.core.CoreException
	{
		return getReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData getReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData
	 * @param reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata
	 */
	public final void setReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata)
	{
		setReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(getContext(), reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata);
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData
	 * @param context
	 * @param reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata
	 */
	public final void setReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata)
	{
		if (reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata == null) {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchContainer_ReqDataCollectionColumnListFetchInputData.toString(), reqdatacollectioncolumnlistfetchcontainer_reqdatacollectioncolumnlistfetchinputdata.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqDataCollectionColumnListFetchContainerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer that = (excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchContainer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
