// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqDataCollectionColumnListFetchRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqDataCollectionColumnListFetchRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqDataCollectionColumnListFetchRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot("EXCR_ContainerManagement_API.ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot"),
		ReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot("EXCR_ContainerManagement_API.ReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqDataCollectionColumnListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqDataCollectionColumnListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqDataCollectionColumnListFetchRootMendixObject)
	{
		if (reqDataCollectionColumnListFetchRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqDataCollectionColumnListFetchRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqDataCollectionColumnListFetchRootMendixObject = reqDataCollectionColumnListFetchRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData getReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData getReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot
	 * @param reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot
	 */
	public final void setReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot)
	{
		setReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(getContext(), reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot);
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot
	 * @param context
	 * @param reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot
	 */
	public final void setReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchInputData reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot)
	{
		if (reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchInputData_ReqDataCollectionColumnListFetchRoot.toString(), reqdatacollectioncolumnlistfetchinputdata_reqdatacollectioncolumnlistfetchroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchEvent getReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchEvent getReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchEvent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchEvent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot
	 * @param reqdatacollectioncolumnlistfetchevent_reqdatacollectioncolumnlistfetchroot
	 */
	public final void setReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot(excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchEvent reqdatacollectioncolumnlistfetchevent_reqdatacollectioncolumnlistfetchroot)
	{
		setReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot(getContext(), reqdatacollectioncolumnlistfetchevent_reqdatacollectioncolumnlistfetchroot);
	}

	/**
	 * Set value of ReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot
	 * @param context
	 * @param reqdatacollectioncolumnlistfetchevent_reqdatacollectioncolumnlistfetchroot
	 */
	public final void setReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchEvent reqdatacollectioncolumnlistfetchevent_reqdatacollectioncolumnlistfetchroot)
	{
		if (reqdatacollectioncolumnlistfetchevent_reqdatacollectioncolumnlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqDataCollectionColumnListFetchEvent_ReqDataCollectionColumnListFetchRoot.toString(), reqdatacollectioncolumnlistfetchevent_reqdatacollectioncolumnlistfetchroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqDataCollectionColumnListFetchRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot that = (excr_containermanagement_api.proxies.ReqDataCollectionColumnListFetchRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
