// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqLossReasonListFetchServiceDetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqLossReasonListFetchServiceDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqLossReasonListFetchServiceDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot("EXCR_ContainerManagement_API.ReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqLossReasonListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqLossReasonListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqLossReasonListFetchServiceDetailsMendixObject)
	{
		if (reqLossReasonListFetchServiceDetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqLossReasonListFetchServiceDetailsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqLossReasonListFetchServiceDetailsMendixObject = reqLossReasonListFetchServiceDetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot getReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot getReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot
	 * @param reqlossreasonlistfetchservicedetails_reqlossreasonlistfetchroot
	 */
	public final void setReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot(excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot reqlossreasonlistfetchservicedetails_reqlossreasonlistfetchroot)
	{
		setReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot(getContext(), reqlossreasonlistfetchservicedetails_reqlossreasonlistfetchroot);
	}

	/**
	 * Set value of ReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot
	 * @param context
	 * @param reqlossreasonlistfetchservicedetails_reqlossreasonlistfetchroot
	 */
	public final void setReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot reqlossreasonlistfetchservicedetails_reqlossreasonlistfetchroot)
	{
		if (reqlossreasonlistfetchservicedetails_reqlossreasonlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqLossReasonListFetchServiceDetails_ReqLossReasonListFetchRoot.toString(), reqlossreasonlistfetchservicedetails_reqlossreasonlistfetchroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqLossReasonListFetchServiceDetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails that = (excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
