// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqLossReasonListFetchOperation implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqLossReasonListFetchOperationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqLossReasonListFetchOperation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot("EXCR_ContainerManagement_API.ReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqLossReasonListFetchOperation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqLossReasonListFetchOperation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqLossReasonListFetchOperationMendixObject)
	{
		if (reqLossReasonListFetchOperationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqLossReasonListFetchOperationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqLossReasonListFetchOperationMendixObject = reqLossReasonListFetchOperationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqLossReasonListFetchOperation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqLossReasonListFetchOperation(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqLossReasonListFetchOperation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqLossReasonListFetchOperation.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot getReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot getReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot
	 * @param reqlossreasonlistfetchoperation_reqlossreasonlistfetchroot
	 */
	public final void setReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot(excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot reqlossreasonlistfetchoperation_reqlossreasonlistfetchroot)
	{
		setReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot(getContext(), reqlossreasonlistfetchoperation_reqlossreasonlistfetchroot);
	}

	/**
	 * Set value of ReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot
	 * @param context
	 * @param reqlossreasonlistfetchoperation_reqlossreasonlistfetchroot
	 */
	public final void setReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqLossReasonListFetchRoot reqlossreasonlistfetchoperation_reqlossreasonlistfetchroot)
	{
		if (reqlossreasonlistfetchoperation_reqlossreasonlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqLossReasonListFetchOperation_ReqLossReasonListFetchRoot.toString(), reqlossreasonlistfetchoperation_reqlossreasonlistfetchroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqLossReasonListFetchOperationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqLossReasonListFetchOperation that = (excr_containermanagement_api.proxies.ReqLossReasonListFetchOperation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
