// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqLossReasonListFetchServiceDetailsData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqLossReasonListFetchServiceDetailsDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqLossReasonListFetchServiceDetailsData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqLossReasonListFetchServiceDetailsDataType("ReqLossReasonListFetchServiceDetailsDataType"),
		ReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails("EXCR_ContainerManagement_API.ReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqLossReasonListFetchServiceDetailsData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqLossReasonListFetchServiceDetailsData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqLossReasonListFetchServiceDetailsDataMendixObject)
	{
		if (reqLossReasonListFetchServiceDetailsDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqLossReasonListFetchServiceDetailsDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqLossReasonListFetchServiceDetailsDataMendixObject = reqLossReasonListFetchServiceDetailsDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetailsData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetailsData(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetailsData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetailsData.initialize(context, mendixObject);
	}

	/**
	 * @return value of ReqLossReasonListFetchServiceDetailsDataType
	 */
	public final java.lang.String getReqLossReasonListFetchServiceDetailsDataType()
	{
		return getReqLossReasonListFetchServiceDetailsDataType(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqLossReasonListFetchServiceDetailsDataType
	 */
	public final java.lang.String getReqLossReasonListFetchServiceDetailsDataType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReqLossReasonListFetchServiceDetailsDataType.toString());
	}

	/**
	 * Set value of ReqLossReasonListFetchServiceDetailsDataType
	 * @param reqlossreasonlistfetchservicedetailsdatatype
	 */
	public final void setReqLossReasonListFetchServiceDetailsDataType(java.lang.String reqlossreasonlistfetchservicedetailsdatatype)
	{
		setReqLossReasonListFetchServiceDetailsDataType(getContext(), reqlossreasonlistfetchservicedetailsdatatype);
	}

	/**
	 * Set value of ReqLossReasonListFetchServiceDetailsDataType
	 * @param context
	 * @param reqlossreasonlistfetchservicedetailsdatatype
	 */
	public final void setReqLossReasonListFetchServiceDetailsDataType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reqlossreasonlistfetchservicedetailsdatatype)
	{
		getMendixObject().setValue(context, MemberNames.ReqLossReasonListFetchServiceDetailsDataType.toString(), reqlossreasonlistfetchservicedetailsdatatype);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails
	 */
	public final excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails getReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails() throws com.mendix.core.CoreException
	{
		return getReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails getReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails
	 * @param reqlossreasonlistfetchservicedetailsdata_reqlossreasonlistfetchservicedetails
	 */
	public final void setReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails(excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails reqlossreasonlistfetchservicedetailsdata_reqlossreasonlistfetchservicedetails)
	{
		setReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails(getContext(), reqlossreasonlistfetchservicedetailsdata_reqlossreasonlistfetchservicedetails);
	}

	/**
	 * Set value of ReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails
	 * @param context
	 * @param reqlossreasonlistfetchservicedetailsdata_reqlossreasonlistfetchservicedetails
	 */
	public final void setReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetails reqlossreasonlistfetchservicedetailsdata_reqlossreasonlistfetchservicedetails)
	{
		if (reqlossreasonlistfetchservicedetailsdata_reqlossreasonlistfetchservicedetails == null) {
			getMendixObject().setValue(context, MemberNames.ReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqLossReasonListFetchServiceDetailsData_ReqLossReasonListFetchServiceDetails.toString(), reqlossreasonlistfetchservicedetailsdata_reqlossreasonlistfetchservicedetails.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqLossReasonListFetchServiceDetailsDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetailsData that = (excr_containermanagement_api.proxies.ReqLossReasonListFetchServiceDetailsData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
