// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqObjectDPInputListParametricData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqObjectDPInputListParametricDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqObjectDPInputListParametricData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot("EXCR_ContainerManagement_API.ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot"),
		ReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData("EXCR_ContainerManagement_API.ReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqObjectDPInputListParametricData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqObjectDPInputListParametricData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqObjectDPInputListParametricDataMendixObject)
	{
		if (reqObjectDPInputListParametricDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqObjectDPInputListParametricDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqObjectDPInputListParametricDataMendixObject = reqObjectDPInputListParametricDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot
	 */
	public final excr_containermanagement_api.proxies.ReqObjectDPInputListRoot getReqObjectDPInputListParametricData_ReqObjectDPInputListRoot() throws com.mendix.core.CoreException
	{
		return getReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqObjectDPInputListRoot getReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqObjectDPInputListRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqObjectDPInputListRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot
	 * @param reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot
	 */
	public final void setReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(excr_containermanagement_api.proxies.ReqObjectDPInputListRoot reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot)
	{
		setReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(getContext(), reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot);
	}

	/**
	 * Set value of ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot
	 * @param context
	 * @param reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot
	 */
	public final void setReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqObjectDPInputListRoot reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot)
	{
		if (reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot.toString(), reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData
	 */
	public final excr_containermanagement_api.proxies.ReqObjectDPInputListDataPointDetailsRoot getReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData() throws com.mendix.core.CoreException
	{
		return getReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqObjectDPInputListDataPointDetailsRoot getReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqObjectDPInputListDataPointDetailsRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqObjectDPInputListDataPointDetailsRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData
	 * @param reqobjectdpinputlistdatapointdetailsroot_reqobjectdpinputlistparametricdata
	 */
	public final void setReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData(excr_containermanagement_api.proxies.ReqObjectDPInputListDataPointDetailsRoot reqobjectdpinputlistdatapointdetailsroot_reqobjectdpinputlistparametricdata)
	{
		setReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData(getContext(), reqobjectdpinputlistdatapointdetailsroot_reqobjectdpinputlistparametricdata);
	}

	/**
	 * Set value of ReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData
	 * @param context
	 * @param reqobjectdpinputlistdatapointdetailsroot_reqobjectdpinputlistparametricdata
	 */
	public final void setReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqObjectDPInputListDataPointDetailsRoot reqobjectdpinputlistdatapointdetailsroot_reqobjectdpinputlistparametricdata)
	{
		if (reqobjectdpinputlistdatapointdetailsroot_reqobjectdpinputlistparametricdata == null) {
			getMendixObject().setValue(context, MemberNames.ReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqObjectDPInputListDataPointDetailsRoot_ReqObjectDPInputListParametricData.toString(), reqobjectdpinputlistdatapointdetailsroot_reqobjectdpinputlistparametricdata.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqObjectDPInputListParametricDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData that = (excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
