// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqObjectDPInputListRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqObjectDPInputListRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqObjectDPInputListRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqObjectDPInputListContainer_ReqObjectDPInputListRoot("EXCR_ContainerManagement_API.ReqObjectDPInputListContainer_ReqObjectDPInputListRoot"),
		ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot("EXCR_ContainerManagement_API.ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqObjectDPInputListRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqObjectDPInputListRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqObjectDPInputListRootMendixObject)
	{
		if (reqObjectDPInputListRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqObjectDPInputListRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqObjectDPInputListRootMendixObject = reqObjectDPInputListRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqObjectDPInputListRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqObjectDPInputListRoot(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqObjectDPInputListRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqObjectDPInputListRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqObjectDPInputListContainer_ReqObjectDPInputListRoot
	 */
	public final excr_containermanagement_api.proxies.ReqObjectDPInputListContainer getReqObjectDPInputListContainer_ReqObjectDPInputListRoot() throws com.mendix.core.CoreException
	{
		return getReqObjectDPInputListContainer_ReqObjectDPInputListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqObjectDPInputListContainer_ReqObjectDPInputListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqObjectDPInputListContainer getReqObjectDPInputListContainer_ReqObjectDPInputListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqObjectDPInputListContainer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqObjectDPInputListContainer_ReqObjectDPInputListRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqObjectDPInputListContainer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqObjectDPInputListContainer_ReqObjectDPInputListRoot
	 * @param reqobjectdpinputlistcontainer_reqobjectdpinputlistroot
	 */
	public final void setReqObjectDPInputListContainer_ReqObjectDPInputListRoot(excr_containermanagement_api.proxies.ReqObjectDPInputListContainer reqobjectdpinputlistcontainer_reqobjectdpinputlistroot)
	{
		setReqObjectDPInputListContainer_ReqObjectDPInputListRoot(getContext(), reqobjectdpinputlistcontainer_reqobjectdpinputlistroot);
	}

	/**
	 * Set value of ReqObjectDPInputListContainer_ReqObjectDPInputListRoot
	 * @param context
	 * @param reqobjectdpinputlistcontainer_reqobjectdpinputlistroot
	 */
	public final void setReqObjectDPInputListContainer_ReqObjectDPInputListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqObjectDPInputListContainer reqobjectdpinputlistcontainer_reqobjectdpinputlistroot)
	{
		if (reqobjectdpinputlistcontainer_reqobjectdpinputlistroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqObjectDPInputListContainer_ReqObjectDPInputListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqObjectDPInputListContainer_ReqObjectDPInputListRoot.toString(), reqobjectdpinputlistcontainer_reqobjectdpinputlistroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot
	 */
	public final excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData getReqObjectDPInputListParametricData_ReqObjectDPInputListRoot() throws com.mendix.core.CoreException
	{
		return getReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData getReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot
	 * @param reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot
	 */
	public final void setReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot)
	{
		setReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(getContext(), reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot);
	}

	/**
	 * Set value of ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot
	 * @param context
	 * @param reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot
	 */
	public final void setReqObjectDPInputListParametricData_ReqObjectDPInputListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqObjectDPInputListParametricData reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot)
	{
		if (reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqObjectDPInputListParametricData_ReqObjectDPInputListRoot.toString(), reqobjectdpinputlistparametricdata_reqobjectdpinputlistroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqObjectDPInputListRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqObjectDPInputListRoot that = (excr_containermanagement_api.proxies.ReqObjectDPInputListRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
