// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ReqSellReasonListFetchRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqSellReasonListFetchRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ReqSellReasonListFetchRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot("EXCR_ContainerManagement_API.ReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot"),
		ReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot("EXCR_ContainerManagement_API.ReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqSellReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqSellReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqSellReasonListFetchRootMendixObject)
	{
		if (reqSellReasonListFetchRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqSellReasonListFetchRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqSellReasonListFetchRootMendixObject = reqSellReasonListFetchRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ReqSellReasonListFetchRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ReqSellReasonListFetchRoot(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ReqSellReasonListFetchRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ReqSellReasonListFetchRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqSellReasonListFetchOperation getReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqSellReasonListFetchOperation getReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqSellReasonListFetchOperation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqSellReasonListFetchOperation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot
	 * @param reqsellreasonlistfetchoperation_reqsellreasonlistfetchroot
	 */
	public final void setReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot(excr_containermanagement_api.proxies.ReqSellReasonListFetchOperation reqsellreasonlistfetchoperation_reqsellreasonlistfetchroot)
	{
		setReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot(getContext(), reqsellreasonlistfetchoperation_reqsellreasonlistfetchroot);
	}

	/**
	 * Set value of ReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot
	 * @param context
	 * @param reqsellreasonlistfetchoperation_reqsellreasonlistfetchroot
	 */
	public final void setReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqSellReasonListFetchOperation reqsellreasonlistfetchoperation_reqsellreasonlistfetchroot)
	{
		if (reqsellreasonlistfetchoperation_reqsellreasonlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqSellReasonListFetchOperation_ReqSellReasonListFetchRoot.toString(), reqsellreasonlistfetchoperation_reqsellreasonlistfetchroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot
	 */
	public final excr_containermanagement_api.proxies.ReqSellReasonListFetchServiceDetails getReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot() throws com.mendix.core.CoreException
	{
		return getReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ReqSellReasonListFetchServiceDetails getReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ReqSellReasonListFetchServiceDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ReqSellReasonListFetchServiceDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot
	 * @param reqsellreasonlistfetchservicedetails_reqsellreasonlistfetchroot
	 */
	public final void setReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot(excr_containermanagement_api.proxies.ReqSellReasonListFetchServiceDetails reqsellreasonlistfetchservicedetails_reqsellreasonlistfetchroot)
	{
		setReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot(getContext(), reqsellreasonlistfetchservicedetails_reqsellreasonlistfetchroot);
	}

	/**
	 * Set value of ReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot
	 * @param context
	 * @param reqsellreasonlistfetchservicedetails_reqsellreasonlistfetchroot
	 */
	public final void setReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ReqSellReasonListFetchServiceDetails reqsellreasonlistfetchservicedetails_reqsellreasonlistfetchroot)
	{
		if (reqsellreasonlistfetchservicedetails_reqsellreasonlistfetchroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqSellReasonListFetchServiceDetails_ReqSellReasonListFetchRoot.toString(), reqsellreasonlistfetchservicedetails_reqsellreasonlistfetchroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqSellReasonListFetchRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ReqSellReasonListFetchRoot that = (excr_containermanagement_api.proxies.ReqSellReasonListFetchRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
