// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ResComponentIssueMaterialsRequirement implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resComponentIssueMaterialsRequirementMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ResComponentIssueMaterialsRequirement";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaterialListItem("MaterialListItem"),
		MaterialListItemId("MaterialListItemId"),
		ComponentProduct("ComponentProduct"),
		ComponentDescription("ComponentDescription"),
		ProductRevision("ProductRevision"),
		QtyRequired("QtyRequired"),
		QtyIssued("QtyIssued"),
		IssueControl("IssueControl"),
		AssemblySequence("AssemblySequence"),
		ParentName("ParentName"),
		ParentRevision("ParentRevision"),
		PhantomBillId("PhantomBillId"),
		EffectiveFromDateGMT("EffectiveFromDateGMT"),
		EffectiveThruDateGMT("EffectiveThruDateGMT"),
		SpecId("SpecId"),
		UOM("UOM"),
		SetupQty("SetupQty"),
		VendorControl("VendorControl"),
		ReferenceDesignator("ReferenceDesignator"),
		ResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot("EXCR_ContainerManagement_API.ResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot"),
		ResComponentIssueMaterialsRequirement_ComponentIssueContext("EXCR_ContainerManagement_API.ResComponentIssueMaterialsRequirement_ComponentIssueContext"),
		ComponentIssueGridRowData_ResComponentIssueMaterialsRequirement("EXCR_ResourceManagement.ComponentIssueGridRowData_ResComponentIssueMaterialsRequirement");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResComponentIssueMaterialsRequirement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResComponentIssueMaterialsRequirement(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resComponentIssueMaterialsRequirementMendixObject)
	{
		if (resComponentIssueMaterialsRequirementMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resComponentIssueMaterialsRequirementMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resComponentIssueMaterialsRequirementMendixObject = resComponentIssueMaterialsRequirementMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirement(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirement load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirement.initialize(context, mendixObject);
	}

	/**
	 * @return value of MaterialListItem
	 */
	public final java.lang.String getMaterialListItem()
	{
		return getMaterialListItem(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialListItem
	 */
	public final java.lang.String getMaterialListItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialListItem.toString());
	}

	/**
	 * Set value of MaterialListItem
	 * @param materiallistitem
	 */
	public final void setMaterialListItem(java.lang.String materiallistitem)
	{
		setMaterialListItem(getContext(), materiallistitem);
	}

	/**
	 * Set value of MaterialListItem
	 * @param context
	 * @param materiallistitem
	 */
	public final void setMaterialListItem(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materiallistitem)
	{
		getMendixObject().setValue(context, MemberNames.MaterialListItem.toString(), materiallistitem);
	}

	/**
	 * @return value of MaterialListItemId
	 */
	public final java.lang.String getMaterialListItemId()
	{
		return getMaterialListItemId(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialListItemId
	 */
	public final java.lang.String getMaterialListItemId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialListItemId.toString());
	}

	/**
	 * Set value of MaterialListItemId
	 * @param materiallistitemid
	 */
	public final void setMaterialListItemId(java.lang.String materiallistitemid)
	{
		setMaterialListItemId(getContext(), materiallistitemid);
	}

	/**
	 * Set value of MaterialListItemId
	 * @param context
	 * @param materiallistitemid
	 */
	public final void setMaterialListItemId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materiallistitemid)
	{
		getMendixObject().setValue(context, MemberNames.MaterialListItemId.toString(), materiallistitemid);
	}

	/**
	 * @return value of ComponentProduct
	 */
	public final java.lang.String getComponentProduct()
	{
		return getComponentProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of ComponentProduct
	 */
	public final java.lang.String getComponentProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ComponentProduct.toString());
	}

	/**
	 * Set value of ComponentProduct
	 * @param componentproduct
	 */
	public final void setComponentProduct(java.lang.String componentproduct)
	{
		setComponentProduct(getContext(), componentproduct);
	}

	/**
	 * Set value of ComponentProduct
	 * @param context
	 * @param componentproduct
	 */
	public final void setComponentProduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String componentproduct)
	{
		getMendixObject().setValue(context, MemberNames.ComponentProduct.toString(), componentproduct);
	}

	/**
	 * @return value of ComponentDescription
	 */
	public final java.lang.String getComponentDescription()
	{
		return getComponentDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ComponentDescription
	 */
	public final java.lang.String getComponentDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ComponentDescription.toString());
	}

	/**
	 * Set value of ComponentDescription
	 * @param componentdescription
	 */
	public final void setComponentDescription(java.lang.String componentdescription)
	{
		setComponentDescription(getContext(), componentdescription);
	}

	/**
	 * Set value of ComponentDescription
	 * @param context
	 * @param componentdescription
	 */
	public final void setComponentDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String componentdescription)
	{
		getMendixObject().setValue(context, MemberNames.ComponentDescription.toString(), componentdescription);
	}

	/**
	 * @return value of ProductRevision
	 */
	public final java.lang.String getProductRevision()
	{
		return getProductRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductRevision
	 */
	public final java.lang.String getProductRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductRevision.toString());
	}

	/**
	 * Set value of ProductRevision
	 * @param productrevision
	 */
	public final void setProductRevision(java.lang.String productrevision)
	{
		setProductRevision(getContext(), productrevision);
	}

	/**
	 * Set value of ProductRevision
	 * @param context
	 * @param productrevision
	 */
	public final void setProductRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productrevision)
	{
		getMendixObject().setValue(context, MemberNames.ProductRevision.toString(), productrevision);
	}

	/**
	 * @return value of QtyRequired
	 */
	public final java.lang.String getQtyRequired()
	{
		return getQtyRequired(getContext());
	}

	/**
	 * @param context
	 * @return value of QtyRequired
	 */
	public final java.lang.String getQtyRequired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QtyRequired.toString());
	}

	/**
	 * Set value of QtyRequired
	 * @param qtyrequired
	 */
	public final void setQtyRequired(java.lang.String qtyrequired)
	{
		setQtyRequired(getContext(), qtyrequired);
	}

	/**
	 * Set value of QtyRequired
	 * @param context
	 * @param qtyrequired
	 */
	public final void setQtyRequired(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String qtyrequired)
	{
		getMendixObject().setValue(context, MemberNames.QtyRequired.toString(), qtyrequired);
	}

	/**
	 * @return value of QtyIssued
	 */
	public final java.lang.String getQtyIssued()
	{
		return getQtyIssued(getContext());
	}

	/**
	 * @param context
	 * @return value of QtyIssued
	 */
	public final java.lang.String getQtyIssued(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QtyIssued.toString());
	}

	/**
	 * Set value of QtyIssued
	 * @param qtyissued
	 */
	public final void setQtyIssued(java.lang.String qtyissued)
	{
		setQtyIssued(getContext(), qtyissued);
	}

	/**
	 * Set value of QtyIssued
	 * @param context
	 * @param qtyissued
	 */
	public final void setQtyIssued(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String qtyissued)
	{
		getMendixObject().setValue(context, MemberNames.QtyIssued.toString(), qtyissued);
	}

	/**
	 * @return value of IssueControl
	 */
	public final java.lang.String getIssueControl()
	{
		return getIssueControl(getContext());
	}

	/**
	 * @param context
	 * @return value of IssueControl
	 */
	public final java.lang.String getIssueControl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IssueControl.toString());
	}

	/**
	 * Set value of IssueControl
	 * @param issuecontrol
	 */
	public final void setIssueControl(java.lang.String issuecontrol)
	{
		setIssueControl(getContext(), issuecontrol);
	}

	/**
	 * Set value of IssueControl
	 * @param context
	 * @param issuecontrol
	 */
	public final void setIssueControl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issuecontrol)
	{
		getMendixObject().setValue(context, MemberNames.IssueControl.toString(), issuecontrol);
	}

	/**
	 * @return value of AssemblySequence
	 */
	public final java.lang.String getAssemblySequence()
	{
		return getAssemblySequence(getContext());
	}

	/**
	 * @param context
	 * @return value of AssemblySequence
	 */
	public final java.lang.String getAssemblySequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssemblySequence.toString());
	}

	/**
	 * Set value of AssemblySequence
	 * @param assemblysequence
	 */
	public final void setAssemblySequence(java.lang.String assemblysequence)
	{
		setAssemblySequence(getContext(), assemblysequence);
	}

	/**
	 * Set value of AssemblySequence
	 * @param context
	 * @param assemblysequence
	 */
	public final void setAssemblySequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assemblysequence)
	{
		getMendixObject().setValue(context, MemberNames.AssemblySequence.toString(), assemblysequence);
	}

	/**
	 * @return value of ParentName
	 */
	public final java.lang.String getParentName()
	{
		return getParentName(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentName
	 */
	public final java.lang.String getParentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentName.toString());
	}

	/**
	 * Set value of ParentName
	 * @param parentname
	 */
	public final void setParentName(java.lang.String parentname)
	{
		setParentName(getContext(), parentname);
	}

	/**
	 * Set value of ParentName
	 * @param context
	 * @param parentname
	 */
	public final void setParentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentname)
	{
		getMendixObject().setValue(context, MemberNames.ParentName.toString(), parentname);
	}

	/**
	 * @return value of ParentRevision
	 */
	public final java.lang.String getParentRevision()
	{
		return getParentRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentRevision
	 */
	public final java.lang.String getParentRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentRevision.toString());
	}

	/**
	 * Set value of ParentRevision
	 * @param parentrevision
	 */
	public final void setParentRevision(java.lang.String parentrevision)
	{
		setParentRevision(getContext(), parentrevision);
	}

	/**
	 * Set value of ParentRevision
	 * @param context
	 * @param parentrevision
	 */
	public final void setParentRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentrevision)
	{
		getMendixObject().setValue(context, MemberNames.ParentRevision.toString(), parentrevision);
	}

	/**
	 * @return value of PhantomBillId
	 */
	public final java.lang.String getPhantomBillId()
	{
		return getPhantomBillId(getContext());
	}

	/**
	 * @param context
	 * @return value of PhantomBillId
	 */
	public final java.lang.String getPhantomBillId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhantomBillId.toString());
	}

	/**
	 * Set value of PhantomBillId
	 * @param phantombillid
	 */
	public final void setPhantomBillId(java.lang.String phantombillid)
	{
		setPhantomBillId(getContext(), phantombillid);
	}

	/**
	 * Set value of PhantomBillId
	 * @param context
	 * @param phantombillid
	 */
	public final void setPhantomBillId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phantombillid)
	{
		getMendixObject().setValue(context, MemberNames.PhantomBillId.toString(), phantombillid);
	}

	/**
	 * @return value of EffectiveFromDateGMT
	 */
	public final java.lang.String getEffectiveFromDateGMT()
	{
		return getEffectiveFromDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of EffectiveFromDateGMT
	 */
	public final java.lang.String getEffectiveFromDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EffectiveFromDateGMT.toString());
	}

	/**
	 * Set value of EffectiveFromDateGMT
	 * @param effectivefromdategmt
	 */
	public final void setEffectiveFromDateGMT(java.lang.String effectivefromdategmt)
	{
		setEffectiveFromDateGMT(getContext(), effectivefromdategmt);
	}

	/**
	 * Set value of EffectiveFromDateGMT
	 * @param context
	 * @param effectivefromdategmt
	 */
	public final void setEffectiveFromDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String effectivefromdategmt)
	{
		getMendixObject().setValue(context, MemberNames.EffectiveFromDateGMT.toString(), effectivefromdategmt);
	}

	/**
	 * @return value of EffectiveThruDateGMT
	 */
	public final java.lang.String getEffectiveThruDateGMT()
	{
		return getEffectiveThruDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of EffectiveThruDateGMT
	 */
	public final java.lang.String getEffectiveThruDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EffectiveThruDateGMT.toString());
	}

	/**
	 * Set value of EffectiveThruDateGMT
	 * @param effectivethrudategmt
	 */
	public final void setEffectiveThruDateGMT(java.lang.String effectivethrudategmt)
	{
		setEffectiveThruDateGMT(getContext(), effectivethrudategmt);
	}

	/**
	 * Set value of EffectiveThruDateGMT
	 * @param context
	 * @param effectivethrudategmt
	 */
	public final void setEffectiveThruDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String effectivethrudategmt)
	{
		getMendixObject().setValue(context, MemberNames.EffectiveThruDateGMT.toString(), effectivethrudategmt);
	}

	/**
	 * @return value of SpecId
	 */
	public final java.lang.String getSpecId()
	{
		return getSpecId(getContext());
	}

	/**
	 * @param context
	 * @return value of SpecId
	 */
	public final java.lang.String getSpecId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SpecId.toString());
	}

	/**
	 * Set value of SpecId
	 * @param specid
	 */
	public final void setSpecId(java.lang.String specid)
	{
		setSpecId(getContext(), specid);
	}

	/**
	 * Set value of SpecId
	 * @param context
	 * @param specid
	 */
	public final void setSpecId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String specid)
	{
		getMendixObject().setValue(context, MemberNames.SpecId.toString(), specid);
	}

	/**
	 * @return value of UOM
	 */
	public final java.lang.String getUOM()
	{
		return getUOM(getContext());
	}

	/**
	 * @param context
	 * @return value of UOM
	 */
	public final java.lang.String getUOM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UOM.toString());
	}

	/**
	 * Set value of UOM
	 * @param uom
	 */
	public final void setUOM(java.lang.String uom)
	{
		setUOM(getContext(), uom);
	}

	/**
	 * Set value of UOM
	 * @param context
	 * @param uom
	 */
	public final void setUOM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uom)
	{
		getMendixObject().setValue(context, MemberNames.UOM.toString(), uom);
	}

	/**
	 * @return value of SetupQty
	 */
	public final java.lang.String getSetupQty()
	{
		return getSetupQty(getContext());
	}

	/**
	 * @param context
	 * @return value of SetupQty
	 */
	public final java.lang.String getSetupQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SetupQty.toString());
	}

	/**
	 * Set value of SetupQty
	 * @param setupqty
	 */
	public final void setSetupQty(java.lang.String setupqty)
	{
		setSetupQty(getContext(), setupqty);
	}

	/**
	 * Set value of SetupQty
	 * @param context
	 * @param setupqty
	 */
	public final void setSetupQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String setupqty)
	{
		getMendixObject().setValue(context, MemberNames.SetupQty.toString(), setupqty);
	}

	/**
	 * @return value of VendorControl
	 */
	public final java.lang.String getVendorControl()
	{
		return getVendorControl(getContext());
	}

	/**
	 * @param context
	 * @return value of VendorControl
	 */
	public final java.lang.String getVendorControl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VendorControl.toString());
	}

	/**
	 * Set value of VendorControl
	 * @param vendorcontrol
	 */
	public final void setVendorControl(java.lang.String vendorcontrol)
	{
		setVendorControl(getContext(), vendorcontrol);
	}

	/**
	 * Set value of VendorControl
	 * @param context
	 * @param vendorcontrol
	 */
	public final void setVendorControl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String vendorcontrol)
	{
		getMendixObject().setValue(context, MemberNames.VendorControl.toString(), vendorcontrol);
	}

	/**
	 * @return value of ReferenceDesignator
	 */
	public final java.lang.String getReferenceDesignator()
	{
		return getReferenceDesignator(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceDesignator
	 */
	public final java.lang.String getReferenceDesignator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReferenceDesignator.toString());
	}

	/**
	 * Set value of ReferenceDesignator
	 * @param referencedesignator
	 */
	public final void setReferenceDesignator(java.lang.String referencedesignator)
	{
		setReferenceDesignator(getContext(), referencedesignator);
	}

	/**
	 * Set value of ReferenceDesignator
	 * @param context
	 * @param referencedesignator
	 */
	public final void setReferenceDesignator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String referencedesignator)
	{
		getMendixObject().setValue(context, MemberNames.ReferenceDesignator.toString(), referencedesignator);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot
	 */
	public final excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirementsRoot getResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot() throws com.mendix.core.CoreException
	{
		return getResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirementsRoot getResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirementsRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirementsRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot
	 * @param rescomponentissuematerialsrequirement_rescomponentissuematerialsrequirementsroot
	 */
	public final void setResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot(excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirementsRoot rescomponentissuematerialsrequirement_rescomponentissuematerialsrequirementsroot)
	{
		setResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot(getContext(), rescomponentissuematerialsrequirement_rescomponentissuematerialsrequirementsroot);
	}

	/**
	 * Set value of ResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot
	 * @param context
	 * @param rescomponentissuematerialsrequirement_rescomponentissuematerialsrequirementsroot
	 */
	public final void setResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirementsRoot rescomponentissuematerialsrequirement_rescomponentissuematerialsrequirementsroot)
	{
		if (rescomponentissuematerialsrequirement_rescomponentissuematerialsrequirementsroot == null) {
			getMendixObject().setValue(context, MemberNames.ResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResComponentIssueMaterialsRequirement_ResComponentIssueMaterialsRequirementsRoot.toString(), rescomponentissuematerialsrequirement_rescomponentissuematerialsrequirementsroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResComponentIssueMaterialsRequirement_ComponentIssueContext
	 */
	public final excr_resourcemanagement.proxies.ComponentIssueContext getResComponentIssueMaterialsRequirement_ComponentIssueContext() throws com.mendix.core.CoreException
	{
		return getResComponentIssueMaterialsRequirement_ComponentIssueContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ResComponentIssueMaterialsRequirement_ComponentIssueContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ComponentIssueContext getResComponentIssueMaterialsRequirement_ComponentIssueContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ComponentIssueContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResComponentIssueMaterialsRequirement_ComponentIssueContext.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ComponentIssueContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResComponentIssueMaterialsRequirement_ComponentIssueContext
	 * @param rescomponentissuematerialsrequirement_componentissuecontext
	 */
	public final void setResComponentIssueMaterialsRequirement_ComponentIssueContext(excr_resourcemanagement.proxies.ComponentIssueContext rescomponentissuematerialsrequirement_componentissuecontext)
	{
		setResComponentIssueMaterialsRequirement_ComponentIssueContext(getContext(), rescomponentissuematerialsrequirement_componentissuecontext);
	}

	/**
	 * Set value of ResComponentIssueMaterialsRequirement_ComponentIssueContext
	 * @param context
	 * @param rescomponentissuematerialsrequirement_componentissuecontext
	 */
	public final void setResComponentIssueMaterialsRequirement_ComponentIssueContext(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ComponentIssueContext rescomponentissuematerialsrequirement_componentissuecontext)
	{
		if (rescomponentissuematerialsrequirement_componentissuecontext == null) {
			getMendixObject().setValue(context, MemberNames.ResComponentIssueMaterialsRequirement_ComponentIssueContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResComponentIssueMaterialsRequirement_ComponentIssueContext.toString(), rescomponentissuematerialsrequirement_componentissuecontext.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ComponentIssueGridRowData_ResComponentIssueMaterialsRequirement
	 */
	public final excr_resourcemanagement.proxies.ComponentIssueGridRowData getComponentIssueGridRowData_ResComponentIssueMaterialsRequirement() throws com.mendix.core.CoreException
	{
		return getComponentIssueGridRowData_ResComponentIssueMaterialsRequirement(getContext());
	}

	/**
	 * @param context
	 * @return value of ComponentIssueGridRowData_ResComponentIssueMaterialsRequirement
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ComponentIssueGridRowData getComponentIssueGridRowData_ResComponentIssueMaterialsRequirement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ComponentIssueGridRowData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ComponentIssueGridRowData_ResComponentIssueMaterialsRequirement.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ComponentIssueGridRowData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ComponentIssueGridRowData_ResComponentIssueMaterialsRequirement
	 * @param componentissuegridrowdata_rescomponentissuematerialsrequirement
	 */
	public final void setComponentIssueGridRowData_ResComponentIssueMaterialsRequirement(excr_resourcemanagement.proxies.ComponentIssueGridRowData componentissuegridrowdata_rescomponentissuematerialsrequirement)
	{
		setComponentIssueGridRowData_ResComponentIssueMaterialsRequirement(getContext(), componentissuegridrowdata_rescomponentissuematerialsrequirement);
	}

	/**
	 * Set value of ComponentIssueGridRowData_ResComponentIssueMaterialsRequirement
	 * @param context
	 * @param componentissuegridrowdata_rescomponentissuematerialsrequirement
	 */
	public final void setComponentIssueGridRowData_ResComponentIssueMaterialsRequirement(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ComponentIssueGridRowData componentissuegridrowdata_rescomponentissuematerialsrequirement)
	{
		if (componentissuegridrowdata_rescomponentissuematerialsrequirement == null) {
			getMendixObject().setValue(context, MemberNames.ComponentIssueGridRowData_ResComponentIssueMaterialsRequirement.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ComponentIssueGridRowData_ResComponentIssueMaterialsRequirement.toString(), componentissuegridrowdata_rescomponentissuematerialsrequirement.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resComponentIssueMaterialsRequirementMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirement that = (excr_containermanagement_api.proxies.ResComponentIssueMaterialsRequirement) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
