// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ResDataCollectionHistoryDataPoint implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resDataCollectionHistoryDataPointMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ResDataCollectionHistoryDataPoint";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataName("DataName"),
		DataValue("DataValue"),
		ResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot("EXCR_ContainerManagement_API.ResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot"),
		ResDataCollectionHistoryDataPoint_ContainerCollectDataContext("EXCR_ContainerManagement_API.ResDataCollectionHistoryDataPoint_ContainerCollectDataContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResDataCollectionHistoryDataPoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResDataCollectionHistoryDataPoint(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resDataCollectionHistoryDataPointMendixObject)
	{
		if (resDataCollectionHistoryDataPointMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resDataCollectionHistoryDataPointMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resDataCollectionHistoryDataPointMendixObject = resDataCollectionHistoryDataPointMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ResDataCollectionHistoryDataPoint initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ResDataCollectionHistoryDataPoint(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ResDataCollectionHistoryDataPoint load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ResDataCollectionHistoryDataPoint.initialize(context, mendixObject);
	}

	/**
	 * @return value of DataName
	 */
	public final java.lang.String getDataName()
	{
		return getDataName(getContext());
	}

	/**
	 * @param context
	 * @return value of DataName
	 */
	public final java.lang.String getDataName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataName.toString());
	}

	/**
	 * Set value of DataName
	 * @param dataname
	 */
	public final void setDataName(java.lang.String dataname)
	{
		setDataName(getContext(), dataname);
	}

	/**
	 * Set value of DataName
	 * @param context
	 * @param dataname
	 */
	public final void setDataName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dataname)
	{
		getMendixObject().setValue(context, MemberNames.DataName.toString(), dataname);
	}

	/**
	 * @return value of DataValue
	 */
	public final java.lang.String getDataValue()
	{
		return getDataValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DataValue
	 */
	public final java.lang.String getDataValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataValue.toString());
	}

	/**
	 * Set value of DataValue
	 * @param datavalue
	 */
	public final void setDataValue(java.lang.String datavalue)
	{
		setDataValue(getContext(), datavalue);
	}

	/**
	 * Set value of DataValue
	 * @param context
	 * @param datavalue
	 */
	public final void setDataValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datavalue)
	{
		getMendixObject().setValue(context, MemberNames.DataValue.toString(), datavalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot
	 */
	public final excr_containermanagement_api.proxies.ResDataCollectionHistoryRoot getResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot() throws com.mendix.core.CoreException
	{
		return getResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ResDataCollectionHistoryRoot getResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ResDataCollectionHistoryRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ResDataCollectionHistoryRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot
	 * @param resdatacollectionhistorydatapoint_resdatacollectionhistoryroot
	 */
	public final void setResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot(excr_containermanagement_api.proxies.ResDataCollectionHistoryRoot resdatacollectionhistorydatapoint_resdatacollectionhistoryroot)
	{
		setResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot(getContext(), resdatacollectionhistorydatapoint_resdatacollectionhistoryroot);
	}

	/**
	 * Set value of ResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot
	 * @param context
	 * @param resdatacollectionhistorydatapoint_resdatacollectionhistoryroot
	 */
	public final void setResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ResDataCollectionHistoryRoot resdatacollectionhistorydatapoint_resdatacollectionhistoryroot)
	{
		if (resdatacollectionhistorydatapoint_resdatacollectionhistoryroot == null) {
			getMendixObject().setValue(context, MemberNames.ResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResDataCollectionHistoryDataPoint_ResDataCollectionHistoryRoot.toString(), resdatacollectionhistorydatapoint_resdatacollectionhistoryroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResDataCollectionHistoryDataPoint_ContainerCollectDataContext
	 */
	public final excr_resourcemanagement.proxies.ContainerCollectDataContext getResDataCollectionHistoryDataPoint_ContainerCollectDataContext() throws com.mendix.core.CoreException
	{
		return getResDataCollectionHistoryDataPoint_ContainerCollectDataContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ResDataCollectionHistoryDataPoint_ContainerCollectDataContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ContainerCollectDataContext getResDataCollectionHistoryDataPoint_ContainerCollectDataContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ContainerCollectDataContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResDataCollectionHistoryDataPoint_ContainerCollectDataContext.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ContainerCollectDataContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResDataCollectionHistoryDataPoint_ContainerCollectDataContext
	 * @param resdatacollectionhistorydatapoint_containercollectdatacontext
	 */
	public final void setResDataCollectionHistoryDataPoint_ContainerCollectDataContext(excr_resourcemanagement.proxies.ContainerCollectDataContext resdatacollectionhistorydatapoint_containercollectdatacontext)
	{
		setResDataCollectionHistoryDataPoint_ContainerCollectDataContext(getContext(), resdatacollectionhistorydatapoint_containercollectdatacontext);
	}

	/**
	 * Set value of ResDataCollectionHistoryDataPoint_ContainerCollectDataContext
	 * @param context
	 * @param resdatacollectionhistorydatapoint_containercollectdatacontext
	 */
	public final void setResDataCollectionHistoryDataPoint_ContainerCollectDataContext(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ContainerCollectDataContext resdatacollectionhistorydatapoint_containercollectdatacontext)
	{
		if (resdatacollectionhistorydatapoint_containercollectdatacontext == null) {
			getMendixObject().setValue(context, MemberNames.ResDataCollectionHistoryDataPoint_ContainerCollectDataContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResDataCollectionHistoryDataPoint_ContainerCollectDataContext.toString(), resdatacollectionhistorydatapoint_containercollectdatacontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resDataCollectionHistoryDataPointMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ResDataCollectionHistoryDataPoint that = (excr_containermanagement_api.proxies.ResDataCollectionHistoryDataPoint) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
