// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ResHoldReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resHoldReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ResHoldReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ResHoldReason_ResHoldReasonListRoot("EXCR_ContainerManagement_API.ResHoldReason_ResHoldReasonListRoot"),
		ResHoldReason_ContainerHoldContext("EXCR_ContainerManagement_API.ResHoldReason_ContainerHoldContext"),
		ResHoldReason_HoldManagementPageContext("EXCR_ContainerManagement_API.ResHoldReason_HoldManagementPageContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResHoldReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResHoldReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resHoldReasonMendixObject)
	{
		if (resHoldReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resHoldReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resHoldReasonMendixObject = resHoldReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ResHoldReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ResHoldReason(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ResHoldReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ResHoldReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResHoldReason_ResHoldReasonListRoot
	 */
	public final excr_containermanagement_api.proxies.ResHoldReasonListRoot getResHoldReason_ResHoldReasonListRoot() throws com.mendix.core.CoreException
	{
		return getResHoldReason_ResHoldReasonListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResHoldReason_ResHoldReasonListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ResHoldReasonListRoot getResHoldReason_ResHoldReasonListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ResHoldReasonListRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResHoldReason_ResHoldReasonListRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ResHoldReasonListRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResHoldReason_ResHoldReasonListRoot
	 * @param resholdreason_resholdreasonlistroot
	 */
	public final void setResHoldReason_ResHoldReasonListRoot(excr_containermanagement_api.proxies.ResHoldReasonListRoot resholdreason_resholdreasonlistroot)
	{
		setResHoldReason_ResHoldReasonListRoot(getContext(), resholdreason_resholdreasonlistroot);
	}

	/**
	 * Set value of ResHoldReason_ResHoldReasonListRoot
	 * @param context
	 * @param resholdreason_resholdreasonlistroot
	 */
	public final void setResHoldReason_ResHoldReasonListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ResHoldReasonListRoot resholdreason_resholdreasonlistroot)
	{
		if (resholdreason_resholdreasonlistroot == null) {
			getMendixObject().setValue(context, MemberNames.ResHoldReason_ResHoldReasonListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResHoldReason_ResHoldReasonListRoot.toString(), resholdreason_resholdreasonlistroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResHoldReason_ContainerHoldContext
	 */
	public final excr_resourcemanagement.proxies.ContainerHoldContext getResHoldReason_ContainerHoldContext() throws com.mendix.core.CoreException
	{
		return getResHoldReason_ContainerHoldContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ResHoldReason_ContainerHoldContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ContainerHoldContext getResHoldReason_ContainerHoldContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ContainerHoldContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResHoldReason_ContainerHoldContext.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ContainerHoldContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResHoldReason_ContainerHoldContext
	 * @param resholdreason_containerholdcontext
	 */
	public final void setResHoldReason_ContainerHoldContext(excr_resourcemanagement.proxies.ContainerHoldContext resholdreason_containerholdcontext)
	{
		setResHoldReason_ContainerHoldContext(getContext(), resholdreason_containerholdcontext);
	}

	/**
	 * Set value of ResHoldReason_ContainerHoldContext
	 * @param context
	 * @param resholdreason_containerholdcontext
	 */
	public final void setResHoldReason_ContainerHoldContext(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ContainerHoldContext resholdreason_containerholdcontext)
	{
		if (resholdreason_containerholdcontext == null) {
			getMendixObject().setValue(context, MemberNames.ResHoldReason_ContainerHoldContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResHoldReason_ContainerHoldContext.toString(), resholdreason_containerholdcontext.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResHoldReason_HoldManagementPageContext
	 */
	public final excr_holdmanagement.proxies.HoldManagementPageContext getResHoldReason_HoldManagementPageContext() throws com.mendix.core.CoreException
	{
		return getResHoldReason_HoldManagementPageContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ResHoldReason_HoldManagementPageContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_holdmanagement.proxies.HoldManagementPageContext getResHoldReason_HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_holdmanagement.proxies.HoldManagementPageContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResHoldReason_HoldManagementPageContext.toString());
		if (identifier != null) {
			result = excr_holdmanagement.proxies.HoldManagementPageContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResHoldReason_HoldManagementPageContext
	 * @param resholdreason_holdmanagementpagecontext
	 */
	public final void setResHoldReason_HoldManagementPageContext(excr_holdmanagement.proxies.HoldManagementPageContext resholdreason_holdmanagementpagecontext)
	{
		setResHoldReason_HoldManagementPageContext(getContext(), resholdreason_holdmanagementpagecontext);
	}

	/**
	 * Set value of ResHoldReason_HoldManagementPageContext
	 * @param context
	 * @param resholdreason_holdmanagementpagecontext
	 */
	public final void setResHoldReason_HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context, excr_holdmanagement.proxies.HoldManagementPageContext resholdreason_holdmanagementpagecontext)
	{
		if (resholdreason_holdmanagementpagecontext == null) {
			getMendixObject().setValue(context, MemberNames.ResHoldReason_HoldManagementPageContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResHoldReason_HoldManagementPageContext.toString(), resholdreason_holdmanagementpagecontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resHoldReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ResHoldReason that = (excr_containermanagement_api.proxies.ResHoldReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
