// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ResIssueDifferenceReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resIssueDifferenceReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ResIssueDifferenceReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ResIssueDifferenceReason_ResIssueDifferenceReasonListRoot("EXCR_ContainerManagement_API.ResIssueDifferenceReason_ResIssueDifferenceReasonListRoot"),
		ResIssueDifferenceReason_ComponentIssueMaterialDetail("EXCR_ContainerManagement_API.ResIssueDifferenceReason_ComponentIssueMaterialDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResIssueDifferenceReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResIssueDifferenceReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resIssueDifferenceReasonMendixObject)
	{
		if (resIssueDifferenceReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resIssueDifferenceReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resIssueDifferenceReasonMendixObject = resIssueDifferenceReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ResIssueDifferenceReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ResIssueDifferenceReason(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ResIssueDifferenceReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ResIssueDifferenceReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResIssueDifferenceReason_ResIssueDifferenceReasonListRoot
	 */
	public final excr_containermanagement_api.proxies.ResIssueDifferenceReasonListRoot getResIssueDifferenceReason_ResIssueDifferenceReasonListRoot() throws com.mendix.core.CoreException
	{
		return getResIssueDifferenceReason_ResIssueDifferenceReasonListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResIssueDifferenceReason_ResIssueDifferenceReasonListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ResIssueDifferenceReasonListRoot getResIssueDifferenceReason_ResIssueDifferenceReasonListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ResIssueDifferenceReasonListRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResIssueDifferenceReason_ResIssueDifferenceReasonListRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ResIssueDifferenceReasonListRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResIssueDifferenceReason_ResIssueDifferenceReasonListRoot
	 * @param resissuedifferencereason_resissuedifferencereasonlistroot
	 */
	public final void setResIssueDifferenceReason_ResIssueDifferenceReasonListRoot(excr_containermanagement_api.proxies.ResIssueDifferenceReasonListRoot resissuedifferencereason_resissuedifferencereasonlistroot)
	{
		setResIssueDifferenceReason_ResIssueDifferenceReasonListRoot(getContext(), resissuedifferencereason_resissuedifferencereasonlistroot);
	}

	/**
	 * Set value of ResIssueDifferenceReason_ResIssueDifferenceReasonListRoot
	 * @param context
	 * @param resissuedifferencereason_resissuedifferencereasonlistroot
	 */
	public final void setResIssueDifferenceReason_ResIssueDifferenceReasonListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ResIssueDifferenceReasonListRoot resissuedifferencereason_resissuedifferencereasonlistroot)
	{
		if (resissuedifferencereason_resissuedifferencereasonlistroot == null) {
			getMendixObject().setValue(context, MemberNames.ResIssueDifferenceReason_ResIssueDifferenceReasonListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResIssueDifferenceReason_ResIssueDifferenceReasonListRoot.toString(), resissuedifferencereason_resissuedifferencereasonlistroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResIssueDifferenceReason_ComponentIssueMaterialDetail
	 */
	public final excr_resourcemanagement.proxies.ComponentIssueMaterialDetail getResIssueDifferenceReason_ComponentIssueMaterialDetail() throws com.mendix.core.CoreException
	{
		return getResIssueDifferenceReason_ComponentIssueMaterialDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ResIssueDifferenceReason_ComponentIssueMaterialDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ComponentIssueMaterialDetail getResIssueDifferenceReason_ComponentIssueMaterialDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ComponentIssueMaterialDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResIssueDifferenceReason_ComponentIssueMaterialDetail.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ComponentIssueMaterialDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResIssueDifferenceReason_ComponentIssueMaterialDetail
	 * @param resissuedifferencereason_componentissuematerialdetail
	 */
	public final void setResIssueDifferenceReason_ComponentIssueMaterialDetail(excr_resourcemanagement.proxies.ComponentIssueMaterialDetail resissuedifferencereason_componentissuematerialdetail)
	{
		setResIssueDifferenceReason_ComponentIssueMaterialDetail(getContext(), resissuedifferencereason_componentissuematerialdetail);
	}

	/**
	 * Set value of ResIssueDifferenceReason_ComponentIssueMaterialDetail
	 * @param context
	 * @param resissuedifferencereason_componentissuematerialdetail
	 */
	public final void setResIssueDifferenceReason_ComponentIssueMaterialDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ComponentIssueMaterialDetail resissuedifferencereason_componentissuematerialdetail)
	{
		if (resissuedifferencereason_componentissuematerialdetail == null) {
			getMendixObject().setValue(context, MemberNames.ResIssueDifferenceReason_ComponentIssueMaterialDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResIssueDifferenceReason_ComponentIssueMaterialDetail.toString(), resissuedifferencereason_componentissuematerialdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resIssueDifferenceReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ResIssueDifferenceReason that = (excr_containermanagement_api.proxies.ResIssueDifferenceReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
