// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ResReleaseReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resReleaseReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ResReleaseReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ResReleaseReason_ResReleaseReasonListRoot("EXCR_ContainerManagement_API.ResReleaseReason_ResReleaseReasonListRoot"),
		ResReleaseReason_ContainerReleaseContext("EXCR_ContainerManagement_API.ResReleaseReason_ContainerReleaseContext"),
		ResReleaseReason_HoldManagementPageContext("EXCR_ContainerManagement_API.ResReleaseReason_HoldManagementPageContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResReleaseReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResReleaseReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resReleaseReasonMendixObject)
	{
		if (resReleaseReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resReleaseReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resReleaseReasonMendixObject = resReleaseReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ResReleaseReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ResReleaseReason(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ResReleaseReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ResReleaseReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResReleaseReason_ResReleaseReasonListRoot
	 */
	public final excr_containermanagement_api.proxies.ResReleaseReasonListRoot getResReleaseReason_ResReleaseReasonListRoot() throws com.mendix.core.CoreException
	{
		return getResReleaseReason_ResReleaseReasonListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResReleaseReason_ResReleaseReasonListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ResReleaseReasonListRoot getResReleaseReason_ResReleaseReasonListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ResReleaseReasonListRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResReleaseReason_ResReleaseReasonListRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ResReleaseReasonListRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResReleaseReason_ResReleaseReasonListRoot
	 * @param resreleasereason_resreleasereasonlistroot
	 */
	public final void setResReleaseReason_ResReleaseReasonListRoot(excr_containermanagement_api.proxies.ResReleaseReasonListRoot resreleasereason_resreleasereasonlistroot)
	{
		setResReleaseReason_ResReleaseReasonListRoot(getContext(), resreleasereason_resreleasereasonlistroot);
	}

	/**
	 * Set value of ResReleaseReason_ResReleaseReasonListRoot
	 * @param context
	 * @param resreleasereason_resreleasereasonlistroot
	 */
	public final void setResReleaseReason_ResReleaseReasonListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ResReleaseReasonListRoot resreleasereason_resreleasereasonlistroot)
	{
		if (resreleasereason_resreleasereasonlistroot == null) {
			getMendixObject().setValue(context, MemberNames.ResReleaseReason_ResReleaseReasonListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResReleaseReason_ResReleaseReasonListRoot.toString(), resreleasereason_resreleasereasonlistroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResReleaseReason_ContainerReleaseContext
	 */
	public final excr_resourcemanagement.proxies.ContainerReleaseContext getResReleaseReason_ContainerReleaseContext() throws com.mendix.core.CoreException
	{
		return getResReleaseReason_ContainerReleaseContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ResReleaseReason_ContainerReleaseContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ContainerReleaseContext getResReleaseReason_ContainerReleaseContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ContainerReleaseContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResReleaseReason_ContainerReleaseContext.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ContainerReleaseContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResReleaseReason_ContainerReleaseContext
	 * @param resreleasereason_containerreleasecontext
	 */
	public final void setResReleaseReason_ContainerReleaseContext(excr_resourcemanagement.proxies.ContainerReleaseContext resreleasereason_containerreleasecontext)
	{
		setResReleaseReason_ContainerReleaseContext(getContext(), resreleasereason_containerreleasecontext);
	}

	/**
	 * Set value of ResReleaseReason_ContainerReleaseContext
	 * @param context
	 * @param resreleasereason_containerreleasecontext
	 */
	public final void setResReleaseReason_ContainerReleaseContext(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ContainerReleaseContext resreleasereason_containerreleasecontext)
	{
		if (resreleasereason_containerreleasecontext == null) {
			getMendixObject().setValue(context, MemberNames.ResReleaseReason_ContainerReleaseContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResReleaseReason_ContainerReleaseContext.toString(), resreleasereason_containerreleasecontext.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResReleaseReason_HoldManagementPageContext
	 */
	public final excr_holdmanagement.proxies.HoldManagementPageContext getResReleaseReason_HoldManagementPageContext() throws com.mendix.core.CoreException
	{
		return getResReleaseReason_HoldManagementPageContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ResReleaseReason_HoldManagementPageContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_holdmanagement.proxies.HoldManagementPageContext getResReleaseReason_HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_holdmanagement.proxies.HoldManagementPageContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResReleaseReason_HoldManagementPageContext.toString());
		if (identifier != null) {
			result = excr_holdmanagement.proxies.HoldManagementPageContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResReleaseReason_HoldManagementPageContext
	 * @param resreleasereason_holdmanagementpagecontext
	 */
	public final void setResReleaseReason_HoldManagementPageContext(excr_holdmanagement.proxies.HoldManagementPageContext resreleasereason_holdmanagementpagecontext)
	{
		setResReleaseReason_HoldManagementPageContext(getContext(), resreleasereason_holdmanagementpagecontext);
	}

	/**
	 * Set value of ResReleaseReason_HoldManagementPageContext
	 * @param context
	 * @param resreleasereason_holdmanagementpagecontext
	 */
	public final void setResReleaseReason_HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context, excr_holdmanagement.proxies.HoldManagementPageContext resreleasereason_holdmanagementpagecontext)
	{
		if (resreleasereason_holdmanagementpagecontext == null) {
			getMendixObject().setValue(context, MemberNames.ResReleaseReason_HoldManagementPageContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResReleaseReason_HoldManagementPageContext.toString(), resreleasereason_holdmanagementpagecontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resReleaseReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ResReleaseReason that = (excr_containermanagement_api.proxies.ResReleaseReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
