// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_containermanagement_api.proxies;

public class ResSellReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resSellReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ContainerManagement_API.ResSellReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		IsFrozen("IsFrozen"),
		InstanceId("InstanceId"),
		Description("Description"),
		ResSellReason_ResSellReasonListRoot("EXCR_ContainerManagement_API.ResSellReason_ResSellReasonListRoot"),
		ResSellReason_SellReason("EXCR_ContainerManagement_API.ResSellReason_SellReason");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResSellReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResSellReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resSellReasonMendixObject)
	{
		if (resSellReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resSellReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resSellReasonMendixObject = resSellReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_containermanagement_api.proxies.ResSellReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_containermanagement_api.proxies.ResSellReason(context, mendixObject);
	}

	public static excr_containermanagement_api.proxies.ResSellReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_containermanagement_api.proxies.ResSellReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen()
	{
		return getIsFrozen(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IsFrozen.toString());
	}

	/**
	 * Set value of IsFrozen
	 * @param isfrozen
	 */
	public final void setIsFrozen(java.lang.String isfrozen)
	{
		setIsFrozen(getContext(), isfrozen);
	}

	/**
	 * Set value of IsFrozen
	 * @param context
	 * @param isfrozen
	 */
	public final void setIsFrozen(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String isfrozen)
	{
		getMendixObject().setValue(context, MemberNames.IsFrozen.toString(), isfrozen);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResSellReason_ResSellReasonListRoot
	 */
	public final excr_containermanagement_api.proxies.ResSellReasonListRoot getResSellReason_ResSellReasonListRoot() throws com.mendix.core.CoreException
	{
		return getResSellReason_ResSellReasonListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResSellReason_ResSellReasonListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ResSellReasonListRoot getResSellReason_ResSellReasonListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ResSellReasonListRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResSellReason_ResSellReasonListRoot.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ResSellReasonListRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResSellReason_ResSellReasonListRoot
	 * @param ressellreason_ressellreasonlistroot
	 */
	public final void setResSellReason_ResSellReasonListRoot(excr_containermanagement_api.proxies.ResSellReasonListRoot ressellreason_ressellreasonlistroot)
	{
		setResSellReason_ResSellReasonListRoot(getContext(), ressellreason_ressellreasonlistroot);
	}

	/**
	 * Set value of ResSellReason_ResSellReasonListRoot
	 * @param context
	 * @param ressellreason_ressellreasonlistroot
	 */
	public final void setResSellReason_ResSellReasonListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ResSellReasonListRoot ressellreason_ressellreasonlistroot)
	{
		if (ressellreason_ressellreasonlistroot == null) {
			getMendixObject().setValue(context, MemberNames.ResSellReason_ResSellReasonListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResSellReason_ResSellReasonListRoot.toString(), ressellreason_ressellreasonlistroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResSellReason_SellReason
	 */
	public final excr_resourcemanagement.proxies.SellReason getResSellReason_SellReason() throws com.mendix.core.CoreException
	{
		return getResSellReason_SellReason(getContext());
	}

	/**
	 * @param context
	 * @return value of ResSellReason_SellReason
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.SellReason getResSellReason_SellReason(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.SellReason result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResSellReason_SellReason.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.SellReason.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResSellReason_SellReason
	 * @param ressellreason_sellreason
	 */
	public final void setResSellReason_SellReason(excr_resourcemanagement.proxies.SellReason ressellreason_sellreason)
	{
		setResSellReason_SellReason(getContext(), ressellreason_sellreason);
	}

	/**
	 * Set value of ResSellReason_SellReason
	 * @param context
	 * @param ressellreason_sellreason
	 */
	public final void setResSellReason_SellReason(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.SellReason ressellreason_sellreason)
	{
		if (ressellreason_sellreason == null) {
			getMendixObject().setValue(context, MemberNames.ResSellReason_SellReason.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResSellReason_SellReason.toString(), ressellreason_sellreason.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resSellReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_containermanagement_api.proxies.ResSellReason that = (excr_containermanagement_api.proxies.ResSellReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
