// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class ConfiguredSAMLAuthnContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configuredSAMLAuthnContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.ConfiguredSAMLAuthnContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Priority("Priority"),
		ConfiguredSAMLAuthnContext_SSOConfiguration("SAML20.ConfiguredSAMLAuthnContext_SSOConfiguration"),
		ConfiguredSAMLAuthnContext_SAMLAuthnContext("SAML20.ConfiguredSAMLAuthnContext_SAMLAuthnContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConfiguredSAMLAuthnContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConfiguredSAMLAuthnContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configuredSAMLAuthnContextMendixObject)
	{
		if (configuredSAMLAuthnContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!configuredSAMLAuthnContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configuredSAMLAuthnContextMendixObject = configuredSAMLAuthnContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static saml20.proxies.ConfiguredSAMLAuthnContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.ConfiguredSAMLAuthnContext(context, mendixObject);
	}

	public static saml20.proxies.ConfiguredSAMLAuthnContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.ConfiguredSAMLAuthnContext.initialize(context, mendixObject);
	}

	public static java.util.List<saml20.proxies.ConfiguredSAMLAuthnContext> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> saml20.proxies.ConfiguredSAMLAuthnContext.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Priority
	 */
	public final java.lang.Integer getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final java.lang.Integer getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Priority.toString());
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(java.lang.Integer priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer priority)
	{
		getMendixObject().setValue(context, MemberNames.Priority.toString(), priority);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfiguredSAMLAuthnContext_SSOConfiguration
	 */
	public final saml20.proxies.SSOConfiguration getConfiguredSAMLAuthnContext_SSOConfiguration() throws com.mendix.core.CoreException
	{
		return getConfiguredSAMLAuthnContext_SSOConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfiguredSAMLAuthnContext_SSOConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final saml20.proxies.SSOConfiguration getConfiguredSAMLAuthnContext_SSOConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.SSOConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfiguredSAMLAuthnContext_SSOConfiguration.toString());
		if (identifier != null) {
			result = saml20.proxies.SSOConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfiguredSAMLAuthnContext_SSOConfiguration
	 * @param configuredsamlauthncontext_ssoconfiguration
	 */
	public final void setConfiguredSAMLAuthnContext_SSOConfiguration(saml20.proxies.SSOConfiguration configuredsamlauthncontext_ssoconfiguration)
	{
		setConfiguredSAMLAuthnContext_SSOConfiguration(getContext(), configuredsamlauthncontext_ssoconfiguration);
	}

	/**
	 * Set value of ConfiguredSAMLAuthnContext_SSOConfiguration
	 * @param context
	 * @param configuredsamlauthncontext_ssoconfiguration
	 */
	public final void setConfiguredSAMLAuthnContext_SSOConfiguration(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.SSOConfiguration configuredsamlauthncontext_ssoconfiguration)
	{
		if (configuredsamlauthncontext_ssoconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.ConfiguredSAMLAuthnContext_SSOConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfiguredSAMLAuthnContext_SSOConfiguration.toString(), configuredsamlauthncontext_ssoconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfiguredSAMLAuthnContext_SAMLAuthnContext
	 */
	public final saml20.proxies.SAMLAuthnContext getConfiguredSAMLAuthnContext_SAMLAuthnContext() throws com.mendix.core.CoreException
	{
		return getConfiguredSAMLAuthnContext_SAMLAuthnContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfiguredSAMLAuthnContext_SAMLAuthnContext
	 * @throws com.mendix.core.CoreException
	 */
	public final saml20.proxies.SAMLAuthnContext getConfiguredSAMLAuthnContext_SAMLAuthnContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.SAMLAuthnContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfiguredSAMLAuthnContext_SAMLAuthnContext.toString());
		if (identifier != null) {
			result = saml20.proxies.SAMLAuthnContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfiguredSAMLAuthnContext_SAMLAuthnContext
	 * @param configuredsamlauthncontext_samlauthncontext
	 */
	public final void setConfiguredSAMLAuthnContext_SAMLAuthnContext(saml20.proxies.SAMLAuthnContext configuredsamlauthncontext_samlauthncontext)
	{
		setConfiguredSAMLAuthnContext_SAMLAuthnContext(getContext(), configuredsamlauthncontext_samlauthncontext);
	}

	/**
	 * Set value of ConfiguredSAMLAuthnContext_SAMLAuthnContext
	 * @param context
	 * @param configuredsamlauthncontext_samlauthncontext
	 */
	public final void setConfiguredSAMLAuthnContext_SAMLAuthnContext(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.SAMLAuthnContext configuredsamlauthncontext_samlauthncontext)
	{
		if (configuredsamlauthncontext_samlauthncontext == null) {
			getMendixObject().setValue(context, MemberNames.ConfiguredSAMLAuthnContext_SAMLAuthnContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfiguredSAMLAuthnContext_SAMLAuthnContext.toString(), configuredsamlauthncontext_samlauthncontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configuredSAMLAuthnContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.ConfiguredSAMLAuthnContext that = (saml20.proxies.ConfiguredSAMLAuthnContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
