// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public enum Enum_Attribute_Consuming_Login_Type
{
	Initial_Login("5308c0ca-2dcc-4d44-8a23-c5d40cfb3adf"),
	InSession_Login("bc1bc6d8-2bdd-45b2-b8f8-87e529e95f71");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_Attribute_Consuming_Login_Type(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
