// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class LoginFeedback implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject loginFeedbackMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.LoginFeedback";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LoginAllowed("LoginAllowed"),
		FeedbackMessageHTML("FeedbackMessageHTML");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LoginFeedback(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected LoginFeedback(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject loginFeedbackMendixObject)
	{
		if (loginFeedbackMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!loginFeedbackMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.loginFeedbackMendixObject = loginFeedbackMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static saml20.proxies.LoginFeedback initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.LoginFeedback(context, mendixObject);
	}

	public static saml20.proxies.LoginFeedback load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.LoginFeedback.initialize(context, mendixObject);
	}

	/**
	 * @return value of LoginAllowed
	 */
	public final java.lang.Boolean getLoginAllowed()
	{
		return getLoginAllowed(getContext());
	}

	/**
	 * @param context
	 * @return value of LoginAllowed
	 */
	public final java.lang.Boolean getLoginAllowed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.LoginAllowed.toString());
	}

	/**
	 * Set value of LoginAllowed
	 * @param loginallowed
	 */
	public final void setLoginAllowed(java.lang.Boolean loginallowed)
	{
		setLoginAllowed(getContext(), loginallowed);
	}

	/**
	 * Set value of LoginAllowed
	 * @param context
	 * @param loginallowed
	 */
	public final void setLoginAllowed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean loginallowed)
	{
		getMendixObject().setValue(context, MemberNames.LoginAllowed.toString(), loginallowed);
	}

	/**
	 * @return value of FeedbackMessageHTML
	 */
	public final java.lang.String getFeedbackMessageHTML()
	{
		return getFeedbackMessageHTML(getContext());
	}

	/**
	 * @param context
	 * @return value of FeedbackMessageHTML
	 */
	public final java.lang.String getFeedbackMessageHTML(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FeedbackMessageHTML.toString());
	}

	/**
	 * Set value of FeedbackMessageHTML
	 * @param feedbackmessagehtml
	 */
	public final void setFeedbackMessageHTML(java.lang.String feedbackmessagehtml)
	{
		setFeedbackMessageHTML(getContext(), feedbackmessagehtml);
	}

	/**
	 * Set value of FeedbackMessageHTML
	 * @param context
	 * @param feedbackmessagehtml
	 */
	public final void setFeedbackMessageHTML(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String feedbackmessagehtml)
	{
		getMendixObject().setValue(context, MemberNames.FeedbackMessageHTML.toString(), feedbackmessagehtml);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return loginFeedbackMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.LoginFeedback that = (saml20.proxies.LoginFeedback) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
