// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public enum ServiceType
{
	SingleSignOnService("0018021e-2e8f-4f02-9f7d-426121cff55e"),
	AssertionIDRequestService("d1503f82-db7f-4457-96d0-a6a98f7dac80"),
	ManageNameIDService("487c5214-424c-44a9-b910-a1ebe73437e5"),
	NameIDMappingService("d1977923-f15e-4b17-bbf2-4b2d26856e38"),
	SingleLogoutService("163286fa-8894-42b5-a93c-483cd225f079"),
	AssertionConsumerService("1a2c867e-0fbf-4966-9b48-863a48e6b8e0"),
	ArtifactResolutionService("1e24f3b9-bd73-46e4-8162-0f7a62ee8cc6"),
	AttributeService("e7c5cbe4-6bf7-437e-8698-2750aadceed9");

	private final java.lang.String i18nCaptionKey;
	
	private ServiceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
