// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class SPAttributeConsumingService implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sPAttributeConsumingServiceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.SPAttributeConsumingService";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServiceName("ServiceName"),
		lang("lang"),
		index("index"),
		isDefault("isDefault"),
		isActive("isActive"),
		LoginType("LoginType"),
		SPAttributeConsumingService_SSOConfiguration("SAML20.SPAttributeConsumingService_SSOConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SPAttributeConsumingService(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SPAttributeConsumingService(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sPAttributeConsumingServiceMendixObject)
	{
		if (sPAttributeConsumingServiceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!sPAttributeConsumingServiceMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sPAttributeConsumingServiceMendixObject = sPAttributeConsumingServiceMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static saml20.proxies.SPAttributeConsumingService initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.SPAttributeConsumingService(context, mendixObject);
	}

	public static saml20.proxies.SPAttributeConsumingService load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.SPAttributeConsumingService.initialize(context, mendixObject);
	}

	public static java.util.List<saml20.proxies.SPAttributeConsumingService> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> saml20.proxies.SPAttributeConsumingService.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ServiceName
	 */
	public final java.lang.String getServiceName()
	{
		return getServiceName(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceName
	 */
	public final java.lang.String getServiceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServiceName.toString());
	}

	/**
	 * Set value of ServiceName
	 * @param servicename
	 */
	public final void setServiceName(java.lang.String servicename)
	{
		setServiceName(getContext(), servicename);
	}

	/**
	 * Set value of ServiceName
	 * @param context
	 * @param servicename
	 */
	public final void setServiceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String servicename)
	{
		getMendixObject().setValue(context, MemberNames.ServiceName.toString(), servicename);
	}

	/**
	 * @return value of lang
	 */
	public final java.lang.String getlang()
	{
		return getlang(getContext());
	}

	/**
	 * @param context
	 * @return value of lang
	 */
	public final java.lang.String getlang(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.lang.toString());
	}

	/**
	 * Set value of lang
	 * @param lang
	 */
	public final void setlang(java.lang.String lang)
	{
		setlang(getContext(), lang);
	}

	/**
	 * Set value of lang
	 * @param context
	 * @param lang
	 */
	public final void setlang(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lang)
	{
		getMendixObject().setValue(context, MemberNames.lang.toString(), lang);
	}

	/**
	 * @return value of index
	 */
	public final java.lang.Integer getindex()
	{
		return getindex(getContext());
	}

	/**
	 * @param context
	 * @return value of index
	 */
	public final java.lang.Integer getindex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.index.toString());
	}

	/**
	 * Set value of index
	 * @param index
	 */
	public final void setindex(java.lang.Integer index)
	{
		setindex(getContext(), index);
	}

	/**
	 * Set value of index
	 * @param context
	 * @param index
	 */
	public final void setindex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer index)
	{
		getMendixObject().setValue(context, MemberNames.index.toString(), index);
	}

	/**
	 * @return value of isDefault
	 */
	public final java.lang.Boolean getisDefault()
	{
		return getisDefault(getContext());
	}

	/**
	 * @param context
	 * @return value of isDefault
	 */
	public final java.lang.Boolean getisDefault(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isDefault.toString());
	}

	/**
	 * Set value of isDefault
	 * @param isdefault
	 */
	public final void setisDefault(java.lang.Boolean isdefault)
	{
		setisDefault(getContext(), isdefault);
	}

	/**
	 * Set value of isDefault
	 * @param context
	 * @param isdefault
	 */
	public final void setisDefault(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdefault)
	{
		getMendixObject().setValue(context, MemberNames.isDefault.toString(), isdefault);
	}

	/**
	 * @return value of isActive
	 */
	public final java.lang.Boolean getisActive()
	{
		return getisActive(getContext());
	}

	/**
	 * @param context
	 * @return value of isActive
	 */
	public final java.lang.Boolean getisActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isActive.toString());
	}

	/**
	 * Set value of isActive
	 * @param isactive
	 */
	public final void setisActive(java.lang.Boolean isactive)
	{
		setisActive(getContext(), isactive);
	}

	/**
	 * Set value of isActive
	 * @param context
	 * @param isactive
	 */
	public final void setisActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isactive)
	{
		getMendixObject().setValue(context, MemberNames.isActive.toString(), isactive);
	}

	/**
	 * Get value of LoginType
	 * @param logintype
	 */
	public final saml20.proxies.Enum_Attribute_Consuming_Login_Type getLoginType()
	{
		return getLoginType(getContext());
	}

	/**
	 * @param context
	 * @return value of LoginType
	 */
	public final saml20.proxies.Enum_Attribute_Consuming_Login_Type getLoginType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.LoginType.toString());
		if (obj == null) {
			return null;
		}
		return saml20.proxies.Enum_Attribute_Consuming_Login_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of LoginType
	 * @param logintype
	 */
	public final void setLoginType(saml20.proxies.Enum_Attribute_Consuming_Login_Type logintype)
	{
		setLoginType(getContext(), logintype);
	}

	/**
	 * Set value of LoginType
	 * @param context
	 * @param logintype
	 */
	public final void setLoginType(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.Enum_Attribute_Consuming_Login_Type logintype)
	{
		if (logintype != null) {
			getMendixObject().setValue(context, MemberNames.LoginType.toString(), logintype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.LoginType.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SPAttributeConsumingService_SSOConfiguration
	 */
	public final saml20.proxies.SSOConfiguration getSPAttributeConsumingService_SSOConfiguration() throws com.mendix.core.CoreException
	{
		return getSPAttributeConsumingService_SSOConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of SPAttributeConsumingService_SSOConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final saml20.proxies.SSOConfiguration getSPAttributeConsumingService_SSOConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.SSOConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SPAttributeConsumingService_SSOConfiguration.toString());
		if (identifier != null) {
			result = saml20.proxies.SSOConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SPAttributeConsumingService_SSOConfiguration
	 * @param spattributeconsumingservice_ssoconfiguration
	 */
	public final void setSPAttributeConsumingService_SSOConfiguration(saml20.proxies.SSOConfiguration spattributeconsumingservice_ssoconfiguration)
	{
		setSPAttributeConsumingService_SSOConfiguration(getContext(), spattributeconsumingservice_ssoconfiguration);
	}

	/**
	 * Set value of SPAttributeConsumingService_SSOConfiguration
	 * @param context
	 * @param spattributeconsumingservice_ssoconfiguration
	 */
	public final void setSPAttributeConsumingService_SSOConfiguration(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.SSOConfiguration spattributeconsumingservice_ssoconfiguration)
	{
		if (spattributeconsumingservice_ssoconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.SPAttributeConsumingService_SSOConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SPAttributeConsumingService_SSOConfiguration.toString(), spattributeconsumingservice_ssoconfiguration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sPAttributeConsumingServiceMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.SPAttributeConsumingService that = (saml20.proxies.SPAttributeConsumingService) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
