// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public enum TypeOfAuthnContext
{
	MINIMUM("77ea8628-4022-4018-9523-327dacc325aa"),
	MAXIMUM("ad05e5e8-0f24-4fd2-9ade-cf7a2c8eda2a"),
	EXACT("59556866-5c1e-49fb-8f7e-0de59e0b2e55"),
	BETTER("acfdf175-78a2-474e-b947-c756e7cdb33f");

	private final java.lang.String i18nCaptionKey;
	
	private TypeOfAuthnContext(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
