// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class UserClaimValue implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userClaimValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.UserClaimValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		UserClaimValue_UserClaim("SAML20.UserClaimValue_UserClaim");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserClaimValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UserClaimValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userClaimValueMendixObject)
	{
		if (userClaimValueMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!userClaimValueMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.userClaimValueMendixObject = userClaimValueMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static saml20.proxies.UserClaimValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.UserClaimValue(context, mendixObject);
	}

	public static saml20.proxies.UserClaimValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.UserClaimValue.initialize(context, mendixObject);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserClaimValue_UserClaim
	 */
	public final usercommons.proxies.UserClaim getUserClaimValue_UserClaim() throws com.mendix.core.CoreException
	{
		return getUserClaimValue_UserClaim(getContext());
	}

	/**
	 * @param context
	 * @return value of UserClaimValue_UserClaim
	 * @throws com.mendix.core.CoreException
	 */
	public final usercommons.proxies.UserClaim getUserClaimValue_UserClaim(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usercommons.proxies.UserClaim result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserClaimValue_UserClaim.toString());
		if (identifier != null) {
			result = usercommons.proxies.UserClaim.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserClaimValue_UserClaim
	 * @param userclaimvalue_userclaim
	 */
	public final void setUserClaimValue_UserClaim(usercommons.proxies.UserClaim userclaimvalue_userclaim)
	{
		setUserClaimValue_UserClaim(getContext(), userclaimvalue_userclaim);
	}

	/**
	 * Set value of UserClaimValue_UserClaim
	 * @param context
	 * @param userclaimvalue_userclaim
	 */
	public final void setUserClaimValue_UserClaim(com.mendix.systemwideinterfaces.core.IContext context, usercommons.proxies.UserClaim userclaimvalue_userclaim)
	{
		if (userclaimvalue_userclaim == null) {
			getMendixObject().setValue(context, MemberNames.UserClaimValue_UserClaim.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserClaimValue_UserClaim.toString(), userclaimvalue_userclaim.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userClaimValueMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.UserClaimValue that = (saml20.proxies.UserClaimValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
