// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_inlinespc.proxies;

public enum ENUM_SPCAnnotateEntries
{
	By_Subgroup("33836ba4-a879-479b-8f76-a1f0f91cbc7a"),
	By_Data_Value("7ec38b1c-af52-42dc-bbef-cad4d370250b");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_SPCAnnotateEntries(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
