// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_showcase.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the EXCR_Showcase module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DropdownSamples_ShowPageBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_Showcase.ACT_DropdownSamples_ShowPage");
		return builder;
	}

	public static void aCT_DropdownSamples_ShowPage(IContext context)
	{
		aCT_DropdownSamples_ShowPageBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder emptyMicroflowBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_Showcase.EmptyMicroflow");
		return builder;
	}

	public static void emptyMicroflow(IContext context)
	{
		emptyMicroflowBuilder().execute(context);
	}
}
