// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_holdmanagement_api.proxies;

public class ReqHoldManagementList implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqHoldManagementListMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_HoldManagement_API.ReqHoldManagementList";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Parameters_ReqHoldManagementList("EXCR_HoldManagement_API.Parameters_ReqHoldManagementList");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqHoldManagementList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqHoldManagementList(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqHoldManagementListMendixObject)
	{
		if (reqHoldManagementListMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqHoldManagementListMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqHoldManagementListMendixObject = reqHoldManagementListMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_holdmanagement_api.proxies.ReqHoldManagementList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_holdmanagement_api.proxies.ReqHoldManagementList(context, mendixObject);
	}

	public static excr_holdmanagement_api.proxies.ReqHoldManagementList load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_holdmanagement_api.proxies.ReqHoldManagementList.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parameters_ReqHoldManagementList
	 */
	public final excr_holdmanagement_api.proxies.Parameters getParameters_ReqHoldManagementList() throws com.mendix.core.CoreException
	{
		return getParameters_ReqHoldManagementList(getContext());
	}

	/**
	 * @param context
	 * @return value of Parameters_ReqHoldManagementList
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_holdmanagement_api.proxies.Parameters getParameters_ReqHoldManagementList(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_holdmanagement_api.proxies.Parameters result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parameters_ReqHoldManagementList.toString());
		if (identifier != null) {
			result = excr_holdmanagement_api.proxies.Parameters.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parameters_ReqHoldManagementList
	 * @param parameters_reqholdmanagementlist
	 */
	public final void setParameters_ReqHoldManagementList(excr_holdmanagement_api.proxies.Parameters parameters_reqholdmanagementlist)
	{
		setParameters_ReqHoldManagementList(getContext(), parameters_reqholdmanagementlist);
	}

	/**
	 * Set value of Parameters_ReqHoldManagementList
	 * @param context
	 * @param parameters_reqholdmanagementlist
	 */
	public final void setParameters_ReqHoldManagementList(com.mendix.systemwideinterfaces.core.IContext context, excr_holdmanagement_api.proxies.Parameters parameters_reqholdmanagementlist)
	{
		if (parameters_reqholdmanagementlist == null) {
			getMendixObject().setValue(context, MemberNames.Parameters_ReqHoldManagementList.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parameters_ReqHoldManagementList.toString(), parameters_reqholdmanagementlist.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqHoldManagementListMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_holdmanagement_api.proxies.ReqHoldManagementList that = (excr_holdmanagement_api.proxies.ReqHoldManagementList) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
