// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_holdmanagement_api.proxies;

public class ReqReleaseObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqReleaseObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_HoldManagement_API.ReqReleaseObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HoldAction("HoldAction"),
		ReleaseMessage("ReleaseMessage"),
		OnHold("OnHold"),
		OnHoldObjectType("OnHoldObjectType"),
		OnHoldObjectName("OnHoldObjectName"),
		OnHoldObjectRevision("OnHoldObjectRevision"),
		ReqReleaseReason_ReqReleaseObject("EXCR_HoldManagement_API.ReqReleaseReason_ReqReleaseObject");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqReleaseObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqReleaseObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqReleaseObjectMendixObject)
	{
		if (reqReleaseObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqReleaseObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqReleaseObjectMendixObject = reqReleaseObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_holdmanagement_api.proxies.ReqReleaseObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_holdmanagement_api.proxies.ReqReleaseObject(context, mendixObject);
	}

	public static excr_holdmanagement_api.proxies.ReqReleaseObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_holdmanagement_api.proxies.ReqReleaseObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of HoldAction
	 */
	public final java.lang.String getHoldAction()
	{
		return getHoldAction(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldAction
	 */
	public final java.lang.String getHoldAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldAction.toString());
	}

	/**
	 * Set value of HoldAction
	 * @param holdaction
	 */
	public final void setHoldAction(java.lang.String holdaction)
	{
		setHoldAction(getContext(), holdaction);
	}

	/**
	 * Set value of HoldAction
	 * @param context
	 * @param holdaction
	 */
	public final void setHoldAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdaction)
	{
		getMendixObject().setValue(context, MemberNames.HoldAction.toString(), holdaction);
	}

	/**
	 * @return value of ReleaseMessage
	 */
	public final java.lang.String getReleaseMessage()
	{
		return getReleaseMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ReleaseMessage
	 */
	public final java.lang.String getReleaseMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReleaseMessage.toString());
	}

	/**
	 * Set value of ReleaseMessage
	 * @param releasemessage
	 */
	public final void setReleaseMessage(java.lang.String releasemessage)
	{
		setReleaseMessage(getContext(), releasemessage);
	}

	/**
	 * Set value of ReleaseMessage
	 * @param context
	 * @param releasemessage
	 */
	public final void setReleaseMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String releasemessage)
	{
		getMendixObject().setValue(context, MemberNames.ReleaseMessage.toString(), releasemessage);
	}

	/**
	 * @return value of OnHold
	 */
	public final java.lang.String getOnHold()
	{
		return getOnHold(getContext());
	}

	/**
	 * @param context
	 * @return value of OnHold
	 */
	public final java.lang.String getOnHold(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnHold.toString());
	}

	/**
	 * Set value of OnHold
	 * @param onhold
	 */
	public final void setOnHold(java.lang.String onhold)
	{
		setOnHold(getContext(), onhold);
	}

	/**
	 * Set value of OnHold
	 * @param context
	 * @param onhold
	 */
	public final void setOnHold(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onhold)
	{
		getMendixObject().setValue(context, MemberNames.OnHold.toString(), onhold);
	}

	/**
	 * @return value of OnHoldObjectType
	 */
	public final java.lang.String getOnHoldObjectType()
	{
		return getOnHoldObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of OnHoldObjectType
	 */
	public final java.lang.String getOnHoldObjectType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnHoldObjectType.toString());
	}

	/**
	 * Set value of OnHoldObjectType
	 * @param onholdobjecttype
	 */
	public final void setOnHoldObjectType(java.lang.String onholdobjecttype)
	{
		setOnHoldObjectType(getContext(), onholdobjecttype);
	}

	/**
	 * Set value of OnHoldObjectType
	 * @param context
	 * @param onholdobjecttype
	 */
	public final void setOnHoldObjectType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onholdobjecttype)
	{
		getMendixObject().setValue(context, MemberNames.OnHoldObjectType.toString(), onholdobjecttype);
	}

	/**
	 * @return value of OnHoldObjectName
	 */
	public final java.lang.String getOnHoldObjectName()
	{
		return getOnHoldObjectName(getContext());
	}

	/**
	 * @param context
	 * @return value of OnHoldObjectName
	 */
	public final java.lang.String getOnHoldObjectName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnHoldObjectName.toString());
	}

	/**
	 * Set value of OnHoldObjectName
	 * @param onholdobjectname
	 */
	public final void setOnHoldObjectName(java.lang.String onholdobjectname)
	{
		setOnHoldObjectName(getContext(), onholdobjectname);
	}

	/**
	 * Set value of OnHoldObjectName
	 * @param context
	 * @param onholdobjectname
	 */
	public final void setOnHoldObjectName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onholdobjectname)
	{
		getMendixObject().setValue(context, MemberNames.OnHoldObjectName.toString(), onholdobjectname);
	}

	/**
	 * @return value of OnHoldObjectRevision
	 */
	public final java.lang.String getOnHoldObjectRevision()
	{
		return getOnHoldObjectRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of OnHoldObjectRevision
	 */
	public final java.lang.String getOnHoldObjectRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnHoldObjectRevision.toString());
	}

	/**
	 * Set value of OnHoldObjectRevision
	 * @param onholdobjectrevision
	 */
	public final void setOnHoldObjectRevision(java.lang.String onholdobjectrevision)
	{
		setOnHoldObjectRevision(getContext(), onholdobjectrevision);
	}

	/**
	 * Set value of OnHoldObjectRevision
	 * @param context
	 * @param onholdobjectrevision
	 */
	public final void setOnHoldObjectRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onholdobjectrevision)
	{
		getMendixObject().setValue(context, MemberNames.OnHoldObjectRevision.toString(), onholdobjectrevision);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqReleaseReason_ReqReleaseObject
	 */
	public final excr_holdmanagement_api.proxies.ReqReleaseReason getReqReleaseReason_ReqReleaseObject() throws com.mendix.core.CoreException
	{
		return getReqReleaseReason_ReqReleaseObject(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqReleaseReason_ReqReleaseObject
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_holdmanagement_api.proxies.ReqReleaseReason getReqReleaseReason_ReqReleaseObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_holdmanagement_api.proxies.ReqReleaseReason result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqReleaseReason_ReqReleaseObject.toString());
		if (identifier != null) {
			result = excr_holdmanagement_api.proxies.ReqReleaseReason.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqReleaseReason_ReqReleaseObject
	 * @param reqreleasereason_reqreleaseobject
	 */
	public final void setReqReleaseReason_ReqReleaseObject(excr_holdmanagement_api.proxies.ReqReleaseReason reqreleasereason_reqreleaseobject)
	{
		setReqReleaseReason_ReqReleaseObject(getContext(), reqreleasereason_reqreleaseobject);
	}

	/**
	 * Set value of ReqReleaseReason_ReqReleaseObject
	 * @param context
	 * @param reqreleasereason_reqreleaseobject
	 */
	public final void setReqReleaseReason_ReqReleaseObject(com.mendix.systemwideinterfaces.core.IContext context, excr_holdmanagement_api.proxies.ReqReleaseReason reqreleasereason_reqreleaseobject)
	{
		if (reqreleasereason_reqreleaseobject == null) {
			getMendixObject().setValue(context, MemberNames.ReqReleaseReason_ReqReleaseObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqReleaseReason_ReqReleaseObject.toString(), reqreleasereason_reqreleaseobject.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqReleaseObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_holdmanagement_api.proxies.ReqReleaseObject that = (excr_holdmanagement_api.proxies.ReqReleaseObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
