// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_holdmanagement_api.proxies;

public class ResHoldManagementObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resHoldManagementObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_HoldManagement_API.ResHoldManagementObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ObjectType("ObjectType"),
		ObjectName("ObjectName"),
		ProductHoldRevision("ProductHoldRevision"),
		MfgOrderProductName("MfgOrderProductName"),
		MfgOrderProductRevision("MfgOrderProductRevision"),
		HoldMessage("HoldMessage"),
		HoldReasonName("HoldReasonName"),
		OnHoldDate("OnHoldDate"),
		MfgOrderQty("MfgOrderQty"),
		MfgOrderOnHoldQty("MfgOrderOnHoldQty"),
		ProductQty("ProductQty"),
		ResHoldManagementObject_ResHoldManagementObjectList("EXCR_HoldManagement_API.ResHoldManagementObject_ResHoldManagementObjectList");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResHoldManagementObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResHoldManagementObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resHoldManagementObjectMendixObject)
	{
		if (resHoldManagementObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resHoldManagementObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resHoldManagementObjectMendixObject = resHoldManagementObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_holdmanagement_api.proxies.ResHoldManagementObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_holdmanagement_api.proxies.ResHoldManagementObject(context, mendixObject);
	}

	public static excr_holdmanagement_api.proxies.ResHoldManagementObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_holdmanagement_api.proxies.ResHoldManagementObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of ObjectType
	 */
	public final java.lang.String getObjectType()
	{
		return getObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectType
	 */
	public final java.lang.String getObjectType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectType.toString());
	}

	/**
	 * Set value of ObjectType
	 * @param objecttype
	 */
	public final void setObjectType(java.lang.String objecttype)
	{
		setObjectType(getContext(), objecttype);
	}

	/**
	 * Set value of ObjectType
	 * @param context
	 * @param objecttype
	 */
	public final void setObjectType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objecttype)
	{
		getMendixObject().setValue(context, MemberNames.ObjectType.toString(), objecttype);
	}

	/**
	 * @return value of ObjectName
	 */
	public final java.lang.String getObjectName()
	{
		return getObjectName(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectName
	 */
	public final java.lang.String getObjectName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectName.toString());
	}

	/**
	 * Set value of ObjectName
	 * @param objectname
	 */
	public final void setObjectName(java.lang.String objectname)
	{
		setObjectName(getContext(), objectname);
	}

	/**
	 * Set value of ObjectName
	 * @param context
	 * @param objectname
	 */
	public final void setObjectName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objectname)
	{
		getMendixObject().setValue(context, MemberNames.ObjectName.toString(), objectname);
	}

	/**
	 * @return value of ProductHoldRevision
	 */
	public final java.lang.String getProductHoldRevision()
	{
		return getProductHoldRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductHoldRevision
	 */
	public final java.lang.String getProductHoldRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductHoldRevision.toString());
	}

	/**
	 * Set value of ProductHoldRevision
	 * @param productholdrevision
	 */
	public final void setProductHoldRevision(java.lang.String productholdrevision)
	{
		setProductHoldRevision(getContext(), productholdrevision);
	}

	/**
	 * Set value of ProductHoldRevision
	 * @param context
	 * @param productholdrevision
	 */
	public final void setProductHoldRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productholdrevision)
	{
		getMendixObject().setValue(context, MemberNames.ProductHoldRevision.toString(), productholdrevision);
	}

	/**
	 * @return value of MfgOrderProductName
	 */
	public final java.lang.String getMfgOrderProductName()
	{
		return getMfgOrderProductName(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrderProductName
	 */
	public final java.lang.String getMfgOrderProductName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MfgOrderProductName.toString());
	}

	/**
	 * Set value of MfgOrderProductName
	 * @param mfgorderproductname
	 */
	public final void setMfgOrderProductName(java.lang.String mfgorderproductname)
	{
		setMfgOrderProductName(getContext(), mfgorderproductname);
	}

	/**
	 * Set value of MfgOrderProductName
	 * @param context
	 * @param mfgorderproductname
	 */
	public final void setMfgOrderProductName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfgorderproductname)
	{
		getMendixObject().setValue(context, MemberNames.MfgOrderProductName.toString(), mfgorderproductname);
	}

	/**
	 * @return value of MfgOrderProductRevision
	 */
	public final java.lang.String getMfgOrderProductRevision()
	{
		return getMfgOrderProductRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrderProductRevision
	 */
	public final java.lang.String getMfgOrderProductRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MfgOrderProductRevision.toString());
	}

	/**
	 * Set value of MfgOrderProductRevision
	 * @param mfgorderproductrevision
	 */
	public final void setMfgOrderProductRevision(java.lang.String mfgorderproductrevision)
	{
		setMfgOrderProductRevision(getContext(), mfgorderproductrevision);
	}

	/**
	 * Set value of MfgOrderProductRevision
	 * @param context
	 * @param mfgorderproductrevision
	 */
	public final void setMfgOrderProductRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfgorderproductrevision)
	{
		getMendixObject().setValue(context, MemberNames.MfgOrderProductRevision.toString(), mfgorderproductrevision);
	}

	/**
	 * @return value of HoldMessage
	 */
	public final java.lang.String getHoldMessage()
	{
		return getHoldMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldMessage
	 */
	public final java.lang.String getHoldMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldMessage.toString());
	}

	/**
	 * Set value of HoldMessage
	 * @param holdmessage
	 */
	public final void setHoldMessage(java.lang.String holdmessage)
	{
		setHoldMessage(getContext(), holdmessage);
	}

	/**
	 * Set value of HoldMessage
	 * @param context
	 * @param holdmessage
	 */
	public final void setHoldMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdmessage)
	{
		getMendixObject().setValue(context, MemberNames.HoldMessage.toString(), holdmessage);
	}

	/**
	 * @return value of HoldReasonName
	 */
	public final java.lang.String getHoldReasonName()
	{
		return getHoldReasonName(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldReasonName
	 */
	public final java.lang.String getHoldReasonName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldReasonName.toString());
	}

	/**
	 * Set value of HoldReasonName
	 * @param holdreasonname
	 */
	public final void setHoldReasonName(java.lang.String holdreasonname)
	{
		setHoldReasonName(getContext(), holdreasonname);
	}

	/**
	 * Set value of HoldReasonName
	 * @param context
	 * @param holdreasonname
	 */
	public final void setHoldReasonName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdreasonname)
	{
		getMendixObject().setValue(context, MemberNames.HoldReasonName.toString(), holdreasonname);
	}

	/**
	 * @return value of OnHoldDate
	 */
	public final java.util.Date getOnHoldDate()
	{
		return getOnHoldDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OnHoldDate
	 */
	public final java.util.Date getOnHoldDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OnHoldDate.toString());
	}

	/**
	 * Set value of OnHoldDate
	 * @param onholddate
	 */
	public final void setOnHoldDate(java.util.Date onholddate)
	{
		setOnHoldDate(getContext(), onholddate);
	}

	/**
	 * Set value of OnHoldDate
	 * @param context
	 * @param onholddate
	 */
	public final void setOnHoldDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date onholddate)
	{
		getMendixObject().setValue(context, MemberNames.OnHoldDate.toString(), onholddate);
	}

	/**
	 * @return value of MfgOrderQty
	 */
	public final java.lang.String getMfgOrderQty()
	{
		return getMfgOrderQty(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrderQty
	 */
	public final java.lang.String getMfgOrderQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MfgOrderQty.toString());
	}

	/**
	 * Set value of MfgOrderQty
	 * @param mfgorderqty
	 */
	public final void setMfgOrderQty(java.lang.String mfgorderqty)
	{
		setMfgOrderQty(getContext(), mfgorderqty);
	}

	/**
	 * Set value of MfgOrderQty
	 * @param context
	 * @param mfgorderqty
	 */
	public final void setMfgOrderQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfgorderqty)
	{
		getMendixObject().setValue(context, MemberNames.MfgOrderQty.toString(), mfgorderqty);
	}

	/**
	 * @return value of MfgOrderOnHoldQty
	 */
	public final java.lang.String getMfgOrderOnHoldQty()
	{
		return getMfgOrderOnHoldQty(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrderOnHoldQty
	 */
	public final java.lang.String getMfgOrderOnHoldQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MfgOrderOnHoldQty.toString());
	}

	/**
	 * Set value of MfgOrderOnHoldQty
	 * @param mfgorderonholdqty
	 */
	public final void setMfgOrderOnHoldQty(java.lang.String mfgorderonholdqty)
	{
		setMfgOrderOnHoldQty(getContext(), mfgorderonholdqty);
	}

	/**
	 * Set value of MfgOrderOnHoldQty
	 * @param context
	 * @param mfgorderonholdqty
	 */
	public final void setMfgOrderOnHoldQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfgorderonholdqty)
	{
		getMendixObject().setValue(context, MemberNames.MfgOrderOnHoldQty.toString(), mfgorderonholdqty);
	}

	/**
	 * @return value of ProductQty
	 */
	public final java.lang.String getProductQty()
	{
		return getProductQty(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductQty
	 */
	public final java.lang.String getProductQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductQty.toString());
	}

	/**
	 * Set value of ProductQty
	 * @param productqty
	 */
	public final void setProductQty(java.lang.String productqty)
	{
		setProductQty(getContext(), productqty);
	}

	/**
	 * Set value of ProductQty
	 * @param context
	 * @param productqty
	 */
	public final void setProductQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productqty)
	{
		getMendixObject().setValue(context, MemberNames.ProductQty.toString(), productqty);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResHoldManagementObject_ResHoldManagementObjectList
	 */
	public final excr_holdmanagement_api.proxies.ResHoldManagementObjectList getResHoldManagementObject_ResHoldManagementObjectList() throws com.mendix.core.CoreException
	{
		return getResHoldManagementObject_ResHoldManagementObjectList(getContext());
	}

	/**
	 * @param context
	 * @return value of ResHoldManagementObject_ResHoldManagementObjectList
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_holdmanagement_api.proxies.ResHoldManagementObjectList getResHoldManagementObject_ResHoldManagementObjectList(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_holdmanagement_api.proxies.ResHoldManagementObjectList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResHoldManagementObject_ResHoldManagementObjectList.toString());
		if (identifier != null) {
			result = excr_holdmanagement_api.proxies.ResHoldManagementObjectList.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResHoldManagementObject_ResHoldManagementObjectList
	 * @param resholdmanagementobject_resholdmanagementobjectlist
	 */
	public final void setResHoldManagementObject_ResHoldManagementObjectList(excr_holdmanagement_api.proxies.ResHoldManagementObjectList resholdmanagementobject_resholdmanagementobjectlist)
	{
		setResHoldManagementObject_ResHoldManagementObjectList(getContext(), resholdmanagementobject_resholdmanagementobjectlist);
	}

	/**
	 * Set value of ResHoldManagementObject_ResHoldManagementObjectList
	 * @param context
	 * @param resholdmanagementobject_resholdmanagementobjectlist
	 */
	public final void setResHoldManagementObject_ResHoldManagementObjectList(com.mendix.systemwideinterfaces.core.IContext context, excr_holdmanagement_api.proxies.ResHoldManagementObjectList resholdmanagementobject_resholdmanagementobjectlist)
	{
		if (resholdmanagementobject_resholdmanagementobjectlist == null) {
			getMendixObject().setValue(context, MemberNames.ResHoldManagementObject_ResHoldManagementObjectList.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResHoldManagementObject_ResHoldManagementObjectList.toString(), resholdmanagementobject_resholdmanagementobjectlist.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resHoldManagementObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_holdmanagement_api.proxies.ResHoldManagementObject that = (excr_holdmanagement_api.proxies.ResHoldManagementObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
