// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_holdmanagement_api.proxies;

public class ResProductForHoldObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resProductForHoldObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_HoldManagement_API.ResProductForHoldObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ObjectType("ObjectType"),
		ObjectName("ObjectName"),
		ProductRevision("ProductRevision"),
		ResProductForHoldObject_ResProductForHoldObjectList("EXCR_HoldManagement_API.ResProductForHoldObject_ResProductForHoldObjectList"),
		ResProductForHoldObject_HoldManagementPageContext("EXCR_HoldManagement_API.ResProductForHoldObject_HoldManagementPageContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResProductForHoldObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResProductForHoldObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resProductForHoldObjectMendixObject)
	{
		if (resProductForHoldObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resProductForHoldObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resProductForHoldObjectMendixObject = resProductForHoldObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_holdmanagement_api.proxies.ResProductForHoldObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_holdmanagement_api.proxies.ResProductForHoldObject(context, mendixObject);
	}

	public static excr_holdmanagement_api.proxies.ResProductForHoldObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_holdmanagement_api.proxies.ResProductForHoldObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of ObjectType
	 */
	public final java.lang.String getObjectType()
	{
		return getObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectType
	 */
	public final java.lang.String getObjectType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectType.toString());
	}

	/**
	 * Set value of ObjectType
	 * @param objecttype
	 */
	public final void setObjectType(java.lang.String objecttype)
	{
		setObjectType(getContext(), objecttype);
	}

	/**
	 * Set value of ObjectType
	 * @param context
	 * @param objecttype
	 */
	public final void setObjectType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objecttype)
	{
		getMendixObject().setValue(context, MemberNames.ObjectType.toString(), objecttype);
	}

	/**
	 * @return value of ObjectName
	 */
	public final java.lang.String getObjectName()
	{
		return getObjectName(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectName
	 */
	public final java.lang.String getObjectName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectName.toString());
	}

	/**
	 * Set value of ObjectName
	 * @param objectname
	 */
	public final void setObjectName(java.lang.String objectname)
	{
		setObjectName(getContext(), objectname);
	}

	/**
	 * Set value of ObjectName
	 * @param context
	 * @param objectname
	 */
	public final void setObjectName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objectname)
	{
		getMendixObject().setValue(context, MemberNames.ObjectName.toString(), objectname);
	}

	/**
	 * @return value of ProductRevision
	 */
	public final java.lang.String getProductRevision()
	{
		return getProductRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductRevision
	 */
	public final java.lang.String getProductRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductRevision.toString());
	}

	/**
	 * Set value of ProductRevision
	 * @param productrevision
	 */
	public final void setProductRevision(java.lang.String productrevision)
	{
		setProductRevision(getContext(), productrevision);
	}

	/**
	 * Set value of ProductRevision
	 * @param context
	 * @param productrevision
	 */
	public final void setProductRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productrevision)
	{
		getMendixObject().setValue(context, MemberNames.ProductRevision.toString(), productrevision);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResProductForHoldObject_ResProductForHoldObjectList
	 */
	public final excr_holdmanagement_api.proxies.ResProductForHoldObjectList getResProductForHoldObject_ResProductForHoldObjectList() throws com.mendix.core.CoreException
	{
		return getResProductForHoldObject_ResProductForHoldObjectList(getContext());
	}

	/**
	 * @param context
	 * @return value of ResProductForHoldObject_ResProductForHoldObjectList
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_holdmanagement_api.proxies.ResProductForHoldObjectList getResProductForHoldObject_ResProductForHoldObjectList(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_holdmanagement_api.proxies.ResProductForHoldObjectList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResProductForHoldObject_ResProductForHoldObjectList.toString());
		if (identifier != null) {
			result = excr_holdmanagement_api.proxies.ResProductForHoldObjectList.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResProductForHoldObject_ResProductForHoldObjectList
	 * @param resproductforholdobject_resproductforholdobjectlist
	 */
	public final void setResProductForHoldObject_ResProductForHoldObjectList(excr_holdmanagement_api.proxies.ResProductForHoldObjectList resproductforholdobject_resproductforholdobjectlist)
	{
		setResProductForHoldObject_ResProductForHoldObjectList(getContext(), resproductforholdobject_resproductforholdobjectlist);
	}

	/**
	 * Set value of ResProductForHoldObject_ResProductForHoldObjectList
	 * @param context
	 * @param resproductforholdobject_resproductforholdobjectlist
	 */
	public final void setResProductForHoldObject_ResProductForHoldObjectList(com.mendix.systemwideinterfaces.core.IContext context, excr_holdmanagement_api.proxies.ResProductForHoldObjectList resproductforholdobject_resproductforholdobjectlist)
	{
		if (resproductforholdobject_resproductforholdobjectlist == null) {
			getMendixObject().setValue(context, MemberNames.ResProductForHoldObject_ResProductForHoldObjectList.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResProductForHoldObject_ResProductForHoldObjectList.toString(), resproductforholdobject_resproductforholdobjectlist.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResProductForHoldObject_HoldManagementPageContext
	 */
	public final excr_holdmanagement.proxies.HoldManagementPageContext getResProductForHoldObject_HoldManagementPageContext() throws com.mendix.core.CoreException
	{
		return getResProductForHoldObject_HoldManagementPageContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ResProductForHoldObject_HoldManagementPageContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_holdmanagement.proxies.HoldManagementPageContext getResProductForHoldObject_HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_holdmanagement.proxies.HoldManagementPageContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResProductForHoldObject_HoldManagementPageContext.toString());
		if (identifier != null) {
			result = excr_holdmanagement.proxies.HoldManagementPageContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResProductForHoldObject_HoldManagementPageContext
	 * @param resproductforholdobject_holdmanagementpagecontext
	 */
	public final void setResProductForHoldObject_HoldManagementPageContext(excr_holdmanagement.proxies.HoldManagementPageContext resproductforholdobject_holdmanagementpagecontext)
	{
		setResProductForHoldObject_HoldManagementPageContext(getContext(), resproductforholdobject_holdmanagementpagecontext);
	}

	/**
	 * Set value of ResProductForHoldObject_HoldManagementPageContext
	 * @param context
	 * @param resproductforholdobject_holdmanagementpagecontext
	 */
	public final void setResProductForHoldObject_HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context, excr_holdmanagement.proxies.HoldManagementPageContext resproductforholdobject_holdmanagementpagecontext)
	{
		if (resproductforholdobject_holdmanagementpagecontext == null) {
			getMendixObject().setValue(context, MemberNames.ResProductForHoldObject_HoldManagementPageContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResProductForHoldObject_HoldManagementPageContext.toString(), resproductforholdobject_holdmanagementpagecontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resProductForHoldObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_holdmanagement_api.proxies.ResProductForHoldObject that = (excr_holdmanagement_api.proxies.ResProductForHoldObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
