// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class CalledByTransactionTask implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject calledByTransactionTaskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.CalledByTransactionTask";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TaskName("TaskName"),
		Name("Name"),
		CalledByTransactionTask_ReqMoveInTxnTaskRoot("EXCR_EProcedure_API.CalledByTransactionTask_ReqMoveInTxnTaskRoot"),
		Parent_CalledByTransactionTask("EXCR_EProcedure_API.Parent_CalledByTransactionTask"),
		CalledByTransactionTask_ReqMoveTxnTaskRoot("EXCR_EProcedure_API.CalledByTransactionTask_ReqMoveTxnTaskRoot"),
		CalledByTransactionTask_ReqContainerCollectDataRoot("EXCR_EProcedure_API.CalledByTransactionTask_ReqContainerCollectDataRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject calledByTransactionTaskMendixObject)
	{
		if (calledByTransactionTaskMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!calledByTransactionTaskMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.calledByTransactionTaskMendixObject = calledByTransactionTaskMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.CalledByTransactionTask initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.CalledByTransactionTask(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.CalledByTransactionTask load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.CalledByTransactionTask.initialize(context, mendixObject);
	}

	/**
	 * @return value of TaskName
	 */
	public final java.lang.String getTaskName()
	{
		return getTaskName(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskName
	 */
	public final java.lang.String getTaskName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskName.toString());
	}

	/**
	 * Set value of TaskName
	 * @param taskname
	 */
	public final void setTaskName(java.lang.String taskname)
	{
		setTaskName(getContext(), taskname);
	}

	/**
	 * Set value of TaskName
	 * @param context
	 * @param taskname
	 */
	public final void setTaskName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taskname)
	{
		getMendixObject().setValue(context, MemberNames.TaskName.toString(), taskname);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CalledByTransactionTask_ReqMoveInTxnTaskRoot
	 */
	public final excr_eprocedure_api.proxies.ReqMoveInTxnTaskRoot getCalledByTransactionTask_ReqMoveInTxnTaskRoot() throws com.mendix.core.CoreException
	{
		return getCalledByTransactionTask_ReqMoveInTxnTaskRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of CalledByTransactionTask_ReqMoveInTxnTaskRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqMoveInTxnTaskRoot getCalledByTransactionTask_ReqMoveInTxnTaskRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqMoveInTxnTaskRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CalledByTransactionTask_ReqMoveInTxnTaskRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqMoveInTxnTaskRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CalledByTransactionTask_ReqMoveInTxnTaskRoot
	 * @param calledbytransactiontask_reqmoveintxntaskroot
	 */
	public final void setCalledByTransactionTask_ReqMoveInTxnTaskRoot(excr_eprocedure_api.proxies.ReqMoveInTxnTaskRoot calledbytransactiontask_reqmoveintxntaskroot)
	{
		setCalledByTransactionTask_ReqMoveInTxnTaskRoot(getContext(), calledbytransactiontask_reqmoveintxntaskroot);
	}

	/**
	 * Set value of CalledByTransactionTask_ReqMoveInTxnTaskRoot
	 * @param context
	 * @param calledbytransactiontask_reqmoveintxntaskroot
	 */
	public final void setCalledByTransactionTask_ReqMoveInTxnTaskRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqMoveInTxnTaskRoot calledbytransactiontask_reqmoveintxntaskroot)
	{
		if (calledbytransactiontask_reqmoveintxntaskroot == null) {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqMoveInTxnTaskRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqMoveInTxnTaskRoot.toString(), calledbytransactiontask_reqmoveintxntaskroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_CalledByTransactionTask
	 */
	public final excr_eprocedure_api.proxies.Parent getParent_CalledByTransactionTask() throws com.mendix.core.CoreException
	{
		return getParent_CalledByTransactionTask(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_CalledByTransactionTask
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.Parent getParent_CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.Parent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_CalledByTransactionTask.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.Parent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_CalledByTransactionTask
	 * @param parent_calledbytransactiontask
	 */
	public final void setParent_CalledByTransactionTask(excr_eprocedure_api.proxies.Parent parent_calledbytransactiontask)
	{
		setParent_CalledByTransactionTask(getContext(), parent_calledbytransactiontask);
	}

	/**
	 * Set value of Parent_CalledByTransactionTask
	 * @param context
	 * @param parent_calledbytransactiontask
	 */
	public final void setParent_CalledByTransactionTask(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.Parent parent_calledbytransactiontask)
	{
		if (parent_calledbytransactiontask == null) {
			getMendixObject().setValue(context, MemberNames.Parent_CalledByTransactionTask.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_CalledByTransactionTask.toString(), parent_calledbytransactiontask.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CalledByTransactionTask_ReqMoveTxnTaskRoot
	 */
	public final excr_eprocedure_api.proxies.ReqMoveTxnTaskRoot getCalledByTransactionTask_ReqMoveTxnTaskRoot() throws com.mendix.core.CoreException
	{
		return getCalledByTransactionTask_ReqMoveTxnTaskRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of CalledByTransactionTask_ReqMoveTxnTaskRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqMoveTxnTaskRoot getCalledByTransactionTask_ReqMoveTxnTaskRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqMoveTxnTaskRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CalledByTransactionTask_ReqMoveTxnTaskRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqMoveTxnTaskRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CalledByTransactionTask_ReqMoveTxnTaskRoot
	 * @param calledbytransactiontask_reqmovetxntaskroot
	 */
	public final void setCalledByTransactionTask_ReqMoveTxnTaskRoot(excr_eprocedure_api.proxies.ReqMoveTxnTaskRoot calledbytransactiontask_reqmovetxntaskroot)
	{
		setCalledByTransactionTask_ReqMoveTxnTaskRoot(getContext(), calledbytransactiontask_reqmovetxntaskroot);
	}

	/**
	 * Set value of CalledByTransactionTask_ReqMoveTxnTaskRoot
	 * @param context
	 * @param calledbytransactiontask_reqmovetxntaskroot
	 */
	public final void setCalledByTransactionTask_ReqMoveTxnTaskRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqMoveTxnTaskRoot calledbytransactiontask_reqmovetxntaskroot)
	{
		if (calledbytransactiontask_reqmovetxntaskroot == null) {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqMoveTxnTaskRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqMoveTxnTaskRoot.toString(), calledbytransactiontask_reqmovetxntaskroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CalledByTransactionTask_ReqContainerCollectDataRoot
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRoot getCalledByTransactionTask_ReqContainerCollectDataRoot() throws com.mendix.core.CoreException
	{
		return getCalledByTransactionTask_ReqContainerCollectDataRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of CalledByTransactionTask_ReqContainerCollectDataRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRoot getCalledByTransactionTask_ReqContainerCollectDataRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CalledByTransactionTask_ReqContainerCollectDataRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CalledByTransactionTask_ReqContainerCollectDataRoot
	 * @param calledbytransactiontask_reqcontainercollectdataroot
	 */
	public final void setCalledByTransactionTask_ReqContainerCollectDataRoot(excr_eprocedure_api.proxies.ReqContainerCollectDataRoot calledbytransactiontask_reqcontainercollectdataroot)
	{
		setCalledByTransactionTask_ReqContainerCollectDataRoot(getContext(), calledbytransactiontask_reqcontainercollectdataroot);
	}

	/**
	 * Set value of CalledByTransactionTask_ReqContainerCollectDataRoot
	 * @param context
	 * @param calledbytransactiontask_reqcontainercollectdataroot
	 */
	public final void setCalledByTransactionTask_ReqContainerCollectDataRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataRoot calledbytransactiontask_reqcontainercollectdataroot)
	{
		if (calledbytransactiontask_reqcontainercollectdataroot == null) {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqContainerCollectDataRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CalledByTransactionTask_ReqContainerCollectDataRoot.toString(), calledbytransactiontask_reqcontainercollectdataroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return calledByTransactionTaskMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.CalledByTransactionTask that = (excr_eprocedure_api.proxies.CalledByTransactionTask) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
