// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class CaptureDetail implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject captureDetailMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.CaptureDetail";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		SignerPassword("SignerPassword"),
		CoSignerPassword("CoSignerPassword"),
		Comments("Comments"),
		CaptureDetail_CaptureDetails("EXCR_EProcedure_API.CaptureDetail_CaptureDetails"),
		Signer_CaptureDetail("EXCR_EProcedure_API.Signer_CaptureDetail"),
		CoSigner_CaptureDetail("EXCR_EProcedure_API.CoSigner_CaptureDetail"),
		CosignReason_CaptureDetail("EXCR_EProcedure_API.CosignReason_CaptureDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject captureDetailMendixObject)
	{
		if (captureDetailMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!captureDetailMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.captureDetailMendixObject = captureDetailMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.CaptureDetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.CaptureDetail(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.CaptureDetail load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.CaptureDetail.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of SignerPassword
	 */
	public final java.lang.String getSignerPassword()
	{
		return getSignerPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of SignerPassword
	 */
	public final java.lang.String getSignerPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SignerPassword.toString());
	}

	/**
	 * Set value of SignerPassword
	 * @param signerpassword
	 */
	public final void setSignerPassword(java.lang.String signerpassword)
	{
		setSignerPassword(getContext(), signerpassword);
	}

	/**
	 * Set value of SignerPassword
	 * @param context
	 * @param signerpassword
	 */
	public final void setSignerPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String signerpassword)
	{
		getMendixObject().setValue(context, MemberNames.SignerPassword.toString(), signerpassword);
	}

	/**
	 * @return value of CoSignerPassword
	 */
	public final java.lang.String getCoSignerPassword()
	{
		return getCoSignerPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of CoSignerPassword
	 */
	public final java.lang.String getCoSignerPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CoSignerPassword.toString());
	}

	/**
	 * Set value of CoSignerPassword
	 * @param cosignerpassword
	 */
	public final void setCoSignerPassword(java.lang.String cosignerpassword)
	{
		setCoSignerPassword(getContext(), cosignerpassword);
	}

	/**
	 * Set value of CoSignerPassword
	 * @param context
	 * @param cosignerpassword
	 */
	public final void setCoSignerPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cosignerpassword)
	{
		getMendixObject().setValue(context, MemberNames.CoSignerPassword.toString(), cosignerpassword);
	}

	/**
	 * @return value of Comments
	 */
	public final java.lang.String getComments()
	{
		return getComments(getContext());
	}

	/**
	 * @param context
	 * @return value of Comments
	 */
	public final java.lang.String getComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comments.toString());
	}

	/**
	 * Set value of Comments
	 * @param comments
	 */
	public final void setComments(java.lang.String comments)
	{
		setComments(getContext(), comments);
	}

	/**
	 * Set value of Comments
	 * @param context
	 * @param comments
	 */
	public final void setComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comments)
	{
		getMendixObject().setValue(context, MemberNames.Comments.toString(), comments);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CaptureDetail_CaptureDetails
	 */
	public final excr_eprocedure_api.proxies.CaptureDetails getCaptureDetail_CaptureDetails() throws com.mendix.core.CoreException
	{
		return getCaptureDetail_CaptureDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of CaptureDetail_CaptureDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.CaptureDetails getCaptureDetail_CaptureDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.CaptureDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CaptureDetail_CaptureDetails.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.CaptureDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CaptureDetail_CaptureDetails
	 * @param capturedetail_capturedetails
	 */
	public final void setCaptureDetail_CaptureDetails(excr_eprocedure_api.proxies.CaptureDetails capturedetail_capturedetails)
	{
		setCaptureDetail_CaptureDetails(getContext(), capturedetail_capturedetails);
	}

	/**
	 * Set value of CaptureDetail_CaptureDetails
	 * @param context
	 * @param capturedetail_capturedetails
	 */
	public final void setCaptureDetail_CaptureDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.CaptureDetails capturedetail_capturedetails)
	{
		if (capturedetail_capturedetails == null) {
			getMendixObject().setValue(context, MemberNames.CaptureDetail_CaptureDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CaptureDetail_CaptureDetails.toString(), capturedetail_capturedetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Signer_CaptureDetail
	 */
	public final excr_eprocedure_api.proxies.Signer getSigner_CaptureDetail() throws com.mendix.core.CoreException
	{
		return getSigner_CaptureDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of Signer_CaptureDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.Signer getSigner_CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.Signer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Signer_CaptureDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.Signer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Signer_CaptureDetail
	 * @param signer_capturedetail
	 */
	public final void setSigner_CaptureDetail(excr_eprocedure_api.proxies.Signer signer_capturedetail)
	{
		setSigner_CaptureDetail(getContext(), signer_capturedetail);
	}

	/**
	 * Set value of Signer_CaptureDetail
	 * @param context
	 * @param signer_capturedetail
	 */
	public final void setSigner_CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.Signer signer_capturedetail)
	{
		if (signer_capturedetail == null) {
			getMendixObject().setValue(context, MemberNames.Signer_CaptureDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Signer_CaptureDetail.toString(), signer_capturedetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CoSigner_CaptureDetail
	 */
	public final excr_eprocedure_api.proxies.CoSigner getCoSigner_CaptureDetail() throws com.mendix.core.CoreException
	{
		return getCoSigner_CaptureDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of CoSigner_CaptureDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.CoSigner getCoSigner_CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.CoSigner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CoSigner_CaptureDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.CoSigner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CoSigner_CaptureDetail
	 * @param cosigner_capturedetail
	 */
	public final void setCoSigner_CaptureDetail(excr_eprocedure_api.proxies.CoSigner cosigner_capturedetail)
	{
		setCoSigner_CaptureDetail(getContext(), cosigner_capturedetail);
	}

	/**
	 * Set value of CoSigner_CaptureDetail
	 * @param context
	 * @param cosigner_capturedetail
	 */
	public final void setCoSigner_CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.CoSigner cosigner_capturedetail)
	{
		if (cosigner_capturedetail == null) {
			getMendixObject().setValue(context, MemberNames.CoSigner_CaptureDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CoSigner_CaptureDetail.toString(), cosigner_capturedetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CosignReason_CaptureDetail
	 */
	public final excr_eprocedure_api.proxies.CosignReason getCosignReason_CaptureDetail() throws com.mendix.core.CoreException
	{
		return getCosignReason_CaptureDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of CosignReason_CaptureDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.CosignReason getCosignReason_CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.CosignReason result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CosignReason_CaptureDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.CosignReason.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CosignReason_CaptureDetail
	 * @param cosignreason_capturedetail
	 */
	public final void setCosignReason_CaptureDetail(excr_eprocedure_api.proxies.CosignReason cosignreason_capturedetail)
	{
		setCosignReason_CaptureDetail(getContext(), cosignreason_capturedetail);
	}

	/**
	 * Set value of CosignReason_CaptureDetail
	 * @param context
	 * @param cosignreason_capturedetail
	 */
	public final void setCosignReason_CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.CosignReason cosignreason_capturedetail)
	{
		if (cosignreason_capturedetail == null) {
			getMendixObject().setValue(context, MemberNames.CosignReason_CaptureDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CosignReason_CaptureDetail.toString(), cosignreason_capturedetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return captureDetailMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.CaptureDetail that = (excr_eprocedure_api.proxies.CaptureDetail) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
