// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ContainerRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject containerRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ContainerRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Container_ContainerRoot("EXCR_EProcedure_API.Container_ContainerRoot"),
		EProcedureContext_ContainerRoot("EXCR_EProcedure.EProcedureContext_ContainerRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ContainerRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ContainerRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject containerRootMendixObject)
	{
		if (containerRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!containerRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.containerRootMendixObject = containerRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ContainerRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ContainerRoot(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ContainerRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ContainerRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Container_ContainerRoot
	 */
	public final excr_eprocedure_api.proxies.Container getContainer_ContainerRoot() throws com.mendix.core.CoreException
	{
		return getContainer_ContainerRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Container_ContainerRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.Container getContainer_ContainerRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.Container result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Container_ContainerRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.Container.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Container_ContainerRoot
	 * @param container_containerroot
	 */
	public final void setContainer_ContainerRoot(excr_eprocedure_api.proxies.Container container_containerroot)
	{
		setContainer_ContainerRoot(getContext(), container_containerroot);
	}

	/**
	 * Set value of Container_ContainerRoot
	 * @param context
	 * @param container_containerroot
	 */
	public final void setContainer_ContainerRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.Container container_containerroot)
	{
		if (container_containerroot == null) {
			getMendixObject().setValue(context, MemberNames.Container_ContainerRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Container_ContainerRoot.toString(), container_containerroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EProcedureContext_ContainerRoot
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ContainerRoot() throws com.mendix.core.CoreException
	{
		return getEProcedureContext_ContainerRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of EProcedureContext_ContainerRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ContainerRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure.proxies.EProcedureContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EProcedureContext_ContainerRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure.proxies.EProcedureContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EProcedureContext_ContainerRoot
	 * @param eprocedurecontext_containerroot
	 */
	public final void setEProcedureContext_ContainerRoot(excr_eprocedure.proxies.EProcedureContext eprocedurecontext_containerroot)
	{
		setEProcedureContext_ContainerRoot(getContext(), eprocedurecontext_containerroot);
	}

	/**
	 * Set value of EProcedureContext_ContainerRoot
	 * @param context
	 * @param eprocedurecontext_containerroot
	 */
	public final void setEProcedureContext_ContainerRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure.proxies.EProcedureContext eprocedurecontext_containerroot)
	{
		if (eprocedurecontext_containerroot == null) {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ContainerRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ContainerRoot.toString(), eprocedurecontext_containerroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return containerRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ContainerRoot that = (excr_eprocedure_api.proxies.ContainerRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
