// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class DispositionDetailsReq_Task implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dispositionDetailsReq_TaskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.DispositionDetailsReq_Task";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		DispositionDetailsReq_Task_DispositionDetailsReq_InputData("EXCR_EProcedure_API.DispositionDetailsReq_Task_DispositionDetailsReq_InputData"),
		DispositionDetailsReq_Parent_DispositionDetailsReq_Task("EXCR_EProcedure_API.DispositionDetailsReq_Parent_DispositionDetailsReq_Task");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DispositionDetailsReq_Task(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DispositionDetailsReq_Task(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dispositionDetailsReq_TaskMendixObject)
	{
		if (dispositionDetailsReq_TaskMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!dispositionDetailsReq_TaskMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dispositionDetailsReq_TaskMendixObject = dispositionDetailsReq_TaskMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.DispositionDetailsReq_Task initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.DispositionDetailsReq_Task(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.DispositionDetailsReq_Task load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.DispositionDetailsReq_Task.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DispositionDetailsReq_Task_DispositionDetailsReq_InputData
	 */
	public final excr_eprocedure_api.proxies.DispositionDetailsReq_InputData getDispositionDetailsReq_Task_DispositionDetailsReq_InputData() throws com.mendix.core.CoreException
	{
		return getDispositionDetailsReq_Task_DispositionDetailsReq_InputData(getContext());
	}

	/**
	 * @param context
	 * @return value of DispositionDetailsReq_Task_DispositionDetailsReq_InputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.DispositionDetailsReq_InputData getDispositionDetailsReq_Task_DispositionDetailsReq_InputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.DispositionDetailsReq_InputData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DispositionDetailsReq_Task_DispositionDetailsReq_InputData.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.DispositionDetailsReq_InputData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DispositionDetailsReq_Task_DispositionDetailsReq_InputData
	 * @param dispositiondetailsreq_task_dispositiondetailsreq_inputdata
	 */
	public final void setDispositionDetailsReq_Task_DispositionDetailsReq_InputData(excr_eprocedure_api.proxies.DispositionDetailsReq_InputData dispositiondetailsreq_task_dispositiondetailsreq_inputdata)
	{
		setDispositionDetailsReq_Task_DispositionDetailsReq_InputData(getContext(), dispositiondetailsreq_task_dispositiondetailsreq_inputdata);
	}

	/**
	 * Set value of DispositionDetailsReq_Task_DispositionDetailsReq_InputData
	 * @param context
	 * @param dispositiondetailsreq_task_dispositiondetailsreq_inputdata
	 */
	public final void setDispositionDetailsReq_Task_DispositionDetailsReq_InputData(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.DispositionDetailsReq_InputData dispositiondetailsreq_task_dispositiondetailsreq_inputdata)
	{
		if (dispositiondetailsreq_task_dispositiondetailsreq_inputdata == null) {
			getMendixObject().setValue(context, MemberNames.DispositionDetailsReq_Task_DispositionDetailsReq_InputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DispositionDetailsReq_Task_DispositionDetailsReq_InputData.toString(), dispositiondetailsreq_task_dispositiondetailsreq_inputdata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DispositionDetailsReq_Parent_DispositionDetailsReq_Task
	 */
	public final excr_eprocedure_api.proxies.DispositionDetailsReq_Parent getDispositionDetailsReq_Parent_DispositionDetailsReq_Task() throws com.mendix.core.CoreException
	{
		return getDispositionDetailsReq_Parent_DispositionDetailsReq_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of DispositionDetailsReq_Parent_DispositionDetailsReq_Task
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.DispositionDetailsReq_Parent getDispositionDetailsReq_Parent_DispositionDetailsReq_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.DispositionDetailsReq_Parent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DispositionDetailsReq_Parent_DispositionDetailsReq_Task.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.DispositionDetailsReq_Parent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DispositionDetailsReq_Parent_DispositionDetailsReq_Task
	 * @param dispositiondetailsreq_parent_dispositiondetailsreq_task
	 */
	public final void setDispositionDetailsReq_Parent_DispositionDetailsReq_Task(excr_eprocedure_api.proxies.DispositionDetailsReq_Parent dispositiondetailsreq_parent_dispositiondetailsreq_task)
	{
		setDispositionDetailsReq_Parent_DispositionDetailsReq_Task(getContext(), dispositiondetailsreq_parent_dispositiondetailsreq_task);
	}

	/**
	 * Set value of DispositionDetailsReq_Parent_DispositionDetailsReq_Task
	 * @param context
	 * @param dispositiondetailsreq_parent_dispositiondetailsreq_task
	 */
	public final void setDispositionDetailsReq_Parent_DispositionDetailsReq_Task(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.DispositionDetailsReq_Parent dispositiondetailsreq_parent_dispositiondetailsreq_task)
	{
		if (dispositiondetailsreq_parent_dispositiondetailsreq_task == null) {
			getMendixObject().setValue(context, MemberNames.DispositionDetailsReq_Parent_DispositionDetailsReq_Task.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DispositionDetailsReq_Parent_DispositionDetailsReq_Task.toString(), dispositiondetailsreq_parent_dispositiondetailsreq_task.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dispositionDetailsReq_TaskMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.DispositionDetailsReq_Task that = (excr_eprocedure_api.proxies.DispositionDetailsReq_Task) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
