// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class DispositionDetailsReq_Event implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dispositionDetailsReq_EventMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.DispositionDetailsReq_Event";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EventName("EventName"),
		DispositionDetailsReq_Event_DispositionDetailsReq_Root("EXCR_EProcedure_API.DispositionDetailsReq_Event_DispositionDetailsReq_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DispositionDetailsReq_Event(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DispositionDetailsReq_Event(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dispositionDetailsReq_EventMendixObject)
	{
		if (dispositionDetailsReq_EventMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!dispositionDetailsReq_EventMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dispositionDetailsReq_EventMendixObject = dispositionDetailsReq_EventMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.DispositionDetailsReq_Event initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.DispositionDetailsReq_Event(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.DispositionDetailsReq_Event load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.DispositionDetailsReq_Event.initialize(context, mendixObject);
	}

	/**
	 * @return value of EventName
	 */
	public final java.lang.String getEventName()
	{
		return getEventName(getContext());
	}

	/**
	 * @param context
	 * @return value of EventName
	 */
	public final java.lang.String getEventName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EventName.toString());
	}

	/**
	 * Set value of EventName
	 * @param eventname
	 */
	public final void setEventName(java.lang.String eventname)
	{
		setEventName(getContext(), eventname);
	}

	/**
	 * Set value of EventName
	 * @param context
	 * @param eventname
	 */
	public final void setEventName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String eventname)
	{
		getMendixObject().setValue(context, MemberNames.EventName.toString(), eventname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DispositionDetailsReq_Event_DispositionDetailsReq_Root
	 */
	public final excr_eprocedure_api.proxies.DispositionDetailsReq_Root getDispositionDetailsReq_Event_DispositionDetailsReq_Root() throws com.mendix.core.CoreException
	{
		return getDispositionDetailsReq_Event_DispositionDetailsReq_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of DispositionDetailsReq_Event_DispositionDetailsReq_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.DispositionDetailsReq_Root getDispositionDetailsReq_Event_DispositionDetailsReq_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.DispositionDetailsReq_Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DispositionDetailsReq_Event_DispositionDetailsReq_Root.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.DispositionDetailsReq_Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DispositionDetailsReq_Event_DispositionDetailsReq_Root
	 * @param dispositiondetailsreq_event_dispositiondetailsreq_root
	 */
	public final void setDispositionDetailsReq_Event_DispositionDetailsReq_Root(excr_eprocedure_api.proxies.DispositionDetailsReq_Root dispositiondetailsreq_event_dispositiondetailsreq_root)
	{
		setDispositionDetailsReq_Event_DispositionDetailsReq_Root(getContext(), dispositiondetailsreq_event_dispositiondetailsreq_root);
	}

	/**
	 * Set value of DispositionDetailsReq_Event_DispositionDetailsReq_Root
	 * @param context
	 * @param dispositiondetailsreq_event_dispositiondetailsreq_root
	 */
	public final void setDispositionDetailsReq_Event_DispositionDetailsReq_Root(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.DispositionDetailsReq_Root dispositiondetailsreq_event_dispositiondetailsreq_root)
	{
		if (dispositiondetailsreq_event_dispositiondetailsreq_root == null) {
			getMendixObject().setValue(context, MemberNames.DispositionDetailsReq_Event_DispositionDetailsReq_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DispositionDetailsReq_Event_DispositionDetailsReq_Root.toString(), dispositiondetailsreq_event_dispositiondetailsreq_root.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dispositionDetailsReq_EventMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.DispositionDetailsReq_Event that = (excr_eprocedure_api.proxies.DispositionDetailsReq_Event) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
