// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class DispositionDetailsRes_ValueItem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dispositionDetailsRes_ValueItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.DispositionDetailsRes_ValueItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsConfirmation("IsConfirmation"),
		DispositionDetailsRes_ValueItem_DispositionDetailsRes_Value("EXCR_EProcedure_API.DispositionDetailsRes_ValueItem_DispositionDetailsRes_Value");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DispositionDetailsRes_ValueItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DispositionDetailsRes_ValueItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dispositionDetailsRes_ValueItemMendixObject)
	{
		if (dispositionDetailsRes_ValueItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!dispositionDetailsRes_ValueItemMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dispositionDetailsRes_ValueItemMendixObject = dispositionDetailsRes_ValueItemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.DispositionDetailsRes_ValueItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.DispositionDetailsRes_ValueItem(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.DispositionDetailsRes_ValueItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.DispositionDetailsRes_ValueItem.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsConfirmation
	 */
	public final java.lang.Boolean getIsConfirmation()
	{
		return getIsConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of IsConfirmation
	 */
	public final java.lang.Boolean getIsConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsConfirmation.toString());
	}

	/**
	 * Set value of IsConfirmation
	 * @param isconfirmation
	 */
	public final void setIsConfirmation(java.lang.Boolean isconfirmation)
	{
		setIsConfirmation(getContext(), isconfirmation);
	}

	/**
	 * Set value of IsConfirmation
	 * @param context
	 * @param isconfirmation
	 */
	public final void setIsConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.IsConfirmation.toString(), isconfirmation);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DispositionDetailsRes_ValueItem_DispositionDetailsRes_Value
	 */
	public final excr_eprocedure_api.proxies.DispositionDetailsRes_Value getDispositionDetailsRes_ValueItem_DispositionDetailsRes_Value() throws com.mendix.core.CoreException
	{
		return getDispositionDetailsRes_ValueItem_DispositionDetailsRes_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of DispositionDetailsRes_ValueItem_DispositionDetailsRes_Value
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.DispositionDetailsRes_Value getDispositionDetailsRes_ValueItem_DispositionDetailsRes_Value(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.DispositionDetailsRes_Value result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DispositionDetailsRes_ValueItem_DispositionDetailsRes_Value.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.DispositionDetailsRes_Value.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DispositionDetailsRes_ValueItem_DispositionDetailsRes_Value
	 * @param dispositiondetailsres_valueitem_dispositiondetailsres_value
	 */
	public final void setDispositionDetailsRes_ValueItem_DispositionDetailsRes_Value(excr_eprocedure_api.proxies.DispositionDetailsRes_Value dispositiondetailsres_valueitem_dispositiondetailsres_value)
	{
		setDispositionDetailsRes_ValueItem_DispositionDetailsRes_Value(getContext(), dispositiondetailsres_valueitem_dispositiondetailsres_value);
	}

	/**
	 * Set value of DispositionDetailsRes_ValueItem_DispositionDetailsRes_Value
	 * @param context
	 * @param dispositiondetailsres_valueitem_dispositiondetailsres_value
	 */
	public final void setDispositionDetailsRes_ValueItem_DispositionDetailsRes_Value(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.DispositionDetailsRes_Value dispositiondetailsres_valueitem_dispositiondetailsres_value)
	{
		if (dispositiondetailsres_valueitem_dispositiondetailsres_value == null) {
			getMendixObject().setValue(context, MemberNames.DispositionDetailsRes_ValueItem_DispositionDetailsRes_Value.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DispositionDetailsRes_ValueItem_DispositionDetailsRes_Value.toString(), dispositiondetailsres_valueitem_dispositiondetailsres_value.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dispositionDetailsRes_ValueItemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.DispositionDetailsRes_ValueItem that = (excr_eprocedure_api.proxies.DispositionDetailsRes_ValueItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
