// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class EprocDataCollectionDefParent implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject eprocDataCollectionDefParentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.EprocDataCollectionDefParent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		CDOTypeName("CDOTypeName"),
		Name("Name"),
		Revision("Revision"),
		EprocDataCollectionDefParent_Task("EXCR_EProcedure_API.EprocDataCollectionDefParent_Task");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EprocDataCollectionDefParent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EprocDataCollectionDefParent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject eprocDataCollectionDefParentMendixObject)
	{
		if (eprocDataCollectionDefParentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!eprocDataCollectionDefParentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.eprocDataCollectionDefParentMendixObject = eprocDataCollectionDefParentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.EprocDataCollectionDefParent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.EprocDataCollectionDefParent(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.EprocDataCollectionDefParent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.EprocDataCollectionDefParent.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName()
	{
		return getCDOTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CDOTypeName.toString());
	}

	/**
	 * Set value of CDOTypeName
	 * @param cdotypename
	 */
	public final void setCDOTypeName(java.lang.String cdotypename)
	{
		setCDOTypeName(getContext(), cdotypename);
	}

	/**
	 * Set value of CDOTypeName
	 * @param context
	 * @param cdotypename
	 */
	public final void setCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cdotypename)
	{
		getMendixObject().setValue(context, MemberNames.CDOTypeName.toString(), cdotypename);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EprocDataCollectionDefParent_Task
	 */
	public final excr_eprocedure_api.proxies.Task getEprocDataCollectionDefParent_Task() throws com.mendix.core.CoreException
	{
		return getEprocDataCollectionDefParent_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of EprocDataCollectionDefParent_Task
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.Task getEprocDataCollectionDefParent_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EprocDataCollectionDefParent_Task.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.Task.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EprocDataCollectionDefParent_Task
	 * @param eprocdatacollectiondefparent_task
	 */
	public final void setEprocDataCollectionDefParent_Task(excr_eprocedure_api.proxies.Task eprocdatacollectiondefparent_task)
	{
		setEprocDataCollectionDefParent_Task(getContext(), eprocdatacollectiondefparent_task);
	}

	/**
	 * Set value of EprocDataCollectionDefParent_Task
	 * @param context
	 * @param eprocdatacollectiondefparent_task
	 */
	public final void setEprocDataCollectionDefParent_Task(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.Task eprocdatacollectiondefparent_task)
	{
		if (eprocdatacollectiondefparent_task == null) {
			getMendixObject().setValue(context, MemberNames.EprocDataCollectionDefParent_Task.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EprocDataCollectionDefParent_Task.toString(), eprocdatacollectiondefparent_task.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return eprocDataCollectionDefParentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.EprocDataCollectionDefParent that = (excr_eprocedure_api.proxies.EprocDataCollectionDefParent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
