// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class Event implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject eventMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.Event";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EventName("EventName"),
		Event_ReqFetchDataPointRoot("EXCR_EProcedure_API.Event_ReqFetchDataPointRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Event(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Event(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject eventMendixObject)
	{
		if (eventMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!eventMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.eventMendixObject = eventMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.Event initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.Event(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.Event load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.Event.initialize(context, mendixObject);
	}

	/**
	 * @return value of EventName
	 */
	public final java.lang.String getEventName()
	{
		return getEventName(getContext());
	}

	/**
	 * @param context
	 * @return value of EventName
	 */
	public final java.lang.String getEventName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EventName.toString());
	}

	/**
	 * Set value of EventName
	 * @param eventname
	 */
	public final void setEventName(java.lang.String eventname)
	{
		setEventName(getContext(), eventname);
	}

	/**
	 * Set value of EventName
	 * @param context
	 * @param eventname
	 */
	public final void setEventName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String eventname)
	{
		getMendixObject().setValue(context, MemberNames.EventName.toString(), eventname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Event_ReqFetchDataPointRoot
	 */
	public final excr_eprocedure_api.proxies.ReqFetchDataPointRoot getEvent_ReqFetchDataPointRoot() throws com.mendix.core.CoreException
	{
		return getEvent_ReqFetchDataPointRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Event_ReqFetchDataPointRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqFetchDataPointRoot getEvent_ReqFetchDataPointRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqFetchDataPointRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Event_ReqFetchDataPointRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqFetchDataPointRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Event_ReqFetchDataPointRoot
	 * @param event_reqfetchdatapointroot
	 */
	public final void setEvent_ReqFetchDataPointRoot(excr_eprocedure_api.proxies.ReqFetchDataPointRoot event_reqfetchdatapointroot)
	{
		setEvent_ReqFetchDataPointRoot(getContext(), event_reqfetchdatapointroot);
	}

	/**
	 * Set value of Event_ReqFetchDataPointRoot
	 * @param context
	 * @param event_reqfetchdatapointroot
	 */
	public final void setEvent_ReqFetchDataPointRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqFetchDataPointRoot event_reqfetchdatapointroot)
	{
		if (event_reqfetchdatapointroot == null) {
			getMendixObject().setValue(context, MemberNames.Event_ReqFetchDataPointRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Event_ReqFetchDataPointRoot.toString(), event_reqfetchdatapointroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return eventMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.Event that = (excr_eprocedure_api.proxies.Event) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
