// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ExecuteTaskResponse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject executeTaskResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ExecuteTaskResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TaskName("TaskName"),
		QueryName("QueryName"),
		ParameterName("ParameterName"),
		ResolvedValue("ResolvedValue"),
		DynamicValue("DynamicValue"),
		ExecuteTaskResponse_RootExecuteTaskResponse("EXCR_EProcedure_API.ExecuteTaskResponse_RootExecuteTaskResponse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExecuteTaskResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ExecuteTaskResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject executeTaskResponseMendixObject)
	{
		if (executeTaskResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!executeTaskResponseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.executeTaskResponseMendixObject = executeTaskResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ExecuteTaskResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ExecuteTaskResponse(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ExecuteTaskResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ExecuteTaskResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of TaskName
	 */
	public final java.lang.String getTaskName()
	{
		return getTaskName(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskName
	 */
	public final java.lang.String getTaskName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskName.toString());
	}

	/**
	 * Set value of TaskName
	 * @param taskname
	 */
	public final void setTaskName(java.lang.String taskname)
	{
		setTaskName(getContext(), taskname);
	}

	/**
	 * Set value of TaskName
	 * @param context
	 * @param taskname
	 */
	public final void setTaskName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taskname)
	{
		getMendixObject().setValue(context, MemberNames.TaskName.toString(), taskname);
	}

	/**
	 * @return value of QueryName
	 */
	public final java.lang.String getQueryName()
	{
		return getQueryName(getContext());
	}

	/**
	 * @param context
	 * @return value of QueryName
	 */
	public final java.lang.String getQueryName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QueryName.toString());
	}

	/**
	 * Set value of QueryName
	 * @param queryname
	 */
	public final void setQueryName(java.lang.String queryname)
	{
		setQueryName(getContext(), queryname);
	}

	/**
	 * Set value of QueryName
	 * @param context
	 * @param queryname
	 */
	public final void setQueryName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String queryname)
	{
		getMendixObject().setValue(context, MemberNames.QueryName.toString(), queryname);
	}

	/**
	 * @return value of ParameterName
	 */
	public final java.lang.String getParameterName()
	{
		return getParameterName(getContext());
	}

	/**
	 * @param context
	 * @return value of ParameterName
	 */
	public final java.lang.String getParameterName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParameterName.toString());
	}

	/**
	 * Set value of ParameterName
	 * @param parametername
	 */
	public final void setParameterName(java.lang.String parametername)
	{
		setParameterName(getContext(), parametername);
	}

	/**
	 * Set value of ParameterName
	 * @param context
	 * @param parametername
	 */
	public final void setParameterName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parametername)
	{
		getMendixObject().setValue(context, MemberNames.ParameterName.toString(), parametername);
	}

	/**
	 * @return value of ResolvedValue
	 */
	public final java.lang.String getResolvedValue()
	{
		return getResolvedValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ResolvedValue
	 */
	public final java.lang.String getResolvedValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResolvedValue.toString());
	}

	/**
	 * Set value of ResolvedValue
	 * @param resolvedvalue
	 */
	public final void setResolvedValue(java.lang.String resolvedvalue)
	{
		setResolvedValue(getContext(), resolvedvalue);
	}

	/**
	 * Set value of ResolvedValue
	 * @param context
	 * @param resolvedvalue
	 */
	public final void setResolvedValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resolvedvalue)
	{
		getMendixObject().setValue(context, MemberNames.ResolvedValue.toString(), resolvedvalue);
	}

	/**
	 * @return value of DynamicValue
	 */
	public final java.lang.String getDynamicValue()
	{
		return getDynamicValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DynamicValue
	 */
	public final java.lang.String getDynamicValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DynamicValue.toString());
	}

	/**
	 * Set value of DynamicValue
	 * @param dynamicvalue
	 */
	public final void setDynamicValue(java.lang.String dynamicvalue)
	{
		setDynamicValue(getContext(), dynamicvalue);
	}

	/**
	 * Set value of DynamicValue
	 * @param context
	 * @param dynamicvalue
	 */
	public final void setDynamicValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dynamicvalue)
	{
		getMendixObject().setValue(context, MemberNames.DynamicValue.toString(), dynamicvalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ExecuteTaskResponse_RootExecuteTaskResponse
	 */
	public final excr_eprocedure_api.proxies.RootExecuteTaskResponse getExecuteTaskResponse_RootExecuteTaskResponse() throws com.mendix.core.CoreException
	{
		return getExecuteTaskResponse_RootExecuteTaskResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of ExecuteTaskResponse_RootExecuteTaskResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.RootExecuteTaskResponse getExecuteTaskResponse_RootExecuteTaskResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.RootExecuteTaskResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ExecuteTaskResponse_RootExecuteTaskResponse.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.RootExecuteTaskResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ExecuteTaskResponse_RootExecuteTaskResponse
	 * @param executetaskresponse_rootexecutetaskresponse
	 */
	public final void setExecuteTaskResponse_RootExecuteTaskResponse(excr_eprocedure_api.proxies.RootExecuteTaskResponse executetaskresponse_rootexecutetaskresponse)
	{
		setExecuteTaskResponse_RootExecuteTaskResponse(getContext(), executetaskresponse_rootexecutetaskresponse);
	}

	/**
	 * Set value of ExecuteTaskResponse_RootExecuteTaskResponse
	 * @param context
	 * @param executetaskresponse_rootexecutetaskresponse
	 */
	public final void setExecuteTaskResponse_RootExecuteTaskResponse(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.RootExecuteTaskResponse executetaskresponse_rootexecutetaskresponse)
	{
		if (executetaskresponse_rootexecutetaskresponse == null) {
			getMendixObject().setValue(context, MemberNames.ExecuteTaskResponse_RootExecuteTaskResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ExecuteTaskResponse_RootExecuteTaskResponse.toString(), executetaskresponse_rootexecutetaskresponse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return executeTaskResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ExecuteTaskResponse that = (excr_eprocedure_api.proxies.ExecuteTaskResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
