// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class Factory implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject factoryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.Factory";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Factory_OnlineQueryAPI("EXCR_EProcedure_API.Factory_OnlineQueryAPI");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Factory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Factory(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject factoryMendixObject)
	{
		if (factoryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!factoryMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.factoryMendixObject = factoryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.Factory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.Factory(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.Factory load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.Factory.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Factory_OnlineQueryAPI
	 */
	public final excr_eprocedure_api.proxies.OnlineQueryAPI getFactory_OnlineQueryAPI() throws com.mendix.core.CoreException
	{
		return getFactory_OnlineQueryAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of Factory_OnlineQueryAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.OnlineQueryAPI getFactory_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.OnlineQueryAPI result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Factory_OnlineQueryAPI.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.OnlineQueryAPI.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Factory_OnlineQueryAPI
	 * @param factory_onlinequeryapi
	 */
	public final void setFactory_OnlineQueryAPI(excr_eprocedure_api.proxies.OnlineQueryAPI factory_onlinequeryapi)
	{
		setFactory_OnlineQueryAPI(getContext(), factory_onlinequeryapi);
	}

	/**
	 * Set value of Factory_OnlineQueryAPI
	 * @param context
	 * @param factory_onlinequeryapi
	 */
	public final void setFactory_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.OnlineQueryAPI factory_onlinequeryapi)
	{
		if (factory_onlinequeryapi == null) {
			getMendixObject().setValue(context, MemberNames.Factory_OnlineQueryAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Factory_OnlineQueryAPI.toString(), factory_onlinequeryapi.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return factoryMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.Factory that = (excr_eprocedure_api.proxies.Factory) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
