// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class LocationJsonObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject locationJsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.LocationJsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		OwnerName("OwnerName"),
		OwnerInstanceId("OwnerInstanceId"),
		IsFrozen("IsFrozen"),
		InstanceId("InstanceId"),
		LocationJsonObject_ResLocationRoot("EXCR_EProcedure_API.LocationJsonObject_ResLocationRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LocationJsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected LocationJsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject locationJsonObjectMendixObject)
	{
		if (locationJsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!locationJsonObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.locationJsonObjectMendixObject = locationJsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.LocationJsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.LocationJsonObject(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.LocationJsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.LocationJsonObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName()
	{
		return getOwnerName(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OwnerName.toString());
	}

	/**
	 * Set value of OwnerName
	 * @param ownername
	 */
	public final void setOwnerName(java.lang.String ownername)
	{
		setOwnerName(getContext(), ownername);
	}

	/**
	 * Set value of OwnerName
	 * @param context
	 * @param ownername
	 */
	public final void setOwnerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ownername)
	{
		getMendixObject().setValue(context, MemberNames.OwnerName.toString(), ownername);
	}

	/**
	 * @return value of OwnerInstanceId
	 */
	public final java.lang.String getOwnerInstanceId()
	{
		return getOwnerInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnerInstanceId
	 */
	public final java.lang.String getOwnerInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OwnerInstanceId.toString());
	}

	/**
	 * Set value of OwnerInstanceId
	 * @param ownerinstanceid
	 */
	public final void setOwnerInstanceId(java.lang.String ownerinstanceid)
	{
		setOwnerInstanceId(getContext(), ownerinstanceid);
	}

	/**
	 * Set value of OwnerInstanceId
	 * @param context
	 * @param ownerinstanceid
	 */
	public final void setOwnerInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ownerinstanceid)
	{
		getMendixObject().setValue(context, MemberNames.OwnerInstanceId.toString(), ownerinstanceid);
	}

	/**
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen()
	{
		return getIsFrozen(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IsFrozen.toString());
	}

	/**
	 * Set value of IsFrozen
	 * @param isfrozen
	 */
	public final void setIsFrozen(java.lang.String isfrozen)
	{
		setIsFrozen(getContext(), isfrozen);
	}

	/**
	 * Set value of IsFrozen
	 * @param context
	 * @param isfrozen
	 */
	public final void setIsFrozen(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String isfrozen)
	{
		getMendixObject().setValue(context, MemberNames.IsFrozen.toString(), isfrozen);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LocationJsonObject_ResLocationRoot
	 */
	public final excr_eprocedure_api.proxies.ResLocationRoot getLocationJsonObject_ResLocationRoot() throws com.mendix.core.CoreException
	{
		return getLocationJsonObject_ResLocationRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationJsonObject_ResLocationRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ResLocationRoot getLocationJsonObject_ResLocationRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ResLocationRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LocationJsonObject_ResLocationRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ResLocationRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LocationJsonObject_ResLocationRoot
	 * @param locationjsonobject_reslocationroot
	 */
	public final void setLocationJsonObject_ResLocationRoot(excr_eprocedure_api.proxies.ResLocationRoot locationjsonobject_reslocationroot)
	{
		setLocationJsonObject_ResLocationRoot(getContext(), locationjsonobject_reslocationroot);
	}

	/**
	 * Set value of LocationJsonObject_ResLocationRoot
	 * @param context
	 * @param locationjsonobject_reslocationroot
	 */
	public final void setLocationJsonObject_ResLocationRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ResLocationRoot locationjsonobject_reslocationroot)
	{
		if (locationjsonobject_reslocationroot == null) {
			getMendixObject().setValue(context, MemberNames.LocationJsonObject_ResLocationRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LocationJsonObject_ResLocationRoot.toString(), locationjsonobject_reslocationroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return locationJsonObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.LocationJsonObject that = (excr_eprocedure_api.proxies.LocationJsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
