// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class OnlineQueryAPI implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject onlineQueryAPIMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.OnlineQueryAPI";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Container_OnlineQueryAPI("EXCR_EProcedure_API.Container_OnlineQueryAPI"),
		TaskList_OnlineQueryAPI("EXCR_EProcedure_API.TaskList_OnlineQueryAPI"),
		Factory_OnlineQueryAPI("EXCR_EProcedure_API.Factory_OnlineQueryAPI"),
		Task_OnlineQueryAPI("EXCR_EProcedure_API.Task_OnlineQueryAPI");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject onlineQueryAPIMendixObject)
	{
		if (onlineQueryAPIMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!onlineQueryAPIMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.onlineQueryAPIMendixObject = onlineQueryAPIMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.OnlineQueryAPI initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.OnlineQueryAPI(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.OnlineQueryAPI load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.OnlineQueryAPI.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Container_OnlineQueryAPI
	 */
	public final excr_eprocedure_api.proxies.Container getContainer_OnlineQueryAPI() throws com.mendix.core.CoreException
	{
		return getContainer_OnlineQueryAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of Container_OnlineQueryAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.Container getContainer_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.Container result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Container_OnlineQueryAPI.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.Container.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Container_OnlineQueryAPI
	 * @param container_onlinequeryapi
	 */
	public final void setContainer_OnlineQueryAPI(excr_eprocedure_api.proxies.Container container_onlinequeryapi)
	{
		setContainer_OnlineQueryAPI(getContext(), container_onlinequeryapi);
	}

	/**
	 * Set value of Container_OnlineQueryAPI
	 * @param context
	 * @param container_onlinequeryapi
	 */
	public final void setContainer_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.Container container_onlinequeryapi)
	{
		if (container_onlinequeryapi == null) {
			getMendixObject().setValue(context, MemberNames.Container_OnlineQueryAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Container_OnlineQueryAPI.toString(), container_onlinequeryapi.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_OnlineQueryAPI
	 */
	public final excr_eprocedure_api.proxies.TaskList getTaskList_OnlineQueryAPI() throws com.mendix.core.CoreException
	{
		return getTaskList_OnlineQueryAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_OnlineQueryAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.TaskList getTaskList_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.TaskList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_OnlineQueryAPI.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.TaskList.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_OnlineQueryAPI
	 * @param tasklist_onlinequeryapi
	 */
	public final void setTaskList_OnlineQueryAPI(excr_eprocedure_api.proxies.TaskList tasklist_onlinequeryapi)
	{
		setTaskList_OnlineQueryAPI(getContext(), tasklist_onlinequeryapi);
	}

	/**
	 * Set value of TaskList_OnlineQueryAPI
	 * @param context
	 * @param tasklist_onlinequeryapi
	 */
	public final void setTaskList_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.TaskList tasklist_onlinequeryapi)
	{
		if (tasklist_onlinequeryapi == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_OnlineQueryAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_OnlineQueryAPI.toString(), tasklist_onlinequeryapi.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Factory_OnlineQueryAPI
	 */
	public final excr_eprocedure_api.proxies.Factory getFactory_OnlineQueryAPI() throws com.mendix.core.CoreException
	{
		return getFactory_OnlineQueryAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of Factory_OnlineQueryAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.Factory getFactory_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.Factory result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Factory_OnlineQueryAPI.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.Factory.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Factory_OnlineQueryAPI
	 * @param factory_onlinequeryapi
	 */
	public final void setFactory_OnlineQueryAPI(excr_eprocedure_api.proxies.Factory factory_onlinequeryapi)
	{
		setFactory_OnlineQueryAPI(getContext(), factory_onlinequeryapi);
	}

	/**
	 * Set value of Factory_OnlineQueryAPI
	 * @param context
	 * @param factory_onlinequeryapi
	 */
	public final void setFactory_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.Factory factory_onlinequeryapi)
	{
		if (factory_onlinequeryapi == null) {
			getMendixObject().setValue(context, MemberNames.Factory_OnlineQueryAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Factory_OnlineQueryAPI.toString(), factory_onlinequeryapi.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_OnlineQueryAPI
	 */
	public final excr_eprocedure_api.proxies.Task getTask_OnlineQueryAPI() throws com.mendix.core.CoreException
	{
		return getTask_OnlineQueryAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_OnlineQueryAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.Task getTask_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_OnlineQueryAPI.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.Task.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_OnlineQueryAPI
	 * @param task_onlinequeryapi
	 */
	public final void setTask_OnlineQueryAPI(excr_eprocedure_api.proxies.Task task_onlinequeryapi)
	{
		setTask_OnlineQueryAPI(getContext(), task_onlinequeryapi);
	}

	/**
	 * Set value of Task_OnlineQueryAPI
	 * @param context
	 * @param task_onlinequeryapi
	 */
	public final void setTask_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.Task task_onlinequeryapi)
	{
		if (task_onlinequeryapi == null) {
			getMendixObject().setValue(context, MemberNames.Task_OnlineQueryAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_OnlineQueryAPI.toString(), task_onlinequeryapi.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return onlineQueryAPIMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.OnlineQueryAPI that = (excr_eprocedure_api.proxies.OnlineQueryAPI) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
