// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class Parameters implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject parametersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.Parameters";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Parameters_ApiReqEmployeeRoot("EXCR_EProcedure_API.Parameters_ApiReqEmployeeRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Parameters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Parameters(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject parametersMendixObject)
	{
		if (parametersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!parametersMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.parametersMendixObject = parametersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.Parameters initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.Parameters(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.Parameters load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.Parameters.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parameters_ApiReqEmployeeRoot
	 */
	public final excr_eprocedure_api.proxies.ApiReqEmployeeRoot getParameters_ApiReqEmployeeRoot() throws com.mendix.core.CoreException
	{
		return getParameters_ApiReqEmployeeRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Parameters_ApiReqEmployeeRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ApiReqEmployeeRoot getParameters_ApiReqEmployeeRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ApiReqEmployeeRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parameters_ApiReqEmployeeRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ApiReqEmployeeRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parameters_ApiReqEmployeeRoot
	 * @param parameters_apireqemployeeroot
	 */
	public final void setParameters_ApiReqEmployeeRoot(excr_eprocedure_api.proxies.ApiReqEmployeeRoot parameters_apireqemployeeroot)
	{
		setParameters_ApiReqEmployeeRoot(getContext(), parameters_apireqemployeeroot);
	}

	/**
	 * Set value of Parameters_ApiReqEmployeeRoot
	 * @param context
	 * @param parameters_apireqemployeeroot
	 */
	public final void setParameters_ApiReqEmployeeRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ApiReqEmployeeRoot parameters_apireqemployeeroot)
	{
		if (parameters_apireqemployeeroot == null) {
			getMendixObject().setValue(context, MemberNames.Parameters_ApiReqEmployeeRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parameters_ApiReqEmployeeRoot.toString(), parameters_apireqemployeeroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return parametersMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.Parameters that = (excr_eprocedure_api.proxies.Parameters) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
