// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class RDOValue implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rDOValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.RDOValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		Name("Name"),
		Revision("Revision"),
		UseROR("UseROR"),
		RDOValue_ReqContainerCollectDataDataPointDetail("EXCR_EProcedure_API.RDOValue_ReqContainerCollectDataDataPointDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RDOValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RDOValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rDOValueMendixObject)
	{
		if (rDOValueMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!rDOValueMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.rDOValueMendixObject = rDOValueMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.RDOValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.RDOValue(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.RDOValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.RDOValue.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @return value of UseROR
	 */
	public final java.lang.Boolean getUseROR()
	{
		return getUseROR(getContext());
	}

	/**
	 * @param context
	 * @return value of UseROR
	 */
	public final java.lang.Boolean getUseROR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseROR.toString());
	}

	/**
	 * Set value of UseROR
	 * @param useror
	 */
	public final void setUseROR(java.lang.Boolean useror)
	{
		setUseROR(getContext(), useror);
	}

	/**
	 * Set value of UseROR
	 * @param context
	 * @param useror
	 */
	public final void setUseROR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useror)
	{
		getMendixObject().setValue(context, MemberNames.UseROR.toString(), useror);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RDOValue_ReqContainerCollectDataDataPointDetail
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail getRDOValue_ReqContainerCollectDataDataPointDetail() throws com.mendix.core.CoreException
	{
		return getRDOValue_ReqContainerCollectDataDataPointDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of RDOValue_ReqContainerCollectDataDataPointDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail getRDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RDOValue_ReqContainerCollectDataDataPointDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RDOValue_ReqContainerCollectDataDataPointDetail
	 * @param rdovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setRDOValue_ReqContainerCollectDataDataPointDetail(excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail rdovalue_reqcontainercollectdatadatapointdetail)
	{
		setRDOValue_ReqContainerCollectDataDataPointDetail(getContext(), rdovalue_reqcontainercollectdatadatapointdetail);
	}

	/**
	 * Set value of RDOValue_ReqContainerCollectDataDataPointDetail
	 * @param context
	 * @param rdovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setRDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail rdovalue_reqcontainercollectdatadatapointdetail)
	{
		if (rdovalue_reqcontainercollectdatadatapointdetail == null) {
			getMendixObject().setValue(context, MemberNames.RDOValue_ReqContainerCollectDataDataPointDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RDOValue_ReqContainerCollectDataDataPointDetail.toString(), rdovalue_reqcontainercollectdatadatapointdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rDOValueMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.RDOValue that = (excr_eprocedure_api.proxies.RDOValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
