// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ReqContainerCollectDataResource implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerCollectDataResourceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ReqContainerCollectDataResource";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ReqContainerCollectDataResource_ReqContainerCollectDataRoot("EXCR_EProcedure_API.ReqContainerCollectDataResource_ReqContainerCollectDataRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerCollectDataResource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerCollectDataResource(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerCollectDataResourceMendixObject)
	{
		if (reqContainerCollectDataResourceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerCollectDataResourceMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerCollectDataResourceMendixObject = reqContainerCollectDataResourceMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ReqContainerCollectDataResource initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ReqContainerCollectDataResource(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ReqContainerCollectDataResource load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ReqContainerCollectDataResource.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerCollectDataResource_ReqContainerCollectDataRoot
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRoot getReqContainerCollectDataResource_ReqContainerCollectDataRoot() throws com.mendix.core.CoreException
	{
		return getReqContainerCollectDataResource_ReqContainerCollectDataRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerCollectDataResource_ReqContainerCollectDataRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRoot getReqContainerCollectDataResource_ReqContainerCollectDataRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerCollectDataResource_ReqContainerCollectDataRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerCollectDataResource_ReqContainerCollectDataRoot
	 * @param reqcontainercollectdataresource_reqcontainercollectdataroot
	 */
	public final void setReqContainerCollectDataResource_ReqContainerCollectDataRoot(excr_eprocedure_api.proxies.ReqContainerCollectDataRoot reqcontainercollectdataresource_reqcontainercollectdataroot)
	{
		setReqContainerCollectDataResource_ReqContainerCollectDataRoot(getContext(), reqcontainercollectdataresource_reqcontainercollectdataroot);
	}

	/**
	 * Set value of ReqContainerCollectDataResource_ReqContainerCollectDataRoot
	 * @param context
	 * @param reqcontainercollectdataresource_reqcontainercollectdataroot
	 */
	public final void setReqContainerCollectDataResource_ReqContainerCollectDataRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataRoot reqcontainercollectdataresource_reqcontainercollectdataroot)
	{
		if (reqcontainercollectdataresource_reqcontainercollectdataroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataResource_ReqContainerCollectDataRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataResource_ReqContainerCollectDataRoot.toString(), reqcontainercollectdataresource_reqcontainercollectdataroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerCollectDataResourceMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ReqContainerCollectDataResource that = (excr_eprocedure_api.proxies.ReqContainerCollectDataResource) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
