// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ReqContainerCollectDataDataPointDetail implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerCollectDataDataPointDetailMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ReqContainerCollectDataDataPointDetail";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		DataType("DataType"),
		DataValue("DataValue"),
		OriginalValue("OriginalValue"),
		ReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot("EXCR_EProcedure_API.ReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot"),
		ReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail("EXCR_EProcedure_API.ReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail"),
		ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail("EXCR_EProcedure_API.ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail"),
		ReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail("EXCR_EProcedure_API.ReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail"),
		NDOValue_ReqContainerCollectDataDataPointDetail("EXCR_EProcedure_API.NDOValue_ReqContainerCollectDataDataPointDetail"),
		RDOValue_ReqContainerCollectDataDataPointDetail("EXCR_EProcedure_API.RDOValue_ReqContainerCollectDataDataPointDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerCollectDataDataPointDetailMendixObject)
	{
		if (reqContainerCollectDataDataPointDetailMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerCollectDataDataPointDetailMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerCollectDataDataPointDetailMendixObject = reqContainerCollectDataDataPointDetailMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of DataType
	 */
	public final java.lang.Integer getDataType()
	{
		return getDataType(getContext());
	}

	/**
	 * @param context
	 * @return value of DataType
	 */
	public final java.lang.Integer getDataType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DataType.toString());
	}

	/**
	 * Set value of DataType
	 * @param datatype
	 */
	public final void setDataType(java.lang.Integer datatype)
	{
		setDataType(getContext(), datatype);
	}

	/**
	 * Set value of DataType
	 * @param context
	 * @param datatype
	 */
	public final void setDataType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer datatype)
	{
		getMendixObject().setValue(context, MemberNames.DataType.toString(), datatype);
	}

	/**
	 * @return value of DataValue
	 */
	public final java.lang.String getDataValue()
	{
		return getDataValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DataValue
	 */
	public final java.lang.String getDataValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataValue.toString());
	}

	/**
	 * Set value of DataValue
	 * @param datavalue
	 */
	public final void setDataValue(java.lang.String datavalue)
	{
		setDataValue(getContext(), datavalue);
	}

	/**
	 * Set value of DataValue
	 * @param context
	 * @param datavalue
	 */
	public final void setDataValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datavalue)
	{
		getMendixObject().setValue(context, MemberNames.DataValue.toString(), datavalue);
	}

	/**
	 * @return value of OriginalValue
	 */
	public final java.lang.String getOriginalValue()
	{
		return getOriginalValue(getContext());
	}

	/**
	 * @param context
	 * @return value of OriginalValue
	 */
	public final java.lang.String getOriginalValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OriginalValue.toString());
	}

	/**
	 * Set value of OriginalValue
	 * @param originalvalue
	 */
	public final void setOriginalValue(java.lang.String originalvalue)
	{
		setOriginalValue(getContext(), originalvalue);
	}

	/**
	 * Set value of OriginalValue
	 * @param context
	 * @param originalvalue
	 */
	public final void setOriginalValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String originalvalue)
	{
		getMendixObject().setValue(context, MemberNames.OriginalValue.toString(), originalvalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetailsRoot getReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot() throws com.mendix.core.CoreException
	{
		return getReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetailsRoot getReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetailsRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetailsRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot
	 * @param reqcontainercollectdatadatapointdetail_reqcontainercollectdatadatapointdetailsroot
	 */
	public final void setReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot(excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetailsRoot reqcontainercollectdatadatapointdetail_reqcontainercollectdatadatapointdetailsroot)
	{
		setReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot(getContext(), reqcontainercollectdatadatapointdetail_reqcontainercollectdatadatapointdetailsroot);
	}

	/**
	 * Set value of ReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot
	 * @param context
	 * @param reqcontainercollectdatadatapointdetail_reqcontainercollectdatadatapointdetailsroot
	 */
	public final void setReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetailsRoot reqcontainercollectdatadatapointdetail_reqcontainercollectdatadatapointdetailsroot)
	{
		if (reqcontainercollectdatadatapointdetail_reqcontainercollectdatadatapointdetailsroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataDataPointDetail_ReqContainerCollectDataDataPointDetailsRoot.toString(), reqcontainercollectdatadatapointdetail_reqcontainercollectdatadatapointdetailsroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataDataPoint getReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail() throws com.mendix.core.CoreException
	{
		return getReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataDataPoint getReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataDataPoint result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataDataPoint.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail
	 * @param reqcontainercollectdatadatapoint_reqcontainercollectdatadatapointdetail
	 */
	public final void setReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail(excr_eprocedure_api.proxies.ReqContainerCollectDataDataPoint reqcontainercollectdatadatapoint_reqcontainercollectdatadatapointdetail)
	{
		setReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail(getContext(), reqcontainercollectdatadatapoint_reqcontainercollectdatadatapointdetail);
	}

	/**
	 * Set value of ReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail
	 * @param context
	 * @param reqcontainercollectdatadatapoint_reqcontainercollectdatadatapointdetail
	 */
	public final void setReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataDataPoint reqcontainercollectdatadatapoint_reqcontainercollectdatadatapointdetail)
	{
		if (reqcontainercollectdatadatapoint_reqcontainercollectdatadatapointdetail == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataDataPoint_ReqContainerCollectDataDataPointDetail.toString(), reqcontainercollectdatadatapoint_reqcontainercollectdatadatapointdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue getReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail() throws com.mendix.core.CoreException
	{
		return getReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue getReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail
	 * @param reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail)
	{
		setReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(getContext(), reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail);
	}

	/**
	 * Set value of ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail
	 * @param context
	 * @param reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail)
	{
		if (reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail.toString(), reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRDOValue getReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail() throws com.mendix.core.CoreException
	{
		return getReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRDOValue getReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataRDOValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataRDOValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail
	 * @param reqcontainercollectdatardovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail(excr_eprocedure_api.proxies.ReqContainerCollectDataRDOValue reqcontainercollectdatardovalue_reqcontainercollectdatadatapointdetail)
	{
		setReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail(getContext(), reqcontainercollectdatardovalue_reqcontainercollectdatadatapointdetail);
	}

	/**
	 * Set value of ReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail
	 * @param context
	 * @param reqcontainercollectdatardovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataRDOValue reqcontainercollectdatardovalue_reqcontainercollectdatadatapointdetail)
	{
		if (reqcontainercollectdatardovalue_reqcontainercollectdatadatapointdetail == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataRDOValue_ReqContainerCollectDataDataPointDetail.toString(), reqcontainercollectdatardovalue_reqcontainercollectdatadatapointdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NDOValue_ReqContainerCollectDataDataPointDetail
	 */
	public final excr_eprocedure_api.proxies.NDOValue getNDOValue_ReqContainerCollectDataDataPointDetail() throws com.mendix.core.CoreException
	{
		return getNDOValue_ReqContainerCollectDataDataPointDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of NDOValue_ReqContainerCollectDataDataPointDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.NDOValue getNDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.NDOValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NDOValue_ReqContainerCollectDataDataPointDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.NDOValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NDOValue_ReqContainerCollectDataDataPointDetail
	 * @param ndovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setNDOValue_ReqContainerCollectDataDataPointDetail(excr_eprocedure_api.proxies.NDOValue ndovalue_reqcontainercollectdatadatapointdetail)
	{
		setNDOValue_ReqContainerCollectDataDataPointDetail(getContext(), ndovalue_reqcontainercollectdatadatapointdetail);
	}

	/**
	 * Set value of NDOValue_ReqContainerCollectDataDataPointDetail
	 * @param context
	 * @param ndovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setNDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.NDOValue ndovalue_reqcontainercollectdatadatapointdetail)
	{
		if (ndovalue_reqcontainercollectdatadatapointdetail == null) {
			getMendixObject().setValue(context, MemberNames.NDOValue_ReqContainerCollectDataDataPointDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NDOValue_ReqContainerCollectDataDataPointDetail.toString(), ndovalue_reqcontainercollectdatadatapointdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RDOValue_ReqContainerCollectDataDataPointDetail
	 */
	public final excr_eprocedure_api.proxies.RDOValue getRDOValue_ReqContainerCollectDataDataPointDetail() throws com.mendix.core.CoreException
	{
		return getRDOValue_ReqContainerCollectDataDataPointDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of RDOValue_ReqContainerCollectDataDataPointDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.RDOValue getRDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.RDOValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RDOValue_ReqContainerCollectDataDataPointDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.RDOValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RDOValue_ReqContainerCollectDataDataPointDetail
	 * @param rdovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setRDOValue_ReqContainerCollectDataDataPointDetail(excr_eprocedure_api.proxies.RDOValue rdovalue_reqcontainercollectdatadatapointdetail)
	{
		setRDOValue_ReqContainerCollectDataDataPointDetail(getContext(), rdovalue_reqcontainercollectdatadatapointdetail);
	}

	/**
	 * Set value of RDOValue_ReqContainerCollectDataDataPointDetail
	 * @param context
	 * @param rdovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setRDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.RDOValue rdovalue_reqcontainercollectdatadatapointdetail)
	{
		if (rdovalue_reqcontainercollectdatadatapointdetail == null) {
			getMendixObject().setValue(context, MemberNames.RDOValue_ReqContainerCollectDataDataPointDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RDOValue_ReqContainerCollectDataDataPointDetail.toString(), rdovalue_reqcontainercollectdatadatapointdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerCollectDataDataPointDetailMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail that = (excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
