// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ReqContainerCollectDataNDOValue implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerCollectDataNDOValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ReqContainerCollectDataNDOValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		Name("Name"),
		ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail("EXCR_EProcedure_API.ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerCollectDataNDOValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerCollectDataNDOValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerCollectDataNDOValueMendixObject)
	{
		if (reqContainerCollectDataNDOValueMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerCollectDataNDOValueMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerCollectDataNDOValueMendixObject = reqContainerCollectDataNDOValueMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail getReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail() throws com.mendix.core.CoreException
	{
		return getReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail getReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail
	 * @param reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail)
	{
		setReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(getContext(), reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail);
	}

	/**
	 * Set value of ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail
	 * @param context
	 * @param reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail
	 */
	public final void setReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataDataPointDetail reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail)
	{
		if (reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerCollectDataNDOValue_ReqContainerCollectDataDataPointDetail.toString(), reqcontainercollectdatandovalue_reqcontainercollectdatadatapointdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerCollectDataNDOValueMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue that = (excr_eprocedure_api.proxies.ReqContainerCollectDataNDOValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
