// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ReqContainerInfoParameter implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerInfoParameterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ReqContainerInfoParameter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Value("Value"),
		ReqContainerInfoParameter_ReqContainerInfoRootParameters("EXCR_EProcedure_API.ReqContainerInfoParameter_ReqContainerInfoRootParameters");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerInfoParameter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerInfoParameter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerInfoParameterMendixObject)
	{
		if (reqContainerInfoParameterMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerInfoParameterMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerInfoParameterMendixObject = reqContainerInfoParameterMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ReqContainerInfoParameter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ReqContainerInfoParameter(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ReqContainerInfoParameter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ReqContainerInfoParameter.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerInfoParameter_ReqContainerInfoRootParameters
	 */
	public final excr_eprocedure_api.proxies.ReqContainerInfoRootParameters getReqContainerInfoParameter_ReqContainerInfoRootParameters() throws com.mendix.core.CoreException
	{
		return getReqContainerInfoParameter_ReqContainerInfoRootParameters(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerInfoParameter_ReqContainerInfoRootParameters
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerInfoRootParameters getReqContainerInfoParameter_ReqContainerInfoRootParameters(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerInfoRootParameters result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerInfoParameter_ReqContainerInfoRootParameters.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerInfoRootParameters.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerInfoParameter_ReqContainerInfoRootParameters
	 * @param reqcontainerinfoparameter_reqcontainerinforootparameters
	 */
	public final void setReqContainerInfoParameter_ReqContainerInfoRootParameters(excr_eprocedure_api.proxies.ReqContainerInfoRootParameters reqcontainerinfoparameter_reqcontainerinforootparameters)
	{
		setReqContainerInfoParameter_ReqContainerInfoRootParameters(getContext(), reqcontainerinfoparameter_reqcontainerinforootparameters);
	}

	/**
	 * Set value of ReqContainerInfoParameter_ReqContainerInfoRootParameters
	 * @param context
	 * @param reqcontainerinfoparameter_reqcontainerinforootparameters
	 */
	public final void setReqContainerInfoParameter_ReqContainerInfoRootParameters(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerInfoRootParameters reqcontainerinfoparameter_reqcontainerinforootparameters)
	{
		if (reqcontainerinfoparameter_reqcontainerinforootparameters == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerInfoParameter_ReqContainerInfoRootParameters.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerInfoParameter_ReqContainerInfoRootParameters.toString(), reqcontainerinfoparameter_reqcontainerinforootparameters.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerInfoParameterMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ReqContainerInfoParameter that = (excr_eprocedure_api.proxies.ReqContainerInfoParameter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
