// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ReqContainerDocs_Event implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerDocs_EventMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ReqContainerDocs_Event";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqContainerDocs_EventName("ReqContainerDocs_EventName"),
		ReqContainerDocs_Event_ReqContainerDocs_Root("EXCR_EProcedure_API.ReqContainerDocs_Event_ReqContainerDocs_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerDocs_Event(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerDocs_Event(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerDocs_EventMendixObject)
	{
		if (reqContainerDocs_EventMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerDocs_EventMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerDocs_EventMendixObject = reqContainerDocs_EventMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ReqContainerDocs_Event initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ReqContainerDocs_Event(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ReqContainerDocs_Event load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ReqContainerDocs_Event.initialize(context, mendixObject);
	}

	/**
	 * @return value of ReqContainerDocs_EventName
	 */
	public final java.lang.String getReqContainerDocs_EventName()
	{
		return getReqContainerDocs_EventName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerDocs_EventName
	 */
	public final java.lang.String getReqContainerDocs_EventName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReqContainerDocs_EventName.toString());
	}

	/**
	 * Set value of ReqContainerDocs_EventName
	 * @param reqcontainerdocs_eventname
	 */
	public final void setReqContainerDocs_EventName(java.lang.String reqcontainerdocs_eventname)
	{
		setReqContainerDocs_EventName(getContext(), reqcontainerdocs_eventname);
	}

	/**
	 * Set value of ReqContainerDocs_EventName
	 * @param context
	 * @param reqcontainerdocs_eventname
	 */
	public final void setReqContainerDocs_EventName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reqcontainerdocs_eventname)
	{
		getMendixObject().setValue(context, MemberNames.ReqContainerDocs_EventName.toString(), reqcontainerdocs_eventname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerDocs_Event_ReqContainerDocs_Root
	 */
	public final excr_eprocedure_api.proxies.ReqContainerDocs_Root getReqContainerDocs_Event_ReqContainerDocs_Root() throws com.mendix.core.CoreException
	{
		return getReqContainerDocs_Event_ReqContainerDocs_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerDocs_Event_ReqContainerDocs_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerDocs_Root getReqContainerDocs_Event_ReqContainerDocs_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerDocs_Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerDocs_Event_ReqContainerDocs_Root.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerDocs_Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerDocs_Event_ReqContainerDocs_Root
	 * @param reqcontainerdocs_event_reqcontainerdocs_root
	 */
	public final void setReqContainerDocs_Event_ReqContainerDocs_Root(excr_eprocedure_api.proxies.ReqContainerDocs_Root reqcontainerdocs_event_reqcontainerdocs_root)
	{
		setReqContainerDocs_Event_ReqContainerDocs_Root(getContext(), reqcontainerdocs_event_reqcontainerdocs_root);
	}

	/**
	 * Set value of ReqContainerDocs_Event_ReqContainerDocs_Root
	 * @param context
	 * @param reqcontainerdocs_event_reqcontainerdocs_root
	 */
	public final void setReqContainerDocs_Event_ReqContainerDocs_Root(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerDocs_Root reqcontainerdocs_event_reqcontainerdocs_root)
	{
		if (reqcontainerdocs_event_reqcontainerdocs_root == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerDocs_Event_ReqContainerDocs_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerDocs_Event_ReqContainerDocs_Root.toString(), reqcontainerdocs_event_reqcontainerdocs_root.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerDocs_EventMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ReqContainerDocs_Event that = (excr_eprocedure_api.proxies.ReqContainerDocs_Event) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
