// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ReqTaskDocs_Event implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqTaskDocs_EventMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ReqTaskDocs_Event";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqTaskDocs_EventName("ReqTaskDocs_EventName"),
		ReqTaskDocs_Event_ReqTaskDocs_Root("EXCR_EProcedure_API.ReqTaskDocs_Event_ReqTaskDocs_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqTaskDocs_Event(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqTaskDocs_Event(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqTaskDocs_EventMendixObject)
	{
		if (reqTaskDocs_EventMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqTaskDocs_EventMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqTaskDocs_EventMendixObject = reqTaskDocs_EventMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ReqTaskDocs_Event initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ReqTaskDocs_Event(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ReqTaskDocs_Event load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ReqTaskDocs_Event.initialize(context, mendixObject);
	}

	/**
	 * @return value of ReqTaskDocs_EventName
	 */
	public final java.lang.String getReqTaskDocs_EventName()
	{
		return getReqTaskDocs_EventName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqTaskDocs_EventName
	 */
	public final java.lang.String getReqTaskDocs_EventName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReqTaskDocs_EventName.toString());
	}

	/**
	 * Set value of ReqTaskDocs_EventName
	 * @param reqtaskdocs_eventname
	 */
	public final void setReqTaskDocs_EventName(java.lang.String reqtaskdocs_eventname)
	{
		setReqTaskDocs_EventName(getContext(), reqtaskdocs_eventname);
	}

	/**
	 * Set value of ReqTaskDocs_EventName
	 * @param context
	 * @param reqtaskdocs_eventname
	 */
	public final void setReqTaskDocs_EventName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reqtaskdocs_eventname)
	{
		getMendixObject().setValue(context, MemberNames.ReqTaskDocs_EventName.toString(), reqtaskdocs_eventname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqTaskDocs_Event_ReqTaskDocs_Root
	 */
	public final excr_eprocedure_api.proxies.ReqTaskDocs_Root getReqTaskDocs_Event_ReqTaskDocs_Root() throws com.mendix.core.CoreException
	{
		return getReqTaskDocs_Event_ReqTaskDocs_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqTaskDocs_Event_ReqTaskDocs_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqTaskDocs_Root getReqTaskDocs_Event_ReqTaskDocs_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqTaskDocs_Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqTaskDocs_Event_ReqTaskDocs_Root.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqTaskDocs_Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqTaskDocs_Event_ReqTaskDocs_Root
	 * @param reqtaskdocs_event_reqtaskdocs_root
	 */
	public final void setReqTaskDocs_Event_ReqTaskDocs_Root(excr_eprocedure_api.proxies.ReqTaskDocs_Root reqtaskdocs_event_reqtaskdocs_root)
	{
		setReqTaskDocs_Event_ReqTaskDocs_Root(getContext(), reqtaskdocs_event_reqtaskdocs_root);
	}

	/**
	 * Set value of ReqTaskDocs_Event_ReqTaskDocs_Root
	 * @param context
	 * @param reqtaskdocs_event_reqtaskdocs_root
	 */
	public final void setReqTaskDocs_Event_ReqTaskDocs_Root(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqTaskDocs_Root reqtaskdocs_event_reqtaskdocs_root)
	{
		if (reqtaskdocs_event_reqtaskdocs_root == null) {
			getMendixObject().setValue(context, MemberNames.ReqTaskDocs_Event_ReqTaskDocs_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqTaskDocs_Event_ReqTaskDocs_Root.toString(), reqtaskdocs_event_reqtaskdocs_root.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqTaskDocs_EventMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ReqTaskDocs_Event that = (excr_eprocedure_api.proxies.ReqTaskDocs_Event) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
