// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ReqTaskDocs_InputData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqTaskDocs_InputDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ReqTaskDocs_InputData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqTaskDocs_InputData_ReqTaskDocs_Root("EXCR_EProcedure_API.ReqTaskDocs_InputData_ReqTaskDocs_Root"),
		ReqTaskDocs_Container_ReqTaskDocs_InputData("EXCR_EProcedure_API.ReqTaskDocs_Container_ReqTaskDocs_InputData"),
		ReqTaskDocs_Task_ReqTaskDocs_InputData("EXCR_EProcedure_API.ReqTaskDocs_Task_ReqTaskDocs_InputData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqTaskDocs_InputData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqTaskDocs_InputData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqTaskDocs_InputDataMendixObject)
	{
		if (reqTaskDocs_InputDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqTaskDocs_InputDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqTaskDocs_InputDataMendixObject = reqTaskDocs_InputDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ReqTaskDocs_InputData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ReqTaskDocs_InputData(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ReqTaskDocs_InputData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ReqTaskDocs_InputData.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqTaskDocs_InputData_ReqTaskDocs_Root
	 */
	public final excr_eprocedure_api.proxies.ReqTaskDocs_Root getReqTaskDocs_InputData_ReqTaskDocs_Root() throws com.mendix.core.CoreException
	{
		return getReqTaskDocs_InputData_ReqTaskDocs_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqTaskDocs_InputData_ReqTaskDocs_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqTaskDocs_Root getReqTaskDocs_InputData_ReqTaskDocs_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqTaskDocs_Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqTaskDocs_InputData_ReqTaskDocs_Root.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqTaskDocs_Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqTaskDocs_InputData_ReqTaskDocs_Root
	 * @param reqtaskdocs_inputdata_reqtaskdocs_root
	 */
	public final void setReqTaskDocs_InputData_ReqTaskDocs_Root(excr_eprocedure_api.proxies.ReqTaskDocs_Root reqtaskdocs_inputdata_reqtaskdocs_root)
	{
		setReqTaskDocs_InputData_ReqTaskDocs_Root(getContext(), reqtaskdocs_inputdata_reqtaskdocs_root);
	}

	/**
	 * Set value of ReqTaskDocs_InputData_ReqTaskDocs_Root
	 * @param context
	 * @param reqtaskdocs_inputdata_reqtaskdocs_root
	 */
	public final void setReqTaskDocs_InputData_ReqTaskDocs_Root(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqTaskDocs_Root reqtaskdocs_inputdata_reqtaskdocs_root)
	{
		if (reqtaskdocs_inputdata_reqtaskdocs_root == null) {
			getMendixObject().setValue(context, MemberNames.ReqTaskDocs_InputData_ReqTaskDocs_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqTaskDocs_InputData_ReqTaskDocs_Root.toString(), reqtaskdocs_inputdata_reqtaskdocs_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqTaskDocs_Container_ReqTaskDocs_InputData
	 */
	public final excr_eprocedure_api.proxies.ReqTaskDocs_Container getReqTaskDocs_Container_ReqTaskDocs_InputData() throws com.mendix.core.CoreException
	{
		return getReqTaskDocs_Container_ReqTaskDocs_InputData(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqTaskDocs_Container_ReqTaskDocs_InputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqTaskDocs_Container getReqTaskDocs_Container_ReqTaskDocs_InputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqTaskDocs_Container result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqTaskDocs_Container_ReqTaskDocs_InputData.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqTaskDocs_Container.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqTaskDocs_Container_ReqTaskDocs_InputData
	 * @param reqtaskdocs_container_reqtaskdocs_inputdata
	 */
	public final void setReqTaskDocs_Container_ReqTaskDocs_InputData(excr_eprocedure_api.proxies.ReqTaskDocs_Container reqtaskdocs_container_reqtaskdocs_inputdata)
	{
		setReqTaskDocs_Container_ReqTaskDocs_InputData(getContext(), reqtaskdocs_container_reqtaskdocs_inputdata);
	}

	/**
	 * Set value of ReqTaskDocs_Container_ReqTaskDocs_InputData
	 * @param context
	 * @param reqtaskdocs_container_reqtaskdocs_inputdata
	 */
	public final void setReqTaskDocs_Container_ReqTaskDocs_InputData(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqTaskDocs_Container reqtaskdocs_container_reqtaskdocs_inputdata)
	{
		if (reqtaskdocs_container_reqtaskdocs_inputdata == null) {
			getMendixObject().setValue(context, MemberNames.ReqTaskDocs_Container_ReqTaskDocs_InputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqTaskDocs_Container_ReqTaskDocs_InputData.toString(), reqtaskdocs_container_reqtaskdocs_inputdata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqTaskDocs_Task_ReqTaskDocs_InputData
	 */
	public final excr_eprocedure_api.proxies.ReqTaskDocs_Task getReqTaskDocs_Task_ReqTaskDocs_InputData() throws com.mendix.core.CoreException
	{
		return getReqTaskDocs_Task_ReqTaskDocs_InputData(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqTaskDocs_Task_ReqTaskDocs_InputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqTaskDocs_Task getReqTaskDocs_Task_ReqTaskDocs_InputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqTaskDocs_Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqTaskDocs_Task_ReqTaskDocs_InputData.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqTaskDocs_Task.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqTaskDocs_Task_ReqTaskDocs_InputData
	 * @param reqtaskdocs_task_reqtaskdocs_inputdata
	 */
	public final void setReqTaskDocs_Task_ReqTaskDocs_InputData(excr_eprocedure_api.proxies.ReqTaskDocs_Task reqtaskdocs_task_reqtaskdocs_inputdata)
	{
		setReqTaskDocs_Task_ReqTaskDocs_InputData(getContext(), reqtaskdocs_task_reqtaskdocs_inputdata);
	}

	/**
	 * Set value of ReqTaskDocs_Task_ReqTaskDocs_InputData
	 * @param context
	 * @param reqtaskdocs_task_reqtaskdocs_inputdata
	 */
	public final void setReqTaskDocs_Task_ReqTaskDocs_InputData(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqTaskDocs_Task reqtaskdocs_task_reqtaskdocs_inputdata)
	{
		if (reqtaskdocs_task_reqtaskdocs_inputdata == null) {
			getMendixObject().setValue(context, MemberNames.ReqTaskDocs_Task_ReqTaskDocs_InputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqTaskDocs_Task_ReqTaskDocs_InputData.toString(), reqtaskdocs_task_reqtaskdocs_inputdata.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqTaskDocs_InputDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ReqTaskDocs_InputData that = (excr_eprocedure_api.proxies.ReqTaskDocs_InputData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
