// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ResContainerInfoJsonObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resContainerInfoJsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ResContainerInfoJsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceId("InstanceId"),
		Container("Container"),
		Level("Level"),
		Carrier("Carrier"),
		CarrierName("CarrierName"),
		Step("Step"),
		Priority("Priority"),
		Product("Product"),
		Revision("Revision"),
		ProductDescription("ProductDescription"),
		ProductROR("ProductROR"),
		Qty("Qty"),
		InProcess("InProcess"),
		Status("Status"),
		Operation("Operation"),
		UseQueue("UseQueue"),
		MfgOrder("MfgOrder"),
		UOM("UOM"),
		DueDate("DueDate"),
		OriginalStartDate("OriginalStartDate"),
		IsOnHold("IsOnHold"),
		HoldReason("HoldReason"),
		OwnerName("OwnerName"),
		TimersCount("TimersCount"),
		ElectronicProcedure("ElectronicProcedure"),
		ResourceName("ResourceName"),
		SpecId("SpecId"),
		CurrentHoldCount("CurrentHoldCount"),
		HoldReasonId("HoldReasonId"),
		WorkflowRevision("WorkflowRevision"),
		WorkflowName("WorkflowName"),
		ElectronicProcedureRevision("ElectronicProcedureRevision"),
		ElectronicProcedureName("ElectronicProcedureName"),
		ResContainerInfoJsonObject_ResContainerInfoRoot("EXCR_EProcedure_API.ResContainerInfoJsonObject_ResContainerInfoRoot"),
		EProcedureContext_ResContainerInfoJsonObject("EXCR_EProcedure.EProcedureContext_ResContainerInfoJsonObject");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResContainerInfoJsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResContainerInfoJsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resContainerInfoJsonObjectMendixObject)
	{
		if (resContainerInfoJsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resContainerInfoJsonObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resContainerInfoJsonObjectMendixObject = resContainerInfoJsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ResContainerInfoJsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ResContainerInfoJsonObject(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ResContainerInfoJsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ResContainerInfoJsonObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @return value of Container
	 */
	public final java.lang.String getContainer()
	{
		return getContainer(getContext());
	}

	/**
	 * @param context
	 * @return value of Container
	 */
	public final java.lang.String getContainer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Container.toString());
	}

	/**
	 * Set value of Container
	 * @param container
	 */
	public final void setContainer(java.lang.String container)
	{
		setContainer(getContext(), container);
	}

	/**
	 * Set value of Container
	 * @param context
	 * @param container
	 */
	public final void setContainer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String container)
	{
		getMendixObject().setValue(context, MemberNames.Container.toString(), container);
	}

	/**
	 * @return value of Level
	 */
	public final java.lang.String getLevel()
	{
		return getLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of Level
	 */
	public final java.lang.String getLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Level.toString());
	}

	/**
	 * Set value of Level
	 * @param level
	 */
	public final void setLevel(java.lang.String level)
	{
		setLevel(getContext(), level);
	}

	/**
	 * Set value of Level
	 * @param context
	 * @param level
	 */
	public final void setLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String level)
	{
		getMendixObject().setValue(context, MemberNames.Level.toString(), level);
	}

	/**
	 * @return value of Carrier
	 */
	public final java.lang.String getCarrier()
	{
		return getCarrier(getContext());
	}

	/**
	 * @param context
	 * @return value of Carrier
	 */
	public final java.lang.String getCarrier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Carrier.toString());
	}

	/**
	 * Set value of Carrier
	 * @param carrier
	 */
	public final void setCarrier(java.lang.String carrier)
	{
		setCarrier(getContext(), carrier);
	}

	/**
	 * Set value of Carrier
	 * @param context
	 * @param carrier
	 */
	public final void setCarrier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String carrier)
	{
		getMendixObject().setValue(context, MemberNames.Carrier.toString(), carrier);
	}

	/**
	 * @return value of CarrierName
	 */
	public final java.lang.String getCarrierName()
	{
		return getCarrierName(getContext());
	}

	/**
	 * @param context
	 * @return value of CarrierName
	 */
	public final java.lang.String getCarrierName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CarrierName.toString());
	}

	/**
	 * Set value of CarrierName
	 * @param carriername
	 */
	public final void setCarrierName(java.lang.String carriername)
	{
		setCarrierName(getContext(), carriername);
	}

	/**
	 * Set value of CarrierName
	 * @param context
	 * @param carriername
	 */
	public final void setCarrierName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String carriername)
	{
		getMendixObject().setValue(context, MemberNames.CarrierName.toString(), carriername);
	}

	/**
	 * @return value of Step
	 */
	public final java.lang.String getStep()
	{
		return getStep(getContext());
	}

	/**
	 * @param context
	 * @return value of Step
	 */
	public final java.lang.String getStep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Step.toString());
	}

	/**
	 * Set value of Step
	 * @param step
	 */
	public final void setStep(java.lang.String step)
	{
		setStep(getContext(), step);
	}

	/**
	 * Set value of Step
	 * @param context
	 * @param step
	 */
	public final void setStep(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String step)
	{
		getMendixObject().setValue(context, MemberNames.Step.toString(), step);
	}

	/**
	 * @return value of Priority
	 */
	public final java.lang.String getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final java.lang.String getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Priority.toString());
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(java.lang.String priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String priority)
	{
		getMendixObject().setValue(context, MemberNames.Priority.toString(), priority);
	}

	/**
	 * @return value of Product
	 */
	public final java.lang.String getProduct()
	{
		return getProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of Product
	 */
	public final java.lang.String getProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Product.toString());
	}

	/**
	 * Set value of Product
	 * @param product
	 */
	public final void setProduct(java.lang.String product)
	{
		setProduct(getContext(), product);
	}

	/**
	 * Set value of Product
	 * @param context
	 * @param product
	 */
	public final void setProduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product)
	{
		getMendixObject().setValue(context, MemberNames.Product.toString(), product);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @return value of ProductDescription
	 */
	public final java.lang.String getProductDescription()
	{
		return getProductDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductDescription
	 */
	public final java.lang.String getProductDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductDescription.toString());
	}

	/**
	 * Set value of ProductDescription
	 * @param productdescription
	 */
	public final void setProductDescription(java.lang.String productdescription)
	{
		setProductDescription(getContext(), productdescription);
	}

	/**
	 * Set value of ProductDescription
	 * @param context
	 * @param productdescription
	 */
	public final void setProductDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productdescription)
	{
		getMendixObject().setValue(context, MemberNames.ProductDescription.toString(), productdescription);
	}

	/**
	 * @return value of ProductROR
	 */
	public final java.lang.String getProductROR()
	{
		return getProductROR(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductROR
	 */
	public final java.lang.String getProductROR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductROR.toString());
	}

	/**
	 * Set value of ProductROR
	 * @param productror
	 */
	public final void setProductROR(java.lang.String productror)
	{
		setProductROR(getContext(), productror);
	}

	/**
	 * Set value of ProductROR
	 * @param context
	 * @param productror
	 */
	public final void setProductROR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productror)
	{
		getMendixObject().setValue(context, MemberNames.ProductROR.toString(), productror);
	}

	/**
	 * @return value of Qty
	 */
	public final java.lang.String getQty()
	{
		return getQty(getContext());
	}

	/**
	 * @param context
	 * @return value of Qty
	 */
	public final java.lang.String getQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Qty.toString());
	}

	/**
	 * Set value of Qty
	 * @param qty
	 */
	public final void setQty(java.lang.String qty)
	{
		setQty(getContext(), qty);
	}

	/**
	 * Set value of Qty
	 * @param context
	 * @param qty
	 */
	public final void setQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String qty)
	{
		getMendixObject().setValue(context, MemberNames.Qty.toString(), qty);
	}

	/**
	 * @return value of InProcess
	 */
	public final java.lang.String getInProcess()
	{
		return getInProcess(getContext());
	}

	/**
	 * @param context
	 * @return value of InProcess
	 */
	public final java.lang.String getInProcess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InProcess.toString());
	}

	/**
	 * Set value of InProcess
	 * @param inprocess
	 */
	public final void setInProcess(java.lang.String inprocess)
	{
		setInProcess(getContext(), inprocess);
	}

	/**
	 * Set value of InProcess
	 * @param context
	 * @param inprocess
	 */
	public final void setInProcess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String inprocess)
	{
		getMendixObject().setValue(context, MemberNames.InProcess.toString(), inprocess);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of Operation
	 */
	public final java.lang.String getOperation()
	{
		return getOperation(getContext());
	}

	/**
	 * @param context
	 * @return value of Operation
	 */
	public final java.lang.String getOperation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Operation.toString());
	}

	/**
	 * Set value of Operation
	 * @param operation
	 */
	public final void setOperation(java.lang.String operation)
	{
		setOperation(getContext(), operation);
	}

	/**
	 * Set value of Operation
	 * @param context
	 * @param operation
	 */
	public final void setOperation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operation)
	{
		getMendixObject().setValue(context, MemberNames.Operation.toString(), operation);
	}

	/**
	 * @return value of UseQueue
	 */
	public final java.lang.String getUseQueue()
	{
		return getUseQueue(getContext());
	}

	/**
	 * @param context
	 * @return value of UseQueue
	 */
	public final java.lang.String getUseQueue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseQueue.toString());
	}

	/**
	 * Set value of UseQueue
	 * @param usequeue
	 */
	public final void setUseQueue(java.lang.String usequeue)
	{
		setUseQueue(getContext(), usequeue);
	}

	/**
	 * Set value of UseQueue
	 * @param context
	 * @param usequeue
	 */
	public final void setUseQueue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usequeue)
	{
		getMendixObject().setValue(context, MemberNames.UseQueue.toString(), usequeue);
	}

	/**
	 * @return value of MfgOrder
	 */
	public final java.lang.String getMfgOrder()
	{
		return getMfgOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrder
	 */
	public final java.lang.String getMfgOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MfgOrder.toString());
	}

	/**
	 * Set value of MfgOrder
	 * @param mfgorder
	 */
	public final void setMfgOrder(java.lang.String mfgorder)
	{
		setMfgOrder(getContext(), mfgorder);
	}

	/**
	 * Set value of MfgOrder
	 * @param context
	 * @param mfgorder
	 */
	public final void setMfgOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfgorder)
	{
		getMendixObject().setValue(context, MemberNames.MfgOrder.toString(), mfgorder);
	}

	/**
	 * @return value of UOM
	 */
	public final java.lang.String getUOM()
	{
		return getUOM(getContext());
	}

	/**
	 * @param context
	 * @return value of UOM
	 */
	public final java.lang.String getUOM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UOM.toString());
	}

	/**
	 * Set value of UOM
	 * @param uom
	 */
	public final void setUOM(java.lang.String uom)
	{
		setUOM(getContext(), uom);
	}

	/**
	 * Set value of UOM
	 * @param context
	 * @param uom
	 */
	public final void setUOM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uom)
	{
		getMendixObject().setValue(context, MemberNames.UOM.toString(), uom);
	}

	/**
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate()
	{
		return getDueDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DueDate.toString());
	}

	/**
	 * Set value of DueDate
	 * @param duedate
	 */
	public final void setDueDate(java.util.Date duedate)
	{
		setDueDate(getContext(), duedate);
	}

	/**
	 * Set value of DueDate
	 * @param context
	 * @param duedate
	 */
	public final void setDueDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date duedate)
	{
		getMendixObject().setValue(context, MemberNames.DueDate.toString(), duedate);
	}

	/**
	 * @return value of OriginalStartDate
	 */
	public final java.util.Date getOriginalStartDate()
	{
		return getOriginalStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OriginalStartDate
	 */
	public final java.util.Date getOriginalStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OriginalStartDate.toString());
	}

	/**
	 * Set value of OriginalStartDate
	 * @param originalstartdate
	 */
	public final void setOriginalStartDate(java.util.Date originalstartdate)
	{
		setOriginalStartDate(getContext(), originalstartdate);
	}

	/**
	 * Set value of OriginalStartDate
	 * @param context
	 * @param originalstartdate
	 */
	public final void setOriginalStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date originalstartdate)
	{
		getMendixObject().setValue(context, MemberNames.OriginalStartDate.toString(), originalstartdate);
	}

	/**
	 * @return value of IsOnHold
	 */
	public final java.lang.String getIsOnHold()
	{
		return getIsOnHold(getContext());
	}

	/**
	 * @param context
	 * @return value of IsOnHold
	 */
	public final java.lang.String getIsOnHold(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IsOnHold.toString());
	}

	/**
	 * Set value of IsOnHold
	 * @param isonhold
	 */
	public final void setIsOnHold(java.lang.String isonhold)
	{
		setIsOnHold(getContext(), isonhold);
	}

	/**
	 * Set value of IsOnHold
	 * @param context
	 * @param isonhold
	 */
	public final void setIsOnHold(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String isonhold)
	{
		getMendixObject().setValue(context, MemberNames.IsOnHold.toString(), isonhold);
	}

	/**
	 * @return value of HoldReason
	 */
	public final java.lang.String getHoldReason()
	{
		return getHoldReason(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldReason
	 */
	public final java.lang.String getHoldReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldReason.toString());
	}

	/**
	 * Set value of HoldReason
	 * @param holdreason
	 */
	public final void setHoldReason(java.lang.String holdreason)
	{
		setHoldReason(getContext(), holdreason);
	}

	/**
	 * Set value of HoldReason
	 * @param context
	 * @param holdreason
	 */
	public final void setHoldReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdreason)
	{
		getMendixObject().setValue(context, MemberNames.HoldReason.toString(), holdreason);
	}

	/**
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName()
	{
		return getOwnerName(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OwnerName.toString());
	}

	/**
	 * Set value of OwnerName
	 * @param ownername
	 */
	public final void setOwnerName(java.lang.String ownername)
	{
		setOwnerName(getContext(), ownername);
	}

	/**
	 * Set value of OwnerName
	 * @param context
	 * @param ownername
	 */
	public final void setOwnerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ownername)
	{
		getMendixObject().setValue(context, MemberNames.OwnerName.toString(), ownername);
	}

	/**
	 * @return value of TimersCount
	 */
	public final java.lang.String getTimersCount()
	{
		return getTimersCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TimersCount
	 */
	public final java.lang.String getTimersCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TimersCount.toString());
	}

	/**
	 * Set value of TimersCount
	 * @param timerscount
	 */
	public final void setTimersCount(java.lang.String timerscount)
	{
		setTimersCount(getContext(), timerscount);
	}

	/**
	 * Set value of TimersCount
	 * @param context
	 * @param timerscount
	 */
	public final void setTimersCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timerscount)
	{
		getMendixObject().setValue(context, MemberNames.TimersCount.toString(), timerscount);
	}

	/**
	 * @return value of ElectronicProcedure
	 */
	public final java.lang.String getElectronicProcedure()
	{
		return getElectronicProcedure(getContext());
	}

	/**
	 * @param context
	 * @return value of ElectronicProcedure
	 */
	public final java.lang.String getElectronicProcedure(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ElectronicProcedure.toString());
	}

	/**
	 * Set value of ElectronicProcedure
	 * @param electronicprocedure
	 */
	public final void setElectronicProcedure(java.lang.String electronicprocedure)
	{
		setElectronicProcedure(getContext(), electronicprocedure);
	}

	/**
	 * Set value of ElectronicProcedure
	 * @param context
	 * @param electronicprocedure
	 */
	public final void setElectronicProcedure(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String electronicprocedure)
	{
		getMendixObject().setValue(context, MemberNames.ElectronicProcedure.toString(), electronicprocedure);
	}

	/**
	 * @return value of ResourceName
	 */
	public final java.lang.String getResourceName()
	{
		return getResourceName(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceName
	 */
	public final java.lang.String getResourceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResourceName.toString());
	}

	/**
	 * Set value of ResourceName
	 * @param resourcename
	 */
	public final void setResourceName(java.lang.String resourcename)
	{
		setResourceName(getContext(), resourcename);
	}

	/**
	 * Set value of ResourceName
	 * @param context
	 * @param resourcename
	 */
	public final void setResourceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resourcename)
	{
		getMendixObject().setValue(context, MemberNames.ResourceName.toString(), resourcename);
	}

	/**
	 * @return value of SpecId
	 */
	public final java.lang.String getSpecId()
	{
		return getSpecId(getContext());
	}

	/**
	 * @param context
	 * @return value of SpecId
	 */
	public final java.lang.String getSpecId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SpecId.toString());
	}

	/**
	 * Set value of SpecId
	 * @param specid
	 */
	public final void setSpecId(java.lang.String specid)
	{
		setSpecId(getContext(), specid);
	}

	/**
	 * Set value of SpecId
	 * @param context
	 * @param specid
	 */
	public final void setSpecId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String specid)
	{
		getMendixObject().setValue(context, MemberNames.SpecId.toString(), specid);
	}

	/**
	 * @return value of CurrentHoldCount
	 */
	public final java.lang.String getCurrentHoldCount()
	{
		return getCurrentHoldCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentHoldCount
	 */
	public final java.lang.String getCurrentHoldCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrentHoldCount.toString());
	}

	/**
	 * Set value of CurrentHoldCount
	 * @param currentholdcount
	 */
	public final void setCurrentHoldCount(java.lang.String currentholdcount)
	{
		setCurrentHoldCount(getContext(), currentholdcount);
	}

	/**
	 * Set value of CurrentHoldCount
	 * @param context
	 * @param currentholdcount
	 */
	public final void setCurrentHoldCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currentholdcount)
	{
		getMendixObject().setValue(context, MemberNames.CurrentHoldCount.toString(), currentholdcount);
	}

	/**
	 * @return value of HoldReasonId
	 */
	public final java.lang.String getHoldReasonId()
	{
		return getHoldReasonId(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldReasonId
	 */
	public final java.lang.String getHoldReasonId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldReasonId.toString());
	}

	/**
	 * Set value of HoldReasonId
	 * @param holdreasonid
	 */
	public final void setHoldReasonId(java.lang.String holdreasonid)
	{
		setHoldReasonId(getContext(), holdreasonid);
	}

	/**
	 * Set value of HoldReasonId
	 * @param context
	 * @param holdreasonid
	 */
	public final void setHoldReasonId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdreasonid)
	{
		getMendixObject().setValue(context, MemberNames.HoldReasonId.toString(), holdreasonid);
	}

	/**
	 * @return value of WorkflowRevision
	 */
	public final java.lang.String getWorkflowRevision()
	{
		return getWorkflowRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRevision
	 */
	public final java.lang.String getWorkflowRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkflowRevision.toString());
	}

	/**
	 * Set value of WorkflowRevision
	 * @param workflowrevision
	 */
	public final void setWorkflowRevision(java.lang.String workflowrevision)
	{
		setWorkflowRevision(getContext(), workflowrevision);
	}

	/**
	 * Set value of WorkflowRevision
	 * @param context
	 * @param workflowrevision
	 */
	public final void setWorkflowRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workflowrevision)
	{
		getMendixObject().setValue(context, MemberNames.WorkflowRevision.toString(), workflowrevision);
	}

	/**
	 * @return value of WorkflowName
	 */
	public final java.lang.String getWorkflowName()
	{
		return getWorkflowName(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowName
	 */
	public final java.lang.String getWorkflowName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkflowName.toString());
	}

	/**
	 * Set value of WorkflowName
	 * @param workflowname
	 */
	public final void setWorkflowName(java.lang.String workflowname)
	{
		setWorkflowName(getContext(), workflowname);
	}

	/**
	 * Set value of WorkflowName
	 * @param context
	 * @param workflowname
	 */
	public final void setWorkflowName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workflowname)
	{
		getMendixObject().setValue(context, MemberNames.WorkflowName.toString(), workflowname);
	}

	/**
	 * @return value of ElectronicProcedureRevision
	 */
	public final java.lang.String getElectronicProcedureRevision()
	{
		return getElectronicProcedureRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of ElectronicProcedureRevision
	 */
	public final java.lang.String getElectronicProcedureRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ElectronicProcedureRevision.toString());
	}

	/**
	 * Set value of ElectronicProcedureRevision
	 * @param electronicprocedurerevision
	 */
	public final void setElectronicProcedureRevision(java.lang.String electronicprocedurerevision)
	{
		setElectronicProcedureRevision(getContext(), electronicprocedurerevision);
	}

	/**
	 * Set value of ElectronicProcedureRevision
	 * @param context
	 * @param electronicprocedurerevision
	 */
	public final void setElectronicProcedureRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String electronicprocedurerevision)
	{
		getMendixObject().setValue(context, MemberNames.ElectronicProcedureRevision.toString(), electronicprocedurerevision);
	}

	/**
	 * @return value of ElectronicProcedureName
	 */
	public final java.lang.String getElectronicProcedureName()
	{
		return getElectronicProcedureName(getContext());
	}

	/**
	 * @param context
	 * @return value of ElectronicProcedureName
	 */
	public final java.lang.String getElectronicProcedureName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ElectronicProcedureName.toString());
	}

	/**
	 * Set value of ElectronicProcedureName
	 * @param electronicprocedurename
	 */
	public final void setElectronicProcedureName(java.lang.String electronicprocedurename)
	{
		setElectronicProcedureName(getContext(), electronicprocedurename);
	}

	/**
	 * Set value of ElectronicProcedureName
	 * @param context
	 * @param electronicprocedurename
	 */
	public final void setElectronicProcedureName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String electronicprocedurename)
	{
		getMendixObject().setValue(context, MemberNames.ElectronicProcedureName.toString(), electronicprocedurename);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResContainerInfoJsonObject_ResContainerInfoRoot
	 */
	public final excr_eprocedure_api.proxies.ResContainerInfoRoot getResContainerInfoJsonObject_ResContainerInfoRoot() throws com.mendix.core.CoreException
	{
		return getResContainerInfoJsonObject_ResContainerInfoRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResContainerInfoJsonObject_ResContainerInfoRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ResContainerInfoRoot getResContainerInfoJsonObject_ResContainerInfoRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ResContainerInfoRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResContainerInfoJsonObject_ResContainerInfoRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ResContainerInfoRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResContainerInfoJsonObject_ResContainerInfoRoot
	 * @param rescontainerinfojsonobject_rescontainerinforoot
	 */
	public final void setResContainerInfoJsonObject_ResContainerInfoRoot(excr_eprocedure_api.proxies.ResContainerInfoRoot rescontainerinfojsonobject_rescontainerinforoot)
	{
		setResContainerInfoJsonObject_ResContainerInfoRoot(getContext(), rescontainerinfojsonobject_rescontainerinforoot);
	}

	/**
	 * Set value of ResContainerInfoJsonObject_ResContainerInfoRoot
	 * @param context
	 * @param rescontainerinfojsonobject_rescontainerinforoot
	 */
	public final void setResContainerInfoJsonObject_ResContainerInfoRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ResContainerInfoRoot rescontainerinfojsonobject_rescontainerinforoot)
	{
		if (rescontainerinfojsonobject_rescontainerinforoot == null) {
			getMendixObject().setValue(context, MemberNames.ResContainerInfoJsonObject_ResContainerInfoRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResContainerInfoJsonObject_ResContainerInfoRoot.toString(), rescontainerinfojsonobject_rescontainerinforoot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EProcedureContext_ResContainerInfoJsonObject
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ResContainerInfoJsonObject() throws com.mendix.core.CoreException
	{
		return getEProcedureContext_ResContainerInfoJsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of EProcedureContext_ResContainerInfoJsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ResContainerInfoJsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure.proxies.EProcedureContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EProcedureContext_ResContainerInfoJsonObject.toString());
		if (identifier != null) {
			result = excr_eprocedure.proxies.EProcedureContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EProcedureContext_ResContainerInfoJsonObject
	 * @param eprocedurecontext_rescontainerinfojsonobject
	 */
	public final void setEProcedureContext_ResContainerInfoJsonObject(excr_eprocedure.proxies.EProcedureContext eprocedurecontext_rescontainerinfojsonobject)
	{
		setEProcedureContext_ResContainerInfoJsonObject(getContext(), eprocedurecontext_rescontainerinfojsonobject);
	}

	/**
	 * Set value of EProcedureContext_ResContainerInfoJsonObject
	 * @param context
	 * @param eprocedurecontext_rescontainerinfojsonobject
	 */
	public final void setEProcedureContext_ResContainerInfoJsonObject(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure.proxies.EProcedureContext eprocedurecontext_rescontainerinfojsonobject)
	{
		if (eprocedurecontext_rescontainerinfojsonobject == null) {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ResContainerInfoJsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ResContainerInfoJsonObject.toString(), eprocedurecontext_rescontainerinfojsonobject.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resContainerInfoJsonObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ResContainerInfoJsonObject that = (excr_eprocedure_api.proxies.ResContainerInfoJsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
