// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ResDataCollectionDefJsonObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resDataCollectionDefJsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ResDataCollectionDefJsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceID("InstanceID"),
		Name("Name"),
		Revision("Revision"),
		IsRevOfRcd("IsRevOfRcd"),
		Description("Description"),
		ResDataCollectionDefJsonObject_ResDataCollectionDefRoot("EXCR_EProcedure_API.ResDataCollectionDefJsonObject_ResDataCollectionDefRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResDataCollectionDefJsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResDataCollectionDefJsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resDataCollectionDefJsonObjectMendixObject)
	{
		if (resDataCollectionDefJsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resDataCollectionDefJsonObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resDataCollectionDefJsonObjectMendixObject = resDataCollectionDefJsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ResDataCollectionDefJsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ResDataCollectionDefJsonObject(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ResDataCollectionDefJsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ResDataCollectionDefJsonObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID()
	{
		return getInstanceID(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceID.toString());
	}

	/**
	 * Set value of InstanceID
	 * @param instanceid
	 */
	public final void setInstanceID(java.lang.String instanceid)
	{
		setInstanceID(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceID
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceID.toString(), instanceid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @return value of IsRevOfRcd
	 */
	public final java.lang.String getIsRevOfRcd()
	{
		return getIsRevOfRcd(getContext());
	}

	/**
	 * @param context
	 * @return value of IsRevOfRcd
	 */
	public final java.lang.String getIsRevOfRcd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IsRevOfRcd.toString());
	}

	/**
	 * Set value of IsRevOfRcd
	 * @param isrevofrcd
	 */
	public final void setIsRevOfRcd(java.lang.String isrevofrcd)
	{
		setIsRevOfRcd(getContext(), isrevofrcd);
	}

	/**
	 * Set value of IsRevOfRcd
	 * @param context
	 * @param isrevofrcd
	 */
	public final void setIsRevOfRcd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String isrevofrcd)
	{
		getMendixObject().setValue(context, MemberNames.IsRevOfRcd.toString(), isrevofrcd);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResDataCollectionDefJsonObject_ResDataCollectionDefRoot
	 */
	public final excr_eprocedure_api.proxies.ResDataCollectionDefRoot getResDataCollectionDefJsonObject_ResDataCollectionDefRoot() throws com.mendix.core.CoreException
	{
		return getResDataCollectionDefJsonObject_ResDataCollectionDefRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResDataCollectionDefJsonObject_ResDataCollectionDefRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ResDataCollectionDefRoot getResDataCollectionDefJsonObject_ResDataCollectionDefRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ResDataCollectionDefRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResDataCollectionDefJsonObject_ResDataCollectionDefRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ResDataCollectionDefRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResDataCollectionDefJsonObject_ResDataCollectionDefRoot
	 * @param resdatacollectiondefjsonobject_resdatacollectiondefroot
	 */
	public final void setResDataCollectionDefJsonObject_ResDataCollectionDefRoot(excr_eprocedure_api.proxies.ResDataCollectionDefRoot resdatacollectiondefjsonobject_resdatacollectiondefroot)
	{
		setResDataCollectionDefJsonObject_ResDataCollectionDefRoot(getContext(), resdatacollectiondefjsonobject_resdatacollectiondefroot);
	}

	/**
	 * Set value of ResDataCollectionDefJsonObject_ResDataCollectionDefRoot
	 * @param context
	 * @param resdatacollectiondefjsonobject_resdatacollectiondefroot
	 */
	public final void setResDataCollectionDefJsonObject_ResDataCollectionDefRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ResDataCollectionDefRoot resdatacollectiondefjsonobject_resdatacollectiondefroot)
	{
		if (resdatacollectiondefjsonobject_resdatacollectiondefroot == null) {
			getMendixObject().setValue(context, MemberNames.ResDataCollectionDefJsonObject_ResDataCollectionDefRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResDataCollectionDefJsonObject_ResDataCollectionDefRoot.toString(), resdatacollectiondefjsonobject_resdatacollectiondefroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resDataCollectionDefJsonObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ResDataCollectionDefJsonObject that = (excr_eprocedure_api.proxies.ResDataCollectionDefJsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
