// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ResDataCollectionRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resDataCollectionRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ResDataCollectionRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_context("_odata_context"),
		ResDataCollectionValue_ResDataCollectionRoot("EXCR_EProcedure_API.ResDataCollectionValue_ResDataCollectionRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResDataCollectionRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResDataCollectionRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resDataCollectionRootMendixObject)
	{
		if (resDataCollectionRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resDataCollectionRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resDataCollectionRootMendixObject = resDataCollectionRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ResDataCollectionRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ResDataCollectionRoot(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ResDataCollectionRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ResDataCollectionRoot.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context()
	{
		return get_odata_context(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_context.toString());
	}

	/**
	 * Set value of _odata_context
	 * @param _odata_context
	 */
	public final void set_odata_context(java.lang.String _odata_context)
	{
		set_odata_context(getContext(), _odata_context);
	}

	/**
	 * Set value of _odata_context
	 * @param context
	 * @param _odata_context
	 */
	public final void set_odata_context(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_context)
	{
		getMendixObject().setValue(context, MemberNames._odata_context.toString(), _odata_context);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResDataCollectionValue_ResDataCollectionRoot
	 */
	public final excr_eprocedure_api.proxies.ResDataCollectionValue getResDataCollectionValue_ResDataCollectionRoot() throws com.mendix.core.CoreException
	{
		return getResDataCollectionValue_ResDataCollectionRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResDataCollectionValue_ResDataCollectionRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ResDataCollectionValue getResDataCollectionValue_ResDataCollectionRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ResDataCollectionValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResDataCollectionValue_ResDataCollectionRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ResDataCollectionValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResDataCollectionValue_ResDataCollectionRoot
	 * @param resdatacollectionvalue_resdatacollectionroot
	 */
	public final void setResDataCollectionValue_ResDataCollectionRoot(excr_eprocedure_api.proxies.ResDataCollectionValue resdatacollectionvalue_resdatacollectionroot)
	{
		setResDataCollectionValue_ResDataCollectionRoot(getContext(), resdatacollectionvalue_resdatacollectionroot);
	}

	/**
	 * Set value of ResDataCollectionValue_ResDataCollectionRoot
	 * @param context
	 * @param resdatacollectionvalue_resdatacollectionroot
	 */
	public final void setResDataCollectionValue_ResDataCollectionRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ResDataCollectionValue resdatacollectionvalue_resdatacollectionroot)
	{
		if (resdatacollectionvalue_resdatacollectionroot == null) {
			getMendixObject().setValue(context, MemberNames.ResDataCollectionValue_ResDataCollectionRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResDataCollectionValue_ResDataCollectionRoot.toString(), resdatacollectionvalue_resdatacollectionroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resDataCollectionRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ResDataCollectionRoot that = (excr_eprocedure_api.proxies.ResDataCollectionRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
