// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ResProcessTimerRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resProcessTimerRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ResProcessTimerRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_context("_odata_context"),
		ProcessTimerDetails_ResProcessTimerRoot("EXCR_EProcedure_API.ProcessTimerDetails_ResProcessTimerRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResProcessTimerRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResProcessTimerRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resProcessTimerRootMendixObject)
	{
		if (resProcessTimerRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resProcessTimerRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resProcessTimerRootMendixObject = resProcessTimerRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ResProcessTimerRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ResProcessTimerRoot(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ResProcessTimerRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ResProcessTimerRoot.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context()
	{
		return get_odata_context(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_context.toString());
	}

	/**
	 * Set value of _odata_context
	 * @param _odata_context
	 */
	public final void set_odata_context(java.lang.String _odata_context)
	{
		set_odata_context(getContext(), _odata_context);
	}

	/**
	 * Set value of _odata_context
	 * @param context
	 * @param _odata_context
	 */
	public final void set_odata_context(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_context)
	{
		getMendixObject().setValue(context, MemberNames._odata_context.toString(), _odata_context);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ProcessTimerDetails_ResProcessTimerRoot
	 */
	public final excr_eprocedure_api.proxies.ProcessTimerDetails getProcessTimerDetails_ResProcessTimerRoot() throws com.mendix.core.CoreException
	{
		return getProcessTimerDetails_ResProcessTimerRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessTimerDetails_ResProcessTimerRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ProcessTimerDetails getProcessTimerDetails_ResProcessTimerRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ProcessTimerDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProcessTimerDetails_ResProcessTimerRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ProcessTimerDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ProcessTimerDetails_ResProcessTimerRoot
	 * @param processtimerdetails_resprocesstimerroot
	 */
	public final void setProcessTimerDetails_ResProcessTimerRoot(excr_eprocedure_api.proxies.ProcessTimerDetails processtimerdetails_resprocesstimerroot)
	{
		setProcessTimerDetails_ResProcessTimerRoot(getContext(), processtimerdetails_resprocesstimerroot);
	}

	/**
	 * Set value of ProcessTimerDetails_ResProcessTimerRoot
	 * @param context
	 * @param processtimerdetails_resprocesstimerroot
	 */
	public final void setProcessTimerDetails_ResProcessTimerRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ProcessTimerDetails processtimerdetails_resprocesstimerroot)
	{
		if (processtimerdetails_resprocesstimerroot == null) {
			getMendixObject().setValue(context, MemberNames.ProcessTimerDetails_ResProcessTimerRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ProcessTimerDetails_ResProcessTimerRoot.toString(), processtimerdetails_resprocesstimerroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resProcessTimerRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ResProcessTimerRoot that = (excr_eprocedure_api.proxies.ResProcessTimerRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
