// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ResPathJsonObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resPathJsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ResPathJsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		OwnerName("OwnerName"),
		OwnerInstanceId("OwnerInstanceId"),
		IsFrozen("IsFrozen"),
		InstanceId("InstanceId"),
		ResPathJsonObject_ResPathRoot("EXCR_EProcedure_API.ResPathJsonObject_ResPathRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResPathJsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResPathJsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resPathJsonObjectMendixObject)
	{
		if (resPathJsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resPathJsonObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resPathJsonObjectMendixObject = resPathJsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ResPathJsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ResPathJsonObject(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ResPathJsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ResPathJsonObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName()
	{
		return getOwnerName(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OwnerName.toString());
	}

	/**
	 * Set value of OwnerName
	 * @param ownername
	 */
	public final void setOwnerName(java.lang.String ownername)
	{
		setOwnerName(getContext(), ownername);
	}

	/**
	 * Set value of OwnerName
	 * @param context
	 * @param ownername
	 */
	public final void setOwnerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ownername)
	{
		getMendixObject().setValue(context, MemberNames.OwnerName.toString(), ownername);
	}

	/**
	 * @return value of OwnerInstanceId
	 */
	public final java.lang.String getOwnerInstanceId()
	{
		return getOwnerInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnerInstanceId
	 */
	public final java.lang.String getOwnerInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OwnerInstanceId.toString());
	}

	/**
	 * Set value of OwnerInstanceId
	 * @param ownerinstanceid
	 */
	public final void setOwnerInstanceId(java.lang.String ownerinstanceid)
	{
		setOwnerInstanceId(getContext(), ownerinstanceid);
	}

	/**
	 * Set value of OwnerInstanceId
	 * @param context
	 * @param ownerinstanceid
	 */
	public final void setOwnerInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ownerinstanceid)
	{
		getMendixObject().setValue(context, MemberNames.OwnerInstanceId.toString(), ownerinstanceid);
	}

	/**
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen()
	{
		return getIsFrozen(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IsFrozen.toString());
	}

	/**
	 * Set value of IsFrozen
	 * @param isfrozen
	 */
	public final void setIsFrozen(java.lang.String isfrozen)
	{
		setIsFrozen(getContext(), isfrozen);
	}

	/**
	 * Set value of IsFrozen
	 * @param context
	 * @param isfrozen
	 */
	public final void setIsFrozen(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String isfrozen)
	{
		getMendixObject().setValue(context, MemberNames.IsFrozen.toString(), isfrozen);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResPathJsonObject_ResPathRoot
	 */
	public final excr_eprocedure_api.proxies.ResPathRoot getResPathJsonObject_ResPathRoot() throws com.mendix.core.CoreException
	{
		return getResPathJsonObject_ResPathRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResPathJsonObject_ResPathRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ResPathRoot getResPathJsonObject_ResPathRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ResPathRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResPathJsonObject_ResPathRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ResPathRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResPathJsonObject_ResPathRoot
	 * @param respathjsonobject_respathroot
	 */
	public final void setResPathJsonObject_ResPathRoot(excr_eprocedure_api.proxies.ResPathRoot respathjsonobject_respathroot)
	{
		setResPathJsonObject_ResPathRoot(getContext(), respathjsonobject_respathroot);
	}

	/**
	 * Set value of ResPathJsonObject_ResPathRoot
	 * @param context
	 * @param respathjsonobject_respathroot
	 */
	public final void setResPathJsonObject_ResPathRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ResPathRoot respathjsonobject_respathroot)
	{
		if (respathjsonobject_respathroot == null) {
			getMendixObject().setValue(context, MemberNames.ResPathJsonObject_ResPathRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResPathJsonObject_ResPathRoot.toString(), respathjsonobject_respathroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resPathJsonObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ResPathJsonObject that = (excr_eprocedure_api.proxies.ResPathJsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
