// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ResPauseTaskTimer implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resPauseTaskTimerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ResPauseTaskTimer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ElapsedTaskTime("ElapsedTaskTime"),
		EProcedureContext_ResPauseTaskTimer("EXCR_EProcedure.EProcedureContext_ResPauseTaskTimer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResPauseTaskTimer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResPauseTaskTimer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resPauseTaskTimerMendixObject)
	{
		if (resPauseTaskTimerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resPauseTaskTimerMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resPauseTaskTimerMendixObject = resPauseTaskTimerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ResPauseTaskTimer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ResPauseTaskTimer(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ResPauseTaskTimer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ResPauseTaskTimer.initialize(context, mendixObject);
	}

	/**
	 * @return value of ElapsedTaskTime
	 */
	public final java.math.BigDecimal getElapsedTaskTime()
	{
		return getElapsedTaskTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ElapsedTaskTime
	 */
	public final java.math.BigDecimal getElapsedTaskTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ElapsedTaskTime.toString());
	}

	/**
	 * Set value of ElapsedTaskTime
	 * @param elapsedtasktime
	 */
	public final void setElapsedTaskTime(java.math.BigDecimal elapsedtasktime)
	{
		setElapsedTaskTime(getContext(), elapsedtasktime);
	}

	/**
	 * Set value of ElapsedTaskTime
	 * @param context
	 * @param elapsedtasktime
	 */
	public final void setElapsedTaskTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal elapsedtasktime)
	{
		getMendixObject().setValue(context, MemberNames.ElapsedTaskTime.toString(), elapsedtasktime);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EProcedureContext_ResPauseTaskTimer
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ResPauseTaskTimer() throws com.mendix.core.CoreException
	{
		return getEProcedureContext_ResPauseTaskTimer(getContext());
	}

	/**
	 * @param context
	 * @return value of EProcedureContext_ResPauseTaskTimer
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ResPauseTaskTimer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure.proxies.EProcedureContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EProcedureContext_ResPauseTaskTimer.toString());
		if (identifier != null) {
			result = excr_eprocedure.proxies.EProcedureContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EProcedureContext_ResPauseTaskTimer
	 * @param eprocedurecontext_respausetasktimer
	 */
	public final void setEProcedureContext_ResPauseTaskTimer(excr_eprocedure.proxies.EProcedureContext eprocedurecontext_respausetasktimer)
	{
		setEProcedureContext_ResPauseTaskTimer(getContext(), eprocedurecontext_respausetasktimer);
	}

	/**
	 * Set value of EProcedureContext_ResPauseTaskTimer
	 * @param context
	 * @param eprocedurecontext_respausetasktimer
	 */
	public final void setEProcedureContext_ResPauseTaskTimer(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure.proxies.EProcedureContext eprocedurecontext_respausetasktimer)
	{
		if (eprocedurecontext_respausetasktimer == null) {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ResPauseTaskTimer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ResPauseTaskTimer.toString(), eprocedurecontext_respausetasktimer.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resPauseTaskTimerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ResPauseTaskTimer that = (excr_eprocedure_api.proxies.ResPauseTaskTimer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
