// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class ResTaskDocs_Document implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resTaskDocs_DocumentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.ResTaskDocs_Document";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ResTaskDocs_DocumentName("ResTaskDocs_DocumentName"),
		ResTaskDocs_DocumentRevision("ResTaskDocs_DocumentRevision"),
		ResTaskDocs_Document_ResTaskDocs_DocumentEntry("EXCR_EProcedure_API.ResTaskDocs_Document_ResTaskDocs_DocumentEntry");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResTaskDocs_Document(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResTaskDocs_Document(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resTaskDocs_DocumentMendixObject)
	{
		if (resTaskDocs_DocumentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resTaskDocs_DocumentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resTaskDocs_DocumentMendixObject = resTaskDocs_DocumentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.ResTaskDocs_Document initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.ResTaskDocs_Document(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.ResTaskDocs_Document load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.ResTaskDocs_Document.initialize(context, mendixObject);
	}

	/**
	 * @return value of ResTaskDocs_DocumentName
	 */
	public final java.lang.String getResTaskDocs_DocumentName()
	{
		return getResTaskDocs_DocumentName(getContext());
	}

	/**
	 * @param context
	 * @return value of ResTaskDocs_DocumentName
	 */
	public final java.lang.String getResTaskDocs_DocumentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResTaskDocs_DocumentName.toString());
	}

	/**
	 * Set value of ResTaskDocs_DocumentName
	 * @param restaskdocs_documentname
	 */
	public final void setResTaskDocs_DocumentName(java.lang.String restaskdocs_documentname)
	{
		setResTaskDocs_DocumentName(getContext(), restaskdocs_documentname);
	}

	/**
	 * Set value of ResTaskDocs_DocumentName
	 * @param context
	 * @param restaskdocs_documentname
	 */
	public final void setResTaskDocs_DocumentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String restaskdocs_documentname)
	{
		getMendixObject().setValue(context, MemberNames.ResTaskDocs_DocumentName.toString(), restaskdocs_documentname);
	}

	/**
	 * @return value of ResTaskDocs_DocumentRevision
	 */
	public final java.lang.String getResTaskDocs_DocumentRevision()
	{
		return getResTaskDocs_DocumentRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of ResTaskDocs_DocumentRevision
	 */
	public final java.lang.String getResTaskDocs_DocumentRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResTaskDocs_DocumentRevision.toString());
	}

	/**
	 * Set value of ResTaskDocs_DocumentRevision
	 * @param restaskdocs_documentrevision
	 */
	public final void setResTaskDocs_DocumentRevision(java.lang.String restaskdocs_documentrevision)
	{
		setResTaskDocs_DocumentRevision(getContext(), restaskdocs_documentrevision);
	}

	/**
	 * Set value of ResTaskDocs_DocumentRevision
	 * @param context
	 * @param restaskdocs_documentrevision
	 */
	public final void setResTaskDocs_DocumentRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String restaskdocs_documentrevision)
	{
		getMendixObject().setValue(context, MemberNames.ResTaskDocs_DocumentRevision.toString(), restaskdocs_documentrevision);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResTaskDocs_Document_ResTaskDocs_DocumentEntry
	 */
	public final excr_eprocedure_api.proxies.ResTaskDocs_DocumentEntry getResTaskDocs_Document_ResTaskDocs_DocumentEntry() throws com.mendix.core.CoreException
	{
		return getResTaskDocs_Document_ResTaskDocs_DocumentEntry(getContext());
	}

	/**
	 * @param context
	 * @return value of ResTaskDocs_Document_ResTaskDocs_DocumentEntry
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ResTaskDocs_DocumentEntry getResTaskDocs_Document_ResTaskDocs_DocumentEntry(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ResTaskDocs_DocumentEntry result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResTaskDocs_Document_ResTaskDocs_DocumentEntry.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ResTaskDocs_DocumentEntry.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResTaskDocs_Document_ResTaskDocs_DocumentEntry
	 * @param restaskdocs_document_restaskdocs_documententry
	 */
	public final void setResTaskDocs_Document_ResTaskDocs_DocumentEntry(excr_eprocedure_api.proxies.ResTaskDocs_DocumentEntry restaskdocs_document_restaskdocs_documententry)
	{
		setResTaskDocs_Document_ResTaskDocs_DocumentEntry(getContext(), restaskdocs_document_restaskdocs_documententry);
	}

	/**
	 * Set value of ResTaskDocs_Document_ResTaskDocs_DocumentEntry
	 * @param context
	 * @param restaskdocs_document_restaskdocs_documententry
	 */
	public final void setResTaskDocs_Document_ResTaskDocs_DocumentEntry(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ResTaskDocs_DocumentEntry restaskdocs_document_restaskdocs_documententry)
	{
		if (restaskdocs_document_restaskdocs_documententry == null) {
			getMendixObject().setValue(context, MemberNames.ResTaskDocs_Document_ResTaskDocs_DocumentEntry.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResTaskDocs_Document_ResTaskDocs_DocumentEntry.toString(), restaskdocs_document_restaskdocs_documententry.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resTaskDocs_DocumentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.ResTaskDocs_Document that = (excr_eprocedure_api.proxies.ResTaskDocs_Document) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
