// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class Signer implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject signerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.Signer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Signer_CaptureDetail("EXCR_EProcedure_API.Signer_CaptureDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Signer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Signer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject signerMendixObject)
	{
		if (signerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!signerMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.signerMendixObject = signerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.Signer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.Signer(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.Signer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.Signer.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Signer_CaptureDetail
	 */
	public final excr_eprocedure_api.proxies.CaptureDetail getSigner_CaptureDetail() throws com.mendix.core.CoreException
	{
		return getSigner_CaptureDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of Signer_CaptureDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.CaptureDetail getSigner_CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.CaptureDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Signer_CaptureDetail.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.CaptureDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Signer_CaptureDetail
	 * @param signer_capturedetail
	 */
	public final void setSigner_CaptureDetail(excr_eprocedure_api.proxies.CaptureDetail signer_capturedetail)
	{
		setSigner_CaptureDetail(getContext(), signer_capturedetail);
	}

	/**
	 * Set value of Signer_CaptureDetail
	 * @param context
	 * @param signer_capturedetail
	 */
	public final void setSigner_CaptureDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.CaptureDetail signer_capturedetail)
	{
		if (signer_capturedetail == null) {
			getMendixObject().setValue(context, MemberNames.Signer_CaptureDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Signer_CaptureDetail.toString(), signer_capturedetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return signerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.Signer that = (excr_eprocedure_api.proxies.Signer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
