// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class Step implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stepMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.Step";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Step_PauseTaskTimerRoot("EXCR_EProcedure_API.Step_PauseTaskTimerRoot"),
		Parent_Step("EXCR_EProcedure_API.Parent_Step");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Step(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Step(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stepMendixObject)
	{
		if (stepMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!stepMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.stepMendixObject = stepMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.Step initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.Step(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.Step load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.Step.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Step_PauseTaskTimerRoot
	 */
	public final excr_eprocedure_api.proxies.PauseTaskTimerRoot getStep_PauseTaskTimerRoot() throws com.mendix.core.CoreException
	{
		return getStep_PauseTaskTimerRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Step_PauseTaskTimerRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.PauseTaskTimerRoot getStep_PauseTaskTimerRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.PauseTaskTimerRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Step_PauseTaskTimerRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.PauseTaskTimerRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Step_PauseTaskTimerRoot
	 * @param step_pausetasktimerroot
	 */
	public final void setStep_PauseTaskTimerRoot(excr_eprocedure_api.proxies.PauseTaskTimerRoot step_pausetasktimerroot)
	{
		setStep_PauseTaskTimerRoot(getContext(), step_pausetasktimerroot);
	}

	/**
	 * Set value of Step_PauseTaskTimerRoot
	 * @param context
	 * @param step_pausetasktimerroot
	 */
	public final void setStep_PauseTaskTimerRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.PauseTaskTimerRoot step_pausetasktimerroot)
	{
		if (step_pausetasktimerroot == null) {
			getMendixObject().setValue(context, MemberNames.Step_PauseTaskTimerRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Step_PauseTaskTimerRoot.toString(), step_pausetasktimerroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_Step
	 */
	public final excr_eprocedure_api.proxies.Parent getParent_Step() throws com.mendix.core.CoreException
	{
		return getParent_Step(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_Step
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.Parent getParent_Step(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.Parent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_Step.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.Parent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_Step
	 * @param parent_step
	 */
	public final void setParent_Step(excr_eprocedure_api.proxies.Parent parent_step)
	{
		setParent_Step(getContext(), parent_step);
	}

	/**
	 * Set value of Parent_Step
	 * @param context
	 * @param parent_step
	 */
	public final void setParent_Step(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.Parent parent_step)
	{
		if (parent_step == null) {
			getMendixObject().setValue(context, MemberNames.Parent_Step.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_Step.toString(), parent_step.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stepMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.Step that = (excr_eprocedure_api.proxies.Step) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
