// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class TaskTimerInfo implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskTimerInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.TaskTimerInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceID("InstanceID"),
		Name("Name"),
		AllocatedTime("AllocatedTime"),
		EProcedureContext_TaskTimerInfo("EXCR_EProcedure.EProcedureContext_TaskTimerInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaskTimerInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TaskTimerInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskTimerInfoMendixObject)
	{
		if (taskTimerInfoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!taskTimerInfoMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.taskTimerInfoMendixObject = taskTimerInfoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.TaskTimerInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.TaskTimerInfo(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.TaskTimerInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.TaskTimerInfo.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID()
	{
		return getInstanceID(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceID.toString());
	}

	/**
	 * Set value of InstanceID
	 * @param instanceid
	 */
	public final void setInstanceID(java.lang.String instanceid)
	{
		setInstanceID(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceID
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceID.toString(), instanceid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of AllocatedTime
	 */
	public final java.math.BigDecimal getAllocatedTime()
	{
		return getAllocatedTime(getContext());
	}

	/**
	 * @param context
	 * @return value of AllocatedTime
	 */
	public final java.math.BigDecimal getAllocatedTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AllocatedTime.toString());
	}

	/**
	 * Set value of AllocatedTime
	 * @param allocatedtime
	 */
	public final void setAllocatedTime(java.math.BigDecimal allocatedtime)
	{
		setAllocatedTime(getContext(), allocatedtime);
	}

	/**
	 * Set value of AllocatedTime
	 * @param context
	 * @param allocatedtime
	 */
	public final void setAllocatedTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal allocatedtime)
	{
		getMendixObject().setValue(context, MemberNames.AllocatedTime.toString(), allocatedtime);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EProcedureContext_TaskTimerInfo
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_TaskTimerInfo() throws com.mendix.core.CoreException
	{
		return getEProcedureContext_TaskTimerInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of EProcedureContext_TaskTimerInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_TaskTimerInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure.proxies.EProcedureContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EProcedureContext_TaskTimerInfo.toString());
		if (identifier != null) {
			result = excr_eprocedure.proxies.EProcedureContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EProcedureContext_TaskTimerInfo
	 * @param eprocedurecontext_tasktimerinfo
	 */
	public final void setEProcedureContext_TaskTimerInfo(excr_eprocedure.proxies.EProcedureContext eprocedurecontext_tasktimerinfo)
	{
		setEProcedureContext_TaskTimerInfo(getContext(), eprocedurecontext_tasktimerinfo);
	}

	/**
	 * Set value of EProcedureContext_TaskTimerInfo
	 * @param context
	 * @param eprocedurecontext_tasktimerinfo
	 */
	public final void setEProcedureContext_TaskTimerInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure.proxies.EProcedureContext eprocedurecontext_tasktimerinfo)
	{
		if (eprocedurecontext_tasktimerinfo == null) {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_TaskTimerInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_TaskTimerInfo.toString(), eprocedurecontext_tasktimerinfo.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskTimerInfoMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.TaskTimerInfo that = (excr_eprocedure_api.proxies.TaskTimerInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
