// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class TaskList implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskListMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.TaskList";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Revision("Revision"),
		_odata_type("_odata_type"),
		ReqAcknowledgementTaskCDOTypeName("ReqAcknowledgementTaskCDOTypeName"),
		TaskListName("TaskListName"),
		TaskListRevision("TaskListRevision"),
		ReqPassFailTaskCDOTypeName("ReqPassFailTaskCDOTypeName"),
		CDOTypeName("CDOTypeName"),
		TaskList_ReqTaskFromTaskListRoot("EXCR_EProcedure_API.TaskList_ReqTaskFromTaskListRoot"),
		TaskList_TaskListRoot("EXCR_EProcedure_API.TaskList_TaskListRoot"),
		TaskList_ReqAcknowledgementTaskRoot("EXCR_EProcedure_API.TaskList_ReqAcknowledgementTaskRoot"),
		TaskList_ReqPassFailTaskRoot("EXCR_EProcedure_API.TaskList_ReqPassFailTaskRoot"),
		TaskList_InputData("EXCR_EProcedure_API.TaskList_InputData"),
		TaskList_ReqContainerCollectDataRoot("EXCR_EProcedure_API.TaskList_ReqContainerCollectDataRoot"),
		TaskList_OnlineQueryAPI("EXCR_EProcedure_API.TaskList_OnlineQueryAPI");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaskList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TaskList(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskListMendixObject)
	{
		if (taskListMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!taskListMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.taskListMendixObject = taskListMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.TaskList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.TaskList(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.TaskList load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.TaskList.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of ReqAcknowledgementTaskCDOTypeName
	 */
	public final java.lang.String getReqAcknowledgementTaskCDOTypeName()
	{
		return getReqAcknowledgementTaskCDOTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqAcknowledgementTaskCDOTypeName
	 */
	public final java.lang.String getReqAcknowledgementTaskCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReqAcknowledgementTaskCDOTypeName.toString());
	}

	/**
	 * Set value of ReqAcknowledgementTaskCDOTypeName
	 * @param reqacknowledgementtaskcdotypename
	 */
	public final void setReqAcknowledgementTaskCDOTypeName(java.lang.String reqacknowledgementtaskcdotypename)
	{
		setReqAcknowledgementTaskCDOTypeName(getContext(), reqacknowledgementtaskcdotypename);
	}

	/**
	 * Set value of ReqAcknowledgementTaskCDOTypeName
	 * @param context
	 * @param reqacknowledgementtaskcdotypename
	 */
	public final void setReqAcknowledgementTaskCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reqacknowledgementtaskcdotypename)
	{
		getMendixObject().setValue(context, MemberNames.ReqAcknowledgementTaskCDOTypeName.toString(), reqacknowledgementtaskcdotypename);
	}

	/**
	 * @return value of TaskListName
	 */
	public final java.lang.String getTaskListName()
	{
		return getTaskListName(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskListName
	 */
	public final java.lang.String getTaskListName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskListName.toString());
	}

	/**
	 * Set value of TaskListName
	 * @param tasklistname
	 */
	public final void setTaskListName(java.lang.String tasklistname)
	{
		setTaskListName(getContext(), tasklistname);
	}

	/**
	 * Set value of TaskListName
	 * @param context
	 * @param tasklistname
	 */
	public final void setTaskListName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tasklistname)
	{
		getMendixObject().setValue(context, MemberNames.TaskListName.toString(), tasklistname);
	}

	/**
	 * @return value of TaskListRevision
	 */
	public final java.lang.String getTaskListRevision()
	{
		return getTaskListRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskListRevision
	 */
	public final java.lang.String getTaskListRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskListRevision.toString());
	}

	/**
	 * Set value of TaskListRevision
	 * @param tasklistrevision
	 */
	public final void setTaskListRevision(java.lang.String tasklistrevision)
	{
		setTaskListRevision(getContext(), tasklistrevision);
	}

	/**
	 * Set value of TaskListRevision
	 * @param context
	 * @param tasklistrevision
	 */
	public final void setTaskListRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tasklistrevision)
	{
		getMendixObject().setValue(context, MemberNames.TaskListRevision.toString(), tasklistrevision);
	}

	/**
	 * @return value of ReqPassFailTaskCDOTypeName
	 */
	public final java.lang.String getReqPassFailTaskCDOTypeName()
	{
		return getReqPassFailTaskCDOTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqPassFailTaskCDOTypeName
	 */
	public final java.lang.String getReqPassFailTaskCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReqPassFailTaskCDOTypeName.toString());
	}

	/**
	 * Set value of ReqPassFailTaskCDOTypeName
	 * @param reqpassfailtaskcdotypename
	 */
	public final void setReqPassFailTaskCDOTypeName(java.lang.String reqpassfailtaskcdotypename)
	{
		setReqPassFailTaskCDOTypeName(getContext(), reqpassfailtaskcdotypename);
	}

	/**
	 * Set value of ReqPassFailTaskCDOTypeName
	 * @param context
	 * @param reqpassfailtaskcdotypename
	 */
	public final void setReqPassFailTaskCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reqpassfailtaskcdotypename)
	{
		getMendixObject().setValue(context, MemberNames.ReqPassFailTaskCDOTypeName.toString(), reqpassfailtaskcdotypename);
	}

	/**
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName()
	{
		return getCDOTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CDOTypeName.toString());
	}

	/**
	 * Set value of CDOTypeName
	 * @param cdotypename
	 */
	public final void setCDOTypeName(java.lang.String cdotypename)
	{
		setCDOTypeName(getContext(), cdotypename);
	}

	/**
	 * Set value of CDOTypeName
	 * @param context
	 * @param cdotypename
	 */
	public final void setCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cdotypename)
	{
		getMendixObject().setValue(context, MemberNames.CDOTypeName.toString(), cdotypename);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_ReqTaskFromTaskListRoot
	 */
	public final excr_eprocedure_api.proxies.ReqTaskFromTaskListRoot getTaskList_ReqTaskFromTaskListRoot() throws com.mendix.core.CoreException
	{
		return getTaskList_ReqTaskFromTaskListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_ReqTaskFromTaskListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqTaskFromTaskListRoot getTaskList_ReqTaskFromTaskListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqTaskFromTaskListRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_ReqTaskFromTaskListRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqTaskFromTaskListRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_ReqTaskFromTaskListRoot
	 * @param tasklist_reqtaskfromtasklistroot
	 */
	public final void setTaskList_ReqTaskFromTaskListRoot(excr_eprocedure_api.proxies.ReqTaskFromTaskListRoot tasklist_reqtaskfromtasklistroot)
	{
		setTaskList_ReqTaskFromTaskListRoot(getContext(), tasklist_reqtaskfromtasklistroot);
	}

	/**
	 * Set value of TaskList_ReqTaskFromTaskListRoot
	 * @param context
	 * @param tasklist_reqtaskfromtasklistroot
	 */
	public final void setTaskList_ReqTaskFromTaskListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqTaskFromTaskListRoot tasklist_reqtaskfromtasklistroot)
	{
		if (tasklist_reqtaskfromtasklistroot == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_ReqTaskFromTaskListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_ReqTaskFromTaskListRoot.toString(), tasklist_reqtaskfromtasklistroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_TaskListRoot
	 */
	public final excr_eprocedure_api.proxies.TaskListRoot getTaskList_TaskListRoot() throws com.mendix.core.CoreException
	{
		return getTaskList_TaskListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_TaskListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.TaskListRoot getTaskList_TaskListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.TaskListRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_TaskListRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.TaskListRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_TaskListRoot
	 * @param tasklist_tasklistroot
	 */
	public final void setTaskList_TaskListRoot(excr_eprocedure_api.proxies.TaskListRoot tasklist_tasklistroot)
	{
		setTaskList_TaskListRoot(getContext(), tasklist_tasklistroot);
	}

	/**
	 * Set value of TaskList_TaskListRoot
	 * @param context
	 * @param tasklist_tasklistroot
	 */
	public final void setTaskList_TaskListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.TaskListRoot tasklist_tasklistroot)
	{
		if (tasklist_tasklistroot == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_TaskListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_TaskListRoot.toString(), tasklist_tasklistroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_ReqAcknowledgementTaskRoot
	 */
	public final excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot getTaskList_ReqAcknowledgementTaskRoot() throws com.mendix.core.CoreException
	{
		return getTaskList_ReqAcknowledgementTaskRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_ReqAcknowledgementTaskRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot getTaskList_ReqAcknowledgementTaskRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_ReqAcknowledgementTaskRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_ReqAcknowledgementTaskRoot
	 * @param tasklist_reqacknowledgementtaskroot
	 */
	public final void setTaskList_ReqAcknowledgementTaskRoot(excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot tasklist_reqacknowledgementtaskroot)
	{
		setTaskList_ReqAcknowledgementTaskRoot(getContext(), tasklist_reqacknowledgementtaskroot);
	}

	/**
	 * Set value of TaskList_ReqAcknowledgementTaskRoot
	 * @param context
	 * @param tasklist_reqacknowledgementtaskroot
	 */
	public final void setTaskList_ReqAcknowledgementTaskRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot tasklist_reqacknowledgementtaskroot)
	{
		if (tasklist_reqacknowledgementtaskroot == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_ReqAcknowledgementTaskRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_ReqAcknowledgementTaskRoot.toString(), tasklist_reqacknowledgementtaskroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_ReqPassFailTaskRoot
	 */
	public final excr_eprocedure_api.proxies.ReqPassFailTaskRoot getTaskList_ReqPassFailTaskRoot() throws com.mendix.core.CoreException
	{
		return getTaskList_ReqPassFailTaskRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_ReqPassFailTaskRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqPassFailTaskRoot getTaskList_ReqPassFailTaskRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqPassFailTaskRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_ReqPassFailTaskRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqPassFailTaskRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_ReqPassFailTaskRoot
	 * @param tasklist_reqpassfailtaskroot
	 */
	public final void setTaskList_ReqPassFailTaskRoot(excr_eprocedure_api.proxies.ReqPassFailTaskRoot tasklist_reqpassfailtaskroot)
	{
		setTaskList_ReqPassFailTaskRoot(getContext(), tasklist_reqpassfailtaskroot);
	}

	/**
	 * Set value of TaskList_ReqPassFailTaskRoot
	 * @param context
	 * @param tasklist_reqpassfailtaskroot
	 */
	public final void setTaskList_ReqPassFailTaskRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqPassFailTaskRoot tasklist_reqpassfailtaskroot)
	{
		if (tasklist_reqpassfailtaskroot == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_ReqPassFailTaskRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_ReqPassFailTaskRoot.toString(), tasklist_reqpassfailtaskroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_InputData
	 */
	public final excr_eprocedure_api.proxies.InputData getTaskList_InputData() throws com.mendix.core.CoreException
	{
		return getTaskList_InputData(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_InputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.InputData getTaskList_InputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.InputData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_InputData.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.InputData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_InputData
	 * @param tasklist_inputdata
	 */
	public final void setTaskList_InputData(excr_eprocedure_api.proxies.InputData tasklist_inputdata)
	{
		setTaskList_InputData(getContext(), tasklist_inputdata);
	}

	/**
	 * Set value of TaskList_InputData
	 * @param context
	 * @param tasklist_inputdata
	 */
	public final void setTaskList_InputData(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.InputData tasklist_inputdata)
	{
		if (tasklist_inputdata == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_InputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_InputData.toString(), tasklist_inputdata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_ReqContainerCollectDataRoot
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRoot getTaskList_ReqContainerCollectDataRoot() throws com.mendix.core.CoreException
	{
		return getTaskList_ReqContainerCollectDataRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_ReqContainerCollectDataRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRoot getTaskList_ReqContainerCollectDataRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_ReqContainerCollectDataRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_ReqContainerCollectDataRoot
	 * @param tasklist_reqcontainercollectdataroot
	 */
	public final void setTaskList_ReqContainerCollectDataRoot(excr_eprocedure_api.proxies.ReqContainerCollectDataRoot tasklist_reqcontainercollectdataroot)
	{
		setTaskList_ReqContainerCollectDataRoot(getContext(), tasklist_reqcontainercollectdataroot);
	}

	/**
	 * Set value of TaskList_ReqContainerCollectDataRoot
	 * @param context
	 * @param tasklist_reqcontainercollectdataroot
	 */
	public final void setTaskList_ReqContainerCollectDataRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataRoot tasklist_reqcontainercollectdataroot)
	{
		if (tasklist_reqcontainercollectdataroot == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_ReqContainerCollectDataRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_ReqContainerCollectDataRoot.toString(), tasklist_reqcontainercollectdataroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_OnlineQueryAPI
	 */
	public final excr_eprocedure_api.proxies.OnlineQueryAPI getTaskList_OnlineQueryAPI() throws com.mendix.core.CoreException
	{
		return getTaskList_OnlineQueryAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_OnlineQueryAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.OnlineQueryAPI getTaskList_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.OnlineQueryAPI result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_OnlineQueryAPI.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.OnlineQueryAPI.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_OnlineQueryAPI
	 * @param tasklist_onlinequeryapi
	 */
	public final void setTaskList_OnlineQueryAPI(excr_eprocedure_api.proxies.OnlineQueryAPI tasklist_onlinequeryapi)
	{
		setTaskList_OnlineQueryAPI(getContext(), tasklist_onlinequeryapi);
	}

	/**
	 * Set value of TaskList_OnlineQueryAPI
	 * @param context
	 * @param tasklist_onlinequeryapi
	 */
	public final void setTaskList_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.OnlineQueryAPI tasklist_onlinequeryapi)
	{
		if (tasklist_onlinequeryapi == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_OnlineQueryAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_OnlineQueryAPI.toString(), tasklist_onlinequeryapi.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskListMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.TaskList that = (excr_eprocedure_api.proxies.TaskList) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
