// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class Task implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.Task";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		TaskName("TaskName"),
		InstanceId("InstanceId"),
		Task_ReqAcknowledgementTaskRoot("EXCR_EProcedure_API.Task_ReqAcknowledgementTaskRoot"),
		Parent_Task("EXCR_EProcedure_API.Parent_Task"),
		Task_ReqPassFailTaskRoot("EXCR_EProcedure_API.Task_ReqPassFailTaskRoot"),
		Task_InputData("EXCR_EProcedure_API.Task_InputData"),
		Task_ReqContainerCollectDataRoot("EXCR_EProcedure_API.Task_ReqContainerCollectDataRoot"),
		Task_EprocDataCollecionDefRoot("EXCR_EProcedure_API.Task_EprocDataCollecionDefRoot"),
		EprocDataCollectionDefParent_Task("EXCR_EProcedure_API.EprocDataCollectionDefParent_Task"),
		Task_PauseTaskTimerRoot("EXCR_EProcedure_API.Task_PauseTaskTimerRoot"),
		Task_OnlineQueryAPI("EXCR_EProcedure_API.Task_OnlineQueryAPI");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Task(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Task(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskMendixObject)
	{
		if (taskMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!taskMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.taskMendixObject = taskMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.Task initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.Task(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.Task load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.Task.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of TaskName
	 */
	public final java.lang.String getTaskName()
	{
		return getTaskName(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskName
	 */
	public final java.lang.String getTaskName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskName.toString());
	}

	/**
	 * Set value of TaskName
	 * @param taskname
	 */
	public final void setTaskName(java.lang.String taskname)
	{
		setTaskName(getContext(), taskname);
	}

	/**
	 * Set value of TaskName
	 * @param context
	 * @param taskname
	 */
	public final void setTaskName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taskname)
	{
		getMendixObject().setValue(context, MemberNames.TaskName.toString(), taskname);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_ReqAcknowledgementTaskRoot
	 */
	public final excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot getTask_ReqAcknowledgementTaskRoot() throws com.mendix.core.CoreException
	{
		return getTask_ReqAcknowledgementTaskRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_ReqAcknowledgementTaskRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot getTask_ReqAcknowledgementTaskRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_ReqAcknowledgementTaskRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_ReqAcknowledgementTaskRoot
	 * @param task_reqacknowledgementtaskroot
	 */
	public final void setTask_ReqAcknowledgementTaskRoot(excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot task_reqacknowledgementtaskroot)
	{
		setTask_ReqAcknowledgementTaskRoot(getContext(), task_reqacknowledgementtaskroot);
	}

	/**
	 * Set value of Task_ReqAcknowledgementTaskRoot
	 * @param context
	 * @param task_reqacknowledgementtaskroot
	 */
	public final void setTask_ReqAcknowledgementTaskRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqAcknowledgementTaskRoot task_reqacknowledgementtaskroot)
	{
		if (task_reqacknowledgementtaskroot == null) {
			getMendixObject().setValue(context, MemberNames.Task_ReqAcknowledgementTaskRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_ReqAcknowledgementTaskRoot.toString(), task_reqacknowledgementtaskroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_Task
	 */
	public final excr_eprocedure_api.proxies.Parent getParent_Task() throws com.mendix.core.CoreException
	{
		return getParent_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_Task
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.Parent getParent_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.Parent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_Task.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.Parent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_Task
	 * @param parent_task
	 */
	public final void setParent_Task(excr_eprocedure_api.proxies.Parent parent_task)
	{
		setParent_Task(getContext(), parent_task);
	}

	/**
	 * Set value of Parent_Task
	 * @param context
	 * @param parent_task
	 */
	public final void setParent_Task(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.Parent parent_task)
	{
		if (parent_task == null) {
			getMendixObject().setValue(context, MemberNames.Parent_Task.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_Task.toString(), parent_task.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_ReqPassFailTaskRoot
	 */
	public final excr_eprocedure_api.proxies.ReqPassFailTaskRoot getTask_ReqPassFailTaskRoot() throws com.mendix.core.CoreException
	{
		return getTask_ReqPassFailTaskRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_ReqPassFailTaskRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqPassFailTaskRoot getTask_ReqPassFailTaskRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqPassFailTaskRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_ReqPassFailTaskRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqPassFailTaskRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_ReqPassFailTaskRoot
	 * @param task_reqpassfailtaskroot
	 */
	public final void setTask_ReqPassFailTaskRoot(excr_eprocedure_api.proxies.ReqPassFailTaskRoot task_reqpassfailtaskroot)
	{
		setTask_ReqPassFailTaskRoot(getContext(), task_reqpassfailtaskroot);
	}

	/**
	 * Set value of Task_ReqPassFailTaskRoot
	 * @param context
	 * @param task_reqpassfailtaskroot
	 */
	public final void setTask_ReqPassFailTaskRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqPassFailTaskRoot task_reqpassfailtaskroot)
	{
		if (task_reqpassfailtaskroot == null) {
			getMendixObject().setValue(context, MemberNames.Task_ReqPassFailTaskRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_ReqPassFailTaskRoot.toString(), task_reqpassfailtaskroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_InputData
	 */
	public final excr_eprocedure_api.proxies.InputData getTask_InputData() throws com.mendix.core.CoreException
	{
		return getTask_InputData(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_InputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.InputData getTask_InputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.InputData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_InputData.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.InputData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_InputData
	 * @param task_inputdata
	 */
	public final void setTask_InputData(excr_eprocedure_api.proxies.InputData task_inputdata)
	{
		setTask_InputData(getContext(), task_inputdata);
	}

	/**
	 * Set value of Task_InputData
	 * @param context
	 * @param task_inputdata
	 */
	public final void setTask_InputData(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.InputData task_inputdata)
	{
		if (task_inputdata == null) {
			getMendixObject().setValue(context, MemberNames.Task_InputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_InputData.toString(), task_inputdata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_ReqContainerCollectDataRoot
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRoot getTask_ReqContainerCollectDataRoot() throws com.mendix.core.CoreException
	{
		return getTask_ReqContainerCollectDataRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_ReqContainerCollectDataRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.ReqContainerCollectDataRoot getTask_ReqContainerCollectDataRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.ReqContainerCollectDataRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_ReqContainerCollectDataRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.ReqContainerCollectDataRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_ReqContainerCollectDataRoot
	 * @param task_reqcontainercollectdataroot
	 */
	public final void setTask_ReqContainerCollectDataRoot(excr_eprocedure_api.proxies.ReqContainerCollectDataRoot task_reqcontainercollectdataroot)
	{
		setTask_ReqContainerCollectDataRoot(getContext(), task_reqcontainercollectdataroot);
	}

	/**
	 * Set value of Task_ReqContainerCollectDataRoot
	 * @param context
	 * @param task_reqcontainercollectdataroot
	 */
	public final void setTask_ReqContainerCollectDataRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.ReqContainerCollectDataRoot task_reqcontainercollectdataroot)
	{
		if (task_reqcontainercollectdataroot == null) {
			getMendixObject().setValue(context, MemberNames.Task_ReqContainerCollectDataRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_ReqContainerCollectDataRoot.toString(), task_reqcontainercollectdataroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_EprocDataCollecionDefRoot
	 */
	public final excr_eprocedure_api.proxies.EprocDataCollecionDefRoot getTask_EprocDataCollecionDefRoot() throws com.mendix.core.CoreException
	{
		return getTask_EprocDataCollecionDefRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_EprocDataCollecionDefRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.EprocDataCollecionDefRoot getTask_EprocDataCollecionDefRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.EprocDataCollecionDefRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_EprocDataCollecionDefRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.EprocDataCollecionDefRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_EprocDataCollecionDefRoot
	 * @param task_eprocdatacolleciondefroot
	 */
	public final void setTask_EprocDataCollecionDefRoot(excr_eprocedure_api.proxies.EprocDataCollecionDefRoot task_eprocdatacolleciondefroot)
	{
		setTask_EprocDataCollecionDefRoot(getContext(), task_eprocdatacolleciondefroot);
	}

	/**
	 * Set value of Task_EprocDataCollecionDefRoot
	 * @param context
	 * @param task_eprocdatacolleciondefroot
	 */
	public final void setTask_EprocDataCollecionDefRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.EprocDataCollecionDefRoot task_eprocdatacolleciondefroot)
	{
		if (task_eprocdatacolleciondefroot == null) {
			getMendixObject().setValue(context, MemberNames.Task_EprocDataCollecionDefRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_EprocDataCollecionDefRoot.toString(), task_eprocdatacolleciondefroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EprocDataCollectionDefParent_Task
	 */
	public final excr_eprocedure_api.proxies.EprocDataCollectionDefParent getEprocDataCollectionDefParent_Task() throws com.mendix.core.CoreException
	{
		return getEprocDataCollectionDefParent_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of EprocDataCollectionDefParent_Task
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.EprocDataCollectionDefParent getEprocDataCollectionDefParent_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.EprocDataCollectionDefParent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EprocDataCollectionDefParent_Task.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.EprocDataCollectionDefParent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EprocDataCollectionDefParent_Task
	 * @param eprocdatacollectiondefparent_task
	 */
	public final void setEprocDataCollectionDefParent_Task(excr_eprocedure_api.proxies.EprocDataCollectionDefParent eprocdatacollectiondefparent_task)
	{
		setEprocDataCollectionDefParent_Task(getContext(), eprocdatacollectiondefparent_task);
	}

	/**
	 * Set value of EprocDataCollectionDefParent_Task
	 * @param context
	 * @param eprocdatacollectiondefparent_task
	 */
	public final void setEprocDataCollectionDefParent_Task(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.EprocDataCollectionDefParent eprocdatacollectiondefparent_task)
	{
		if (eprocdatacollectiondefparent_task == null) {
			getMendixObject().setValue(context, MemberNames.EprocDataCollectionDefParent_Task.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EprocDataCollectionDefParent_Task.toString(), eprocdatacollectiondefparent_task.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_PauseTaskTimerRoot
	 */
	public final excr_eprocedure_api.proxies.PauseTaskTimerRoot getTask_PauseTaskTimerRoot() throws com.mendix.core.CoreException
	{
		return getTask_PauseTaskTimerRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_PauseTaskTimerRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.PauseTaskTimerRoot getTask_PauseTaskTimerRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.PauseTaskTimerRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_PauseTaskTimerRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.PauseTaskTimerRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_PauseTaskTimerRoot
	 * @param task_pausetasktimerroot
	 */
	public final void setTask_PauseTaskTimerRoot(excr_eprocedure_api.proxies.PauseTaskTimerRoot task_pausetasktimerroot)
	{
		setTask_PauseTaskTimerRoot(getContext(), task_pausetasktimerroot);
	}

	/**
	 * Set value of Task_PauseTaskTimerRoot
	 * @param context
	 * @param task_pausetasktimerroot
	 */
	public final void setTask_PauseTaskTimerRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.PauseTaskTimerRoot task_pausetasktimerroot)
	{
		if (task_pausetasktimerroot == null) {
			getMendixObject().setValue(context, MemberNames.Task_PauseTaskTimerRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_PauseTaskTimerRoot.toString(), task_pausetasktimerroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_OnlineQueryAPI
	 */
	public final excr_eprocedure_api.proxies.OnlineQueryAPI getTask_OnlineQueryAPI() throws com.mendix.core.CoreException
	{
		return getTask_OnlineQueryAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_OnlineQueryAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.OnlineQueryAPI getTask_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.OnlineQueryAPI result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_OnlineQueryAPI.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.OnlineQueryAPI.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_OnlineQueryAPI
	 * @param task_onlinequeryapi
	 */
	public final void setTask_OnlineQueryAPI(excr_eprocedure_api.proxies.OnlineQueryAPI task_onlinequeryapi)
	{
		setTask_OnlineQueryAPI(getContext(), task_onlinequeryapi);
	}

	/**
	 * Set value of Task_OnlineQueryAPI
	 * @param context
	 * @param task_onlinequeryapi
	 */
	public final void setTask_OnlineQueryAPI(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.OnlineQueryAPI task_onlinequeryapi)
	{
		if (task_onlinequeryapi == null) {
			getMendixObject().setValue(context, MemberNames.Task_OnlineQueryAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_OnlineQueryAPI.toString(), task_onlinequeryapi.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.Task that = (excr_eprocedure_api.proxies.Task) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
