// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure_api.proxies;

public class WorkstationJsonObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workstationJsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure_API.WorkstationJsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		IsFrozen("IsFrozen"),
		InstanceId("InstanceId"),
		Description("Description"),
		Availability("Availability"),
		WorkstationJsonObject_WorkstationRoot("EXCR_EProcedure_API.WorkstationJsonObject_WorkstationRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkstationJsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkstationJsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workstationJsonObjectMendixObject)
	{
		if (workstationJsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!workstationJsonObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workstationJsonObjectMendixObject = workstationJsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure_api.proxies.WorkstationJsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure_api.proxies.WorkstationJsonObject(context, mendixObject);
	}

	public static excr_eprocedure_api.proxies.WorkstationJsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure_api.proxies.WorkstationJsonObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen()
	{
		return getIsFrozen(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IsFrozen.toString());
	}

	/**
	 * Set value of IsFrozen
	 * @param isfrozen
	 */
	public final void setIsFrozen(java.lang.String isfrozen)
	{
		setIsFrozen(getContext(), isfrozen);
	}

	/**
	 * Set value of IsFrozen
	 * @param context
	 * @param isfrozen
	 */
	public final void setIsFrozen(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String isfrozen)
	{
		getMendixObject().setValue(context, MemberNames.IsFrozen.toString(), isfrozen);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Availability
	 */
	public final java.lang.String getAvailability()
	{
		return getAvailability(getContext());
	}

	/**
	 * @param context
	 * @return value of Availability
	 */
	public final java.lang.String getAvailability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Availability.toString());
	}

	/**
	 * Set value of Availability
	 * @param availability
	 */
	public final void setAvailability(java.lang.String availability)
	{
		setAvailability(getContext(), availability);
	}

	/**
	 * Set value of Availability
	 * @param context
	 * @param availability
	 */
	public final void setAvailability(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String availability)
	{
		getMendixObject().setValue(context, MemberNames.Availability.toString(), availability);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkstationJsonObject_WorkstationRoot
	 */
	public final excr_eprocedure_api.proxies.WorkstationRoot getWorkstationJsonObject_WorkstationRoot() throws com.mendix.core.CoreException
	{
		return getWorkstationJsonObject_WorkstationRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkstationJsonObject_WorkstationRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure_api.proxies.WorkstationRoot getWorkstationJsonObject_WorkstationRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure_api.proxies.WorkstationRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkstationJsonObject_WorkstationRoot.toString());
		if (identifier != null) {
			result = excr_eprocedure_api.proxies.WorkstationRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkstationJsonObject_WorkstationRoot
	 * @param workstationjsonobject_workstationroot
	 */
	public final void setWorkstationJsonObject_WorkstationRoot(excr_eprocedure_api.proxies.WorkstationRoot workstationjsonobject_workstationroot)
	{
		setWorkstationJsonObject_WorkstationRoot(getContext(), workstationjsonobject_workstationroot);
	}

	/**
	 * Set value of WorkstationJsonObject_WorkstationRoot
	 * @param context
	 * @param workstationjsonobject_workstationroot
	 */
	public final void setWorkstationJsonObject_WorkstationRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure_api.proxies.WorkstationRoot workstationjsonobject_workstationroot)
	{
		if (workstationjsonobject_workstationroot == null) {
			getMendixObject().setValue(context, MemberNames.WorkstationJsonObject_WorkstationRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkstationJsonObject_WorkstationRoot.toString(), workstationjsonobject_workstationroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workstationJsonObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure_api.proxies.WorkstationJsonObject that = (excr_eprocedure_api.proxies.WorkstationJsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
