// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_component.proxies;

public class Component implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject componentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Component.Component";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContainerId("ContainerId"),
		IssueActualHistoryId("IssueActualHistoryId"),
		ParentContainerId("ParentContainerId"),
		IssuedFrom("IssuedFrom"),
		ParentContainerName("ParentContainerName"),
		FromLot("FromLot"),
		FromStockPoint("FromStockPoint"),
		ContainerLevel("ContainerLevel"),
		Product("Product"),
		Description("Description"),
		QtyIssued("QtyIssued"),
		ReferenceDesignator("ReferenceDesignator"),
		HVIssueHistoryDetailId("HVIssueHistoryDetailId"),
		HVSetupDetailId("HVSetupDetailId"),
		MaterialListItemId("MaterialListItemId"),
		IssueKey("IssueKey"),
		KidCount("KidCount"),
		Index("Index"),
		_isChanged("_isChanged"),
		MermaidUID("MermaidUID"),
		_collapseChildren("_collapseChildren"),
		hasChildren("hasChildren"),
		selected("selected"),
		All("EXCR_Component.All"),
		RemovalCanidate_Chosen("EXCR_Component.RemovalCanidate_Chosen"),
		toParent("EXCR_Component.toParent"),
		Children("EXCR_Component.Children"),
		RemovalCandidate_MultiSelect("EXCR_Component.RemovalCandidate_MultiSelect");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Component(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Component(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject componentMendixObject)
	{
		if (componentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!componentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.componentMendixObject = componentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_component.proxies.Component initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_component.proxies.Component(context, mendixObject);
	}

	public static excr_component.proxies.Component load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_component.proxies.Component.initialize(context, mendixObject);
	}

	/**
	 * @return value of ContainerId
	 */
	public final java.lang.String getContainerId()
	{
		return getContainerId(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainerId
	 */
	public final java.lang.String getContainerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContainerId.toString());
	}

	/**
	 * Set value of ContainerId
	 * @param containerid
	 */
	public final void setContainerId(java.lang.String containerid)
	{
		setContainerId(getContext(), containerid);
	}

	/**
	 * Set value of ContainerId
	 * @param context
	 * @param containerid
	 */
	public final void setContainerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String containerid)
	{
		getMendixObject().setValue(context, MemberNames.ContainerId.toString(), containerid);
	}

	/**
	 * @return value of IssueActualHistoryId
	 */
	public final java.lang.String getIssueActualHistoryId()
	{
		return getIssueActualHistoryId(getContext());
	}

	/**
	 * @param context
	 * @return value of IssueActualHistoryId
	 */
	public final java.lang.String getIssueActualHistoryId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IssueActualHistoryId.toString());
	}

	/**
	 * Set value of IssueActualHistoryId
	 * @param issueactualhistoryid
	 */
	public final void setIssueActualHistoryId(java.lang.String issueactualhistoryid)
	{
		setIssueActualHistoryId(getContext(), issueactualhistoryid);
	}

	/**
	 * Set value of IssueActualHistoryId
	 * @param context
	 * @param issueactualhistoryid
	 */
	public final void setIssueActualHistoryId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issueactualhistoryid)
	{
		getMendixObject().setValue(context, MemberNames.IssueActualHistoryId.toString(), issueactualhistoryid);
	}

	/**
	 * @return value of ParentContainerId
	 */
	public final java.lang.String getParentContainerId()
	{
		return getParentContainerId(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentContainerId
	 */
	public final java.lang.String getParentContainerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentContainerId.toString());
	}

	/**
	 * Set value of ParentContainerId
	 * @param parentcontainerid
	 */
	public final void setParentContainerId(java.lang.String parentcontainerid)
	{
		setParentContainerId(getContext(), parentcontainerid);
	}

	/**
	 * Set value of ParentContainerId
	 * @param context
	 * @param parentcontainerid
	 */
	public final void setParentContainerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentcontainerid)
	{
		getMendixObject().setValue(context, MemberNames.ParentContainerId.toString(), parentcontainerid);
	}

	/**
	 * @return value of IssuedFrom
	 */
	public final java.lang.String getIssuedFrom()
	{
		return getIssuedFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of IssuedFrom
	 */
	public final java.lang.String getIssuedFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IssuedFrom.toString());
	}

	/**
	 * Set value of IssuedFrom
	 * @param issuedfrom
	 */
	public final void setIssuedFrom(java.lang.String issuedfrom)
	{
		setIssuedFrom(getContext(), issuedfrom);
	}

	/**
	 * Set value of IssuedFrom
	 * @param context
	 * @param issuedfrom
	 */
	public final void setIssuedFrom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issuedfrom)
	{
		getMendixObject().setValue(context, MemberNames.IssuedFrom.toString(), issuedfrom);
	}

	/**
	 * @return value of ParentContainerName
	 */
	public final java.lang.String getParentContainerName()
	{
		return getParentContainerName(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentContainerName
	 */
	public final java.lang.String getParentContainerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentContainerName.toString());
	}

	/**
	 * Set value of ParentContainerName
	 * @param parentcontainername
	 */
	public final void setParentContainerName(java.lang.String parentcontainername)
	{
		setParentContainerName(getContext(), parentcontainername);
	}

	/**
	 * Set value of ParentContainerName
	 * @param context
	 * @param parentcontainername
	 */
	public final void setParentContainerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentcontainername)
	{
		getMendixObject().setValue(context, MemberNames.ParentContainerName.toString(), parentcontainername);
	}

	/**
	 * @return value of FromLot
	 */
	public final java.lang.String getFromLot()
	{
		return getFromLot(getContext());
	}

	/**
	 * @param context
	 * @return value of FromLot
	 */
	public final java.lang.String getFromLot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FromLot.toString());
	}

	/**
	 * Set value of FromLot
	 * @param fromlot
	 */
	public final void setFromLot(java.lang.String fromlot)
	{
		setFromLot(getContext(), fromlot);
	}

	/**
	 * Set value of FromLot
	 * @param context
	 * @param fromlot
	 */
	public final void setFromLot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fromlot)
	{
		getMendixObject().setValue(context, MemberNames.FromLot.toString(), fromlot);
	}

	/**
	 * @return value of FromStockPoint
	 */
	public final java.lang.String getFromStockPoint()
	{
		return getFromStockPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of FromStockPoint
	 */
	public final java.lang.String getFromStockPoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FromStockPoint.toString());
	}

	/**
	 * Set value of FromStockPoint
	 * @param fromstockpoint
	 */
	public final void setFromStockPoint(java.lang.String fromstockpoint)
	{
		setFromStockPoint(getContext(), fromstockpoint);
	}

	/**
	 * Set value of FromStockPoint
	 * @param context
	 * @param fromstockpoint
	 */
	public final void setFromStockPoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fromstockpoint)
	{
		getMendixObject().setValue(context, MemberNames.FromStockPoint.toString(), fromstockpoint);
	}

	/**
	 * @return value of ContainerLevel
	 */
	public final java.lang.String getContainerLevel()
	{
		return getContainerLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainerLevel
	 */
	public final java.lang.String getContainerLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContainerLevel.toString());
	}

	/**
	 * Set value of ContainerLevel
	 * @param containerlevel
	 */
	public final void setContainerLevel(java.lang.String containerlevel)
	{
		setContainerLevel(getContext(), containerlevel);
	}

	/**
	 * Set value of ContainerLevel
	 * @param context
	 * @param containerlevel
	 */
	public final void setContainerLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String containerlevel)
	{
		getMendixObject().setValue(context, MemberNames.ContainerLevel.toString(), containerlevel);
	}

	/**
	 * @return value of Product
	 */
	public final java.lang.String getProduct()
	{
		return getProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of Product
	 */
	public final java.lang.String getProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Product.toString());
	}

	/**
	 * Set value of Product
	 * @param product
	 */
	public final void setProduct(java.lang.String product)
	{
		setProduct(getContext(), product);
	}

	/**
	 * Set value of Product
	 * @param context
	 * @param product
	 */
	public final void setProduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product)
	{
		getMendixObject().setValue(context, MemberNames.Product.toString(), product);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of QtyIssued
	 */
	public final java.lang.String getQtyIssued()
	{
		return getQtyIssued(getContext());
	}

	/**
	 * @param context
	 * @return value of QtyIssued
	 */
	public final java.lang.String getQtyIssued(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QtyIssued.toString());
	}

	/**
	 * Set value of QtyIssued
	 * @param qtyissued
	 */
	public final void setQtyIssued(java.lang.String qtyissued)
	{
		setQtyIssued(getContext(), qtyissued);
	}

	/**
	 * Set value of QtyIssued
	 * @param context
	 * @param qtyissued
	 */
	public final void setQtyIssued(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String qtyissued)
	{
		getMendixObject().setValue(context, MemberNames.QtyIssued.toString(), qtyissued);
	}

	/**
	 * @return value of ReferenceDesignator
	 */
	public final java.lang.String getReferenceDesignator()
	{
		return getReferenceDesignator(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceDesignator
	 */
	public final java.lang.String getReferenceDesignator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReferenceDesignator.toString());
	}

	/**
	 * Set value of ReferenceDesignator
	 * @param referencedesignator
	 */
	public final void setReferenceDesignator(java.lang.String referencedesignator)
	{
		setReferenceDesignator(getContext(), referencedesignator);
	}

	/**
	 * Set value of ReferenceDesignator
	 * @param context
	 * @param referencedesignator
	 */
	public final void setReferenceDesignator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String referencedesignator)
	{
		getMendixObject().setValue(context, MemberNames.ReferenceDesignator.toString(), referencedesignator);
	}

	/**
	 * @return value of HVIssueHistoryDetailId
	 */
	public final java.lang.String getHVIssueHistoryDetailId()
	{
		return getHVIssueHistoryDetailId(getContext());
	}

	/**
	 * @param context
	 * @return value of HVIssueHistoryDetailId
	 */
	public final java.lang.String getHVIssueHistoryDetailId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HVIssueHistoryDetailId.toString());
	}

	/**
	 * Set value of HVIssueHistoryDetailId
	 * @param hvissuehistorydetailid
	 */
	public final void setHVIssueHistoryDetailId(java.lang.String hvissuehistorydetailid)
	{
		setHVIssueHistoryDetailId(getContext(), hvissuehistorydetailid);
	}

	/**
	 * Set value of HVIssueHistoryDetailId
	 * @param context
	 * @param hvissuehistorydetailid
	 */
	public final void setHVIssueHistoryDetailId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hvissuehistorydetailid)
	{
		getMendixObject().setValue(context, MemberNames.HVIssueHistoryDetailId.toString(), hvissuehistorydetailid);
	}

	/**
	 * @return value of HVSetupDetailId
	 */
	public final java.lang.String getHVSetupDetailId()
	{
		return getHVSetupDetailId(getContext());
	}

	/**
	 * @param context
	 * @return value of HVSetupDetailId
	 */
	public final java.lang.String getHVSetupDetailId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HVSetupDetailId.toString());
	}

	/**
	 * Set value of HVSetupDetailId
	 * @param hvsetupdetailid
	 */
	public final void setHVSetupDetailId(java.lang.String hvsetupdetailid)
	{
		setHVSetupDetailId(getContext(), hvsetupdetailid);
	}

	/**
	 * Set value of HVSetupDetailId
	 * @param context
	 * @param hvsetupdetailid
	 */
	public final void setHVSetupDetailId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hvsetupdetailid)
	{
		getMendixObject().setValue(context, MemberNames.HVSetupDetailId.toString(), hvsetupdetailid);
	}

	/**
	 * @return value of MaterialListItemId
	 */
	public final java.lang.String getMaterialListItemId()
	{
		return getMaterialListItemId(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialListItemId
	 */
	public final java.lang.String getMaterialListItemId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialListItemId.toString());
	}

	/**
	 * Set value of MaterialListItemId
	 * @param materiallistitemid
	 */
	public final void setMaterialListItemId(java.lang.String materiallistitemid)
	{
		setMaterialListItemId(getContext(), materiallistitemid);
	}

	/**
	 * Set value of MaterialListItemId
	 * @param context
	 * @param materiallistitemid
	 */
	public final void setMaterialListItemId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materiallistitemid)
	{
		getMendixObject().setValue(context, MemberNames.MaterialListItemId.toString(), materiallistitemid);
	}

	/**
	 * @return value of IssueKey
	 */
	public final java.lang.String getIssueKey()
	{
		return getIssueKey(getContext());
	}

	/**
	 * @param context
	 * @return value of IssueKey
	 */
	public final java.lang.String getIssueKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IssueKey.toString());
	}

	/**
	 * Set value of IssueKey
	 * @param issuekey
	 */
	public final void setIssueKey(java.lang.String issuekey)
	{
		setIssueKey(getContext(), issuekey);
	}

	/**
	 * Set value of IssueKey
	 * @param context
	 * @param issuekey
	 */
	public final void setIssueKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issuekey)
	{
		getMendixObject().setValue(context, MemberNames.IssueKey.toString(), issuekey);
	}

	/**
	 * @return value of KidCount
	 */
	public final java.lang.Integer getKidCount()
	{
		return getKidCount(getContext());
	}

	/**
	 * @param context
	 * @return value of KidCount
	 */
	public final java.lang.Integer getKidCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.KidCount.toString());
	}

	/**
	 * Set value of KidCount
	 * @param kidcount
	 */
	public final void setKidCount(java.lang.Integer kidcount)
	{
		setKidCount(getContext(), kidcount);
	}

	/**
	 * Set value of KidCount
	 * @param context
	 * @param kidcount
	 */
	public final void setKidCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer kidcount)
	{
		getMendixObject().setValue(context, MemberNames.KidCount.toString(), kidcount);
	}

	/**
	 * @return value of Index
	 */
	public final java.lang.Integer getIndex()
	{
		return getIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of Index
	 */
	public final java.lang.Integer getIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Index.toString());
	}

	/**
	 * Set value of Index
	 * @param index
	 */
	public final void setIndex(java.lang.Integer index)
	{
		setIndex(getContext(), index);
	}

	/**
	 * Set value of Index
	 * @param context
	 * @param index
	 */
	public final void setIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer index)
	{
		getMendixObject().setValue(context, MemberNames.Index.toString(), index);
	}

	/**
	 * @return value of _isChanged
	 */
	public final java.lang.Boolean get_isChanged()
	{
		return get_isChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of _isChanged
	 */
	public final java.lang.Boolean get_isChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._isChanged.toString());
	}

	/**
	 * Set value of _isChanged
	 * @param _ischanged
	 */
	public final void set_isChanged(java.lang.Boolean _ischanged)
	{
		set_isChanged(getContext(), _ischanged);
	}

	/**
	 * Set value of _isChanged
	 * @param context
	 * @param _ischanged
	 */
	public final void set_isChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _ischanged)
	{
		getMendixObject().setValue(context, MemberNames._isChanged.toString(), _ischanged);
	}

	/**
	 * @return value of MermaidUID
	 */
	public final java.lang.String getMermaidUID()
	{
		return getMermaidUID(getContext());
	}

	/**
	 * @param context
	 * @return value of MermaidUID
	 */
	public final java.lang.String getMermaidUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MermaidUID.toString());
	}

	/**
	 * Set value of MermaidUID
	 * @param mermaiduid
	 */
	public final void setMermaidUID(java.lang.String mermaiduid)
	{
		setMermaidUID(getContext(), mermaiduid);
	}

	/**
	 * Set value of MermaidUID
	 * @param context
	 * @param mermaiduid
	 */
	public final void setMermaidUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mermaiduid)
	{
		getMendixObject().setValue(context, MemberNames.MermaidUID.toString(), mermaiduid);
	}

	/**
	 * @return value of _collapseChildren
	 */
	public final java.lang.Boolean get_collapseChildren()
	{
		return get_collapseChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of _collapseChildren
	 */
	public final java.lang.Boolean get_collapseChildren(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._collapseChildren.toString());
	}

	/**
	 * Set value of _collapseChildren
	 * @param _collapsechildren
	 */
	public final void set_collapseChildren(java.lang.Boolean _collapsechildren)
	{
		set_collapseChildren(getContext(), _collapsechildren);
	}

	/**
	 * Set value of _collapseChildren
	 * @param context
	 * @param _collapsechildren
	 */
	public final void set_collapseChildren(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _collapsechildren)
	{
		getMendixObject().setValue(context, MemberNames._collapseChildren.toString(), _collapsechildren);
	}

	/**
	 * @return value of hasChildren
	 */
	public final java.lang.Boolean gethasChildren()
	{
		return gethasChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of hasChildren
	 */
	public final java.lang.Boolean gethasChildren(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.hasChildren.toString());
	}

	/**
	 * Set value of hasChildren
	 * @param haschildren
	 */
	public final void sethasChildren(java.lang.Boolean haschildren)
	{
		sethasChildren(getContext(), haschildren);
	}

	/**
	 * Set value of hasChildren
	 * @param context
	 * @param haschildren
	 */
	public final void sethasChildren(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haschildren)
	{
		getMendixObject().setValue(context, MemberNames.hasChildren.toString(), haschildren);
	}

	/**
	 * @return value of selected
	 */
	public final java.lang.Boolean getselected()
	{
		return getselected(getContext());
	}

	/**
	 * @param context
	 * @return value of selected
	 */
	public final java.lang.Boolean getselected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.selected.toString());
	}

	/**
	 * Set value of selected
	 * @param selected
	 */
	public final void setselected(java.lang.Boolean selected)
	{
		setselected(getContext(), selected);
	}

	/**
	 * Set value of selected
	 * @param context
	 * @param selected
	 */
	public final void setselected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selected)
	{
		getMendixObject().setValue(context, MemberNames.selected.toString(), selected);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of All
	 */
	public final excr_component.proxies.ComponentTxnContext getAll() throws com.mendix.core.CoreException
	{
		return getAll(getContext());
	}

	/**
	 * @param context
	 * @return value of All
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_component.proxies.ComponentTxnContext getAll(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_component.proxies.ComponentTxnContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.All.toString());
		if (identifier != null) {
			result = excr_component.proxies.ComponentTxnContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of All
	 * @param all
	 */
	public final void setAll(excr_component.proxies.ComponentTxnContext all)
	{
		setAll(getContext(), all);
	}

	/**
	 * Set value of All
	 * @param context
	 * @param all
	 */
	public final void setAll(com.mendix.systemwideinterfaces.core.IContext context, excr_component.proxies.ComponentTxnContext all)
	{
		if (all == null) {
			getMendixObject().setValue(context, MemberNames.All.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.All.toString(), all.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RemovalCanidate_Chosen
	 */
	public final excr_component.proxies.ComponentTxnContext getRemovalCanidate_Chosen() throws com.mendix.core.CoreException
	{
		return getRemovalCanidate_Chosen(getContext());
	}

	/**
	 * @param context
	 * @return value of RemovalCanidate_Chosen
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_component.proxies.ComponentTxnContext getRemovalCanidate_Chosen(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_component.proxies.ComponentTxnContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RemovalCanidate_Chosen.toString());
		if (identifier != null) {
			result = excr_component.proxies.ComponentTxnContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RemovalCanidate_Chosen
	 * @param removalcanidate_chosen
	 */
	public final void setRemovalCanidate_Chosen(excr_component.proxies.ComponentTxnContext removalcanidate_chosen)
	{
		setRemovalCanidate_Chosen(getContext(), removalcanidate_chosen);
	}

	/**
	 * Set value of RemovalCanidate_Chosen
	 * @param context
	 * @param removalcanidate_chosen
	 */
	public final void setRemovalCanidate_Chosen(com.mendix.systemwideinterfaces.core.IContext context, excr_component.proxies.ComponentTxnContext removalcanidate_chosen)
	{
		if (removalcanidate_chosen == null) {
			getMendixObject().setValue(context, MemberNames.RemovalCanidate_Chosen.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RemovalCanidate_Chosen.toString(), removalcanidate_chosen.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of toParent
	 */
	public final excr_component.proxies.ComponentTxnContext gettoParent() throws com.mendix.core.CoreException
	{
		return gettoParent(getContext());
	}

	/**
	 * @param context
	 * @return value of toParent
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_component.proxies.ComponentTxnContext gettoParent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_component.proxies.ComponentTxnContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.toParent.toString());
		if (identifier != null) {
			result = excr_component.proxies.ComponentTxnContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of toParent
	 * @param toparent
	 */
	public final void settoParent(excr_component.proxies.ComponentTxnContext toparent)
	{
		settoParent(getContext(), toparent);
	}

	/**
	 * Set value of toParent
	 * @param context
	 * @param toparent
	 */
	public final void settoParent(com.mendix.systemwideinterfaces.core.IContext context, excr_component.proxies.ComponentTxnContext toparent)
	{
		if (toparent == null) {
			getMendixObject().setValue(context, MemberNames.toParent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.toParent.toString(), toparent.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Children
	 */
	public final excr_component.proxies.Component getChildren() throws com.mendix.core.CoreException
	{
		return getChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of Children
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_component.proxies.Component getChildren(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_component.proxies.Component result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Children.toString());
		if (identifier != null) {
			result = excr_component.proxies.Component.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Children
	 * @param children
	 */
	public final void setChildren(excr_component.proxies.Component children)
	{
		setChildren(getContext(), children);
	}

	/**
	 * Set value of Children
	 * @param context
	 * @param children
	 */
	public final void setChildren(com.mendix.systemwideinterfaces.core.IContext context, excr_component.proxies.Component children)
	{
		if (children == null) {
			getMendixObject().setValue(context, MemberNames.Children.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Children.toString(), children.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RemovalCandidate_MultiSelect
	 */
	public final java.util.List<excr_component.proxies.ComponentTxnContext> getRemovalCandidate_MultiSelect() throws com.mendix.core.CoreException
	{
		return getRemovalCandidate_MultiSelect(getContext());
	}

	/**
	 * @param context
	 * @return value of RemovalCandidate_MultiSelect
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<excr_component.proxies.ComponentTxnContext> getRemovalCandidate_MultiSelect(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<excr_component.proxies.ComponentTxnContext> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.RemovalCandidate_MultiSelect.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(excr_component.proxies.ComponentTxnContext.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of RemovalCandidate_MultiSelect
	 * @param removalcandidate_multiselect
	 */
	public final void setRemovalCandidate_MultiSelect(java.util.List<excr_component.proxies.ComponentTxnContext> removalcandidate_multiselect)
	{
		setRemovalCandidate_MultiSelect(getContext(), removalcandidate_multiselect);
	}

	/**
	 * Set value of RemovalCandidate_MultiSelect
	 * @param context
	 * @param removalcandidate_multiselect
	 */
	public final void setRemovalCandidate_MultiSelect(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<excr_component.proxies.ComponentTxnContext> removalcandidate_multiselect)
	{
		var identifiers = removalcandidate_multiselect
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.RemovalCandidate_MultiSelect.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return componentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_component.proxies.Component that = (excr_component.proxies.Component) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
