// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_component.proxies;

public class IssueActualHistory implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject issueActualHistoryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Component.IssueActualHistory";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceId("InstanceId"),
		CDOTypeName("CDOTypeName"),
		IssueActualHistory_ServiceDetail("EXCR_Component.IssueActualHistory_ServiceDetail"),
		Parent_2_IssueActualHistory("EXCR_Component.Parent_2_IssueActualHistory");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IssueActualHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected IssueActualHistory(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject issueActualHistoryMendixObject)
	{
		if (issueActualHistoryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!issueActualHistoryMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.issueActualHistoryMendixObject = issueActualHistoryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_component.proxies.IssueActualHistory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_component.proxies.IssueActualHistory(context, mendixObject);
	}

	public static excr_component.proxies.IssueActualHistory load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_component.proxies.IssueActualHistory.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName()
	{
		return getCDOTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CDOTypeName.toString());
	}

	/**
	 * Set value of CDOTypeName
	 * @param cdotypename
	 */
	public final void setCDOTypeName(java.lang.String cdotypename)
	{
		setCDOTypeName(getContext(), cdotypename);
	}

	/**
	 * Set value of CDOTypeName
	 * @param context
	 * @param cdotypename
	 */
	public final void setCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cdotypename)
	{
		getMendixObject().setValue(context, MemberNames.CDOTypeName.toString(), cdotypename);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IssueActualHistory_ServiceDetail
	 */
	public final excr_component.proxies.ServiceDetail getIssueActualHistory_ServiceDetail() throws com.mendix.core.CoreException
	{
		return getIssueActualHistory_ServiceDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of IssueActualHistory_ServiceDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_component.proxies.ServiceDetail getIssueActualHistory_ServiceDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_component.proxies.ServiceDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IssueActualHistory_ServiceDetail.toString());
		if (identifier != null) {
			result = excr_component.proxies.ServiceDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IssueActualHistory_ServiceDetail
	 * @param issueactualhistory_servicedetail
	 */
	public final void setIssueActualHistory_ServiceDetail(excr_component.proxies.ServiceDetail issueactualhistory_servicedetail)
	{
		setIssueActualHistory_ServiceDetail(getContext(), issueactualhistory_servicedetail);
	}

	/**
	 * Set value of IssueActualHistory_ServiceDetail
	 * @param context
	 * @param issueactualhistory_servicedetail
	 */
	public final void setIssueActualHistory_ServiceDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_component.proxies.ServiceDetail issueactualhistory_servicedetail)
	{
		if (issueactualhistory_servicedetail == null) {
			getMendixObject().setValue(context, MemberNames.IssueActualHistory_ServiceDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IssueActualHistory_ServiceDetail.toString(), issueactualhistory_servicedetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_2_IssueActualHistory
	 */
	public final excr_component.proxies.Parent_2 getParent_2_IssueActualHistory() throws com.mendix.core.CoreException
	{
		return getParent_2_IssueActualHistory(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_2_IssueActualHistory
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_component.proxies.Parent_2 getParent_2_IssueActualHistory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_component.proxies.Parent_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_2_IssueActualHistory.toString());
		if (identifier != null) {
			result = excr_component.proxies.Parent_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_2_IssueActualHistory
	 * @param parent_2_issueactualhistory
	 */
	public final void setParent_2_IssueActualHistory(excr_component.proxies.Parent_2 parent_2_issueactualhistory)
	{
		setParent_2_IssueActualHistory(getContext(), parent_2_issueactualhistory);
	}

	/**
	 * Set value of Parent_2_IssueActualHistory
	 * @param context
	 * @param parent_2_issueactualhistory
	 */
	public final void setParent_2_IssueActualHistory(com.mendix.systemwideinterfaces.core.IContext context, excr_component.proxies.Parent_2 parent_2_issueactualhistory)
	{
		if (parent_2_issueactualhistory == null) {
			getMendixObject().setValue(context, MemberNames.Parent_2_IssueActualHistory.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_2_IssueActualHistory.toString(), parent_2_issueactualhistory.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return issueActualHistoryMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_component.proxies.IssueActualHistory that = (excr_component.proxies.IssueActualHistory) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
