// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_operatorlog.proxies;

public class LogEntries implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject logEntriesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_OperatorLog.LogEntries";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceID("InstanceID"),
		OperatorLogName("OperatorLogName"),
		TxnDateTime("TxnDateTime"),
		Employee("Employee"),
		LogEntry("LogEntry"),
		LogType("LogType"),
		NewLogEntry("EXCR_OperatorLog.NewLogEntry");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LogEntries(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected LogEntries(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject logEntriesMendixObject)
	{
		if (logEntriesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!logEntriesMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.logEntriesMendixObject = logEntriesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_operatorlog.proxies.LogEntries initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_operatorlog.proxies.LogEntries(context, mendixObject);
	}

	public static excr_operatorlog.proxies.LogEntries load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_operatorlog.proxies.LogEntries.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID()
	{
		return getInstanceID(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceID.toString());
	}

	/**
	 * Set value of InstanceID
	 * @param instanceid
	 */
	public final void setInstanceID(java.lang.String instanceid)
	{
		setInstanceID(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceID
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceID.toString(), instanceid);
	}

	/**
	 * @return value of OperatorLogName
	 */
	public final java.lang.String getOperatorLogName()
	{
		return getOperatorLogName(getContext());
	}

	/**
	 * @param context
	 * @return value of OperatorLogName
	 */
	public final java.lang.String getOperatorLogName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OperatorLogName.toString());
	}

	/**
	 * Set value of OperatorLogName
	 * @param operatorlogname
	 */
	public final void setOperatorLogName(java.lang.String operatorlogname)
	{
		setOperatorLogName(getContext(), operatorlogname);
	}

	/**
	 * Set value of OperatorLogName
	 * @param context
	 * @param operatorlogname
	 */
	public final void setOperatorLogName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operatorlogname)
	{
		getMendixObject().setValue(context, MemberNames.OperatorLogName.toString(), operatorlogname);
	}

	/**
	 * @return value of TxnDateTime
	 */
	public final java.util.Date getTxnDateTime()
	{
		return getTxnDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of TxnDateTime
	 */
	public final java.util.Date getTxnDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TxnDateTime.toString());
	}

	/**
	 * Set value of TxnDateTime
	 * @param txndatetime
	 */
	public final void setTxnDateTime(java.util.Date txndatetime)
	{
		setTxnDateTime(getContext(), txndatetime);
	}

	/**
	 * Set value of TxnDateTime
	 * @param context
	 * @param txndatetime
	 */
	public final void setTxnDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date txndatetime)
	{
		getMendixObject().setValue(context, MemberNames.TxnDateTime.toString(), txndatetime);
	}

	/**
	 * @return value of Employee
	 */
	public final java.lang.String getEmployee()
	{
		return getEmployee(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee
	 */
	public final java.lang.String getEmployee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Employee.toString());
	}

	/**
	 * Set value of Employee
	 * @param employee
	 */
	public final void setEmployee(java.lang.String employee)
	{
		setEmployee(getContext(), employee);
	}

	/**
	 * Set value of Employee
	 * @param context
	 * @param employee
	 */
	public final void setEmployee(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employee)
	{
		getMendixObject().setValue(context, MemberNames.Employee.toString(), employee);
	}

	/**
	 * @return value of LogEntry
	 */
	public final java.lang.String getLogEntry()
	{
		return getLogEntry(getContext());
	}

	/**
	 * @param context
	 * @return value of LogEntry
	 */
	public final java.lang.String getLogEntry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LogEntry.toString());
	}

	/**
	 * Set value of LogEntry
	 * @param logentry
	 */
	public final void setLogEntry(java.lang.String logentry)
	{
		setLogEntry(getContext(), logentry);
	}

	/**
	 * Set value of LogEntry
	 * @param context
	 * @param logentry
	 */
	public final void setLogEntry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String logentry)
	{
		getMendixObject().setValue(context, MemberNames.LogEntry.toString(), logentry);
	}

	/**
	 * @return value of LogType
	 */
	public final java.lang.String getLogType()
	{
		return getLogType(getContext());
	}

	/**
	 * @param context
	 * @return value of LogType
	 */
	public final java.lang.String getLogType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LogType.toString());
	}

	/**
	 * Set value of LogType
	 * @param logtype
	 */
	public final void setLogType(java.lang.String logtype)
	{
		setLogType(getContext(), logtype);
	}

	/**
	 * Set value of LogType
	 * @param context
	 * @param logtype
	 */
	public final void setLogType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String logtype)
	{
		getMendixObject().setValue(context, MemberNames.LogType.toString(), logtype);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NewLogEntry
	 */
	public final excr_operatorlog.proxies.OperatorLog_Context getNewLogEntry() throws com.mendix.core.CoreException
	{
		return getNewLogEntry(getContext());
	}

	/**
	 * @param context
	 * @return value of NewLogEntry
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_operatorlog.proxies.OperatorLog_Context getNewLogEntry(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_operatorlog.proxies.OperatorLog_Context result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NewLogEntry.toString());
		if (identifier != null) {
			result = excr_operatorlog.proxies.OperatorLog_Context.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NewLogEntry
	 * @param newlogentry
	 */
	public final void setNewLogEntry(excr_operatorlog.proxies.OperatorLog_Context newlogentry)
	{
		setNewLogEntry(getContext(), newlogentry);
	}

	/**
	 * Set value of NewLogEntry
	 * @param context
	 * @param newlogentry
	 */
	public final void setNewLogEntry(com.mendix.systemwideinterfaces.core.IContext context, excr_operatorlog.proxies.OperatorLog_Context newlogentry)
	{
		if (newlogentry == null) {
			getMendixObject().setValue(context, MemberNames.NewLogEntry.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NewLogEntry.toString(), newlogentry.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return logEntriesMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_operatorlog.proxies.LogEntries that = (excr_operatorlog.proxies.LogEntries) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
