// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_operatorlog.proxies;

public class LogType implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject logTypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_OperatorLog.LogType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		InstanceID("InstanceID"),
		IsFrozen("IsFrozen"),
		Description("Description"),
		LogType_OperatorLog_Context("EXCR_OperatorLog.LogType_OperatorLog_Context");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LogType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected LogType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject logTypeMendixObject)
	{
		if (logTypeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!logTypeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.logTypeMendixObject = logTypeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_operatorlog.proxies.LogType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_operatorlog.proxies.LogType(context, mendixObject);
	}

	public static excr_operatorlog.proxies.LogType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_operatorlog.proxies.LogType.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID()
	{
		return getInstanceID(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceID.toString());
	}

	/**
	 * Set value of InstanceID
	 * @param instanceid
	 */
	public final void setInstanceID(java.lang.String instanceid)
	{
		setInstanceID(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceID
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceID.toString(), instanceid);
	}

	/**
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen()
	{
		return getIsFrozen(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFrozen
	 */
	public final java.lang.String getIsFrozen(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IsFrozen.toString());
	}

	/**
	 * Set value of IsFrozen
	 * @param isfrozen
	 */
	public final void setIsFrozen(java.lang.String isfrozen)
	{
		setIsFrozen(getContext(), isfrozen);
	}

	/**
	 * Set value of IsFrozen
	 * @param context
	 * @param isfrozen
	 */
	public final void setIsFrozen(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String isfrozen)
	{
		getMendixObject().setValue(context, MemberNames.IsFrozen.toString(), isfrozen);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LogType_OperatorLog_Context
	 */
	public final excr_operatorlog.proxies.OperatorLog_Context getLogType_OperatorLog_Context() throws com.mendix.core.CoreException
	{
		return getLogType_OperatorLog_Context(getContext());
	}

	/**
	 * @param context
	 * @return value of LogType_OperatorLog_Context
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_operatorlog.proxies.OperatorLog_Context getLogType_OperatorLog_Context(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_operatorlog.proxies.OperatorLog_Context result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LogType_OperatorLog_Context.toString());
		if (identifier != null) {
			result = excr_operatorlog.proxies.OperatorLog_Context.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LogType_OperatorLog_Context
	 * @param logtype_operatorlog_context
	 */
	public final void setLogType_OperatorLog_Context(excr_operatorlog.proxies.OperatorLog_Context logtype_operatorlog_context)
	{
		setLogType_OperatorLog_Context(getContext(), logtype_operatorlog_context);
	}

	/**
	 * Set value of LogType_OperatorLog_Context
	 * @param context
	 * @param logtype_operatorlog_context
	 */
	public final void setLogType_OperatorLog_Context(com.mendix.systemwideinterfaces.core.IContext context, excr_operatorlog.proxies.OperatorLog_Context logtype_operatorlog_context)
	{
		if (logtype_operatorlog_context == null) {
			getMendixObject().setValue(context, MemberNames.LogType_OperatorLog_Context.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LogType_OperatorLog_Context.toString(), logtype_operatorlog_context.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return logTypeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_operatorlog.proxies.LogType that = (excr_operatorlog.proxies.LogType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
