// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_holdmanagement.proxies;

public class ContainerHoldGridContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject containerHoldGridContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_HoldManagement.ContainerHoldGridContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Selection("Selection"),
		ContainerName("ContainerName"),
		ProductName("ProductName"),
		ProductRevision("ProductRevision"),
		MfgOrderName("MfgOrderName"),
		Qty("Qty"),
		UOM("UOM"),
		HoldReason("HoldReason"),
		HoldMessage("HoldMessage"),
		OnHoldDate("OnHoldDate"),
		ContainerHoldGridContext_HoldManagementPageContext("EXCR_HoldManagement.ContainerHoldGridContext_HoldManagementPageContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ContainerHoldGridContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ContainerHoldGridContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject containerHoldGridContextMendixObject)
	{
		if (containerHoldGridContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!containerHoldGridContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.containerHoldGridContextMendixObject = containerHoldGridContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_holdmanagement.proxies.ContainerHoldGridContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_holdmanagement.proxies.ContainerHoldGridContext(context, mendixObject);
	}

	public static excr_holdmanagement.proxies.ContainerHoldGridContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_holdmanagement.proxies.ContainerHoldGridContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of Selection
	 */
	public final java.lang.Boolean getSelection()
	{
		return getSelection(getContext());
	}

	/**
	 * @param context
	 * @return value of Selection
	 */
	public final java.lang.Boolean getSelection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Selection.toString());
	}

	/**
	 * Set value of Selection
	 * @param selection
	 */
	public final void setSelection(java.lang.Boolean selection)
	{
		setSelection(getContext(), selection);
	}

	/**
	 * Set value of Selection
	 * @param context
	 * @param selection
	 */
	public final void setSelection(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selection)
	{
		getMendixObject().setValue(context, MemberNames.Selection.toString(), selection);
	}

	/**
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName()
	{
		return getContainerName(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContainerName.toString());
	}

	/**
	 * Set value of ContainerName
	 * @param containername
	 */
	public final void setContainerName(java.lang.String containername)
	{
		setContainerName(getContext(), containername);
	}

	/**
	 * Set value of ContainerName
	 * @param context
	 * @param containername
	 */
	public final void setContainerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String containername)
	{
		getMendixObject().setValue(context, MemberNames.ContainerName.toString(), containername);
	}

	/**
	 * @return value of ProductName
	 */
	public final java.lang.String getProductName()
	{
		return getProductName(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductName
	 */
	public final java.lang.String getProductName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductName.toString());
	}

	/**
	 * Set value of ProductName
	 * @param productname
	 */
	public final void setProductName(java.lang.String productname)
	{
		setProductName(getContext(), productname);
	}

	/**
	 * Set value of ProductName
	 * @param context
	 * @param productname
	 */
	public final void setProductName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productname)
	{
		getMendixObject().setValue(context, MemberNames.ProductName.toString(), productname);
	}

	/**
	 * @return value of ProductRevision
	 */
	public final java.lang.String getProductRevision()
	{
		return getProductRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductRevision
	 */
	public final java.lang.String getProductRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductRevision.toString());
	}

	/**
	 * Set value of ProductRevision
	 * @param productrevision
	 */
	public final void setProductRevision(java.lang.String productrevision)
	{
		setProductRevision(getContext(), productrevision);
	}

	/**
	 * Set value of ProductRevision
	 * @param context
	 * @param productrevision
	 */
	public final void setProductRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productrevision)
	{
		getMendixObject().setValue(context, MemberNames.ProductRevision.toString(), productrevision);
	}

	/**
	 * @return value of MfgOrderName
	 */
	public final java.lang.String getMfgOrderName()
	{
		return getMfgOrderName(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrderName
	 */
	public final java.lang.String getMfgOrderName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MfgOrderName.toString());
	}

	/**
	 * Set value of MfgOrderName
	 * @param mfgordername
	 */
	public final void setMfgOrderName(java.lang.String mfgordername)
	{
		setMfgOrderName(getContext(), mfgordername);
	}

	/**
	 * Set value of MfgOrderName
	 * @param context
	 * @param mfgordername
	 */
	public final void setMfgOrderName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfgordername)
	{
		getMendixObject().setValue(context, MemberNames.MfgOrderName.toString(), mfgordername);
	}

	/**
	 * @return value of Qty
	 */
	public final java.lang.String getQty()
	{
		return getQty(getContext());
	}

	/**
	 * @param context
	 * @return value of Qty
	 */
	public final java.lang.String getQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Qty.toString());
	}

	/**
	 * Set value of Qty
	 * @param qty
	 */
	public final void setQty(java.lang.String qty)
	{
		setQty(getContext(), qty);
	}

	/**
	 * Set value of Qty
	 * @param context
	 * @param qty
	 */
	public final void setQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String qty)
	{
		getMendixObject().setValue(context, MemberNames.Qty.toString(), qty);
	}

	/**
	 * @return value of UOM
	 */
	public final java.lang.String getUOM()
	{
		return getUOM(getContext());
	}

	/**
	 * @param context
	 * @return value of UOM
	 */
	public final java.lang.String getUOM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UOM.toString());
	}

	/**
	 * Set value of UOM
	 * @param uom
	 */
	public final void setUOM(java.lang.String uom)
	{
		setUOM(getContext(), uom);
	}

	/**
	 * Set value of UOM
	 * @param context
	 * @param uom
	 */
	public final void setUOM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uom)
	{
		getMendixObject().setValue(context, MemberNames.UOM.toString(), uom);
	}

	/**
	 * @return value of HoldReason
	 */
	public final java.lang.String getHoldReason()
	{
		return getHoldReason(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldReason
	 */
	public final java.lang.String getHoldReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldReason.toString());
	}

	/**
	 * Set value of HoldReason
	 * @param holdreason
	 */
	public final void setHoldReason(java.lang.String holdreason)
	{
		setHoldReason(getContext(), holdreason);
	}

	/**
	 * Set value of HoldReason
	 * @param context
	 * @param holdreason
	 */
	public final void setHoldReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdreason)
	{
		getMendixObject().setValue(context, MemberNames.HoldReason.toString(), holdreason);
	}

	/**
	 * @return value of HoldMessage
	 */
	public final java.lang.String getHoldMessage()
	{
		return getHoldMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldMessage
	 */
	public final java.lang.String getHoldMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldMessage.toString());
	}

	/**
	 * Set value of HoldMessage
	 * @param holdmessage
	 */
	public final void setHoldMessage(java.lang.String holdmessage)
	{
		setHoldMessage(getContext(), holdmessage);
	}

	/**
	 * Set value of HoldMessage
	 * @param context
	 * @param holdmessage
	 */
	public final void setHoldMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdmessage)
	{
		getMendixObject().setValue(context, MemberNames.HoldMessage.toString(), holdmessage);
	}

	/**
	 * @return value of OnHoldDate
	 */
	public final java.lang.String getOnHoldDate()
	{
		return getOnHoldDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OnHoldDate
	 */
	public final java.lang.String getOnHoldDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnHoldDate.toString());
	}

	/**
	 * Set value of OnHoldDate
	 * @param onholddate
	 */
	public final void setOnHoldDate(java.lang.String onholddate)
	{
		setOnHoldDate(getContext(), onholddate);
	}

	/**
	 * Set value of OnHoldDate
	 * @param context
	 * @param onholddate
	 */
	public final void setOnHoldDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onholddate)
	{
		getMendixObject().setValue(context, MemberNames.OnHoldDate.toString(), onholddate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ContainerHoldGridContext_HoldManagementPageContext
	 */
	public final excr_holdmanagement.proxies.HoldManagementPageContext getContainerHoldGridContext_HoldManagementPageContext() throws com.mendix.core.CoreException
	{
		return getContainerHoldGridContext_HoldManagementPageContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainerHoldGridContext_HoldManagementPageContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_holdmanagement.proxies.HoldManagementPageContext getContainerHoldGridContext_HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_holdmanagement.proxies.HoldManagementPageContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ContainerHoldGridContext_HoldManagementPageContext.toString());
		if (identifier != null) {
			result = excr_holdmanagement.proxies.HoldManagementPageContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ContainerHoldGridContext_HoldManagementPageContext
	 * @param containerholdgridcontext_holdmanagementpagecontext
	 */
	public final void setContainerHoldGridContext_HoldManagementPageContext(excr_holdmanagement.proxies.HoldManagementPageContext containerholdgridcontext_holdmanagementpagecontext)
	{
		setContainerHoldGridContext_HoldManagementPageContext(getContext(), containerholdgridcontext_holdmanagementpagecontext);
	}

	/**
	 * Set value of ContainerHoldGridContext_HoldManagementPageContext
	 * @param context
	 * @param containerholdgridcontext_holdmanagementpagecontext
	 */
	public final void setContainerHoldGridContext_HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context, excr_holdmanagement.proxies.HoldManagementPageContext containerholdgridcontext_holdmanagementpagecontext)
	{
		if (containerholdgridcontext_holdmanagementpagecontext == null) {
			getMendixObject().setValue(context, MemberNames.ContainerHoldGridContext_HoldManagementPageContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ContainerHoldGridContext_HoldManagementPageContext.toString(), containerholdgridcontext_holdmanagementpagecontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return containerHoldGridContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_holdmanagement.proxies.ContainerHoldGridContext that = (excr_holdmanagement.proxies.ContainerHoldGridContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
