// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_holdmanagement.proxies;

public class HoldManagementPageContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject holdManagementPageContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_HoldManagement.HoldManagementPageContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ObjectName("ObjectName"),
		ObjectRevision("ObjectRevision"),
		HoldType("HoldType"),
		SearchName("SearchName"),
		SelectedHoldReasonSearch("SelectedHoldReasonSearch"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		HoldName("HoldName"),
		SelectedHoldReason("SelectedHoldReason"),
		HoldMessage("HoldMessage"),
		ReleaseMessage("ReleaseMessage"),
		SelectedReleaseReason("SelectedReleaseReason"),
		TotalRows("TotalRows"),
		SelectionChecked("SelectionChecked");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected HoldManagementPageContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject holdManagementPageContextMendixObject)
	{
		if (holdManagementPageContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!holdManagementPageContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.holdManagementPageContextMendixObject = holdManagementPageContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_holdmanagement.proxies.HoldManagementPageContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_holdmanagement.proxies.HoldManagementPageContext(context, mendixObject);
	}

	public static excr_holdmanagement.proxies.HoldManagementPageContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_holdmanagement.proxies.HoldManagementPageContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of ObjectName
	 */
	public final java.lang.String getObjectName()
	{
		return getObjectName(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectName
	 */
	public final java.lang.String getObjectName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectName.toString());
	}

	/**
	 * Set value of ObjectName
	 * @param objectname
	 */
	public final void setObjectName(java.lang.String objectname)
	{
		setObjectName(getContext(), objectname);
	}

	/**
	 * Set value of ObjectName
	 * @param context
	 * @param objectname
	 */
	public final void setObjectName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objectname)
	{
		getMendixObject().setValue(context, MemberNames.ObjectName.toString(), objectname);
	}

	/**
	 * @return value of ObjectRevision
	 */
	public final java.lang.String getObjectRevision()
	{
		return getObjectRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectRevision
	 */
	public final java.lang.String getObjectRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectRevision.toString());
	}

	/**
	 * Set value of ObjectRevision
	 * @param objectrevision
	 */
	public final void setObjectRevision(java.lang.String objectrevision)
	{
		setObjectRevision(getContext(), objectrevision);
	}

	/**
	 * Set value of ObjectRevision
	 * @param context
	 * @param objectrevision
	 */
	public final void setObjectRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objectrevision)
	{
		getMendixObject().setValue(context, MemberNames.ObjectRevision.toString(), objectrevision);
	}

	/**
	 * Get value of HoldType
	 * @param holdtype
	 */
	public final excr_holdmanagement.proxies.HoldType_ENUM getHoldType()
	{
		return getHoldType(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldType
	 */
	public final excr_holdmanagement.proxies.HoldType_ENUM getHoldType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.HoldType.toString());
		if (obj == null) {
			return null;
		}
		return excr_holdmanagement.proxies.HoldType_ENUM.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of HoldType
	 * @param holdtype
	 */
	public final void setHoldType(excr_holdmanagement.proxies.HoldType_ENUM holdtype)
	{
		setHoldType(getContext(), holdtype);
	}

	/**
	 * Set value of HoldType
	 * @param context
	 * @param holdtype
	 */
	public final void setHoldType(com.mendix.systemwideinterfaces.core.IContext context, excr_holdmanagement.proxies.HoldType_ENUM holdtype)
	{
		if (holdtype != null) {
			getMendixObject().setValue(context, MemberNames.HoldType.toString(), holdtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.HoldType.toString(), null);
		}
	}

	/**
	 * @return value of SearchName
	 */
	public final java.lang.String getSearchName()
	{
		return getSearchName(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchName
	 */
	public final java.lang.String getSearchName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchName.toString());
	}

	/**
	 * Set value of SearchName
	 * @param searchname
	 */
	public final void setSearchName(java.lang.String searchname)
	{
		setSearchName(getContext(), searchname);
	}

	/**
	 * Set value of SearchName
	 * @param context
	 * @param searchname
	 */
	public final void setSearchName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchname)
	{
		getMendixObject().setValue(context, MemberNames.SearchName.toString(), searchname);
	}

	/**
	 * @return value of SelectedHoldReasonSearch
	 */
	public final java.lang.String getSelectedHoldReasonSearch()
	{
		return getSelectedHoldReasonSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedHoldReasonSearch
	 */
	public final java.lang.String getSelectedHoldReasonSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SelectedHoldReasonSearch.toString());
	}

	/**
	 * Set value of SelectedHoldReasonSearch
	 * @param selectedholdreasonsearch
	 */
	public final void setSelectedHoldReasonSearch(java.lang.String selectedholdreasonsearch)
	{
		setSelectedHoldReasonSearch(getContext(), selectedholdreasonsearch);
	}

	/**
	 * Set value of SelectedHoldReasonSearch
	 * @param context
	 * @param selectedholdreasonsearch
	 */
	public final void setSelectedHoldReasonSearch(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String selectedholdreasonsearch)
	{
		getMendixObject().setValue(context, MemberNames.SelectedHoldReasonSearch.toString(), selectedholdreasonsearch);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @return value of HoldName
	 */
	public final java.lang.String getHoldName()
	{
		return getHoldName(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldName
	 */
	public final java.lang.String getHoldName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldName.toString());
	}

	/**
	 * Set value of HoldName
	 * @param holdname
	 */
	public final void setHoldName(java.lang.String holdname)
	{
		setHoldName(getContext(), holdname);
	}

	/**
	 * Set value of HoldName
	 * @param context
	 * @param holdname
	 */
	public final void setHoldName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdname)
	{
		getMendixObject().setValue(context, MemberNames.HoldName.toString(), holdname);
	}

	/**
	 * @return value of SelectedHoldReason
	 */
	public final java.lang.String getSelectedHoldReason()
	{
		return getSelectedHoldReason(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedHoldReason
	 */
	public final java.lang.String getSelectedHoldReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SelectedHoldReason.toString());
	}

	/**
	 * Set value of SelectedHoldReason
	 * @param selectedholdreason
	 */
	public final void setSelectedHoldReason(java.lang.String selectedholdreason)
	{
		setSelectedHoldReason(getContext(), selectedholdreason);
	}

	/**
	 * Set value of SelectedHoldReason
	 * @param context
	 * @param selectedholdreason
	 */
	public final void setSelectedHoldReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String selectedholdreason)
	{
		getMendixObject().setValue(context, MemberNames.SelectedHoldReason.toString(), selectedholdreason);
	}

	/**
	 * @return value of HoldMessage
	 */
	public final java.lang.String getHoldMessage()
	{
		return getHoldMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldMessage
	 */
	public final java.lang.String getHoldMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldMessage.toString());
	}

	/**
	 * Set value of HoldMessage
	 * @param holdmessage
	 */
	public final void setHoldMessage(java.lang.String holdmessage)
	{
		setHoldMessage(getContext(), holdmessage);
	}

	/**
	 * Set value of HoldMessage
	 * @param context
	 * @param holdmessage
	 */
	public final void setHoldMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdmessage)
	{
		getMendixObject().setValue(context, MemberNames.HoldMessage.toString(), holdmessage);
	}

	/**
	 * @return value of ReleaseMessage
	 */
	public final java.lang.String getReleaseMessage()
	{
		return getReleaseMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ReleaseMessage
	 */
	public final java.lang.String getReleaseMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReleaseMessage.toString());
	}

	/**
	 * Set value of ReleaseMessage
	 * @param releasemessage
	 */
	public final void setReleaseMessage(java.lang.String releasemessage)
	{
		setReleaseMessage(getContext(), releasemessage);
	}

	/**
	 * Set value of ReleaseMessage
	 * @param context
	 * @param releasemessage
	 */
	public final void setReleaseMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String releasemessage)
	{
		getMendixObject().setValue(context, MemberNames.ReleaseMessage.toString(), releasemessage);
	}

	/**
	 * @return value of SelectedReleaseReason
	 */
	public final java.lang.String getSelectedReleaseReason()
	{
		return getSelectedReleaseReason(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedReleaseReason
	 */
	public final java.lang.String getSelectedReleaseReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SelectedReleaseReason.toString());
	}

	/**
	 * Set value of SelectedReleaseReason
	 * @param selectedreleasereason
	 */
	public final void setSelectedReleaseReason(java.lang.String selectedreleasereason)
	{
		setSelectedReleaseReason(getContext(), selectedreleasereason);
	}

	/**
	 * Set value of SelectedReleaseReason
	 * @param context
	 * @param selectedreleasereason
	 */
	public final void setSelectedReleaseReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String selectedreleasereason)
	{
		getMendixObject().setValue(context, MemberNames.SelectedReleaseReason.toString(), selectedreleasereason);
	}

	/**
	 * @return value of TotalRows
	 */
	public final java.lang.Integer getTotalRows()
	{
		return getTotalRows(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalRows
	 */
	public final java.lang.Integer getTotalRows(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalRows.toString());
	}

	/**
	 * Set value of TotalRows
	 * @param totalrows
	 */
	public final void setTotalRows(java.lang.Integer totalrows)
	{
		setTotalRows(getContext(), totalrows);
	}

	/**
	 * Set value of TotalRows
	 * @param context
	 * @param totalrows
	 */
	public final void setTotalRows(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalrows)
	{
		getMendixObject().setValue(context, MemberNames.TotalRows.toString(), totalrows);
	}

	/**
	 * @return value of SelectionChecked
	 */
	public final java.lang.Boolean getSelectionChecked()
	{
		return getSelectionChecked(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectionChecked
	 */
	public final java.lang.Boolean getSelectionChecked(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SelectionChecked.toString());
	}

	/**
	 * Set value of SelectionChecked
	 * @param selectionchecked
	 */
	public final void setSelectionChecked(java.lang.Boolean selectionchecked)
	{
		setSelectionChecked(getContext(), selectionchecked);
	}

	/**
	 * Set value of SelectionChecked
	 * @param context
	 * @param selectionchecked
	 */
	public final void setSelectionChecked(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selectionchecked)
	{
		getMendixObject().setValue(context, MemberNames.SelectionChecked.toString(), selectionchecked);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return holdManagementPageContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_holdmanagement.proxies.HoldManagementPageContext that = (excr_holdmanagement.proxies.HoldManagementPageContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
