// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_inlinespc_api.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the EXCR_InlineSPC_API module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pOST_AdHocSPC_CreateBuilder(
		excr_inlinespc_api.proxies.APIReqSPCParam _aPIReqSPCParam,
		excr_inlinespc_api.proxies.APIReqSPCSetup _aPIReqSPCSetup
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_InlineSPC_API.POST_AdHocSPC_Create");
		builder = builder.withParam("APIReqSPCParam", _aPIReqSPCParam);
		builder = builder.withParam("APIReqSPCSetup", _aPIReqSPCSetup);
		return builder;
	}

	public static excr_inlinespc_api.proxies.APIResSPCRoot pOST_AdHocSPC_Create(
		IContext context,
		excr_inlinespc_api.proxies.APIReqSPCParam _aPIReqSPCParam,
		excr_inlinespc_api.proxies.APIReqSPCSetup _aPIReqSPCSetup
	)
	{
		Object result = pOST_AdHocSPC_CreateBuilder(
				_aPIReqSPCParam,
				_aPIReqSPCSetup
			)
			.execute(context);
		return result == null ? null : excr_inlinespc_api.proxies.APIResSPCRoot.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pOST_AdHocWIPData_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_InlineSPC_API.POST_AdHocWIPData_Create");
		return builder;
	}

	public static excr_inlinespc_api.proxies.APIResSPCRoot pOST_AdHocWIPData_Create(IContext context)
	{
		Object result = pOST_AdHocWIPData_CreateBuilder().execute(context);
		return result == null ? null : excr_inlinespc_api.proxies.APIResSPCRoot.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pRS_DELETE_SPCTxnDataPoint_SubmitBuilder(
		excr_inlinespc_api.proxies.APIReqSPCTxnDataPointSubmit _aPIReqSPCTxnDataPointSubmit,
		excr_inlinespc_api.proxies.SPCResDataPoint _sPCResDataPoint,
		excr_commons.proxies.Notification _notification
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_InlineSPC_API.PRS_DELETE_SPCTxnDataPoint_Submit");
		builder = builder.withParam("APIReqSPCTxnDataPointSubmit", _aPIReqSPCTxnDataPointSubmit);
		builder = builder.withParam("SPCResDataPoint", _sPCResDataPoint);
		builder = builder.withParam("Notification", _notification);
		return builder;
	}

	public static excr_commons.proxies.Notification pRS_DELETE_SPCTxnDataPoint_Submit(
		IContext context,
		excr_inlinespc_api.proxies.APIReqSPCTxnDataPointSubmit _aPIReqSPCTxnDataPointSubmit,
		excr_inlinespc_api.proxies.SPCResDataPoint _sPCResDataPoint,
		excr_commons.proxies.Notification _notification
	)
	{
		Object result = pRS_DELETE_SPCTxnDataPoint_SubmitBuilder(
				_aPIReqSPCTxnDataPointSubmit,
				_sPCResDataPoint,
				_notification
			)
			.execute(context);
		return result == null ? null : excr_commons.proxies.Notification.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pRS_GET_NDO_ListBuilder(
		java.lang.String _objectName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_InlineSPC_API.PRS_GET_NDO_List");
		builder = builder.withParam("ObjectName", _objectName);
		return builder;
	}

	public static excr_inlinespc_api.proxies.SPCResNDOs pRS_GET_NDO_List(
		IContext context,
		java.lang.String _objectName
	)
	{
		Object result = pRS_GET_NDO_ListBuilder(
				_objectName
			)
			.execute(context);
		return result == null ? null : excr_inlinespc_api.proxies.SPCResNDOs.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pRS_GET_SPCTxnDataPointBuilder(
		java.lang.String _whereClause
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_InlineSPC_API.PRS_GET_SPCTxnDataPoint");
		builder = builder.withParam("WhereClause", _whereClause);
		return builder;
	}

	public static excr_inlinespc_api.proxies.APIResSPCTxnDataPoint pRS_GET_SPCTxnDataPoint(
		IContext context,
		java.lang.String _whereClause
	)
	{
		Object result = pRS_GET_SPCTxnDataPointBuilder(
				_whereClause
			)
			.execute(context);
		return result == null ? null : excr_inlinespc_api.proxies.APIResSPCTxnDataPoint.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pRS_POST_SPCTxnDataPoint_SubmitBuilder(
		excr_inlinespc_api.proxies.APIReqSPCTxnDataPointSubmit _aPIReqSPCTxnDataPointSubmit,
		excr_commons.proxies.Notification _notification
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_InlineSPC_API.PRS_POST_SPCTxnDataPoint_Submit");
		builder = builder.withParam("APIReqSPCTxnDataPointSubmit", _aPIReqSPCTxnDataPointSubmit);
		builder = builder.withParam("Notification", _notification);
		return builder;
	}

	public static excr_commons.proxies.Notification pRS_POST_SPCTxnDataPoint_Submit(
		IContext context,
		excr_inlinespc_api.proxies.APIReqSPCTxnDataPointSubmit _aPIReqSPCTxnDataPointSubmit,
		excr_commons.proxies.Notification _notification
	)
	{
		Object result = pRS_POST_SPCTxnDataPoint_SubmitBuilder(
				_aPIReqSPCTxnDataPointSubmit,
				_notification
			)
			.execute(context);
		return result == null ? null : excr_commons.proxies.Notification.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pRS_PUT_SPCTxnData_ReplotBuilder(
		excr_inlinespc.proxies.SPCDataViewControl _sPCDataViewControl
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_InlineSPC_API.PRS_PUT_SPCTxnData_Replot");
		builder = builder.withParam("SPCDataViewControl", _sPCDataViewControl);
		return builder;
	}

	public static boolean pRS_PUT_SPCTxnData_Replot(
		IContext context,
		excr_inlinespc.proxies.SPCDataViewControl _sPCDataViewControl
	)
	{
		Object result = pRS_PUT_SPCTxnData_ReplotBuilder(
				_sPCDataViewControl
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pRS_PUT_SPCTxnDataPoint_SubmitBuilder(
		excr_inlinespc_api.proxies.APIReqSPCTxnDataPointSubmit _aPIReqSPCTxnDataPointSubmit,
		excr_inlinespc_api.proxies.SPCResDataPoint _sPCResDataPoint,
		excr_commons.proxies.Notification _notification
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_InlineSPC_API.PRS_PUT_SPCTxnDataPoint_Submit");
		builder = builder.withParam("APIReqSPCTxnDataPointSubmit", _aPIReqSPCTxnDataPointSubmit);
		builder = builder.withParam("SPCResDataPoint", _sPCResDataPoint);
		builder = builder.withParam("Notification", _notification);
		return builder;
	}

	public static excr_commons.proxies.Notification pRS_PUT_SPCTxnDataPoint_Submit(
		IContext context,
		excr_inlinespc_api.proxies.APIReqSPCTxnDataPointSubmit _aPIReqSPCTxnDataPointSubmit,
		excr_inlinespc_api.proxies.SPCResDataPoint _sPCResDataPoint,
		excr_commons.proxies.Notification _notification
	)
	{
		Object result = pRS_PUT_SPCTxnDataPoint_SubmitBuilder(
				_aPIReqSPCTxnDataPointSubmit,
				_sPCResDataPoint,
				_notification
			)
			.execute(context);
		return result == null ? null : excr_commons.proxies.Notification.initialize(context, (IMendixObject) result);
	}
}
