// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure.proxies;

public class Document implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject documentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure.Document";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceID("InstanceID"),
		DisplayName("DisplayName"),
		DocumentName("DocumentName"),
		Description("Description"),
		DocumentIdentifier("DocumentIdentifier"),
		DocumentIcon("DocumentIcon"),
		Revision("Revision"),
		Document_DocumentSet("EXCR_EProcedure.Document_DocumentSet");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Document(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Document(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentMendixObject)
	{
		if (documentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!documentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.documentMendixObject = documentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure.proxies.Document initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure.proxies.Document(context, mendixObject);
	}

	public static excr_eprocedure.proxies.Document load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure.proxies.Document.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID()
	{
		return getInstanceID(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceID.toString());
	}

	/**
	 * Set value of InstanceID
	 * @param instanceid
	 */
	public final void setInstanceID(java.lang.String instanceid)
	{
		setInstanceID(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceID
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceID.toString(), instanceid);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of DocumentName
	 */
	public final java.lang.String getDocumentName()
	{
		return getDocumentName(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentName
	 */
	public final java.lang.String getDocumentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DocumentName.toString());
	}

	/**
	 * Set value of DocumentName
	 * @param documentname
	 */
	public final void setDocumentName(java.lang.String documentname)
	{
		setDocumentName(getContext(), documentname);
	}

	/**
	 * Set value of DocumentName
	 * @param context
	 * @param documentname
	 */
	public final void setDocumentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String documentname)
	{
		getMendixObject().setValue(context, MemberNames.DocumentName.toString(), documentname);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of DocumentIdentifier
	 */
	public final java.lang.String getDocumentIdentifier()
	{
		return getDocumentIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentIdentifier
	 */
	public final java.lang.String getDocumentIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DocumentIdentifier.toString());
	}

	/**
	 * Set value of DocumentIdentifier
	 * @param documentidentifier
	 */
	public final void setDocumentIdentifier(java.lang.String documentidentifier)
	{
		setDocumentIdentifier(getContext(), documentidentifier);
	}

	/**
	 * Set value of DocumentIdentifier
	 * @param context
	 * @param documentidentifier
	 */
	public final void setDocumentIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String documentidentifier)
	{
		getMendixObject().setValue(context, MemberNames.DocumentIdentifier.toString(), documentidentifier);
	}

	/**
	 * @return value of DocumentIcon
	 */
	public final java.lang.String getDocumentIcon()
	{
		return getDocumentIcon(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentIcon
	 */
	public final java.lang.String getDocumentIcon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DocumentIcon.toString());
	}

	/**
	 * Set value of DocumentIcon
	 * @param documenticon
	 */
	public final void setDocumentIcon(java.lang.String documenticon)
	{
		setDocumentIcon(getContext(), documenticon);
	}

	/**
	 * Set value of DocumentIcon
	 * @param context
	 * @param documenticon
	 */
	public final void setDocumentIcon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String documenticon)
	{
		getMendixObject().setValue(context, MemberNames.DocumentIcon.toString(), documenticon);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Document_DocumentSet
	 */
	public final excr_eprocedure.proxies.DocumentSet getDocument_DocumentSet() throws com.mendix.core.CoreException
	{
		return getDocument_DocumentSet(getContext());
	}

	/**
	 * @param context
	 * @return value of Document_DocumentSet
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure.proxies.DocumentSet getDocument_DocumentSet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure.proxies.DocumentSet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Document_DocumentSet.toString());
		if (identifier != null) {
			result = excr_eprocedure.proxies.DocumentSet.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Document_DocumentSet
	 * @param document_documentset
	 */
	public final void setDocument_DocumentSet(excr_eprocedure.proxies.DocumentSet document_documentset)
	{
		setDocument_DocumentSet(getContext(), document_documentset);
	}

	/**
	 * Set value of Document_DocumentSet
	 * @param context
	 * @param document_documentset
	 */
	public final void setDocument_DocumentSet(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure.proxies.DocumentSet document_documentset)
	{
		if (document_documentset == null) {
			getMendixObject().setValue(context, MemberNames.Document_DocumentSet.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Document_DocumentSet.toString(), document_documentset.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return documentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure.proxies.Document that = (excr_eprocedure.proxies.Document) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
