// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure.proxies;

public class OnlineQueryReqParameters implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject onlineQueryReqParametersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EProcedure.OnlineQueryReqParameters";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ParameterName("ParameterName"),
		ParameterValue("ParameterValue"),
		OnlineQueryReqParameters_OnlineQueryReq("EXCR_EProcedure.OnlineQueryReqParameters_OnlineQueryReq");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OnlineQueryReqParameters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OnlineQueryReqParameters(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject onlineQueryReqParametersMendixObject)
	{
		if (onlineQueryReqParametersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!onlineQueryReqParametersMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.onlineQueryReqParametersMendixObject = onlineQueryReqParametersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_eprocedure.proxies.OnlineQueryReqParameters initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_eprocedure.proxies.OnlineQueryReqParameters(context, mendixObject);
	}

	public static excr_eprocedure.proxies.OnlineQueryReqParameters load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_eprocedure.proxies.OnlineQueryReqParameters.initialize(context, mendixObject);
	}

	/**
	 * @return value of ParameterName
	 */
	public final java.lang.String getParameterName()
	{
		return getParameterName(getContext());
	}

	/**
	 * @param context
	 * @return value of ParameterName
	 */
	public final java.lang.String getParameterName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParameterName.toString());
	}

	/**
	 * Set value of ParameterName
	 * @param parametername
	 */
	public final void setParameterName(java.lang.String parametername)
	{
		setParameterName(getContext(), parametername);
	}

	/**
	 * Set value of ParameterName
	 * @param context
	 * @param parametername
	 */
	public final void setParameterName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parametername)
	{
		getMendixObject().setValue(context, MemberNames.ParameterName.toString(), parametername);
	}

	/**
	 * @return value of ParameterValue
	 */
	public final java.lang.String getParameterValue()
	{
		return getParameterValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ParameterValue
	 */
	public final java.lang.String getParameterValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParameterValue.toString());
	}

	/**
	 * Set value of ParameterValue
	 * @param parametervalue
	 */
	public final void setParameterValue(java.lang.String parametervalue)
	{
		setParameterValue(getContext(), parametervalue);
	}

	/**
	 * Set value of ParameterValue
	 * @param context
	 * @param parametervalue
	 */
	public final void setParameterValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parametervalue)
	{
		getMendixObject().setValue(context, MemberNames.ParameterValue.toString(), parametervalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OnlineQueryReqParameters_OnlineQueryReq
	 */
	public final excr_eprocedure.proxies.OnlineQueryReq getOnlineQueryReqParameters_OnlineQueryReq() throws com.mendix.core.CoreException
	{
		return getOnlineQueryReqParameters_OnlineQueryReq(getContext());
	}

	/**
	 * @param context
	 * @return value of OnlineQueryReqParameters_OnlineQueryReq
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure.proxies.OnlineQueryReq getOnlineQueryReqParameters_OnlineQueryReq(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure.proxies.OnlineQueryReq result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OnlineQueryReqParameters_OnlineQueryReq.toString());
		if (identifier != null) {
			result = excr_eprocedure.proxies.OnlineQueryReq.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OnlineQueryReqParameters_OnlineQueryReq
	 * @param onlinequeryreqparameters_onlinequeryreq
	 */
	public final void setOnlineQueryReqParameters_OnlineQueryReq(excr_eprocedure.proxies.OnlineQueryReq onlinequeryreqparameters_onlinequeryreq)
	{
		setOnlineQueryReqParameters_OnlineQueryReq(getContext(), onlinequeryreqparameters_onlinequeryreq);
	}

	/**
	 * Set value of OnlineQueryReqParameters_OnlineQueryReq
	 * @param context
	 * @param onlinequeryreqparameters_onlinequeryreq
	 */
	public final void setOnlineQueryReqParameters_OnlineQueryReq(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure.proxies.OnlineQueryReq onlinequeryreqparameters_onlinequeryreq)
	{
		if (onlinequeryreqparameters_onlinequeryreq == null) {
			getMendixObject().setValue(context, MemberNames.OnlineQueryReqParameters_OnlineQueryReq.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OnlineQueryReqParameters_OnlineQueryReq.toString(), onlinequeryreqparameters_onlinequeryreq.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return onlineQueryReqParametersMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_eprocedure.proxies.OnlineQueryReqParameters that = (excr_eprocedure.proxies.OnlineQueryReqParameters) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
