// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usercommons.proxies;

public class UserProvisionAutoConfig implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userProvisionAutoConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserCommons.UserProvisionAutoConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UserEntity("UserEntity"),
		PrincipalAttribute("PrincipalAttribute"),
		IDPPrincipalAttribute("IDPPrincipalAttribute"),
		UserRole("UserRole"),
		CustomUserProvisioning("CustomUserProvisioning"),
		UserType("UserType"),
		AllowCreateUsers("AllowCreateUsers");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserProvisionAutoConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UserProvisionAutoConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userProvisionAutoConfigMendixObject)
	{
		if (userProvisionAutoConfigMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!userProvisionAutoConfigMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.userProvisionAutoConfigMendixObject = userProvisionAutoConfigMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static usercommons.proxies.UserProvisionAutoConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new usercommons.proxies.UserProvisionAutoConfig(context, mendixObject);
	}

	public static usercommons.proxies.UserProvisionAutoConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return usercommons.proxies.UserProvisionAutoConfig.initialize(context, mendixObject);
	}

	/**
	 * @return value of UserEntity
	 */
	public final java.lang.String getUserEntity()
	{
		return getUserEntity(getContext());
	}

	/**
	 * @param context
	 * @return value of UserEntity
	 */
	public final java.lang.String getUserEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserEntity.toString());
	}

	/**
	 * Set value of UserEntity
	 * @param userentity
	 */
	public final void setUserEntity(java.lang.String userentity)
	{
		setUserEntity(getContext(), userentity);
	}

	/**
	 * Set value of UserEntity
	 * @param context
	 * @param userentity
	 */
	public final void setUserEntity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userentity)
	{
		getMendixObject().setValue(context, MemberNames.UserEntity.toString(), userentity);
	}

	/**
	 * @return value of PrincipalAttribute
	 */
	public final java.lang.String getPrincipalAttribute()
	{
		return getPrincipalAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of PrincipalAttribute
	 */
	public final java.lang.String getPrincipalAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PrincipalAttribute.toString());
	}

	/**
	 * Set value of PrincipalAttribute
	 * @param principalattribute
	 */
	public final void setPrincipalAttribute(java.lang.String principalattribute)
	{
		setPrincipalAttribute(getContext(), principalattribute);
	}

	/**
	 * Set value of PrincipalAttribute
	 * @param context
	 * @param principalattribute
	 */
	public final void setPrincipalAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String principalattribute)
	{
		getMendixObject().setValue(context, MemberNames.PrincipalAttribute.toString(), principalattribute);
	}

	/**
	 * @return value of IDPPrincipalAttribute
	 */
	public final java.lang.String getIDPPrincipalAttribute()
	{
		return getIDPPrincipalAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of IDPPrincipalAttribute
	 */
	public final java.lang.String getIDPPrincipalAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IDPPrincipalAttribute.toString());
	}

	/**
	 * Set value of IDPPrincipalAttribute
	 * @param idpprincipalattribute
	 */
	public final void setIDPPrincipalAttribute(java.lang.String idpprincipalattribute)
	{
		setIDPPrincipalAttribute(getContext(), idpprincipalattribute);
	}

	/**
	 * Set value of IDPPrincipalAttribute
	 * @param context
	 * @param idpprincipalattribute
	 */
	public final void setIDPPrincipalAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String idpprincipalattribute)
	{
		getMendixObject().setValue(context, MemberNames.IDPPrincipalAttribute.toString(), idpprincipalattribute);
	}

	/**
	 * @return value of UserRole
	 */
	public final java.lang.String getUserRole()
	{
		return getUserRole(getContext());
	}

	/**
	 * @param context
	 * @return value of UserRole
	 */
	public final java.lang.String getUserRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserRole.toString());
	}

	/**
	 * Set value of UserRole
	 * @param userrole
	 */
	public final void setUserRole(java.lang.String userrole)
	{
		setUserRole(getContext(), userrole);
	}

	/**
	 * Set value of UserRole
	 * @param context
	 * @param userrole
	 */
	public final void setUserRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userrole)
	{
		getMendixObject().setValue(context, MemberNames.UserRole.toString(), userrole);
	}

	/**
	 * @return value of CustomUserProvisioning
	 */
	public final java.lang.String getCustomUserProvisioning()
	{
		return getCustomUserProvisioning(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomUserProvisioning
	 */
	public final java.lang.String getCustomUserProvisioning(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomUserProvisioning.toString());
	}

	/**
	 * Set value of CustomUserProvisioning
	 * @param customuserprovisioning
	 */
	public final void setCustomUserProvisioning(java.lang.String customuserprovisioning)
	{
		setCustomUserProvisioning(getContext(), customuserprovisioning);
	}

	/**
	 * Set value of CustomUserProvisioning
	 * @param context
	 * @param customuserprovisioning
	 */
	public final void setCustomUserProvisioning(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customuserprovisioning)
	{
		getMendixObject().setValue(context, MemberNames.CustomUserProvisioning.toString(), customuserprovisioning);
	}

	/**
	 * @return value of UserType
	 */
	public final java.lang.String getUserType()
	{
		return getUserType(getContext());
	}

	/**
	 * @param context
	 * @return value of UserType
	 */
	public final java.lang.String getUserType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserType.toString());
	}

	/**
	 * Set value of UserType
	 * @param usertype
	 */
	public final void setUserType(java.lang.String usertype)
	{
		setUserType(getContext(), usertype);
	}

	/**
	 * Set value of UserType
	 * @param context
	 * @param usertype
	 */
	public final void setUserType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usertype)
	{
		getMendixObject().setValue(context, MemberNames.UserType.toString(), usertype);
	}

	/**
	 * @return value of AllowCreateUsers
	 */
	public final java.lang.Boolean getAllowCreateUsers()
	{
		return getAllowCreateUsers(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowCreateUsers
	 */
	public final java.lang.Boolean getAllowCreateUsers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AllowCreateUsers.toString());
	}

	/**
	 * Set value of AllowCreateUsers
	 * @param allowcreateusers
	 */
	public final void setAllowCreateUsers(java.lang.Boolean allowcreateusers)
	{
		setAllowCreateUsers(getContext(), allowcreateusers);
	}

	/**
	 * Set value of AllowCreateUsers
	 * @param context
	 * @param allowcreateusers
	 */
	public final void setAllowCreateUsers(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allowcreateusers)
	{
		getMendixObject().setValue(context, MemberNames.AllowCreateUsers.toString(), allowcreateusers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userProvisionAutoConfigMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final usercommons.proxies.UserProvisionAutoConfig that = (usercommons.proxies.UserProvisionAutoConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
