// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package saml20.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import saml20.implementation.SAMLRequestHandler;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DelegatedAuthentication extends UserAction<java.lang.Boolean>
{
	/** @deprecated use SAMLSessionParam.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __SAMLSessionParam;
	private final saml20.proxies.SAMLSession SAMLSessionParam;
	private final java.lang.String ResourceURL;

	public DelegatedAuthentication(
		IContext context,
		IMendixObject _sAMLSessionParam,
		java.lang.String _resourceURL
	)
	{
		super(context);
		this.__SAMLSessionParam = _sAMLSessionParam;
		this.SAMLSessionParam = _sAMLSessionParam == null ? null : saml20.proxies.SAMLSession.initialize(getContext(), _sAMLSessionParam);
		this.ResourceURL = _resourceURL;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        SAMLRequestHandler.getInstance(getContext()).requestDelegatedAuthentication(this.SAMLSessionParam.getSessionID(), this.ResourceURL);

        return false;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DelegatedAuthentication";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
