// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the SAML20 module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCo_ADe_ClaimMapBuilder(
		saml20.proxies.ClaimMap _claimMap
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.ACo_ADe_ClaimMap");
		builder = builder.withParam("ClaimMap", _claimMap);
		return builder;
	}

	public static void aCo_ADe_ClaimMap(
		IContext context,
		saml20.proxies.ClaimMap _claimMap
	)
	{
		aCo_ADe_ClaimMapBuilder(
				_claimMap
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AttributeConsumingService_SaveBuilder(
		saml20.proxies.SPAttributeConsumingService _sPAttributeConsumingService,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.ACT_AttributeConsumingService_Save");
		builder = builder.withParam("SPAttributeConsumingService", _sPAttributeConsumingService);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static boolean aCT_AttributeConsumingService_Save(
		IContext context,
		saml20.proxies.SPAttributeConsumingService _sPAttributeConsumingService,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = aCT_AttributeConsumingService_SaveBuilder(
				_sPAttributeConsumingService,
				_sSOConfiguration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SPRequestedAttribute_DeleteBuilder(
		saml20.proxies.SPRequestedAttribute _sPRequestedAttribute,
		saml20.proxies.SPAttributeConsumingService _sPAttributeConsumingService,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.ACT_SPRequestedAttribute_Delete");
		builder = builder.withParam("SPRequestedAttribute", _sPRequestedAttribute);
		builder = builder.withParam("SPAttributeConsumingService", _sPAttributeConsumingService);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void aCT_SPRequestedAttribute_Delete(
		IContext context,
		saml20.proxies.SPRequestedAttribute _sPRequestedAttribute,
		saml20.proxies.SPAttributeConsumingService _sPAttributeConsumingService,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		aCT_SPRequestedAttribute_DeleteBuilder(
				_sPRequestedAttribute,
				_sPAttributeConsumingService,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_CreateSPMetadataAndSSOConfigurationBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.ASU_CreateSPMetadataAndSSOConfiguration");
		return builder;
	}

	public static void aSU_CreateSPMetadataAndSSOConfiguration(IContext context)
	{
		aSU_CreateSPMetadataAndSSOConfigurationBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder checkADFSDefaultsBuilder(
		saml20.proxies.EntityDescriptor _entitiesDescriptor_adfs,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.CheckADFSDefaults");
		builder = builder.withParam("EntitiesDescriptor_adfs", _entitiesDescriptor_adfs);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void checkADFSDefaults(
		IContext context,
		saml20.proxies.EntityDescriptor _entitiesDescriptor_adfs,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		checkADFSDefaultsBuilder(
				_entitiesDescriptor_adfs,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder create_SP_MetadataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.Create_SP_Metadata");
		return builder;
	}

	public static boolean create_SP_Metadata(IContext context)
	{
		Object result = create_SP_MetadataBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder custom_Create_IdPConfigurationBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.Custom_Create_IdPConfiguration");
		return builder;
	}

	public static java.util.List<saml20.proxies.Dep_IdPConfiguration> custom_Create_IdPConfiguration(IContext context)
	{
		Object result = custom_Create_IdPConfigurationBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> saml20.proxies.Dep_IdPConfiguration.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder customAfterSigninLogicBuilder(
		system.proxies.Session _previousSession,
		system.proxies.Session _newSession,
		system.proxies.User _previousUser,
		system.proxies.User _newUser,
		saml20.proxies.SAMLRequest _samlRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.CustomAfterSigninLogic");
		builder = builder.withParam("PreviousSession", _previousSession);
		builder = builder.withParam("NewSession", _newSession);
		builder = builder.withParam("PreviousUser", _previousUser);
		builder = builder.withParam("NewUser", _newUser);
		builder = builder.withParam("SamlRequest", _samlRequest);
		return builder;
	}

	public static void customAfterSigninLogic(
		IContext context,
		system.proxies.Session _previousSession,
		system.proxies.Session _newSession,
		system.proxies.User _previousUser,
		system.proxies.User _newUser,
		saml20.proxies.SAMLRequest _samlRequest
	)
	{
		customAfterSigninLogicBuilder(
				_previousSession,
				_newSession,
				_previousUser,
				_newUser,
				_samlRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder customEvaluateInSessionAuthenticationBuilder(
		system.proxies.Session _existingSession,
		system.proxies.User _existingUser,
		system.proxies.User _newUser,
		saml20.proxies.SAMLRequest _samlRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.CustomEvaluateInSessionAuthentication");
		builder = builder.withParam("ExistingSession", _existingSession);
		builder = builder.withParam("ExistingUser", _existingUser);
		builder = builder.withParam("NewUser", _newUser);
		builder = builder.withParam("SamlRequest", _samlRequest);
		return builder;
	}

	public static void customEvaluateInSessionAuthentication(
		IContext context,
		system.proxies.Session _existingSession,
		system.proxies.User _existingUser,
		system.proxies.User _newUser,
		saml20.proxies.SAMLRequest _samlRequest
	)
	{
		customEvaluateInSessionAuthenticationBuilder(
				_existingSession,
				_existingUser,
				_newUser,
				_samlRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder customPrepareInSessionAuthenticationBuilder(
		java.lang.String _contextOn,
		saml20.proxies.SAMLRequest _samlRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.CustomPrepareInSessionAuthentication");
		builder = builder.withParam("ContextOn", _contextOn);
		builder = builder.withParam("SamlRequest", _samlRequest);
		return builder;
	}

	public static void customPrepareInSessionAuthentication(
		IContext context,
		java.lang.String _contextOn,
		saml20.proxies.SAMLRequest _samlRequest
	)
	{
		customPrepareInSessionAuthenticationBuilder(
				_contextOn,
				_samlRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder customUserProvisioningBuilder(
		saml20.proxies.SAMLSession _sAMLSession,
		system.proxies.User _user,
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.util.List<saml20.proxies.AssertionAttribute> _assertionAttributeList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.CustomUserProvisioning");
		builder = builder.withParam("SAMLSession", _sAMLSession);
		builder = builder.withParam("User", _user);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		builder = builder.withParam("AssertionAttributeList", _assertionAttributeList);
		return builder;
	}

	public static saml20.proxies.LoginFeedback customUserProvisioning(
		IContext context,
		saml20.proxies.SAMLSession _sAMLSession,
		system.proxies.User _user,
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.util.List<saml20.proxies.AssertionAttribute> _assertionAttributeList
	)
	{
		Object result = customUserProvisioningBuilder(
				_sAMLSession,
				_user,
				_sSOConfiguration,
				_assertionAttributeList
			)
			.execute(context);
		return result == null ? null : saml20.proxies.LoginFeedback.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder default_CreateIDPConfigurationBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.Default_CreateIDPConfiguration");
		return builder;
	}

	public static java.util.List<saml20.proxies.Dep_IdPConfiguration> default_CreateIDPConfiguration(IContext context)
	{
		Object result = default_CreateIDPConfigurationBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> saml20.proxies.Dep_IdPConfiguration.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder download_SP_MetadataBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.Download_SP_Metadata");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void download_SP_Metadata(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		download_SP_MetadataBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetKeyDescriptorBuilder(
		saml20.proxies.KeyInfo _keyInfo
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.DS_GetKeyDescriptor");
		builder = builder.withParam("KeyInfo", _keyInfo);
		return builder;
	}

	public static saml20.proxies.KeyDescriptor dS_GetKeyDescriptor(
		IContext context,
		saml20.proxies.KeyInfo _keyInfo
	)
	{
		Object result = dS_GetKeyDescriptorBuilder(
				_keyInfo
			)
			.execute(context);
		return result == null ? null : saml20.proxies.KeyDescriptor.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetSPAttributeConsumingService_InitialLoginBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.DS_GetSPAttributeConsumingService_InitialLogin");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static saml20.proxies.SPAttributeConsumingService dS_GetSPAttributeConsumingService_InitialLogin(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = dS_GetSPAttributeConsumingService_InitialLoginBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : saml20.proxies.SPAttributeConsumingService.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetSPAttributeConsumingService_InSessionLoginBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.DS_GetSPAttributeConsumingService_InSessionLogin");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static saml20.proxies.SPAttributeConsumingService dS_GetSPAttributeConsumingService_InSessionLogin(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = dS_GetSPAttributeConsumingService_InSessionLoginBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : saml20.proxies.SPAttributeConsumingService.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetSPMetadataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.DS_GetSPMetadata");
		return builder;
	}

	public static saml20.proxies.SPMetadata dS_GetSPMetadata(IContext context)
	{
		Object result = dS_GetSPMetadataBuilder().execute(context);
		return result == null ? null : saml20.proxies.SPMetadata.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetSSOMetadataLinkBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.DS_GetSSOMetadataLink");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static saml20.proxies.SSOMetadataLink dS_GetSSOMetadataLink(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = dS_GetSSOMetadataLinkBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : saml20.proxies.SSOMetadataLink.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_RetrieveAvailableSAMLAuthnContextsBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.DS_RetrieveAvailableSAMLAuthnContexts");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static java.util.List<saml20.proxies.SAMLAuthnContext> dS_RetrieveAvailableSAMLAuthnContexts(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = dS_RetrieveAvailableSAMLAuthnContextsBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> saml20.proxies.SAMLAuthnContext.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder evaluateMultipleUserMatchesBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.util.List<saml20.proxies.AssertionAttribute> _assertionAttributeList,
		java.util.List<system.proxies.User> _matchingUserList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.evaluateMultipleUserMatches");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		builder = builder.withParam("AssertionAttributeList", _assertionAttributeList);
		builder = builder.withParam("MatchingUserList", _matchingUserList);
		return builder;
	}

	public static system.proxies.User evaluateMultipleUserMatches(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.util.List<saml20.proxies.AssertionAttribute> _assertionAttributeList,
		java.util.List<system.proxies.User> _matchingUserList
	)
	{
		Object result = evaluateMultipleUserMatchesBuilder(
				_sSOConfiguration,
				_assertionAttributeList,
				_matchingUserList
			)
			.execute(context);
		return result == null ? null : system.proxies.User.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder extractMetadataFromObjectBuilder(
		saml20.proxies.IdPMetadata _idPMetadata
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.ExtractMetadataFromObject");
		builder = builder.withParam("IdPMetadata", _idPMetadata);
		return builder;
	}

	public static void extractMetadataFromObject(
		IContext context,
		saml20.proxies.IdPMetadata _idPMetadata
	)
	{
		extractMetadataFromObjectBuilder(
				_idPMetadata
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getAttributeBuilder(
		java.lang.String _name,
		java.lang.String _friendlyName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.GetAttribute");
		builder = builder.withParam("Name", _name);
		builder = builder.withParam("FriendlyName", _friendlyName);
		return builder;
	}

	public static saml20.proxies.Attribute getAttribute(
		IContext context,
		java.lang.String _name,
		java.lang.String _friendlyName
	)
	{
		Object result = getAttributeBuilder(
				_name,
				_friendlyName
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Attribute.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getCustomMicroflowsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.GetCustomMicroflows");
		return builder;
	}

	public static java.util.List<usercommons.proxies.CustomFlow> getCustomMicroflows(IContext context)
	{
		Object result = getCustomMicroflowsBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> usercommons.proxies.CustomFlow.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder idPMetadata_RefreshBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.IdPMetadata_Refresh");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void idPMetadata_Refresh(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		idPMetadata_RefreshBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder importIDPFileBuilder(
		saml20.proxies.IdPMetadata _fileDocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.ImportIDPFile");
		builder = builder.withParam("FileDocument", _fileDocument);
		return builder;
	}

	public static void importIDPFile(
		IContext context,
		saml20.proxies.IdPMetadata _fileDocument
	)
	{
		importIDPFileBuilder(
				_fileDocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_AssertionConsumerServiceBuilder(
		java.lang.String _binding
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_AssertionConsumerService");
		builder = builder.withParam("Binding", _binding);
		return builder;
	}

	public static saml20.proxies.Endpoint m_AssertionConsumerService(
		IContext context,
		java.lang.String _binding
	)
	{
		Object result = m_AssertionConsumerServiceBuilder(
				_binding
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Endpoint.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetArtifactResolutionServiceBuilder(
		java.lang.String _binding
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetArtifactResolutionService");
		builder = builder.withParam("Binding", _binding);
		return builder;
	}

	public static saml20.proxies.Endpoint m_GetArtifactResolutionService(
		IContext context,
		java.lang.String _binding
	)
	{
		Object result = m_GetArtifactResolutionServiceBuilder(
				_binding
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Endpoint.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetAssertionIDRequestServiceBuilder(
		java.lang.String _binding
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetAssertionIDRequestService");
		builder = builder.withParam("Binding", _binding);
		return builder;
	}

	public static saml20.proxies.Endpoint m_GetAssertionIDRequestService(
		IContext context,
		java.lang.String _binding
	)
	{
		Object result = m_GetAssertionIDRequestServiceBuilder(
				_binding
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Endpoint.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetAttributeBuilder(
		saml20.proxies.IdPMetadata _idPMetadata,
		java.lang.String _name,
		java.lang.String _friendlyName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetAttribute");
		builder = builder.withParam("IdPMetadata", _idPMetadata);
		builder = builder.withParam("Name", _name);
		builder = builder.withParam("FriendlyName", _friendlyName);
		return builder;
	}

	public static saml20.proxies.Attribute m_GetAttribute(
		IContext context,
		saml20.proxies.IdPMetadata _idPMetadata,
		java.lang.String _name,
		java.lang.String _friendlyName
	)
	{
		Object result = m_GetAttributeBuilder(
				_idPMetadata,
				_name,
				_friendlyName
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Attribute.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetAttributeAuthorityDescriptorBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetAttributeAuthorityDescriptor");
		return builder;
	}

	public static saml20.proxies.RoleDescriptor m_GetAttributeAuthorityDescriptor(IContext context)
	{
		Object result = m_GetAttributeAuthorityDescriptorBuilder().execute(context);
		return result == null ? null : saml20.proxies.RoleDescriptor.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetAttributeServiceBuilder(
		java.lang.String _binding
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetAttributeService");
		builder = builder.withParam("Binding", _binding);
		return builder;
	}

	public static saml20.proxies.Endpoint m_GetAttributeService(
		IContext context,
		java.lang.String _binding
	)
	{
		Object result = m_GetAttributeServiceBuilder(
				_binding
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Endpoint.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetEntitiesDescriptorBuilder(
		saml20.proxies.IdPMetadata _idPMetadata,
		java.lang.String _iD,
		java.lang.String _name
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetEntitiesDescriptor");
		builder = builder.withParam("IdPMetadata", _idPMetadata);
		builder = builder.withParam("ID", _iD);
		builder = builder.withParam("Name", _name);
		return builder;
	}

	public static saml20.proxies.EntitiesDescriptor m_GetEntitiesDescriptor(
		IContext context,
		saml20.proxies.IdPMetadata _idPMetadata,
		java.lang.String _iD,
		java.lang.String _name
	)
	{
		Object result = m_GetEntitiesDescriptorBuilder(
				_idPMetadata,
				_iD,
				_name
			)
			.execute(context);
		return result == null ? null : saml20.proxies.EntitiesDescriptor.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetIDPSSODescriptorBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetIDPSSODescriptor");
		return builder;
	}

	public static saml20.proxies.RoleDescriptor m_GetIDPSSODescriptor(IContext context)
	{
		Object result = m_GetIDPSSODescriptorBuilder().execute(context);
		return result == null ? null : saml20.proxies.RoleDescriptor.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetManageNameIDServiceBuilder(
		java.lang.String _binding
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetManageNameIDService");
		builder = builder.withParam("Binding", _binding);
		return builder;
	}

	public static saml20.proxies.Endpoint m_GetManageNameIDService(
		IContext context,
		java.lang.String _binding
	)
	{
		Object result = m_GetManageNameIDServiceBuilder(
				_binding
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Endpoint.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetNameIDFormatBuilder(
		java.lang.String _content,
		saml20.proxies.RoleDescriptor _roleDescriptor
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetNameIDFormat");
		builder = builder.withParam("content", _content);
		builder = builder.withParam("RoleDescriptor", _roleDescriptor);
		return builder;
	}

	public static saml20.proxies.NameIDFormat m_GetNameIDFormat(
		IContext context,
		java.lang.String _content,
		saml20.proxies.RoleDescriptor _roleDescriptor
	)
	{
		Object result = m_GetNameIDFormatBuilder(
				_content,
				_roleDescriptor
			)
			.execute(context);
		return result == null ? null : saml20.proxies.NameIDFormat.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetNameIDMappingServiceBuilder(
		java.lang.String _binding
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetNameIDMappingService");
		builder = builder.withParam("Binding", _binding);
		return builder;
	}

	public static saml20.proxies.Endpoint m_GetNameIDMappingService(
		IContext context,
		java.lang.String _binding
	)
	{
		Object result = m_GetNameIDMappingServiceBuilder(
				_binding
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Endpoint.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetSingleLogoutServiceBuilder(
		java.lang.String _binding
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetSingleLogoutService");
		builder = builder.withParam("Binding", _binding);
		return builder;
	}

	public static saml20.proxies.Endpoint m_GetSingleLogoutService(
		IContext context,
		java.lang.String _binding
	)
	{
		Object result = m_GetSingleLogoutServiceBuilder(
				_binding
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Endpoint.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetSingleSignOnServiceBuilder(
		java.lang.String _binding
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetSingleSignOnService");
		builder = builder.withParam("Binding", _binding);
		return builder;
	}

	public static saml20.proxies.Endpoint m_GetSingleSignOnService(
		IContext context,
		java.lang.String _binding
	)
	{
		Object result = m_GetSingleSignOnServiceBuilder(
				_binding
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Endpoint.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_GetSPSSODescriptorBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_GetSPSSODescriptor");
		return builder;
	}

	public static saml20.proxies.RoleDescriptor m_GetSPSSODescriptor(IContext context)
	{
		Object result = m_GetSPSSODescriptorBuilder().execute(context);
		return result == null ? null : saml20.proxies.RoleDescriptor.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder m_PassKeyInfoBuilder(
		saml20.proxies.KeyInfo _xMLMappingParent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.M_PassKeyInfo");
		builder = builder.withParam("XMLMappingParent", _xMLMappingParent);
		return builder;
	}

	public static saml20.proxies.KeyInfo m_PassKeyInfo(
		IContext context,
		saml20.proxies.KeyInfo _xMLMappingParent
	)
	{
		Object result = m_PassKeyInfoBuilder(
				_xMLMappingParent
			)
			.execute(context);
		return result == null ? null : saml20.proxies.KeyInfo.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_DeleteAttributeBuilder(
		saml20.proxies.Attribute _attribute
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_DeleteAttribute");
		builder = builder.withParam("Attribute", _attribute);
		return builder;
	}

	public static void mB_DeleteAttribute(
		IContext context,
		saml20.proxies.Attribute _attribute
	)
	{
		mB_DeleteAttributeBuilder(
				_attribute
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_GetKeyStoreBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_GetKeyStore");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static saml20.proxies.KeyStore mB_GetKeyStore(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = mB_GetKeyStoreBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : saml20.proxies.KeyStore.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_IDP_SelfGenerate_KeyStoreBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_IDP_SelfGenerate_KeyStore");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_IDP_SelfGenerate_KeyStore(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_IDP_SelfGenerate_KeyStoreBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_MigrateToConfiguredSAMLAuthnContextsBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_MigrateToConfiguredSAMLAuthnContexts");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_MigrateToConfiguredSAMLAuthnContexts(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_MigrateToConfiguredSAMLAuthnContextsBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_NewAttributeBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_NewAttribute");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_NewAttribute(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_NewAttributeBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_NewAttribute_ClaimMapBuilder(
		saml20.proxies.ClaimMap _claimMap
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_NewAttribute_ClaimMap");
		builder = builder.withParam("ClaimMap", _claimMap);
		return builder;
	}

	public static void mB_NewAttribute_ClaimMap(
		IContext context,
		saml20.proxies.ClaimMap _claimMap
	)
	{
		mB_NewAttribute_ClaimMapBuilder(
				_claimMap
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_NewConfigurationBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_NewConfiguration");
		return builder;
	}

	public static void mB_NewConfiguration(IContext context)
	{
		mB_NewConfigurationBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_OpenSAMLAuthnContext_SelectBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_OpenSAMLAuthnContext_Select");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_OpenSAMLAuthnContext_Select(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_OpenSAMLAuthnContext_SelectBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_SaveSPMetadataBuilder(
		saml20.proxies.SPMetadata _sPMetadata
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_SaveSPMetadata");
		builder = builder.withParam("SPMetadata", _sPMetadata);
		return builder;
	}

	public static boolean mB_SaveSPMetadata(
		IContext context,
		saml20.proxies.SPMetadata _sPMetadata
	)
	{
		Object result = mB_SaveSPMetadataBuilder(
				_sPMetadata
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_Select_SAMLAuthnContextsBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.util.List<saml20.proxies.SAMLAuthnContext> _sAMLAuthnContextList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_Select_SAMLAuthnContexts");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		builder = builder.withParam("SAMLAuthnContextList", _sAMLAuthnContextList);
		return builder;
	}

	public static void mB_Select_SAMLAuthnContexts(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.util.List<saml20.proxies.SAMLAuthnContext> _sAMLAuthnContextList
	)
	{
		mB_Select_SAMLAuthnContextsBuilder(
				_sSOConfiguration,
				_sAMLAuthnContextList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_SelectAttributeBuilder(
		saml20.proxies.Attribute _attribute,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_SelectAttribute");
		builder = builder.withParam("Attribute", _attribute);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_SelectAttribute(
		IContext context,
		saml20.proxies.Attribute _attribute,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_SelectAttributeBuilder(
				_attribute,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_SelectAttribute_ClaimMapBuilder(
		saml20.proxies.Attribute _attribute,
		saml20.proxies.ClaimMap _claimMap
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_SelectAttribute_ClaimMap");
		builder = builder.withParam("Attribute", _attribute);
		builder = builder.withParam("ClaimMap", _claimMap);
		return builder;
	}

	public static void mB_SelectAttribute_ClaimMap(
		IContext context,
		saml20.proxies.Attribute _attribute,
		saml20.proxies.ClaimMap _claimMap
	)
	{
		mB_SelectAttribute_ClaimMapBuilder(
				_attribute,
				_claimMap
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_SelectEntityDescriptorBuilder(
		saml20.proxies.EntityDescriptor _entityDescriptor,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_SelectEntityDescriptor");
		builder = builder.withParam("EntityDescriptor", _entityDescriptor);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_SelectEntityDescriptor(
		IContext context,
		saml20.proxies.EntityDescriptor _entityDescriptor,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_SelectEntityDescriptorBuilder(
				_entityDescriptor,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_ShowAttributesForConfigBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_ShowAttributesForConfig");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_ShowAttributesForConfig(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_ShowAttributesForConfigBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_ShowAttributesForConfig_ClaimMapBuilder(
		saml20.proxies.ClaimMap _claimMap
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_ShowAttributesForConfig_ClaimMap");
		builder = builder.withParam("ClaimMap", _claimMap);
		return builder;
	}

	public static void mB_ShowAttributesForConfig_ClaimMap(
		IContext context,
		saml20.proxies.ClaimMap _claimMap
	)
	{
		mB_ShowAttributesForConfig_ClaimMapBuilder(
				_claimMap
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_ShowEntityDescriptorsBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_ShowEntityDescriptors");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_ShowEntityDescriptors(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_ShowEntityDescriptorsBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_ShowSelectedEntityDescriptorBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_ShowSelectedEntityDescriptor");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_ShowSelectedEntityDescriptor(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_ShowSelectedEntityDescriptorBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_SPAttributeConsumingServicesBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_SPAttributeConsumingServices");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static boolean mB_SPAttributeConsumingServices(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = mB_SPAttributeConsumingServicesBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_SSOConfiguration_SaveBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_SSOConfiguration_Save");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_SSOConfiguration_Save(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_SSOConfiguration_SaveBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_ToggleActiveBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_ToggleActive");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mB_ToggleActive(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mB_ToggleActiveBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mB_UploadKeyStoreBuilder(
		saml20.proxies.KeyStore _keyStore
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MB_UploadKeyStore");
		builder = builder.withParam("KeyStore", _keyStore);
		return builder;
	}

	public static void mB_UploadKeyStore(
		IContext context,
		saml20.proxies.KeyStore _keyStore
	)
	{
		mB_UploadKeyStoreBuilder(
				_keyStore
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_AvailableAttributesForSSOConfigBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MF_AvailableAttributesForSSOConfig");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static java.util.List<saml20.proxies.Attribute> mF_AvailableAttributesForSSOConfig(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = mF_AvailableAttributesForSSOConfigBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> saml20.proxies.Attribute.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_AvailableAttributesForSSOConfigByClaimMapBuilder(
		saml20.proxies.ClaimMap _claimMap
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MF_AvailableAttributesForSSOConfigByClaimMap");
		builder = builder.withParam("ClaimMap", _claimMap);
		return builder;
	}

	public static java.util.List<saml20.proxies.Attribute> mF_AvailableAttributesForSSOConfigByClaimMap(
		IContext context,
		saml20.proxies.ClaimMap _claimMap
	)
	{
		Object result = mF_AvailableAttributesForSSOConfigByClaimMapBuilder(
				_claimMap
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> saml20.proxies.Attribute.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_CreateConfiguredSAMLAuthnContextBuilder(
		saml20.proxies.SAMLAuthnContext _sAMLAuthnContext,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MF_CreateConfiguredSAMLAuthnContext");
		builder = builder.withParam("SAMLAuthnContext", _sAMLAuthnContext);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static saml20.proxies.ConfiguredSAMLAuthnContext mF_CreateConfiguredSAMLAuthnContext(
		IContext context,
		saml20.proxies.SAMLAuthnContext _sAMLAuthnContext,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = mF_CreateConfiguredSAMLAuthnContextBuilder(
				_sAMLAuthnContext,
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : saml20.proxies.ConfiguredSAMLAuthnContext.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_CreateConfiguredSAMLAuthnContext_FromListBuilder(
		java.util.List<saml20.proxies.SAMLAuthnContext> _sAMLAuthnContextList,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MF_CreateConfiguredSAMLAuthnContext_FromList");
		builder = builder.withParam("SAMLAuthnContextList", _sAMLAuthnContextList);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void mF_CreateConfiguredSAMLAuthnContext_FromList(
		IContext context,
		java.util.List<saml20.proxies.SAMLAuthnContext> _sAMLAuthnContextList,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		mF_CreateConfiguredSAMLAuthnContext_FromListBuilder(
				_sAMLAuthnContextList,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mG_CreateClaimBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.lang.String _name,
		java.lang.String _friendlyName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MG_CreateClaim");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		builder = builder.withParam("Name", _name);
		builder = builder.withParam("FriendlyName", _friendlyName);
		return builder;
	}

	public static void mG_CreateClaim(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.lang.String _name,
		java.lang.String _friendlyName
	)
	{
		mG_CreateClaimBuilder(
				_sSOConfiguration,
				_name,
				_friendlyName
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mG_CreateUseClaimIdClaimBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MG_CreateUseClaimIdClaim");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static usercommons.proxies.Claim mG_CreateUseClaimIdClaim(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = mG_CreateUseClaimIdClaimBuilder(
				_userProvisioning
			)
			.execute(context);
		return result == null ? null : usercommons.proxies.Claim.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mG_GetUserProvisioningBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MG_GetUserProvisioning");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static usercommons.proxies.UserProvisioning mG_GetUserProvisioning(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = mG_GetUserProvisioningBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : usercommons.proxies.UserProvisioning.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder migrateIDPEncryptionSettingBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MigrateIDPEncryptionSetting");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static saml20.proxies.SSOConfiguration migrateIDPEncryptionSetting(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = migrateIDPEncryptionSettingBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : saml20.proxies.SSOConfiguration.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder migrateKeyStoreDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.MigrateKeyStoreData");
		return builder;
	}

	public static void migrateKeyStoreData(IContext context)
	{
		migrateKeyStoreDataBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oC_RefreshAttributesBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.OC_RefreshAttributes");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void oC_RefreshAttributes(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		oC_RefreshAttributesBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCh_SSOConfigUserEntityBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.OCh_SSOConfigUserEntity");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void oCh_SSOConfigUserEntity(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		oCh_SSOConfigUserEntityBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openConfigurationBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.OpenConfiguration");
		return builder;
	}

	public static void openConfiguration(IContext context)
	{
		openConfigurationBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openPreviousFormBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.OpenPreviousForm");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static saml20.proxies.WizardStepCollection openPreviousForm(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = openPreviousFormBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : saml20.proxies.WizardStepCollection.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder prepareInCommonAttributesBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.PrepareInCommonAttributes");
		return builder;
	}

	public static void prepareInCommonAttributes(IContext context)
	{
		prepareInCommonAttributesBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder refreshApplicationRootURLBuilder(
		saml20.proxies.SPMetadata _sPMetadata
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.RefreshApplicationRootURL");
		builder = builder.withParam("SPMetadata", _sPMetadata);
		return builder;
	}

	public static void refreshApplicationRootURL(
		IContext context,
		saml20.proxies.SPMetadata _sPMetadata
	)
	{
		refreshApplicationRootURLBuilder(
				_sPMetadata
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder requestResponse_OverviewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.RequestResponse_Overview");
		return builder;
	}

	public static void requestResponse_Overview(IContext context)
	{
		requestResponse_OverviewBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder resetConfigurationBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.ResetConfiguration");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void resetConfiguration(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		resetConfigurationBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder retrieveIdPMetadataBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.RetrieveIdPMetadata");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static saml20.proxies.IdPMetadata retrieveIdPMetadata(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = retrieveIdPMetadataBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : saml20.proxies.IdPMetadata.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sE_LogCleanUpBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SE_LogCleanUp");
		return builder;
	}

	public static void sE_LogCleanUp(IContext context)
	{
		sE_LogCleanUpBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sE_Sync_IDPMetadataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SE_Sync_IDPMetadata");
		return builder;
	}

	public static void sE_Sync_IDPMetadata(IContext context)
	{
		sE_Sync_IDPMetadataBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder setBindingTypeBuilder(
		java.lang.String _binding,
		saml20.proxies.Endpoint _endpoint
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SetBindingType");
		builder = builder.withParam("Binding", _binding);
		builder = builder.withParam("Endpoint", _endpoint);
		return builder;
	}

	public static void setBindingType(
		IContext context,
		java.lang.String _binding,
		saml20.proxies.Endpoint _endpoint
	)
	{
		setBindingTypeBuilder(
				_binding,
				_endpoint
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sPMetadata_ValidateBuilder(
		saml20.proxies.SPMetadata _sPMetadata
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SPMetadata_Validate");
		builder = builder.withParam("SPMetadata", _sPMetadata);
		return builder;
	}

	public static boolean sPMetadata_Validate(
		IContext context,
		saml20.proxies.SPMetadata _sPMetadata
	)
	{
		Object result = sPMetadata_ValidateBuilder(
				_sPMetadata
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfig_FinishedBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfig_Finished");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfig_Finished(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfig_FinishedBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfig_ToStep1Builder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfig_ToStep1");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfig_ToStep1(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfig_ToStep1Builder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfig_ToStep2Builder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfig_ToStep2");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfig_ToStep2(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfig_ToStep2Builder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfig_ToStep3Builder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfig_ToStep3");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfig_ToStep3(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfig_ToStep3Builder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfig_ToStep4Builder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfig_ToStep4");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfig_ToStep4(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfig_ToStep4Builder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfig_ToStep5Builder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfig_ToStep5");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfig_ToStep5(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfig_ToStep5Builder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfig_ToStep6Builder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfig_ToStep6");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfig_ToStep6(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfig_ToStep6Builder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfig_ToStep7Builder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfig_ToStep7");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfig_ToStep7(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfig_ToStep7Builder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfig_ToStepBackBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfig_ToStepBack");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfig_ToStepBack(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfig_ToStepBackBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfiguration_ExportMetadataBuilder(
		saml20.proxies.SSOConfiguration _sSOMetadata
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfiguration_ExportMetadata");
		builder = builder.withParam("SSOMetadata", _sSOMetadata);
		return builder;
	}

	public static void sSOConfiguration_ExportMetadata(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOMetadata
	)
	{
		sSOConfiguration_ExportMetadataBuilder(
				_sSOMetadata
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sSOConfigurationReloadConfig_ADeBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SSOConfigurationReloadConfig_ADe");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sSOConfigurationReloadConfig_ADe(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sSOConfigurationReloadConfig_ADeBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder startupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.Startup");
		return builder;
	}

	public static boolean startup(IContext context)
	{
		Object result = startupBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_FindCliamBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning,
		java.lang.String _name
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_FindCliam");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		builder = builder.withParam("Name", _name);
		return builder;
	}

	public static usercommons.proxies.Claim sUB_FindCliam(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning,
		java.lang.String _name
	)
	{
		Object result = sUB_FindCliamBuilder(
				_userProvisioning,
				_name
			)
			.execute(context);
		return result == null ? null : usercommons.proxies.Claim.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Get_AuthenticationContextComparisonBuilder(
		java.lang.String _authenticationContextComparison
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Get_AuthenticationContextComparison");
		builder = builder.withParam("AuthenticationContextComparison", _authenticationContextComparison);
		return builder;
	}

	public static saml20.proxies.TypeOfAuthnContext sUB_Get_AuthenticationContextComparison(
		IContext context,
		java.lang.String _authenticationContextComparison
	)
	{
		Object result = sUB_Get_AuthenticationContextComparisonBuilder(
				_authenticationContextComparison
			)
			.execute(context);
		return result == null ? null : saml20.proxies.TypeOfAuthnContext.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Get_EncryptionKeyLengthBuilder(
		java.lang.String _encryptionKeyLength
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Get_EncryptionKeyLength");
		builder = builder.withParam("EncryptionKeyLength", _encryptionKeyLength);
		return builder;
	}

	public static saml20.proxies.EncryptionKeyLength sUB_Get_EncryptionKeyLength(
		IContext context,
		java.lang.String _encryptionKeyLength
	)
	{
		Object result = sUB_Get_EncryptionKeyLengthBuilder(
				_encryptionKeyLength
			)
			.execute(context);
		return result == null ? null : saml20.proxies.EncryptionKeyLength.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Get_EncryptionMethodBuilder(
		java.lang.String _encryptionMethod
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Get_EncryptionMethod");
		builder = builder.withParam("EncryptionMethod", _encryptionMethod);
		return builder;
	}

	public static saml20.proxies.EncryptionMethod sUB_Get_EncryptionMethod(
		IContext context,
		java.lang.String _encryptionMethod
	)
	{
		Object result = sUB_Get_EncryptionMethodBuilder(
				_encryptionMethod
			)
			.execute(context);
		return result == null ? null : saml20.proxies.EncryptionMethod.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Get_ResponseProtocolBindingBuilder(
		java.lang.String _responseProtocolBinding
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Get_ResponseProtocolBinding");
		builder = builder.withParam("ResponseProtocolBinding", _responseProtocolBinding);
		return builder;
	}

	public static saml20.proxies.Enum_ProtocolBinding sUB_Get_ResponseProtocolBinding(
		IContext context,
		java.lang.String _responseProtocolBinding
	)
	{
		Object result = sUB_Get_ResponseProtocolBindingBuilder(
				_responseProtocolBinding
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Enum_ProtocolBinding.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Get_UseAssertionConsumerServiceConceptBuilder(
		java.lang.String _useAssertionConsumerServiceConcept
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Get_UseAssertionConsumerServiceConcept");
		builder = builder.withParam("UseAssertionConsumerServiceConcept", _useAssertionConsumerServiceConcept);
		return builder;
	}

	public static saml20.proxies.Enum_AssertionConsumerServiceIndex sUB_Get_UseAssertionConsumerServiceConcept(
		IContext context,
		java.lang.String _useAssertionConsumerServiceConcept
	)
	{
		Object result = sUB_Get_UseAssertionConsumerServiceConceptBuilder(
				_useAssertionConsumerServiceConcept
			)
			.execute(context);
		return result == null ? null : saml20.proxies.Enum_AssertionConsumerServiceIndex.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_GetNameIDFormatBuilder(
		java.lang.String _nameID
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_GetNameIDFormat");
		builder = builder.withParam("NameID", _nameID);
		return builder;
	}

	public static saml20.proxies.NameIDFormat sUB_GetNameIDFormat(
		IContext context,
		java.lang.String _nameID
	)
	{
		Object result = sUB_GetNameIDFormatBuilder(
				_nameID
			)
			.execute(context);
		return result == null ? null : saml20.proxies.NameIDFormat.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Handle_SSOConfigurationBuilder(
		saml20.proxies.Dep_IdPConfiguration _iDPConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Handle_SSOConfiguration");
		builder = builder.withParam("IDPConfiguration", _iDPConfiguration);
		return builder;
	}

	public static boolean sUB_Handle_SSOConfiguration(
		IContext context,
		saml20.proxies.Dep_IdPConfiguration _iDPConfiguration
	)
	{
		Object result = sUB_Handle_SSOConfigurationBuilder(
				_iDPConfiguration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_HandleACServiceAttributeBuilder(
		java.util.List<saml20.proxies.Dep_SPAttribute> _sPAttributeList,
		saml20.proxies.SPAttributeConsumingService _sPAttributeConsumingService
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_HandleACServiceAttribute");
		builder = builder.withParam("SPAttributeList", _sPAttributeList);
		builder = builder.withParam("SPAttributeConsumingService", _sPAttributeConsumingService);
		return builder;
	}

	public static void sUB_HandleACServiceAttribute(
		IContext context,
		java.util.List<saml20.proxies.Dep_SPAttribute> _sPAttributeList,
		saml20.proxies.SPAttributeConsumingService _sPAttributeConsumingService
	)
	{
		sUB_HandleACServiceAttributeBuilder(
				_sPAttributeList,
				_sPAttributeConsumingService
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_HandleAttributeConsumingServiceBuilder(
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_HandleAttributeConsumingService");
		builder = builder.withParam("IdPConfiguration", _idPConfiguration);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sUB_HandleAttributeConsumingService(
		IContext context,
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sUB_HandleAttributeConsumingServiceBuilder(
				_idPConfiguration,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Migrate_Atrribute_To_UserCommons_ClaimsBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Migrate_Atrribute_To_UserCommons_Claims");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static void sUB_Migrate_Atrribute_To_UserCommons_Claims(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		sUB_Migrate_Atrribute_To_UserCommons_ClaimsBuilder(
				_sSOConfiguration,
				_userProvisioning
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Migrate_PrincipalAttributeBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Migrate_PrincipalAttribute");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sUB_Migrate_PrincipalAttribute(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sUB_Migrate_PrincipalAttributeBuilder(
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Migrate_Provisioning_To_UserCommonsProvisioningBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Migrate_Provisioning_To_UserCommonsProvisioning");
		return builder;
	}

	public static void sUB_Migrate_Provisioning_To_UserCommonsProvisioning(IContext context)
	{
		sUB_Migrate_Provisioning_To_UserCommonsProvisioningBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Migrate_UserProvisioningBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_Migrate_UserProvisioning");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static usercommons.proxies.UserProvisioning sUB_Migrate_UserProvisioning(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = sUB_Migrate_UserProvisioningBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return result == null ? null : usercommons.proxies.UserProvisioning.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_PrepareInCommonAttributesBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_PrepareInCommonAttributes");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static void sUB_PrepareInCommonAttributes(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		sUB_PrepareInCommonAttributesBuilder(
				_userProvisioning
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UpdateAuthenticationContextBuilder(
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_UpdateAuthenticationContext");
		builder = builder.withParam("IdPConfiguration", _idPConfiguration);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sUB_UpdateAuthenticationContext(
		IContext context,
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sUB_UpdateAuthenticationContextBuilder(
				_idPConfiguration,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UpdateAuthnContextClassesBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.util.List<saml20.proxies.Dep_SAMLAuthnContext> _authnContextList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_UpdateAuthnContextClasses");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		builder = builder.withParam("AuthnContextList", _authnContextList);
		return builder;
	}

	public static void sUB_UpdateAuthnContextClasses(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.util.List<saml20.proxies.Dep_SAMLAuthnContext> _authnContextList
	)
	{
		sUB_UpdateAuthnContextClassesBuilder(
				_sSOConfiguration,
				_authnContextList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UpdateEncryptionSettingsBuilder(
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_UpdateEncryptionSettings");
		builder = builder.withParam("IdPConfiguration", _idPConfiguration);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sUB_UpdateEncryptionSettings(
		IContext context,
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sUB_UpdateEncryptionSettingsBuilder(
				_idPConfiguration,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UpdateIdPAttributeEntityAttributeMappingBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning,
		java.util.List<saml20.proxies.Dep_IdpAttributeEntityAttributeMapping> _idpAttributeEntityAttributeMappingList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_UpdateIdPAttributeEntityAttributeMapping");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		builder = builder.withParam("IdpAttributeEntityAttributeMappingList", _idpAttributeEntityAttributeMappingList);
		return builder;
	}

	public static void sUB_UpdateIdPAttributeEntityAttributeMapping(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning,
		java.util.List<saml20.proxies.Dep_IdpAttributeEntityAttributeMapping> _idpAttributeEntityAttributeMappingList
	)
	{
		sUB_UpdateIdPAttributeEntityAttributeMappingBuilder(
				_userProvisioning,
				_idpAttributeEntityAttributeMappingList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UpdateIdPConfigurationBuilder(
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_UpdateIdPConfiguration");
		builder = builder.withParam("IdPConfiguration", _idPConfiguration);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sUB_UpdateIdPConfiguration(
		IContext context,
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sUB_UpdateIdPConfigurationBuilder(
				_idPConfiguration,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UpdatePreferedEntityDescriptorBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.lang.String _preferredEntityDescriptor
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_UpdatePreferedEntityDescriptor");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		builder = builder.withParam("PreferredEntityDescriptor", _preferredEntityDescriptor);
		return builder;
	}

	public static void sUB_UpdatePreferedEntityDescriptor(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration,
		java.lang.String _preferredEntityDescriptor
	)
	{
		sUB_UpdatePreferedEntityDescriptorBuilder(
				_sSOConfiguration,
				_preferredEntityDescriptor
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UpdateSSOConfigurationBuilder(
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_UpdateSSOConfiguration");
		builder = builder.withParam("IdPConfiguration", _idPConfiguration);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sUB_UpdateSSOConfiguration(
		IContext context,
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sUB_UpdateSSOConfigurationBuilder(
				_idPConfiguration,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UpdateUserProvisioningBuilder(
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.SUB_UpdateUserProvisioning");
		builder = builder.withParam("IdPConfiguration", _idPConfiguration);
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static void sUB_UpdateUserProvisioning(
		IContext context,
		saml20.proxies.Dep_IdPConfiguration _idPConfiguration,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		sUB_UpdateUserProvisioningBuilder(
				_idPConfiguration,
				_sSOConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder update_UserProvisioningBuilder(
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.Update_UserProvisioning");
		builder = builder.withParam("SSOConfiguration", _sSOConfiguration);
		return builder;
	}

	public static boolean update_UserProvisioning(
		IContext context,
		saml20.proxies.SSOConfiguration _sSOConfiguration
	)
	{
		Object result = update_UserProvisioningBuilder(
				_sSOConfiguration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_SP_MetadataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.VAL_SP_Metadata");
		return builder;
	}

	public static boolean vAL_SP_Metadata(IContext context)
	{
		Object result = vAL_SP_MetadataBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_SSO_MetadataBuilder(
		java.lang.String _alias,
		java.lang.String _idPURL
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SAML20.VAL_SSO_Metadata");
		builder = builder.withParam("Alias", _alias);
		builder = builder.withParam("IdPURL", _idPURL);
		return builder;
	}

	public static boolean vAL_SSO_Metadata(
		IContext context,
		java.lang.String _alias,
		java.lang.String _idPURL
	)
	{
		Object result = vAL_SSO_MetadataBuilder(
				_alias,
				_idPURL
			)
			.execute(context);
		return (boolean) result;
	}
}
