// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package excr_mfgordermanagement.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import java.nio.charset.Charset;
import java.util.Base64;
import org.apache.pdfbox.util.Hex;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_ConvertHexatoBase64String extends UserAction<java.lang.String>
{
	private final java.lang.String Hexa;

	public JA_ConvertHexatoBase64String(
		IContext context,
		java.lang.String _hexa
	)
	{
		super(context);
		this.Hexa = _hexa;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String originalInput = this.Hexa;
		if (originalInput.startsWith("0x")) {
			originalInput = originalInput.substring(2);
		  }
		byte[] bytesEncoded = Base64.getEncoder().encode(originalInput.getBytes());
		String encodedStr = (new String(bytesEncoded,Charset.forName("ISO-8859-1")));
		//String encodedString = 
				  //Base64.getMimeEncoder().encodeToString(originalInput.getBytes());
	         return encodedStr;

	   

	   
	
		//byte[] decodedHex = Hex.decodeHex(this.Hexa);
		//byte[] encodedHexB64 = Base64.getEncoder().encode(decodedHex);
		//System.out.println("converted value is " +encodedHexB64.toString());
		//return encodedHexB64.toString();
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		//byte[] b  = Base64.getEncoder().encode(this.Hexa.getBytes());
		//return b.toString();
		
		    
		
		
		 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ConvertHexatoBase64String";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
