// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public class AdjustReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject adjustReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement.AdjustReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Quantity("Quantity"),
		isValid("isValid"),
		AdjustReason_ContainerChangeQtyContext("EXCR_ResourceManagement.AdjustReason_ContainerChangeQtyContext"),
		ResAdjustReason_AdjustReason("EXCR_ContainerManagement_API.ResAdjustReason_AdjustReason");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AdjustReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AdjustReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject adjustReasonMendixObject)
	{
		if (adjustReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!adjustReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.adjustReasonMendixObject = adjustReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement.proxies.AdjustReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement.proxies.AdjustReason(context, mendixObject);
	}

	public static excr_resourcemanagement.proxies.AdjustReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement.proxies.AdjustReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.String getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.String getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.String quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of isValid
	 */
	public final java.lang.Boolean getisValid()
	{
		return getisValid(getContext());
	}

	/**
	 * @param context
	 * @return value of isValid
	 */
	public final java.lang.Boolean getisValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isValid.toString());
	}

	/**
	 * Set value of isValid
	 * @param isvalid
	 */
	public final void setisValid(java.lang.Boolean isvalid)
	{
		setisValid(getContext(), isvalid);
	}

	/**
	 * Set value of isValid
	 * @param context
	 * @param isvalid
	 */
	public final void setisValid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvalid)
	{
		getMendixObject().setValue(context, MemberNames.isValid.toString(), isvalid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AdjustReason_ContainerChangeQtyContext
	 */
	public final excr_resourcemanagement.proxies.ContainerChangeQtyContext getAdjustReason_ContainerChangeQtyContext() throws com.mendix.core.CoreException
	{
		return getAdjustReason_ContainerChangeQtyContext(getContext());
	}

	/**
	 * @param context
	 * @return value of AdjustReason_ContainerChangeQtyContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ContainerChangeQtyContext getAdjustReason_ContainerChangeQtyContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ContainerChangeQtyContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AdjustReason_ContainerChangeQtyContext.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ContainerChangeQtyContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AdjustReason_ContainerChangeQtyContext
	 * @param adjustreason_containerchangeqtycontext
	 */
	public final void setAdjustReason_ContainerChangeQtyContext(excr_resourcemanagement.proxies.ContainerChangeQtyContext adjustreason_containerchangeqtycontext)
	{
		setAdjustReason_ContainerChangeQtyContext(getContext(), adjustreason_containerchangeqtycontext);
	}

	/**
	 * Set value of AdjustReason_ContainerChangeQtyContext
	 * @param context
	 * @param adjustreason_containerchangeqtycontext
	 */
	public final void setAdjustReason_ContainerChangeQtyContext(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ContainerChangeQtyContext adjustreason_containerchangeqtycontext)
	{
		if (adjustreason_containerchangeqtycontext == null) {
			getMendixObject().setValue(context, MemberNames.AdjustReason_ContainerChangeQtyContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AdjustReason_ContainerChangeQtyContext.toString(), adjustreason_containerchangeqtycontext.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResAdjustReason_AdjustReason
	 */
	public final excr_containermanagement_api.proxies.ResAdjustReason getResAdjustReason_AdjustReason() throws com.mendix.core.CoreException
	{
		return getResAdjustReason_AdjustReason(getContext());
	}

	/**
	 * @param context
	 * @return value of ResAdjustReason_AdjustReason
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_containermanagement_api.proxies.ResAdjustReason getResAdjustReason_AdjustReason(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_containermanagement_api.proxies.ResAdjustReason result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResAdjustReason_AdjustReason.toString());
		if (identifier != null) {
			result = excr_containermanagement_api.proxies.ResAdjustReason.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResAdjustReason_AdjustReason
	 * @param resadjustreason_adjustreason
	 */
	public final void setResAdjustReason_AdjustReason(excr_containermanagement_api.proxies.ResAdjustReason resadjustreason_adjustreason)
	{
		setResAdjustReason_AdjustReason(getContext(), resadjustreason_adjustreason);
	}

	/**
	 * Set value of ResAdjustReason_AdjustReason
	 * @param context
	 * @param resadjustreason_adjustreason
	 */
	public final void setResAdjustReason_AdjustReason(com.mendix.systemwideinterfaces.core.IContext context, excr_containermanagement_api.proxies.ResAdjustReason resadjustreason_adjustreason)
	{
		if (resadjustreason_adjustreason == null) {
			getMendixObject().setValue(context, MemberNames.ResAdjustReason_AdjustReason.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResAdjustReason_AdjustReason.toString(), resadjustreason_adjustreason.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return adjustReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement.proxies.AdjustReason that = (excr_resourcemanagement.proxies.AdjustReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
