// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public class ComponentIssueContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject componentIssueContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement.ComponentIssueContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AutoIssue("AutoIssue"),
		HideSatisfiedRequirements("HideSatisfiedRequirements"),
		IsSubmitDisabled("IsSubmitDisabled"),
		ScanContainer("ScanContainer"),
		ScanContainerQR("ScanContainerQR"),
		Container_ComponentIssueContext("EXCR_ResourceManagement.Container_ComponentIssueContext"),
		EProcedureContext_ComponentIssueContext("EXCR_EProcedure.EProcedureContext_ComponentIssueContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ComponentIssueContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ComponentIssueContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject componentIssueContextMendixObject)
	{
		if (componentIssueContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!componentIssueContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.componentIssueContextMendixObject = componentIssueContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement.proxies.ComponentIssueContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement.proxies.ComponentIssueContext(context, mendixObject);
	}

	public static excr_resourcemanagement.proxies.ComponentIssueContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement.proxies.ComponentIssueContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of AutoIssue
	 */
	public final java.lang.Boolean getAutoIssue()
	{
		return getAutoIssue(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoIssue
	 */
	public final java.lang.Boolean getAutoIssue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AutoIssue.toString());
	}

	/**
	 * Set value of AutoIssue
	 * @param autoissue
	 */
	public final void setAutoIssue(java.lang.Boolean autoissue)
	{
		setAutoIssue(getContext(), autoissue);
	}

	/**
	 * Set value of AutoIssue
	 * @param context
	 * @param autoissue
	 */
	public final void setAutoIssue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean autoissue)
	{
		getMendixObject().setValue(context, MemberNames.AutoIssue.toString(), autoissue);
	}

	/**
	 * @return value of HideSatisfiedRequirements
	 */
	public final java.lang.Boolean getHideSatisfiedRequirements()
	{
		return getHideSatisfiedRequirements(getContext());
	}

	/**
	 * @param context
	 * @return value of HideSatisfiedRequirements
	 */
	public final java.lang.Boolean getHideSatisfiedRequirements(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HideSatisfiedRequirements.toString());
	}

	/**
	 * Set value of HideSatisfiedRequirements
	 * @param hidesatisfiedrequirements
	 */
	public final void setHideSatisfiedRequirements(java.lang.Boolean hidesatisfiedrequirements)
	{
		setHideSatisfiedRequirements(getContext(), hidesatisfiedrequirements);
	}

	/**
	 * Set value of HideSatisfiedRequirements
	 * @param context
	 * @param hidesatisfiedrequirements
	 */
	public final void setHideSatisfiedRequirements(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hidesatisfiedrequirements)
	{
		getMendixObject().setValue(context, MemberNames.HideSatisfiedRequirements.toString(), hidesatisfiedrequirements);
	}

	/**
	 * @return value of IsSubmitDisabled
	 */
	public final java.lang.Boolean getIsSubmitDisabled()
	{
		return getIsSubmitDisabled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSubmitDisabled
	 */
	public final java.lang.Boolean getIsSubmitDisabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSubmitDisabled.toString());
	}

	/**
	 * Set value of IsSubmitDisabled
	 * @param issubmitdisabled
	 */
	public final void setIsSubmitDisabled(java.lang.Boolean issubmitdisabled)
	{
		setIsSubmitDisabled(getContext(), issubmitdisabled);
	}

	/**
	 * Set value of IsSubmitDisabled
	 * @param context
	 * @param issubmitdisabled
	 */
	public final void setIsSubmitDisabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean issubmitdisabled)
	{
		getMendixObject().setValue(context, MemberNames.IsSubmitDisabled.toString(), issubmitdisabled);
	}

	/**
	 * @return value of ScanContainer
	 */
	public final java.lang.String getScanContainer()
	{
		return getScanContainer(getContext());
	}

	/**
	 * @param context
	 * @return value of ScanContainer
	 */
	public final java.lang.String getScanContainer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ScanContainer.toString());
	}

	/**
	 * Set value of ScanContainer
	 * @param scancontainer
	 */
	public final void setScanContainer(java.lang.String scancontainer)
	{
		setScanContainer(getContext(), scancontainer);
	}

	/**
	 * Set value of ScanContainer
	 * @param context
	 * @param scancontainer
	 */
	public final void setScanContainer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scancontainer)
	{
		getMendixObject().setValue(context, MemberNames.ScanContainer.toString(), scancontainer);
	}

	/**
	 * @return value of ScanContainerQR
	 */
	public final java.lang.Boolean getScanContainerQR()
	{
		return getScanContainerQR(getContext());
	}

	/**
	 * @param context
	 * @return value of ScanContainerQR
	 */
	public final java.lang.Boolean getScanContainerQR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ScanContainerQR.toString());
	}

	/**
	 * Set value of ScanContainerQR
	 * @param scancontainerqr
	 */
	public final void setScanContainerQR(java.lang.Boolean scancontainerqr)
	{
		setScanContainerQR(getContext(), scancontainerqr);
	}

	/**
	 * Set value of ScanContainerQR
	 * @param context
	 * @param scancontainerqr
	 */
	public final void setScanContainerQR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean scancontainerqr)
	{
		getMendixObject().setValue(context, MemberNames.ScanContainerQR.toString(), scancontainerqr);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Container_ComponentIssueContext
	 */
	public final excr_resourcemanagement.proxies.Container getContainer_ComponentIssueContext() throws com.mendix.core.CoreException
	{
		return getContainer_ComponentIssueContext(getContext());
	}

	/**
	 * @param context
	 * @return value of Container_ComponentIssueContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.Container getContainer_ComponentIssueContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.Container result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Container_ComponentIssueContext.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.Container.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Container_ComponentIssueContext
	 * @param container_componentissuecontext
	 */
	public final void setContainer_ComponentIssueContext(excr_resourcemanagement.proxies.Container container_componentissuecontext)
	{
		setContainer_ComponentIssueContext(getContext(), container_componentissuecontext);
	}

	/**
	 * Set value of Container_ComponentIssueContext
	 * @param context
	 * @param container_componentissuecontext
	 */
	public final void setContainer_ComponentIssueContext(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.Container container_componentissuecontext)
	{
		if (container_componentissuecontext == null) {
			getMendixObject().setValue(context, MemberNames.Container_ComponentIssueContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Container_ComponentIssueContext.toString(), container_componentissuecontext.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EProcedureContext_ComponentIssueContext
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ComponentIssueContext() throws com.mendix.core.CoreException
	{
		return getEProcedureContext_ComponentIssueContext(getContext());
	}

	/**
	 * @param context
	 * @return value of EProcedureContext_ComponentIssueContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ComponentIssueContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure.proxies.EProcedureContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EProcedureContext_ComponentIssueContext.toString());
		if (identifier != null) {
			result = excr_eprocedure.proxies.EProcedureContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EProcedureContext_ComponentIssueContext
	 * @param eprocedurecontext_componentissuecontext
	 */
	public final void setEProcedureContext_ComponentIssueContext(excr_eprocedure.proxies.EProcedureContext eprocedurecontext_componentissuecontext)
	{
		setEProcedureContext_ComponentIssueContext(getContext(), eprocedurecontext_componentissuecontext);
	}

	/**
	 * Set value of EProcedureContext_ComponentIssueContext
	 * @param context
	 * @param eprocedurecontext_componentissuecontext
	 */
	public final void setEProcedureContext_ComponentIssueContext(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure.proxies.EProcedureContext eprocedurecontext_componentissuecontext)
	{
		if (eprocedurecontext_componentissuecontext == null) {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ComponentIssueContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ComponentIssueContext.toString(), eprocedurecontext_componentissuecontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return componentIssueContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement.proxies.ComponentIssueContext that = (excr_resourcemanagement.proxies.ComponentIssueContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
