// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public class ContainerCollectDataContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject containerCollectDataContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement.ContainerCollectDataContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EnteredAmount("EnteredAmount"),
		RowCount("RowCount"),
		Comments("Comments"),
		IsCommentsFieldVisible("IsCommentsFieldVisible"),
		RequestBody("RequestBody"),
		ContainerName("ContainerName"),
		DataCollectionName("DataCollectionName"),
		IsSubmitBtnEnabled("IsSubmitBtnEnabled"),
		DataPointLayout("DataPointLayout"),
		Revision("Revision"),
		isParentDataCollection("isParentDataCollection"),
		isROR("isROR"),
		Workstation("Workstation"),
		WorkstationCount("WorkstationCount"),
		IsReset("IsReset"),
		IsSingleDataCollection("IsSingleDataCollection"),
		ZoomScale("ZoomScale"),
		EProcedureContext_ContainerCollectDataContext("EXCR_EProcedure.EProcedureContext_ContainerCollectDataContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ContainerCollectDataContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ContainerCollectDataContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject containerCollectDataContextMendixObject)
	{
		if (containerCollectDataContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!containerCollectDataContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.containerCollectDataContextMendixObject = containerCollectDataContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement.proxies.ContainerCollectDataContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement.proxies.ContainerCollectDataContext(context, mendixObject);
	}

	public static excr_resourcemanagement.proxies.ContainerCollectDataContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement.proxies.ContainerCollectDataContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of EnteredAmount
	 */
	public final java.lang.String getEnteredAmount()
	{
		return getEnteredAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of EnteredAmount
	 */
	public final java.lang.String getEnteredAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EnteredAmount.toString());
	}

	/**
	 * Set value of EnteredAmount
	 * @param enteredamount
	 */
	public final void setEnteredAmount(java.lang.String enteredamount)
	{
		setEnteredAmount(getContext(), enteredamount);
	}

	/**
	 * Set value of EnteredAmount
	 * @param context
	 * @param enteredamount
	 */
	public final void setEnteredAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String enteredamount)
	{
		getMendixObject().setValue(context, MemberNames.EnteredAmount.toString(), enteredamount);
	}

	/**
	 * @return value of RowCount
	 */
	public final java.lang.Integer getRowCount()
	{
		return getRowCount(getContext());
	}

	/**
	 * @param context
	 * @return value of RowCount
	 */
	public final java.lang.Integer getRowCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RowCount.toString());
	}

	/**
	 * Set value of RowCount
	 * @param rowcount
	 */
	public final void setRowCount(java.lang.Integer rowcount)
	{
		setRowCount(getContext(), rowcount);
	}

	/**
	 * Set value of RowCount
	 * @param context
	 * @param rowcount
	 */
	public final void setRowCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rowcount)
	{
		getMendixObject().setValue(context, MemberNames.RowCount.toString(), rowcount);
	}

	/**
	 * @return value of Comments
	 */
	public final java.lang.String getComments()
	{
		return getComments(getContext());
	}

	/**
	 * @param context
	 * @return value of Comments
	 */
	public final java.lang.String getComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comments.toString());
	}

	/**
	 * Set value of Comments
	 * @param comments
	 */
	public final void setComments(java.lang.String comments)
	{
		setComments(getContext(), comments);
	}

	/**
	 * Set value of Comments
	 * @param context
	 * @param comments
	 */
	public final void setComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comments)
	{
		getMendixObject().setValue(context, MemberNames.Comments.toString(), comments);
	}

	/**
	 * @return value of IsCommentsFieldVisible
	 */
	public final java.lang.Boolean getIsCommentsFieldVisible()
	{
		return getIsCommentsFieldVisible(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCommentsFieldVisible
	 */
	public final java.lang.Boolean getIsCommentsFieldVisible(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCommentsFieldVisible.toString());
	}

	/**
	 * Set value of IsCommentsFieldVisible
	 * @param iscommentsfieldvisible
	 */
	public final void setIsCommentsFieldVisible(java.lang.Boolean iscommentsfieldvisible)
	{
		setIsCommentsFieldVisible(getContext(), iscommentsfieldvisible);
	}

	/**
	 * Set value of IsCommentsFieldVisible
	 * @param context
	 * @param iscommentsfieldvisible
	 */
	public final void setIsCommentsFieldVisible(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscommentsfieldvisible)
	{
		getMendixObject().setValue(context, MemberNames.IsCommentsFieldVisible.toString(), iscommentsfieldvisible);
	}

	/**
	 * @return value of RequestBody
	 */
	public final java.lang.String getRequestBody()
	{
		return getRequestBody(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestBody
	 */
	public final java.lang.String getRequestBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestBody.toString());
	}

	/**
	 * Set value of RequestBody
	 * @param requestbody
	 */
	public final void setRequestBody(java.lang.String requestbody)
	{
		setRequestBody(getContext(), requestbody);
	}

	/**
	 * Set value of RequestBody
	 * @param context
	 * @param requestbody
	 */
	public final void setRequestBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestbody)
	{
		getMendixObject().setValue(context, MemberNames.RequestBody.toString(), requestbody);
	}

	/**
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName()
	{
		return getContainerName(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContainerName.toString());
	}

	/**
	 * Set value of ContainerName
	 * @param containername
	 */
	public final void setContainerName(java.lang.String containername)
	{
		setContainerName(getContext(), containername);
	}

	/**
	 * Set value of ContainerName
	 * @param context
	 * @param containername
	 */
	public final void setContainerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String containername)
	{
		getMendixObject().setValue(context, MemberNames.ContainerName.toString(), containername);
	}

	/**
	 * @return value of DataCollectionName
	 */
	public final java.lang.String getDataCollectionName()
	{
		return getDataCollectionName(getContext());
	}

	/**
	 * @param context
	 * @return value of DataCollectionName
	 */
	public final java.lang.String getDataCollectionName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataCollectionName.toString());
	}

	/**
	 * Set value of DataCollectionName
	 * @param datacollectionname
	 */
	public final void setDataCollectionName(java.lang.String datacollectionname)
	{
		setDataCollectionName(getContext(), datacollectionname);
	}

	/**
	 * Set value of DataCollectionName
	 * @param context
	 * @param datacollectionname
	 */
	public final void setDataCollectionName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datacollectionname)
	{
		getMendixObject().setValue(context, MemberNames.DataCollectionName.toString(), datacollectionname);
	}

	/**
	 * @return value of IsSubmitBtnEnabled
	 */
	public final java.lang.Integer getIsSubmitBtnEnabled()
	{
		return getIsSubmitBtnEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSubmitBtnEnabled
	 */
	public final java.lang.Integer getIsSubmitBtnEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IsSubmitBtnEnabled.toString());
	}

	/**
	 * Set value of IsSubmitBtnEnabled
	 * @param issubmitbtnenabled
	 */
	public final void setIsSubmitBtnEnabled(java.lang.Integer issubmitbtnenabled)
	{
		setIsSubmitBtnEnabled(getContext(), issubmitbtnenabled);
	}

	/**
	 * Set value of IsSubmitBtnEnabled
	 * @param context
	 * @param issubmitbtnenabled
	 */
	public final void setIsSubmitBtnEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer issubmitbtnenabled)
	{
		getMendixObject().setValue(context, MemberNames.IsSubmitBtnEnabled.toString(), issubmitbtnenabled);
	}

	/**
	 * @return value of DataPointLayout
	 */
	public final java.lang.Integer getDataPointLayout()
	{
		return getDataPointLayout(getContext());
	}

	/**
	 * @param context
	 * @return value of DataPointLayout
	 */
	public final java.lang.Integer getDataPointLayout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DataPointLayout.toString());
	}

	/**
	 * Set value of DataPointLayout
	 * @param datapointlayout
	 */
	public final void setDataPointLayout(java.lang.Integer datapointlayout)
	{
		setDataPointLayout(getContext(), datapointlayout);
	}

	/**
	 * Set value of DataPointLayout
	 * @param context
	 * @param datapointlayout
	 */
	public final void setDataPointLayout(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer datapointlayout)
	{
		getMendixObject().setValue(context, MemberNames.DataPointLayout.toString(), datapointlayout);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @return value of isParentDataCollection
	 */
	public final java.lang.String getisParentDataCollection()
	{
		return getisParentDataCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of isParentDataCollection
	 */
	public final java.lang.String getisParentDataCollection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.isParentDataCollection.toString());
	}

	/**
	 * Set value of isParentDataCollection
	 * @param isparentdatacollection
	 */
	public final void setisParentDataCollection(java.lang.String isparentdatacollection)
	{
		setisParentDataCollection(getContext(), isparentdatacollection);
	}

	/**
	 * Set value of isParentDataCollection
	 * @param context
	 * @param isparentdatacollection
	 */
	public final void setisParentDataCollection(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String isparentdatacollection)
	{
		getMendixObject().setValue(context, MemberNames.isParentDataCollection.toString(), isparentdatacollection);
	}

	/**
	 * @return value of isROR
	 */
	public final java.lang.Boolean getisROR()
	{
		return getisROR(getContext());
	}

	/**
	 * @param context
	 * @return value of isROR
	 */
	public final java.lang.Boolean getisROR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isROR.toString());
	}

	/**
	 * Set value of isROR
	 * @param isror
	 */
	public final void setisROR(java.lang.Boolean isror)
	{
		setisROR(getContext(), isror);
	}

	/**
	 * Set value of isROR
	 * @param context
	 * @param isror
	 */
	public final void setisROR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isror)
	{
		getMendixObject().setValue(context, MemberNames.isROR.toString(), isror);
	}

	/**
	 * @return value of Workstation
	 */
	public final java.lang.String getWorkstation()
	{
		return getWorkstation(getContext());
	}

	/**
	 * @param context
	 * @return value of Workstation
	 */
	public final java.lang.String getWorkstation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Workstation.toString());
	}

	/**
	 * Set value of Workstation
	 * @param workstation
	 */
	public final void setWorkstation(java.lang.String workstation)
	{
		setWorkstation(getContext(), workstation);
	}

	/**
	 * Set value of Workstation
	 * @param context
	 * @param workstation
	 */
	public final void setWorkstation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workstation)
	{
		getMendixObject().setValue(context, MemberNames.Workstation.toString(), workstation);
	}

	/**
	 * @return value of WorkstationCount
	 */
	public final java.lang.Integer getWorkstationCount()
	{
		return getWorkstationCount(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkstationCount
	 */
	public final java.lang.Integer getWorkstationCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.WorkstationCount.toString());
	}

	/**
	 * Set value of WorkstationCount
	 * @param workstationcount
	 */
	public final void setWorkstationCount(java.lang.Integer workstationcount)
	{
		setWorkstationCount(getContext(), workstationcount);
	}

	/**
	 * Set value of WorkstationCount
	 * @param context
	 * @param workstationcount
	 */
	public final void setWorkstationCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer workstationcount)
	{
		getMendixObject().setValue(context, MemberNames.WorkstationCount.toString(), workstationcount);
	}

	/**
	 * @return value of IsReset
	 */
	public final java.lang.Boolean getIsReset()
	{
		return getIsReset(getContext());
	}

	/**
	 * @param context
	 * @return value of IsReset
	 */
	public final java.lang.Boolean getIsReset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsReset.toString());
	}

	/**
	 * Set value of IsReset
	 * @param isreset
	 */
	public final void setIsReset(java.lang.Boolean isreset)
	{
		setIsReset(getContext(), isreset);
	}

	/**
	 * Set value of IsReset
	 * @param context
	 * @param isreset
	 */
	public final void setIsReset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isreset)
	{
		getMendixObject().setValue(context, MemberNames.IsReset.toString(), isreset);
	}

	/**
	 * @return value of IsSingleDataCollection
	 */
	public final java.lang.Boolean getIsSingleDataCollection()
	{
		return getIsSingleDataCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSingleDataCollection
	 */
	public final java.lang.Boolean getIsSingleDataCollection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSingleDataCollection.toString());
	}

	/**
	 * Set value of IsSingleDataCollection
	 * @param issingledatacollection
	 */
	public final void setIsSingleDataCollection(java.lang.Boolean issingledatacollection)
	{
		setIsSingleDataCollection(getContext(), issingledatacollection);
	}

	/**
	 * Set value of IsSingleDataCollection
	 * @param context
	 * @param issingledatacollection
	 */
	public final void setIsSingleDataCollection(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean issingledatacollection)
	{
		getMendixObject().setValue(context, MemberNames.IsSingleDataCollection.toString(), issingledatacollection);
	}

	/**
	 * @return value of ZoomScale
	 */
	public final java.lang.String getZoomScale()
	{
		return getZoomScale(getContext());
	}

	/**
	 * @param context
	 * @return value of ZoomScale
	 */
	public final java.lang.String getZoomScale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ZoomScale.toString());
	}

	/**
	 * Set value of ZoomScale
	 * @param zoomscale
	 */
	public final void setZoomScale(java.lang.String zoomscale)
	{
		setZoomScale(getContext(), zoomscale);
	}

	/**
	 * Set value of ZoomScale
	 * @param context
	 * @param zoomscale
	 */
	public final void setZoomScale(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zoomscale)
	{
		getMendixObject().setValue(context, MemberNames.ZoomScale.toString(), zoomscale);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EProcedureContext_ContainerCollectDataContext
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ContainerCollectDataContext() throws com.mendix.core.CoreException
	{
		return getEProcedureContext_ContainerCollectDataContext(getContext());
	}

	/**
	 * @param context
	 * @return value of EProcedureContext_ContainerCollectDataContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_eprocedure.proxies.EProcedureContext getEProcedureContext_ContainerCollectDataContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_eprocedure.proxies.EProcedureContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EProcedureContext_ContainerCollectDataContext.toString());
		if (identifier != null) {
			result = excr_eprocedure.proxies.EProcedureContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EProcedureContext_ContainerCollectDataContext
	 * @param eprocedurecontext_containercollectdatacontext
	 */
	public final void setEProcedureContext_ContainerCollectDataContext(excr_eprocedure.proxies.EProcedureContext eprocedurecontext_containercollectdatacontext)
	{
		setEProcedureContext_ContainerCollectDataContext(getContext(), eprocedurecontext_containercollectdatacontext);
	}

	/**
	 * Set value of EProcedureContext_ContainerCollectDataContext
	 * @param context
	 * @param eprocedurecontext_containercollectdatacontext
	 */
	public final void setEProcedureContext_ContainerCollectDataContext(com.mendix.systemwideinterfaces.core.IContext context, excr_eprocedure.proxies.EProcedureContext eprocedurecontext_containercollectdatacontext)
	{
		if (eprocedurecontext_containercollectdatacontext == null) {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ContainerCollectDataContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EProcedureContext_ContainerCollectDataContext.toString(), eprocedurecontext_containercollectdatacontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return containerCollectDataContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement.proxies.ContainerCollectDataContext that = (excr_resourcemanagement.proxies.ContainerCollectDataContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
