// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public class HistoryEventGroup implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject historyEventGroupMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement.HistoryEventGroup";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		txnName("txnName"),
		txnDate("txnDate"),
		operation("operation"),
		operator("operator"),
		isDataCollection("isDataCollection"),
		instructions("instructions"),
		status("status"),
		taskName("taskName"),
		isIssueMaterial("isIssueMaterial"),
		HistoryEventGroup_EventCluster("EXCR_ResourceManagement.HistoryEventGroup_EventCluster");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HistoryEventGroup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected HistoryEventGroup(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject historyEventGroupMendixObject)
	{
		if (historyEventGroupMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!historyEventGroupMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.historyEventGroupMendixObject = historyEventGroupMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement.proxies.HistoryEventGroup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement.proxies.HistoryEventGroup(context, mendixObject);
	}

	public static excr_resourcemanagement.proxies.HistoryEventGroup load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement.proxies.HistoryEventGroup.initialize(context, mendixObject);
	}

	/**
	 * @return value of txnName
	 */
	public final java.lang.String gettxnName()
	{
		return gettxnName(getContext());
	}

	/**
	 * @param context
	 * @return value of txnName
	 */
	public final java.lang.String gettxnName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.txnName.toString());
	}

	/**
	 * Set value of txnName
	 * @param txnname
	 */
	public final void settxnName(java.lang.String txnname)
	{
		settxnName(getContext(), txnname);
	}

	/**
	 * Set value of txnName
	 * @param context
	 * @param txnname
	 */
	public final void settxnName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String txnname)
	{
		getMendixObject().setValue(context, MemberNames.txnName.toString(), txnname);
	}

	/**
	 * @return value of txnDate
	 */
	public final java.util.Date gettxnDate()
	{
		return gettxnDate(getContext());
	}

	/**
	 * @param context
	 * @return value of txnDate
	 */
	public final java.util.Date gettxnDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.txnDate.toString());
	}

	/**
	 * Set value of txnDate
	 * @param txndate
	 */
	public final void settxnDate(java.util.Date txndate)
	{
		settxnDate(getContext(), txndate);
	}

	/**
	 * Set value of txnDate
	 * @param context
	 * @param txndate
	 */
	public final void settxnDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date txndate)
	{
		getMendixObject().setValue(context, MemberNames.txnDate.toString(), txndate);
	}

	/**
	 * @return value of operation
	 */
	public final java.lang.String getoperation()
	{
		return getoperation(getContext());
	}

	/**
	 * @param context
	 * @return value of operation
	 */
	public final java.lang.String getoperation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.operation.toString());
	}

	/**
	 * Set value of operation
	 * @param operation
	 */
	public final void setoperation(java.lang.String operation)
	{
		setoperation(getContext(), operation);
	}

	/**
	 * Set value of operation
	 * @param context
	 * @param operation
	 */
	public final void setoperation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operation)
	{
		getMendixObject().setValue(context, MemberNames.operation.toString(), operation);
	}

	/**
	 * @return value of operator
	 */
	public final java.lang.String getoperator()
	{
		return getoperator(getContext());
	}

	/**
	 * @param context
	 * @return value of operator
	 */
	public final java.lang.String getoperator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.operator.toString());
	}

	/**
	 * Set value of operator
	 * @param operator
	 */
	public final void setoperator(java.lang.String operator)
	{
		setoperator(getContext(), operator);
	}

	/**
	 * Set value of operator
	 * @param context
	 * @param operator
	 */
	public final void setoperator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operator)
	{
		getMendixObject().setValue(context, MemberNames.operator.toString(), operator);
	}

	/**
	 * @return value of isDataCollection
	 */
	public final java.lang.Boolean getisDataCollection()
	{
		return getisDataCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of isDataCollection
	 */
	public final java.lang.Boolean getisDataCollection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isDataCollection.toString());
	}

	/**
	 * Set value of isDataCollection
	 * @param isdatacollection
	 */
	public final void setisDataCollection(java.lang.Boolean isdatacollection)
	{
		setisDataCollection(getContext(), isdatacollection);
	}

	/**
	 * Set value of isDataCollection
	 * @param context
	 * @param isdatacollection
	 */
	public final void setisDataCollection(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdatacollection)
	{
		getMendixObject().setValue(context, MemberNames.isDataCollection.toString(), isdatacollection);
	}

	/**
	 * @return value of instructions
	 */
	public final java.lang.String getinstructions()
	{
		return getinstructions(getContext());
	}

	/**
	 * @param context
	 * @return value of instructions
	 */
	public final java.lang.String getinstructions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.instructions.toString());
	}

	/**
	 * Set value of instructions
	 * @param instructions
	 */
	public final void setinstructions(java.lang.String instructions)
	{
		setinstructions(getContext(), instructions);
	}

	/**
	 * Set value of instructions
	 * @param context
	 * @param instructions
	 */
	public final void setinstructions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instructions)
	{
		getMendixObject().setValue(context, MemberNames.instructions.toString(), instructions);
	}

	/**
	 * @return value of status
	 */
	public final java.lang.String getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final java.lang.String getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.status.toString());
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(java.lang.String status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.status.toString(), status);
	}

	/**
	 * @return value of taskName
	 */
	public final java.lang.String gettaskName()
	{
		return gettaskName(getContext());
	}

	/**
	 * @param context
	 * @return value of taskName
	 */
	public final java.lang.String gettaskName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.taskName.toString());
	}

	/**
	 * Set value of taskName
	 * @param taskname
	 */
	public final void settaskName(java.lang.String taskname)
	{
		settaskName(getContext(), taskname);
	}

	/**
	 * Set value of taskName
	 * @param context
	 * @param taskname
	 */
	public final void settaskName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taskname)
	{
		getMendixObject().setValue(context, MemberNames.taskName.toString(), taskname);
	}

	/**
	 * @return value of isIssueMaterial
	 */
	public final java.lang.Boolean getisIssueMaterial()
	{
		return getisIssueMaterial(getContext());
	}

	/**
	 * @param context
	 * @return value of isIssueMaterial
	 */
	public final java.lang.Boolean getisIssueMaterial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isIssueMaterial.toString());
	}

	/**
	 * Set value of isIssueMaterial
	 * @param isissuematerial
	 */
	public final void setisIssueMaterial(java.lang.Boolean isissuematerial)
	{
		setisIssueMaterial(getContext(), isissuematerial);
	}

	/**
	 * Set value of isIssueMaterial
	 * @param context
	 * @param isissuematerial
	 */
	public final void setisIssueMaterial(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isissuematerial)
	{
		getMendixObject().setValue(context, MemberNames.isIssueMaterial.toString(), isissuematerial);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of HistoryEventGroup_EventCluster
	 */
	public final excr_resourcemanagement.proxies.EventCluster getHistoryEventGroup_EventCluster() throws com.mendix.core.CoreException
	{
		return getHistoryEventGroup_EventCluster(getContext());
	}

	/**
	 * @param context
	 * @return value of HistoryEventGroup_EventCluster
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.EventCluster getHistoryEventGroup_EventCluster(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.EventCluster result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.HistoryEventGroup_EventCluster.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.EventCluster.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of HistoryEventGroup_EventCluster
	 * @param historyeventgroup_eventcluster
	 */
	public final void setHistoryEventGroup_EventCluster(excr_resourcemanagement.proxies.EventCluster historyeventgroup_eventcluster)
	{
		setHistoryEventGroup_EventCluster(getContext(), historyeventgroup_eventcluster);
	}

	/**
	 * Set value of HistoryEventGroup_EventCluster
	 * @param context
	 * @param historyeventgroup_eventcluster
	 */
	public final void setHistoryEventGroup_EventCluster(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.EventCluster historyeventgroup_eventcluster)
	{
		if (historyeventgroup_eventcluster == null) {
			getMendixObject().setValue(context, MemberNames.HistoryEventGroup_EventCluster.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.HistoryEventGroup_EventCluster.toString(), historyeventgroup_eventcluster.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return historyEventGroupMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement.proxies.HistoryEventGroup that = (excr_resourcemanagement.proxies.HistoryEventGroup) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
