// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public class ResourceHistoryModel implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resourceHistoryModelMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement.ResourceHistoryModel";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ResourceName("ResourceName"),
		isFiltered("isFiltered");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResourceHistoryModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResourceHistoryModel(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourceHistoryModelMendixObject)
	{
		if (resourceHistoryModelMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resourceHistoryModelMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resourceHistoryModelMendixObject = resourceHistoryModelMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement.proxies.ResourceHistoryModel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement.proxies.ResourceHistoryModel(context, mendixObject);
	}

	public static excr_resourcemanagement.proxies.ResourceHistoryModel load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement.proxies.ResourceHistoryModel.initialize(context, mendixObject);
	}

	/**
	 * @return value of ResourceName
	 */
	public final java.lang.String getResourceName()
	{
		return getResourceName(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceName
	 */
	public final java.lang.String getResourceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResourceName.toString());
	}

	/**
	 * Set value of ResourceName
	 * @param resourcename
	 */
	public final void setResourceName(java.lang.String resourcename)
	{
		setResourceName(getContext(), resourcename);
	}

	/**
	 * Set value of ResourceName
	 * @param context
	 * @param resourcename
	 */
	public final void setResourceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resourcename)
	{
		getMendixObject().setValue(context, MemberNames.ResourceName.toString(), resourcename);
	}

	/**
	 * @return value of isFiltered
	 */
	public final java.lang.Boolean getisFiltered()
	{
		return getisFiltered(getContext());
	}

	/**
	 * @param context
	 * @return value of isFiltered
	 */
	public final java.lang.Boolean getisFiltered(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isFiltered.toString());
	}

	/**
	 * Set value of isFiltered
	 * @param isfiltered
	 */
	public final void setisFiltered(java.lang.Boolean isfiltered)
	{
		setisFiltered(getContext(), isfiltered);
	}

	/**
	 * Set value of isFiltered
	 * @param context
	 * @param isfiltered
	 */
	public final void setisFiltered(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isfiltered)
	{
		getMendixObject().setValue(context, MemberNames.isFiltered.toString(), isfiltered);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resourceHistoryModelMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement.proxies.ResourceHistoryModel that = (excr_resourcemanagement.proxies.ResourceHistoryModel) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
