// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public class ResourcePinValidation implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resourcePinValidationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement.ResourcePinValidation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		XLocation("XLocation"),
		YLocation("YLocation");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResourcePinValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResourcePinValidation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourcePinValidationMendixObject)
	{
		if (resourcePinValidationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resourcePinValidationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resourcePinValidationMendixObject = resourcePinValidationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement.proxies.ResourcePinValidation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement.proxies.ResourcePinValidation(context, mendixObject);
	}

	public static excr_resourcemanagement.proxies.ResourcePinValidation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement.proxies.ResourcePinValidation.initialize(context, mendixObject);
	}

	/**
	 * @return value of XLocation
	 */
	public final java.lang.Boolean getXLocation()
	{
		return getXLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of XLocation
	 */
	public final java.lang.Boolean getXLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.XLocation.toString());
	}

	/**
	 * Set value of XLocation
	 * @param xlocation
	 */
	public final void setXLocation(java.lang.Boolean xlocation)
	{
		setXLocation(getContext(), xlocation);
	}

	/**
	 * Set value of XLocation
	 * @param context
	 * @param xlocation
	 */
	public final void setXLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean xlocation)
	{
		getMendixObject().setValue(context, MemberNames.XLocation.toString(), xlocation);
	}

	/**
	 * @return value of YLocation
	 */
	public final java.lang.Boolean getYLocation()
	{
		return getYLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of YLocation
	 */
	public final java.lang.Boolean getYLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.YLocation.toString());
	}

	/**
	 * Set value of YLocation
	 * @param ylocation
	 */
	public final void setYLocation(java.lang.Boolean ylocation)
	{
		setYLocation(getContext(), ylocation);
	}

	/**
	 * Set value of YLocation
	 * @param context
	 * @param ylocation
	 */
	public final void setYLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ylocation)
	{
		getMendixObject().setValue(context, MemberNames.YLocation.toString(), ylocation);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resourcePinValidationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement.proxies.ResourcePinValidation that = (excr_resourcemanagement.proxies.ResourcePinValidation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
