// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public class ResourcePin implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resourcePinMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement.ResourcePin";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PinColor("PinColor"),
		ShowPointer("ShowPointer"),
		IsSelected("IsSelected"),
		MarkerSize("MarkerSize"),
		ResourcePin_ResResourceLayoutDetail("EXCR_ResourceManagement.ResourcePin_ResResourceLayoutDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResourcePin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResourcePin(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourcePinMendixObject)
	{
		if (resourcePinMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resourcePinMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resourcePinMendixObject = resourcePinMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement.proxies.ResourcePin initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement.proxies.ResourcePin(context, mendixObject);
	}

	public static excr_resourcemanagement.proxies.ResourcePin load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement.proxies.ResourcePin.initialize(context, mendixObject);
	}

	/**
	 * @return value of PinColor
	 */
	public final java.lang.String getPinColor()
	{
		return getPinColor(getContext());
	}

	/**
	 * @param context
	 * @return value of PinColor
	 */
	public final java.lang.String getPinColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PinColor.toString());
	}

	/**
	 * Set value of PinColor
	 * @param pincolor
	 */
	public final void setPinColor(java.lang.String pincolor)
	{
		setPinColor(getContext(), pincolor);
	}

	/**
	 * Set value of PinColor
	 * @param context
	 * @param pincolor
	 */
	public final void setPinColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pincolor)
	{
		getMendixObject().setValue(context, MemberNames.PinColor.toString(), pincolor);
	}

	/**
	 * @return value of ShowPointer
	 */
	public final java.lang.Boolean getShowPointer()
	{
		return getShowPointer(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowPointer
	 */
	public final java.lang.Boolean getShowPointer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowPointer.toString());
	}

	/**
	 * Set value of ShowPointer
	 * @param showpointer
	 */
	public final void setShowPointer(java.lang.Boolean showpointer)
	{
		setShowPointer(getContext(), showpointer);
	}

	/**
	 * Set value of ShowPointer
	 * @param context
	 * @param showpointer
	 */
	public final void setShowPointer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showpointer)
	{
		getMendixObject().setValue(context, MemberNames.ShowPointer.toString(), showpointer);
	}

	/**
	 * @return value of IsSelected
	 */
	public final java.lang.Boolean getIsSelected()
	{
		return getIsSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSelected
	 */
	public final java.lang.Boolean getIsSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSelected.toString());
	}

	/**
	 * Set value of IsSelected
	 * @param isselected
	 */
	public final void setIsSelected(java.lang.Boolean isselected)
	{
		setIsSelected(getContext(), isselected);
	}

	/**
	 * Set value of IsSelected
	 * @param context
	 * @param isselected
	 */
	public final void setIsSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isselected)
	{
		getMendixObject().setValue(context, MemberNames.IsSelected.toString(), isselected);
	}

	/**
	 * @return value of MarkerSize
	 */
	public final java.math.BigDecimal getMarkerSize()
	{
		return getMarkerSize(getContext());
	}

	/**
	 * @param context
	 * @return value of MarkerSize
	 */
	public final java.math.BigDecimal getMarkerSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MarkerSize.toString());
	}

	/**
	 * Set value of MarkerSize
	 * @param markersize
	 */
	public final void setMarkerSize(java.math.BigDecimal markersize)
	{
		setMarkerSize(getContext(), markersize);
	}

	/**
	 * Set value of MarkerSize
	 * @param context
	 * @param markersize
	 */
	public final void setMarkerSize(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal markersize)
	{
		getMendixObject().setValue(context, MemberNames.MarkerSize.toString(), markersize);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourcePin_ResResourceLayoutDetail
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetail getResourcePin_ResResourceLayoutDetail() throws com.mendix.core.CoreException
	{
		return getResourcePin_ResResourceLayoutDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourcePin_ResResourceLayoutDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetail getResourcePin_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResResourceLayoutDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourcePin_ResResourceLayoutDetail.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResResourceLayoutDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourcePin_ResResourceLayoutDetail
	 * @param resourcepin_resresourcelayoutdetail
	 */
	public final void setResourcePin_ResResourceLayoutDetail(excr_resourcemanagement_api.proxies.ResResourceLayoutDetail resourcepin_resresourcelayoutdetail)
	{
		setResourcePin_ResResourceLayoutDetail(getContext(), resourcepin_resresourcelayoutdetail);
	}

	/**
	 * Set value of ResourcePin_ResResourceLayoutDetail
	 * @param context
	 * @param resourcepin_resresourcelayoutdetail
	 */
	public final void setResourcePin_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResResourceLayoutDetail resourcepin_resresourcelayoutdetail)
	{
		if (resourcepin_resresourcelayoutdetail == null) {
			getMendixObject().setValue(context, MemberNames.ResourcePin_ResResourceLayoutDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourcePin_ResResourceLayoutDetail.toString(), resourcepin_resresourcelayoutdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resourcePinMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement.proxies.ResourcePin that = (excr_resourcemanagement.proxies.ResourcePin) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
