// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public class ResourceSetupModel implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resourceSetupModelMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement.ResourceSetupModel";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		DataSource("DataSource"),
		CurrentStatus("CurrentStatus"),
		LengthofTimeInCurrentStatus("LengthofTimeInCurrentStatus"),
		CurrentStatusReason("CurrentStatusReason"),
		ResourceStatusCode("ResourceStatusCode"),
		ResourceStatusCodeQR("ResourceStatusCodeQR"),
		Comments("Comments"),
		ResourceStatusReason("ResourceStatusReason"),
		ResourceStatusReasonQR("ResourceStatusReasonQR"),
		Availability("Availability"),
		ResourceSetupModel_ResResourceCode("EXCR_ResourceManagement.ResourceSetupModel_ResResourceCode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResourceSetupModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResourceSetupModel(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourceSetupModelMendixObject)
	{
		if (resourceSetupModelMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resourceSetupModelMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resourceSetupModelMendixObject = resourceSetupModelMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement.proxies.ResourceSetupModel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement.proxies.ResourceSetupModel(context, mendixObject);
	}

	public static excr_resourcemanagement.proxies.ResourceSetupModel load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement.proxies.ResourceSetupModel.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of DataSource
	 */
	public final java.lang.String getDataSource()
	{
		return getDataSource(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSource
	 */
	public final java.lang.String getDataSource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataSource.toString());
	}

	/**
	 * Set value of DataSource
	 * @param datasource
	 */
	public final void setDataSource(java.lang.String datasource)
	{
		setDataSource(getContext(), datasource);
	}

	/**
	 * Set value of DataSource
	 * @param context
	 * @param datasource
	 */
	public final void setDataSource(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datasource)
	{
		getMendixObject().setValue(context, MemberNames.DataSource.toString(), datasource);
	}

	/**
	 * @return value of CurrentStatus
	 */
	public final java.lang.String getCurrentStatus()
	{
		return getCurrentStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentStatus
	 */
	public final java.lang.String getCurrentStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrentStatus.toString());
	}

	/**
	 * Set value of CurrentStatus
	 * @param currentstatus
	 */
	public final void setCurrentStatus(java.lang.String currentstatus)
	{
		setCurrentStatus(getContext(), currentstatus);
	}

	/**
	 * Set value of CurrentStatus
	 * @param context
	 * @param currentstatus
	 */
	public final void setCurrentStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currentstatus)
	{
		getMendixObject().setValue(context, MemberNames.CurrentStatus.toString(), currentstatus);
	}

	/**
	 * @return value of LengthofTimeInCurrentStatus
	 */
	public final java.lang.String getLengthofTimeInCurrentStatus()
	{
		return getLengthofTimeInCurrentStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of LengthofTimeInCurrentStatus
	 */
	public final java.lang.String getLengthofTimeInCurrentStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LengthofTimeInCurrentStatus.toString());
	}

	/**
	 * Set value of LengthofTimeInCurrentStatus
	 * @param lengthoftimeincurrentstatus
	 */
	public final void setLengthofTimeInCurrentStatus(java.lang.String lengthoftimeincurrentstatus)
	{
		setLengthofTimeInCurrentStatus(getContext(), lengthoftimeincurrentstatus);
	}

	/**
	 * Set value of LengthofTimeInCurrentStatus
	 * @param context
	 * @param lengthoftimeincurrentstatus
	 */
	public final void setLengthofTimeInCurrentStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lengthoftimeincurrentstatus)
	{
		getMendixObject().setValue(context, MemberNames.LengthofTimeInCurrentStatus.toString(), lengthoftimeincurrentstatus);
	}

	/**
	 * @return value of CurrentStatusReason
	 */
	public final java.lang.String getCurrentStatusReason()
	{
		return getCurrentStatusReason(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentStatusReason
	 */
	public final java.lang.String getCurrentStatusReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrentStatusReason.toString());
	}

	/**
	 * Set value of CurrentStatusReason
	 * @param currentstatusreason
	 */
	public final void setCurrentStatusReason(java.lang.String currentstatusreason)
	{
		setCurrentStatusReason(getContext(), currentstatusreason);
	}

	/**
	 * Set value of CurrentStatusReason
	 * @param context
	 * @param currentstatusreason
	 */
	public final void setCurrentStatusReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currentstatusreason)
	{
		getMendixObject().setValue(context, MemberNames.CurrentStatusReason.toString(), currentstatusreason);
	}

	/**
	 * @return value of ResourceStatusCode
	 */
	public final java.lang.String getResourceStatusCode()
	{
		return getResourceStatusCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceStatusCode
	 */
	public final java.lang.String getResourceStatusCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResourceStatusCode.toString());
	}

	/**
	 * Set value of ResourceStatusCode
	 * @param resourcestatuscode
	 */
	public final void setResourceStatusCode(java.lang.String resourcestatuscode)
	{
		setResourceStatusCode(getContext(), resourcestatuscode);
	}

	/**
	 * Set value of ResourceStatusCode
	 * @param context
	 * @param resourcestatuscode
	 */
	public final void setResourceStatusCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resourcestatuscode)
	{
		getMendixObject().setValue(context, MemberNames.ResourceStatusCode.toString(), resourcestatuscode);
	}

	/**
	 * @return value of ResourceStatusCodeQR
	 */
	public final java.lang.Boolean getResourceStatusCodeQR()
	{
		return getResourceStatusCodeQR(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceStatusCodeQR
	 */
	public final java.lang.Boolean getResourceStatusCodeQR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ResourceStatusCodeQR.toString());
	}

	/**
	 * Set value of ResourceStatusCodeQR
	 * @param resourcestatuscodeqr
	 */
	public final void setResourceStatusCodeQR(java.lang.Boolean resourcestatuscodeqr)
	{
		setResourceStatusCodeQR(getContext(), resourcestatuscodeqr);
	}

	/**
	 * Set value of ResourceStatusCodeQR
	 * @param context
	 * @param resourcestatuscodeqr
	 */
	public final void setResourceStatusCodeQR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean resourcestatuscodeqr)
	{
		getMendixObject().setValue(context, MemberNames.ResourceStatusCodeQR.toString(), resourcestatuscodeqr);
	}

	/**
	 * @return value of Comments
	 */
	public final java.lang.String getComments()
	{
		return getComments(getContext());
	}

	/**
	 * @param context
	 * @return value of Comments
	 */
	public final java.lang.String getComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comments.toString());
	}

	/**
	 * Set value of Comments
	 * @param comments
	 */
	public final void setComments(java.lang.String comments)
	{
		setComments(getContext(), comments);
	}

	/**
	 * Set value of Comments
	 * @param context
	 * @param comments
	 */
	public final void setComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comments)
	{
		getMendixObject().setValue(context, MemberNames.Comments.toString(), comments);
	}

	/**
	 * @return value of ResourceStatusReason
	 */
	public final java.lang.String getResourceStatusReason()
	{
		return getResourceStatusReason(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceStatusReason
	 */
	public final java.lang.String getResourceStatusReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResourceStatusReason.toString());
	}

	/**
	 * Set value of ResourceStatusReason
	 * @param resourcestatusreason
	 */
	public final void setResourceStatusReason(java.lang.String resourcestatusreason)
	{
		setResourceStatusReason(getContext(), resourcestatusreason);
	}

	/**
	 * Set value of ResourceStatusReason
	 * @param context
	 * @param resourcestatusreason
	 */
	public final void setResourceStatusReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resourcestatusreason)
	{
		getMendixObject().setValue(context, MemberNames.ResourceStatusReason.toString(), resourcestatusreason);
	}

	/**
	 * @return value of ResourceStatusReasonQR
	 */
	public final java.lang.Boolean getResourceStatusReasonQR()
	{
		return getResourceStatusReasonQR(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceStatusReasonQR
	 */
	public final java.lang.Boolean getResourceStatusReasonQR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ResourceStatusReasonQR.toString());
	}

	/**
	 * Set value of ResourceStatusReasonQR
	 * @param resourcestatusreasonqr
	 */
	public final void setResourceStatusReasonQR(java.lang.Boolean resourcestatusreasonqr)
	{
		setResourceStatusReasonQR(getContext(), resourcestatusreasonqr);
	}

	/**
	 * Set value of ResourceStatusReasonQR
	 * @param context
	 * @param resourcestatusreasonqr
	 */
	public final void setResourceStatusReasonQR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean resourcestatusreasonqr)
	{
		getMendixObject().setValue(context, MemberNames.ResourceStatusReasonQR.toString(), resourcestatusreasonqr);
	}

	/**
	 * @return value of Availability
	 */
	public final java.lang.String getAvailability()
	{
		return getAvailability(getContext());
	}

	/**
	 * @param context
	 * @return value of Availability
	 */
	public final java.lang.String getAvailability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Availability.toString());
	}

	/**
	 * Set value of Availability
	 * @param availability
	 */
	public final void setAvailability(java.lang.String availability)
	{
		setAvailability(getContext(), availability);
	}

	/**
	 * Set value of Availability
	 * @param context
	 * @param availability
	 */
	public final void setAvailability(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String availability)
	{
		getMendixObject().setValue(context, MemberNames.Availability.toString(), availability);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourceSetupModel_ResResourceCode
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceStatusCode getResourceSetupModel_ResResourceCode() throws com.mendix.core.CoreException
	{
		return getResourceSetupModel_ResResourceCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceSetupModel_ResResourceCode
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceStatusCode getResourceSetupModel_ResResourceCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResResourceStatusCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourceSetupModel_ResResourceCode.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResResourceStatusCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourceSetupModel_ResResourceCode
	 * @param resourcesetupmodel_resresourcecode
	 */
	public final void setResourceSetupModel_ResResourceCode(excr_resourcemanagement_api.proxies.ResResourceStatusCode resourcesetupmodel_resresourcecode)
	{
		setResourceSetupModel_ResResourceCode(getContext(), resourcesetupmodel_resresourcecode);
	}

	/**
	 * Set value of ResourceSetupModel_ResResourceCode
	 * @param context
	 * @param resourcesetupmodel_resresourcecode
	 */
	public final void setResourceSetupModel_ResResourceCode(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResResourceStatusCode resourcesetupmodel_resresourcecode)
	{
		if (resourcesetupmodel_resresourcecode == null) {
			getMendixObject().setValue(context, MemberNames.ResourceSetupModel_ResResourceCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourceSetupModel_ResResourceCode.toString(), resourcesetupmodel_resresourcecode.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resourceSetupModelMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement.proxies.ResourceSetupModel that = (excr_resourcemanagement.proxies.ResourceSetupModel) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
