// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public class ResourceLayoutOverviewContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resourceLayoutOverviewContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement.ResourceLayoutOverviewContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SelectedX("SelectedX"),
		SelectedY("SelectedY"),
		LayoutSearchString("LayoutSearchString"),
		ExcludedResourcesXPathString("ExcludedResourcesXPathString"),
		ExcludedOperationsXPathString("ExcludedOperationsXPathString"),
		ExcludedSpecsXPathString("ExcludedSpecsXPathString"),
		ResourceLayoutOverviewContext_ResourceLayout_SelectedLayout("EXCR_ResourceManagement.ResourceLayoutOverviewContext_ResourceLayout_SelectedLayout");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResourceLayoutOverviewContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResourceLayoutOverviewContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourceLayoutOverviewContextMendixObject)
	{
		if (resourceLayoutOverviewContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resourceLayoutOverviewContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resourceLayoutOverviewContextMendixObject = resourceLayoutOverviewContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement.proxies.ResourceLayoutOverviewContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement.proxies.ResourceLayoutOverviewContext(context, mendixObject);
	}

	public static excr_resourcemanagement.proxies.ResourceLayoutOverviewContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement.proxies.ResourceLayoutOverviewContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of SelectedX
	 */
	public final java.math.BigDecimal getSelectedX()
	{
		return getSelectedX(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedX
	 */
	public final java.math.BigDecimal getSelectedX(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.SelectedX.toString());
	}

	/**
	 * Set value of SelectedX
	 * @param selectedx
	 */
	public final void setSelectedX(java.math.BigDecimal selectedx)
	{
		setSelectedX(getContext(), selectedx);
	}

	/**
	 * Set value of SelectedX
	 * @param context
	 * @param selectedx
	 */
	public final void setSelectedX(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal selectedx)
	{
		getMendixObject().setValue(context, MemberNames.SelectedX.toString(), selectedx);
	}

	/**
	 * @return value of SelectedY
	 */
	public final java.math.BigDecimal getSelectedY()
	{
		return getSelectedY(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedY
	 */
	public final java.math.BigDecimal getSelectedY(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.SelectedY.toString());
	}

	/**
	 * Set value of SelectedY
	 * @param selectedy
	 */
	public final void setSelectedY(java.math.BigDecimal selectedy)
	{
		setSelectedY(getContext(), selectedy);
	}

	/**
	 * Set value of SelectedY
	 * @param context
	 * @param selectedy
	 */
	public final void setSelectedY(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal selectedy)
	{
		getMendixObject().setValue(context, MemberNames.SelectedY.toString(), selectedy);
	}

	/**
	 * @return value of LayoutSearchString
	 */
	public final java.lang.String getLayoutSearchString()
	{
		return getLayoutSearchString(getContext());
	}

	/**
	 * @param context
	 * @return value of LayoutSearchString
	 */
	public final java.lang.String getLayoutSearchString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LayoutSearchString.toString());
	}

	/**
	 * Set value of LayoutSearchString
	 * @param layoutsearchstring
	 */
	public final void setLayoutSearchString(java.lang.String layoutsearchstring)
	{
		setLayoutSearchString(getContext(), layoutsearchstring);
	}

	/**
	 * Set value of LayoutSearchString
	 * @param context
	 * @param layoutsearchstring
	 */
	public final void setLayoutSearchString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String layoutsearchstring)
	{
		getMendixObject().setValue(context, MemberNames.LayoutSearchString.toString(), layoutsearchstring);
	}

	/**
	 * @return value of ExcludedResourcesXPathString
	 */
	public final java.lang.String getExcludedResourcesXPathString()
	{
		return getExcludedResourcesXPathString(getContext());
	}

	/**
	 * @param context
	 * @return value of ExcludedResourcesXPathString
	 */
	public final java.lang.String getExcludedResourcesXPathString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExcludedResourcesXPathString.toString());
	}

	/**
	 * Set value of ExcludedResourcesXPathString
	 * @param excludedresourcesxpathstring
	 */
	public final void setExcludedResourcesXPathString(java.lang.String excludedresourcesxpathstring)
	{
		setExcludedResourcesXPathString(getContext(), excludedresourcesxpathstring);
	}

	/**
	 * Set value of ExcludedResourcesXPathString
	 * @param context
	 * @param excludedresourcesxpathstring
	 */
	public final void setExcludedResourcesXPathString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String excludedresourcesxpathstring)
	{
		getMendixObject().setValue(context, MemberNames.ExcludedResourcesXPathString.toString(), excludedresourcesxpathstring);
	}

	/**
	 * @return value of ExcludedOperationsXPathString
	 */
	public final java.lang.String getExcludedOperationsXPathString()
	{
		return getExcludedOperationsXPathString(getContext());
	}

	/**
	 * @param context
	 * @return value of ExcludedOperationsXPathString
	 */
	public final java.lang.String getExcludedOperationsXPathString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExcludedOperationsXPathString.toString());
	}

	/**
	 * Set value of ExcludedOperationsXPathString
	 * @param excludedoperationsxpathstring
	 */
	public final void setExcludedOperationsXPathString(java.lang.String excludedoperationsxpathstring)
	{
		setExcludedOperationsXPathString(getContext(), excludedoperationsxpathstring);
	}

	/**
	 * Set value of ExcludedOperationsXPathString
	 * @param context
	 * @param excludedoperationsxpathstring
	 */
	public final void setExcludedOperationsXPathString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String excludedoperationsxpathstring)
	{
		getMendixObject().setValue(context, MemberNames.ExcludedOperationsXPathString.toString(), excludedoperationsxpathstring);
	}

	/**
	 * @return value of ExcludedSpecsXPathString
	 */
	public final java.lang.String getExcludedSpecsXPathString()
	{
		return getExcludedSpecsXPathString(getContext());
	}

	/**
	 * @param context
	 * @return value of ExcludedSpecsXPathString
	 */
	public final java.lang.String getExcludedSpecsXPathString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExcludedSpecsXPathString.toString());
	}

	/**
	 * Set value of ExcludedSpecsXPathString
	 * @param excludedspecsxpathstring
	 */
	public final void setExcludedSpecsXPathString(java.lang.String excludedspecsxpathstring)
	{
		setExcludedSpecsXPathString(getContext(), excludedspecsxpathstring);
	}

	/**
	 * Set value of ExcludedSpecsXPathString
	 * @param context
	 * @param excludedspecsxpathstring
	 */
	public final void setExcludedSpecsXPathString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String excludedspecsxpathstring)
	{
		getMendixObject().setValue(context, MemberNames.ExcludedSpecsXPathString.toString(), excludedspecsxpathstring);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourceLayoutOverviewContext_ResourceLayout_SelectedLayout
	 */
	public final excr_resourcemanagement.proxies.ResourceLayout getResourceLayoutOverviewContext_ResourceLayout_SelectedLayout() throws com.mendix.core.CoreException
	{
		return getResourceLayoutOverviewContext_ResourceLayout_SelectedLayout(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceLayoutOverviewContext_ResourceLayout_SelectedLayout
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ResourceLayout getResourceLayoutOverviewContext_ResourceLayout_SelectedLayout(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ResourceLayout result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourceLayoutOverviewContext_ResourceLayout_SelectedLayout.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ResourceLayout.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourceLayoutOverviewContext_ResourceLayout_SelectedLayout
	 * @param resourcelayoutoverviewcontext_resourcelayout_selectedlayout
	 */
	public final void setResourceLayoutOverviewContext_ResourceLayout_SelectedLayout(excr_resourcemanagement.proxies.ResourceLayout resourcelayoutoverviewcontext_resourcelayout_selectedlayout)
	{
		setResourceLayoutOverviewContext_ResourceLayout_SelectedLayout(getContext(), resourcelayoutoverviewcontext_resourcelayout_selectedlayout);
	}

	/**
	 * Set value of ResourceLayoutOverviewContext_ResourceLayout_SelectedLayout
	 * @param context
	 * @param resourcelayoutoverviewcontext_resourcelayout_selectedlayout
	 */
	public final void setResourceLayoutOverviewContext_ResourceLayout_SelectedLayout(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ResourceLayout resourcelayoutoverviewcontext_resourcelayout_selectedlayout)
	{
		if (resourcelayoutoverviewcontext_resourcelayout_selectedlayout == null) {
			getMendixObject().setValue(context, MemberNames.ResourceLayoutOverviewContext_ResourceLayout_SelectedLayout.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourceLayoutOverviewContext_ResourceLayout_SelectedLayout.toString(), resourcelayoutoverviewcontext_resourcelayout_selectedlayout.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resourceLayoutOverviewContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement.proxies.ResourceLayoutOverviewContext that = (excr_resourcemanagement.proxies.ResourceLayoutOverviewContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
