// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement.proxies;

public enum viewType_ENUM
{
	containerOnly("676c2f01-596e-4aa2-9c9c-ba3e2ee09437"),
	ResourceOnly("74b25d56-9822-4b73-9f77-9aefdf909894"),
	dual("0a2fb319-6543-4b39-9ec3-62a3f83271ec");

	private final java.lang.String i18nCaptionKey;
	
	private viewType_ENUM(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
