// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public class APIReqMfgOrderTaskItem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aPIReqMfgOrderTaskItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement.APIReqMfgOrderTaskItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Value("Value"),
		APIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter("EXCR_MfgOrderManagement.APIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public APIReqMfgOrderTaskItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected APIReqMfgOrderTaskItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPIReqMfgOrderTaskItemMendixObject)
	{
		if (aPIReqMfgOrderTaskItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!aPIReqMfgOrderTaskItemMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aPIReqMfgOrderTaskItemMendixObject = aPIReqMfgOrderTaskItemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItem(context, mendixObject);
	}

	public static excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItem.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter
	 */
	public final excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItemParameter getAPIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter() throws com.mendix.core.CoreException
	{
		return getAPIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter(getContext());
	}

	/**
	 * @param context
	 * @return value of APIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItemParameter getAPIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItemParameter result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItemParameter.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter
	 * @param apireqmfgordertaskitem_apireqmfgordertaskitemparameter
	 */
	public final void setAPIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter(excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItemParameter apireqmfgordertaskitem_apireqmfgordertaskitemparameter)
	{
		setAPIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter(getContext(), apireqmfgordertaskitem_apireqmfgordertaskitemparameter);
	}

	/**
	 * Set value of APIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter
	 * @param context
	 * @param apireqmfgordertaskitem_apireqmfgordertaskitemparameter
	 */
	public final void setAPIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItemParameter apireqmfgordertaskitem_apireqmfgordertaskitemparameter)
	{
		if (apireqmfgordertaskitem_apireqmfgordertaskitemparameter == null) {
			getMendixObject().setValue(context, MemberNames.APIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIReqMfgOrderTaskItem_APIReqMfgOrderTaskItemParameter.toString(), apireqmfgordertaskitem_apireqmfgordertaskitemparameter.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aPIReqMfgOrderTaskItemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItem that = (excr_mfgordermanagement.proxies.APIReqMfgOrderTaskItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
