// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public class APIReqMfgOrderProcedure implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aPIReqMfgOrderProcedureMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement.APIReqMfgOrderProcedure";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Revision("Revision"),
		UseROR("UseROR"),
		APIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask("EXCR_MfgOrderManagement.APIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public APIReqMfgOrderProcedure(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected APIReqMfgOrderProcedure(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPIReqMfgOrderProcedureMendixObject)
	{
		if (aPIReqMfgOrderProcedureMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!aPIReqMfgOrderProcedureMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aPIReqMfgOrderProcedureMendixObject = aPIReqMfgOrderProcedureMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement.proxies.APIReqMfgOrderProcedure initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement.proxies.APIReqMfgOrderProcedure(context, mendixObject);
	}

	public static excr_mfgordermanagement.proxies.APIReqMfgOrderProcedure load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement.proxies.APIReqMfgOrderProcedure.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Revision
	 */
	public final java.lang.String getRevision()
	{
		return getRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision
	 */
	public final java.lang.String getRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision.toString());
	}

	/**
	 * Set value of Revision
	 * @param revision
	 */
	public final void setRevision(java.lang.String revision)
	{
		setRevision(getContext(), revision);
	}

	/**
	 * Set value of Revision
	 * @param context
	 * @param revision
	 */
	public final void setRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision)
	{
		getMendixObject().setValue(context, MemberNames.Revision.toString(), revision);
	}

	/**
	 * @return value of UseROR
	 */
	public final java.lang.String getUseROR()
	{
		return getUseROR(getContext());
	}

	/**
	 * @param context
	 * @return value of UseROR
	 */
	public final java.lang.String getUseROR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseROR.toString());
	}

	/**
	 * Set value of UseROR
	 * @param useror
	 */
	public final void setUseROR(java.lang.String useror)
	{
		setUseROR(getContext(), useror);
	}

	/**
	 * Set value of UseROR
	 * @param context
	 * @param useror
	 */
	public final void setUseROR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String useror)
	{
		getMendixObject().setValue(context, MemberNames.UseROR.toString(), useror);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask
	 */
	public final excr_mfgordermanagement.proxies.APIReqExecuteMfgOrderTask getAPIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask() throws com.mendix.core.CoreException
	{
		return getAPIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask(getContext());
	}

	/**
	 * @param context
	 * @return value of APIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.APIReqExecuteMfgOrderTask getAPIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.APIReqExecuteMfgOrderTask result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.APIReqExecuteMfgOrderTask.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask
	 * @param apireqmfgorderprocedure_apireqexecutemfgordertask
	 */
	public final void setAPIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask(excr_mfgordermanagement.proxies.APIReqExecuteMfgOrderTask apireqmfgorderprocedure_apireqexecutemfgordertask)
	{
		setAPIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask(getContext(), apireqmfgorderprocedure_apireqexecutemfgordertask);
	}

	/**
	 * Set value of APIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask
	 * @param context
	 * @param apireqmfgorderprocedure_apireqexecutemfgordertask
	 */
	public final void setAPIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.APIReqExecuteMfgOrderTask apireqmfgorderprocedure_apireqexecutemfgordertask)
	{
		if (apireqmfgorderprocedure_apireqexecutemfgordertask == null) {
			getMendixObject().setValue(context, MemberNames.APIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIReqMfgOrderProcedure_APIReqExecuteMfgOrderTask.toString(), apireqmfgorderprocedure_apireqexecutemfgordertask.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aPIReqMfgOrderProcedureMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement.proxies.APIReqMfgOrderProcedure that = (excr_mfgordermanagement.proxies.APIReqMfgOrderProcedure) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
