// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public class DispatchMfgOrders implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dispatchMfgOrdersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement.DispatchMfgOrders";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MfgOrderId("MfgOrderId"),
		InstanceId("InstanceId"),
		MfgOrder("MfgOrder"),
		Priority("Priority"),
		ReleaseDate("ReleaseDate"),
		QtyStarted("QtyStarted"),
		Qty("Qty"),
		StdStartQty("StdStartQty"),
		UOM("UOM"),
		InProcessQty("InProcessQty"),
		BeginProduct("BeginProduct"),
		Product("Product"),
		ProductDescription("ProductDescription"),
		OrderType("OrderType"),
		OrderStatus("OrderStatus"),
		PlannedStartDate("PlannedStartDate"),
		PlannedCompletionDate("PlannedCompletionDate"),
		RelativePriority("RelativePriority"),
		PriorityCodeChange("PriorityCodeChange"),
		DispatchMfgOrders_OrderDispatchContext("EXCR_MfgOrderManagement.DispatchMfgOrders_OrderDispatchContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DispatchMfgOrders(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DispatchMfgOrders(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dispatchMfgOrdersMendixObject)
	{
		if (dispatchMfgOrdersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!dispatchMfgOrdersMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dispatchMfgOrdersMendixObject = dispatchMfgOrdersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement.proxies.DispatchMfgOrders initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement.proxies.DispatchMfgOrders(context, mendixObject);
	}

	public static excr_mfgordermanagement.proxies.DispatchMfgOrders load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement.proxies.DispatchMfgOrders.initialize(context, mendixObject);
	}

	/**
	 * @return value of MfgOrderId
	 */
	public final java.lang.String getMfgOrderId()
	{
		return getMfgOrderId(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrderId
	 */
	public final java.lang.String getMfgOrderId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MfgOrderId.toString());
	}

	/**
	 * Set value of MfgOrderId
	 * @param mfgorderid
	 */
	public final void setMfgOrderId(java.lang.String mfgorderid)
	{
		setMfgOrderId(getContext(), mfgorderid);
	}

	/**
	 * Set value of MfgOrderId
	 * @param context
	 * @param mfgorderid
	 */
	public final void setMfgOrderId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfgorderid)
	{
		getMendixObject().setValue(context, MemberNames.MfgOrderId.toString(), mfgorderid);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @return value of MfgOrder
	 */
	public final java.lang.String getMfgOrder()
	{
		return getMfgOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrder
	 */
	public final java.lang.String getMfgOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MfgOrder.toString());
	}

	/**
	 * Set value of MfgOrder
	 * @param mfgorder
	 */
	public final void setMfgOrder(java.lang.String mfgorder)
	{
		setMfgOrder(getContext(), mfgorder);
	}

	/**
	 * Set value of MfgOrder
	 * @param context
	 * @param mfgorder
	 */
	public final void setMfgOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfgorder)
	{
		getMendixObject().setValue(context, MemberNames.MfgOrder.toString(), mfgorder);
	}

	/**
	 * @return value of Priority
	 */
	public final java.lang.String getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final java.lang.String getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Priority.toString());
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(java.lang.String priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String priority)
	{
		getMendixObject().setValue(context, MemberNames.Priority.toString(), priority);
	}

	/**
	 * @return value of ReleaseDate
	 */
	public final java.util.Date getReleaseDate()
	{
		return getReleaseDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ReleaseDate
	 */
	public final java.util.Date getReleaseDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ReleaseDate.toString());
	}

	/**
	 * Set value of ReleaseDate
	 * @param releasedate
	 */
	public final void setReleaseDate(java.util.Date releasedate)
	{
		setReleaseDate(getContext(), releasedate);
	}

	/**
	 * Set value of ReleaseDate
	 * @param context
	 * @param releasedate
	 */
	public final void setReleaseDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date releasedate)
	{
		getMendixObject().setValue(context, MemberNames.ReleaseDate.toString(), releasedate);
	}

	/**
	 * @return value of QtyStarted
	 */
	public final java.lang.String getQtyStarted()
	{
		return getQtyStarted(getContext());
	}

	/**
	 * @param context
	 * @return value of QtyStarted
	 */
	public final java.lang.String getQtyStarted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QtyStarted.toString());
	}

	/**
	 * Set value of QtyStarted
	 * @param qtystarted
	 */
	public final void setQtyStarted(java.lang.String qtystarted)
	{
		setQtyStarted(getContext(), qtystarted);
	}

	/**
	 * Set value of QtyStarted
	 * @param context
	 * @param qtystarted
	 */
	public final void setQtyStarted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String qtystarted)
	{
		getMendixObject().setValue(context, MemberNames.QtyStarted.toString(), qtystarted);
	}

	/**
	 * @return value of Qty
	 */
	public final java.lang.String getQty()
	{
		return getQty(getContext());
	}

	/**
	 * @param context
	 * @return value of Qty
	 */
	public final java.lang.String getQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Qty.toString());
	}

	/**
	 * Set value of Qty
	 * @param qty
	 */
	public final void setQty(java.lang.String qty)
	{
		setQty(getContext(), qty);
	}

	/**
	 * Set value of Qty
	 * @param context
	 * @param qty
	 */
	public final void setQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String qty)
	{
		getMendixObject().setValue(context, MemberNames.Qty.toString(), qty);
	}

	/**
	 * @return value of StdStartQty
	 */
	public final java.lang.String getStdStartQty()
	{
		return getStdStartQty(getContext());
	}

	/**
	 * @param context
	 * @return value of StdStartQty
	 */
	public final java.lang.String getStdStartQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StdStartQty.toString());
	}

	/**
	 * Set value of StdStartQty
	 * @param stdstartqty
	 */
	public final void setStdStartQty(java.lang.String stdstartqty)
	{
		setStdStartQty(getContext(), stdstartqty);
	}

	/**
	 * Set value of StdStartQty
	 * @param context
	 * @param stdstartqty
	 */
	public final void setStdStartQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stdstartqty)
	{
		getMendixObject().setValue(context, MemberNames.StdStartQty.toString(), stdstartqty);
	}

	/**
	 * @return value of UOM
	 */
	public final java.lang.String getUOM()
	{
		return getUOM(getContext());
	}

	/**
	 * @param context
	 * @return value of UOM
	 */
	public final java.lang.String getUOM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UOM.toString());
	}

	/**
	 * Set value of UOM
	 * @param uom
	 */
	public final void setUOM(java.lang.String uom)
	{
		setUOM(getContext(), uom);
	}

	/**
	 * Set value of UOM
	 * @param context
	 * @param uom
	 */
	public final void setUOM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uom)
	{
		getMendixObject().setValue(context, MemberNames.UOM.toString(), uom);
	}

	/**
	 * @return value of InProcessQty
	 */
	public final java.lang.String getInProcessQty()
	{
		return getInProcessQty(getContext());
	}

	/**
	 * @param context
	 * @return value of InProcessQty
	 */
	public final java.lang.String getInProcessQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InProcessQty.toString());
	}

	/**
	 * Set value of InProcessQty
	 * @param inprocessqty
	 */
	public final void setInProcessQty(java.lang.String inprocessqty)
	{
		setInProcessQty(getContext(), inprocessqty);
	}

	/**
	 * Set value of InProcessQty
	 * @param context
	 * @param inprocessqty
	 */
	public final void setInProcessQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String inprocessqty)
	{
		getMendixObject().setValue(context, MemberNames.InProcessQty.toString(), inprocessqty);
	}

	/**
	 * @return value of BeginProduct
	 */
	public final java.lang.String getBeginProduct()
	{
		return getBeginProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of BeginProduct
	 */
	public final java.lang.String getBeginProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BeginProduct.toString());
	}

	/**
	 * Set value of BeginProduct
	 * @param beginproduct
	 */
	public final void setBeginProduct(java.lang.String beginproduct)
	{
		setBeginProduct(getContext(), beginproduct);
	}

	/**
	 * Set value of BeginProduct
	 * @param context
	 * @param beginproduct
	 */
	public final void setBeginProduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String beginproduct)
	{
		getMendixObject().setValue(context, MemberNames.BeginProduct.toString(), beginproduct);
	}

	/**
	 * @return value of Product
	 */
	public final java.lang.String getProduct()
	{
		return getProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of Product
	 */
	public final java.lang.String getProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Product.toString());
	}

	/**
	 * Set value of Product
	 * @param product
	 */
	public final void setProduct(java.lang.String product)
	{
		setProduct(getContext(), product);
	}

	/**
	 * Set value of Product
	 * @param context
	 * @param product
	 */
	public final void setProduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product)
	{
		getMendixObject().setValue(context, MemberNames.Product.toString(), product);
	}

	/**
	 * @return value of ProductDescription
	 */
	public final java.lang.String getProductDescription()
	{
		return getProductDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductDescription
	 */
	public final java.lang.String getProductDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductDescription.toString());
	}

	/**
	 * Set value of ProductDescription
	 * @param productdescription
	 */
	public final void setProductDescription(java.lang.String productdescription)
	{
		setProductDescription(getContext(), productdescription);
	}

	/**
	 * Set value of ProductDescription
	 * @param context
	 * @param productdescription
	 */
	public final void setProductDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productdescription)
	{
		getMendixObject().setValue(context, MemberNames.ProductDescription.toString(), productdescription);
	}

	/**
	 * @return value of OrderType
	 */
	public final java.lang.String getOrderType()
	{
		return getOrderType(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderType
	 */
	public final java.lang.String getOrderType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderType.toString());
	}

	/**
	 * Set value of OrderType
	 * @param ordertype
	 */
	public final void setOrderType(java.lang.String ordertype)
	{
		setOrderType(getContext(), ordertype);
	}

	/**
	 * Set value of OrderType
	 * @param context
	 * @param ordertype
	 */
	public final void setOrderType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ordertype)
	{
		getMendixObject().setValue(context, MemberNames.OrderType.toString(), ordertype);
	}

	/**
	 * @return value of OrderStatus
	 */
	public final java.lang.String getOrderStatus()
	{
		return getOrderStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderStatus
	 */
	public final java.lang.String getOrderStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderStatus.toString());
	}

	/**
	 * Set value of OrderStatus
	 * @param orderstatus
	 */
	public final void setOrderStatus(java.lang.String orderstatus)
	{
		setOrderStatus(getContext(), orderstatus);
	}

	/**
	 * Set value of OrderStatus
	 * @param context
	 * @param orderstatus
	 */
	public final void setOrderStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String orderstatus)
	{
		getMendixObject().setValue(context, MemberNames.OrderStatus.toString(), orderstatus);
	}

	/**
	 * @return value of PlannedStartDate
	 */
	public final java.util.Date getPlannedStartDate()
	{
		return getPlannedStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PlannedStartDate
	 */
	public final java.util.Date getPlannedStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PlannedStartDate.toString());
	}

	/**
	 * Set value of PlannedStartDate
	 * @param plannedstartdate
	 */
	public final void setPlannedStartDate(java.util.Date plannedstartdate)
	{
		setPlannedStartDate(getContext(), plannedstartdate);
	}

	/**
	 * Set value of PlannedStartDate
	 * @param context
	 * @param plannedstartdate
	 */
	public final void setPlannedStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date plannedstartdate)
	{
		getMendixObject().setValue(context, MemberNames.PlannedStartDate.toString(), plannedstartdate);
	}

	/**
	 * @return value of PlannedCompletionDate
	 */
	public final java.util.Date getPlannedCompletionDate()
	{
		return getPlannedCompletionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PlannedCompletionDate
	 */
	public final java.util.Date getPlannedCompletionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PlannedCompletionDate.toString());
	}

	/**
	 * Set value of PlannedCompletionDate
	 * @param plannedcompletiondate
	 */
	public final void setPlannedCompletionDate(java.util.Date plannedcompletiondate)
	{
		setPlannedCompletionDate(getContext(), plannedcompletiondate);
	}

	/**
	 * Set value of PlannedCompletionDate
	 * @param context
	 * @param plannedcompletiondate
	 */
	public final void setPlannedCompletionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date plannedcompletiondate)
	{
		getMendixObject().setValue(context, MemberNames.PlannedCompletionDate.toString(), plannedcompletiondate);
	}

	/**
	 * @return value of RelativePriority
	 */
	public final java.lang.String getRelativePriority()
	{
		return getRelativePriority(getContext());
	}

	/**
	 * @param context
	 * @return value of RelativePriority
	 */
	public final java.lang.String getRelativePriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RelativePriority.toString());
	}

	/**
	 * Set value of RelativePriority
	 * @param relativepriority
	 */
	public final void setRelativePriority(java.lang.String relativepriority)
	{
		setRelativePriority(getContext(), relativepriority);
	}

	/**
	 * Set value of RelativePriority
	 * @param context
	 * @param relativepriority
	 */
	public final void setRelativePriority(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relativepriority)
	{
		getMendixObject().setValue(context, MemberNames.RelativePriority.toString(), relativepriority);
	}

	/**
	 * @return value of PriorityCodeChange
	 */
	public final java.lang.String getPriorityCodeChange()
	{
		return getPriorityCodeChange(getContext());
	}

	/**
	 * @param context
	 * @return value of PriorityCodeChange
	 */
	public final java.lang.String getPriorityCodeChange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PriorityCodeChange.toString());
	}

	/**
	 * Set value of PriorityCodeChange
	 * @param prioritycodechange
	 */
	public final void setPriorityCodeChange(java.lang.String prioritycodechange)
	{
		setPriorityCodeChange(getContext(), prioritycodechange);
	}

	/**
	 * Set value of PriorityCodeChange
	 * @param context
	 * @param prioritycodechange
	 */
	public final void setPriorityCodeChange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prioritycodechange)
	{
		getMendixObject().setValue(context, MemberNames.PriorityCodeChange.toString(), prioritycodechange);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DispatchMfgOrders_OrderDispatchContext
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchContext getDispatchMfgOrders_OrderDispatchContext() throws com.mendix.core.CoreException
	{
		return getDispatchMfgOrders_OrderDispatchContext(getContext());
	}

	/**
	 * @param context
	 * @return value of DispatchMfgOrders_OrderDispatchContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchContext getDispatchMfgOrders_OrderDispatchContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.OrderDispatchContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DispatchMfgOrders_OrderDispatchContext.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.OrderDispatchContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DispatchMfgOrders_OrderDispatchContext
	 * @param dispatchmfgorders_orderdispatchcontext
	 */
	public final void setDispatchMfgOrders_OrderDispatchContext(excr_mfgordermanagement.proxies.OrderDispatchContext dispatchmfgorders_orderdispatchcontext)
	{
		setDispatchMfgOrders_OrderDispatchContext(getContext(), dispatchmfgorders_orderdispatchcontext);
	}

	/**
	 * Set value of DispatchMfgOrders_OrderDispatchContext
	 * @param context
	 * @param dispatchmfgorders_orderdispatchcontext
	 */
	public final void setDispatchMfgOrders_OrderDispatchContext(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.OrderDispatchContext dispatchmfgorders_orderdispatchcontext)
	{
		if (dispatchmfgorders_orderdispatchcontext == null) {
			getMendixObject().setValue(context, MemberNames.DispatchMfgOrders_OrderDispatchContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DispatchMfgOrders_OrderDispatchContext.toString(), dispatchmfgorders_orderdispatchcontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dispatchMfgOrdersMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement.proxies.DispatchMfgOrders that = (excr_mfgordermanagement.proxies.DispatchMfgOrders) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
