// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public enum ENUM_MfgOrderStatus
{
	NotStarted("f50a8587-dc0c-49c2-8880-c4396944451a"),
	Completed("0221f67a-f925-4cd3-9e55-c51ebba1fb79"),
	Issues("a202ae1e-760d-47fb-b6e8-92d1709dddc5"),
	InProgress("1ee98a9d-23e8-4b98-a47f-3e0ecae9bb1a");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MfgOrderStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
