// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public enum ENUM_TearDown_ProcessStatus
{
	NotStarted("72a002ae-d4a1-4158-a523-3c0b9faf78a4"),
	InProgress("630368a2-6b5a-4258-bc4f-0d7a2ef6d198"),
	Issues("1c18e5e4-e6cf-4001-a3cc-21d1d66adb11"),
	Completed("3aa6a1cc-7de2-4a0e-ba03-0b616d9df906");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_TearDown_ProcessStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
