// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public enum ENUM_SetupStatus
{
	NotStarted("7e0f5c41-fbf6-43c0-8e73-8fca38166a76"),
	InProgress("21ec0108-62ba-4440-b017-5ffc2843b85a"),
	Issues("fa5982fb-c9b4-4a5f-8f5d-f9f26fa2a489"),
	Completed("c5e76a3d-461b-4916-978a-b7e807b6b101");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_SetupStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
