// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public enum ENUM_Task_Status
{
	Not_Started("230814d2-650d-4c24-b287-43d4edcee32f"),
	InProgeess("fc6cd82d-6af9-44d3-b015-a13cfa4f62ab"),
	Issues("bda762cf-2b0c-4948-87a9-3a078bb129fb"),
	Completed("fbc89aa6-1448-4a4c-bf4d-ddceac9143eb");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Task_Status(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
