// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public enum ENUM_postEproceStatus
{
	NotStarted("e8e2c587-663e-4457-90c8-bfe563cb6bd5"),
	InProgress("c32ac2cf-d71c-454c-bc4e-18fe7ec5e5f5"),
	Issues("1f43b355-3a11-4c3a-b58e-c18114b03ec4"),
	Completed("b123d8df-1ffe-4213-9fd9-c2105bdf3c62");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_postEproceStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
