// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public class MfgOrderInfos implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mfgOrderInfosMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement.MfgOrderInfos";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MfgOrderInfos_MfgOrderInquiryRoot("EXCR_MfgOrderManagement.MfgOrderInfos_MfgOrderInquiryRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MfgOrderInfos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MfgOrderInfos(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mfgOrderInfosMendixObject)
	{
		if (mfgOrderInfosMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mfgOrderInfosMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mfgOrderInfosMendixObject = mfgOrderInfosMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement.proxies.MfgOrderInfos initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement.proxies.MfgOrderInfos(context, mendixObject);
	}

	public static excr_mfgordermanagement.proxies.MfgOrderInfos load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement.proxies.MfgOrderInfos.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MfgOrderInfos_MfgOrderInquiryRoot
	 */
	public final excr_mfgordermanagement.proxies.MfgOrderInquiryRoot getMfgOrderInfos_MfgOrderInquiryRoot() throws com.mendix.core.CoreException
	{
		return getMfgOrderInfos_MfgOrderInquiryRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrderInfos_MfgOrderInquiryRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.MfgOrderInquiryRoot getMfgOrderInfos_MfgOrderInquiryRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.MfgOrderInquiryRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MfgOrderInfos_MfgOrderInquiryRoot.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.MfgOrderInquiryRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MfgOrderInfos_MfgOrderInquiryRoot
	 * @param mfgorderinfos_mfgorderinquiryroot
	 */
	public final void setMfgOrderInfos_MfgOrderInquiryRoot(excr_mfgordermanagement.proxies.MfgOrderInquiryRoot mfgorderinfos_mfgorderinquiryroot)
	{
		setMfgOrderInfos_MfgOrderInquiryRoot(getContext(), mfgorderinfos_mfgorderinquiryroot);
	}

	/**
	 * Set value of MfgOrderInfos_MfgOrderInquiryRoot
	 * @param context
	 * @param mfgorderinfos_mfgorderinquiryroot
	 */
	public final void setMfgOrderInfos_MfgOrderInquiryRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.MfgOrderInquiryRoot mfgorderinfos_mfgorderinquiryroot)
	{
		if (mfgorderinfos_mfgorderinquiryroot == null) {
			getMendixObject().setValue(context, MemberNames.MfgOrderInfos_MfgOrderInquiryRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MfgOrderInfos_MfgOrderInquiryRoot.toString(), mfgorderinfos_mfgorderinquiryroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mfgOrderInfosMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement.proxies.MfgOrderInfos that = (excr_mfgordermanagement.proxies.MfgOrderInfos) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
