// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public class OrderDispatchDetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderDispatchDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement.OrderDispatchDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		AttachAsROR("AttachAsROR"),
		AttachmentIsROR("AttachmentIsROR"),
		AutoNumber("AutoNumber"),
		Qty("Qty"),
		IsContainer("IsContainer"),
		OrderDispatchDetails_OrderDispatchRoot("EXCR_MfgOrderManagement.OrderDispatchDetails_OrderDispatchRoot"),
		OrderDispatchLevel_OrderDispatchDetails("EXCR_MfgOrderManagement.OrderDispatchLevel_OrderDispatchDetails"),
		OrderDispatchProduct_OrderDispatchDetails("EXCR_MfgOrderManagement.OrderDispatchProduct_OrderDispatchDetails"),
		OrderDispatch_owner_OrderDispatchDetails("EXCR_MfgOrderManagement.OrderDispatch_owner_OrderDispatchDetails"),
		OrderDispatchStartReason_OrderDispatchDetails("EXCR_MfgOrderManagement.OrderDispatchStartReason_OrderDispatchDetails"),
		OrderDispatchMfgOrder_OrderDispatchDetails("EXCR_MfgOrderManagement.OrderDispatchMfgOrder_OrderDispatchDetails");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderDispatchDetailsMendixObject)
	{
		if (orderDispatchDetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!orderDispatchDetailsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderDispatchDetailsMendixObject = orderDispatchDetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement.proxies.OrderDispatchDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement.proxies.OrderDispatchDetails(context, mendixObject);
	}

	public static excr_mfgordermanagement.proxies.OrderDispatchDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement.proxies.OrderDispatchDetails.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @return value of AttachAsROR
	 */
	public final java.lang.Boolean getAttachAsROR()
	{
		return getAttachAsROR(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachAsROR
	 */
	public final java.lang.Boolean getAttachAsROR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AttachAsROR.toString());
	}

	/**
	 * Set value of AttachAsROR
	 * @param attachasror
	 */
	public final void setAttachAsROR(java.lang.Boolean attachasror)
	{
		setAttachAsROR(getContext(), attachasror);
	}

	/**
	 * Set value of AttachAsROR
	 * @param context
	 * @param attachasror
	 */
	public final void setAttachAsROR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean attachasror)
	{
		getMendixObject().setValue(context, MemberNames.AttachAsROR.toString(), attachasror);
	}

	/**
	 * @return value of AttachmentIsROR
	 */
	public final java.lang.Boolean getAttachmentIsROR()
	{
		return getAttachmentIsROR(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachmentIsROR
	 */
	public final java.lang.Boolean getAttachmentIsROR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AttachmentIsROR.toString());
	}

	/**
	 * Set value of AttachmentIsROR
	 * @param attachmentisror
	 */
	public final void setAttachmentIsROR(java.lang.Boolean attachmentisror)
	{
		setAttachmentIsROR(getContext(), attachmentisror);
	}

	/**
	 * Set value of AttachmentIsROR
	 * @param context
	 * @param attachmentisror
	 */
	public final void setAttachmentIsROR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean attachmentisror)
	{
		getMendixObject().setValue(context, MemberNames.AttachmentIsROR.toString(), attachmentisror);
	}

	/**
	 * @return value of AutoNumber
	 */
	public final java.lang.Boolean getAutoNumber()
	{
		return getAutoNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoNumber
	 */
	public final java.lang.Boolean getAutoNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AutoNumber.toString());
	}

	/**
	 * Set value of AutoNumber
	 * @param autonumber
	 */
	public final void setAutoNumber(java.lang.Boolean autonumber)
	{
		setAutoNumber(getContext(), autonumber);
	}

	/**
	 * Set value of AutoNumber
	 * @param context
	 * @param autonumber
	 */
	public final void setAutoNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean autonumber)
	{
		getMendixObject().setValue(context, MemberNames.AutoNumber.toString(), autonumber);
	}

	/**
	 * @return value of Qty
	 */
	public final java.lang.Integer getQty()
	{
		return getQty(getContext());
	}

	/**
	 * @param context
	 * @return value of Qty
	 */
	public final java.lang.Integer getQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Qty.toString());
	}

	/**
	 * Set value of Qty
	 * @param qty
	 */
	public final void setQty(java.lang.Integer qty)
	{
		setQty(getContext(), qty);
	}

	/**
	 * Set value of Qty
	 * @param context
	 * @param qty
	 */
	public final void setQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer qty)
	{
		getMendixObject().setValue(context, MemberNames.Qty.toString(), qty);
	}

	/**
	 * @return value of IsContainer
	 */
	public final java.lang.Boolean getIsContainer()
	{
		return getIsContainer(getContext());
	}

	/**
	 * @param context
	 * @return value of IsContainer
	 */
	public final java.lang.Boolean getIsContainer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsContainer.toString());
	}

	/**
	 * Set value of IsContainer
	 * @param iscontainer
	 */
	public final void setIsContainer(java.lang.Boolean iscontainer)
	{
		setIsContainer(getContext(), iscontainer);
	}

	/**
	 * Set value of IsContainer
	 * @param context
	 * @param iscontainer
	 */
	public final void setIsContainer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscontainer)
	{
		getMendixObject().setValue(context, MemberNames.IsContainer.toString(), iscontainer);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderDispatchDetails_OrderDispatchRoot
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchRoot getOrderDispatchDetails_OrderDispatchRoot() throws com.mendix.core.CoreException
	{
		return getOrderDispatchDetails_OrderDispatchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDispatchDetails_OrderDispatchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchRoot getOrderDispatchDetails_OrderDispatchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.OrderDispatchRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderDispatchDetails_OrderDispatchRoot.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.OrderDispatchRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderDispatchDetails_OrderDispatchRoot
	 * @param orderdispatchdetails_orderdispatchroot
	 */
	public final void setOrderDispatchDetails_OrderDispatchRoot(excr_mfgordermanagement.proxies.OrderDispatchRoot orderdispatchdetails_orderdispatchroot)
	{
		setOrderDispatchDetails_OrderDispatchRoot(getContext(), orderdispatchdetails_orderdispatchroot);
	}

	/**
	 * Set value of OrderDispatchDetails_OrderDispatchRoot
	 * @param context
	 * @param orderdispatchdetails_orderdispatchroot
	 */
	public final void setOrderDispatchDetails_OrderDispatchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.OrderDispatchRoot orderdispatchdetails_orderdispatchroot)
	{
		if (orderdispatchdetails_orderdispatchroot == null) {
			getMendixObject().setValue(context, MemberNames.OrderDispatchDetails_OrderDispatchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderDispatchDetails_OrderDispatchRoot.toString(), orderdispatchdetails_orderdispatchroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderDispatchLevel_OrderDispatchDetails
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchLevel getOrderDispatchLevel_OrderDispatchDetails() throws com.mendix.core.CoreException
	{
		return getOrderDispatchLevel_OrderDispatchDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDispatchLevel_OrderDispatchDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchLevel getOrderDispatchLevel_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.OrderDispatchLevel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderDispatchLevel_OrderDispatchDetails.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.OrderDispatchLevel.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderDispatchLevel_OrderDispatchDetails
	 * @param orderdispatchlevel_orderdispatchdetails
	 */
	public final void setOrderDispatchLevel_OrderDispatchDetails(excr_mfgordermanagement.proxies.OrderDispatchLevel orderdispatchlevel_orderdispatchdetails)
	{
		setOrderDispatchLevel_OrderDispatchDetails(getContext(), orderdispatchlevel_orderdispatchdetails);
	}

	/**
	 * Set value of OrderDispatchLevel_OrderDispatchDetails
	 * @param context
	 * @param orderdispatchlevel_orderdispatchdetails
	 */
	public final void setOrderDispatchLevel_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.OrderDispatchLevel orderdispatchlevel_orderdispatchdetails)
	{
		if (orderdispatchlevel_orderdispatchdetails == null) {
			getMendixObject().setValue(context, MemberNames.OrderDispatchLevel_OrderDispatchDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderDispatchLevel_OrderDispatchDetails.toString(), orderdispatchlevel_orderdispatchdetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderDispatchProduct_OrderDispatchDetails
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchProduct getOrderDispatchProduct_OrderDispatchDetails() throws com.mendix.core.CoreException
	{
		return getOrderDispatchProduct_OrderDispatchDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDispatchProduct_OrderDispatchDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchProduct getOrderDispatchProduct_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.OrderDispatchProduct result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderDispatchProduct_OrderDispatchDetails.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.OrderDispatchProduct.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderDispatchProduct_OrderDispatchDetails
	 * @param orderdispatchproduct_orderdispatchdetails
	 */
	public final void setOrderDispatchProduct_OrderDispatchDetails(excr_mfgordermanagement.proxies.OrderDispatchProduct orderdispatchproduct_orderdispatchdetails)
	{
		setOrderDispatchProduct_OrderDispatchDetails(getContext(), orderdispatchproduct_orderdispatchdetails);
	}

	/**
	 * Set value of OrderDispatchProduct_OrderDispatchDetails
	 * @param context
	 * @param orderdispatchproduct_orderdispatchdetails
	 */
	public final void setOrderDispatchProduct_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.OrderDispatchProduct orderdispatchproduct_orderdispatchdetails)
	{
		if (orderdispatchproduct_orderdispatchdetails == null) {
			getMendixObject().setValue(context, MemberNames.OrderDispatchProduct_OrderDispatchDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderDispatchProduct_OrderDispatchDetails.toString(), orderdispatchproduct_orderdispatchdetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderDispatch_owner_OrderDispatchDetails
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatch_owner getOrderDispatch_owner_OrderDispatchDetails() throws com.mendix.core.CoreException
	{
		return getOrderDispatch_owner_OrderDispatchDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDispatch_owner_OrderDispatchDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatch_owner getOrderDispatch_owner_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.OrderDispatch_owner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderDispatch_owner_OrderDispatchDetails.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.OrderDispatch_owner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderDispatch_owner_OrderDispatchDetails
	 * @param orderdispatch_owner_orderdispatchdetails
	 */
	public final void setOrderDispatch_owner_OrderDispatchDetails(excr_mfgordermanagement.proxies.OrderDispatch_owner orderdispatch_owner_orderdispatchdetails)
	{
		setOrderDispatch_owner_OrderDispatchDetails(getContext(), orderdispatch_owner_orderdispatchdetails);
	}

	/**
	 * Set value of OrderDispatch_owner_OrderDispatchDetails
	 * @param context
	 * @param orderdispatch_owner_orderdispatchdetails
	 */
	public final void setOrderDispatch_owner_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.OrderDispatch_owner orderdispatch_owner_orderdispatchdetails)
	{
		if (orderdispatch_owner_orderdispatchdetails == null) {
			getMendixObject().setValue(context, MemberNames.OrderDispatch_owner_OrderDispatchDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderDispatch_owner_OrderDispatchDetails.toString(), orderdispatch_owner_orderdispatchdetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderDispatchStartReason_OrderDispatchDetails
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchStartReason getOrderDispatchStartReason_OrderDispatchDetails() throws com.mendix.core.CoreException
	{
		return getOrderDispatchStartReason_OrderDispatchDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDispatchStartReason_OrderDispatchDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchStartReason getOrderDispatchStartReason_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.OrderDispatchStartReason result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderDispatchStartReason_OrderDispatchDetails.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.OrderDispatchStartReason.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderDispatchStartReason_OrderDispatchDetails
	 * @param orderdispatchstartreason_orderdispatchdetails
	 */
	public final void setOrderDispatchStartReason_OrderDispatchDetails(excr_mfgordermanagement.proxies.OrderDispatchStartReason orderdispatchstartreason_orderdispatchdetails)
	{
		setOrderDispatchStartReason_OrderDispatchDetails(getContext(), orderdispatchstartreason_orderdispatchdetails);
	}

	/**
	 * Set value of OrderDispatchStartReason_OrderDispatchDetails
	 * @param context
	 * @param orderdispatchstartreason_orderdispatchdetails
	 */
	public final void setOrderDispatchStartReason_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.OrderDispatchStartReason orderdispatchstartreason_orderdispatchdetails)
	{
		if (orderdispatchstartreason_orderdispatchdetails == null) {
			getMendixObject().setValue(context, MemberNames.OrderDispatchStartReason_OrderDispatchDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderDispatchStartReason_OrderDispatchDetails.toString(), orderdispatchstartreason_orderdispatchdetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderDispatchMfgOrder_OrderDispatchDetails
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchMfgOrder getOrderDispatchMfgOrder_OrderDispatchDetails() throws com.mendix.core.CoreException
	{
		return getOrderDispatchMfgOrder_OrderDispatchDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDispatchMfgOrder_OrderDispatchDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchMfgOrder getOrderDispatchMfgOrder_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.OrderDispatchMfgOrder result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderDispatchMfgOrder_OrderDispatchDetails.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.OrderDispatchMfgOrder.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderDispatchMfgOrder_OrderDispatchDetails
	 * @param orderdispatchmfgorder_orderdispatchdetails
	 */
	public final void setOrderDispatchMfgOrder_OrderDispatchDetails(excr_mfgordermanagement.proxies.OrderDispatchMfgOrder orderdispatchmfgorder_orderdispatchdetails)
	{
		setOrderDispatchMfgOrder_OrderDispatchDetails(getContext(), orderdispatchmfgorder_orderdispatchdetails);
	}

	/**
	 * Set value of OrderDispatchMfgOrder_OrderDispatchDetails
	 * @param context
	 * @param orderdispatchmfgorder_orderdispatchdetails
	 */
	public final void setOrderDispatchMfgOrder_OrderDispatchDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.OrderDispatchMfgOrder orderdispatchmfgorder_orderdispatchdetails)
	{
		if (orderdispatchmfgorder_orderdispatchdetails == null) {
			getMendixObject().setValue(context, MemberNames.OrderDispatchMfgOrder_OrderDispatchDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderDispatchMfgOrder_OrderDispatchDetails.toString(), orderdispatchmfgorder_orderdispatchdetails.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderDispatchDetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement.proxies.OrderDispatchDetails that = (excr_mfgordermanagement.proxies.OrderDispatchDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
