// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public class OrderDispatchRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderDispatchRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement.OrderDispatchRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderDispatchDetails_OrderDispatchRoot("EXCR_MfgOrderManagement.OrderDispatchDetails_OrderDispatchRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OrderDispatchRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OrderDispatchRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderDispatchRootMendixObject)
	{
		if (orderDispatchRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!orderDispatchRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderDispatchRootMendixObject = orderDispatchRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement.proxies.OrderDispatchRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement.proxies.OrderDispatchRoot(context, mendixObject);
	}

	public static excr_mfgordermanagement.proxies.OrderDispatchRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement.proxies.OrderDispatchRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderDispatchDetails_OrderDispatchRoot
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchDetails getOrderDispatchDetails_OrderDispatchRoot() throws com.mendix.core.CoreException
	{
		return getOrderDispatchDetails_OrderDispatchRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDispatchDetails_OrderDispatchRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.OrderDispatchDetails getOrderDispatchDetails_OrderDispatchRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.OrderDispatchDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderDispatchDetails_OrderDispatchRoot.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.OrderDispatchDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderDispatchDetails_OrderDispatchRoot
	 * @param orderdispatchdetails_orderdispatchroot
	 */
	public final void setOrderDispatchDetails_OrderDispatchRoot(excr_mfgordermanagement.proxies.OrderDispatchDetails orderdispatchdetails_orderdispatchroot)
	{
		setOrderDispatchDetails_OrderDispatchRoot(getContext(), orderdispatchdetails_orderdispatchroot);
	}

	/**
	 * Set value of OrderDispatchDetails_OrderDispatchRoot
	 * @param context
	 * @param orderdispatchdetails_orderdispatchroot
	 */
	public final void setOrderDispatchDetails_OrderDispatchRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.OrderDispatchDetails orderdispatchdetails_orderdispatchroot)
	{
		if (orderdispatchdetails_orderdispatchroot == null) {
			getMendixObject().setValue(context, MemberNames.OrderDispatchDetails_OrderDispatchRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderDispatchDetails_OrderDispatchRoot.toString(), orderdispatchdetails_orderdispatchroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderDispatchRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement.proxies.OrderDispatchRoot that = (excr_mfgordermanagement.proxies.OrderDispatchRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
