// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public class TaskItemInfos implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskItemInfosMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement.TaskItemInfos";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TaskItemInfos_TaskListInfo("EXCR_MfgOrderManagement.TaskItemInfos_TaskListInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaskItemInfos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TaskItemInfos(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskItemInfosMendixObject)
	{
		if (taskItemInfosMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!taskItemInfosMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.taskItemInfosMendixObject = taskItemInfosMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement.proxies.TaskItemInfos initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement.proxies.TaskItemInfos(context, mendixObject);
	}

	public static excr_mfgordermanagement.proxies.TaskItemInfos load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement.proxies.TaskItemInfos.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskItemInfos_TaskListInfo
	 */
	public final excr_mfgordermanagement.proxies.TaskListInfo getTaskItemInfos_TaskListInfo() throws com.mendix.core.CoreException
	{
		return getTaskItemInfos_TaskListInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskItemInfos_TaskListInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.TaskListInfo getTaskItemInfos_TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.TaskListInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskItemInfos_TaskListInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.TaskListInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskItemInfos_TaskListInfo
	 * @param taskiteminfos_tasklistinfo
	 */
	public final void setTaskItemInfos_TaskListInfo(excr_mfgordermanagement.proxies.TaskListInfo taskiteminfos_tasklistinfo)
	{
		setTaskItemInfos_TaskListInfo(getContext(), taskiteminfos_tasklistinfo);
	}

	/**
	 * Set value of TaskItemInfos_TaskListInfo
	 * @param context
	 * @param taskiteminfos_tasklistinfo
	 */
	public final void setTaskItemInfos_TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.TaskListInfo taskiteminfos_tasklistinfo)
	{
		if (taskiteminfos_tasklistinfo == null) {
			getMendixObject().setValue(context, MemberNames.TaskItemInfos_TaskListInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskItemInfos_TaskListInfo.toString(), taskiteminfos_tasklistinfo.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskItemInfosMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement.proxies.TaskItemInfos that = (excr_mfgordermanagement.proxies.TaskItemInfos) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
