// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public class TaskListInfo implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskListInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement.TaskListInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		State("State"),
		StatusTaskChanged("StatusTaskChanged"),
		TaskListImageIdentifier("TaskListImageIdentifier"),
		TaskListImageBrowseMode("TaskListImageBrowseMode"),
		TaskListInfo_TaskListInfos("EXCR_MfgOrderManagement.TaskListInfo_TaskListInfos"),
		TaskList_TaskListInfo("EXCR_MfgOrderManagement.TaskList_TaskListInfo"),
		TaskItemInfos_TaskListInfo("EXCR_MfgOrderManagement.TaskItemInfos_TaskListInfo"),
		TaskListImage_TaskListInfo("EXCR_MfgOrderManagement.TaskListImage_TaskListInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskListInfoMendixObject)
	{
		if (taskListInfoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!taskListInfoMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.taskListInfoMendixObject = taskListInfoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement.proxies.TaskListInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement.proxies.TaskListInfo(context, mendixObject);
	}

	public static excr_mfgordermanagement.proxies.TaskListInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement.proxies.TaskListInfo.initialize(context, mendixObject);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.Integer getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.Integer getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.Integer state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of StatusTaskChanged
	 */
	public final java.lang.Boolean getStatusTaskChanged()
	{
		return getStatusTaskChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusTaskChanged
	 */
	public final java.lang.Boolean getStatusTaskChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.StatusTaskChanged.toString());
	}

	/**
	 * Set value of StatusTaskChanged
	 * @param statustaskchanged
	 */
	public final void setStatusTaskChanged(java.lang.Boolean statustaskchanged)
	{
		setStatusTaskChanged(getContext(), statustaskchanged);
	}

	/**
	 * Set value of StatusTaskChanged
	 * @param context
	 * @param statustaskchanged
	 */
	public final void setStatusTaskChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean statustaskchanged)
	{
		getMendixObject().setValue(context, MemberNames.StatusTaskChanged.toString(), statustaskchanged);
	}

	/**
	 * @return value of TaskListImageIdentifier
	 */
	public final java.lang.String getTaskListImageIdentifier()
	{
		return getTaskListImageIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskListImageIdentifier
	 */
	public final java.lang.String getTaskListImageIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskListImageIdentifier.toString());
	}

	/**
	 * Set value of TaskListImageIdentifier
	 * @param tasklistimageidentifier
	 */
	public final void setTaskListImageIdentifier(java.lang.String tasklistimageidentifier)
	{
		setTaskListImageIdentifier(getContext(), tasklistimageidentifier);
	}

	/**
	 * Set value of TaskListImageIdentifier
	 * @param context
	 * @param tasklistimageidentifier
	 */
	public final void setTaskListImageIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tasklistimageidentifier)
	{
		getMendixObject().setValue(context, MemberNames.TaskListImageIdentifier.toString(), tasklistimageidentifier);
	}

	/**
	 * @return value of TaskListImageBrowseMode
	 */
	public final java.lang.Integer getTaskListImageBrowseMode()
	{
		return getTaskListImageBrowseMode(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskListImageBrowseMode
	 */
	public final java.lang.Integer getTaskListImageBrowseMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TaskListImageBrowseMode.toString());
	}

	/**
	 * Set value of TaskListImageBrowseMode
	 * @param tasklistimagebrowsemode
	 */
	public final void setTaskListImageBrowseMode(java.lang.Integer tasklistimagebrowsemode)
	{
		setTaskListImageBrowseMode(getContext(), tasklistimagebrowsemode);
	}

	/**
	 * Set value of TaskListImageBrowseMode
	 * @param context
	 * @param tasklistimagebrowsemode
	 */
	public final void setTaskListImageBrowseMode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer tasklistimagebrowsemode)
	{
		getMendixObject().setValue(context, MemberNames.TaskListImageBrowseMode.toString(), tasklistimagebrowsemode);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskListInfo_TaskListInfos
	 */
	public final excr_mfgordermanagement.proxies.TaskListInfos getTaskListInfo_TaskListInfos() throws com.mendix.core.CoreException
	{
		return getTaskListInfo_TaskListInfos(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskListInfo_TaskListInfos
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.TaskListInfos getTaskListInfo_TaskListInfos(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.TaskListInfos result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskListInfo_TaskListInfos.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.TaskListInfos.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskListInfo_TaskListInfos
	 * @param tasklistinfo_tasklistinfos
	 */
	public final void setTaskListInfo_TaskListInfos(excr_mfgordermanagement.proxies.TaskListInfos tasklistinfo_tasklistinfos)
	{
		setTaskListInfo_TaskListInfos(getContext(), tasklistinfo_tasklistinfos);
	}

	/**
	 * Set value of TaskListInfo_TaskListInfos
	 * @param context
	 * @param tasklistinfo_tasklistinfos
	 */
	public final void setTaskListInfo_TaskListInfos(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.TaskListInfos tasklistinfo_tasklistinfos)
	{
		if (tasklistinfo_tasklistinfos == null) {
			getMendixObject().setValue(context, MemberNames.TaskListInfo_TaskListInfos.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskListInfo_TaskListInfos.toString(), tasklistinfo_tasklistinfos.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_TaskListInfo
	 */
	public final excr_mfgordermanagement.proxies.TaskList getTaskList_TaskListInfo() throws com.mendix.core.CoreException
	{
		return getTaskList_TaskListInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_TaskListInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.TaskList getTaskList_TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.TaskList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_TaskListInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.TaskList.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_TaskListInfo
	 * @param tasklist_tasklistinfo
	 */
	public final void setTaskList_TaskListInfo(excr_mfgordermanagement.proxies.TaskList tasklist_tasklistinfo)
	{
		setTaskList_TaskListInfo(getContext(), tasklist_tasklistinfo);
	}

	/**
	 * Set value of TaskList_TaskListInfo
	 * @param context
	 * @param tasklist_tasklistinfo
	 */
	public final void setTaskList_TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.TaskList tasklist_tasklistinfo)
	{
		if (tasklist_tasklistinfo == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_TaskListInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_TaskListInfo.toString(), tasklist_tasklistinfo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskItemInfos_TaskListInfo
	 */
	public final excr_mfgordermanagement.proxies.TaskItemInfos getTaskItemInfos_TaskListInfo() throws com.mendix.core.CoreException
	{
		return getTaskItemInfos_TaskListInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskItemInfos_TaskListInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.TaskItemInfos getTaskItemInfos_TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.TaskItemInfos result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskItemInfos_TaskListInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.TaskItemInfos.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskItemInfos_TaskListInfo
	 * @param taskiteminfos_tasklistinfo
	 */
	public final void setTaskItemInfos_TaskListInfo(excr_mfgordermanagement.proxies.TaskItemInfos taskiteminfos_tasklistinfo)
	{
		setTaskItemInfos_TaskListInfo(getContext(), taskiteminfos_tasklistinfo);
	}

	/**
	 * Set value of TaskItemInfos_TaskListInfo
	 * @param context
	 * @param taskiteminfos_tasklistinfo
	 */
	public final void setTaskItemInfos_TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.TaskItemInfos taskiteminfos_tasklistinfo)
	{
		if (taskiteminfos_tasklistinfo == null) {
			getMendixObject().setValue(context, MemberNames.TaskItemInfos_TaskListInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskItemInfos_TaskListInfo.toString(), taskiteminfos_tasklistinfo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskListImage_TaskListInfo
	 */
	public final excr_mfgordermanagement.proxies.TaskListImage getTaskListImage_TaskListInfo() throws com.mendix.core.CoreException
	{
		return getTaskListImage_TaskListInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskListImage_TaskListInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.TaskListImage getTaskListImage_TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.TaskListImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskListImage_TaskListInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.TaskListImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskListImage_TaskListInfo
	 * @param tasklistimage_tasklistinfo
	 */
	public final void setTaskListImage_TaskListInfo(excr_mfgordermanagement.proxies.TaskListImage tasklistimage_tasklistinfo)
	{
		setTaskListImage_TaskListInfo(getContext(), tasklistimage_tasklistinfo);
	}

	/**
	 * Set value of TaskListImage_TaskListInfo
	 * @param context
	 * @param tasklistimage_tasklistinfo
	 */
	public final void setTaskListImage_TaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.TaskListImage tasklistimage_tasklistinfo)
	{
		if (tasklistimage_tasklistinfo == null) {
			getMendixObject().setValue(context, MemberNames.TaskListImage_TaskListInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskListImage_TaskListInfo.toString(), tasklistimage_tasklistinfo.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskListInfoMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement.proxies.TaskListInfo that = (excr_mfgordermanagement.proxies.TaskListInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
