// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public class TaskItemComment implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskItemCommentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement.TaskItemComment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Comment("Comment"),
		TaskItemComment_TaskItemInfo("EXCR_MfgOrderManagement.TaskItemComment_TaskItemInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaskItemComment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TaskItemComment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskItemCommentMendixObject)
	{
		if (taskItemCommentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!taskItemCommentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.taskItemCommentMendixObject = taskItemCommentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement.proxies.TaskItemComment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement.proxies.TaskItemComment(context, mendixObject);
	}

	public static excr_mfgordermanagement.proxies.TaskItemComment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement.proxies.TaskItemComment.initialize(context, mendixObject);
	}

	/**
	 * @return value of Comment
	 */
	public final java.lang.String getComment()
	{
		return getComment(getContext());
	}

	/**
	 * @param context
	 * @return value of Comment
	 */
	public final java.lang.String getComment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comment.toString());
	}

	/**
	 * Set value of Comment
	 * @param comment
	 */
	public final void setComment(java.lang.String comment)
	{
		setComment(getContext(), comment);
	}

	/**
	 * Set value of Comment
	 * @param context
	 * @param comment
	 */
	public final void setComment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comment)
	{
		getMendixObject().setValue(context, MemberNames.Comment.toString(), comment);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskItemComment_TaskItemInfo
	 */
	public final excr_mfgordermanagement.proxies.TaskItemInfo getTaskItemComment_TaskItemInfo() throws com.mendix.core.CoreException
	{
		return getTaskItemComment_TaskItemInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskItemComment_TaskItemInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement.proxies.TaskItemInfo getTaskItemComment_TaskItemInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement.proxies.TaskItemInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskItemComment_TaskItemInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement.proxies.TaskItemInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskItemComment_TaskItemInfo
	 * @param taskitemcomment_taskiteminfo
	 */
	public final void setTaskItemComment_TaskItemInfo(excr_mfgordermanagement.proxies.TaskItemInfo taskitemcomment_taskiteminfo)
	{
		setTaskItemComment_TaskItemInfo(getContext(), taskitemcomment_taskiteminfo);
	}

	/**
	 * Set value of TaskItemComment_TaskItemInfo
	 * @param context
	 * @param taskitemcomment_taskiteminfo
	 */
	public final void setTaskItemComment_TaskItemInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement.proxies.TaskItemInfo taskitemcomment_taskiteminfo)
	{
		if (taskitemcomment_taskiteminfo == null) {
			getMendixObject().setValue(context, MemberNames.TaskItemComment_TaskItemInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskItemComment_TaskItemInfo.toString(), taskitemcomment_taskiteminfo.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskItemCommentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement.proxies.TaskItemComment that = (excr_mfgordermanagement.proxies.TaskItemComment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
