// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement.proxies;

public enum TearDownStatus
{
	NotStarted("4971c112-1dab-430c-851c-75b83763e550"),
	InProgress("ca1eccc7-a3c3-4409-86a4-be1612dc813d"),
	Issues("0150cc50-7a36-4be0-90f1-4c6a5462bbef"),
	Completed("1cf252c0-4042-4d89-88e7-beee8c01edf8");

	private final java.lang.String i18nCaptionKey;
	
	private TearDownStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
