// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_operatorlog.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the EXCR_OperatorLog module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AttachOpDocBuilder(
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context,
		excr_operatorlog.proxies.Doc _doc
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_OperatorLog.ACT_AttachOpDoc");
		builder = builder.withParam("OperatorLog_Context", _operatorLog_Context);
		builder = builder.withParam("Doc", _doc);
		return builder;
	}

	public static excr_commons.proxies.Notification aCT_AttachOpDoc(
		IContext context,
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context,
		excr_operatorlog.proxies.Doc _doc
	)
	{
		Object result = aCT_AttachOpDocBuilder(
				_operatorLog_Context,
				_doc
			)
			.execute(context);
		return result == null ? null : excr_commons.proxies.Notification.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GetAllOpEntries_FromOpNameBuilder(
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_OperatorLog.ACT_GetAllOpEntries_FromOpName");
		builder = builder.withParam("OperatorLog_Context", _operatorLog_Context);
		return builder;
	}

	public static java.util.List<excr_operatorlog.proxies.LogEntries> aCT_GetAllOpEntries_FromOpName(
		IContext context,
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context
	)
	{
		Object result = aCT_GetAllOpEntries_FromOpNameBuilder(
				_operatorLog_Context
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> excr_operatorlog.proxies.LogEntries.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GetLogTypesBuilder(
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_OperatorLog.ACT_GetLogTypes");
		builder = builder.withParam("OperatorLog_Context", _operatorLog_Context);
		return builder;
	}

	public static java.util.List<excr_operatorlog.proxies.LogType> aCT_GetLogTypes(
		IContext context,
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context
	)
	{
		Object result = aCT_GetLogTypesBuilder(
				_operatorLog_Context
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> excr_operatorlog.proxies.LogType.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GetOpEntriesBuilder(
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_OperatorLog.ACT_GetOpEntries");
		builder = builder.withParam("OperatorLog_Context", _operatorLog_Context);
		return builder;
	}

	public static java.util.List<excr_operatorlog.proxies.LogEntries> aCT_GetOpEntries(
		IContext context,
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context
	)
	{
		Object result = aCT_GetOpEntriesBuilder(
				_operatorLog_Context
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> excr_operatorlog.proxies.LogEntries.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GetOpLogsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_OperatorLog.ACT_GetOpLogs");
		return builder;
	}

	public static java.util.List<excr_operatorlog.proxies.OperatorLog> aCT_GetOpLogs(IContext context)
	{
		Object result = aCT_GetOpLogsBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> excr_operatorlog.proxies.OperatorLog.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SubmitOpLogBuilder(
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_OperatorLog.ACT_SubmitOpLog");
		builder = builder.withParam("OperatorLog_Context", _operatorLog_Context);
		return builder;
	}

	public static excr_commons.proxies.Notification aCT_SubmitOpLog(
		IContext context,
		excr_operatorlog.proxies.OperatorLog_Context _operatorLog_Context
	)
	{
		Object result = aCT_SubmitOpLogBuilder(
				_operatorLog_Context
			)
			.execute(context);
		return result == null ? null : excr_commons.proxies.Notification.initialize(context, (IMendixObject) result);
	}
}
