// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} tableClass
 * @returns {Promise.<boolean>}
 */
export async function IsCheckGridSelection(tableClass) {
	// BEGIN USER CODE
	try {
		if (!tableClass) {
			console.error("🚫 Error: 'tableClass' parameter is missing.");
			return false;
		}

		const table = document.querySelector(`.${tableClass}`);

		if (!table) {
			console.warn(`⚠️ Warning: No table found with class '${tableClass}'`);
			return false;
		}

		const checkboxes = table.querySelectorAll('input[type="checkbox"]');
		const isAnyChecked = Array.from(checkboxes).some(cb => cb.checked);

		console.log(`✅ Checkbox check completed. Any checked: ${isAnyChecked}`);
		return isAnyChecked;

	} catch (error) {
		console.error("🔥 Exception in IsCheckGridSelection:", error);
		return false;
	}
	// END USER CODE
}
