// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} divClassName - div class name
 * @returns {Promise.<void>}
 */
export async function SetCursorPrefixCustomDropdown(divClassName) {
	// BEGIN USER CODE
	  try {
        setTimeout(() => {
            // Dynamically build class selector from parameter
            const wrapper = document.querySelector(`.${divClassName}`);

            if (wrapper) {
                const input = wrapper.querySelector(
                    '.PrefixCustomDropdown__input[role="combobox"][tabindex="0"]'
                );

                if (input) {
                    input.focus();
                    console.log(`Dropdown input focused inside .${divClassName}`);
                } else {
                    console.error(`Dropdown input not found inside .${divClassName}`);
                }
            } else {
                console.error(`Container .${divClassName} not found.`);
            }
        }, 100); // Adjust delay if needed
    } catch (error) {
        console.error('Error in SetCursorPrefixCustomDropdown:', error);
    }
	// END USER CODE
}
