// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("ce5e8304-74c9-4b29-9f18-98bced14d6f0"),
	low("ff96a472-0ea7-432a-9a5d-2a33df72f22f"),
	medium("bc2636ae-dfc2-4eec-874f-5ad6d3553f41"),
	high("afced6e5-40fc-4f70-be93-fc4d5c1f344e"),
	custom("ce835972-f1cd-4497-bd3f-bd88401ded49");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
