// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement_api.proxies;

public class MfgOrderInfoData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mfgOrderInfoDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement_API.MfgOrderInfoData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceID("InstanceID"),
		CompletedQty("CompletedQty"),
		OrderPlannedCompletionDate("OrderPlannedCompletionDate"),
		OrderPlannedStartDate("OrderPlannedStartDate"),
		OrderQty("OrderQty"),
		PostProductionCompleteDate("PostProductionCompleteDate"),
		PostProductionCompleteDateGMT("PostProductionCompleteDateGMT"),
		PostProductionProcedureState("PostProductionProcedureState"),
		PostProductionStartDate("PostProductionStartDate"),
		PostProductionStartDateGMT("PostProductionStartDateGMT"),
		PreProductionCompleteDate("PreProductionCompleteDate"),
		PreProductionCompleteDateGMT("PreProductionCompleteDateGMT"),
		PreProductionProcedureState("PreProductionProcedureState"),
		PreProductionStartDate("PreProductionStartDate"),
		PreProductionStartDateGMT("PreProductionStartDateGMT"),
		ProductionComplete("ProductionComplete"),
		ProductionCompleteDate("ProductionCompleteDate"),
		ProductionCompleteDateGMT("ProductionCompleteDateGMT"),
		ProductionStartDate("ProductionStartDate"),
		ProductionStartDateGMT("ProductionStartDateGMT"),
		ProductPlannedCost("ProductPlannedCost"),
		ScrapQty("ScrapQty"),
		OrderStatus("OrderStatus"),
		PreProductionTotalCompletionHour("PreProductionTotalCompletionHour"),
		PostProductionTotalCompletionHour("PostProductionTotalCompletionHour"),
		ProductionTotalCompletionHour("ProductionTotalCompletionHour"),
		OnTimeHour("OnTimeHour"),
		TargetTimePre("TargetTimePre"),
		ProductImageIdentifier("ProductImageIdentifier"),
		PreState("PreState"),
		PostState("PostState"),
		PreProductionProcedureInfoSet("PreProductionProcedureInfoSet"),
		PostProductionProcedureInfoSet("PostProductionProcedureInfoSet"),
		OrderPlannedCompletionDateGMT("OrderPlannedCompletionDateGMT"),
		OrderPlannedStartDateGMT("OrderPlannedStartDateGMT"),
		daysBetweenPreStartCompletedDate("daysBetweenPreStartCompletedDate"),
		TargetTimePost("TargetTimePost"),
		daysBetweenPostStartCompletedDate("daysBetweenPostStartCompletedDate"),
		EnableStartButton("EnableStartButton"),
		ProductImageBrowseMode("ProductImageBrowseMode"),
		MfgOrder_MfgOrderInfoData("EXCR_MfgOrderManagement_API.MfgOrder_MfgOrderInfoData"),
		Product_MfgOrderInfoData("EXCR_MfgOrderManagement_API.Product_MfgOrderInfoData"),
		PreProductionProcedureInfo_MfgOrderInfoData("EXCR_MfgOrderManagement_API.PreProductionProcedureInfo_MfgOrderInfoData"),
		PostProductionProcedureInfo_MfgOrderInfoData("EXCR_MfgOrderManagement_API.PostProductionProcedureInfo_MfgOrderInfoData"),
		ProductImage_MfgOrderInfoData("EXCR_MfgOrderManagement_API.ProductImage_MfgOrderInfoData"),
		MfgOrderInfoData_ImageConvert("EXCR_MfgOrderManagement_API.MfgOrderInfoData_ImageConvert");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mfgOrderInfoDataMendixObject)
	{
		if (mfgOrderInfoDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mfgOrderInfoDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mfgOrderInfoDataMendixObject = mfgOrderInfoDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement_api.proxies.MfgOrderInfoData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement_api.proxies.MfgOrderInfoData(context, mendixObject);
	}

	public static excr_mfgordermanagement_api.proxies.MfgOrderInfoData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement_api.proxies.MfgOrderInfoData.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID()
	{
		return getInstanceID(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceID.toString());
	}

	/**
	 * Set value of InstanceID
	 * @param instanceid
	 */
	public final void setInstanceID(java.lang.String instanceid)
	{
		setInstanceID(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceID
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceID.toString(), instanceid);
	}

	/**
	 * @return value of CompletedQty
	 */
	public final java.math.BigDecimal getCompletedQty()
	{
		return getCompletedQty(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletedQty
	 */
	public final java.math.BigDecimal getCompletedQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.CompletedQty.toString());
	}

	/**
	 * Set value of CompletedQty
	 * @param completedqty
	 */
	public final void setCompletedQty(java.math.BigDecimal completedqty)
	{
		setCompletedQty(getContext(), completedqty);
	}

	/**
	 * Set value of CompletedQty
	 * @param context
	 * @param completedqty
	 */
	public final void setCompletedQty(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal completedqty)
	{
		getMendixObject().setValue(context, MemberNames.CompletedQty.toString(), completedqty);
	}

	/**
	 * @return value of OrderPlannedCompletionDate
	 */
	public final java.util.Date getOrderPlannedCompletionDate()
	{
		return getOrderPlannedCompletionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderPlannedCompletionDate
	 */
	public final java.util.Date getOrderPlannedCompletionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderPlannedCompletionDate.toString());
	}

	/**
	 * Set value of OrderPlannedCompletionDate
	 * @param orderplannedcompletiondate
	 */
	public final void setOrderPlannedCompletionDate(java.util.Date orderplannedcompletiondate)
	{
		setOrderPlannedCompletionDate(getContext(), orderplannedcompletiondate);
	}

	/**
	 * Set value of OrderPlannedCompletionDate
	 * @param context
	 * @param orderplannedcompletiondate
	 */
	public final void setOrderPlannedCompletionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderplannedcompletiondate)
	{
		getMendixObject().setValue(context, MemberNames.OrderPlannedCompletionDate.toString(), orderplannedcompletiondate);
	}

	/**
	 * @return value of OrderPlannedStartDate
	 */
	public final java.util.Date getOrderPlannedStartDate()
	{
		return getOrderPlannedStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderPlannedStartDate
	 */
	public final java.util.Date getOrderPlannedStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderPlannedStartDate.toString());
	}

	/**
	 * Set value of OrderPlannedStartDate
	 * @param orderplannedstartdate
	 */
	public final void setOrderPlannedStartDate(java.util.Date orderplannedstartdate)
	{
		setOrderPlannedStartDate(getContext(), orderplannedstartdate);
	}

	/**
	 * Set value of OrderPlannedStartDate
	 * @param context
	 * @param orderplannedstartdate
	 */
	public final void setOrderPlannedStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderplannedstartdate)
	{
		getMendixObject().setValue(context, MemberNames.OrderPlannedStartDate.toString(), orderplannedstartdate);
	}

	/**
	 * @return value of OrderQty
	 */
	public final java.math.BigDecimal getOrderQty()
	{
		return getOrderQty(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderQty
	 */
	public final java.math.BigDecimal getOrderQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.OrderQty.toString());
	}

	/**
	 * Set value of OrderQty
	 * @param orderqty
	 */
	public final void setOrderQty(java.math.BigDecimal orderqty)
	{
		setOrderQty(getContext(), orderqty);
	}

	/**
	 * Set value of OrderQty
	 * @param context
	 * @param orderqty
	 */
	public final void setOrderQty(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal orderqty)
	{
		getMendixObject().setValue(context, MemberNames.OrderQty.toString(), orderqty);
	}

	/**
	 * @return value of PostProductionCompleteDate
	 */
	public final java.util.Date getPostProductionCompleteDate()
	{
		return getPostProductionCompleteDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PostProductionCompleteDate
	 */
	public final java.util.Date getPostProductionCompleteDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PostProductionCompleteDate.toString());
	}

	/**
	 * Set value of PostProductionCompleteDate
	 * @param postproductioncompletedate
	 */
	public final void setPostProductionCompleteDate(java.util.Date postproductioncompletedate)
	{
		setPostProductionCompleteDate(getContext(), postproductioncompletedate);
	}

	/**
	 * Set value of PostProductionCompleteDate
	 * @param context
	 * @param postproductioncompletedate
	 */
	public final void setPostProductionCompleteDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date postproductioncompletedate)
	{
		getMendixObject().setValue(context, MemberNames.PostProductionCompleteDate.toString(), postproductioncompletedate);
	}

	/**
	 * @return value of PostProductionCompleteDateGMT
	 */
	public final java.util.Date getPostProductionCompleteDateGMT()
	{
		return getPostProductionCompleteDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of PostProductionCompleteDateGMT
	 */
	public final java.util.Date getPostProductionCompleteDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PostProductionCompleteDateGMT.toString());
	}

	/**
	 * Set value of PostProductionCompleteDateGMT
	 * @param postproductioncompletedategmt
	 */
	public final void setPostProductionCompleteDateGMT(java.util.Date postproductioncompletedategmt)
	{
		setPostProductionCompleteDateGMT(getContext(), postproductioncompletedategmt);
	}

	/**
	 * Set value of PostProductionCompleteDateGMT
	 * @param context
	 * @param postproductioncompletedategmt
	 */
	public final void setPostProductionCompleteDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date postproductioncompletedategmt)
	{
		getMendixObject().setValue(context, MemberNames.PostProductionCompleteDateGMT.toString(), postproductioncompletedategmt);
	}

	/**
	 * @return value of PostProductionProcedureState
	 */
	public final java.lang.Integer getPostProductionProcedureState()
	{
		return getPostProductionProcedureState(getContext());
	}

	/**
	 * @param context
	 * @return value of PostProductionProcedureState
	 */
	public final java.lang.Integer getPostProductionProcedureState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PostProductionProcedureState.toString());
	}

	/**
	 * Set value of PostProductionProcedureState
	 * @param postproductionprocedurestate
	 */
	public final void setPostProductionProcedureState(java.lang.Integer postproductionprocedurestate)
	{
		setPostProductionProcedureState(getContext(), postproductionprocedurestate);
	}

	/**
	 * Set value of PostProductionProcedureState
	 * @param context
	 * @param postproductionprocedurestate
	 */
	public final void setPostProductionProcedureState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer postproductionprocedurestate)
	{
		getMendixObject().setValue(context, MemberNames.PostProductionProcedureState.toString(), postproductionprocedurestate);
	}

	/**
	 * @return value of PostProductionStartDate
	 */
	public final java.util.Date getPostProductionStartDate()
	{
		return getPostProductionStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PostProductionStartDate
	 */
	public final java.util.Date getPostProductionStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PostProductionStartDate.toString());
	}

	/**
	 * Set value of PostProductionStartDate
	 * @param postproductionstartdate
	 */
	public final void setPostProductionStartDate(java.util.Date postproductionstartdate)
	{
		setPostProductionStartDate(getContext(), postproductionstartdate);
	}

	/**
	 * Set value of PostProductionStartDate
	 * @param context
	 * @param postproductionstartdate
	 */
	public final void setPostProductionStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date postproductionstartdate)
	{
		getMendixObject().setValue(context, MemberNames.PostProductionStartDate.toString(), postproductionstartdate);
	}

	/**
	 * @return value of PostProductionStartDateGMT
	 */
	public final java.util.Date getPostProductionStartDateGMT()
	{
		return getPostProductionStartDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of PostProductionStartDateGMT
	 */
	public final java.util.Date getPostProductionStartDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PostProductionStartDateGMT.toString());
	}

	/**
	 * Set value of PostProductionStartDateGMT
	 * @param postproductionstartdategmt
	 */
	public final void setPostProductionStartDateGMT(java.util.Date postproductionstartdategmt)
	{
		setPostProductionStartDateGMT(getContext(), postproductionstartdategmt);
	}

	/**
	 * Set value of PostProductionStartDateGMT
	 * @param context
	 * @param postproductionstartdategmt
	 */
	public final void setPostProductionStartDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date postproductionstartdategmt)
	{
		getMendixObject().setValue(context, MemberNames.PostProductionStartDateGMT.toString(), postproductionstartdategmt);
	}

	/**
	 * @return value of PreProductionCompleteDate
	 */
	public final java.util.Date getPreProductionCompleteDate()
	{
		return getPreProductionCompleteDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PreProductionCompleteDate
	 */
	public final java.util.Date getPreProductionCompleteDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PreProductionCompleteDate.toString());
	}

	/**
	 * Set value of PreProductionCompleteDate
	 * @param preproductioncompletedate
	 */
	public final void setPreProductionCompleteDate(java.util.Date preproductioncompletedate)
	{
		setPreProductionCompleteDate(getContext(), preproductioncompletedate);
	}

	/**
	 * Set value of PreProductionCompleteDate
	 * @param context
	 * @param preproductioncompletedate
	 */
	public final void setPreProductionCompleteDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date preproductioncompletedate)
	{
		getMendixObject().setValue(context, MemberNames.PreProductionCompleteDate.toString(), preproductioncompletedate);
	}

	/**
	 * @return value of PreProductionCompleteDateGMT
	 */
	public final java.util.Date getPreProductionCompleteDateGMT()
	{
		return getPreProductionCompleteDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of PreProductionCompleteDateGMT
	 */
	public final java.util.Date getPreProductionCompleteDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PreProductionCompleteDateGMT.toString());
	}

	/**
	 * Set value of PreProductionCompleteDateGMT
	 * @param preproductioncompletedategmt
	 */
	public final void setPreProductionCompleteDateGMT(java.util.Date preproductioncompletedategmt)
	{
		setPreProductionCompleteDateGMT(getContext(), preproductioncompletedategmt);
	}

	/**
	 * Set value of PreProductionCompleteDateGMT
	 * @param context
	 * @param preproductioncompletedategmt
	 */
	public final void setPreProductionCompleteDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date preproductioncompletedategmt)
	{
		getMendixObject().setValue(context, MemberNames.PreProductionCompleteDateGMT.toString(), preproductioncompletedategmt);
	}

	/**
	 * @return value of PreProductionProcedureState
	 */
	public final java.lang.Integer getPreProductionProcedureState()
	{
		return getPreProductionProcedureState(getContext());
	}

	/**
	 * @param context
	 * @return value of PreProductionProcedureState
	 */
	public final java.lang.Integer getPreProductionProcedureState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PreProductionProcedureState.toString());
	}

	/**
	 * Set value of PreProductionProcedureState
	 * @param preproductionprocedurestate
	 */
	public final void setPreProductionProcedureState(java.lang.Integer preproductionprocedurestate)
	{
		setPreProductionProcedureState(getContext(), preproductionprocedurestate);
	}

	/**
	 * Set value of PreProductionProcedureState
	 * @param context
	 * @param preproductionprocedurestate
	 */
	public final void setPreProductionProcedureState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer preproductionprocedurestate)
	{
		getMendixObject().setValue(context, MemberNames.PreProductionProcedureState.toString(), preproductionprocedurestate);
	}

	/**
	 * @return value of PreProductionStartDate
	 */
	public final java.util.Date getPreProductionStartDate()
	{
		return getPreProductionStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PreProductionStartDate
	 */
	public final java.util.Date getPreProductionStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PreProductionStartDate.toString());
	}

	/**
	 * Set value of PreProductionStartDate
	 * @param preproductionstartdate
	 */
	public final void setPreProductionStartDate(java.util.Date preproductionstartdate)
	{
		setPreProductionStartDate(getContext(), preproductionstartdate);
	}

	/**
	 * Set value of PreProductionStartDate
	 * @param context
	 * @param preproductionstartdate
	 */
	public final void setPreProductionStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date preproductionstartdate)
	{
		getMendixObject().setValue(context, MemberNames.PreProductionStartDate.toString(), preproductionstartdate);
	}

	/**
	 * @return value of PreProductionStartDateGMT
	 */
	public final java.util.Date getPreProductionStartDateGMT()
	{
		return getPreProductionStartDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of PreProductionStartDateGMT
	 */
	public final java.util.Date getPreProductionStartDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PreProductionStartDateGMT.toString());
	}

	/**
	 * Set value of PreProductionStartDateGMT
	 * @param preproductionstartdategmt
	 */
	public final void setPreProductionStartDateGMT(java.util.Date preproductionstartdategmt)
	{
		setPreProductionStartDateGMT(getContext(), preproductionstartdategmt);
	}

	/**
	 * Set value of PreProductionStartDateGMT
	 * @param context
	 * @param preproductionstartdategmt
	 */
	public final void setPreProductionStartDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date preproductionstartdategmt)
	{
		getMendixObject().setValue(context, MemberNames.PreProductionStartDateGMT.toString(), preproductionstartdategmt);
	}

	/**
	 * @return value of ProductionComplete
	 */
	public final java.lang.String getProductionComplete()
	{
		return getProductionComplete(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductionComplete
	 */
	public final java.lang.String getProductionComplete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductionComplete.toString());
	}

	/**
	 * Set value of ProductionComplete
	 * @param productioncomplete
	 */
	public final void setProductionComplete(java.lang.String productioncomplete)
	{
		setProductionComplete(getContext(), productioncomplete);
	}

	/**
	 * Set value of ProductionComplete
	 * @param context
	 * @param productioncomplete
	 */
	public final void setProductionComplete(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productioncomplete)
	{
		getMendixObject().setValue(context, MemberNames.ProductionComplete.toString(), productioncomplete);
	}

	/**
	 * @return value of ProductionCompleteDate
	 */
	public final java.util.Date getProductionCompleteDate()
	{
		return getProductionCompleteDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductionCompleteDate
	 */
	public final java.util.Date getProductionCompleteDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ProductionCompleteDate.toString());
	}

	/**
	 * Set value of ProductionCompleteDate
	 * @param productioncompletedate
	 */
	public final void setProductionCompleteDate(java.util.Date productioncompletedate)
	{
		setProductionCompleteDate(getContext(), productioncompletedate);
	}

	/**
	 * Set value of ProductionCompleteDate
	 * @param context
	 * @param productioncompletedate
	 */
	public final void setProductionCompleteDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date productioncompletedate)
	{
		getMendixObject().setValue(context, MemberNames.ProductionCompleteDate.toString(), productioncompletedate);
	}

	/**
	 * @return value of ProductionCompleteDateGMT
	 */
	public final java.util.Date getProductionCompleteDateGMT()
	{
		return getProductionCompleteDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductionCompleteDateGMT
	 */
	public final java.util.Date getProductionCompleteDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ProductionCompleteDateGMT.toString());
	}

	/**
	 * Set value of ProductionCompleteDateGMT
	 * @param productioncompletedategmt
	 */
	public final void setProductionCompleteDateGMT(java.util.Date productioncompletedategmt)
	{
		setProductionCompleteDateGMT(getContext(), productioncompletedategmt);
	}

	/**
	 * Set value of ProductionCompleteDateGMT
	 * @param context
	 * @param productioncompletedategmt
	 */
	public final void setProductionCompleteDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date productioncompletedategmt)
	{
		getMendixObject().setValue(context, MemberNames.ProductionCompleteDateGMT.toString(), productioncompletedategmt);
	}

	/**
	 * @return value of ProductionStartDate
	 */
	public final java.util.Date getProductionStartDate()
	{
		return getProductionStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductionStartDate
	 */
	public final java.util.Date getProductionStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ProductionStartDate.toString());
	}

	/**
	 * Set value of ProductionStartDate
	 * @param productionstartdate
	 */
	public final void setProductionStartDate(java.util.Date productionstartdate)
	{
		setProductionStartDate(getContext(), productionstartdate);
	}

	/**
	 * Set value of ProductionStartDate
	 * @param context
	 * @param productionstartdate
	 */
	public final void setProductionStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date productionstartdate)
	{
		getMendixObject().setValue(context, MemberNames.ProductionStartDate.toString(), productionstartdate);
	}

	/**
	 * @return value of ProductionStartDateGMT
	 */
	public final java.util.Date getProductionStartDateGMT()
	{
		return getProductionStartDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductionStartDateGMT
	 */
	public final java.util.Date getProductionStartDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ProductionStartDateGMT.toString());
	}

	/**
	 * Set value of ProductionStartDateGMT
	 * @param productionstartdategmt
	 */
	public final void setProductionStartDateGMT(java.util.Date productionstartdategmt)
	{
		setProductionStartDateGMT(getContext(), productionstartdategmt);
	}

	/**
	 * Set value of ProductionStartDateGMT
	 * @param context
	 * @param productionstartdategmt
	 */
	public final void setProductionStartDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date productionstartdategmt)
	{
		getMendixObject().setValue(context, MemberNames.ProductionStartDateGMT.toString(), productionstartdategmt);
	}

	/**
	 * @return value of ProductPlannedCost
	 */
	public final java.lang.String getProductPlannedCost()
	{
		return getProductPlannedCost(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductPlannedCost
	 */
	public final java.lang.String getProductPlannedCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductPlannedCost.toString());
	}

	/**
	 * Set value of ProductPlannedCost
	 * @param productplannedcost
	 */
	public final void setProductPlannedCost(java.lang.String productplannedcost)
	{
		setProductPlannedCost(getContext(), productplannedcost);
	}

	/**
	 * Set value of ProductPlannedCost
	 * @param context
	 * @param productplannedcost
	 */
	public final void setProductPlannedCost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productplannedcost)
	{
		getMendixObject().setValue(context, MemberNames.ProductPlannedCost.toString(), productplannedcost);
	}

	/**
	 * @return value of ScrapQty
	 */
	public final java.math.BigDecimal getScrapQty()
	{
		return getScrapQty(getContext());
	}

	/**
	 * @param context
	 * @return value of ScrapQty
	 */
	public final java.math.BigDecimal getScrapQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ScrapQty.toString());
	}

	/**
	 * Set value of ScrapQty
	 * @param scrapqty
	 */
	public final void setScrapQty(java.math.BigDecimal scrapqty)
	{
		setScrapQty(getContext(), scrapqty);
	}

	/**
	 * Set value of ScrapQty
	 * @param context
	 * @param scrapqty
	 */
	public final void setScrapQty(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal scrapqty)
	{
		getMendixObject().setValue(context, MemberNames.ScrapQty.toString(), scrapqty);
	}

	/**
	 * @return value of OrderStatus
	 */
	public final java.lang.String getOrderStatus()
	{
		return getOrderStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderStatus
	 */
	public final java.lang.String getOrderStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderStatus.toString());
	}

	/**
	 * Set value of OrderStatus
	 * @param orderstatus
	 */
	public final void setOrderStatus(java.lang.String orderstatus)
	{
		setOrderStatus(getContext(), orderstatus);
	}

	/**
	 * Set value of OrderStatus
	 * @param context
	 * @param orderstatus
	 */
	public final void setOrderStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String orderstatus)
	{
		getMendixObject().setValue(context, MemberNames.OrderStatus.toString(), orderstatus);
	}

	/**
	 * @return value of PreProductionTotalCompletionHour
	 */
	public final java.lang.String getPreProductionTotalCompletionHour()
	{
		return getPreProductionTotalCompletionHour(getContext());
	}

	/**
	 * @param context
	 * @return value of PreProductionTotalCompletionHour
	 */
	public final java.lang.String getPreProductionTotalCompletionHour(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PreProductionTotalCompletionHour.toString());
	}

	/**
	 * Set value of PreProductionTotalCompletionHour
	 * @param preproductiontotalcompletionhour
	 */
	public final void setPreProductionTotalCompletionHour(java.lang.String preproductiontotalcompletionhour)
	{
		setPreProductionTotalCompletionHour(getContext(), preproductiontotalcompletionhour);
	}

	/**
	 * Set value of PreProductionTotalCompletionHour
	 * @param context
	 * @param preproductiontotalcompletionhour
	 */
	public final void setPreProductionTotalCompletionHour(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String preproductiontotalcompletionhour)
	{
		getMendixObject().setValue(context, MemberNames.PreProductionTotalCompletionHour.toString(), preproductiontotalcompletionhour);
	}

	/**
	 * @return value of PostProductionTotalCompletionHour
	 */
	public final java.lang.String getPostProductionTotalCompletionHour()
	{
		return getPostProductionTotalCompletionHour(getContext());
	}

	/**
	 * @param context
	 * @return value of PostProductionTotalCompletionHour
	 */
	public final java.lang.String getPostProductionTotalCompletionHour(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PostProductionTotalCompletionHour.toString());
	}

	/**
	 * Set value of PostProductionTotalCompletionHour
	 * @param postproductiontotalcompletionhour
	 */
	public final void setPostProductionTotalCompletionHour(java.lang.String postproductiontotalcompletionhour)
	{
		setPostProductionTotalCompletionHour(getContext(), postproductiontotalcompletionhour);
	}

	/**
	 * Set value of PostProductionTotalCompletionHour
	 * @param context
	 * @param postproductiontotalcompletionhour
	 */
	public final void setPostProductionTotalCompletionHour(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postproductiontotalcompletionhour)
	{
		getMendixObject().setValue(context, MemberNames.PostProductionTotalCompletionHour.toString(), postproductiontotalcompletionhour);
	}

	/**
	 * @return value of ProductionTotalCompletionHour
	 */
	public final java.lang.String getProductionTotalCompletionHour()
	{
		return getProductionTotalCompletionHour(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductionTotalCompletionHour
	 */
	public final java.lang.String getProductionTotalCompletionHour(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductionTotalCompletionHour.toString());
	}

	/**
	 * Set value of ProductionTotalCompletionHour
	 * @param productiontotalcompletionhour
	 */
	public final void setProductionTotalCompletionHour(java.lang.String productiontotalcompletionhour)
	{
		setProductionTotalCompletionHour(getContext(), productiontotalcompletionhour);
	}

	/**
	 * Set value of ProductionTotalCompletionHour
	 * @param context
	 * @param productiontotalcompletionhour
	 */
	public final void setProductionTotalCompletionHour(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productiontotalcompletionhour)
	{
		getMendixObject().setValue(context, MemberNames.ProductionTotalCompletionHour.toString(), productiontotalcompletionhour);
	}

	/**
	 * @return value of OnTimeHour
	 */
	public final java.lang.String getOnTimeHour()
	{
		return getOnTimeHour(getContext());
	}

	/**
	 * @param context
	 * @return value of OnTimeHour
	 */
	public final java.lang.String getOnTimeHour(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnTimeHour.toString());
	}

	/**
	 * Set value of OnTimeHour
	 * @param ontimehour
	 */
	public final void setOnTimeHour(java.lang.String ontimehour)
	{
		setOnTimeHour(getContext(), ontimehour);
	}

	/**
	 * Set value of OnTimeHour
	 * @param context
	 * @param ontimehour
	 */
	public final void setOnTimeHour(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ontimehour)
	{
		getMendixObject().setValue(context, MemberNames.OnTimeHour.toString(), ontimehour);
	}

	/**
	 * @return value of TargetTimePre
	 */
	public final java.math.BigDecimal getTargetTimePre()
	{
		return getTargetTimePre(getContext());
	}

	/**
	 * @param context
	 * @return value of TargetTimePre
	 */
	public final java.math.BigDecimal getTargetTimePre(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TargetTimePre.toString());
	}

	/**
	 * Set value of TargetTimePre
	 * @param targettimepre
	 */
	public final void setTargetTimePre(java.math.BigDecimal targettimepre)
	{
		setTargetTimePre(getContext(), targettimepre);
	}

	/**
	 * Set value of TargetTimePre
	 * @param context
	 * @param targettimepre
	 */
	public final void setTargetTimePre(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal targettimepre)
	{
		getMendixObject().setValue(context, MemberNames.TargetTimePre.toString(), targettimepre);
	}

	/**
	 * @return value of ProductImageIdentifier
	 */
	public final java.lang.String getProductImageIdentifier()
	{
		return getProductImageIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductImageIdentifier
	 */
	public final java.lang.String getProductImageIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductImageIdentifier.toString());
	}

	/**
	 * Set value of ProductImageIdentifier
	 * @param productimageidentifier
	 */
	public final void setProductImageIdentifier(java.lang.String productimageidentifier)
	{
		setProductImageIdentifier(getContext(), productimageidentifier);
	}

	/**
	 * Set value of ProductImageIdentifier
	 * @param context
	 * @param productimageidentifier
	 */
	public final void setProductImageIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productimageidentifier)
	{
		getMendixObject().setValue(context, MemberNames.ProductImageIdentifier.toString(), productimageidentifier);
	}

	/**
	 * @return value of PreState
	 */
	public final java.lang.Integer getPreState()
	{
		return getPreState(getContext());
	}

	/**
	 * @param context
	 * @return value of PreState
	 */
	public final java.lang.Integer getPreState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PreState.toString());
	}

	/**
	 * Set value of PreState
	 * @param prestate
	 */
	public final void setPreState(java.lang.Integer prestate)
	{
		setPreState(getContext(), prestate);
	}

	/**
	 * Set value of PreState
	 * @param context
	 * @param prestate
	 */
	public final void setPreState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer prestate)
	{
		getMendixObject().setValue(context, MemberNames.PreState.toString(), prestate);
	}

	/**
	 * @return value of PostState
	 */
	public final java.lang.Integer getPostState()
	{
		return getPostState(getContext());
	}

	/**
	 * @param context
	 * @return value of PostState
	 */
	public final java.lang.Integer getPostState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PostState.toString());
	}

	/**
	 * Set value of PostState
	 * @param poststate
	 */
	public final void setPostState(java.lang.Integer poststate)
	{
		setPostState(getContext(), poststate);
	}

	/**
	 * Set value of PostState
	 * @param context
	 * @param poststate
	 */
	public final void setPostState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer poststate)
	{
		getMendixObject().setValue(context, MemberNames.PostState.toString(), poststate);
	}

	/**
	 * @return value of PreProductionProcedureInfoSet
	 */
	public final java.lang.Boolean getPreProductionProcedureInfoSet()
	{
		return getPreProductionProcedureInfoSet(getContext());
	}

	/**
	 * @param context
	 * @return value of PreProductionProcedureInfoSet
	 */
	public final java.lang.Boolean getPreProductionProcedureInfoSet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PreProductionProcedureInfoSet.toString());
	}

	/**
	 * Set value of PreProductionProcedureInfoSet
	 * @param preproductionprocedureinfoset
	 */
	public final void setPreProductionProcedureInfoSet(java.lang.Boolean preproductionprocedureinfoset)
	{
		setPreProductionProcedureInfoSet(getContext(), preproductionprocedureinfoset);
	}

	/**
	 * Set value of PreProductionProcedureInfoSet
	 * @param context
	 * @param preproductionprocedureinfoset
	 */
	public final void setPreProductionProcedureInfoSet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean preproductionprocedureinfoset)
	{
		getMendixObject().setValue(context, MemberNames.PreProductionProcedureInfoSet.toString(), preproductionprocedureinfoset);
	}

	/**
	 * @return value of PostProductionProcedureInfoSet
	 */
	public final java.lang.Boolean getPostProductionProcedureInfoSet()
	{
		return getPostProductionProcedureInfoSet(getContext());
	}

	/**
	 * @param context
	 * @return value of PostProductionProcedureInfoSet
	 */
	public final java.lang.Boolean getPostProductionProcedureInfoSet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PostProductionProcedureInfoSet.toString());
	}

	/**
	 * Set value of PostProductionProcedureInfoSet
	 * @param postproductionprocedureinfoset
	 */
	public final void setPostProductionProcedureInfoSet(java.lang.Boolean postproductionprocedureinfoset)
	{
		setPostProductionProcedureInfoSet(getContext(), postproductionprocedureinfoset);
	}

	/**
	 * Set value of PostProductionProcedureInfoSet
	 * @param context
	 * @param postproductionprocedureinfoset
	 */
	public final void setPostProductionProcedureInfoSet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean postproductionprocedureinfoset)
	{
		getMendixObject().setValue(context, MemberNames.PostProductionProcedureInfoSet.toString(), postproductionprocedureinfoset);
	}

	/**
	 * @return value of OrderPlannedCompletionDateGMT
	 */
	public final java.util.Date getOrderPlannedCompletionDateGMT()
	{
		return getOrderPlannedCompletionDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderPlannedCompletionDateGMT
	 */
	public final java.util.Date getOrderPlannedCompletionDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderPlannedCompletionDateGMT.toString());
	}

	/**
	 * Set value of OrderPlannedCompletionDateGMT
	 * @param orderplannedcompletiondategmt
	 */
	public final void setOrderPlannedCompletionDateGMT(java.util.Date orderplannedcompletiondategmt)
	{
		setOrderPlannedCompletionDateGMT(getContext(), orderplannedcompletiondategmt);
	}

	/**
	 * Set value of OrderPlannedCompletionDateGMT
	 * @param context
	 * @param orderplannedcompletiondategmt
	 */
	public final void setOrderPlannedCompletionDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderplannedcompletiondategmt)
	{
		getMendixObject().setValue(context, MemberNames.OrderPlannedCompletionDateGMT.toString(), orderplannedcompletiondategmt);
	}

	/**
	 * @return value of OrderPlannedStartDateGMT
	 */
	public final java.util.Date getOrderPlannedStartDateGMT()
	{
		return getOrderPlannedStartDateGMT(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderPlannedStartDateGMT
	 */
	public final java.util.Date getOrderPlannedStartDateGMT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderPlannedStartDateGMT.toString());
	}

	/**
	 * Set value of OrderPlannedStartDateGMT
	 * @param orderplannedstartdategmt
	 */
	public final void setOrderPlannedStartDateGMT(java.util.Date orderplannedstartdategmt)
	{
		setOrderPlannedStartDateGMT(getContext(), orderplannedstartdategmt);
	}

	/**
	 * Set value of OrderPlannedStartDateGMT
	 * @param context
	 * @param orderplannedstartdategmt
	 */
	public final void setOrderPlannedStartDateGMT(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderplannedstartdategmt)
	{
		getMendixObject().setValue(context, MemberNames.OrderPlannedStartDateGMT.toString(), orderplannedstartdategmt);
	}

	/**
	 * @return value of daysBetweenPreStartCompletedDate
	 */
	public final java.math.BigDecimal getdaysBetweenPreStartCompletedDate()
	{
		return getdaysBetweenPreStartCompletedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of daysBetweenPreStartCompletedDate
	 */
	public final java.math.BigDecimal getdaysBetweenPreStartCompletedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.daysBetweenPreStartCompletedDate.toString());
	}

	/**
	 * Set value of daysBetweenPreStartCompletedDate
	 * @param daysbetweenprestartcompleteddate
	 */
	public final void setdaysBetweenPreStartCompletedDate(java.math.BigDecimal daysbetweenprestartcompleteddate)
	{
		setdaysBetweenPreStartCompletedDate(getContext(), daysbetweenprestartcompleteddate);
	}

	/**
	 * Set value of daysBetweenPreStartCompletedDate
	 * @param context
	 * @param daysbetweenprestartcompleteddate
	 */
	public final void setdaysBetweenPreStartCompletedDate(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal daysbetweenprestartcompleteddate)
	{
		getMendixObject().setValue(context, MemberNames.daysBetweenPreStartCompletedDate.toString(), daysbetweenprestartcompleteddate);
	}

	/**
	 * @return value of TargetTimePost
	 */
	public final java.math.BigDecimal getTargetTimePost()
	{
		return getTargetTimePost(getContext());
	}

	/**
	 * @param context
	 * @return value of TargetTimePost
	 */
	public final java.math.BigDecimal getTargetTimePost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TargetTimePost.toString());
	}

	/**
	 * Set value of TargetTimePost
	 * @param targettimepost
	 */
	public final void setTargetTimePost(java.math.BigDecimal targettimepost)
	{
		setTargetTimePost(getContext(), targettimepost);
	}

	/**
	 * Set value of TargetTimePost
	 * @param context
	 * @param targettimepost
	 */
	public final void setTargetTimePost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal targettimepost)
	{
		getMendixObject().setValue(context, MemberNames.TargetTimePost.toString(), targettimepost);
	}

	/**
	 * @return value of daysBetweenPostStartCompletedDate
	 */
	public final java.math.BigDecimal getdaysBetweenPostStartCompletedDate()
	{
		return getdaysBetweenPostStartCompletedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of daysBetweenPostStartCompletedDate
	 */
	public final java.math.BigDecimal getdaysBetweenPostStartCompletedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.daysBetweenPostStartCompletedDate.toString());
	}

	/**
	 * Set value of daysBetweenPostStartCompletedDate
	 * @param daysbetweenpoststartcompleteddate
	 */
	public final void setdaysBetweenPostStartCompletedDate(java.math.BigDecimal daysbetweenpoststartcompleteddate)
	{
		setdaysBetweenPostStartCompletedDate(getContext(), daysbetweenpoststartcompleteddate);
	}

	/**
	 * Set value of daysBetweenPostStartCompletedDate
	 * @param context
	 * @param daysbetweenpoststartcompleteddate
	 */
	public final void setdaysBetweenPostStartCompletedDate(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal daysbetweenpoststartcompleteddate)
	{
		getMendixObject().setValue(context, MemberNames.daysBetweenPostStartCompletedDate.toString(), daysbetweenpoststartcompleteddate);
	}

	/**
	 * @return value of EnableStartButton
	 */
	public final java.lang.Boolean getEnableStartButton()
	{
		return getEnableStartButton(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableStartButton
	 */
	public final java.lang.Boolean getEnableStartButton(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableStartButton.toString());
	}

	/**
	 * Set value of EnableStartButton
	 * @param enablestartbutton
	 */
	public final void setEnableStartButton(java.lang.Boolean enablestartbutton)
	{
		setEnableStartButton(getContext(), enablestartbutton);
	}

	/**
	 * Set value of EnableStartButton
	 * @param context
	 * @param enablestartbutton
	 */
	public final void setEnableStartButton(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enablestartbutton)
	{
		getMendixObject().setValue(context, MemberNames.EnableStartButton.toString(), enablestartbutton);
	}

	/**
	 * @return value of ProductImageBrowseMode
	 */
	public final java.lang.Integer getProductImageBrowseMode()
	{
		return getProductImageBrowseMode(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductImageBrowseMode
	 */
	public final java.lang.Integer getProductImageBrowseMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProductImageBrowseMode.toString());
	}

	/**
	 * Set value of ProductImageBrowseMode
	 * @param productimagebrowsemode
	 */
	public final void setProductImageBrowseMode(java.lang.Integer productimagebrowsemode)
	{
		setProductImageBrowseMode(getContext(), productimagebrowsemode);
	}

	/**
	 * Set value of ProductImageBrowseMode
	 * @param context
	 * @param productimagebrowsemode
	 */
	public final void setProductImageBrowseMode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer productimagebrowsemode)
	{
		getMendixObject().setValue(context, MemberNames.ProductImageBrowseMode.toString(), productimagebrowsemode);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MfgOrder_MfgOrderInfoData
	 */
	public final excr_mfgordermanagement_api.proxies.MfgOrder getMfgOrder_MfgOrderInfoData() throws com.mendix.core.CoreException
	{
		return getMfgOrder_MfgOrderInfoData(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrder_MfgOrderInfoData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.MfgOrder getMfgOrder_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.MfgOrder result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MfgOrder_MfgOrderInfoData.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.MfgOrder.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MfgOrder_MfgOrderInfoData
	 * @param mfgorder_mfgorderinfodata
	 */
	public final void setMfgOrder_MfgOrderInfoData(excr_mfgordermanagement_api.proxies.MfgOrder mfgorder_mfgorderinfodata)
	{
		setMfgOrder_MfgOrderInfoData(getContext(), mfgorder_mfgorderinfodata);
	}

	/**
	 * Set value of MfgOrder_MfgOrderInfoData
	 * @param context
	 * @param mfgorder_mfgorderinfodata
	 */
	public final void setMfgOrder_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.MfgOrder mfgorder_mfgorderinfodata)
	{
		if (mfgorder_mfgorderinfodata == null) {
			getMendixObject().setValue(context, MemberNames.MfgOrder_MfgOrderInfoData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MfgOrder_MfgOrderInfoData.toString(), mfgorder_mfgorderinfodata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Product_MfgOrderInfoData
	 */
	public final excr_mfgordermanagement_api.proxies.Product getProduct_MfgOrderInfoData() throws com.mendix.core.CoreException
	{
		return getProduct_MfgOrderInfoData(getContext());
	}

	/**
	 * @param context
	 * @return value of Product_MfgOrderInfoData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.Product getProduct_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Product_MfgOrderInfoData.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.Product.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Product_MfgOrderInfoData
	 * @param product_mfgorderinfodata
	 */
	public final void setProduct_MfgOrderInfoData(excr_mfgordermanagement_api.proxies.Product product_mfgorderinfodata)
	{
		setProduct_MfgOrderInfoData(getContext(), product_mfgorderinfodata);
	}

	/**
	 * Set value of Product_MfgOrderInfoData
	 * @param context
	 * @param product_mfgorderinfodata
	 */
	public final void setProduct_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.Product product_mfgorderinfodata)
	{
		if (product_mfgorderinfodata == null) {
			getMendixObject().setValue(context, MemberNames.Product_MfgOrderInfoData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Product_MfgOrderInfoData.toString(), product_mfgorderinfodata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PreProductionProcedureInfo_MfgOrderInfoData
	 */
	public final excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo getPreProductionProcedureInfo_MfgOrderInfoData() throws com.mendix.core.CoreException
	{
		return getPreProductionProcedureInfo_MfgOrderInfoData(getContext());
	}

	/**
	 * @param context
	 * @return value of PreProductionProcedureInfo_MfgOrderInfoData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo getPreProductionProcedureInfo_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PreProductionProcedureInfo_MfgOrderInfoData.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PreProductionProcedureInfo_MfgOrderInfoData
	 * @param preproductionprocedureinfo_mfgorderinfodata
	 */
	public final void setPreProductionProcedureInfo_MfgOrderInfoData(excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo preproductionprocedureinfo_mfgorderinfodata)
	{
		setPreProductionProcedureInfo_MfgOrderInfoData(getContext(), preproductionprocedureinfo_mfgorderinfodata);
	}

	/**
	 * Set value of PreProductionProcedureInfo_MfgOrderInfoData
	 * @param context
	 * @param preproductionprocedureinfo_mfgorderinfodata
	 */
	public final void setPreProductionProcedureInfo_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo preproductionprocedureinfo_mfgorderinfodata)
	{
		if (preproductionprocedureinfo_mfgorderinfodata == null) {
			getMendixObject().setValue(context, MemberNames.PreProductionProcedureInfo_MfgOrderInfoData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PreProductionProcedureInfo_MfgOrderInfoData.toString(), preproductionprocedureinfo_mfgorderinfodata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PostProductionProcedureInfo_MfgOrderInfoData
	 */
	public final excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo getPostProductionProcedureInfo_MfgOrderInfoData() throws com.mendix.core.CoreException
	{
		return getPostProductionProcedureInfo_MfgOrderInfoData(getContext());
	}

	/**
	 * @param context
	 * @return value of PostProductionProcedureInfo_MfgOrderInfoData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo getPostProductionProcedureInfo_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PostProductionProcedureInfo_MfgOrderInfoData.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PostProductionProcedureInfo_MfgOrderInfoData
	 * @param postproductionprocedureinfo_mfgorderinfodata
	 */
	public final void setPostProductionProcedureInfo_MfgOrderInfoData(excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo postproductionprocedureinfo_mfgorderinfodata)
	{
		setPostProductionProcedureInfo_MfgOrderInfoData(getContext(), postproductionprocedureinfo_mfgorderinfodata);
	}

	/**
	 * Set value of PostProductionProcedureInfo_MfgOrderInfoData
	 * @param context
	 * @param postproductionprocedureinfo_mfgorderinfodata
	 */
	public final void setPostProductionProcedureInfo_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo postproductionprocedureinfo_mfgorderinfodata)
	{
		if (postproductionprocedureinfo_mfgorderinfodata == null) {
			getMendixObject().setValue(context, MemberNames.PostProductionProcedureInfo_MfgOrderInfoData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PostProductionProcedureInfo_MfgOrderInfoData.toString(), postproductionprocedureinfo_mfgorderinfodata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ProductImage_MfgOrderInfoData
	 */
	public final excr_mfgordermanagement_api.proxies.ProductImage getProductImage_MfgOrderInfoData() throws com.mendix.core.CoreException
	{
		return getProductImage_MfgOrderInfoData(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductImage_MfgOrderInfoData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.ProductImage getProductImage_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.ProductImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductImage_MfgOrderInfoData.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.ProductImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ProductImage_MfgOrderInfoData
	 * @param productimage_mfgorderinfodata
	 */
	public final void setProductImage_MfgOrderInfoData(excr_mfgordermanagement_api.proxies.ProductImage productimage_mfgorderinfodata)
	{
		setProductImage_MfgOrderInfoData(getContext(), productimage_mfgorderinfodata);
	}

	/**
	 * Set value of ProductImage_MfgOrderInfoData
	 * @param context
	 * @param productimage_mfgorderinfodata
	 */
	public final void setProductImage_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.ProductImage productimage_mfgorderinfodata)
	{
		if (productimage_mfgorderinfodata == null) {
			getMendixObject().setValue(context, MemberNames.ProductImage_MfgOrderInfoData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ProductImage_MfgOrderInfoData.toString(), productimage_mfgorderinfodata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MfgOrderInfoData_ImageConvert
	 */
	public final excr_mfgordermanagement_api.proxies.ImageConvert getMfgOrderInfoData_ImageConvert() throws com.mendix.core.CoreException
	{
		return getMfgOrderInfoData_ImageConvert(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrderInfoData_ImageConvert
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.ImageConvert getMfgOrderInfoData_ImageConvert(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.ImageConvert result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MfgOrderInfoData_ImageConvert.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.ImageConvert.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MfgOrderInfoData_ImageConvert
	 * @param mfgorderinfodata_imageconvert
	 */
	public final void setMfgOrderInfoData_ImageConvert(excr_mfgordermanagement_api.proxies.ImageConvert mfgorderinfodata_imageconvert)
	{
		setMfgOrderInfoData_ImageConvert(getContext(), mfgorderinfodata_imageconvert);
	}

	/**
	 * Set value of MfgOrderInfoData_ImageConvert
	 * @param context
	 * @param mfgorderinfodata_imageconvert
	 */
	public final void setMfgOrderInfoData_ImageConvert(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.ImageConvert mfgorderinfodata_imageconvert)
	{
		if (mfgorderinfodata_imageconvert == null) {
			getMendixObject().setValue(context, MemberNames.MfgOrderInfoData_ImageConvert.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MfgOrderInfoData_ImageConvert.toString(), mfgorderinfodata_imageconvert.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mfgOrderInfoDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement_api.proxies.MfgOrderInfoData that = (excr_mfgordermanagement_api.proxies.MfgOrderInfoData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
