// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement_api.proxies;

public class MfgOrder implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mfgOrderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement_API.MfgOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceId("InstanceId"),
		CDOTypeName("CDOTypeName"),
		Name("Name"),
		MfgOrder_MfgOrderInfoData("EXCR_MfgOrderManagement_API.MfgOrder_MfgOrderInfoData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MfgOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MfgOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mfgOrderMendixObject)
	{
		if (mfgOrderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mfgOrderMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mfgOrderMendixObject = mfgOrderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement_api.proxies.MfgOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement_api.proxies.MfgOrder(context, mendixObject);
	}

	public static excr_mfgordermanagement_api.proxies.MfgOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement_api.proxies.MfgOrder.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName()
	{
		return getCDOTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CDOTypeName.toString());
	}

	/**
	 * Set value of CDOTypeName
	 * @param cdotypename
	 */
	public final void setCDOTypeName(java.lang.String cdotypename)
	{
		setCDOTypeName(getContext(), cdotypename);
	}

	/**
	 * Set value of CDOTypeName
	 * @param context
	 * @param cdotypename
	 */
	public final void setCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cdotypename)
	{
		getMendixObject().setValue(context, MemberNames.CDOTypeName.toString(), cdotypename);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MfgOrder_MfgOrderInfoData
	 */
	public final excr_mfgordermanagement_api.proxies.MfgOrderInfoData getMfgOrder_MfgOrderInfoData() throws com.mendix.core.CoreException
	{
		return getMfgOrder_MfgOrderInfoData(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrder_MfgOrderInfoData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.MfgOrderInfoData getMfgOrder_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.MfgOrderInfoData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MfgOrder_MfgOrderInfoData.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.MfgOrderInfoData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MfgOrder_MfgOrderInfoData
	 * @param mfgorder_mfgorderinfodata
	 */
	public final void setMfgOrder_MfgOrderInfoData(excr_mfgordermanagement_api.proxies.MfgOrderInfoData mfgorder_mfgorderinfodata)
	{
		setMfgOrder_MfgOrderInfoData(getContext(), mfgorder_mfgorderinfodata);
	}

	/**
	 * Set value of MfgOrder_MfgOrderInfoData
	 * @param context
	 * @param mfgorder_mfgorderinfodata
	 */
	public final void setMfgOrder_MfgOrderInfoData(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.MfgOrderInfoData mfgorder_mfgorderinfodata)
	{
		if (mfgorder_mfgorderinfodata == null) {
			getMendixObject().setValue(context, MemberNames.MfgOrder_MfgOrderInfoData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MfgOrder_MfgOrderInfoData.toString(), mfgorder_mfgorderinfodata.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mfgOrderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement_api.proxies.MfgOrder that = (excr_mfgordermanagement_api.proxies.MfgOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
