// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement_api.proxies;

public class PostTaskItem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject postTaskItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement_API.PostTaskItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceId("InstanceId"),
		CDOTypeName("CDOTypeName"),
		Name("Name"),
		PostTaskItem_PostTaskItemInfo("EXCR_MfgOrderManagement_API.PostTaskItem_PostTaskItemInfo"),
		PostParent_PostTaskItem("EXCR_MfgOrderManagement_API.PostParent_PostTaskItem");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PostTaskItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PostTaskItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject postTaskItemMendixObject)
	{
		if (postTaskItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!postTaskItemMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.postTaskItemMendixObject = postTaskItemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement_api.proxies.PostTaskItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement_api.proxies.PostTaskItem(context, mendixObject);
	}

	public static excr_mfgordermanagement_api.proxies.PostTaskItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement_api.proxies.PostTaskItem.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName()
	{
		return getCDOTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of CDOTypeName
	 */
	public final java.lang.String getCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CDOTypeName.toString());
	}

	/**
	 * Set value of CDOTypeName
	 * @param cdotypename
	 */
	public final void setCDOTypeName(java.lang.String cdotypename)
	{
		setCDOTypeName(getContext(), cdotypename);
	}

	/**
	 * Set value of CDOTypeName
	 * @param context
	 * @param cdotypename
	 */
	public final void setCDOTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cdotypename)
	{
		getMendixObject().setValue(context, MemberNames.CDOTypeName.toString(), cdotypename);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PostTaskItem_PostTaskItemInfo
	 */
	public final excr_mfgordermanagement_api.proxies.PostTaskItemInfo getPostTaskItem_PostTaskItemInfo() throws com.mendix.core.CoreException
	{
		return getPostTaskItem_PostTaskItemInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of PostTaskItem_PostTaskItemInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PostTaskItemInfo getPostTaskItem_PostTaskItemInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PostTaskItemInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PostTaskItem_PostTaskItemInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PostTaskItemInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PostTaskItem_PostTaskItemInfo
	 * @param posttaskitem_posttaskiteminfo
	 */
	public final void setPostTaskItem_PostTaskItemInfo(excr_mfgordermanagement_api.proxies.PostTaskItemInfo posttaskitem_posttaskiteminfo)
	{
		setPostTaskItem_PostTaskItemInfo(getContext(), posttaskitem_posttaskiteminfo);
	}

	/**
	 * Set value of PostTaskItem_PostTaskItemInfo
	 * @param context
	 * @param posttaskitem_posttaskiteminfo
	 */
	public final void setPostTaskItem_PostTaskItemInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PostTaskItemInfo posttaskitem_posttaskiteminfo)
	{
		if (posttaskitem_posttaskiteminfo == null) {
			getMendixObject().setValue(context, MemberNames.PostTaskItem_PostTaskItemInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PostTaskItem_PostTaskItemInfo.toString(), posttaskitem_posttaskiteminfo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PostParent_PostTaskItem
	 */
	public final excr_mfgordermanagement_api.proxies.PostParent getPostParent_PostTaskItem() throws com.mendix.core.CoreException
	{
		return getPostParent_PostTaskItem(getContext());
	}

	/**
	 * @param context
	 * @return value of PostParent_PostTaskItem
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PostParent getPostParent_PostTaskItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PostParent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PostParent_PostTaskItem.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PostParent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PostParent_PostTaskItem
	 * @param postparent_posttaskitem
	 */
	public final void setPostParent_PostTaskItem(excr_mfgordermanagement_api.proxies.PostParent postparent_posttaskitem)
	{
		setPostParent_PostTaskItem(getContext(), postparent_posttaskitem);
	}

	/**
	 * Set value of PostParent_PostTaskItem
	 * @param context
	 * @param postparent_posttaskitem
	 */
	public final void setPostParent_PostTaskItem(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PostParent postparent_posttaskitem)
	{
		if (postparent_posttaskitem == null) {
			getMendixObject().setValue(context, MemberNames.PostParent_PostTaskItem.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PostParent_PostTaskItem.toString(), postparent_posttaskitem.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return postTaskItemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement_api.proxies.PostTaskItem that = (excr_mfgordermanagement_api.proxies.PostTaskItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
