// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement_api.proxies;

public class PostTaskListInfo implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject postTaskListInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement_API.PostTaskListInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		State("State"),
		PostTaskList_PostTaskListInfo("EXCR_MfgOrderManagement_API.PostTaskList_PostTaskListInfo"),
		PostTaskListInfo_PostProductionProcedureInfo("EXCR_MfgOrderManagement_API.PostTaskListInfo_PostProductionProcedureInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PostTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PostTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject postTaskListInfoMendixObject)
	{
		if (postTaskListInfoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!postTaskListInfoMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.postTaskListInfoMendixObject = postTaskListInfoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement_api.proxies.PostTaskListInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement_api.proxies.PostTaskListInfo(context, mendixObject);
	}

	public static excr_mfgordermanagement_api.proxies.PostTaskListInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement_api.proxies.PostTaskListInfo.initialize(context, mendixObject);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.Integer getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.Integer getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.Integer state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PostTaskList_PostTaskListInfo
	 */
	public final excr_mfgordermanagement_api.proxies.PostTaskList getPostTaskList_PostTaskListInfo() throws com.mendix.core.CoreException
	{
		return getPostTaskList_PostTaskListInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of PostTaskList_PostTaskListInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PostTaskList getPostTaskList_PostTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PostTaskList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PostTaskList_PostTaskListInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PostTaskList.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PostTaskList_PostTaskListInfo
	 * @param posttasklist_posttasklistinfo
	 */
	public final void setPostTaskList_PostTaskListInfo(excr_mfgordermanagement_api.proxies.PostTaskList posttasklist_posttasklistinfo)
	{
		setPostTaskList_PostTaskListInfo(getContext(), posttasklist_posttasklistinfo);
	}

	/**
	 * Set value of PostTaskList_PostTaskListInfo
	 * @param context
	 * @param posttasklist_posttasklistinfo
	 */
	public final void setPostTaskList_PostTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PostTaskList posttasklist_posttasklistinfo)
	{
		if (posttasklist_posttasklistinfo == null) {
			getMendixObject().setValue(context, MemberNames.PostTaskList_PostTaskListInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PostTaskList_PostTaskListInfo.toString(), posttasklist_posttasklistinfo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PostTaskListInfo_PostProductionProcedureInfo
	 */
	public final excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo getPostTaskListInfo_PostProductionProcedureInfo() throws com.mendix.core.CoreException
	{
		return getPostTaskListInfo_PostProductionProcedureInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of PostTaskListInfo_PostProductionProcedureInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo getPostTaskListInfo_PostProductionProcedureInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PostTaskListInfo_PostProductionProcedureInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PostTaskListInfo_PostProductionProcedureInfo
	 * @param posttasklistinfo_postproductionprocedureinfo
	 */
	public final void setPostTaskListInfo_PostProductionProcedureInfo(excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo posttasklistinfo_postproductionprocedureinfo)
	{
		setPostTaskListInfo_PostProductionProcedureInfo(getContext(), posttasklistinfo_postproductionprocedureinfo);
	}

	/**
	 * Set value of PostTaskListInfo_PostProductionProcedureInfo
	 * @param context
	 * @param posttasklistinfo_postproductionprocedureinfo
	 */
	public final void setPostTaskListInfo_PostProductionProcedureInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PostProductionProcedureInfo posttasklistinfo_postproductionprocedureinfo)
	{
		if (posttasklistinfo_postproductionprocedureinfo == null) {
			getMendixObject().setValue(context, MemberNames.PostTaskListInfo_PostProductionProcedureInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PostTaskListInfo_PostProductionProcedureInfo.toString(), posttasklistinfo_postproductionprocedureinfo.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return postTaskListInfoMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement_api.proxies.PostTaskListInfo that = (excr_mfgordermanagement_api.proxies.PostTaskListInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
