// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement_api.proxies;

public class PreTaskListInfo implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject preTaskListInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement_API.PreTaskListInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		State("State"),
		PreTaskList_PreTaskListInfo("EXCR_MfgOrderManagement_API.PreTaskList_PreTaskListInfo"),
		PreTaskListInfo_PreProductionProcedureInfo("EXCR_MfgOrderManagement_API.PreTaskListInfo_PreProductionProcedureInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PreTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PreTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject preTaskListInfoMendixObject)
	{
		if (preTaskListInfoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!preTaskListInfoMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.preTaskListInfoMendixObject = preTaskListInfoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement_api.proxies.PreTaskListInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement_api.proxies.PreTaskListInfo(context, mendixObject);
	}

	public static excr_mfgordermanagement_api.proxies.PreTaskListInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement_api.proxies.PreTaskListInfo.initialize(context, mendixObject);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.Integer getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.Integer getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.Integer state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PreTaskList_PreTaskListInfo
	 */
	public final excr_mfgordermanagement_api.proxies.PreTaskList getPreTaskList_PreTaskListInfo() throws com.mendix.core.CoreException
	{
		return getPreTaskList_PreTaskListInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of PreTaskList_PreTaskListInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PreTaskList getPreTaskList_PreTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PreTaskList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PreTaskList_PreTaskListInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PreTaskList.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PreTaskList_PreTaskListInfo
	 * @param pretasklist_pretasklistinfo
	 */
	public final void setPreTaskList_PreTaskListInfo(excr_mfgordermanagement_api.proxies.PreTaskList pretasklist_pretasklistinfo)
	{
		setPreTaskList_PreTaskListInfo(getContext(), pretasklist_pretasklistinfo);
	}

	/**
	 * Set value of PreTaskList_PreTaskListInfo
	 * @param context
	 * @param pretasklist_pretasklistinfo
	 */
	public final void setPreTaskList_PreTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PreTaskList pretasklist_pretasklistinfo)
	{
		if (pretasklist_pretasklistinfo == null) {
			getMendixObject().setValue(context, MemberNames.PreTaskList_PreTaskListInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PreTaskList_PreTaskListInfo.toString(), pretasklist_pretasklistinfo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PreTaskListInfo_PreProductionProcedureInfo
	 */
	public final excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo getPreTaskListInfo_PreProductionProcedureInfo() throws com.mendix.core.CoreException
	{
		return getPreTaskListInfo_PreProductionProcedureInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of PreTaskListInfo_PreProductionProcedureInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo getPreTaskListInfo_PreProductionProcedureInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PreTaskListInfo_PreProductionProcedureInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PreTaskListInfo_PreProductionProcedureInfo
	 * @param pretasklistinfo_preproductionprocedureinfo
	 */
	public final void setPreTaskListInfo_PreProductionProcedureInfo(excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo pretasklistinfo_preproductionprocedureinfo)
	{
		setPreTaskListInfo_PreProductionProcedureInfo(getContext(), pretasklistinfo_preproductionprocedureinfo);
	}

	/**
	 * Set value of PreTaskListInfo_PreProductionProcedureInfo
	 * @param context
	 * @param pretasklistinfo_preproductionprocedureinfo
	 */
	public final void setPreTaskListInfo_PreProductionProcedureInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PreProductionProcedureInfo pretasklistinfo_preproductionprocedureinfo)
	{
		if (pretasklistinfo_preproductionprocedureinfo == null) {
			getMendixObject().setValue(context, MemberNames.PreTaskListInfo_PreProductionProcedureInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PreTaskListInfo_PreProductionProcedureInfo.toString(), pretasklistinfo_preproductionprocedureinfo.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return preTaskListInfoMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement_api.proxies.PreTaskListInfo that = (excr_mfgordermanagement_api.proxies.PreTaskListInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
