// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement_api.proxies;

public class PreTaskItemInfo implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject preTaskItemInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement_API.PreTaskItemInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		State("State"),
		AdvanceToNextTask("AdvanceToNextTask"),
		ExecutionCount("ExecutionCount"),
		Instruction("Instruction"),
		InstructionType("InstructionType"),
		LastComment("LastComment"),
		MaxIterations("MaxIterations"),
		MinIterations("MinIterations"),
		Sequence("Sequence"),
		StatusTaskComplete("StatusTaskComplete"),
		StatusTaskFailed("StatusTaskFailed"),
		Status("Status"),
		PreTaskItem_PreTaskItemInfo("EXCR_MfgOrderManagement_API.PreTaskItem_PreTaskItemInfo"),
		PreTaskItemInfo_PreTaskListInfo("EXCR_MfgOrderManagement_API.PreTaskItemInfo_PreTaskListInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PreTaskItemInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PreTaskItemInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject preTaskItemInfoMendixObject)
	{
		if (preTaskItemInfoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!preTaskItemInfoMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.preTaskItemInfoMendixObject = preTaskItemInfoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement_api.proxies.PreTaskItemInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement_api.proxies.PreTaskItemInfo(context, mendixObject);
	}

	public static excr_mfgordermanagement_api.proxies.PreTaskItemInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement_api.proxies.PreTaskItemInfo.initialize(context, mendixObject);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.Integer getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.Integer getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.Integer state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of AdvanceToNextTask
	 */
	public final java.lang.Boolean getAdvanceToNextTask()
	{
		return getAdvanceToNextTask(getContext());
	}

	/**
	 * @param context
	 * @return value of AdvanceToNextTask
	 */
	public final java.lang.Boolean getAdvanceToNextTask(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AdvanceToNextTask.toString());
	}

	/**
	 * Set value of AdvanceToNextTask
	 * @param advancetonexttask
	 */
	public final void setAdvanceToNextTask(java.lang.Boolean advancetonexttask)
	{
		setAdvanceToNextTask(getContext(), advancetonexttask);
	}

	/**
	 * Set value of AdvanceToNextTask
	 * @param context
	 * @param advancetonexttask
	 */
	public final void setAdvanceToNextTask(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean advancetonexttask)
	{
		getMendixObject().setValue(context, MemberNames.AdvanceToNextTask.toString(), advancetonexttask);
	}

	/**
	 * @return value of ExecutionCount
	 */
	public final java.lang.Integer getExecutionCount()
	{
		return getExecutionCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ExecutionCount
	 */
	public final java.lang.Integer getExecutionCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ExecutionCount.toString());
	}

	/**
	 * Set value of ExecutionCount
	 * @param executioncount
	 */
	public final void setExecutionCount(java.lang.Integer executioncount)
	{
		setExecutionCount(getContext(), executioncount);
	}

	/**
	 * Set value of ExecutionCount
	 * @param context
	 * @param executioncount
	 */
	public final void setExecutionCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer executioncount)
	{
		getMendixObject().setValue(context, MemberNames.ExecutionCount.toString(), executioncount);
	}

	/**
	 * @return value of Instruction
	 */
	public final java.lang.String getInstruction()
	{
		return getInstruction(getContext());
	}

	/**
	 * @param context
	 * @return value of Instruction
	 */
	public final java.lang.String getInstruction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Instruction.toString());
	}

	/**
	 * Set value of Instruction
	 * @param instruction
	 */
	public final void setInstruction(java.lang.String instruction)
	{
		setInstruction(getContext(), instruction);
	}

	/**
	 * Set value of Instruction
	 * @param context
	 * @param instruction
	 */
	public final void setInstruction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instruction)
	{
		getMendixObject().setValue(context, MemberNames.Instruction.toString(), instruction);
	}

	/**
	 * @return value of InstructionType
	 */
	public final java.lang.Integer getInstructionType()
	{
		return getInstructionType(getContext());
	}

	/**
	 * @param context
	 * @return value of InstructionType
	 */
	public final java.lang.Integer getInstructionType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.InstructionType.toString());
	}

	/**
	 * Set value of InstructionType
	 * @param instructiontype
	 */
	public final void setInstructionType(java.lang.Integer instructiontype)
	{
		setInstructionType(getContext(), instructiontype);
	}

	/**
	 * Set value of InstructionType
	 * @param context
	 * @param instructiontype
	 */
	public final void setInstructionType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer instructiontype)
	{
		getMendixObject().setValue(context, MemberNames.InstructionType.toString(), instructiontype);
	}

	/**
	 * @return value of LastComment
	 */
	public final java.lang.String getLastComment()
	{
		return getLastComment(getContext());
	}

	/**
	 * @param context
	 * @return value of LastComment
	 */
	public final java.lang.String getLastComment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastComment.toString());
	}

	/**
	 * Set value of LastComment
	 * @param lastcomment
	 */
	public final void setLastComment(java.lang.String lastcomment)
	{
		setLastComment(getContext(), lastcomment);
	}

	/**
	 * Set value of LastComment
	 * @param context
	 * @param lastcomment
	 */
	public final void setLastComment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastcomment)
	{
		getMendixObject().setValue(context, MemberNames.LastComment.toString(), lastcomment);
	}

	/**
	 * @return value of MaxIterations
	 */
	public final java.lang.Integer getMaxIterations()
	{
		return getMaxIterations(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxIterations
	 */
	public final java.lang.Integer getMaxIterations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxIterations.toString());
	}

	/**
	 * Set value of MaxIterations
	 * @param maxiterations
	 */
	public final void setMaxIterations(java.lang.Integer maxiterations)
	{
		setMaxIterations(getContext(), maxiterations);
	}

	/**
	 * Set value of MaxIterations
	 * @param context
	 * @param maxiterations
	 */
	public final void setMaxIterations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxiterations)
	{
		getMendixObject().setValue(context, MemberNames.MaxIterations.toString(), maxiterations);
	}

	/**
	 * @return value of MinIterations
	 */
	public final java.lang.Integer getMinIterations()
	{
		return getMinIterations(getContext());
	}

	/**
	 * @param context
	 * @return value of MinIterations
	 */
	public final java.lang.Integer getMinIterations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinIterations.toString());
	}

	/**
	 * Set value of MinIterations
	 * @param miniterations
	 */
	public final void setMinIterations(java.lang.Integer miniterations)
	{
		setMinIterations(getContext(), miniterations);
	}

	/**
	 * Set value of MinIterations
	 * @param context
	 * @param miniterations
	 */
	public final void setMinIterations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer miniterations)
	{
		getMendixObject().setValue(context, MemberNames.MinIterations.toString(), miniterations);
	}

	/**
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.Integer sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * @return value of StatusTaskComplete
	 */
	public final java.lang.Integer getStatusTaskComplete()
	{
		return getStatusTaskComplete(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusTaskComplete
	 */
	public final java.lang.Integer getStatusTaskComplete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StatusTaskComplete.toString());
	}

	/**
	 * Set value of StatusTaskComplete
	 * @param statustaskcomplete
	 */
	public final void setStatusTaskComplete(java.lang.Integer statustaskcomplete)
	{
		setStatusTaskComplete(getContext(), statustaskcomplete);
	}

	/**
	 * Set value of StatusTaskComplete
	 * @param context
	 * @param statustaskcomplete
	 */
	public final void setStatusTaskComplete(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer statustaskcomplete)
	{
		getMendixObject().setValue(context, MemberNames.StatusTaskComplete.toString(), statustaskcomplete);
	}

	/**
	 * @return value of StatusTaskFailed
	 */
	public final java.lang.Integer getStatusTaskFailed()
	{
		return getStatusTaskFailed(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusTaskFailed
	 */
	public final java.lang.Integer getStatusTaskFailed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StatusTaskFailed.toString());
	}

	/**
	 * Set value of StatusTaskFailed
	 * @param statustaskfailed
	 */
	public final void setStatusTaskFailed(java.lang.Integer statustaskfailed)
	{
		setStatusTaskFailed(getContext(), statustaskfailed);
	}

	/**
	 * Set value of StatusTaskFailed
	 * @param context
	 * @param statustaskfailed
	 */
	public final void setStatusTaskFailed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer statustaskfailed)
	{
		getMendixObject().setValue(context, MemberNames.StatusTaskFailed.toString(), statustaskfailed);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.Integer getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.Integer getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.Integer status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PreTaskItem_PreTaskItemInfo
	 */
	public final excr_mfgordermanagement_api.proxies.PreTaskItem getPreTaskItem_PreTaskItemInfo() throws com.mendix.core.CoreException
	{
		return getPreTaskItem_PreTaskItemInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of PreTaskItem_PreTaskItemInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PreTaskItem getPreTaskItem_PreTaskItemInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PreTaskItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PreTaskItem_PreTaskItemInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PreTaskItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PreTaskItem_PreTaskItemInfo
	 * @param pretaskitem_pretaskiteminfo
	 */
	public final void setPreTaskItem_PreTaskItemInfo(excr_mfgordermanagement_api.proxies.PreTaskItem pretaskitem_pretaskiteminfo)
	{
		setPreTaskItem_PreTaskItemInfo(getContext(), pretaskitem_pretaskiteminfo);
	}

	/**
	 * Set value of PreTaskItem_PreTaskItemInfo
	 * @param context
	 * @param pretaskitem_pretaskiteminfo
	 */
	public final void setPreTaskItem_PreTaskItemInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PreTaskItem pretaskitem_pretaskiteminfo)
	{
		if (pretaskitem_pretaskiteminfo == null) {
			getMendixObject().setValue(context, MemberNames.PreTaskItem_PreTaskItemInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PreTaskItem_PreTaskItemInfo.toString(), pretaskitem_pretaskiteminfo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PreTaskItemInfo_PreTaskListInfo
	 */
	public final excr_mfgordermanagement_api.proxies.PreTaskListInfo getPreTaskItemInfo_PreTaskListInfo() throws com.mendix.core.CoreException
	{
		return getPreTaskItemInfo_PreTaskListInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of PreTaskItemInfo_PreTaskListInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.PreTaskListInfo getPreTaskItemInfo_PreTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.PreTaskListInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PreTaskItemInfo_PreTaskListInfo.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.PreTaskListInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PreTaskItemInfo_PreTaskListInfo
	 * @param pretaskiteminfo_pretasklistinfo
	 */
	public final void setPreTaskItemInfo_PreTaskListInfo(excr_mfgordermanagement_api.proxies.PreTaskListInfo pretaskiteminfo_pretasklistinfo)
	{
		setPreTaskItemInfo_PreTaskListInfo(getContext(), pretaskiteminfo_pretasklistinfo);
	}

	/**
	 * Set value of PreTaskItemInfo_PreTaskListInfo
	 * @param context
	 * @param pretaskiteminfo_pretasklistinfo
	 */
	public final void setPreTaskItemInfo_PreTaskListInfo(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.PreTaskListInfo pretaskiteminfo_pretasklistinfo)
	{
		if (pretaskiteminfo_pretasklistinfo == null) {
			getMendixObject().setValue(context, MemberNames.PreTaskItemInfo_PreTaskListInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PreTaskItemInfo_PreTaskListInfo.toString(), pretaskiteminfo_pretasklistinfo.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return preTaskItemInfoMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement_api.proxies.PreTaskItemInfo that = (excr_mfgordermanagement_api.proxies.PreTaskItemInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
