// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_mfgordermanagement_api.proxies;

public class ReqMfgOrder implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqMfgOrderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_MfgOrderManagement_API.ReqMfgOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ReqMfgOrder_ReqGetMfgOrderbyName("EXCR_MfgOrderManagement_API.ReqMfgOrder_ReqGetMfgOrderbyName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqMfgOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqMfgOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqMfgOrderMendixObject)
	{
		if (reqMfgOrderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqMfgOrderMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqMfgOrderMendixObject = reqMfgOrderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_mfgordermanagement_api.proxies.ReqMfgOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_mfgordermanagement_api.proxies.ReqMfgOrder(context, mendixObject);
	}

	public static excr_mfgordermanagement_api.proxies.ReqMfgOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_mfgordermanagement_api.proxies.ReqMfgOrder.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqMfgOrder_ReqGetMfgOrderbyName
	 */
	public final excr_mfgordermanagement_api.proxies.ReqGetMfgOrderbyName getReqMfgOrder_ReqGetMfgOrderbyName() throws com.mendix.core.CoreException
	{
		return getReqMfgOrder_ReqGetMfgOrderbyName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqMfgOrder_ReqGetMfgOrderbyName
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_mfgordermanagement_api.proxies.ReqGetMfgOrderbyName getReqMfgOrder_ReqGetMfgOrderbyName(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_mfgordermanagement_api.proxies.ReqGetMfgOrderbyName result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqMfgOrder_ReqGetMfgOrderbyName.toString());
		if (identifier != null) {
			result = excr_mfgordermanagement_api.proxies.ReqGetMfgOrderbyName.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqMfgOrder_ReqGetMfgOrderbyName
	 * @param reqmfgorder_reqgetmfgorderbyname
	 */
	public final void setReqMfgOrder_ReqGetMfgOrderbyName(excr_mfgordermanagement_api.proxies.ReqGetMfgOrderbyName reqmfgorder_reqgetmfgorderbyname)
	{
		setReqMfgOrder_ReqGetMfgOrderbyName(getContext(), reqmfgorder_reqgetmfgorderbyname);
	}

	/**
	 * Set value of ReqMfgOrder_ReqGetMfgOrderbyName
	 * @param context
	 * @param reqmfgorder_reqgetmfgorderbyname
	 */
	public final void setReqMfgOrder_ReqGetMfgOrderbyName(com.mendix.systemwideinterfaces.core.IContext context, excr_mfgordermanagement_api.proxies.ReqGetMfgOrderbyName reqmfgorder_reqgetmfgorderbyname)
	{
		if (reqmfgorder_reqgetmfgorderbyname == null) {
			getMendixObject().setValue(context, MemberNames.ReqMfgOrder_ReqGetMfgOrderbyName.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqMfgOrder_ReqGetMfgOrderbyName.toString(), reqmfgorder_reqgetmfgorderbyname.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqMfgOrderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_mfgordermanagement_api.proxies.ReqMfgOrder that = (excr_mfgordermanagement_api.proxies.ReqMfgOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
