// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} hubName
 * @param {string} resourceNameList
 * @returns {Promise.<void>}
 */
export async function ResourceSetupOperationHubEventHandler(hubName, resourceNameList) {
	// BEGIN USER CODE
	if(resourceNameList)
	{
		var resourceNames = resourceNameList.split(",")
	}
	if (typeof $.connection !== 'undefined') 
	{
		if ($.connection.hub.state === $.signalR.connectionState.connected) 
		{
			const hub = $.connection[hubName];
			if(resourceNames && resourceNames.length !== 0)
			{				
				hub.server.subscribeToMultipleGroups(resourceNames, false);
				
			}
		}
	}
	// END USER CODE
}
