// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqContainerListFetchFromOperation implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqContainerListFetchFromOperationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqContainerListFetchFromOperation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Value("Value"),
		ReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters("EXCR_ResourceManagement_API.ReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqContainerListFetchFromOperation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqContainerListFetchFromOperation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqContainerListFetchFromOperationMendixObject)
	{
		if (reqContainerListFetchFromOperationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqContainerListFetchFromOperationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqContainerListFetchFromOperationMendixObject = reqContainerListFetchFromOperationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperation(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperation.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters
	 */
	public final excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperationParameters getReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters() throws com.mendix.core.CoreException
	{
		return getReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperationParameters getReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperationParameters result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperationParameters.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters
	 * @param reqcontainerlistfetchfromoperation_reqcontainerlistfetchfromoperationparameters
	 */
	public final void setReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters(excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperationParameters reqcontainerlistfetchfromoperation_reqcontainerlistfetchfromoperationparameters)
	{
		setReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters(getContext(), reqcontainerlistfetchfromoperation_reqcontainerlistfetchfromoperationparameters);
	}

	/**
	 * Set value of ReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters
	 * @param context
	 * @param reqcontainerlistfetchfromoperation_reqcontainerlistfetchfromoperationparameters
	 */
	public final void setReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperationParameters reqcontainerlistfetchfromoperation_reqcontainerlistfetchfromoperationparameters)
	{
		if (reqcontainerlistfetchfromoperation_reqcontainerlistfetchfromoperationparameters == null) {
			getMendixObject().setValue(context, MemberNames.ReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqContainerListFetchFromOperation_ReqContainerListFetchFromOperationParameters.toString(), reqcontainerlistfetchfromoperation_reqcontainerlistfetchfromoperationparameters.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqContainerListFetchFromOperationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperation that = (excr_resourcemanagement_api.proxies.ReqContainerListFetchFromOperation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
