// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourceStatusHistoryQuery implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourceStatusHistoryQueryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourceStatusHistoryQuery";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Value("Value"),
		ReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters("EXCR_ResourceManagement_API.ReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourceStatusHistoryQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourceStatusHistoryQuery(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourceStatusHistoryQueryMendixObject)
	{
		if (reqResourceStatusHistoryQueryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourceStatusHistoryQueryMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourceStatusHistoryQueryMendixObject = reqResourceStatusHistoryQueryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQuery initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQuery(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQuery load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQuery.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQueryParameters getReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters() throws com.mendix.core.CoreException
	{
		return getReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQueryParameters getReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQueryParameters result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQueryParameters.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters
	 * @param reqresourcestatushistoryquery_reqresourcestatushistoryqueryparameters
	 */
	public final void setReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters(excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQueryParameters reqresourcestatushistoryquery_reqresourcestatushistoryqueryparameters)
	{
		setReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters(getContext(), reqresourcestatushistoryquery_reqresourcestatushistoryqueryparameters);
	}

	/**
	 * Set value of ReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters
	 * @param context
	 * @param reqresourcestatushistoryquery_reqresourcestatushistoryqueryparameters
	 */
	public final void setReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQueryParameters reqresourcestatushistoryquery_reqresourcestatushistoryqueryparameters)
	{
		if (reqresourcestatushistoryquery_reqresourcestatushistoryqueryparameters == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourceStatusHistoryQuery_ReqResourceStatusHistoryQueryParameters.toString(), reqresourcestatushistoryquery_reqresourcestatushistoryqueryparameters.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourceStatusHistoryQueryMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQuery that = (excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryQuery) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
