// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourceSetupTxnRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourceSetupTxnRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourceSetupTxnRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Availability("Availability"),
		Comments("Comments"),
		ReqResourceSetupTxnResource_ReqResourceSetupTxnRoot("EXCR_ResourceManagement_API.ReqResourceSetupTxnResource_ReqResourceSetupTxnRoot"),
		ReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot("EXCR_ResourceManagement_API.ReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot"),
		ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot("EXCR_ResourceManagement_API.ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourceSetupTxnRootMendixObject)
	{
		if (reqResourceSetupTxnRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourceSetupTxnRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourceSetupTxnRootMendixObject = reqResourceSetupTxnRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot.initialize(context, mendixObject);
	}

	/**
	 * @return value of Availability
	 */
	public final java.lang.Integer getAvailability()
	{
		return getAvailability(getContext());
	}

	/**
	 * @param context
	 * @return value of Availability
	 */
	public final java.lang.Integer getAvailability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Availability.toString());
	}

	/**
	 * Set value of Availability
	 * @param availability
	 */
	public final void setAvailability(java.lang.Integer availability)
	{
		setAvailability(getContext(), availability);
	}

	/**
	 * Set value of Availability
	 * @param context
	 * @param availability
	 */
	public final void setAvailability(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer availability)
	{
		getMendixObject().setValue(context, MemberNames.Availability.toString(), availability);
	}

	/**
	 * @return value of Comments
	 */
	public final java.lang.String getComments()
	{
		return getComments(getContext());
	}

	/**
	 * @param context
	 * @return value of Comments
	 */
	public final java.lang.String getComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comments.toString());
	}

	/**
	 * Set value of Comments
	 * @param comments
	 */
	public final void setComments(java.lang.String comments)
	{
		setComments(getContext(), comments);
	}

	/**
	 * Set value of Comments
	 * @param context
	 * @param comments
	 */
	public final void setComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comments)
	{
		getMendixObject().setValue(context, MemberNames.Comments.toString(), comments);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourceSetupTxnResource_ReqResourceSetupTxnRoot
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResource getReqResourceSetupTxnResource_ReqResourceSetupTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqResourceSetupTxnResource_ReqResourceSetupTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceSetupTxnResource_ReqResourceSetupTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResource getReqResourceSetupTxnResource_ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResource result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourceSetupTxnResource_ReqResourceSetupTxnRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResource.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourceSetupTxnResource_ReqResourceSetupTxnRoot
	 * @param reqresourcesetuptxnresource_reqresourcesetuptxnroot
	 */
	public final void setReqResourceSetupTxnResource_ReqResourceSetupTxnRoot(excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResource reqresourcesetuptxnresource_reqresourcesetuptxnroot)
	{
		setReqResourceSetupTxnResource_ReqResourceSetupTxnRoot(getContext(), reqresourcesetuptxnresource_reqresourcesetuptxnroot);
	}

	/**
	 * Set value of ReqResourceSetupTxnResource_ReqResourceSetupTxnRoot
	 * @param context
	 * @param reqresourcesetuptxnresource_reqresourcesetuptxnroot
	 */
	public final void setReqResourceSetupTxnResource_ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResource reqresourcesetuptxnresource_reqresourcesetuptxnroot)
	{
		if (reqresourcesetuptxnresource_reqresourcesetuptxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourceSetupTxnResource_ReqResourceSetupTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourceSetupTxnResource_ReqResourceSetupTxnRoot.toString(), reqresourcesetuptxnresource_reqresourcesetuptxnroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusCode getReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusCode getReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot
	 * @param reqresourcesetuptxnresourcestatuscode_reqresourcesetuptxnroot
	 */
	public final void setReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot(excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusCode reqresourcesetuptxnresourcestatuscode_reqresourcesetuptxnroot)
	{
		setReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot(getContext(), reqresourcesetuptxnresourcestatuscode_reqresourcesetuptxnroot);
	}

	/**
	 * Set value of ReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot
	 * @param context
	 * @param reqresourcesetuptxnresourcestatuscode_reqresourcesetuptxnroot
	 */
	public final void setReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusCode reqresourcesetuptxnresourcestatuscode_reqresourcesetuptxnroot)
	{
		if (reqresourcesetuptxnresourcestatuscode_reqresourcesetuptxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourceSetupTxnResourceStatusCode_ReqResourceSetupTxnRoot.toString(), reqresourcesetuptxnresourcestatuscode_reqresourcesetuptxnroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason getReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason getReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot
	 * @param reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot
	 */
	public final void setReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot)
	{
		setReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(getContext(), reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot);
	}

	/**
	 * Set value of ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot
	 * @param context
	 * @param reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot
	 */
	public final void setReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot)
	{
		if (reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot.toString(), reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourceSetupTxnRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot that = (excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
