// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourcePinAddResourcePinAction implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinAddResourcePinActionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourcePinAddResourcePinAction";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ListItemAction("ListItemAction"),
		ReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded("EXCR_ResourceManagement_API.ReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded"),
		ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction("EXCR_ResourceManagement_API.ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourcePinAddResourcePinAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourcePinAddResourcePinAction(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinAddResourcePinActionMendixObject)
	{
		if (reqResourcePinAddResourcePinActionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourcePinAddResourcePinActionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourcePinAddResourcePinActionMendixObject = reqResourcePinAddResourcePinActionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction.initialize(context, mendixObject);
	}

	/**
	 * @return value of ListItemAction
	 */
	public final java.lang.String getListItemAction()
	{
		return getListItemAction(getContext());
	}

	/**
	 * @param context
	 * @return value of ListItemAction
	 */
	public final java.lang.String getListItemAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ListItemAction.toString());
	}

	/**
	 * Set value of ListItemAction
	 * @param listitemaction
	 */
	public final void setListItemAction(java.lang.String listitemaction)
	{
		setListItemAction(getContext(), listitemaction);
	}

	/**
	 * Set value of ListItemAction
	 * @param context
	 * @param listitemaction
	 */
	public final void setListItemAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String listitemaction)
	{
		getMendixObject().setValue(context, MemberNames.ListItemAction.toString(), listitemaction);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddDetailsExpanded getReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded() throws com.mendix.core.CoreException
	{
		return getReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddDetailsExpanded getReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinAddDetailsExpanded result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinAddDetailsExpanded.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded
	 * @param reqresourcepinaddresourcepinaction_reqresourcepinadddetailsexpanded
	 */
	public final void setReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded(excr_resourcemanagement_api.proxies.ReqResourcePinAddDetailsExpanded reqresourcepinaddresourcepinaction_reqresourcepinadddetailsexpanded)
	{
		setReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded(getContext(), reqresourcepinaddresourcepinaction_reqresourcepinadddetailsexpanded);
	}

	/**
	 * Set value of ReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded
	 * @param context
	 * @param reqresourcepinaddresourcepinaction_reqresourcepinadddetailsexpanded
	 */
	public final void setReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinAddDetailsExpanded reqresourcepinaddresourcepinaction_reqresourcepinadddetailsexpanded)
	{
		if (reqresourcepinaddresourcepinaction_reqresourcepinadddetailsexpanded == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddResourcePinAction_ReqResourcePinAddDetailsExpanded.toString(), reqresourcepinaddresourcepinaction_reqresourcepinadddetailsexpanded.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue getReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction() throws com.mendix.core.CoreException
	{
		return getReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue getReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction
	 * @param reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction
	 */
	public final void setReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction)
	{
		setReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(getContext(), reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction);
	}

	/**
	 * Set value of ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction
	 * @param context
	 * @param reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction
	 */
	public final void setReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction)
	{
		if (reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction.toString(), reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourcePinAddResourcePinActionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction that = (excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
