// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourcePinAddResourcePinValue implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinAddResourcePinValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourcePinAddResourcePinValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		XLocation("XLocation"),
		YLocation("YLocation"),
		Name("Name"),
		MarkerType("MarkerType"),
		ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction("EXCR_ResourceManagement_API.ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction"),
		ReqResourcePinAddResource_ReqResourcePinAddResourcePinValue("EXCR_ResourceManagement_API.ReqResourcePinAddResource_ReqResourcePinAddResourcePinValue"),
		ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue("EXCR_ResourceManagement_API.ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue"),
		ReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue("EXCR_ResourceManagement_API.ReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue"),
		ReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue("EXCR_ResourceManagement_API.ReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue"),
		ReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue("EXCR_ResourceManagement_API.ReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinAddResourcePinValueMendixObject)
	{
		if (reqResourcePinAddResourcePinValueMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourcePinAddResourcePinValueMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourcePinAddResourcePinValueMendixObject = reqResourcePinAddResourcePinValueMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue.initialize(context, mendixObject);
	}

	/**
	 * @return value of XLocation
	 */
	public final java.math.BigDecimal getXLocation()
	{
		return getXLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of XLocation
	 */
	public final java.math.BigDecimal getXLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.XLocation.toString());
	}

	/**
	 * Set value of XLocation
	 * @param xlocation
	 */
	public final void setXLocation(java.math.BigDecimal xlocation)
	{
		setXLocation(getContext(), xlocation);
	}

	/**
	 * Set value of XLocation
	 * @param context
	 * @param xlocation
	 */
	public final void setXLocation(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal xlocation)
	{
		getMendixObject().setValue(context, MemberNames.XLocation.toString(), xlocation);
	}

	/**
	 * @return value of YLocation
	 */
	public final java.math.BigDecimal getYLocation()
	{
		return getYLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of YLocation
	 */
	public final java.math.BigDecimal getYLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.YLocation.toString());
	}

	/**
	 * Set value of YLocation
	 * @param ylocation
	 */
	public final void setYLocation(java.math.BigDecimal ylocation)
	{
		setYLocation(getContext(), ylocation);
	}

	/**
	 * Set value of YLocation
	 * @param context
	 * @param ylocation
	 */
	public final void setYLocation(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ylocation)
	{
		getMendixObject().setValue(context, MemberNames.YLocation.toString(), ylocation);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of MarkerType
	 */
	public final java.lang.String getMarkerType()
	{
		return getMarkerType(getContext());
	}

	/**
	 * @param context
	 * @return value of MarkerType
	 */
	public final java.lang.String getMarkerType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MarkerType.toString());
	}

	/**
	 * Set value of MarkerType
	 * @param markertype
	 */
	public final void setMarkerType(java.lang.String markertype)
	{
		setMarkerType(getContext(), markertype);
	}

	/**
	 * Set value of MarkerType
	 * @param context
	 * @param markertype
	 */
	public final void setMarkerType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String markertype)
	{
		getMendixObject().setValue(context, MemberNames.MarkerType.toString(), markertype);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction getReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction() throws com.mendix.core.CoreException
	{
		return getReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction getReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction
	 * @param reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction
	 */
	public final void setReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction)
	{
		setReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(getContext(), reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction);
	}

	/**
	 * Set value of ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction
	 * @param context
	 * @param reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction
	 */
	public final void setReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinAction reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction)
	{
		if (reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddResourcePinValue_ReqResourcePinAddResourcePinAction.toString(), reqresourcepinaddresourcepinvalue_reqresourcepinaddresourcepinaction.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinAddResource_ReqResourcePinAddResourcePinValue
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddResource getReqResourcePinAddResource_ReqResourcePinAddResourcePinValue() throws com.mendix.core.CoreException
	{
		return getReqResourcePinAddResource_ReqResourcePinAddResourcePinValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinAddResource_ReqResourcePinAddResourcePinValue
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddResource getReqResourcePinAddResource_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinAddResource result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinAddResource_ReqResourcePinAddResourcePinValue.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinAddResource.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinAddResource_ReqResourcePinAddResourcePinValue
	 * @param reqresourcepinaddresource_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddResource_ReqResourcePinAddResourcePinValue(excr_resourcemanagement_api.proxies.ReqResourcePinAddResource reqresourcepinaddresource_reqresourcepinaddresourcepinvalue)
	{
		setReqResourcePinAddResource_ReqResourcePinAddResourcePinValue(getContext(), reqresourcepinaddresource_reqresourcepinaddresourcepinvalue);
	}

	/**
	 * Set value of ReqResourcePinAddResource_ReqResourcePinAddResourcePinValue
	 * @param context
	 * @param reqresourcepinaddresource_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddResource_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinAddResource reqresourcepinaddresource_reqresourcepinaddresourcepinvalue)
	{
		if (reqresourcepinaddresource_reqresourcepinaddresourcepinvalue == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddResource_ReqResourcePinAddResourcePinValue.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddResource_ReqResourcePinAddResourcePinValue.toString(), reqresourcepinaddresource_reqresourcepinaddresourcepinvalue.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout getReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue() throws com.mendix.core.CoreException
	{
		return getReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout getReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue
	 * @param reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue)
	{
		setReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(getContext(), reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue);
	}

	/**
	 * Set value of ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue
	 * @param context
	 * @param reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue)
	{
		if (reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue.toString(), reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddOperation getReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue() throws com.mendix.core.CoreException
	{
		return getReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddOperation getReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinAddOperation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinAddOperation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue
	 * @param reqresourcepinaddoperation_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue(excr_resourcemanagement_api.proxies.ReqResourcePinAddOperation reqresourcepinaddoperation_reqresourcepinaddresourcepinvalue)
	{
		setReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue(getContext(), reqresourcepinaddoperation_reqresourcepinaddresourcepinvalue);
	}

	/**
	 * Set value of ReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue
	 * @param context
	 * @param reqresourcepinaddoperation_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinAddOperation reqresourcepinaddoperation_reqresourcepinaddresourcepinvalue)
	{
		if (reqresourcepinaddoperation_reqresourcepinaddresourcepinvalue == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddOperation_ReqResourcePinAddResourcePinValue.toString(), reqresourcepinaddoperation_reqresourcepinaddresourcepinvalue.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcerPinAddSpec getReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue() throws com.mendix.core.CoreException
	{
		return getReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcerPinAddSpec getReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcerPinAddSpec result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcerPinAddSpec.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue
	 * @param reqresourcerpinaddspec_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue(excr_resourcemanagement_api.proxies.ReqResourcerPinAddSpec reqresourcerpinaddspec_reqresourcepinaddresourcepinvalue)
	{
		setReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue(getContext(), reqresourcerpinaddspec_reqresourcepinaddresourcepinvalue);
	}

	/**
	 * Set value of ReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue
	 * @param context
	 * @param reqresourcerpinaddspec_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcerPinAddSpec reqresourcerpinaddspec_reqresourcepinaddresourcepinvalue)
	{
		if (reqresourcerpinaddspec_reqresourcepinaddresourcepinvalue == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcerPinAddSpec_ReqResourcePinAddResourcePinValue.toString(), reqresourcerpinaddspec_reqresourcepinaddresourcepinvalue.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddWorkCenter getReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue() throws com.mendix.core.CoreException
	{
		return getReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddWorkCenter getReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinAddWorkCenter result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinAddWorkCenter.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue
	 * @param reqresourcepinaddworkcenter_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue(excr_resourcemanagement_api.proxies.ReqResourcePinAddWorkCenter reqresourcepinaddworkcenter_reqresourcepinaddresourcepinvalue)
	{
		setReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue(getContext(), reqresourcepinaddworkcenter_reqresourcepinaddresourcepinvalue);
	}

	/**
	 * Set value of ReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue
	 * @param context
	 * @param reqresourcepinaddworkcenter_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinAddWorkCenter reqresourcepinaddworkcenter_reqresourcepinaddresourcepinvalue)
	{
		if (reqresourcepinaddworkcenter_reqresourcepinaddresourcepinvalue == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddWorkCenter_ReqResourcePinAddResourcePinValue.toString(), reqresourcepinaddworkcenter_reqresourcepinaddresourcepinvalue.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourcePinAddResourcePinValueMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue that = (excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
