// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourceStatusHistoryRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourceStatusHistoryRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourceStatusHistoryRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot("EXCR_ResourceManagement_API.ReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourceStatusHistoryRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourceStatusHistoryRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourceStatusHistoryRootMendixObject)
	{
		if (reqResourceStatusHistoryRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourceStatusHistoryRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourceStatusHistoryRootMendixObject = reqResourceStatusHistoryRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryRoot(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryParameters getReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot() throws com.mendix.core.CoreException
	{
		return getReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryParameters getReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryParameters result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryParameters.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot
	 * @param reqresourcestatushistoryparameters_reqresourcestatushistoryroot
	 */
	public final void setReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot(excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryParameters reqresourcestatushistoryparameters_reqresourcestatushistoryroot)
	{
		setReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot(getContext(), reqresourcestatushistoryparameters_reqresourcestatushistoryroot);
	}

	/**
	 * Set value of ReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot
	 * @param context
	 * @param reqresourcestatushistoryparameters_reqresourcestatushistoryroot
	 */
	public final void setReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryParameters reqresourcestatushistoryparameters_reqresourcestatushistoryroot)
	{
		if (reqresourcestatushistoryparameters_reqresourcestatushistoryroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourceStatusHistoryParameters_ReqResourceStatusHistoryRoot.toString(), reqresourcestatushistoryparameters_reqresourcestatushistoryroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourceStatusHistoryRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryRoot that = (excr_resourcemanagement_api.proxies.ReqResourceStatusHistoryRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
