// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourcePinEditRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinEditRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourcePinEditRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot("EXCR_ResourceManagement_API.ReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourcePinEditRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourcePinEditRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinEditRootMendixObject)
	{
		if (reqResourcePinEditRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourcePinEditRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourcePinEditRootMendixObject = reqResourcePinEditRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourcePinEditRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourcePinEditRoot(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourcePinEditRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourcePinEditRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot getReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot() throws com.mendix.core.CoreException
	{
		return getReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot getReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot
	 * @param reqresourcepineditdetailsexpandedroot_reqresourcepineditroot
	 */
	public final void setReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot(excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot reqresourcepineditdetailsexpandedroot_reqresourcepineditroot)
	{
		setReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot(getContext(), reqresourcepineditdetailsexpandedroot_reqresourcepineditroot);
	}

	/**
	 * Set value of ReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot
	 * @param context
	 * @param reqresourcepineditdetailsexpandedroot_reqresourcepineditroot
	 */
	public final void setReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot reqresourcepineditdetailsexpandedroot_reqresourcepineditroot)
	{
		if (reqresourcepineditdetailsexpandedroot_reqresourcepineditroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditDetailsExpandedRoot_ReqResourcePinEditRoot.toString(), reqresourcepineditdetailsexpandedroot_reqresourcepineditroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourcePinEditRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourcePinEditRoot that = (excr_resourcemanagement_api.proxies.ReqResourcePinEditRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
