// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourcePinEditSpec implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinEditSpecMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourcePinEditSpec";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		UseROR("UseROR"),
		ReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue("EXCR_ResourceManagement_API.ReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourcePinEditSpec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourcePinEditSpec(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinEditSpecMendixObject)
	{
		if (reqResourcePinEditSpecMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourcePinEditSpecMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourcePinEditSpecMendixObject = reqResourcePinEditSpecMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourcePinEditSpec initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourcePinEditSpec(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourcePinEditSpec load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourcePinEditSpec.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of UseROR
	 */
	public final java.lang.String getUseROR()
	{
		return getUseROR(getContext());
	}

	/**
	 * @param context
	 * @return value of UseROR
	 */
	public final java.lang.String getUseROR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseROR.toString());
	}

	/**
	 * Set value of UseROR
	 * @param useror
	 */
	public final void setUseROR(java.lang.String useror)
	{
		setUseROR(getContext(), useror);
	}

	/**
	 * Set value of UseROR
	 * @param context
	 * @param useror
	 */
	public final void setUseROR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String useror)
	{
		getMendixObject().setValue(context, MemberNames.UseROR.toString(), useror);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue getReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue() throws com.mendix.core.CoreException
	{
		return getReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue getReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue
	 * @param reqresourcepineditspec_reqresourcepineditresourcepinvalue
	 */
	public final void setReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue(excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue reqresourcepineditspec_reqresourcepineditresourcepinvalue)
	{
		setReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue(getContext(), reqresourcepineditspec_reqresourcepineditresourcepinvalue);
	}

	/**
	 * Set value of ReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue
	 * @param context
	 * @param reqresourcepineditspec_reqresourcepineditresourcepinvalue
	 */
	public final void setReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue reqresourcepineditspec_reqresourcepineditresourcepinvalue)
	{
		if (reqresourcepineditspec_reqresourcepineditresourcepinvalue == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditSpec_ReqResourcePinEditResourcePinValue.toString(), reqresourcepineditspec_reqresourcepineditresourcepinvalue.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourcePinEditSpecMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourcePinEditSpec that = (excr_resourcemanagement_api.proxies.ReqResourcePinEditSpec) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
