// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourceLayoutSaveRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourceLayoutSaveRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourceLayoutSaveRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		BackgroundFilename("BackgroundFilename"),
		Description("Description"),
		ReqResourceLayoutSaveRoot_ReqImage("EXCR_ResourceManagement_API.ReqResourceLayoutSaveRoot_ReqImage"),
		ResourceLayout_ReqResourceLayoutSaveRoot("EXCR_ResourceManagement.ResourceLayout_ReqResourceLayoutSaveRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourceLayoutSaveRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourceLayoutSaveRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourceLayoutSaveRootMendixObject)
	{
		if (reqResourceLayoutSaveRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourceLayoutSaveRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourceLayoutSaveRootMendixObject = reqResourceLayoutSaveRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourceLayoutSaveRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourceLayoutSaveRoot(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourceLayoutSaveRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourceLayoutSaveRoot.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of BackgroundFilename
	 */
	public final java.lang.String getBackgroundFilename()
	{
		return getBackgroundFilename(getContext());
	}

	/**
	 * @param context
	 * @return value of BackgroundFilename
	 */
	public final java.lang.String getBackgroundFilename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BackgroundFilename.toString());
	}

	/**
	 * Set value of BackgroundFilename
	 * @param backgroundfilename
	 */
	public final void setBackgroundFilename(java.lang.String backgroundfilename)
	{
		setBackgroundFilename(getContext(), backgroundfilename);
	}

	/**
	 * Set value of BackgroundFilename
	 * @param context
	 * @param backgroundfilename
	 */
	public final void setBackgroundFilename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String backgroundfilename)
	{
		getMendixObject().setValue(context, MemberNames.BackgroundFilename.toString(), backgroundfilename);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourceLayoutSaveRoot_ReqImage
	 */
	public final excr_resourcemanagement_api.proxies.ReqImage getReqResourceLayoutSaveRoot_ReqImage() throws com.mendix.core.CoreException
	{
		return getReqResourceLayoutSaveRoot_ReqImage(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceLayoutSaveRoot_ReqImage
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqImage getReqResourceLayoutSaveRoot_ReqImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourceLayoutSaveRoot_ReqImage.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourceLayoutSaveRoot_ReqImage
	 * @param reqresourcelayoutsaveroot_reqimage
	 */
	public final void setReqResourceLayoutSaveRoot_ReqImage(excr_resourcemanagement_api.proxies.ReqImage reqresourcelayoutsaveroot_reqimage)
	{
		setReqResourceLayoutSaveRoot_ReqImage(getContext(), reqresourcelayoutsaveroot_reqimage);
	}

	/**
	 * Set value of ReqResourceLayoutSaveRoot_ReqImage
	 * @param context
	 * @param reqresourcelayoutsaveroot_reqimage
	 */
	public final void setReqResourceLayoutSaveRoot_ReqImage(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqImage reqresourcelayoutsaveroot_reqimage)
	{
		if (reqresourcelayoutsaveroot_reqimage == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourceLayoutSaveRoot_ReqImage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourceLayoutSaveRoot_ReqImage.toString(), reqresourcelayoutsaveroot_reqimage.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourceLayout_ReqResourceLayoutSaveRoot
	 */
	public final excr_resourcemanagement.proxies.ResourceLayout getResourceLayout_ReqResourceLayoutSaveRoot() throws com.mendix.core.CoreException
	{
		return getResourceLayout_ReqResourceLayoutSaveRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceLayout_ReqResourceLayoutSaveRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ResourceLayout getResourceLayout_ReqResourceLayoutSaveRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ResourceLayout result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourceLayout_ReqResourceLayoutSaveRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ResourceLayout.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourceLayout_ReqResourceLayoutSaveRoot
	 * @param resourcelayout_reqresourcelayoutsaveroot
	 */
	public final void setResourceLayout_ReqResourceLayoutSaveRoot(excr_resourcemanagement.proxies.ResourceLayout resourcelayout_reqresourcelayoutsaveroot)
	{
		setResourceLayout_ReqResourceLayoutSaveRoot(getContext(), resourcelayout_reqresourcelayoutsaveroot);
	}

	/**
	 * Set value of ResourceLayout_ReqResourceLayoutSaveRoot
	 * @param context
	 * @param resourcelayout_reqresourcelayoutsaveroot
	 */
	public final void setResourceLayout_ReqResourceLayoutSaveRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ResourceLayout resourcelayout_reqresourcelayoutsaveroot)
	{
		if (resourcelayout_reqresourcelayoutsaveroot == null) {
			getMendixObject().setValue(context, MemberNames.ResourceLayout_ReqResourceLayoutSaveRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourceLayout_ReqResourceLayoutSaveRoot.toString(), resourcelayout_reqresourcelayoutsaveroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourceLayoutSaveRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourceLayoutSaveRoot that = (excr_resourcemanagement_api.proxies.ReqResourceLayoutSaveRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
