// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourcePinEditLinkedLayout implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinEditLinkedLayoutMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourcePinEditLinkedLayout";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LinkedLayoutName("LinkedLayoutName"),
		ReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue("EXCR_ResourceManagement_API.ReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourcePinEditLinkedLayout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourcePinEditLinkedLayout(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinEditLinkedLayoutMendixObject)
	{
		if (reqResourcePinEditLinkedLayoutMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourcePinEditLinkedLayoutMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourcePinEditLinkedLayoutMendixObject = reqResourcePinEditLinkedLayoutMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourcePinEditLinkedLayout initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourcePinEditLinkedLayout(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourcePinEditLinkedLayout load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourcePinEditLinkedLayout.initialize(context, mendixObject);
	}

	/**
	 * @return value of LinkedLayoutName
	 */
	public final java.lang.String getLinkedLayoutName()
	{
		return getLinkedLayoutName(getContext());
	}

	/**
	 * @param context
	 * @return value of LinkedLayoutName
	 */
	public final java.lang.String getLinkedLayoutName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LinkedLayoutName.toString());
	}

	/**
	 * Set value of LinkedLayoutName
	 * @param linkedlayoutname
	 */
	public final void setLinkedLayoutName(java.lang.String linkedlayoutname)
	{
		setLinkedLayoutName(getContext(), linkedlayoutname);
	}

	/**
	 * Set value of LinkedLayoutName
	 * @param context
	 * @param linkedlayoutname
	 */
	public final void setLinkedLayoutName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String linkedlayoutname)
	{
		getMendixObject().setValue(context, MemberNames.LinkedLayoutName.toString(), linkedlayoutname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue getReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue() throws com.mendix.core.CoreException
	{
		return getReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue getReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue
	 * @param reqresourcepineditlinkedlayout_reqresourcepineditresourcepinvalue
	 */
	public final void setReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue(excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue reqresourcepineditlinkedlayout_reqresourcepineditresourcepinvalue)
	{
		setReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue(getContext(), reqresourcepineditlinkedlayout_reqresourcepineditresourcepinvalue);
	}

	/**
	 * Set value of ReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue
	 * @param context
	 * @param reqresourcepineditlinkedlayout_reqresourcepineditresourcepinvalue
	 */
	public final void setReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue reqresourcepineditlinkedlayout_reqresourcepineditresourcepinvalue)
	{
		if (reqresourcepineditlinkedlayout_reqresourcepineditresourcepinvalue == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditLinkedLayout_ReqResourcePinEditResourcePinValue.toString(), reqresourcepineditlinkedlayout_reqresourcepineditresourcepinvalue.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourcePinEditLinkedLayoutMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourcePinEditLinkedLayout that = (excr_resourcemanagement_api.proxies.ReqResourcePinEditLinkedLayout) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
