// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourcePinAddLinkedLayout implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinAddLinkedLayoutMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourcePinAddLinkedLayout";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LinkedLayoutName("LinkedLayoutName"),
		ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue("EXCR_ResourceManagement_API.ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourcePinAddLinkedLayout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourcePinAddLinkedLayout(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinAddLinkedLayoutMendixObject)
	{
		if (reqResourcePinAddLinkedLayoutMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourcePinAddLinkedLayoutMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourcePinAddLinkedLayoutMendixObject = reqResourcePinAddLinkedLayoutMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout.initialize(context, mendixObject);
	}

	/**
	 * @return value of LinkedLayoutName
	 */
	public final java.lang.String getLinkedLayoutName()
	{
		return getLinkedLayoutName(getContext());
	}

	/**
	 * @param context
	 * @return value of LinkedLayoutName
	 */
	public final java.lang.String getLinkedLayoutName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LinkedLayoutName.toString());
	}

	/**
	 * Set value of LinkedLayoutName
	 * @param linkedlayoutname
	 */
	public final void setLinkedLayoutName(java.lang.String linkedlayoutname)
	{
		setLinkedLayoutName(getContext(), linkedlayoutname);
	}

	/**
	 * Set value of LinkedLayoutName
	 * @param context
	 * @param linkedlayoutname
	 */
	public final void setLinkedLayoutName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String linkedlayoutname)
	{
		getMendixObject().setValue(context, MemberNames.LinkedLayoutName.toString(), linkedlayoutname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue getReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue() throws com.mendix.core.CoreException
	{
		return getReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue getReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue
	 * @param reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue)
	{
		setReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(getContext(), reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue);
	}

	/**
	 * Set value of ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue
	 * @param context
	 * @param reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue
	 */
	public final void setReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinAddResourcePinValue reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue)
	{
		if (reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinAddLinkedLayout_ReqResourcePinAddResourcePinValue.toString(), reqresourcepinaddlinkedlayout_reqresourcepinaddresourcepinvalue.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourcePinAddLinkedLayoutMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout that = (excr_resourcemanagement_api.proxies.ReqResourcePinAddLinkedLayout) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
