// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourcePinEditDetailsExpanded implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinEditDetailsExpandedMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourcePinEditDetailsExpanded";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot("EXCR_ResourceManagement_API.ReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot"),
		ReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded("EXCR_ResourceManagement_API.ReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded"),
		ReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded("EXCR_ResourceManagement_API.ReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourcePinEditDetailsExpanded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourcePinEditDetailsExpanded(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourcePinEditDetailsExpandedMendixObject)
	{
		if (reqResourcePinEditDetailsExpandedMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourcePinEditDetailsExpandedMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourcePinEditDetailsExpandedMendixObject = reqResourcePinEditDetailsExpandedMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpanded initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpanded(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpanded load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpanded.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot getReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot() throws com.mendix.core.CoreException
	{
		return getReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot getReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot
	 * @param reqresourcepineditdetailsexpanded_reqresourcepineditdetailsexpandedroot
	 */
	public final void setReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot(excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot reqresourcepineditdetailsexpanded_reqresourcepineditdetailsexpandedroot)
	{
		setReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot(getContext(), reqresourcepineditdetailsexpanded_reqresourcepineditdetailsexpandedroot);
	}

	/**
	 * Set value of ReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot
	 * @param context
	 * @param reqresourcepineditdetailsexpanded_reqresourcepineditdetailsexpandedroot
	 */
	public final void setReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpandedRoot reqresourcepineditdetailsexpanded_reqresourcepineditdetailsexpandedroot)
	{
		if (reqresourcepineditdetailsexpanded_reqresourcepineditdetailsexpandedroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditDetailsExpanded_ReqResourcePinEditDetailsExpandedRoot.toString(), reqresourcepineditdetailsexpanded_reqresourcepineditdetailsexpandedroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinKey getReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded() throws com.mendix.core.CoreException
	{
		return getReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinKey getReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinKey result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinKey.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded
	 * @param reqresourcepineditresourcepinkey_reqresourcepineditdetailsexpanded
	 */
	public final void setReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded(excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinKey reqresourcepineditresourcepinkey_reqresourcepineditdetailsexpanded)
	{
		setReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded(getContext(), reqresourcepineditresourcepinkey_reqresourcepineditdetailsexpanded);
	}

	/**
	 * Set value of ReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded
	 * @param context
	 * @param reqresourcepineditresourcepinkey_reqresourcepineditdetailsexpanded
	 */
	public final void setReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinKey reqresourcepineditresourcepinkey_reqresourcepineditdetailsexpanded)
	{
		if (reqresourcepineditresourcepinkey_reqresourcepineditdetailsexpanded == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditResourcePinKey_ReqResourcePinEditDetailsExpanded.toString(), reqresourcepineditresourcepinkey_reqresourcepineditdetailsexpanded.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue getReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded() throws com.mendix.core.CoreException
	{
		return getReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue getReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded
	 * @param reqresourcepineditresourcepinvalue_reqresourcepineditdetailsexpanded
	 */
	public final void setReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded(excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue reqresourcepineditresourcepinvalue_reqresourcepineditdetailsexpanded)
	{
		setReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded(getContext(), reqresourcepineditresourcepinvalue_reqresourcepineditdetailsexpanded);
	}

	/**
	 * Set value of ReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded
	 * @param context
	 * @param reqresourcepineditresourcepinvalue_reqresourcepineditdetailsexpanded
	 */
	public final void setReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourcePinEditResourcePinValue reqresourcepineditresourcepinvalue_reqresourcepineditdetailsexpanded)
	{
		if (reqresourcepineditresourcepinvalue_reqresourcepineditdetailsexpanded == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourcePinEditResourcePinValue_ReqResourcePinEditDetailsExpanded.toString(), reqresourcepineditresourcepinvalue_reqresourcepineditdetailsexpanded.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourcePinEditDetailsExpandedMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpanded that = (excr_resourcemanagement_api.proxies.ReqResourcePinEditDetailsExpanded) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
