// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourceStatusReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourceStatusReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourceStatusReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ReqResourceStatusReason_ReqResourceStatusReasonRoot("EXCR_ResourceManagement_API.ReqResourceStatusReason_ReqResourceStatusReasonRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourceStatusReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourceStatusReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourceStatusReasonMendixObject)
	{
		if (reqResourceStatusReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourceStatusReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourceStatusReasonMendixObject = reqResourceStatusReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourceStatusReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourceStatusReason(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourceStatusReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourceStatusReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourceStatusReason_ReqResourceStatusReasonRoot
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceStatusReasonRoot getReqResourceStatusReason_ReqResourceStatusReasonRoot() throws com.mendix.core.CoreException
	{
		return getReqResourceStatusReason_ReqResourceStatusReasonRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceStatusReason_ReqResourceStatusReasonRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceStatusReasonRoot getReqResourceStatusReason_ReqResourceStatusReasonRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourceStatusReasonRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourceStatusReason_ReqResourceStatusReasonRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourceStatusReasonRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourceStatusReason_ReqResourceStatusReasonRoot
	 * @param reqresourcestatusreason_reqresourcestatusreasonroot
	 */
	public final void setReqResourceStatusReason_ReqResourceStatusReasonRoot(excr_resourcemanagement_api.proxies.ReqResourceStatusReasonRoot reqresourcestatusreason_reqresourcestatusreasonroot)
	{
		setReqResourceStatusReason_ReqResourceStatusReasonRoot(getContext(), reqresourcestatusreason_reqresourcestatusreasonroot);
	}

	/**
	 * Set value of ReqResourceStatusReason_ReqResourceStatusReasonRoot
	 * @param context
	 * @param reqresourcestatusreason_reqresourcestatusreasonroot
	 */
	public final void setReqResourceStatusReason_ReqResourceStatusReasonRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourceStatusReasonRoot reqresourcestatusreason_reqresourcestatusreasonroot)
	{
		if (reqresourcestatusreason_reqresourcestatusreasonroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourceStatusReason_ReqResourceStatusReasonRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourceStatusReason_ReqResourceStatusReasonRoot.toString(), reqresourcestatusreason_reqresourcestatusreasonroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourceStatusReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourceStatusReason that = (excr_resourcemanagement_api.proxies.ReqResourceStatusReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
