// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourceSetupTxnResourceStatusReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourceSetupTxnResourceStatusReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourceSetupTxnResourceStatusReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot("EXCR_ResourceManagement_API.ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourceSetupTxnResourceStatusReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourceSetupTxnResourceStatusReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourceSetupTxnResourceStatusReasonMendixObject)
	{
		if (reqResourceSetupTxnResourceStatusReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourceSetupTxnResourceStatusReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourceSetupTxnResourceStatusReasonMendixObject = reqResourceSetupTxnResourceStatusReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot getReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot() throws com.mendix.core.CoreException
	{
		return getReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot getReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot
	 * @param reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot
	 */
	public final void setReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot)
	{
		setReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(getContext(), reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot);
	}

	/**
	 * Set value of ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot
	 * @param context
	 * @param reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot
	 */
	public final void setReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourceSetupTxnRoot reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot)
	{
		if (reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourceSetupTxnResourceStatusReason_ReqResourceSetupTxnRoot.toString(), reqresourcesetuptxnresourcestatusreason_reqresourcesetuptxnroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourceSetupTxnResourceStatusReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason that = (excr_resourcemanagement_api.proxies.ReqResourceSetupTxnResourceStatusReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
