// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ReqResourceDetailsRootEvent implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqResourceDetailsRootEventMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ReqResourceDetailsRootEvent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ReqResourceDetailsRootEventName("ReqResourceDetailsRootEventName"),
		ReqResourceDetailsRootEvent_ReqResourceDetailsRoot("EXCR_ResourceManagement_API.ReqResourceDetailsRootEvent_ReqResourceDetailsRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqResourceDetailsRootEvent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqResourceDetailsRootEvent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqResourceDetailsRootEventMendixObject)
	{
		if (reqResourceDetailsRootEventMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqResourceDetailsRootEventMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqResourceDetailsRootEventMendixObject = reqResourceDetailsRootEventMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ReqResourceDetailsRootEvent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ReqResourceDetailsRootEvent(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ReqResourceDetailsRootEvent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ReqResourceDetailsRootEvent.initialize(context, mendixObject);
	}

	/**
	 * @return value of ReqResourceDetailsRootEventName
	 */
	public final java.lang.String getReqResourceDetailsRootEventName()
	{
		return getReqResourceDetailsRootEventName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceDetailsRootEventName
	 */
	public final java.lang.String getReqResourceDetailsRootEventName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReqResourceDetailsRootEventName.toString());
	}

	/**
	 * Set value of ReqResourceDetailsRootEventName
	 * @param reqresourcedetailsrooteventname
	 */
	public final void setReqResourceDetailsRootEventName(java.lang.String reqresourcedetailsrooteventname)
	{
		setReqResourceDetailsRootEventName(getContext(), reqresourcedetailsrooteventname);
	}

	/**
	 * Set value of ReqResourceDetailsRootEventName
	 * @param context
	 * @param reqresourcedetailsrooteventname
	 */
	public final void setReqResourceDetailsRootEventName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reqresourcedetailsrooteventname)
	{
		getMendixObject().setValue(context, MemberNames.ReqResourceDetailsRootEventName.toString(), reqresourcedetailsrooteventname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ReqResourceDetailsRootEvent_ReqResourceDetailsRoot
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceDetailsRoot getReqResourceDetailsRootEvent_ReqResourceDetailsRoot() throws com.mendix.core.CoreException
	{
		return getReqResourceDetailsRootEvent_ReqResourceDetailsRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ReqResourceDetailsRootEvent_ReqResourceDetailsRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ReqResourceDetailsRoot getReqResourceDetailsRootEvent_ReqResourceDetailsRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ReqResourceDetailsRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReqResourceDetailsRootEvent_ReqResourceDetailsRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ReqResourceDetailsRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ReqResourceDetailsRootEvent_ReqResourceDetailsRoot
	 * @param reqresourcedetailsrootevent_reqresourcedetailsroot
	 */
	public final void setReqResourceDetailsRootEvent_ReqResourceDetailsRoot(excr_resourcemanagement_api.proxies.ReqResourceDetailsRoot reqresourcedetailsrootevent_reqresourcedetailsroot)
	{
		setReqResourceDetailsRootEvent_ReqResourceDetailsRoot(getContext(), reqresourcedetailsrootevent_reqresourcedetailsroot);
	}

	/**
	 * Set value of ReqResourceDetailsRootEvent_ReqResourceDetailsRoot
	 * @param context
	 * @param reqresourcedetailsrootevent_reqresourcedetailsroot
	 */
	public final void setReqResourceDetailsRootEvent_ReqResourceDetailsRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ReqResourceDetailsRoot reqresourcedetailsrootevent_reqresourcedetailsroot)
	{
		if (reqresourcedetailsrootevent_reqresourcedetailsroot == null) {
			getMendixObject().setValue(context, MemberNames.ReqResourceDetailsRootEvent_ReqResourceDetailsRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ReqResourceDetailsRootEvent_ReqResourceDetailsRoot.toString(), reqresourcedetailsrootevent_reqresourcedetailsroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqResourceDetailsRootEventMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ReqResourceDetailsRootEvent that = (excr_resourcemanagement_api.proxies.ReqResourceDetailsRootEvent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
