// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ResContainerListFetchFromOperation implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resContainerListFetchFromOperationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ResContainerListFetchFromOperation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContainerName("ContainerName"),
		Status("Status"),
		STATUSNAME("STATUSNAME"),
		ContainerId("ContainerId"),
		ProductName("ProductName"),
		Qty("Qty"),
		CurrentHoldCount("CurrentHoldCount"),
		UOMName("UOMName"),
		SpecName("SpecName"),
		SpecId("SpecId"),
		OperationName("OperationName"),
		MfgOrderName("MfgOrderName"),
		UseQueue("UseQueue"),
		HoldReasonId("HoldReasonId"),
		InProcess("InProcess"),
		ResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot("EXCR_ResourceManagement_API.ResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResContainerListFetchFromOperation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResContainerListFetchFromOperation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resContainerListFetchFromOperationMendixObject)
	{
		if (resContainerListFetchFromOperationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resContainerListFetchFromOperationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resContainerListFetchFromOperationMendixObject = resContainerListFetchFromOperationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperation(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperation.initialize(context, mendixObject);
	}

	/**
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName()
	{
		return getContainerName(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContainerName.toString());
	}

	/**
	 * Set value of ContainerName
	 * @param containername
	 */
	public final void setContainerName(java.lang.String containername)
	{
		setContainerName(getContext(), containername);
	}

	/**
	 * Set value of ContainerName
	 * @param context
	 * @param containername
	 */
	public final void setContainerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String containername)
	{
		getMendixObject().setValue(context, MemberNames.ContainerName.toString(), containername);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of STATUSNAME
	 */
	public final java.lang.String getSTATUSNAME()
	{
		return getSTATUSNAME(getContext());
	}

	/**
	 * @param context
	 * @return value of STATUSNAME
	 */
	public final java.lang.String getSTATUSNAME(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.STATUSNAME.toString());
	}

	/**
	 * Set value of STATUSNAME
	 * @param statusname
	 */
	public final void setSTATUSNAME(java.lang.String statusname)
	{
		setSTATUSNAME(getContext(), statusname);
	}

	/**
	 * Set value of STATUSNAME
	 * @param context
	 * @param statusname
	 */
	public final void setSTATUSNAME(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String statusname)
	{
		getMendixObject().setValue(context, MemberNames.STATUSNAME.toString(), statusname);
	}

	/**
	 * @return value of ContainerId
	 */
	public final java.lang.String getContainerId()
	{
		return getContainerId(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainerId
	 */
	public final java.lang.String getContainerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContainerId.toString());
	}

	/**
	 * Set value of ContainerId
	 * @param containerid
	 */
	public final void setContainerId(java.lang.String containerid)
	{
		setContainerId(getContext(), containerid);
	}

	/**
	 * Set value of ContainerId
	 * @param context
	 * @param containerid
	 */
	public final void setContainerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String containerid)
	{
		getMendixObject().setValue(context, MemberNames.ContainerId.toString(), containerid);
	}

	/**
	 * @return value of ProductName
	 */
	public final java.lang.String getProductName()
	{
		return getProductName(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductName
	 */
	public final java.lang.String getProductName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductName.toString());
	}

	/**
	 * Set value of ProductName
	 * @param productname
	 */
	public final void setProductName(java.lang.String productname)
	{
		setProductName(getContext(), productname);
	}

	/**
	 * Set value of ProductName
	 * @param context
	 * @param productname
	 */
	public final void setProductName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productname)
	{
		getMendixObject().setValue(context, MemberNames.ProductName.toString(), productname);
	}

	/**
	 * @return value of Qty
	 */
	public final java.lang.String getQty()
	{
		return getQty(getContext());
	}

	/**
	 * @param context
	 * @return value of Qty
	 */
	public final java.lang.String getQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Qty.toString());
	}

	/**
	 * Set value of Qty
	 * @param qty
	 */
	public final void setQty(java.lang.String qty)
	{
		setQty(getContext(), qty);
	}

	/**
	 * Set value of Qty
	 * @param context
	 * @param qty
	 */
	public final void setQty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String qty)
	{
		getMendixObject().setValue(context, MemberNames.Qty.toString(), qty);
	}

	/**
	 * @return value of CurrentHoldCount
	 */
	public final java.lang.String getCurrentHoldCount()
	{
		return getCurrentHoldCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentHoldCount
	 */
	public final java.lang.String getCurrentHoldCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrentHoldCount.toString());
	}

	/**
	 * Set value of CurrentHoldCount
	 * @param currentholdcount
	 */
	public final void setCurrentHoldCount(java.lang.String currentholdcount)
	{
		setCurrentHoldCount(getContext(), currentholdcount);
	}

	/**
	 * Set value of CurrentHoldCount
	 * @param context
	 * @param currentholdcount
	 */
	public final void setCurrentHoldCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currentholdcount)
	{
		getMendixObject().setValue(context, MemberNames.CurrentHoldCount.toString(), currentholdcount);
	}

	/**
	 * @return value of UOMName
	 */
	public final java.lang.String getUOMName()
	{
		return getUOMName(getContext());
	}

	/**
	 * @param context
	 * @return value of UOMName
	 */
	public final java.lang.String getUOMName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UOMName.toString());
	}

	/**
	 * Set value of UOMName
	 * @param uomname
	 */
	public final void setUOMName(java.lang.String uomname)
	{
		setUOMName(getContext(), uomname);
	}

	/**
	 * Set value of UOMName
	 * @param context
	 * @param uomname
	 */
	public final void setUOMName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uomname)
	{
		getMendixObject().setValue(context, MemberNames.UOMName.toString(), uomname);
	}

	/**
	 * @return value of SpecName
	 */
	public final java.lang.String getSpecName()
	{
		return getSpecName(getContext());
	}

	/**
	 * @param context
	 * @return value of SpecName
	 */
	public final java.lang.String getSpecName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SpecName.toString());
	}

	/**
	 * Set value of SpecName
	 * @param specname
	 */
	public final void setSpecName(java.lang.String specname)
	{
		setSpecName(getContext(), specname);
	}

	/**
	 * Set value of SpecName
	 * @param context
	 * @param specname
	 */
	public final void setSpecName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String specname)
	{
		getMendixObject().setValue(context, MemberNames.SpecName.toString(), specname);
	}

	/**
	 * @return value of SpecId
	 */
	public final java.lang.String getSpecId()
	{
		return getSpecId(getContext());
	}

	/**
	 * @param context
	 * @return value of SpecId
	 */
	public final java.lang.String getSpecId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SpecId.toString());
	}

	/**
	 * Set value of SpecId
	 * @param specid
	 */
	public final void setSpecId(java.lang.String specid)
	{
		setSpecId(getContext(), specid);
	}

	/**
	 * Set value of SpecId
	 * @param context
	 * @param specid
	 */
	public final void setSpecId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String specid)
	{
		getMendixObject().setValue(context, MemberNames.SpecId.toString(), specid);
	}

	/**
	 * @return value of OperationName
	 */
	public final java.lang.String getOperationName()
	{
		return getOperationName(getContext());
	}

	/**
	 * @param context
	 * @return value of OperationName
	 */
	public final java.lang.String getOperationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OperationName.toString());
	}

	/**
	 * Set value of OperationName
	 * @param operationname
	 */
	public final void setOperationName(java.lang.String operationname)
	{
		setOperationName(getContext(), operationname);
	}

	/**
	 * Set value of OperationName
	 * @param context
	 * @param operationname
	 */
	public final void setOperationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operationname)
	{
		getMendixObject().setValue(context, MemberNames.OperationName.toString(), operationname);
	}

	/**
	 * @return value of MfgOrderName
	 */
	public final java.lang.String getMfgOrderName()
	{
		return getMfgOrderName(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgOrderName
	 */
	public final java.lang.String getMfgOrderName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MfgOrderName.toString());
	}

	/**
	 * Set value of MfgOrderName
	 * @param mfgordername
	 */
	public final void setMfgOrderName(java.lang.String mfgordername)
	{
		setMfgOrderName(getContext(), mfgordername);
	}

	/**
	 * Set value of MfgOrderName
	 * @param context
	 * @param mfgordername
	 */
	public final void setMfgOrderName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mfgordername)
	{
		getMendixObject().setValue(context, MemberNames.MfgOrderName.toString(), mfgordername);
	}

	/**
	 * @return value of UseQueue
	 */
	public final java.lang.String getUseQueue()
	{
		return getUseQueue(getContext());
	}

	/**
	 * @param context
	 * @return value of UseQueue
	 */
	public final java.lang.String getUseQueue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseQueue.toString());
	}

	/**
	 * Set value of UseQueue
	 * @param usequeue
	 */
	public final void setUseQueue(java.lang.String usequeue)
	{
		setUseQueue(getContext(), usequeue);
	}

	/**
	 * Set value of UseQueue
	 * @param context
	 * @param usequeue
	 */
	public final void setUseQueue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usequeue)
	{
		getMendixObject().setValue(context, MemberNames.UseQueue.toString(), usequeue);
	}

	/**
	 * @return value of HoldReasonId
	 */
	public final java.lang.String getHoldReasonId()
	{
		return getHoldReasonId(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldReasonId
	 */
	public final java.lang.String getHoldReasonId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldReasonId.toString());
	}

	/**
	 * Set value of HoldReasonId
	 * @param holdreasonid
	 */
	public final void setHoldReasonId(java.lang.String holdreasonid)
	{
		setHoldReasonId(getContext(), holdreasonid);
	}

	/**
	 * Set value of HoldReasonId
	 * @param context
	 * @param holdreasonid
	 */
	public final void setHoldReasonId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdreasonid)
	{
		getMendixObject().setValue(context, MemberNames.HoldReasonId.toString(), holdreasonid);
	}

	/**
	 * @return value of InProcess
	 */
	public final java.lang.String getInProcess()
	{
		return getInProcess(getContext());
	}

	/**
	 * @param context
	 * @return value of InProcess
	 */
	public final java.lang.String getInProcess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InProcess.toString());
	}

	/**
	 * Set value of InProcess
	 * @param inprocess
	 */
	public final void setInProcess(java.lang.String inprocess)
	{
		setInProcess(getContext(), inprocess);
	}

	/**
	 * Set value of InProcess
	 * @param context
	 * @param inprocess
	 */
	public final void setInProcess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String inprocess)
	{
		getMendixObject().setValue(context, MemberNames.InProcess.toString(), inprocess);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot
	 */
	public final excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperationRoot getResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot() throws com.mendix.core.CoreException
	{
		return getResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperationRoot getResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperationRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperationRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot
	 * @param rescontainerlistfetchfromoperation_rescontainerlistfetchfromoperationroot
	 */
	public final void setResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot(excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperationRoot rescontainerlistfetchfromoperation_rescontainerlistfetchfromoperationroot)
	{
		setResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot(getContext(), rescontainerlistfetchfromoperation_rescontainerlistfetchfromoperationroot);
	}

	/**
	 * Set value of ResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot
	 * @param context
	 * @param rescontainerlistfetchfromoperation_rescontainerlistfetchfromoperationroot
	 */
	public final void setResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperationRoot rescontainerlistfetchfromoperation_rescontainerlistfetchfromoperationroot)
	{
		if (rescontainerlistfetchfromoperation_rescontainerlistfetchfromoperationroot == null) {
			getMendixObject().setValue(context, MemberNames.ResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResContainerListFetchFromOperation_ResContainerListFetchFromOperationRoot.toString(), rescontainerlistfetchfromoperation_rescontainerlistfetchfromoperationroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resContainerListFetchFromOperationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperation that = (excr_resourcemanagement_api.proxies.ResContainerListFetchFromOperation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
