// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ResEmployeeLayoutImageRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resEmployeeLayoutImageRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ResEmployeeLayoutImageRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SessionValues_ResEmployeeLayoutImageRoot("EXCR_ResourceManagement_API.SessionValues_ResEmployeeLayoutImageRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResEmployeeLayoutImageRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResEmployeeLayoutImageRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resEmployeeLayoutImageRootMendixObject)
	{
		if (resEmployeeLayoutImageRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resEmployeeLayoutImageRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resEmployeeLayoutImageRootMendixObject = resEmployeeLayoutImageRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ResEmployeeLayoutImageRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ResEmployeeLayoutImageRoot(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ResEmployeeLayoutImageRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ResEmployeeLayoutImageRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SessionValues_ResEmployeeLayoutImageRoot
	 */
	public final excr_resourcemanagement_api.proxies.SessionValues getSessionValues_ResEmployeeLayoutImageRoot() throws com.mendix.core.CoreException
	{
		return getSessionValues_ResEmployeeLayoutImageRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of SessionValues_ResEmployeeLayoutImageRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.SessionValues getSessionValues_ResEmployeeLayoutImageRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.SessionValues result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SessionValues_ResEmployeeLayoutImageRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.SessionValues.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SessionValues_ResEmployeeLayoutImageRoot
	 * @param sessionvalues_resemployeelayoutimageroot
	 */
	public final void setSessionValues_ResEmployeeLayoutImageRoot(excr_resourcemanagement_api.proxies.SessionValues sessionvalues_resemployeelayoutimageroot)
	{
		setSessionValues_ResEmployeeLayoutImageRoot(getContext(), sessionvalues_resemployeelayoutimageroot);
	}

	/**
	 * Set value of SessionValues_ResEmployeeLayoutImageRoot
	 * @param context
	 * @param sessionvalues_resemployeelayoutimageroot
	 */
	public final void setSessionValues_ResEmployeeLayoutImageRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.SessionValues sessionvalues_resemployeelayoutimageroot)
	{
		if (sessionvalues_resemployeelayoutimageroot == null) {
			getMendixObject().setValue(context, MemberNames.SessionValues_ResEmployeeLayoutImageRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SessionValues_ResEmployeeLayoutImageRoot.toString(), sessionvalues_resemployeelayoutimageroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resEmployeeLayoutImageRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ResEmployeeLayoutImageRoot that = (excr_resourcemanagement_api.proxies.ResEmployeeLayoutImageRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
