// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ResMarkerCount implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resMarkerCountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ResMarkerCount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MarkerCount("MarkerCount"),
		ResMarkerCount_ResMarkerCountRoot("EXCR_ResourceManagement_API.ResMarkerCount_ResMarkerCountRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResMarkerCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResMarkerCount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resMarkerCountMendixObject)
	{
		if (resMarkerCountMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resMarkerCountMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resMarkerCountMendixObject = resMarkerCountMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ResMarkerCount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ResMarkerCount(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ResMarkerCount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ResMarkerCount.initialize(context, mendixObject);
	}

	/**
	 * @return value of MarkerCount
	 */
	public final java.lang.String getMarkerCount()
	{
		return getMarkerCount(getContext());
	}

	/**
	 * @param context
	 * @return value of MarkerCount
	 */
	public final java.lang.String getMarkerCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MarkerCount.toString());
	}

	/**
	 * Set value of MarkerCount
	 * @param markercount
	 */
	public final void setMarkerCount(java.lang.String markercount)
	{
		setMarkerCount(getContext(), markercount);
	}

	/**
	 * Set value of MarkerCount
	 * @param context
	 * @param markercount
	 */
	public final void setMarkerCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String markercount)
	{
		getMendixObject().setValue(context, MemberNames.MarkerCount.toString(), markercount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResMarkerCount_ResMarkerCountRoot
	 */
	public final excr_resourcemanagement_api.proxies.ResMarkerCountRoot getResMarkerCount_ResMarkerCountRoot() throws com.mendix.core.CoreException
	{
		return getResMarkerCount_ResMarkerCountRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResMarkerCount_ResMarkerCountRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResMarkerCountRoot getResMarkerCount_ResMarkerCountRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResMarkerCountRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResMarkerCount_ResMarkerCountRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResMarkerCountRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResMarkerCount_ResMarkerCountRoot
	 * @param resmarkercount_resmarkercountroot
	 */
	public final void setResMarkerCount_ResMarkerCountRoot(excr_resourcemanagement_api.proxies.ResMarkerCountRoot resmarkercount_resmarkercountroot)
	{
		setResMarkerCount_ResMarkerCountRoot(getContext(), resmarkercount_resmarkercountroot);
	}

	/**
	 * Set value of ResMarkerCount_ResMarkerCountRoot
	 * @param context
	 * @param resmarkercount_resmarkercountroot
	 */
	public final void setResMarkerCount_ResMarkerCountRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResMarkerCountRoot resmarkercount_resmarkercountroot)
	{
		if (resmarkercount_resmarkercountroot == null) {
			getMendixObject().setValue(context, MemberNames.ResMarkerCount_ResMarkerCountRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResMarkerCount_ResMarkerCountRoot.toString(), resmarkercount_resmarkercountroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resMarkerCountMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ResMarkerCount that = (excr_resourcemanagement_api.proxies.ResMarkerCount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
