// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ResourceSetupAvailabilityRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resourceSetupAvailabilityRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ResourceSetupAvailabilityRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_context("_odata_context"),
		ResourceSetupAvailability("ResourceSetupAvailability");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResourceSetupAvailabilityRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResourceSetupAvailabilityRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourceSetupAvailabilityRootMendixObject)
	{
		if (resourceSetupAvailabilityRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resourceSetupAvailabilityRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resourceSetupAvailabilityRootMendixObject = resourceSetupAvailabilityRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ResourceSetupAvailabilityRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ResourceSetupAvailabilityRoot(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ResourceSetupAvailabilityRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ResourceSetupAvailabilityRoot.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context()
	{
		return get_odata_context(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_context.toString());
	}

	/**
	 * Set value of _odata_context
	 * @param _odata_context
	 */
	public final void set_odata_context(java.lang.String _odata_context)
	{
		set_odata_context(getContext(), _odata_context);
	}

	/**
	 * Set value of _odata_context
	 * @param context
	 * @param _odata_context
	 */
	public final void set_odata_context(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_context)
	{
		getMendixObject().setValue(context, MemberNames._odata_context.toString(), _odata_context);
	}

	/**
	 * @return value of ResourceSetupAvailability
	 */
	public final java.lang.Integer getResourceSetupAvailability()
	{
		return getResourceSetupAvailability(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceSetupAvailability
	 */
	public final java.lang.Integer getResourceSetupAvailability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ResourceSetupAvailability.toString());
	}

	/**
	 * Set value of ResourceSetupAvailability
	 * @param resourcesetupavailability
	 */
	public final void setResourceSetupAvailability(java.lang.Integer resourcesetupavailability)
	{
		setResourceSetupAvailability(getContext(), resourcesetupavailability);
	}

	/**
	 * Set value of ResourceSetupAvailability
	 * @param context
	 * @param resourcesetupavailability
	 */
	public final void setResourceSetupAvailability(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer resourcesetupavailability)
	{
		getMendixObject().setValue(context, MemberNames.ResourceSetupAvailability.toString(), resourcesetupavailability);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resourceSetupAvailabilityRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ResourceSetupAvailabilityRoot that = (excr_resourcemanagement_api.proxies.ResourceSetupAvailabilityRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
