// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ResResourceLayoutDetail implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resResourceLayoutDetailMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ResResourceLayoutDetail";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		XLocation("XLocation"),
		YLocation("YLocation"),
		Name("Name"),
		MarkerType("MarkerType"),
		ResResourceLayoutDetail_ResResourceLayoutDetailsRoot("EXCR_ResourceManagement_API.ResResourceLayoutDetail_ResResourceLayoutDetailsRoot"),
		ResResourceLayoutDetailResource_ResResourceLayoutDetail("EXCR_ResourceManagement_API.ResResourceLayoutDetailResource_ResResourceLayoutDetail"),
		ResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail("EXCR_ResourceManagement_API.ResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail"),
		ResResourceLayoutDetailOperation_ResResourceLayoutDetail("EXCR_ResourceManagement_API.ResResourceLayoutDetailOperation_ResResourceLayoutDetail"),
		ResResourceLayoutDetailSpec_ResResourceLayoutDetail("EXCR_ResourceManagement_API.ResResourceLayoutDetailSpec_ResResourceLayoutDetail"),
		ResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail("EXCR_ResourceManagement_API.ResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail"),
		ResourcePin_ResResourceLayoutDetail("EXCR_ResourceManagement.ResourcePin_ResResourceLayoutDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resResourceLayoutDetailMendixObject)
	{
		if (resResourceLayoutDetailMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resResourceLayoutDetailMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resResourceLayoutDetailMendixObject = resResourceLayoutDetailMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ResResourceLayoutDetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ResResourceLayoutDetail(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ResResourceLayoutDetail load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ResResourceLayoutDetail.initialize(context, mendixObject);
	}

	/**
	 * @return value of XLocation
	 */
	public final java.math.BigDecimal getXLocation()
	{
		return getXLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of XLocation
	 */
	public final java.math.BigDecimal getXLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.XLocation.toString());
	}

	/**
	 * Set value of XLocation
	 * @param xlocation
	 */
	public final void setXLocation(java.math.BigDecimal xlocation)
	{
		setXLocation(getContext(), xlocation);
	}

	/**
	 * Set value of XLocation
	 * @param context
	 * @param xlocation
	 */
	public final void setXLocation(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal xlocation)
	{
		getMendixObject().setValue(context, MemberNames.XLocation.toString(), xlocation);
	}

	/**
	 * @return value of YLocation
	 */
	public final java.math.BigDecimal getYLocation()
	{
		return getYLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of YLocation
	 */
	public final java.math.BigDecimal getYLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.YLocation.toString());
	}

	/**
	 * Set value of YLocation
	 * @param ylocation
	 */
	public final void setYLocation(java.math.BigDecimal ylocation)
	{
		setYLocation(getContext(), ylocation);
	}

	/**
	 * Set value of YLocation
	 * @param context
	 * @param ylocation
	 */
	public final void setYLocation(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ylocation)
	{
		getMendixObject().setValue(context, MemberNames.YLocation.toString(), ylocation);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of MarkerType
	 */
	public final java.lang.String getMarkerType()
	{
		return getMarkerType(getContext());
	}

	/**
	 * @param context
	 * @return value of MarkerType
	 */
	public final java.lang.String getMarkerType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MarkerType.toString());
	}

	/**
	 * Set value of MarkerType
	 * @param markertype
	 */
	public final void setMarkerType(java.lang.String markertype)
	{
		setMarkerType(getContext(), markertype);
	}

	/**
	 * Set value of MarkerType
	 * @param context
	 * @param markertype
	 */
	public final void setMarkerType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String markertype)
	{
		getMendixObject().setValue(context, MemberNames.MarkerType.toString(), markertype);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResResourceLayoutDetail_ResResourceLayoutDetailsRoot
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailsRoot getResResourceLayoutDetail_ResResourceLayoutDetailsRoot() throws com.mendix.core.CoreException
	{
		return getResResourceLayoutDetail_ResResourceLayoutDetailsRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResResourceLayoutDetail_ResResourceLayoutDetailsRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailsRoot getResResourceLayoutDetail_ResResourceLayoutDetailsRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResResourceLayoutDetailsRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResResourceLayoutDetail_ResResourceLayoutDetailsRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResResourceLayoutDetailsRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResResourceLayoutDetail_ResResourceLayoutDetailsRoot
	 * @param resresourcelayoutdetail_resresourcelayoutdetailsroot
	 */
	public final void setResResourceLayoutDetail_ResResourceLayoutDetailsRoot(excr_resourcemanagement_api.proxies.ResResourceLayoutDetailsRoot resresourcelayoutdetail_resresourcelayoutdetailsroot)
	{
		setResResourceLayoutDetail_ResResourceLayoutDetailsRoot(getContext(), resresourcelayoutdetail_resresourcelayoutdetailsroot);
	}

	/**
	 * Set value of ResResourceLayoutDetail_ResResourceLayoutDetailsRoot
	 * @param context
	 * @param resresourcelayoutdetail_resresourcelayoutdetailsroot
	 */
	public final void setResResourceLayoutDetail_ResResourceLayoutDetailsRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResResourceLayoutDetailsRoot resresourcelayoutdetail_resresourcelayoutdetailsroot)
	{
		if (resresourcelayoutdetail_resresourcelayoutdetailsroot == null) {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetail_ResResourceLayoutDetailsRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetail_ResResourceLayoutDetailsRoot.toString(), resresourcelayoutdetail_resresourcelayoutdetailsroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResResourceLayoutDetailResource_ResResourceLayoutDetail
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailResource getResResourceLayoutDetailResource_ResResourceLayoutDetail() throws com.mendix.core.CoreException
	{
		return getResResourceLayoutDetailResource_ResResourceLayoutDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ResResourceLayoutDetailResource_ResResourceLayoutDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailResource getResResourceLayoutDetailResource_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResResourceLayoutDetailResource result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResResourceLayoutDetailResource_ResResourceLayoutDetail.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResResourceLayoutDetailResource.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResResourceLayoutDetailResource_ResResourceLayoutDetail
	 * @param resresourcelayoutdetailresource_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailResource_ResResourceLayoutDetail(excr_resourcemanagement_api.proxies.ResResourceLayoutDetailResource resresourcelayoutdetailresource_resresourcelayoutdetail)
	{
		setResResourceLayoutDetailResource_ResResourceLayoutDetail(getContext(), resresourcelayoutdetailresource_resresourcelayoutdetail);
	}

	/**
	 * Set value of ResResourceLayoutDetailResource_ResResourceLayoutDetail
	 * @param context
	 * @param resresourcelayoutdetailresource_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailResource_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResResourceLayoutDetailResource resresourcelayoutdetailresource_resresourcelayoutdetail)
	{
		if (resresourcelayoutdetailresource_resresourcelayoutdetail == null) {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailResource_ResResourceLayoutDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailResource_ResResourceLayoutDetail.toString(), resresourcelayoutdetailresource_resresourcelayoutdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailLinkedLayout getResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail() throws com.mendix.core.CoreException
	{
		return getResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailLinkedLayout getResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResResourceLayoutDetailLinkedLayout result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResResourceLayoutDetailLinkedLayout.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail
	 * @param resresourcelayoutdetaillinkedlayout_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail(excr_resourcemanagement_api.proxies.ResResourceLayoutDetailLinkedLayout resresourcelayoutdetaillinkedlayout_resresourcelayoutdetail)
	{
		setResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail(getContext(), resresourcelayoutdetaillinkedlayout_resresourcelayoutdetail);
	}

	/**
	 * Set value of ResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail
	 * @param context
	 * @param resresourcelayoutdetaillinkedlayout_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResResourceLayoutDetailLinkedLayout resresourcelayoutdetaillinkedlayout_resresourcelayoutdetail)
	{
		if (resresourcelayoutdetaillinkedlayout_resresourcelayoutdetail == null) {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailLinkedLayout_ResResourceLayoutDetail.toString(), resresourcelayoutdetaillinkedlayout_resresourcelayoutdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResResourceLayoutDetailOperation_ResResourceLayoutDetail
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailOperation getResResourceLayoutDetailOperation_ResResourceLayoutDetail() throws com.mendix.core.CoreException
	{
		return getResResourceLayoutDetailOperation_ResResourceLayoutDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ResResourceLayoutDetailOperation_ResResourceLayoutDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailOperation getResResourceLayoutDetailOperation_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResResourceLayoutDetailOperation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResResourceLayoutDetailOperation_ResResourceLayoutDetail.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResResourceLayoutDetailOperation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResResourceLayoutDetailOperation_ResResourceLayoutDetail
	 * @param resresourcelayoutdetailoperation_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailOperation_ResResourceLayoutDetail(excr_resourcemanagement_api.proxies.ResResourceLayoutDetailOperation resresourcelayoutdetailoperation_resresourcelayoutdetail)
	{
		setResResourceLayoutDetailOperation_ResResourceLayoutDetail(getContext(), resresourcelayoutdetailoperation_resresourcelayoutdetail);
	}

	/**
	 * Set value of ResResourceLayoutDetailOperation_ResResourceLayoutDetail
	 * @param context
	 * @param resresourcelayoutdetailoperation_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailOperation_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResResourceLayoutDetailOperation resresourcelayoutdetailoperation_resresourcelayoutdetail)
	{
		if (resresourcelayoutdetailoperation_resresourcelayoutdetail == null) {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailOperation_ResResourceLayoutDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailOperation_ResResourceLayoutDetail.toString(), resresourcelayoutdetailoperation_resresourcelayoutdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResResourceLayoutDetailSpec_ResResourceLayoutDetail
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailSpec getResResourceLayoutDetailSpec_ResResourceLayoutDetail() throws com.mendix.core.CoreException
	{
		return getResResourceLayoutDetailSpec_ResResourceLayoutDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ResResourceLayoutDetailSpec_ResResourceLayoutDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailSpec getResResourceLayoutDetailSpec_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResResourceLayoutDetailSpec result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResResourceLayoutDetailSpec_ResResourceLayoutDetail.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResResourceLayoutDetailSpec.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResResourceLayoutDetailSpec_ResResourceLayoutDetail
	 * @param resresourcelayoutdetailspec_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailSpec_ResResourceLayoutDetail(excr_resourcemanagement_api.proxies.ResResourceLayoutDetailSpec resresourcelayoutdetailspec_resresourcelayoutdetail)
	{
		setResResourceLayoutDetailSpec_ResResourceLayoutDetail(getContext(), resresourcelayoutdetailspec_resresourcelayoutdetail);
	}

	/**
	 * Set value of ResResourceLayoutDetailSpec_ResResourceLayoutDetail
	 * @param context
	 * @param resresourcelayoutdetailspec_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailSpec_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResResourceLayoutDetailSpec resresourcelayoutdetailspec_resresourcelayoutdetail)
	{
		if (resresourcelayoutdetailspec_resresourcelayoutdetail == null) {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailSpec_ResResourceLayoutDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailSpec_ResResourceLayoutDetail.toString(), resresourcelayoutdetailspec_resresourcelayoutdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailWorkCenter getResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail() throws com.mendix.core.CoreException
	{
		return getResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResResourceLayoutDetailWorkCenter getResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResResourceLayoutDetailWorkCenter result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResResourceLayoutDetailWorkCenter.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail
	 * @param resresourcelayoutdetailworkcenter_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail(excr_resourcemanagement_api.proxies.ResResourceLayoutDetailWorkCenter resresourcelayoutdetailworkcenter_resresourcelayoutdetail)
	{
		setResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail(getContext(), resresourcelayoutdetailworkcenter_resresourcelayoutdetail);
	}

	/**
	 * Set value of ResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail
	 * @param context
	 * @param resresourcelayoutdetailworkcenter_resresourcelayoutdetail
	 */
	public final void setResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResResourceLayoutDetailWorkCenter resresourcelayoutdetailworkcenter_resresourcelayoutdetail)
	{
		if (resresourcelayoutdetailworkcenter_resresourcelayoutdetail == null) {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResResourceLayoutDetailWorkCenter_ResResourceLayoutDetail.toString(), resresourcelayoutdetailworkcenter_resresourcelayoutdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResourcePin_ResResourceLayoutDetail
	 */
	public final excr_resourcemanagement.proxies.ResourcePin getResourcePin_ResResourceLayoutDetail() throws com.mendix.core.CoreException
	{
		return getResourcePin_ResResourceLayoutDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourcePin_ResResourceLayoutDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ResourcePin getResourcePin_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ResourcePin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResourcePin_ResResourceLayoutDetail.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ResourcePin.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResourcePin_ResResourceLayoutDetail
	 * @param resourcepin_resresourcelayoutdetail
	 */
	public final void setResourcePin_ResResourceLayoutDetail(excr_resourcemanagement.proxies.ResourcePin resourcepin_resresourcelayoutdetail)
	{
		setResourcePin_ResResourceLayoutDetail(getContext(), resourcepin_resresourcelayoutdetail);
	}

	/**
	 * Set value of ResourcePin_ResResourceLayoutDetail
	 * @param context
	 * @param resourcepin_resresourcelayoutdetail
	 */
	public final void setResourcePin_ResResourceLayoutDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ResourcePin resourcepin_resresourcelayoutdetail)
	{
		if (resourcepin_resresourcelayoutdetail == null) {
			getMendixObject().setValue(context, MemberNames.ResourcePin_ResResourceLayoutDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResourcePin_ResResourceLayoutDetail.toString(), resourcepin_resresourcelayoutdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resResourceLayoutDetailMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ResResourceLayoutDetail that = (excr_resourcemanagement_api.proxies.ResResourceLayoutDetail) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
