// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_resourcemanagement_api.proxies;

public class ResSpec implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resSpecMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_ResourceManagement_API.ResSpec";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ResSpec_ResSpecsListRoot("EXCR_ResourceManagement_API.ResSpec_ResSpecsListRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResSpec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResSpec(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resSpecMendixObject)
	{
		if (resSpecMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!resSpecMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.resSpecMendixObject = resSpecMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_resourcemanagement_api.proxies.ResSpec initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_resourcemanagement_api.proxies.ResSpec(context, mendixObject);
	}

	public static excr_resourcemanagement_api.proxies.ResSpec load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_resourcemanagement_api.proxies.ResSpec.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResSpec_ResSpecsListRoot
	 */
	public final excr_resourcemanagement_api.proxies.ResSpecsListRoot getResSpec_ResSpecsListRoot() throws com.mendix.core.CoreException
	{
		return getResSpec_ResSpecsListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ResSpec_ResSpecsListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement_api.proxies.ResSpecsListRoot getResSpec_ResSpecsListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement_api.proxies.ResSpecsListRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResSpec_ResSpecsListRoot.toString());
		if (identifier != null) {
			result = excr_resourcemanagement_api.proxies.ResSpecsListRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResSpec_ResSpecsListRoot
	 * @param resspec_resspecslistroot
	 */
	public final void setResSpec_ResSpecsListRoot(excr_resourcemanagement_api.proxies.ResSpecsListRoot resspec_resspecslistroot)
	{
		setResSpec_ResSpecsListRoot(getContext(), resspec_resspecslistroot);
	}

	/**
	 * Set value of ResSpec_ResSpecsListRoot
	 * @param context
	 * @param resspec_resspecslistroot
	 */
	public final void setResSpec_ResSpecsListRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement_api.proxies.ResSpecsListRoot resspec_resspecslistroot)
	{
		if (resspec_resspecslistroot == null) {
			getMendixObject().setValue(context, MemberNames.ResSpec_ResSpecsListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResSpec_ResSpecsListRoot.toString(), resspec_resspecslistroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resSpecMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_resourcemanagement_api.proxies.ResSpec that = (excr_resourcemanagement_api.proxies.ResSpec) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
