// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_inlinespc_api.proxies;

public class APIResSPCSetup implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aPIResSPCSetupMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_InlineSPC_API.APIResSPCSetup";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		InstanceId("InstanceId"),
		APIResSPCSetup_APIResSPCTxnData("EXCR_InlineSPC_API.APIResSPCSetup_APIResSPCTxnData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public APIResSPCSetup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected APIResSPCSetup(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPIResSPCSetupMendixObject)
	{
		if (aPIResSPCSetupMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!aPIResSPCSetupMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aPIResSPCSetupMendixObject = aPIResSPCSetupMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_inlinespc_api.proxies.APIResSPCSetup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_inlinespc_api.proxies.APIResSPCSetup(context, mendixObject);
	}

	public static excr_inlinespc_api.proxies.APIResSPCSetup load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_inlinespc_api.proxies.APIResSPCSetup.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIResSPCSetup_APIResSPCTxnData
	 */
	public final excr_inlinespc_api.proxies.APIResSPCTxnData getAPIResSPCSetup_APIResSPCTxnData() throws com.mendix.core.CoreException
	{
		return getAPIResSPCSetup_APIResSPCTxnData(getContext());
	}

	/**
	 * @param context
	 * @return value of APIResSPCSetup_APIResSPCTxnData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc_api.proxies.APIResSPCTxnData getAPIResSPCSetup_APIResSPCTxnData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc_api.proxies.APIResSPCTxnData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIResSPCSetup_APIResSPCTxnData.toString());
		if (identifier != null) {
			result = excr_inlinespc_api.proxies.APIResSPCTxnData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIResSPCSetup_APIResSPCTxnData
	 * @param apiresspcsetup_apiresspctxndata
	 */
	public final void setAPIResSPCSetup_APIResSPCTxnData(excr_inlinespc_api.proxies.APIResSPCTxnData apiresspcsetup_apiresspctxndata)
	{
		setAPIResSPCSetup_APIResSPCTxnData(getContext(), apiresspcsetup_apiresspctxndata);
	}

	/**
	 * Set value of APIResSPCSetup_APIResSPCTxnData
	 * @param context
	 * @param apiresspcsetup_apiresspctxndata
	 */
	public final void setAPIResSPCSetup_APIResSPCTxnData(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc_api.proxies.APIResSPCTxnData apiresspcsetup_apiresspctxndata)
	{
		if (apiresspcsetup_apiresspctxndata == null) {
			getMendixObject().setValue(context, MemberNames.APIResSPCSetup_APIResSPCTxnData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIResSPCSetup_APIResSPCTxnData.toString(), apiresspcsetup_apiresspctxndata.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aPIResSPCSetupMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_inlinespc_api.proxies.APIResSPCSetup that = (excr_inlinespc_api.proxies.APIResSPCSetup) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
