// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_inlinespc_api.proxies;

public class APIResSPCTxnData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aPIResSPCTxnDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_InlineSPC_API.APIResSPCTxnData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		InstanceId("InstanceId"),
		SPCResult("SPCResult"),
		SPCResultFilename("SPCResultFilename"),
		ChartHeight("ChartHeight"),
		ChartWidth("ChartWidth"),
		SPCFailureAction("SPCFailureAction"),
		htmlContent("htmlContent"),
		serverURL("serverURL"),
		APIResSPCTxnData_APIResSPCRoot("EXCR_InlineSPC_API.APIResSPCTxnData_APIResSPCRoot"),
		APIResSPCSetup_APIResSPCTxnData("EXCR_InlineSPC_API.APIResSPCSetup_APIResSPCTxnData"),
		APIResSPCTxnData_APIresShopfloorTxn("EXCR_InlineSPC_API.APIResSPCTxnData_APIresShopfloorTxn");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public APIResSPCTxnData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected APIResSPCTxnData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPIResSPCTxnDataMendixObject)
	{
		if (aPIResSPCTxnDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!aPIResSPCTxnDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aPIResSPCTxnDataMendixObject = aPIResSPCTxnDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_inlinespc_api.proxies.APIResSPCTxnData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_inlinespc_api.proxies.APIResSPCTxnData(context, mendixObject);
	}

	public static excr_inlinespc_api.proxies.APIResSPCTxnData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_inlinespc_api.proxies.APIResSPCTxnData.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId()
	{
		return getInstanceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceId
	 */
	public final java.lang.String getInstanceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceId.toString());
	}

	/**
	 * Set value of InstanceId
	 * @param instanceid
	 */
	public final void setInstanceId(java.lang.String instanceid)
	{
		setInstanceId(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceId
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceId.toString(), instanceid);
	}

	/**
	 * @return value of SPCResult
	 */
	public final java.lang.String getSPCResult()
	{
		return getSPCResult(getContext());
	}

	/**
	 * @param context
	 * @return value of SPCResult
	 */
	public final java.lang.String getSPCResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SPCResult.toString());
	}

	/**
	 * Set value of SPCResult
	 * @param spcresult
	 */
	public final void setSPCResult(java.lang.String spcresult)
	{
		setSPCResult(getContext(), spcresult);
	}

	/**
	 * Set value of SPCResult
	 * @param context
	 * @param spcresult
	 */
	public final void setSPCResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String spcresult)
	{
		getMendixObject().setValue(context, MemberNames.SPCResult.toString(), spcresult);
	}

	/**
	 * @return value of SPCResultFilename
	 */
	public final java.lang.String getSPCResultFilename()
	{
		return getSPCResultFilename(getContext());
	}

	/**
	 * @param context
	 * @return value of SPCResultFilename
	 */
	public final java.lang.String getSPCResultFilename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SPCResultFilename.toString());
	}

	/**
	 * Set value of SPCResultFilename
	 * @param spcresultfilename
	 */
	public final void setSPCResultFilename(java.lang.String spcresultfilename)
	{
		setSPCResultFilename(getContext(), spcresultfilename);
	}

	/**
	 * Set value of SPCResultFilename
	 * @param context
	 * @param spcresultfilename
	 */
	public final void setSPCResultFilename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String spcresultfilename)
	{
		getMendixObject().setValue(context, MemberNames.SPCResultFilename.toString(), spcresultfilename);
	}

	/**
	 * @return value of ChartHeight
	 */
	public final java.lang.String getChartHeight()
	{
		return getChartHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartHeight
	 */
	public final java.lang.String getChartHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ChartHeight.toString());
	}

	/**
	 * Set value of ChartHeight
	 * @param chartheight
	 */
	public final void setChartHeight(java.lang.String chartheight)
	{
		setChartHeight(getContext(), chartheight);
	}

	/**
	 * Set value of ChartHeight
	 * @param context
	 * @param chartheight
	 */
	public final void setChartHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String chartheight)
	{
		getMendixObject().setValue(context, MemberNames.ChartHeight.toString(), chartheight);
	}

	/**
	 * @return value of ChartWidth
	 */
	public final java.lang.String getChartWidth()
	{
		return getChartWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartWidth
	 */
	public final java.lang.String getChartWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ChartWidth.toString());
	}

	/**
	 * Set value of ChartWidth
	 * @param chartwidth
	 */
	public final void setChartWidth(java.lang.String chartwidth)
	{
		setChartWidth(getContext(), chartwidth);
	}

	/**
	 * Set value of ChartWidth
	 * @param context
	 * @param chartwidth
	 */
	public final void setChartWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String chartwidth)
	{
		getMendixObject().setValue(context, MemberNames.ChartWidth.toString(), chartwidth);
	}

	/**
	 * @return value of SPCFailureAction
	 */
	public final java.lang.String getSPCFailureAction()
	{
		return getSPCFailureAction(getContext());
	}

	/**
	 * @param context
	 * @return value of SPCFailureAction
	 */
	public final java.lang.String getSPCFailureAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SPCFailureAction.toString());
	}

	/**
	 * Set value of SPCFailureAction
	 * @param spcfailureaction
	 */
	public final void setSPCFailureAction(java.lang.String spcfailureaction)
	{
		setSPCFailureAction(getContext(), spcfailureaction);
	}

	/**
	 * Set value of SPCFailureAction
	 * @param context
	 * @param spcfailureaction
	 */
	public final void setSPCFailureAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String spcfailureaction)
	{
		getMendixObject().setValue(context, MemberNames.SPCFailureAction.toString(), spcfailureaction);
	}

	/**
	 * @return value of htmlContent
	 */
	public final java.lang.String gethtmlContent()
	{
		return gethtmlContent(getContext());
	}

	/**
	 * @param context
	 * @return value of htmlContent
	 */
	public final java.lang.String gethtmlContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.htmlContent.toString());
	}

	/**
	 * Set value of htmlContent
	 * @param htmlcontent
	 */
	public final void sethtmlContent(java.lang.String htmlcontent)
	{
		sethtmlContent(getContext(), htmlcontent);
	}

	/**
	 * Set value of htmlContent
	 * @param context
	 * @param htmlcontent
	 */
	public final void sethtmlContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String htmlcontent)
	{
		getMendixObject().setValue(context, MemberNames.htmlContent.toString(), htmlcontent);
	}

	/**
	 * @return value of serverURL
	 */
	public final java.lang.String getserverURL()
	{
		return getserverURL(getContext());
	}

	/**
	 * @param context
	 * @return value of serverURL
	 */
	public final java.lang.String getserverURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.serverURL.toString());
	}

	/**
	 * Set value of serverURL
	 * @param serverurl
	 */
	public final void setserverURL(java.lang.String serverurl)
	{
		setserverURL(getContext(), serverurl);
	}

	/**
	 * Set value of serverURL
	 * @param context
	 * @param serverurl
	 */
	public final void setserverURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serverurl)
	{
		getMendixObject().setValue(context, MemberNames.serverURL.toString(), serverurl);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIResSPCTxnData_APIResSPCRoot
	 */
	public final excr_inlinespc_api.proxies.APIResSPCRoot getAPIResSPCTxnData_APIResSPCRoot() throws com.mendix.core.CoreException
	{
		return getAPIResSPCTxnData_APIResSPCRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of APIResSPCTxnData_APIResSPCRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc_api.proxies.APIResSPCRoot getAPIResSPCTxnData_APIResSPCRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc_api.proxies.APIResSPCRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIResSPCTxnData_APIResSPCRoot.toString());
		if (identifier != null) {
			result = excr_inlinespc_api.proxies.APIResSPCRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIResSPCTxnData_APIResSPCRoot
	 * @param apiresspctxndata_apiresspcroot
	 */
	public final void setAPIResSPCTxnData_APIResSPCRoot(excr_inlinespc_api.proxies.APIResSPCRoot apiresspctxndata_apiresspcroot)
	{
		setAPIResSPCTxnData_APIResSPCRoot(getContext(), apiresspctxndata_apiresspcroot);
	}

	/**
	 * Set value of APIResSPCTxnData_APIResSPCRoot
	 * @param context
	 * @param apiresspctxndata_apiresspcroot
	 */
	public final void setAPIResSPCTxnData_APIResSPCRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc_api.proxies.APIResSPCRoot apiresspctxndata_apiresspcroot)
	{
		if (apiresspctxndata_apiresspcroot == null) {
			getMendixObject().setValue(context, MemberNames.APIResSPCTxnData_APIResSPCRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIResSPCTxnData_APIResSPCRoot.toString(), apiresspctxndata_apiresspcroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIResSPCSetup_APIResSPCTxnData
	 */
	public final excr_inlinespc_api.proxies.APIResSPCSetup getAPIResSPCSetup_APIResSPCTxnData() throws com.mendix.core.CoreException
	{
		return getAPIResSPCSetup_APIResSPCTxnData(getContext());
	}

	/**
	 * @param context
	 * @return value of APIResSPCSetup_APIResSPCTxnData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc_api.proxies.APIResSPCSetup getAPIResSPCSetup_APIResSPCTxnData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc_api.proxies.APIResSPCSetup result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIResSPCSetup_APIResSPCTxnData.toString());
		if (identifier != null) {
			result = excr_inlinespc_api.proxies.APIResSPCSetup.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIResSPCSetup_APIResSPCTxnData
	 * @param apiresspcsetup_apiresspctxndata
	 */
	public final void setAPIResSPCSetup_APIResSPCTxnData(excr_inlinespc_api.proxies.APIResSPCSetup apiresspcsetup_apiresspctxndata)
	{
		setAPIResSPCSetup_APIResSPCTxnData(getContext(), apiresspcsetup_apiresspctxndata);
	}

	/**
	 * Set value of APIResSPCSetup_APIResSPCTxnData
	 * @param context
	 * @param apiresspcsetup_apiresspctxndata
	 */
	public final void setAPIResSPCSetup_APIResSPCTxnData(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc_api.proxies.APIResSPCSetup apiresspcsetup_apiresspctxndata)
	{
		if (apiresspcsetup_apiresspctxndata == null) {
			getMendixObject().setValue(context, MemberNames.APIResSPCSetup_APIResSPCTxnData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIResSPCSetup_APIResSPCTxnData.toString(), apiresspcsetup_apiresspctxndata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIResSPCTxnData_APIresShopfloorTxn
	 */
	public final excr_inlinespc_api.proxies.APIresShopfloorTxn getAPIResSPCTxnData_APIresShopfloorTxn() throws com.mendix.core.CoreException
	{
		return getAPIResSPCTxnData_APIresShopfloorTxn(getContext());
	}

	/**
	 * @param context
	 * @return value of APIResSPCTxnData_APIresShopfloorTxn
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc_api.proxies.APIresShopfloorTxn getAPIResSPCTxnData_APIresShopfloorTxn(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc_api.proxies.APIresShopfloorTxn result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIResSPCTxnData_APIresShopfloorTxn.toString());
		if (identifier != null) {
			result = excr_inlinespc_api.proxies.APIresShopfloorTxn.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIResSPCTxnData_APIresShopfloorTxn
	 * @param apiresspctxndata_apiresshopfloortxn
	 */
	public final void setAPIResSPCTxnData_APIresShopfloorTxn(excr_inlinespc_api.proxies.APIresShopfloorTxn apiresspctxndata_apiresshopfloortxn)
	{
		setAPIResSPCTxnData_APIresShopfloorTxn(getContext(), apiresspctxndata_apiresshopfloortxn);
	}

	/**
	 * Set value of APIResSPCTxnData_APIresShopfloorTxn
	 * @param context
	 * @param apiresspctxndata_apiresshopfloortxn
	 */
	public final void setAPIResSPCTxnData_APIresShopfloorTxn(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc_api.proxies.APIresShopfloorTxn apiresspctxndata_apiresshopfloortxn)
	{
		if (apiresspctxndata_apiresshopfloortxn == null) {
			getMendixObject().setValue(context, MemberNames.APIResSPCTxnData_APIresShopfloorTxn.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIResSPCTxnData_APIresShopfloorTxn.toString(), apiresspctxndata_apiresshopfloortxn.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aPIResSPCTxnDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_inlinespc_api.proxies.APIResSPCTxnData that = (excr_inlinespc_api.proxies.APIResSPCTxnData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
