// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_inlinespc_api.proxies;

public class APIReqSPCTxnData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aPIReqSPCTxnDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_InlineSPC_API.APIReqSPCTxnData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Replot("Replot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public APIReqSPCTxnData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected APIReqSPCTxnData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPIReqSPCTxnDataMendixObject)
	{
		if (aPIReqSPCTxnDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!aPIReqSPCTxnDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aPIReqSPCTxnDataMendixObject = aPIReqSPCTxnDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_inlinespc_api.proxies.APIReqSPCTxnData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_inlinespc_api.proxies.APIReqSPCTxnData(context, mendixObject);
	}

	public static excr_inlinespc_api.proxies.APIReqSPCTxnData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_inlinespc_api.proxies.APIReqSPCTxnData.initialize(context, mendixObject);
	}

	/**
	 * @return value of Replot
	 */
	public final java.lang.Boolean getReplot()
	{
		return getReplot(getContext());
	}

	/**
	 * @param context
	 * @return value of Replot
	 */
	public final java.lang.Boolean getReplot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Replot.toString());
	}

	/**
	 * Set value of Replot
	 * @param replot
	 */
	public final void setReplot(java.lang.Boolean replot)
	{
		setReplot(getContext(), replot);
	}

	/**
	 * Set value of Replot
	 * @param context
	 * @param replot
	 */
	public final void setReplot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean replot)
	{
		getMendixObject().setValue(context, MemberNames.Replot.toString(), replot);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aPIReqSPCTxnDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_inlinespc_api.proxies.APIReqSPCTxnData that = (excr_inlinespc_api.proxies.APIReqSPCTxnData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
