// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_inlinespc_api.proxies;

public class APIReqAdHocWIPDataRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aPIReqAdHocWIPDataRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_InlineSPC_API.APIReqAdHocWIPDataRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ObjectName("ObjectName"),
		APIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot("EXCR_InlineSPC_API.APIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot"),
		APIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot("EXCR_InlineSPC_API.APIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot"),
		APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot("EXCR_InlineSPC_API.APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPIReqAdHocWIPDataRootMendixObject)
	{
		if (aPIReqAdHocWIPDataRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!aPIReqAdHocWIPDataRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aPIReqAdHocWIPDataRootMendixObject = aPIReqAdHocWIPDataRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot(context, mendixObject);
	}

	public static excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot.initialize(context, mendixObject);
	}

	/**
	 * @return value of ObjectName
	 */
	public final java.lang.String getObjectName()
	{
		return getObjectName(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectName
	 */
	public final java.lang.String getObjectName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectName.toString());
	}

	/**
	 * Set value of ObjectName
	 * @param objectname
	 */
	public final void setObjectName(java.lang.String objectname)
	{
		setObjectName(getContext(), objectname);
	}

	/**
	 * Set value of ObjectName
	 * @param context
	 * @param objectname
	 */
	public final void setObjectName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objectname)
	{
		getMendixObject().setValue(context, MemberNames.ObjectName.toString(), objectname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot
	 */
	public final excr_inlinespc_api.proxies.APIReqAdHocWIPDataDetails getAPIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot() throws com.mendix.core.CoreException
	{
		return getAPIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of APIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc_api.proxies.APIReqAdHocWIPDataDetails getAPIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc_api.proxies.APIReqAdHocWIPDataDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot.toString());
		if (identifier != null) {
			result = excr_inlinespc_api.proxies.APIReqAdHocWIPDataDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot
	 * @param apireqadhocwipdatadetails_apireqadhocwipdataroot
	 */
	public final void setAPIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot(excr_inlinespc_api.proxies.APIReqAdHocWIPDataDetails apireqadhocwipdatadetails_apireqadhocwipdataroot)
	{
		setAPIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot(getContext(), apireqadhocwipdatadetails_apireqadhocwipdataroot);
	}

	/**
	 * Set value of APIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot
	 * @param context
	 * @param apireqadhocwipdatadetails_apireqadhocwipdataroot
	 */
	public final void setAPIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc_api.proxies.APIReqAdHocWIPDataDetails apireqadhocwipdatadetails_apireqadhocwipdataroot)
	{
		if (apireqadhocwipdatadetails_apireqadhocwipdataroot == null) {
			getMendixObject().setValue(context, MemberNames.APIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIReqAdHocWIPDataDetails_APIReqAdHocWIPDataRoot.toString(), apireqadhocwipdatadetails_apireqadhocwipdataroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot
	 */
	public final excr_inlinespc_api.proxies.APIReqAdHocWIPDataObjectType getAPIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot() throws com.mendix.core.CoreException
	{
		return getAPIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of APIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc_api.proxies.APIReqAdHocWIPDataObjectType getAPIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc_api.proxies.APIReqAdHocWIPDataObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot.toString());
		if (identifier != null) {
			result = excr_inlinespc_api.proxies.APIReqAdHocWIPDataObjectType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot
	 * @param apireqadhocwipdataobjecttype_apireqadhocwipdataroot
	 */
	public final void setAPIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot(excr_inlinespc_api.proxies.APIReqAdHocWIPDataObjectType apireqadhocwipdataobjecttype_apireqadhocwipdataroot)
	{
		setAPIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot(getContext(), apireqadhocwipdataobjecttype_apireqadhocwipdataroot);
	}

	/**
	 * Set value of APIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot
	 * @param context
	 * @param apireqadhocwipdataobjecttype_apireqadhocwipdataroot
	 */
	public final void setAPIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc_api.proxies.APIReqAdHocWIPDataObjectType apireqadhocwipdataobjecttype_apireqadhocwipdataroot)
	{
		if (apireqadhocwipdataobjecttype_apireqadhocwipdataroot == null) {
			getMendixObject().setValue(context, MemberNames.APIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIReqAdHocWIPDataObjectType_APIReqAdHocWIPDataRoot.toString(), apireqadhocwipdataobjecttype_apireqadhocwipdataroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot
	 */
	public final excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup getAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot() throws com.mendix.core.CoreException
	{
		return getAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup getAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot.toString());
		if (identifier != null) {
			result = excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot
	 * @param apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot
	 */
	public final void setAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot)
	{
		setAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(getContext(), apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot);
	}

	/**
	 * Set value of APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot
	 * @param context
	 * @param apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot
	 */
	public final void setAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot)
	{
		if (apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot == null) {
			getMendixObject().setValue(context, MemberNames.APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot.toString(), apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aPIReqAdHocWIPDataRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot that = (excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
