// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_inlinespc_api.proxies;

public class APIReqAdHocWIPDataWIPDataSetup implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aPIReqAdHocWIPDataWIPDataSetupMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_InlineSPC_API.APIReqAdHocWIPDataWIPDataSetup";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot("EXCR_InlineSPC_API.APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public APIReqAdHocWIPDataWIPDataSetup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected APIReqAdHocWIPDataWIPDataSetup(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPIReqAdHocWIPDataWIPDataSetupMendixObject)
	{
		if (aPIReqAdHocWIPDataWIPDataSetupMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!aPIReqAdHocWIPDataWIPDataSetupMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aPIReqAdHocWIPDataWIPDataSetupMendixObject = aPIReqAdHocWIPDataWIPDataSetupMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup(context, mendixObject);
	}

	public static excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot
	 */
	public final excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot getAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot() throws com.mendix.core.CoreException
	{
		return getAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot getAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot.toString());
		if (identifier != null) {
			result = excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot
	 * @param apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot
	 */
	public final void setAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot)
	{
		setAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(getContext(), apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot);
	}

	/**
	 * Set value of APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot
	 * @param context
	 * @param apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot
	 */
	public final void setAPIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc_api.proxies.APIReqAdHocWIPDataRoot apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot)
	{
		if (apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot == null) {
			getMendixObject().setValue(context, MemberNames.APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIReqAdHocWIPDataWIPDataSetup_APIReqAdHocWIPDataRoot.toString(), apireqadhocwipdatawipdatasetup_apireqadhocwipdataroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aPIReqAdHocWIPDataWIPDataSetupMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup that = (excr_inlinespc_api.proxies.APIReqAdHocWIPDataWIPDataSetup) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
