// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_inlinespc_api.proxies;

public class APIResSPCRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aPIResSPCRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_InlineSPC_API.APIResSPCRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		APIResSPCRoot_SPCDataViewControl("EXCR_InlineSPC_API.APIResSPCRoot_SPCDataViewControl");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public APIResSPCRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected APIResSPCRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPIResSPCRootMendixObject)
	{
		if (aPIResSPCRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!aPIResSPCRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aPIResSPCRootMendixObject = aPIResSPCRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_inlinespc_api.proxies.APIResSPCRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_inlinespc_api.proxies.APIResSPCRoot(context, mendixObject);
	}

	public static excr_inlinespc_api.proxies.APIResSPCRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_inlinespc_api.proxies.APIResSPCRoot.initialize(context, mendixObject);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of APIResSPCRoot_SPCDataViewControl
	 */
	public final excr_inlinespc.proxies.SPCDataViewControl getAPIResSPCRoot_SPCDataViewControl() throws com.mendix.core.CoreException
	{
		return getAPIResSPCRoot_SPCDataViewControl(getContext());
	}

	/**
	 * @param context
	 * @return value of APIResSPCRoot_SPCDataViewControl
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc.proxies.SPCDataViewControl getAPIResSPCRoot_SPCDataViewControl(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc.proxies.SPCDataViewControl result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APIResSPCRoot_SPCDataViewControl.toString());
		if (identifier != null) {
			result = excr_inlinespc.proxies.SPCDataViewControl.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of APIResSPCRoot_SPCDataViewControl
	 * @param apiresspcroot_spcdataviewcontrol
	 */
	public final void setAPIResSPCRoot_SPCDataViewControl(excr_inlinespc.proxies.SPCDataViewControl apiresspcroot_spcdataviewcontrol)
	{
		setAPIResSPCRoot_SPCDataViewControl(getContext(), apiresspcroot_spcdataviewcontrol);
	}

	/**
	 * Set value of APIResSPCRoot_SPCDataViewControl
	 * @param context
	 * @param apiresspcroot_spcdataviewcontrol
	 */
	public final void setAPIResSPCRoot_SPCDataViewControl(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc.proxies.SPCDataViewControl apiresspcroot_spcdataviewcontrol)
	{
		if (apiresspcroot_spcdataviewcontrol == null) {
			getMendixObject().setValue(context, MemberNames.APIResSPCRoot_SPCDataViewControl.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.APIResSPCRoot_SPCDataViewControl.toString(), apiresspcroot_spcdataviewcontrol.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aPIResSPCRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_inlinespc_api.proxies.APIResSPCRoot that = (excr_inlinespc_api.proxies.APIResSPCRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
