// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_inlinespc_api.proxies;

public class SPCResDataPoint implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sPCResDataPointMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_InlineSPC_API.SPCResDataPoint";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataValue("DataValue"),
		IsExisting("IsExisting"),
		UIOverrideValue("UIOverrideValue"),
		SPCTXNDATAPOINTNAME("SPCTXNDATAPOINTNAME"),
		DESCRIPTION("DESCRIPTION"),
		OVERRIDEVALUE("OVERRIDEVALUE"),
		EXCLUDEDATA("EXCLUDEDATA"),
		SPCEXCLUDEREASONNAME("SPCEXCLUDEREASONNAME"),
		SS_SPCANNOTATIONCATEGORYNAME("SS_SPCANNOTATIONCATEGORYNAME"),
		SPCTXNDATAPOINTID("SPCTXNDATAPOINTID"),
		SPCResDataPoint_APIResSPCTxnDataPoint("EXCR_InlineSPC_API.SPCResDataPoint_APIResSPCTxnDataPoint"),
		ModifiedSPCResDataPoints("EXCR_InlineSPC_API.ModifiedSPCResDataPoints");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SPCResDataPoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SPCResDataPoint(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sPCResDataPointMendixObject)
	{
		if (sPCResDataPointMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!sPCResDataPointMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sPCResDataPointMendixObject = sPCResDataPointMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_inlinespc_api.proxies.SPCResDataPoint initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_inlinespc_api.proxies.SPCResDataPoint(context, mendixObject);
	}

	public static excr_inlinespc_api.proxies.SPCResDataPoint load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_inlinespc_api.proxies.SPCResDataPoint.initialize(context, mendixObject);
	}

	/**
	 * @return value of DataValue
	 */
	public final java.lang.String getDataValue()
	{
		return getDataValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DataValue
	 */
	public final java.lang.String getDataValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataValue.toString());
	}

	/**
	 * Set value of DataValue
	 * @param datavalue
	 */
	public final void setDataValue(java.lang.String datavalue)
	{
		setDataValue(getContext(), datavalue);
	}

	/**
	 * Set value of DataValue
	 * @param context
	 * @param datavalue
	 */
	public final void setDataValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datavalue)
	{
		getMendixObject().setValue(context, MemberNames.DataValue.toString(), datavalue);
	}

	/**
	 * @return value of IsExisting
	 */
	public final java.lang.Boolean getIsExisting()
	{
		return getIsExisting(getContext());
	}

	/**
	 * @param context
	 * @return value of IsExisting
	 */
	public final java.lang.Boolean getIsExisting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsExisting.toString());
	}

	/**
	 * Set value of IsExisting
	 * @param isexisting
	 */
	public final void setIsExisting(java.lang.Boolean isexisting)
	{
		setIsExisting(getContext(), isexisting);
	}

	/**
	 * Set value of IsExisting
	 * @param context
	 * @param isexisting
	 */
	public final void setIsExisting(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isexisting)
	{
		getMendixObject().setValue(context, MemberNames.IsExisting.toString(), isexisting);
	}

	/**
	 * @return value of UIOverrideValue
	 */
	public final java.math.BigDecimal getUIOverrideValue()
	{
		return getUIOverrideValue(getContext());
	}

	/**
	 * @param context
	 * @return value of UIOverrideValue
	 */
	public final java.math.BigDecimal getUIOverrideValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.UIOverrideValue.toString());
	}

	/**
	 * Set value of UIOverrideValue
	 * @param uioverridevalue
	 */
	public final void setUIOverrideValue(java.math.BigDecimal uioverridevalue)
	{
		setUIOverrideValue(getContext(), uioverridevalue);
	}

	/**
	 * Set value of UIOverrideValue
	 * @param context
	 * @param uioverridevalue
	 */
	public final void setUIOverrideValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal uioverridevalue)
	{
		getMendixObject().setValue(context, MemberNames.UIOverrideValue.toString(), uioverridevalue);
	}

	/**
	 * @return value of SPCTXNDATAPOINTNAME
	 */
	public final java.lang.String getSPCTXNDATAPOINTNAME()
	{
		return getSPCTXNDATAPOINTNAME(getContext());
	}

	/**
	 * @param context
	 * @return value of SPCTXNDATAPOINTNAME
	 */
	public final java.lang.String getSPCTXNDATAPOINTNAME(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SPCTXNDATAPOINTNAME.toString());
	}

	/**
	 * Set value of SPCTXNDATAPOINTNAME
	 * @param spctxndatapointname
	 */
	public final void setSPCTXNDATAPOINTNAME(java.lang.String spctxndatapointname)
	{
		setSPCTXNDATAPOINTNAME(getContext(), spctxndatapointname);
	}

	/**
	 * Set value of SPCTXNDATAPOINTNAME
	 * @param context
	 * @param spctxndatapointname
	 */
	public final void setSPCTXNDATAPOINTNAME(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String spctxndatapointname)
	{
		getMendixObject().setValue(context, MemberNames.SPCTXNDATAPOINTNAME.toString(), spctxndatapointname);
	}

	/**
	 * @return value of DESCRIPTION
	 */
	public final java.lang.String getDESCRIPTION()
	{
		return getDESCRIPTION(getContext());
	}

	/**
	 * @param context
	 * @return value of DESCRIPTION
	 */
	public final java.lang.String getDESCRIPTION(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DESCRIPTION.toString());
	}

	/**
	 * Set value of DESCRIPTION
	 * @param description
	 */
	public final void setDESCRIPTION(java.lang.String description)
	{
		setDESCRIPTION(getContext(), description);
	}

	/**
	 * Set value of DESCRIPTION
	 * @param context
	 * @param description
	 */
	public final void setDESCRIPTION(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.DESCRIPTION.toString(), description);
	}

	/**
	 * @return value of OVERRIDEVALUE
	 */
	public final java.lang.String getOVERRIDEVALUE()
	{
		return getOVERRIDEVALUE(getContext());
	}

	/**
	 * @param context
	 * @return value of OVERRIDEVALUE
	 */
	public final java.lang.String getOVERRIDEVALUE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OVERRIDEVALUE.toString());
	}

	/**
	 * Set value of OVERRIDEVALUE
	 * @param overridevalue
	 */
	public final void setOVERRIDEVALUE(java.lang.String overridevalue)
	{
		setOVERRIDEVALUE(getContext(), overridevalue);
	}

	/**
	 * Set value of OVERRIDEVALUE
	 * @param context
	 * @param overridevalue
	 */
	public final void setOVERRIDEVALUE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String overridevalue)
	{
		getMendixObject().setValue(context, MemberNames.OVERRIDEVALUE.toString(), overridevalue);
	}

	/**
	 * @return value of EXCLUDEDATA
	 */
	public final java.lang.String getEXCLUDEDATA()
	{
		return getEXCLUDEDATA(getContext());
	}

	/**
	 * @param context
	 * @return value of EXCLUDEDATA
	 */
	public final java.lang.String getEXCLUDEDATA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EXCLUDEDATA.toString());
	}

	/**
	 * Set value of EXCLUDEDATA
	 * @param excludedata
	 */
	public final void setEXCLUDEDATA(java.lang.String excludedata)
	{
		setEXCLUDEDATA(getContext(), excludedata);
	}

	/**
	 * Set value of EXCLUDEDATA
	 * @param context
	 * @param excludedata
	 */
	public final void setEXCLUDEDATA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String excludedata)
	{
		getMendixObject().setValue(context, MemberNames.EXCLUDEDATA.toString(), excludedata);
	}

	/**
	 * @return value of SPCEXCLUDEREASONNAME
	 */
	public final java.lang.String getSPCEXCLUDEREASONNAME()
	{
		return getSPCEXCLUDEREASONNAME(getContext());
	}

	/**
	 * @param context
	 * @return value of SPCEXCLUDEREASONNAME
	 */
	public final java.lang.String getSPCEXCLUDEREASONNAME(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SPCEXCLUDEREASONNAME.toString());
	}

	/**
	 * Set value of SPCEXCLUDEREASONNAME
	 * @param spcexcludereasonname
	 */
	public final void setSPCEXCLUDEREASONNAME(java.lang.String spcexcludereasonname)
	{
		setSPCEXCLUDEREASONNAME(getContext(), spcexcludereasonname);
	}

	/**
	 * Set value of SPCEXCLUDEREASONNAME
	 * @param context
	 * @param spcexcludereasonname
	 */
	public final void setSPCEXCLUDEREASONNAME(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String spcexcludereasonname)
	{
		getMendixObject().setValue(context, MemberNames.SPCEXCLUDEREASONNAME.toString(), spcexcludereasonname);
	}

	/**
	 * @return value of SS_SPCANNOTATIONCATEGORYNAME
	 */
	public final java.lang.String getSS_SPCANNOTATIONCATEGORYNAME()
	{
		return getSS_SPCANNOTATIONCATEGORYNAME(getContext());
	}

	/**
	 * @param context
	 * @return value of SS_SPCANNOTATIONCATEGORYNAME
	 */
	public final java.lang.String getSS_SPCANNOTATIONCATEGORYNAME(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SS_SPCANNOTATIONCATEGORYNAME.toString());
	}

	/**
	 * Set value of SS_SPCANNOTATIONCATEGORYNAME
	 * @param ss_spcannotationcategoryname
	 */
	public final void setSS_SPCANNOTATIONCATEGORYNAME(java.lang.String ss_spcannotationcategoryname)
	{
		setSS_SPCANNOTATIONCATEGORYNAME(getContext(), ss_spcannotationcategoryname);
	}

	/**
	 * Set value of SS_SPCANNOTATIONCATEGORYNAME
	 * @param context
	 * @param ss_spcannotationcategoryname
	 */
	public final void setSS_SPCANNOTATIONCATEGORYNAME(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ss_spcannotationcategoryname)
	{
		getMendixObject().setValue(context, MemberNames.SS_SPCANNOTATIONCATEGORYNAME.toString(), ss_spcannotationcategoryname);
	}

	/**
	 * @return value of SPCTXNDATAPOINTID
	 */
	public final java.lang.String getSPCTXNDATAPOINTID()
	{
		return getSPCTXNDATAPOINTID(getContext());
	}

	/**
	 * @param context
	 * @return value of SPCTXNDATAPOINTID
	 */
	public final java.lang.String getSPCTXNDATAPOINTID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SPCTXNDATAPOINTID.toString());
	}

	/**
	 * Set value of SPCTXNDATAPOINTID
	 * @param spctxndatapointid
	 */
	public final void setSPCTXNDATAPOINTID(java.lang.String spctxndatapointid)
	{
		setSPCTXNDATAPOINTID(getContext(), spctxndatapointid);
	}

	/**
	 * Set value of SPCTXNDATAPOINTID
	 * @param context
	 * @param spctxndatapointid
	 */
	public final void setSPCTXNDATAPOINTID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String spctxndatapointid)
	{
		getMendixObject().setValue(context, MemberNames.SPCTXNDATAPOINTID.toString(), spctxndatapointid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SPCResDataPoint_APIResSPCTxnDataPoint
	 */
	public final excr_inlinespc_api.proxies.APIResSPCTxnDataPoint getSPCResDataPoint_APIResSPCTxnDataPoint() throws com.mendix.core.CoreException
	{
		return getSPCResDataPoint_APIResSPCTxnDataPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of SPCResDataPoint_APIResSPCTxnDataPoint
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc_api.proxies.APIResSPCTxnDataPoint getSPCResDataPoint_APIResSPCTxnDataPoint(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc_api.proxies.APIResSPCTxnDataPoint result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SPCResDataPoint_APIResSPCTxnDataPoint.toString());
		if (identifier != null) {
			result = excr_inlinespc_api.proxies.APIResSPCTxnDataPoint.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SPCResDataPoint_APIResSPCTxnDataPoint
	 * @param spcresdatapoint_apiresspctxndatapoint
	 */
	public final void setSPCResDataPoint_APIResSPCTxnDataPoint(excr_inlinespc_api.proxies.APIResSPCTxnDataPoint spcresdatapoint_apiresspctxndatapoint)
	{
		setSPCResDataPoint_APIResSPCTxnDataPoint(getContext(), spcresdatapoint_apiresspctxndatapoint);
	}

	/**
	 * Set value of SPCResDataPoint_APIResSPCTxnDataPoint
	 * @param context
	 * @param spcresdatapoint_apiresspctxndatapoint
	 */
	public final void setSPCResDataPoint_APIResSPCTxnDataPoint(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc_api.proxies.APIResSPCTxnDataPoint spcresdatapoint_apiresspctxndatapoint)
	{
		if (spcresdatapoint_apiresspctxndatapoint == null) {
			getMendixObject().setValue(context, MemberNames.SPCResDataPoint_APIResSPCTxnDataPoint.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SPCResDataPoint_APIResSPCTxnDataPoint.toString(), spcresdatapoint_apiresspctxndatapoint.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ModifiedSPCResDataPoints
	 */
	public final excr_inlinespc.proxies.SPCDataValuesControl getModifiedSPCResDataPoints() throws com.mendix.core.CoreException
	{
		return getModifiedSPCResDataPoints(getContext());
	}

	/**
	 * @param context
	 * @return value of ModifiedSPCResDataPoints
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_inlinespc.proxies.SPCDataValuesControl getModifiedSPCResDataPoints(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_inlinespc.proxies.SPCDataValuesControl result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ModifiedSPCResDataPoints.toString());
		if (identifier != null) {
			result = excr_inlinespc.proxies.SPCDataValuesControl.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ModifiedSPCResDataPoints
	 * @param modifiedspcresdatapoints
	 */
	public final void setModifiedSPCResDataPoints(excr_inlinespc.proxies.SPCDataValuesControl modifiedspcresdatapoints)
	{
		setModifiedSPCResDataPoints(getContext(), modifiedspcresdatapoints);
	}

	/**
	 * Set value of ModifiedSPCResDataPoints
	 * @param context
	 * @param modifiedspcresdatapoints
	 */
	public final void setModifiedSPCResDataPoints(com.mendix.systemwideinterfaces.core.IContext context, excr_inlinespc.proxies.SPCDataValuesControl modifiedspcresdatapoints)
	{
		if (modifiedspcresdatapoints == null) {
			getMendixObject().setValue(context, MemberNames.ModifiedSPCResDataPoints.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ModifiedSPCResDataPoints.toString(), modifiedspcresdatapoints.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sPCResDataPointMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_inlinespc_api.proxies.SPCResDataPoint that = (excr_inlinespc_api.proxies.SPCResDataPoint) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
