// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons_api.proxies;

public class ApiResCosignerReasonValueItem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject apiResCosignerReasonValueItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons_API.ApiResCosignerReasonValueItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApiResCosignerReasonValueItem_ApiResCosignerSignerRoot("EXCR_Commons_API.ApiResCosignerReasonValueItem_ApiResCosignerSignerRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ApiResCosignerReasonValueItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ApiResCosignerReasonValueItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject apiResCosignerReasonValueItemMendixObject)
	{
		if (apiResCosignerReasonValueItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!apiResCosignerReasonValueItemMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.apiResCosignerReasonValueItemMendixObject = apiResCosignerReasonValueItemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons_api.proxies.ApiResCosignerReasonValueItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons_api.proxies.ApiResCosignerReasonValueItem(context, mendixObject);
	}

	public static excr_commons_api.proxies.ApiResCosignerReasonValueItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons_api.proxies.ApiResCosignerReasonValueItem.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ApiResCosignerReasonValueItem_ApiResCosignerSignerRoot
	 */
	public final excr_commons_api.proxies.ApiResCosignerSignerRoot getApiResCosignerReasonValueItem_ApiResCosignerSignerRoot() throws com.mendix.core.CoreException
	{
		return getApiResCosignerReasonValueItem_ApiResCosignerSignerRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiResCosignerReasonValueItem_ApiResCosignerSignerRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ApiResCosignerSignerRoot getApiResCosignerReasonValueItem_ApiResCosignerSignerRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ApiResCosignerSignerRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApiResCosignerReasonValueItem_ApiResCosignerSignerRoot.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ApiResCosignerSignerRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ApiResCosignerReasonValueItem_ApiResCosignerSignerRoot
	 * @param apirescosignerreasonvalueitem_apirescosignersignerroot
	 */
	public final void setApiResCosignerReasonValueItem_ApiResCosignerSignerRoot(excr_commons_api.proxies.ApiResCosignerSignerRoot apirescosignerreasonvalueitem_apirescosignersignerroot)
	{
		setApiResCosignerReasonValueItem_ApiResCosignerSignerRoot(getContext(), apirescosignerreasonvalueitem_apirescosignersignerroot);
	}

	/**
	 * Set value of ApiResCosignerReasonValueItem_ApiResCosignerSignerRoot
	 * @param context
	 * @param apirescosignerreasonvalueitem_apirescosignersignerroot
	 */
	public final void setApiResCosignerReasonValueItem_ApiResCosignerSignerRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ApiResCosignerSignerRoot apirescosignerreasonvalueitem_apirescosignersignerroot)
	{
		if (apirescosignerreasonvalueitem_apirescosignersignerroot == null) {
			getMendixObject().setValue(context, MemberNames.ApiResCosignerReasonValueItem_ApiResCosignerSignerRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ApiResCosignerReasonValueItem_ApiResCosignerSignerRoot.toString(), apirescosignerreasonvalueitem_apirescosignersignerroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return apiResCosignerReasonValueItemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons_api.proxies.ApiResCosignerReasonValueItem that = (excr_commons_api.proxies.ApiResCosignerReasonValueItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
