// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons_api.proxies;

public class ApiReqCurrentEmployee implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject apiReqCurrentEmployeeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons_API.ApiReqCurrentEmployee";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot("EXCR_Commons_API.ApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ApiReqCurrentEmployee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ApiReqCurrentEmployee(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject apiReqCurrentEmployeeMendixObject)
	{
		if (apiReqCurrentEmployeeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!apiReqCurrentEmployeeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.apiReqCurrentEmployeeMendixObject = apiReqCurrentEmployeeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons_api.proxies.ApiReqCurrentEmployee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons_api.proxies.ApiReqCurrentEmployee(context, mendixObject);
	}

	public static excr_commons_api.proxies.ApiReqCurrentEmployee load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons_api.proxies.ApiReqCurrentEmployee.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot
	 */
	public final excr_commons_api.proxies.ApiReqCurrentEmployeeRoot getApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot() throws com.mendix.core.CoreException
	{
		return getApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ApiReqCurrentEmployeeRoot getApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ApiReqCurrentEmployeeRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ApiReqCurrentEmployeeRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot
	 * @param apireqcurrentemployee_apireqcurrentemployeeroot
	 */
	public final void setApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot(excr_commons_api.proxies.ApiReqCurrentEmployeeRoot apireqcurrentemployee_apireqcurrentemployeeroot)
	{
		setApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot(getContext(), apireqcurrentemployee_apireqcurrentemployeeroot);
	}

	/**
	 * Set value of ApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot
	 * @param context
	 * @param apireqcurrentemployee_apireqcurrentemployeeroot
	 */
	public final void setApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ApiReqCurrentEmployeeRoot apireqcurrentemployee_apireqcurrentemployeeroot)
	{
		if (apireqcurrentemployee_apireqcurrentemployeeroot == null) {
			getMendixObject().setValue(context, MemberNames.ApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ApiReqCurrentEmployee_ApiReqCurrentEmployeeRoot.toString(), apireqcurrentemployee_apireqcurrentemployeeroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return apiReqCurrentEmployeeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons_api.proxies.ApiReqCurrentEmployee that = (excr_commons_api.proxies.ApiReqCurrentEmployee) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
