// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons_api.proxies;

public class ApiResEmployeeRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject apiResEmployeeRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons_API.ApiResEmployeeRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApiResSessionValues_ApiResEmployeeRoot("EXCR_Commons_API.ApiResSessionValues_ApiResEmployeeRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ApiResEmployeeRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ApiResEmployeeRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject apiResEmployeeRootMendixObject)
	{
		if (apiResEmployeeRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!apiResEmployeeRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.apiResEmployeeRootMendixObject = apiResEmployeeRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons_api.proxies.ApiResEmployeeRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons_api.proxies.ApiResEmployeeRoot(context, mendixObject);
	}

	public static excr_commons_api.proxies.ApiResEmployeeRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons_api.proxies.ApiResEmployeeRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ApiResSessionValues_ApiResEmployeeRoot
	 */
	public final excr_commons_api.proxies.ApiResSessionValues getApiResSessionValues_ApiResEmployeeRoot() throws com.mendix.core.CoreException
	{
		return getApiResSessionValues_ApiResEmployeeRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiResSessionValues_ApiResEmployeeRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ApiResSessionValues getApiResSessionValues_ApiResEmployeeRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ApiResSessionValues result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApiResSessionValues_ApiResEmployeeRoot.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ApiResSessionValues.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ApiResSessionValues_ApiResEmployeeRoot
	 * @param apiressessionvalues_apiresemployeeroot
	 */
	public final void setApiResSessionValues_ApiResEmployeeRoot(excr_commons_api.proxies.ApiResSessionValues apiressessionvalues_apiresemployeeroot)
	{
		setApiResSessionValues_ApiResEmployeeRoot(getContext(), apiressessionvalues_apiresemployeeroot);
	}

	/**
	 * Set value of ApiResSessionValues_ApiResEmployeeRoot
	 * @param context
	 * @param apiressessionvalues_apiresemployeeroot
	 */
	public final void setApiResSessionValues_ApiResEmployeeRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ApiResSessionValues apiressessionvalues_apiresemployeeroot)
	{
		if (apiressessionvalues_apiresemployeeroot == null) {
			getMendixObject().setValue(context, MemberNames.ApiResSessionValues_ApiResEmployeeRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ApiResSessionValues_ApiResEmployeeRoot.toString(), apiressessionvalues_apiresemployeeroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return apiResEmployeeRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons_api.proxies.ApiResEmployeeRoot that = (excr_commons_api.proxies.ApiResEmployeeRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
