// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons_api.proxies;

public class ApiResRole implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject apiResRoleMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons_API.ApiResRole";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ApiResRole_ApiResRoleRoot("EXCR_Commons_API.ApiResRole_ApiResRoleRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ApiResRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ApiResRole(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject apiResRoleMendixObject)
	{
		if (apiResRoleMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!apiResRoleMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.apiResRoleMendixObject = apiResRoleMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons_api.proxies.ApiResRole initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons_api.proxies.ApiResRole(context, mendixObject);
	}

	public static excr_commons_api.proxies.ApiResRole load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons_api.proxies.ApiResRole.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ApiResRole_ApiResRoleRoot
	 */
	public final excr_commons_api.proxies.ApiResRoleRoot getApiResRole_ApiResRoleRoot() throws com.mendix.core.CoreException
	{
		return getApiResRole_ApiResRoleRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiResRole_ApiResRoleRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ApiResRoleRoot getApiResRole_ApiResRoleRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ApiResRoleRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApiResRole_ApiResRoleRoot.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ApiResRoleRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ApiResRole_ApiResRoleRoot
	 * @param apiresrole_apiresroleroot
	 */
	public final void setApiResRole_ApiResRoleRoot(excr_commons_api.proxies.ApiResRoleRoot apiresrole_apiresroleroot)
	{
		setApiResRole_ApiResRoleRoot(getContext(), apiresrole_apiresroleroot);
	}

	/**
	 * Set value of ApiResRole_ApiResRoleRoot
	 * @param context
	 * @param apiresrole_apiresroleroot
	 */
	public final void setApiResRole_ApiResRoleRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ApiResRoleRoot apiresrole_apiresroleroot)
	{
		if (apiresrole_apiresroleroot == null) {
			getMendixObject().setValue(context, MemberNames.ApiResRole_ApiResRoleRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ApiResRole_ApiResRoleRoot.toString(), apiresrole_apiresroleroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return apiResRoleMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons_api.proxies.ApiResRole that = (excr_commons_api.proxies.ApiResRole) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
