// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons_api.proxies;

public class ESigProcessTimerDtl implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject eSigProcessTimerDtlMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons_API.ESigProcessTimerDtl";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InstanceID("InstanceID"),
		CaptureCount("CaptureCount"),
		Qty("Qty"),
		SignatureCount("SignatureCount"),
		VerificationMethod("VerificationMethod"),
		ESigProcessTimerDtl_ESigProcessTimerDtls("EXCR_Commons_API.ESigProcessTimerDtl_ESigProcessTimerDtls"),
		Container_2_ESigProcessTimerDtl("EXCR_Commons_API.Container_2_ESigProcessTimerDtl"),
		CosignerRole_ESigProcessTimerDtl("EXCR_Commons_API.CosignerRole_ESigProcessTimerDtl"),
		ESigReqDetail_2_ESigProcessTimerDtl("EXCR_Commons_API.ESigReqDetail_2_ESigProcessTimerDtl"),
		Meaning_2_ESigProcessTimerDtl("EXCR_Commons_API.Meaning_2_ESigProcessTimerDtl"),
		Role_2_ESigProcessTimerDtl("EXCR_Commons_API.Role_2_ESigProcessTimerDtl"),
		Spec_2_ESigProcessTimerDtl("EXCR_Commons_API.Spec_2_ESigProcessTimerDtl"),
		UOM_2_ESigProcessTimerDtl("EXCR_Commons_API.UOM_2_ESigProcessTimerDtl"),
		ESigProcessTimerDtl_CaptureDetails("EXCR_Commons_API.ESigProcessTimerDtl_CaptureDetails");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject eSigProcessTimerDtlMendixObject)
	{
		if (eSigProcessTimerDtlMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!eSigProcessTimerDtlMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.eSigProcessTimerDtlMendixObject = eSigProcessTimerDtlMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons_api.proxies.ESigProcessTimerDtl initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons_api.proxies.ESigProcessTimerDtl(context, mendixObject);
	}

	public static excr_commons_api.proxies.ESigProcessTimerDtl load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons_api.proxies.ESigProcessTimerDtl.initialize(context, mendixObject);
	}

	/**
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID()
	{
		return getInstanceID(getContext());
	}

	/**
	 * @param context
	 * @return value of InstanceID
	 */
	public final java.lang.String getInstanceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstanceID.toString());
	}

	/**
	 * Set value of InstanceID
	 * @param instanceid
	 */
	public final void setInstanceID(java.lang.String instanceid)
	{
		setInstanceID(getContext(), instanceid);
	}

	/**
	 * Set value of InstanceID
	 * @param context
	 * @param instanceid
	 */
	public final void setInstanceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instanceid)
	{
		getMendixObject().setValue(context, MemberNames.InstanceID.toString(), instanceid);
	}

	/**
	 * @return value of CaptureCount
	 */
	public final java.lang.Integer getCaptureCount()
	{
		return getCaptureCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CaptureCount
	 */
	public final java.lang.Integer getCaptureCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CaptureCount.toString());
	}

	/**
	 * Set value of CaptureCount
	 * @param capturecount
	 */
	public final void setCaptureCount(java.lang.Integer capturecount)
	{
		setCaptureCount(getContext(), capturecount);
	}

	/**
	 * Set value of CaptureCount
	 * @param context
	 * @param capturecount
	 */
	public final void setCaptureCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer capturecount)
	{
		getMendixObject().setValue(context, MemberNames.CaptureCount.toString(), capturecount);
	}

	/**
	 * @return value of Qty
	 */
	public final java.math.BigDecimal getQty()
	{
		return getQty(getContext());
	}

	/**
	 * @param context
	 * @return value of Qty
	 */
	public final java.math.BigDecimal getQty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Qty.toString());
	}

	/**
	 * Set value of Qty
	 * @param qty
	 */
	public final void setQty(java.math.BigDecimal qty)
	{
		setQty(getContext(), qty);
	}

	/**
	 * Set value of Qty
	 * @param context
	 * @param qty
	 */
	public final void setQty(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal qty)
	{
		getMendixObject().setValue(context, MemberNames.Qty.toString(), qty);
	}

	/**
	 * @return value of SignatureCount
	 */
	public final java.lang.Integer getSignatureCount()
	{
		return getSignatureCount(getContext());
	}

	/**
	 * @param context
	 * @return value of SignatureCount
	 */
	public final java.lang.Integer getSignatureCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SignatureCount.toString());
	}

	/**
	 * Set value of SignatureCount
	 * @param signaturecount
	 */
	public final void setSignatureCount(java.lang.Integer signaturecount)
	{
		setSignatureCount(getContext(), signaturecount);
	}

	/**
	 * Set value of SignatureCount
	 * @param context
	 * @param signaturecount
	 */
	public final void setSignatureCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer signaturecount)
	{
		getMendixObject().setValue(context, MemberNames.SignatureCount.toString(), signaturecount);
	}

	/**
	 * @return value of VerificationMethod
	 */
	public final java.lang.Integer getVerificationMethod()
	{
		return getVerificationMethod(getContext());
	}

	/**
	 * @param context
	 * @return value of VerificationMethod
	 */
	public final java.lang.Integer getVerificationMethod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.VerificationMethod.toString());
	}

	/**
	 * Set value of VerificationMethod
	 * @param verificationmethod
	 */
	public final void setVerificationMethod(java.lang.Integer verificationmethod)
	{
		setVerificationMethod(getContext(), verificationmethod);
	}

	/**
	 * Set value of VerificationMethod
	 * @param context
	 * @param verificationmethod
	 */
	public final void setVerificationMethod(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer verificationmethod)
	{
		getMendixObject().setValue(context, MemberNames.VerificationMethod.toString(), verificationmethod);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ESigProcessTimerDtl_ESigProcessTimerDtls
	 */
	public final excr_commons_api.proxies.ESigProcessTimerDtls getESigProcessTimerDtl_ESigProcessTimerDtls() throws com.mendix.core.CoreException
	{
		return getESigProcessTimerDtl_ESigProcessTimerDtls(getContext());
	}

	/**
	 * @param context
	 * @return value of ESigProcessTimerDtl_ESigProcessTimerDtls
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ESigProcessTimerDtls getESigProcessTimerDtl_ESigProcessTimerDtls(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ESigProcessTimerDtls result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ESigProcessTimerDtl_ESigProcessTimerDtls.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ESigProcessTimerDtls.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ESigProcessTimerDtl_ESigProcessTimerDtls
	 * @param esigprocesstimerdtl_esigprocesstimerdtls
	 */
	public final void setESigProcessTimerDtl_ESigProcessTimerDtls(excr_commons_api.proxies.ESigProcessTimerDtls esigprocesstimerdtl_esigprocesstimerdtls)
	{
		setESigProcessTimerDtl_ESigProcessTimerDtls(getContext(), esigprocesstimerdtl_esigprocesstimerdtls);
	}

	/**
	 * Set value of ESigProcessTimerDtl_ESigProcessTimerDtls
	 * @param context
	 * @param esigprocesstimerdtl_esigprocesstimerdtls
	 */
	public final void setESigProcessTimerDtl_ESigProcessTimerDtls(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ESigProcessTimerDtls esigprocesstimerdtl_esigprocesstimerdtls)
	{
		if (esigprocesstimerdtl_esigprocesstimerdtls == null) {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDtl_ESigProcessTimerDtls.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDtl_ESigProcessTimerDtls.toString(), esigprocesstimerdtl_esigprocesstimerdtls.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Container_2_ESigProcessTimerDtl
	 */
	public final excr_commons_api.proxies.Container_2 getContainer_2_ESigProcessTimerDtl() throws com.mendix.core.CoreException
	{
		return getContainer_2_ESigProcessTimerDtl(getContext());
	}

	/**
	 * @param context
	 * @return value of Container_2_ESigProcessTimerDtl
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.Container_2 getContainer_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.Container_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Container_2_ESigProcessTimerDtl.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.Container_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Container_2_ESigProcessTimerDtl
	 * @param container_2_esigprocesstimerdtl
	 */
	public final void setContainer_2_ESigProcessTimerDtl(excr_commons_api.proxies.Container_2 container_2_esigprocesstimerdtl)
	{
		setContainer_2_ESigProcessTimerDtl(getContext(), container_2_esigprocesstimerdtl);
	}

	/**
	 * Set value of Container_2_ESigProcessTimerDtl
	 * @param context
	 * @param container_2_esigprocesstimerdtl
	 */
	public final void setContainer_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.Container_2 container_2_esigprocesstimerdtl)
	{
		if (container_2_esigprocesstimerdtl == null) {
			getMendixObject().setValue(context, MemberNames.Container_2_ESigProcessTimerDtl.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Container_2_ESigProcessTimerDtl.toString(), container_2_esigprocesstimerdtl.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CosignerRole_ESigProcessTimerDtl
	 */
	public final excr_commons_api.proxies.CosignerRole getCosignerRole_ESigProcessTimerDtl() throws com.mendix.core.CoreException
	{
		return getCosignerRole_ESigProcessTimerDtl(getContext());
	}

	/**
	 * @param context
	 * @return value of CosignerRole_ESigProcessTimerDtl
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.CosignerRole getCosignerRole_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.CosignerRole result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CosignerRole_ESigProcessTimerDtl.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.CosignerRole.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CosignerRole_ESigProcessTimerDtl
	 * @param cosignerrole_esigprocesstimerdtl
	 */
	public final void setCosignerRole_ESigProcessTimerDtl(excr_commons_api.proxies.CosignerRole cosignerrole_esigprocesstimerdtl)
	{
		setCosignerRole_ESigProcessTimerDtl(getContext(), cosignerrole_esigprocesstimerdtl);
	}

	/**
	 * Set value of CosignerRole_ESigProcessTimerDtl
	 * @param context
	 * @param cosignerrole_esigprocesstimerdtl
	 */
	public final void setCosignerRole_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.CosignerRole cosignerrole_esigprocesstimerdtl)
	{
		if (cosignerrole_esigprocesstimerdtl == null) {
			getMendixObject().setValue(context, MemberNames.CosignerRole_ESigProcessTimerDtl.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CosignerRole_ESigProcessTimerDtl.toString(), cosignerrole_esigprocesstimerdtl.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ESigReqDetail_2_ESigProcessTimerDtl
	 */
	public final excr_commons_api.proxies.ESigReqDetail_2 getESigReqDetail_2_ESigProcessTimerDtl() throws com.mendix.core.CoreException
	{
		return getESigReqDetail_2_ESigProcessTimerDtl(getContext());
	}

	/**
	 * @param context
	 * @return value of ESigReqDetail_2_ESigProcessTimerDtl
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ESigReqDetail_2 getESigReqDetail_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ESigReqDetail_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ESigReqDetail_2_ESigProcessTimerDtl.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ESigReqDetail_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ESigReqDetail_2_ESigProcessTimerDtl
	 * @param esigreqdetail_2_esigprocesstimerdtl
	 */
	public final void setESigReqDetail_2_ESigProcessTimerDtl(excr_commons_api.proxies.ESigReqDetail_2 esigreqdetail_2_esigprocesstimerdtl)
	{
		setESigReqDetail_2_ESigProcessTimerDtl(getContext(), esigreqdetail_2_esigprocesstimerdtl);
	}

	/**
	 * Set value of ESigReqDetail_2_ESigProcessTimerDtl
	 * @param context
	 * @param esigreqdetail_2_esigprocesstimerdtl
	 */
	public final void setESigReqDetail_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ESigReqDetail_2 esigreqdetail_2_esigprocesstimerdtl)
	{
		if (esigreqdetail_2_esigprocesstimerdtl == null) {
			getMendixObject().setValue(context, MemberNames.ESigReqDetail_2_ESigProcessTimerDtl.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ESigReqDetail_2_ESigProcessTimerDtl.toString(), esigreqdetail_2_esigprocesstimerdtl.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Meaning_2_ESigProcessTimerDtl
	 */
	public final excr_commons_api.proxies.Meaning_2 getMeaning_2_ESigProcessTimerDtl() throws com.mendix.core.CoreException
	{
		return getMeaning_2_ESigProcessTimerDtl(getContext());
	}

	/**
	 * @param context
	 * @return value of Meaning_2_ESigProcessTimerDtl
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.Meaning_2 getMeaning_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.Meaning_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Meaning_2_ESigProcessTimerDtl.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.Meaning_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Meaning_2_ESigProcessTimerDtl
	 * @param meaning_2_esigprocesstimerdtl
	 */
	public final void setMeaning_2_ESigProcessTimerDtl(excr_commons_api.proxies.Meaning_2 meaning_2_esigprocesstimerdtl)
	{
		setMeaning_2_ESigProcessTimerDtl(getContext(), meaning_2_esigprocesstimerdtl);
	}

	/**
	 * Set value of Meaning_2_ESigProcessTimerDtl
	 * @param context
	 * @param meaning_2_esigprocesstimerdtl
	 */
	public final void setMeaning_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.Meaning_2 meaning_2_esigprocesstimerdtl)
	{
		if (meaning_2_esigprocesstimerdtl == null) {
			getMendixObject().setValue(context, MemberNames.Meaning_2_ESigProcessTimerDtl.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Meaning_2_ESigProcessTimerDtl.toString(), meaning_2_esigprocesstimerdtl.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Role_2_ESigProcessTimerDtl
	 */
	public final excr_commons_api.proxies.Role_2 getRole_2_ESigProcessTimerDtl() throws com.mendix.core.CoreException
	{
		return getRole_2_ESigProcessTimerDtl(getContext());
	}

	/**
	 * @param context
	 * @return value of Role_2_ESigProcessTimerDtl
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.Role_2 getRole_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.Role_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Role_2_ESigProcessTimerDtl.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.Role_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Role_2_ESigProcessTimerDtl
	 * @param role_2_esigprocesstimerdtl
	 */
	public final void setRole_2_ESigProcessTimerDtl(excr_commons_api.proxies.Role_2 role_2_esigprocesstimerdtl)
	{
		setRole_2_ESigProcessTimerDtl(getContext(), role_2_esigprocesstimerdtl);
	}

	/**
	 * Set value of Role_2_ESigProcessTimerDtl
	 * @param context
	 * @param role_2_esigprocesstimerdtl
	 */
	public final void setRole_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.Role_2 role_2_esigprocesstimerdtl)
	{
		if (role_2_esigprocesstimerdtl == null) {
			getMendixObject().setValue(context, MemberNames.Role_2_ESigProcessTimerDtl.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Role_2_ESigProcessTimerDtl.toString(), role_2_esigprocesstimerdtl.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Spec_2_ESigProcessTimerDtl
	 */
	public final excr_commons_api.proxies.Spec_2 getSpec_2_ESigProcessTimerDtl() throws com.mendix.core.CoreException
	{
		return getSpec_2_ESigProcessTimerDtl(getContext());
	}

	/**
	 * @param context
	 * @return value of Spec_2_ESigProcessTimerDtl
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.Spec_2 getSpec_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.Spec_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Spec_2_ESigProcessTimerDtl.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.Spec_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Spec_2_ESigProcessTimerDtl
	 * @param spec_2_esigprocesstimerdtl
	 */
	public final void setSpec_2_ESigProcessTimerDtl(excr_commons_api.proxies.Spec_2 spec_2_esigprocesstimerdtl)
	{
		setSpec_2_ESigProcessTimerDtl(getContext(), spec_2_esigprocesstimerdtl);
	}

	/**
	 * Set value of Spec_2_ESigProcessTimerDtl
	 * @param context
	 * @param spec_2_esigprocesstimerdtl
	 */
	public final void setSpec_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.Spec_2 spec_2_esigprocesstimerdtl)
	{
		if (spec_2_esigprocesstimerdtl == null) {
			getMendixObject().setValue(context, MemberNames.Spec_2_ESigProcessTimerDtl.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Spec_2_ESigProcessTimerDtl.toString(), spec_2_esigprocesstimerdtl.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UOM_2_ESigProcessTimerDtl
	 */
	public final excr_commons_api.proxies.UOM_2 getUOM_2_ESigProcessTimerDtl() throws com.mendix.core.CoreException
	{
		return getUOM_2_ESigProcessTimerDtl(getContext());
	}

	/**
	 * @param context
	 * @return value of UOM_2_ESigProcessTimerDtl
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.UOM_2 getUOM_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.UOM_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UOM_2_ESigProcessTimerDtl.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.UOM_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UOM_2_ESigProcessTimerDtl
	 * @param uom_2_esigprocesstimerdtl
	 */
	public final void setUOM_2_ESigProcessTimerDtl(excr_commons_api.proxies.UOM_2 uom_2_esigprocesstimerdtl)
	{
		setUOM_2_ESigProcessTimerDtl(getContext(), uom_2_esigprocesstimerdtl);
	}

	/**
	 * Set value of UOM_2_ESigProcessTimerDtl
	 * @param context
	 * @param uom_2_esigprocesstimerdtl
	 */
	public final void setUOM_2_ESigProcessTimerDtl(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.UOM_2 uom_2_esigprocesstimerdtl)
	{
		if (uom_2_esigprocesstimerdtl == null) {
			getMendixObject().setValue(context, MemberNames.UOM_2_ESigProcessTimerDtl.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UOM_2_ESigProcessTimerDtl.toString(), uom_2_esigprocesstimerdtl.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ESigProcessTimerDtl_CaptureDetails
	 */
	public final excr_commons_api.proxies.CaptureDetails getESigProcessTimerDtl_CaptureDetails() throws com.mendix.core.CoreException
	{
		return getESigProcessTimerDtl_CaptureDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of ESigProcessTimerDtl_CaptureDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.CaptureDetails getESigProcessTimerDtl_CaptureDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.CaptureDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ESigProcessTimerDtl_CaptureDetails.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.CaptureDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ESigProcessTimerDtl_CaptureDetails
	 * @param esigprocesstimerdtl_capturedetails
	 */
	public final void setESigProcessTimerDtl_CaptureDetails(excr_commons_api.proxies.CaptureDetails esigprocesstimerdtl_capturedetails)
	{
		setESigProcessTimerDtl_CaptureDetails(getContext(), esigprocesstimerdtl_capturedetails);
	}

	/**
	 * Set value of ESigProcessTimerDtl_CaptureDetails
	 * @param context
	 * @param esigprocesstimerdtl_capturedetails
	 */
	public final void setESigProcessTimerDtl_CaptureDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.CaptureDetails esigprocesstimerdtl_capturedetails)
	{
		if (esigprocesstimerdtl_capturedetails == null) {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDtl_CaptureDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDtl_CaptureDetails.toString(), esigprocesstimerdtl_capturedetails.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return eSigProcessTimerDtlMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons_api.proxies.ESigProcessTimerDtl that = (excr_commons_api.proxies.ESigProcessTimerDtl) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
