// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons_api.proxies;

public class ESigProcessTimerDetail implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject eSigProcessTimerDetailMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons_API.ESigProcessTimerDetail";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_type("_odata_type"),
		ESigProcessTimerDetail_ESigProcessTimerDetails("EXCR_Commons_API.ESigProcessTimerDetail_ESigProcessTimerDetails"),
		ESigProcessTimerDtls_ESigProcessTimerDetail("EXCR_Commons_API.ESigProcessTimerDtls_ESigProcessTimerDetail"),
		ESigProcessTimerDetail_ESigProcessTimerRequirement("EXCR_Commons_API.ESigProcessTimerDetail_ESigProcessTimerRequirement");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ESigProcessTimerDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ESigProcessTimerDetail(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject eSigProcessTimerDetailMendixObject)
	{
		if (eSigProcessTimerDetailMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!eSigProcessTimerDetailMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.eSigProcessTimerDetailMendixObject = eSigProcessTimerDetailMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons_api.proxies.ESigProcessTimerDetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons_api.proxies.ESigProcessTimerDetail(context, mendixObject);
	}

	public static excr_commons_api.proxies.ESigProcessTimerDetail load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons_api.proxies.ESigProcessTimerDetail.initialize(context, mendixObject);
	}

	/**
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type()
	{
		return get_odata_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_type
	 */
	public final java.lang.String get_odata_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_type.toString());
	}

	/**
	 * Set value of _odata_type
	 * @param _odata_type
	 */
	public final void set_odata_type(java.lang.String _odata_type)
	{
		set_odata_type(getContext(), _odata_type);
	}

	/**
	 * Set value of _odata_type
	 * @param context
	 * @param _odata_type
	 */
	public final void set_odata_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_type)
	{
		getMendixObject().setValue(context, MemberNames._odata_type.toString(), _odata_type);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ESigProcessTimerDetail_ESigProcessTimerDetails
	 */
	public final excr_commons_api.proxies.ESigProcessTimerDetails getESigProcessTimerDetail_ESigProcessTimerDetails() throws com.mendix.core.CoreException
	{
		return getESigProcessTimerDetail_ESigProcessTimerDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of ESigProcessTimerDetail_ESigProcessTimerDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ESigProcessTimerDetails getESigProcessTimerDetail_ESigProcessTimerDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ESigProcessTimerDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ESigProcessTimerDetail_ESigProcessTimerDetails.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ESigProcessTimerDetails.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ESigProcessTimerDetail_ESigProcessTimerDetails
	 * @param esigprocesstimerdetail_esigprocesstimerdetails
	 */
	public final void setESigProcessTimerDetail_ESigProcessTimerDetails(excr_commons_api.proxies.ESigProcessTimerDetails esigprocesstimerdetail_esigprocesstimerdetails)
	{
		setESigProcessTimerDetail_ESigProcessTimerDetails(getContext(), esigprocesstimerdetail_esigprocesstimerdetails);
	}

	/**
	 * Set value of ESigProcessTimerDetail_ESigProcessTimerDetails
	 * @param context
	 * @param esigprocesstimerdetail_esigprocesstimerdetails
	 */
	public final void setESigProcessTimerDetail_ESigProcessTimerDetails(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ESigProcessTimerDetails esigprocesstimerdetail_esigprocesstimerdetails)
	{
		if (esigprocesstimerdetail_esigprocesstimerdetails == null) {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDetail_ESigProcessTimerDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDetail_ESigProcessTimerDetails.toString(), esigprocesstimerdetail_esigprocesstimerdetails.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ESigProcessTimerDtls_ESigProcessTimerDetail
	 */
	public final excr_commons_api.proxies.ESigProcessTimerDtls getESigProcessTimerDtls_ESigProcessTimerDetail() throws com.mendix.core.CoreException
	{
		return getESigProcessTimerDtls_ESigProcessTimerDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of ESigProcessTimerDtls_ESigProcessTimerDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ESigProcessTimerDtls getESigProcessTimerDtls_ESigProcessTimerDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ESigProcessTimerDtls result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ESigProcessTimerDtls_ESigProcessTimerDetail.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ESigProcessTimerDtls.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ESigProcessTimerDtls_ESigProcessTimerDetail
	 * @param esigprocesstimerdtls_esigprocesstimerdetail
	 */
	public final void setESigProcessTimerDtls_ESigProcessTimerDetail(excr_commons_api.proxies.ESigProcessTimerDtls esigprocesstimerdtls_esigprocesstimerdetail)
	{
		setESigProcessTimerDtls_ESigProcessTimerDetail(getContext(), esigprocesstimerdtls_esigprocesstimerdetail);
	}

	/**
	 * Set value of ESigProcessTimerDtls_ESigProcessTimerDetail
	 * @param context
	 * @param esigprocesstimerdtls_esigprocesstimerdetail
	 */
	public final void setESigProcessTimerDtls_ESigProcessTimerDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ESigProcessTimerDtls esigprocesstimerdtls_esigprocesstimerdetail)
	{
		if (esigprocesstimerdtls_esigprocesstimerdetail == null) {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDtls_ESigProcessTimerDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDtls_ESigProcessTimerDetail.toString(), esigprocesstimerdtls_esigprocesstimerdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ESigProcessTimerDetail_ESigProcessTimerRequirement
	 */
	public final excr_commons_api.proxies.ESigProcessTimerRequirement getESigProcessTimerDetail_ESigProcessTimerRequirement() throws com.mendix.core.CoreException
	{
		return getESigProcessTimerDetail_ESigProcessTimerRequirement(getContext());
	}

	/**
	 * @param context
	 * @return value of ESigProcessTimerDetail_ESigProcessTimerRequirement
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ESigProcessTimerRequirement getESigProcessTimerDetail_ESigProcessTimerRequirement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ESigProcessTimerRequirement result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ESigProcessTimerDetail_ESigProcessTimerRequirement.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ESigProcessTimerRequirement.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ESigProcessTimerDetail_ESigProcessTimerRequirement
	 * @param esigprocesstimerdetail_esigprocesstimerrequirement
	 */
	public final void setESigProcessTimerDetail_ESigProcessTimerRequirement(excr_commons_api.proxies.ESigProcessTimerRequirement esigprocesstimerdetail_esigprocesstimerrequirement)
	{
		setESigProcessTimerDetail_ESigProcessTimerRequirement(getContext(), esigprocesstimerdetail_esigprocesstimerrequirement);
	}

	/**
	 * Set value of ESigProcessTimerDetail_ESigProcessTimerRequirement
	 * @param context
	 * @param esigprocesstimerdetail_esigprocesstimerrequirement
	 */
	public final void setESigProcessTimerDetail_ESigProcessTimerRequirement(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ESigProcessTimerRequirement esigprocesstimerdetail_esigprocesstimerrequirement)
	{
		if (esigprocesstimerdetail_esigprocesstimerrequirement == null) {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDetail_ESigProcessTimerRequirement.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ESigProcessTimerDetail_ESigProcessTimerRequirement.toString(), esigprocesstimerdetail_esigprocesstimerrequirement.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return eSigProcessTimerDetailMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons_api.proxies.ESigProcessTimerDetail that = (excr_commons_api.proxies.ESigProcessTimerDetail) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
