// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons_api.proxies;

public class InputData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject inputDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons_API.InputData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InputData_ReqValidateESignatureRoot("EXCR_Commons_API.InputData_ReqValidateESignatureRoot"),
		Container_InputData("EXCR_Commons_API.Container_InputData"),
		InputData_ReqValidateESignatureTaskRoot("EXCR_Commons_API.InputData_ReqValidateESignatureTaskRoot"),
		Task_InputData("EXCR_Commons_API.Task_InputData"),
		TaskList_InputData("EXCR_Commons_API.TaskList_InputData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InputData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected InputData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject inputDataMendixObject)
	{
		if (inputDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!inputDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.inputDataMendixObject = inputDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons_api.proxies.InputData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons_api.proxies.InputData(context, mendixObject);
	}

	public static excr_commons_api.proxies.InputData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons_api.proxies.InputData.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InputData_ReqValidateESignatureRoot
	 */
	public final excr_commons_api.proxies.ReqValidateESignatureRoot getInputData_ReqValidateESignatureRoot() throws com.mendix.core.CoreException
	{
		return getInputData_ReqValidateESignatureRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of InputData_ReqValidateESignatureRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ReqValidateESignatureRoot getInputData_ReqValidateESignatureRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ReqValidateESignatureRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InputData_ReqValidateESignatureRoot.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ReqValidateESignatureRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InputData_ReqValidateESignatureRoot
	 * @param inputdata_reqvalidateesignatureroot
	 */
	public final void setInputData_ReqValidateESignatureRoot(excr_commons_api.proxies.ReqValidateESignatureRoot inputdata_reqvalidateesignatureroot)
	{
		setInputData_ReqValidateESignatureRoot(getContext(), inputdata_reqvalidateesignatureroot);
	}

	/**
	 * Set value of InputData_ReqValidateESignatureRoot
	 * @param context
	 * @param inputdata_reqvalidateesignatureroot
	 */
	public final void setInputData_ReqValidateESignatureRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ReqValidateESignatureRoot inputdata_reqvalidateesignatureroot)
	{
		if (inputdata_reqvalidateesignatureroot == null) {
			getMendixObject().setValue(context, MemberNames.InputData_ReqValidateESignatureRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InputData_ReqValidateESignatureRoot.toString(), inputdata_reqvalidateesignatureroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Container_InputData
	 */
	public final excr_commons_api.proxies.Container getContainer_InputData() throws com.mendix.core.CoreException
	{
		return getContainer_InputData(getContext());
	}

	/**
	 * @param context
	 * @return value of Container_InputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.Container getContainer_InputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.Container result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Container_InputData.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.Container.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Container_InputData
	 * @param container_inputdata
	 */
	public final void setContainer_InputData(excr_commons_api.proxies.Container container_inputdata)
	{
		setContainer_InputData(getContext(), container_inputdata);
	}

	/**
	 * Set value of Container_InputData
	 * @param context
	 * @param container_inputdata
	 */
	public final void setContainer_InputData(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.Container container_inputdata)
	{
		if (container_inputdata == null) {
			getMendixObject().setValue(context, MemberNames.Container_InputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Container_InputData.toString(), container_inputdata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InputData_ReqValidateESignatureTaskRoot
	 */
	public final excr_commons_api.proxies.ReqValidateESignatureTaskRoot getInputData_ReqValidateESignatureTaskRoot() throws com.mendix.core.CoreException
	{
		return getInputData_ReqValidateESignatureTaskRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of InputData_ReqValidateESignatureTaskRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ReqValidateESignatureTaskRoot getInputData_ReqValidateESignatureTaskRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ReqValidateESignatureTaskRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InputData_ReqValidateESignatureTaskRoot.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ReqValidateESignatureTaskRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InputData_ReqValidateESignatureTaskRoot
	 * @param inputdata_reqvalidateesignaturetaskroot
	 */
	public final void setInputData_ReqValidateESignatureTaskRoot(excr_commons_api.proxies.ReqValidateESignatureTaskRoot inputdata_reqvalidateesignaturetaskroot)
	{
		setInputData_ReqValidateESignatureTaskRoot(getContext(), inputdata_reqvalidateesignaturetaskroot);
	}

	/**
	 * Set value of InputData_ReqValidateESignatureTaskRoot
	 * @param context
	 * @param inputdata_reqvalidateesignaturetaskroot
	 */
	public final void setInputData_ReqValidateESignatureTaskRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ReqValidateESignatureTaskRoot inputdata_reqvalidateesignaturetaskroot)
	{
		if (inputdata_reqvalidateesignaturetaskroot == null) {
			getMendixObject().setValue(context, MemberNames.InputData_ReqValidateESignatureTaskRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InputData_ReqValidateESignatureTaskRoot.toString(), inputdata_reqvalidateesignaturetaskroot.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Task_InputData
	 */
	public final excr_commons_api.proxies.Task getTask_InputData() throws com.mendix.core.CoreException
	{
		return getTask_InputData(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_InputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.Task getTask_InputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_InputData.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.Task.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Task_InputData
	 * @param task_inputdata
	 */
	public final void setTask_InputData(excr_commons_api.proxies.Task task_inputdata)
	{
		setTask_InputData(getContext(), task_inputdata);
	}

	/**
	 * Set value of Task_InputData
	 * @param context
	 * @param task_inputdata
	 */
	public final void setTask_InputData(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.Task task_inputdata)
	{
		if (task_inputdata == null) {
			getMendixObject().setValue(context, MemberNames.Task_InputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Task_InputData.toString(), task_inputdata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskList_InputData
	 */
	public final excr_commons_api.proxies.TaskList getTaskList_InputData() throws com.mendix.core.CoreException
	{
		return getTaskList_InputData(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskList_InputData
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.TaskList getTaskList_InputData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.TaskList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskList_InputData.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.TaskList.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskList_InputData
	 * @param tasklist_inputdata
	 */
	public final void setTaskList_InputData(excr_commons_api.proxies.TaskList tasklist_inputdata)
	{
		setTaskList_InputData(getContext(), tasklist_inputdata);
	}

	/**
	 * Set value of TaskList_InputData
	 * @param context
	 * @param tasklist_inputdata
	 */
	public final void setTaskList_InputData(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.TaskList tasklist_inputdata)
	{
		if (tasklist_inputdata == null) {
			getMendixObject().setValue(context, MemberNames.TaskList_InputData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskList_InputData.toString(), tasklist_inputdata.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return inputDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons_api.proxies.InputData that = (excr_commons_api.proxies.InputData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
