// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons_api.proxies;

public class ReqVerifyPasswordSignatureRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reqVerifyPasswordSignatureRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons_API.ReqVerifyPasswordSignatureRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Event_ReqVerifyPasswordSignatureRoot("EXCR_Commons_API.Event_ReqVerifyPasswordSignatureRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReqVerifyPasswordSignatureRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ReqVerifyPasswordSignatureRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reqVerifyPasswordSignatureRootMendixObject)
	{
		if (reqVerifyPasswordSignatureRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!reqVerifyPasswordSignatureRootMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reqVerifyPasswordSignatureRootMendixObject = reqVerifyPasswordSignatureRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons_api.proxies.ReqVerifyPasswordSignatureRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons_api.proxies.ReqVerifyPasswordSignatureRoot(context, mendixObject);
	}

	public static excr_commons_api.proxies.ReqVerifyPasswordSignatureRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons_api.proxies.ReqVerifyPasswordSignatureRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Event_ReqVerifyPasswordSignatureRoot
	 */
	public final excr_commons_api.proxies.Event getEvent_ReqVerifyPasswordSignatureRoot() throws com.mendix.core.CoreException
	{
		return getEvent_ReqVerifyPasswordSignatureRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Event_ReqVerifyPasswordSignatureRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.Event getEvent_ReqVerifyPasswordSignatureRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.Event result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Event_ReqVerifyPasswordSignatureRoot.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.Event.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Event_ReqVerifyPasswordSignatureRoot
	 * @param event_reqverifypasswordsignatureroot
	 */
	public final void setEvent_ReqVerifyPasswordSignatureRoot(excr_commons_api.proxies.Event event_reqverifypasswordsignatureroot)
	{
		setEvent_ReqVerifyPasswordSignatureRoot(getContext(), event_reqverifypasswordsignatureroot);
	}

	/**
	 * Set value of Event_ReqVerifyPasswordSignatureRoot
	 * @param context
	 * @param event_reqverifypasswordsignatureroot
	 */
	public final void setEvent_ReqVerifyPasswordSignatureRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.Event event_reqverifypasswordsignatureroot)
	{
		if (event_reqverifypasswordsignatureroot == null) {
			getMendixObject().setValue(context, MemberNames.Event_ReqVerifyPasswordSignatureRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Event_ReqVerifyPasswordSignatureRoot.toString(), event_reqverifypasswordsignatureroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reqVerifyPasswordSignatureRootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons_api.proxies.ReqVerifyPasswordSignatureRoot that = (excr_commons_api.proxies.ReqVerifyPasswordSignatureRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
