// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons_api.proxies;

public class SVSpec implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sVSpecMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons_API.SVSpec";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		UseROR("UseROR"),
		SVSpec_ApiResSessionValues("EXCR_Commons_API.SVSpec_ApiResSessionValues"),
		SVSpec_ApiResSessionValues_List("EXCR_Commons_API.SVSpec_ApiResSessionValues_List");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SVSpec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SVSpec(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sVSpecMendixObject)
	{
		if (sVSpecMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!sVSpecMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sVSpecMendixObject = sVSpecMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons_api.proxies.SVSpec initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons_api.proxies.SVSpec(context, mendixObject);
	}

	public static excr_commons_api.proxies.SVSpec load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons_api.proxies.SVSpec.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of UseROR
	 */
	public final java.lang.Boolean getUseROR()
	{
		return getUseROR(getContext());
	}

	/**
	 * @param context
	 * @return value of UseROR
	 */
	public final java.lang.Boolean getUseROR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseROR.toString());
	}

	/**
	 * Set value of UseROR
	 * @param useror
	 */
	public final void setUseROR(java.lang.Boolean useror)
	{
		setUseROR(getContext(), useror);
	}

	/**
	 * Set value of UseROR
	 * @param context
	 * @param useror
	 */
	public final void setUseROR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useror)
	{
		getMendixObject().setValue(context, MemberNames.UseROR.toString(), useror);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SVSpec_ApiResSessionValues
	 */
	public final excr_commons_api.proxies.ApiResSessionValues getSVSpec_ApiResSessionValues() throws com.mendix.core.CoreException
	{
		return getSVSpec_ApiResSessionValues(getContext());
	}

	/**
	 * @param context
	 * @return value of SVSpec_ApiResSessionValues
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ApiResSessionValues getSVSpec_ApiResSessionValues(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ApiResSessionValues result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SVSpec_ApiResSessionValues.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ApiResSessionValues.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SVSpec_ApiResSessionValues
	 * @param svspec_apiressessionvalues
	 */
	public final void setSVSpec_ApiResSessionValues(excr_commons_api.proxies.ApiResSessionValues svspec_apiressessionvalues)
	{
		setSVSpec_ApiResSessionValues(getContext(), svspec_apiressessionvalues);
	}

	/**
	 * Set value of SVSpec_ApiResSessionValues
	 * @param context
	 * @param svspec_apiressessionvalues
	 */
	public final void setSVSpec_ApiResSessionValues(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ApiResSessionValues svspec_apiressessionvalues)
	{
		if (svspec_apiressessionvalues == null) {
			getMendixObject().setValue(context, MemberNames.SVSpec_ApiResSessionValues.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SVSpec_ApiResSessionValues.toString(), svspec_apiressessionvalues.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SVSpec_ApiResSessionValues_List
	 */
	public final excr_commons_api.proxies.ApiResSessionValues getSVSpec_ApiResSessionValues_List() throws com.mendix.core.CoreException
	{
		return getSVSpec_ApiResSessionValues_List(getContext());
	}

	/**
	 * @param context
	 * @return value of SVSpec_ApiResSessionValues_List
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons_api.proxies.ApiResSessionValues getSVSpec_ApiResSessionValues_List(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons_api.proxies.ApiResSessionValues result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SVSpec_ApiResSessionValues_List.toString());
		if (identifier != null) {
			result = excr_commons_api.proxies.ApiResSessionValues.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SVSpec_ApiResSessionValues_List
	 * @param svspec_apiressessionvalues_list
	 */
	public final void setSVSpec_ApiResSessionValues_List(excr_commons_api.proxies.ApiResSessionValues svspec_apiressessionvalues_list)
	{
		setSVSpec_ApiResSessionValues_List(getContext(), svspec_apiressessionvalues_list);
	}

	/**
	 * Set value of SVSpec_ApiResSessionValues_List
	 * @param context
	 * @param svspec_apiressessionvalues_list
	 */
	public final void setSVSpec_ApiResSessionValues_List(com.mendix.systemwideinterfaces.core.IContext context, excr_commons_api.proxies.ApiResSessionValues svspec_apiressessionvalues_list)
	{
		if (svspec_apiressessionvalues_list == null) {
			getMendixObject().setValue(context, MemberNames.SVSpec_ApiResSessionValues_List.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SVSpec_ApiResSessionValues_List.toString(), svspec_apiressessionvalues_list.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sVSpecMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons_api.proxies.SVSpec that = (excr_commons_api.proxies.SVSpec) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
