// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usercommons.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the UserCommons module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Claim_CreateBuilder(
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttribute
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.ACT_Claim_Create");
		builder = builder.withParam("ClaimEntityAttribute", _claimEntityAttribute);
		return builder;
	}

	public static void aCT_Claim_Create(
		IContext context,
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttribute
	)
	{
		aCT_Claim_CreateBuilder(
				_claimEntityAttribute
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Delete_ClaimEntityAttributeListBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.ACT_Delete_ClaimEntityAttributeList");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static void aCT_Delete_ClaimEntityAttributeList(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		aCT_Delete_ClaimEntityAttributeListBuilder(
				_userProvisioning
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Save_ClaimEntityAttributeBuilder(
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttributeMap
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.ACT_Save_ClaimEntityAttribute");
		builder = builder.withParam("ClaimEntityAttributeMap", _claimEntityAttributeMap);
		return builder;
	}

	public static void aCT_Save_ClaimEntityAttribute(
		IContext context,
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttributeMap
	)
	{
		aCT_Save_ClaimEntityAttributeBuilder(
				_claimEntityAttributeMap
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Save_ConfigurationBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.ACT_Save_Configuration");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static boolean aCT_Save_Configuration(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = aCT_Save_ConfigurationBuilder(
				_userProvisioning
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SelectClaim_ClaimEntityAttributeBuilder(
		usercommons.proxies.Claim _claim,
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttribute
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.ACT_SelectClaim_ClaimEntityAttribute");
		builder = builder.withParam("Claim", _claim);
		builder = builder.withParam("ClaimEntityAttribute", _claimEntityAttribute);
		return builder;
	}

	public static void aCT_SelectClaim_ClaimEntityAttribute(
		IContext context,
		usercommons.proxies.Claim _claim,
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttribute
	)
	{
		aCT_SelectClaim_ClaimEntityAttributeBuilder(
				_claim,
				_claimEntityAttribute
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bCo_UpdateFriendlyNameWhenEmptyBuilder(
		usercommons.proxies.Claim _claim
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.BCo_UpdateFriendlyNameWhenEmpty");
		builder = builder.withParam("Claim", _claim);
		return builder;
	}

	public static boolean bCo_UpdateFriendlyNameWhenEmpty(
		IContext context,
		usercommons.proxies.Claim _claim
	)
	{
		Object result = bCo_UpdateFriendlyNameWhenEmptyBuilder(
				_claim
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder create_ClaimEntityAttributeMapBuilder(
		java.lang.String _entityAttribute,
		java.lang.String _iDPAttribute,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.Create_ClaimEntityAttributeMap");
		builder = builder.withParam("EntityAttribute", _entityAttribute);
		builder = builder.withParam("IDPAttribute", _iDPAttribute);
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static usercommons.proxies.ClaimEntityAttribute create_ClaimEntityAttributeMap(
		IContext context,
		java.lang.String _entityAttribute,
		java.lang.String _iDPAttribute,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = create_ClaimEntityAttributeMapBuilder(
				_entityAttribute,
				_iDPAttribute,
				_userProvisioning
			)
			.execute(context);
		return result == null ? null : usercommons.proxies.ClaimEntityAttribute.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createClaimBuilder(
		java.lang.String _claimName,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.CreateClaim");
		builder = builder.withParam("ClaimName", _claimName);
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static usercommons.proxies.Claim createClaim(
		IContext context,
		java.lang.String _claimName,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = createClaimBuilder(
				_claimName,
				_userProvisioning
			)
			.execute(context);
		return result == null ? null : usercommons.proxies.Claim.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createClaimwithFriendlyNameBuilder(
		java.lang.String _claimName,
		usercommons.proxies.UserProvisioning _userProvisioning,
		java.lang.String _friendlyName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.CreateClaimwithFriendlyName");
		builder = builder.withParam("ClaimName", _claimName);
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		builder = builder.withParam("FriendlyName", _friendlyName);
		return builder;
	}

	public static usercommons.proxies.Claim createClaimwithFriendlyName(
		IContext context,
		java.lang.String _claimName,
		usercommons.proxies.UserProvisioning _userProvisioning,
		java.lang.String _friendlyName
	)
	{
		Object result = createClaimwithFriendlyNameBuilder(
				_claimName,
				_userProvisioning,
				_friendlyName
			)
			.execute(context);
		return result == null ? null : usercommons.proxies.Claim.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createOrUpdate_UserProvisioningBuilder(
		usercommons.proxies.UserProvisionAutoConfig _userProvisionAutoConfig,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.CreateOrUpdate_UserProvisioning");
		builder = builder.withParam("UserProvisionAutoConfig", _userProvisionAutoConfig);
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static usercommons.proxies.UserProvisioning createOrUpdate_UserProvisioning(
		IContext context,
		usercommons.proxies.UserProvisionAutoConfig _userProvisionAutoConfig,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = createOrUpdate_UserProvisioningBuilder(
				_userProvisionAutoConfig,
				_userProvisioning
			)
			.execute(context);
		return result == null ? null : usercommons.proxies.UserProvisioning.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createOrUpdateUserBuilder(
		usercommons.proxies.UserInfoParam _userInfoParameter
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.CreateOrUpdateUser");
		builder = builder.withParam("UserInfoParameter", _userInfoParameter);
		return builder;
	}

	public static system.proxies.User createOrUpdateUser(
		IContext context,
		usercommons.proxies.UserInfoParam _userInfoParameter
	)
	{
		Object result = createOrUpdateUserBuilder(
				_userInfoParameter
			)
			.execute(context);
		return result == null ? null : system.proxies.User.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_AvailableClaimsForUserProvisioningConfigBuilder(
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttribute
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.DS_AvailableClaimsForUserProvisioningConfig");
		builder = builder.withParam("ClaimEntityAttribute", _claimEntityAttribute);
		return builder;
	}

	public static java.util.List<usercommons.proxies.Claim> dS_AvailableClaimsForUserProvisioningConfig(
		IContext context,
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttribute
	)
	{
		Object result = dS_AvailableClaimsForUserProvisioningConfigBuilder(
				_claimEntityAttribute
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> usercommons.proxies.Claim.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetCustomEntityBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.DS_GetCustomEntity");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static java.util.List<usercommons.proxies.CustomEntity> dS_GetCustomEntity(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = dS_GetCustomEntityBuilder(
				_userProvisioning
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> usercommons.proxies.CustomEntity.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetCustomEntityMemberBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.DS_GetCustomEntityMember");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static java.util.List<usercommons.proxies.CustomEntityMember> dS_GetCustomEntityMember(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = dS_GetCustomEntityMemberBuilder(
				_userProvisioning
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> usercommons.proxies.CustomEntityMember.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetCustomEntityStringMemberBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.DS_GetCustomEntityStringMember");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static java.util.List<usercommons.proxies.CustomEntityMember> dS_GetCustomEntityStringMember(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = dS_GetCustomEntityStringMemberBuilder(
				_userProvisioning
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> usercommons.proxies.CustomEntityMember.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetCustomUserProvisioningBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.DS_GetCustomUserProvisioning");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static java.util.List<usercommons.proxies.CustomFlow> dS_GetCustomUserProvisioning(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = dS_GetCustomUserProvisioningBuilder(
				_userProvisioning
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> usercommons.proxies.CustomFlow.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder evaluateMultipleUserMatchesBuilder(
		usercommons.proxies.UserInfoParam _userInfoParam,
		java.util.List<system.proxies.User> _matchingUserList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.evaluateMultipleUserMatches");
		builder = builder.withParam("UserInfoParam", _userInfoParam);
		builder = builder.withParam("MatchingUserList", _matchingUserList);
		return builder;
	}

	public static system.proxies.User evaluateMultipleUserMatches(
		IContext context,
		usercommons.proxies.UserInfoParam _userInfoParam,
		java.util.List<system.proxies.User> _matchingUserList
	)
	{
		Object result = evaluateMultipleUserMatchesBuilder(
				_userInfoParam,
				_matchingUserList
			)
			.execute(context);
		return result == null ? null : system.proxies.User.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder inactiveUserBuilder(
		java.lang.String _username
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.InactiveUser");
		builder = builder.withParam("Username", _username);
		return builder;
	}

	public static void inactiveUser(
		IContext context,
		java.lang.String _username
	)
	{
		inactiveUserBuilder(
				_username
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCH_UpdateCustomMemberBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.OCH_UpdateCustomMember");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static void oCH_UpdateCustomMember(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		oCH_UpdateCustomMemberBuilder(
				_userProvisioning
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_CloseClaimNewEditBuilder(
		usercommons.proxies.Claim _claim
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.SUB_CloseClaimNewEdit");
		builder = builder.withParam("Claim", _claim);
		return builder;
	}

	public static void sUB_CloseClaimNewEdit(
		IContext context,
		usercommons.proxies.Claim _claim
	)
	{
		sUB_CloseClaimNewEditBuilder(
				_claim
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_GetUserTypeBuilder(
		java.lang.String _userType
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.SUB_GetUserType");
		builder = builder.withParam("UserType", _userType);
		return builder;
	}

	public static system.proxies.UserType sUB_GetUserType(
		IContext context,
		java.lang.String _userType
	)
	{
		Object result = sUB_GetUserTypeBuilder(
				_userType
			)
			.execute(context);
		return result == null ? null : system.proxies.UserType.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_handleUserProvisioningBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning,
		usercommons.proxies.Claim _claim,
		java.lang.String _principalMember,
		usercommons.proxies.UserProvisionAutoConfig _userProvisionAutoConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.SUB_handleUserProvisioning");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		builder = builder.withParam("Claim", _claim);
		builder = builder.withParam("PrincipalMember", _principalMember);
		builder = builder.withParam("UserProvisionAutoConfig", _userProvisionAutoConfig);
		return builder;
	}

	public static void sUB_handleUserProvisioning(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning,
		usercommons.proxies.Claim _claim,
		java.lang.String _principalMember,
		usercommons.proxies.UserProvisionAutoConfig _userProvisionAutoConfig
	)
	{
		sUB_handleUserProvisioningBuilder(
				_userProvisioning,
				_claim,
				_principalMember,
				_userProvisionAutoConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_RollbackUserProvisioningBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.SUB_RollbackUserProvisioning");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static void sUB_RollbackUserProvisioning(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		sUB_RollbackUserProvisioningBuilder(
				_userProvisioning
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UpdateClaimEntityAttributeMapBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning,
		java.util.List<usercommons.proxies.ClaimEntityAttribute> _claimEntityAttributeList,
		java.lang.String _principalMember,
		usercommons.proxies.Claim _idpAttribute
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.SUB_UpdateClaimEntityAttributeMap");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		builder = builder.withParam("ClaimEntityAttributeList", _claimEntityAttributeList);
		builder = builder.withParam("PrincipalMember", _principalMember);
		builder = builder.withParam("IdpAttribute", _idpAttribute);
		return builder;
	}

	public static void sUB_UpdateClaimEntityAttributeMap(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning,
		java.util.List<usercommons.proxies.ClaimEntityAttribute> _claimEntityAttributeList,
		java.lang.String _principalMember,
		usercommons.proxies.Claim _idpAttribute
	)
	{
		sUB_UpdateClaimEntityAttributeMapBuilder(
				_userProvisioning,
				_claimEntityAttributeList,
				_principalMember,
				_idpAttribute
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Val_ClaimEntityAttributeConfigurationBuilder(
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttribute
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.SUB_Val_ClaimEntityAttributeConfiguration");
		builder = builder.withParam("ClaimEntityAttribute", _claimEntityAttribute);
		return builder;
	}

	public static boolean sUB_Val_ClaimEntityAttributeConfiguration(
		IContext context,
		usercommons.proxies.ClaimEntityAttribute _claimEntityAttribute
	)
	{
		Object result = sUB_Val_ClaimEntityAttributeConfigurationBuilder(
				_claimEntityAttribute
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Val_PrincipalAttributeClaimConfigurationBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.SUB_Val_PrincipalAttributeClaimConfiguration");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static boolean sUB_Val_PrincipalAttributeClaimConfiguration(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = sUB_Val_PrincipalAttributeClaimConfigurationBuilder(
				_userProvisioning
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Val_ProvisioningConfigurationBuilder(
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.SUB_Val_ProvisioningConfiguration");
		builder = builder.withParam("UserProvisioning", _userProvisioning);
		return builder;
	}

	public static boolean sUB_Val_ProvisioningConfiguration(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioning
	)
	{
		Object result = sUB_Val_ProvisioningConfigurationBuilder(
				_userProvisioning
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Val_UserProvisioningConfigurationBuilder(
		usercommons.proxies.UserProvisioning _userProvisioningConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.SUB_Val_UserProvisioningConfiguration");
		builder = builder.withParam("UserProvisioningConfig", _userProvisioningConfig);
		return builder;
	}

	public static boolean sUB_Val_UserProvisioningConfiguration(
		IContext context,
		usercommons.proxies.UserProvisioning _userProvisioningConfig
	)
	{
		Object result = sUB_Val_UserProvisioningConfigurationBuilder(
				_userProvisioningConfig
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder user_Correct_UserTypeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.User_Correct_UserType");
		return builder;
	}

	public static java.util.List<usercommons.proxies.UserTypeReport> user_Correct_UserType(IContext context)
	{
		Object result = user_Correct_UserTypeBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> usercommons.proxies.UserTypeReport.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder user_RetrieveOrCreateUserReportInfoBuilder(
		system.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserCommons.User_RetrieveOrCreateUserReportInfo");
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static system.proxies.UserReportInfo user_RetrieveOrCreateUserReportInfo(
		IContext context,
		system.proxies.User _user
	)
	{
		Object result = user_RetrieveOrCreateUserReportInfoBuilder(
				_user
			)
			.execute(context);
		return result == null ? null : system.proxies.UserReportInfo.initialize(context, (IMendixObject) result);
	}
}
