// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;
import org.apache.pdfbox.rendering.ImageType;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.*;
import system.proxies.Image;
import com.mendix.systemwideinterfaces.core.UserAction;

public class PdfToImg extends UserAction<IMendixObject>
{
	/** @deprecated use PdfFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __PdfFile;
	private final system.proxies.FileDocument PdfFile;

	public PdfToImg(
		IContext context,
		IMendixObject _pdfFile
	)
	{
		super(context);
		this.__PdfFile = _pdfFile;
		this.PdfFile = _pdfFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _pdfFile);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (PdfFile == null)
			throw new RuntimeException("PdfFile is null.");

			try (InputStream pdfInputStream = Core.getFileDocumentContent(getContext(), PdfFile.getMendixObject());
			PDDocument document = PDDocument.load(pdfInputStream)) {

			PDFRenderer renderer = new PDFRenderer(document);
			BufferedImage bim = renderer.renderImageWithDPI(0, 200, ImageType.RGB); // first page

			ByteArrayOutputStream baos = new ByteArrayOutputStream();
			ImageIO.write(bim, "PNG", baos);
			baos.flush();
			ByteArrayInputStream imageInputStream = new ByteArrayInputStream(baos.toByteArray());

			IMendixObject imageObj = Core.instantiate(getContext(), Image.entityName);
			Core.storeFileDocumentContent(getContext(), imageObj, "first_page.png", imageInputStream);

			// Optional: Commit image if needed
			Core.commit(getContext(), imageObj);

			baos.close();
			return imageObj;

		} catch (Exception e) {
			Core.getLogger("PdfToImg").error("Error converting PDF to image: " + e.getMessage(), e);
			return null; // Return null if it fails
		}
		// throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PdfToImg";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
