// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_RegistrationStatus
{
	Registered("91782864-b672-4e6a-8c6a-951c7e216224"),
	Unregistered("0b58e982-e3f0-404d-8322-d72cdb8d1521");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_RegistrationStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
