// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sweetalert2.proxies;

public enum ENUM_SweetAlert2_Position
{
	top("d8859842-d934-4f14-9ea4-43a65de63fdd"),
	top_start("f830ac68-5773-4324-baaf-32e9046f72b0"),
	top_end("ab973307-d775-4909-b5be-6491c0454f92"),
	center("8560da22-ada0-4639-882d-f7edf0e80b3a"),
	center_start("211e0e42-1124-4d92-850f-5540183464a5"),
	center_end("948f88d4-0a28-4364-a886-9394ec804ffa"),
	bottom("32ed2460-6b71-4b63-9be5-28fcd23f7aa1"),
	bottom_start("fbc1e7b6-ae93-4b5d-8500-ac747497e78a"),
	bottom_end("ca070eaa-f6d4-407a-b156-364e1c27522a");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_SweetAlert2_Position(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
