// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sweetalert2.proxies;

public enum ENUM_SweetAlert2_AnimationExit
{
	animate__backOutDown("f7f47649-ff5e-4c16-90d9-ee09d04fc6df"),
	animate__backOutLeft("0c498641-5e07-4604-813b-27282bf0549e"),
	animate__backOutRight("bb151fa3-b54c-4ef9-ad26-14398b00d035"),
	animate__backOutUp("3aa0de91-6ea1-42b5-af26-d9fca32b3e6e"),
	animate__bounceOut("4def2b05-a8b8-4509-b963-9218ddb45694"),
	animate__bounceOutDown("e6c5e103-7e3c-486d-9320-0d860bb1f8d1"),
	animate__bounceOutLeft("62a62d80-bf21-4938-953a-5a1a27c7759b"),
	animate__bounceOutRight("d61db298-db06-46f0-8156-fa66ddd91842"),
	animate__bounceOutUp("682894c0-d327-425b-8448-938864e2f197"),
	animate__fadeOut("6ad3c9bf-0b41-4bb0-be34-7309d35c0d3c"),
	animate__fadeOutDown("824ce6b4-a983-4304-aca3-5bd9e4d4b251"),
	animate__fadeOutDownBig("dc9bc060-f975-49f3-a093-b10f92ee5f67"),
	animate__fadeOutLeft("723fb3a0-cac4-43d5-8751-f9d7bbf41578"),
	animate__fadeOutLeftBig("e9d56a4c-d1d8-4354-be93-d6067432305f"),
	animate__fadeOutRight("8224b663-049e-454a-935d-851e0e466c44"),
	animate__fadeOutRightBig("94bf2f03-be3f-4236-8257-141c235f76f4"),
	animate__fadeOutUp("175f0e8e-76d0-431c-ad9b-146e9b4a3658"),
	animate__fadeOutUpBig("c6313cd7-2886-43d6-9c06-d97a875dbf50"),
	animate__fadeOutTopLeft("f7f42009-80e4-4b33-bd15-7328bb2df50e"),
	animate__fadeOutTopRight("ef3676c6-d7c9-4eee-99b2-208b58d89080"),
	animate__fadeOutBottomLeft("55f23531-f02b-4e46-8096-c92ca85717fe"),
	animate__fadeOutBottomRight("f4fd18ec-e365-482a-b73b-8010f5ed7a82"),
	animate__flipOutX("c8d69c97-34db-4d40-9495-9f3d484088e6"),
	animate__flipOutY("e140a271-8100-4900-8c0d-a078860c1e14"),
	animate__lightSpeedOutRight("7ec5a7fe-5e7a-4143-800e-32d101932a2c"),
	animate__lightSpeedOutLeft("37dd74ab-cbde-4e7d-818c-d58a7fc37609"),
	animate__rotateOut("bdb961dd-347d-4b6c-b358-cee1b0c99406"),
	animate__rotateOutDownLeft("f640f7bc-db89-440d-8e2a-ca2b0042406f"),
	animate__rotateOutDownRight("0e14ae70-91bf-407b-ae04-4ff2ac964744"),
	animate__rotateOutUpLeft("e35bf0db-3f47-49b5-87fe-49bfe35b4c44"),
	animate__rotateOutUpRight("08e70d52-1010-4413-9163-67f7c46b6a81"),
	animate__hinge("1b9ad0ee-87ce-4dbc-8292-24579d40bd63"),
	animate__rollOut("c6cd8bf3-dba7-4c33-8652-02546e42b82d"),
	animate__zoomOut("719fb148-1248-4ddb-ab3a-4a7704c977ee"),
	animate__zoomOutDown("ab5a4f5a-b93e-48ce-bcef-8d47cbe1df57"),
	animate__zoomOutLeft("1eeaa646-90cb-4db1-bbae-0102d49125e7"),
	animate__zoomOutRight("9441340a-df79-47ed-a447-5f08a3c9bc70"),
	animate__zoomOutUp("acf51f3a-7898-4e20-9ce2-bb531cc6b53d"),
	animate__slideOutDown("37b709eb-8516-455a-a60a-d078b8a9bc73"),
	animate__slideOutLeft("f7c3bde6-b6e4-47db-9c75-95ae8c82862d"),
	animate__slideOutRight("94b55e0b-e77a-4594-8c36-cbe4fb084b9e"),
	animate__slideOutUp("89984711-0657-4bd1-876e-3ce65654d170");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_SweetAlert2_AnimationExit(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
