// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_extentityaccess.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the EXCR_ExtEntityAccess module

	public static java.lang.String getEntityFactoryURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EXCR_ExtEntityAccess.EntityFactoryURL");
	}
}