// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons.proxies;

public class DocumentHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject documentHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons.DocumentHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		showViewer("showViewer"),
		isListView("isListView");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocumentHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DocumentHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentHelperMendixObject)
	{
		if (documentHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!documentHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.documentHelperMendixObject = documentHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons.proxies.DocumentHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons.proxies.DocumentHelper(context, mendixObject);
	}

	public static excr_commons.proxies.DocumentHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons.proxies.DocumentHelper.initialize(context, mendixObject);
	}

	public static java.util.List<excr_commons.proxies.DocumentHelper> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> excr_commons.proxies.DocumentHelper.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of showViewer
	 */
	public final java.lang.Boolean getshowViewer()
	{
		return getshowViewer(getContext());
	}

	/**
	 * @param context
	 * @return value of showViewer
	 */
	public final java.lang.Boolean getshowViewer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.showViewer.toString());
	}

	/**
	 * Set value of showViewer
	 * @param showviewer
	 */
	public final void setshowViewer(java.lang.Boolean showviewer)
	{
		setshowViewer(getContext(), showviewer);
	}

	/**
	 * Set value of showViewer
	 * @param context
	 * @param showviewer
	 */
	public final void setshowViewer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showviewer)
	{
		getMendixObject().setValue(context, MemberNames.showViewer.toString(), showviewer);
	}

	/**
	 * @return value of isListView
	 */
	public final java.lang.Boolean getisListView()
	{
		return getisListView(getContext());
	}

	/**
	 * @param context
	 * @return value of isListView
	 */
	public final java.lang.Boolean getisListView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isListView.toString());
	}

	/**
	 * Set value of isListView
	 * @param islistview
	 */
	public final void setisListView(java.lang.Boolean islistview)
	{
		setisListView(getContext(), islistview);
	}

	/**
	 * Set value of isListView
	 * @param context
	 * @param islistview
	 */
	public final void setisListView(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islistview)
	{
		getMendixObject().setValue(context, MemberNames.isListView.toString(), islistview);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return documentHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons.proxies.DocumentHelper that = (excr_commons.proxies.DocumentHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
