// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons.proxies;

public class DropdownScannerHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dropdownScannerHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons.DropdownScannerHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ScannerString("ScannerString"),
		Attribute("Attribute"),
		ObjectGUID("ObjectGUID"),
		DropdownScannerHelper_ContainerHoldContext("EXCR_Commons.DropdownScannerHelper_ContainerHoldContext"),
		DropdownScannerHelper_ContainerReleaseContext("EXCR_Commons.DropdownScannerHelper_ContainerReleaseContext"),
		DropdownScannerHelper_ResourceSetupModel("EXCR_Commons.DropdownScannerHelper_ResourceSetupModel"),
		DropdownScannerHelper_ComponentIssueMaterialDetail("EXCR_Commons.DropdownScannerHelper_ComponentIssueMaterialDetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DropdownScannerHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DropdownScannerHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dropdownScannerHelperMendixObject)
	{
		if (dropdownScannerHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!dropdownScannerHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dropdownScannerHelperMendixObject = dropdownScannerHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons.proxies.DropdownScannerHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons.proxies.DropdownScannerHelper(context, mendixObject);
	}

	public static excr_commons.proxies.DropdownScannerHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons.proxies.DropdownScannerHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of ScannerString
	 */
	public final java.lang.String getScannerString()
	{
		return getScannerString(getContext());
	}

	/**
	 * @param context
	 * @return value of ScannerString
	 */
	public final java.lang.String getScannerString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ScannerString.toString());
	}

	/**
	 * Set value of ScannerString
	 * @param scannerstring
	 */
	public final void setScannerString(java.lang.String scannerstring)
	{
		setScannerString(getContext(), scannerstring);
	}

	/**
	 * Set value of ScannerString
	 * @param context
	 * @param scannerstring
	 */
	public final void setScannerString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scannerstring)
	{
		getMendixObject().setValue(context, MemberNames.ScannerString.toString(), scannerstring);
	}

	/**
	 * @return value of Attribute
	 */
	public final java.lang.String getAttribute()
	{
		return getAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute
	 */
	public final java.lang.String getAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute.toString());
	}

	/**
	 * Set value of Attribute
	 * @param attribute
	 */
	public final void setAttribute(java.lang.String attribute)
	{
		setAttribute(getContext(), attribute);
	}

	/**
	 * Set value of Attribute
	 * @param context
	 * @param attribute
	 */
	public final void setAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute)
	{
		getMendixObject().setValue(context, MemberNames.Attribute.toString(), attribute);
	}

	/**
	 * @return value of ObjectGUID
	 */
	public final java.lang.String getObjectGUID()
	{
		return getObjectGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectGUID
	 */
	public final java.lang.String getObjectGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectGUID.toString());
	}

	/**
	 * Set value of ObjectGUID
	 * @param objectguid
	 */
	public final void setObjectGUID(java.lang.String objectguid)
	{
		setObjectGUID(getContext(), objectguid);
	}

	/**
	 * Set value of ObjectGUID
	 * @param context
	 * @param objectguid
	 */
	public final void setObjectGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objectguid)
	{
		getMendixObject().setValue(context, MemberNames.ObjectGUID.toString(), objectguid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DropdownScannerHelper_ContainerHoldContext
	 */
	public final excr_resourcemanagement.proxies.ContainerHoldContext getDropdownScannerHelper_ContainerHoldContext() throws com.mendix.core.CoreException
	{
		return getDropdownScannerHelper_ContainerHoldContext(getContext());
	}

	/**
	 * @param context
	 * @return value of DropdownScannerHelper_ContainerHoldContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ContainerHoldContext getDropdownScannerHelper_ContainerHoldContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ContainerHoldContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DropdownScannerHelper_ContainerHoldContext.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ContainerHoldContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DropdownScannerHelper_ContainerHoldContext
	 * @param dropdownscannerhelper_containerholdcontext
	 */
	public final void setDropdownScannerHelper_ContainerHoldContext(excr_resourcemanagement.proxies.ContainerHoldContext dropdownscannerhelper_containerholdcontext)
	{
		setDropdownScannerHelper_ContainerHoldContext(getContext(), dropdownscannerhelper_containerholdcontext);
	}

	/**
	 * Set value of DropdownScannerHelper_ContainerHoldContext
	 * @param context
	 * @param dropdownscannerhelper_containerholdcontext
	 */
	public final void setDropdownScannerHelper_ContainerHoldContext(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ContainerHoldContext dropdownscannerhelper_containerholdcontext)
	{
		if (dropdownscannerhelper_containerholdcontext == null) {
			getMendixObject().setValue(context, MemberNames.DropdownScannerHelper_ContainerHoldContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DropdownScannerHelper_ContainerHoldContext.toString(), dropdownscannerhelper_containerholdcontext.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DropdownScannerHelper_ContainerReleaseContext
	 */
	public final excr_resourcemanagement.proxies.ContainerReleaseContext getDropdownScannerHelper_ContainerReleaseContext() throws com.mendix.core.CoreException
	{
		return getDropdownScannerHelper_ContainerReleaseContext(getContext());
	}

	/**
	 * @param context
	 * @return value of DropdownScannerHelper_ContainerReleaseContext
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ContainerReleaseContext getDropdownScannerHelper_ContainerReleaseContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ContainerReleaseContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DropdownScannerHelper_ContainerReleaseContext.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ContainerReleaseContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DropdownScannerHelper_ContainerReleaseContext
	 * @param dropdownscannerhelper_containerreleasecontext
	 */
	public final void setDropdownScannerHelper_ContainerReleaseContext(excr_resourcemanagement.proxies.ContainerReleaseContext dropdownscannerhelper_containerreleasecontext)
	{
		setDropdownScannerHelper_ContainerReleaseContext(getContext(), dropdownscannerhelper_containerreleasecontext);
	}

	/**
	 * Set value of DropdownScannerHelper_ContainerReleaseContext
	 * @param context
	 * @param dropdownscannerhelper_containerreleasecontext
	 */
	public final void setDropdownScannerHelper_ContainerReleaseContext(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ContainerReleaseContext dropdownscannerhelper_containerreleasecontext)
	{
		if (dropdownscannerhelper_containerreleasecontext == null) {
			getMendixObject().setValue(context, MemberNames.DropdownScannerHelper_ContainerReleaseContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DropdownScannerHelper_ContainerReleaseContext.toString(), dropdownscannerhelper_containerreleasecontext.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DropdownScannerHelper_ResourceSetupModel
	 */
	public final excr_resourcemanagement.proxies.ResourceSetupModel getDropdownScannerHelper_ResourceSetupModel() throws com.mendix.core.CoreException
	{
		return getDropdownScannerHelper_ResourceSetupModel(getContext());
	}

	/**
	 * @param context
	 * @return value of DropdownScannerHelper_ResourceSetupModel
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ResourceSetupModel getDropdownScannerHelper_ResourceSetupModel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ResourceSetupModel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DropdownScannerHelper_ResourceSetupModel.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ResourceSetupModel.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DropdownScannerHelper_ResourceSetupModel
	 * @param dropdownscannerhelper_resourcesetupmodel
	 */
	public final void setDropdownScannerHelper_ResourceSetupModel(excr_resourcemanagement.proxies.ResourceSetupModel dropdownscannerhelper_resourcesetupmodel)
	{
		setDropdownScannerHelper_ResourceSetupModel(getContext(), dropdownscannerhelper_resourcesetupmodel);
	}

	/**
	 * Set value of DropdownScannerHelper_ResourceSetupModel
	 * @param context
	 * @param dropdownscannerhelper_resourcesetupmodel
	 */
	public final void setDropdownScannerHelper_ResourceSetupModel(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ResourceSetupModel dropdownscannerhelper_resourcesetupmodel)
	{
		if (dropdownscannerhelper_resourcesetupmodel == null) {
			getMendixObject().setValue(context, MemberNames.DropdownScannerHelper_ResourceSetupModel.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DropdownScannerHelper_ResourceSetupModel.toString(), dropdownscannerhelper_resourcesetupmodel.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DropdownScannerHelper_ComponentIssueMaterialDetail
	 */
	public final excr_resourcemanagement.proxies.ComponentIssueMaterialDetail getDropdownScannerHelper_ComponentIssueMaterialDetail() throws com.mendix.core.CoreException
	{
		return getDropdownScannerHelper_ComponentIssueMaterialDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of DropdownScannerHelper_ComponentIssueMaterialDetail
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_resourcemanagement.proxies.ComponentIssueMaterialDetail getDropdownScannerHelper_ComponentIssueMaterialDetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_resourcemanagement.proxies.ComponentIssueMaterialDetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DropdownScannerHelper_ComponentIssueMaterialDetail.toString());
		if (identifier != null) {
			result = excr_resourcemanagement.proxies.ComponentIssueMaterialDetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DropdownScannerHelper_ComponentIssueMaterialDetail
	 * @param dropdownscannerhelper_componentissuematerialdetail
	 */
	public final void setDropdownScannerHelper_ComponentIssueMaterialDetail(excr_resourcemanagement.proxies.ComponentIssueMaterialDetail dropdownscannerhelper_componentissuematerialdetail)
	{
		setDropdownScannerHelper_ComponentIssueMaterialDetail(getContext(), dropdownscannerhelper_componentissuematerialdetail);
	}

	/**
	 * Set value of DropdownScannerHelper_ComponentIssueMaterialDetail
	 * @param context
	 * @param dropdownscannerhelper_componentissuematerialdetail
	 */
	public final void setDropdownScannerHelper_ComponentIssueMaterialDetail(com.mendix.systemwideinterfaces.core.IContext context, excr_resourcemanagement.proxies.ComponentIssueMaterialDetail dropdownscannerhelper_componentissuematerialdetail)
	{
		if (dropdownscannerhelper_componentissuematerialdetail == null) {
			getMendixObject().setValue(context, MemberNames.DropdownScannerHelper_ComponentIssueMaterialDetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DropdownScannerHelper_ComponentIssueMaterialDetail.toString(), dropdownscannerhelper_componentissuematerialdetail.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dropdownScannerHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons.proxies.DropdownScannerHelper that = (excr_commons.proxies.DropdownScannerHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
