// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons.proxies;

public class ErrorDetail implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject errorDetailMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons.ErrorDetail";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Message("Message"),
		ErrorCode("ErrorCode"),
		ErrorDetail_HttpErrorRoot("EXCR_Commons.ErrorDetail_HttpErrorRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ErrorDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ErrorDetail(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject errorDetailMendixObject)
	{
		if (errorDetailMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!errorDetailMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.errorDetailMendixObject = errorDetailMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons.proxies.ErrorDetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons.proxies.ErrorDetail(context, mendixObject);
	}

	public static excr_commons.proxies.ErrorDetail load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons.proxies.ErrorDetail.initialize(context, mendixObject);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return value of ErrorCode
	 */
	public final java.lang.String getErrorCode()
	{
		return getErrorCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorCode
	 */
	public final java.lang.String getErrorCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ErrorCode.toString());
	}

	/**
	 * Set value of ErrorCode
	 * @param errorcode
	 */
	public final void setErrorCode(java.lang.String errorcode)
	{
		setErrorCode(getContext(), errorcode);
	}

	/**
	 * Set value of ErrorCode
	 * @param context
	 * @param errorcode
	 */
	public final void setErrorCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errorcode)
	{
		getMendixObject().setValue(context, MemberNames.ErrorCode.toString(), errorcode);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ErrorDetail_HttpErrorRoot
	 */
	public final excr_commons.proxies.HttpErrorRoot getErrorDetail_HttpErrorRoot() throws com.mendix.core.CoreException
	{
		return getErrorDetail_HttpErrorRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorDetail_HttpErrorRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final excr_commons.proxies.HttpErrorRoot getErrorDetail_HttpErrorRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excr_commons.proxies.HttpErrorRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ErrorDetail_HttpErrorRoot.toString());
		if (identifier != null) {
			result = excr_commons.proxies.HttpErrorRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ErrorDetail_HttpErrorRoot
	 * @param errordetail_httperrorroot
	 */
	public final void setErrorDetail_HttpErrorRoot(excr_commons.proxies.HttpErrorRoot errordetail_httperrorroot)
	{
		setErrorDetail_HttpErrorRoot(getContext(), errordetail_httperrorroot);
	}

	/**
	 * Set value of ErrorDetail_HttpErrorRoot
	 * @param context
	 * @param errordetail_httperrorroot
	 */
	public final void setErrorDetail_HttpErrorRoot(com.mendix.systemwideinterfaces.core.IContext context, excr_commons.proxies.HttpErrorRoot errordetail_httperrorroot)
	{
		if (errordetail_httperrorroot == null) {
			getMendixObject().setValue(context, MemberNames.ErrorDetail_HttpErrorRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ErrorDetail_HttpErrorRoot.toString(), errordetail_httperrorroot.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return errorDetailMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons.proxies.ErrorDetail that = (excr_commons.proxies.ErrorDetail) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
