// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_commons.proxies;

public class MenuContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject menuContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_Commons.MenuContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsAdmin("IsAdmin"),
		ShowHamburgerButton("ShowHamburgerButton"),
		ShowMenuItems("ShowMenuItems"),
		ContainerName("ContainerName"),
		ShowHoldContainerMenu("ShowHoldContainerMenu"),
		ShowReleaseContainerMenu("ShowReleaseContainerMenu");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MenuContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MenuContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject menuContextMendixObject)
	{
		if (menuContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!menuContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.menuContextMendixObject = menuContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_commons.proxies.MenuContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_commons.proxies.MenuContext(context, mendixObject);
	}

	public static excr_commons.proxies.MenuContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_commons.proxies.MenuContext.initialize(context, mendixObject);
	}

	public static java.util.List<excr_commons.proxies.MenuContext> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> excr_commons.proxies.MenuContext.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of IsAdmin
	 */
	public final java.lang.Boolean getIsAdmin()
	{
		return getIsAdmin(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAdmin
	 */
	public final java.lang.Boolean getIsAdmin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAdmin.toString());
	}

	/**
	 * Set value of IsAdmin
	 * @param isadmin
	 */
	public final void setIsAdmin(java.lang.Boolean isadmin)
	{
		setIsAdmin(getContext(), isadmin);
	}

	/**
	 * Set value of IsAdmin
	 * @param context
	 * @param isadmin
	 */
	public final void setIsAdmin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isadmin)
	{
		getMendixObject().setValue(context, MemberNames.IsAdmin.toString(), isadmin);
	}

	/**
	 * @return value of ShowHamburgerButton
	 */
	public final java.lang.Boolean getShowHamburgerButton()
	{
		return getShowHamburgerButton(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowHamburgerButton
	 */
	public final java.lang.Boolean getShowHamburgerButton(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowHamburgerButton.toString());
	}

	/**
	 * Set value of ShowHamburgerButton
	 * @param showhamburgerbutton
	 */
	public final void setShowHamburgerButton(java.lang.Boolean showhamburgerbutton)
	{
		setShowHamburgerButton(getContext(), showhamburgerbutton);
	}

	/**
	 * Set value of ShowHamburgerButton
	 * @param context
	 * @param showhamburgerbutton
	 */
	public final void setShowHamburgerButton(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showhamburgerbutton)
	{
		getMendixObject().setValue(context, MemberNames.ShowHamburgerButton.toString(), showhamburgerbutton);
	}

	/**
	 * @return value of ShowMenuItems
	 */
	public final java.lang.Boolean getShowMenuItems()
	{
		return getShowMenuItems(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowMenuItems
	 */
	public final java.lang.Boolean getShowMenuItems(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowMenuItems.toString());
	}

	/**
	 * Set value of ShowMenuItems
	 * @param showmenuitems
	 */
	public final void setShowMenuItems(java.lang.Boolean showmenuitems)
	{
		setShowMenuItems(getContext(), showmenuitems);
	}

	/**
	 * Set value of ShowMenuItems
	 * @param context
	 * @param showmenuitems
	 */
	public final void setShowMenuItems(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showmenuitems)
	{
		getMendixObject().setValue(context, MemberNames.ShowMenuItems.toString(), showmenuitems);
	}

	/**
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName()
	{
		return getContainerName(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContainerName.toString());
	}

	/**
	 * Set value of ContainerName
	 * @param containername
	 */
	public final void setContainerName(java.lang.String containername)
	{
		setContainerName(getContext(), containername);
	}

	/**
	 * Set value of ContainerName
	 * @param context
	 * @param containername
	 */
	public final void setContainerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String containername)
	{
		getMendixObject().setValue(context, MemberNames.ContainerName.toString(), containername);
	}

	/**
	 * @return value of ShowHoldContainerMenu
	 */
	public final java.lang.Boolean getShowHoldContainerMenu()
	{
		return getShowHoldContainerMenu(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowHoldContainerMenu
	 */
	public final java.lang.Boolean getShowHoldContainerMenu(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowHoldContainerMenu.toString());
	}

	/**
	 * Set value of ShowHoldContainerMenu
	 * @param showholdcontainermenu
	 */
	public final void setShowHoldContainerMenu(java.lang.Boolean showholdcontainermenu)
	{
		setShowHoldContainerMenu(getContext(), showholdcontainermenu);
	}

	/**
	 * Set value of ShowHoldContainerMenu
	 * @param context
	 * @param showholdcontainermenu
	 */
	public final void setShowHoldContainerMenu(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showholdcontainermenu)
	{
		getMendixObject().setValue(context, MemberNames.ShowHoldContainerMenu.toString(), showholdcontainermenu);
	}

	/**
	 * @return value of ShowReleaseContainerMenu
	 */
	public final java.lang.Boolean getShowReleaseContainerMenu()
	{
		return getShowReleaseContainerMenu(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowReleaseContainerMenu
	 */
	public final java.lang.Boolean getShowReleaseContainerMenu(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowReleaseContainerMenu.toString());
	}

	/**
	 * Set value of ShowReleaseContainerMenu
	 * @param showreleasecontainermenu
	 */
	public final void setShowReleaseContainerMenu(java.lang.Boolean showreleasecontainermenu)
	{
		setShowReleaseContainerMenu(getContext(), showreleasecontainermenu);
	}

	/**
	 * Set value of ShowReleaseContainerMenu
	 * @param context
	 * @param showreleasecontainermenu
	 */
	public final void setShowReleaseContainerMenu(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showreleasecontainermenu)
	{
		getMendixObject().setValue(context, MemberNames.ShowReleaseContainerMenu.toString(), showreleasecontainermenu);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return menuContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_commons.proxies.MenuContext that = (excr_commons.proxies.MenuContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
