// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("c9101b97-af38-42cd-bf17-c820e4d877b4"),
	Debug("aa4cfe1c-9d0a-4350-9c18-c5c85f9803eb"),
	Info("bc504efd-e576-4f9b-b0df-a08a12290cf8"),
	Warning("40f55e4b-d0b7-4fe4-9a96-329b10d95189"),
	Error("f8854116-a64a-419b-abca-5f837e867046"),
	Critical("94a020f0-d90b-4051-ac8c-955e461c3bfa");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
