// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("a8c518fd-7b02-429c-8d49-3c56a4946098"),
	FORMATTING("f1e7438b-c194-4f09-891b-e66020bfb7eb"),
	IMAGES("e0244f59-875f-4fdb-93b7-a2773095a02e"),
	LINKS("f57c79e4-e911-44cd-bf30-460cef17823a"),
	STYLES("bb82c302-840f-4fed-b195-1da9284570b7"),
	TABLES("a30b97f9-702a-464a-b8a5-3fe45955f146");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
