// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("7f697e6b-124d-4bd6-96e3-4ecb62505c2e"),
	ISO_8859_1("083144e8-661a-482d-b9ea-0db46aa1fb24"),
	UTF_8("41dcb269-a392-4065-b5ff-53404cb762e1"),
	UTF_16BE("5ffb9e6d-6875-4f6e-8ecd-c6671d9f576e"),
	UTF_16LE("3183a5b5-968d-47eb-bbcf-2f45f0359d87"),
	UTF_16("b694bd77-89d5-4154-bfcb-87ab5f5aac4a");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
