// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_eprocedure.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the EXCR_EProcedure module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_EProcedure_DownloadDocs_IfPresentBuilder(
		java.lang.String _documentName,
		java.lang.String _documentRevision,
		java.lang.String _documentIdentifier,
		java.lang.String _displayName,
		boolean _showPreview
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.ACT_EProcedure_DownloadDocs_IfPresent");
		builder = builder.withParam("DocumentName", _documentName);
		builder = builder.withParam("DocumentRevision", _documentRevision);
		builder = builder.withParam("DocumentIdentifier", _documentIdentifier);
		builder = builder.withParam("DisplayName", _displayName);
		builder = builder.withParam("ShowPreview", _showPreview);
		return builder;
	}

	public static excr_commons.proxies.Notification aCT_EProcedure_DownloadDocs_IfPresent(
		IContext context,
		java.lang.String _documentName,
		java.lang.String _documentRevision,
		java.lang.String _documentIdentifier,
		java.lang.String _displayName,
		boolean _showPreview
	)
	{
		Object result = aCT_EProcedure_DownloadDocs_IfPresentBuilder(
				_documentName,
				_documentRevision,
				_documentIdentifier,
				_displayName,
				_showPreview
			)
			.execute(context);
		return result == null ? null : excr_commons.proxies.Notification.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_EProcedure_GetOtherDocsBuilder(
		excr_eprocedure.proxies.EProcedureContext _eProcedureContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.ACT_EProcedure_GetOtherDocs");
		builder = builder.withParam("EProcedureContext", _eProcedureContext);
		return builder;
	}

	public static java.util.List<excr_eprocedure.proxies.Document> aCT_EProcedure_GetOtherDocs(
		IContext context,
		excr_eprocedure.proxies.EProcedureContext _eProcedureContext
	)
	{
		Object result = aCT_EProcedure_GetOtherDocsBuilder(
				_eProcedureContext
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> excr_eprocedure.proxies.Document.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_EProcedure_GetTaskDocsBuilder(
		excr_eprocedure.proxies.EProcedureContext _eProcedureContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.ACT_EProcedure_GetTaskDocs");
		builder = builder.withParam("EProcedureContext", _eProcedureContext);
		return builder;
	}

	public static java.util.List<excr_eprocedure.proxies.Document> aCT_EProcedure_GetTaskDocs(
		IContext context,
		excr_eprocedure.proxies.EProcedureContext _eProcedureContext
	)
	{
		Object result = aCT_EProcedure_GetTaskDocsBuilder(
				_eProcedureContext
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> excr_eprocedure.proxies.Document.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_EProcedure_SetTempConfigObjectBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.ACT_EProcedure_SetTempConfigObject");
		return builder;
	}

	public static excr_eprocedure.proxies.TempConfig aCT_EProcedure_SetTempConfigObject(IContext context)
	{
		Object result = aCT_EProcedure_SetTempConfigObjectBuilder().execute(context);
		return result == null ? null : excr_eprocedure.proxies.TempConfig.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_EProcedure_UpdateMenuContextForContainerBuilder(
		excr_eprocedure.proxies.EProcedureContext _eProcedureContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.ACT_EProcedure_UpdateMenuContextForContainer");
		builder = builder.withParam("EProcedureContext", _eProcedureContext);
		return builder;
	}

	public static void aCT_EProcedure_UpdateMenuContextForContainer(
		IContext context,
		excr_eprocedure.proxies.EProcedureContext _eProcedureContext
	)
	{
		aCT_EProcedure_UpdateMenuContextForContainerBuilder(
				_eProcedureContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GroupOnlineQueryParametersBuilder(
		excr_eprocedure.proxies.OnlineQuerySnippetContext _onlineQuerySnippetContext,
		java.util.List<excr_eprocedure_api.proxies.ExecuteTaskResponse> _executeTaskResponseList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.ACT_GroupOnlineQueryParameters");
		builder = builder.withParam("OnlineQuerySnippetContext", _onlineQuerySnippetContext);
		builder = builder.withParam("ExecuteTaskResponseList", _executeTaskResponseList);
		return builder;
	}

	public static void aCT_GroupOnlineQueryParameters(
		IContext context,
		excr_eprocedure.proxies.OnlineQuerySnippetContext _onlineQuerySnippetContext,
		java.util.List<excr_eprocedure_api.proxies.ExecuteTaskResponse> _executeTaskResponseList
	)
	{
		aCT_GroupOnlineQueryParametersBuilder(
				_onlineQuerySnippetContext,
				_executeTaskResponseList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_PrepareDynamicGridBuilder(
		excr_eprocedure.proxies.OnlineQuerySnippetContext _onlineQuerySnippetContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.ACT_PrepareDynamicGrid");
		builder = builder.withParam("OnlineQuerySnippetContext", _onlineQuerySnippetContext);
		return builder;
	}

	public static excr_eprocedure.proxies.OnlineQuerySnippetContext aCT_PrepareDynamicGrid(
		IContext context,
		excr_eprocedure.proxies.OnlineQuerySnippetContext _onlineQuerySnippetContext
	)
	{
		Object result = aCT_PrepareDynamicGridBuilder(
				_onlineQuerySnippetContext
			)
			.execute(context);
		return result == null ? null : excr_eprocedure.proxies.OnlineQuerySnippetContext.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ShowCompRemoveReplaceBuilder(
		excr_eprocedure.proxies.EProcedureContext _eProcedureContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.ACT_ShowCompRemoveReplace");
		builder = builder.withParam("EProcedureContext", _eProcedureContext);
		return builder;
	}

	public static excr_component.proxies.ComponentTxnContext aCT_ShowCompRemoveReplace(
		IContext context,
		excr_eprocedure.proxies.EProcedureContext _eProcedureContext
	)
	{
		Object result = aCT_ShowCompRemoveReplaceBuilder(
				_eProcedureContext
			)
			.execute(context);
		return result == null ? null : excr_component.proxies.ComponentTxnContext.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder get_DocumentIcon_ByExtensionBuilder(
		java.lang.String _documentIdentifier
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.Get_DocumentIcon_ByExtension");
		builder = builder.withParam("DocumentIdentifier", _documentIdentifier);
		return builder;
	}

	public static java.lang.String get_DocumentIcon_ByExtension(
		IContext context,
		java.lang.String _documentIdentifier
	)
	{
		Object result = get_DocumentIcon_ByExtensionBuilder(
				_documentIdentifier
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pUT_Workstations_FetchBuilder(
		excr_eprocedure_api.proxies.ResTaskFromTaskListJsonObject _resTaskFromTaskListJsonObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.PUT_Workstations_Fetch");
		builder = builder.withParam("ResTaskFromTaskListJsonObject", _resTaskFromTaskListJsonObject);
		return builder;
	}

	public static java.util.List<excr_eprocedure_api.proxies.WorkstationJsonObject> pUT_Workstations_Fetch(
		IContext context,
		excr_eprocedure_api.proxies.ResTaskFromTaskListJsonObject _resTaskFromTaskListJsonObject
	)
	{
		Object result = pUT_Workstations_FetchBuilder(
				_resTaskFromTaskListJsonObject
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> excr_eprocedure_api.proxies.WorkstationJsonObject.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Eprocedure_CollectDataBuilder(
		java.lang.String _requestBody,
		java.lang.String _containerName,
		java.lang.String _dataCollectionName,
		java.lang.String _comments,
		java.lang.String _revision,
		boolean _useROR,
		excr_eprocedure_api.proxies.ResTaskFromTaskListJsonObject _resTaskFromTaskListJsonObject,
		excr_resourcemanagement.proxies.ContainerCollectDataContext _containerCollectDataContext,
		java.math.BigDecimal _currentValue,
		java.math.BigDecimal _allocatedTime
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.SUB_Eprocedure_CollectData");
		builder = builder.withParam("RequestBody", _requestBody);
		builder = builder.withParam("ContainerName", _containerName);
		builder = builder.withParam("DataCollectionName", _dataCollectionName);
		builder = builder.withParam("Comments", _comments);
		builder = builder.withParam("Revision", _revision);
		builder = builder.withParam("UseROR", _useROR);
		builder = builder.withParam("ResTaskFromTaskListJsonObject", _resTaskFromTaskListJsonObject);
		builder = builder.withParam("ContainerCollectDataContext", _containerCollectDataContext);
		builder = builder.withParam("CurrentValue", _currentValue);
		builder = builder.withParam("AllocatedTime", _allocatedTime);
		return builder;
	}

	public static excr_eprocedure_api.proxies.ReqContainerCollectDataRoot sUB_Eprocedure_CollectData(
		IContext context,
		java.lang.String _requestBody,
		java.lang.String _containerName,
		java.lang.String _dataCollectionName,
		java.lang.String _comments,
		java.lang.String _revision,
		boolean _useROR,
		excr_eprocedure_api.proxies.ResTaskFromTaskListJsonObject _resTaskFromTaskListJsonObject,
		excr_resourcemanagement.proxies.ContainerCollectDataContext _containerCollectDataContext,
		java.math.BigDecimal _currentValue,
		java.math.BigDecimal _allocatedTime
	)
	{
		Object result = sUB_Eprocedure_CollectDataBuilder(
				_requestBody,
				_containerName,
				_dataCollectionName,
				_comments,
				_revision,
				_useROR,
				_resTaskFromTaskListJsonObject,
				_containerCollectDataContext,
				_currentValue,
				_allocatedTime
			)
			.execute(context);
		return result == null ? null : excr_eprocedure_api.proxies.ReqContainerCollectDataRoot.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Eprocedure_TransactionCollectDataBuilder(
		java.lang.String _requestBody,
		java.lang.String _containerName,
		java.lang.String _dataCollectionName,
		java.lang.String _comments,
		java.lang.String _revision,
		boolean _useROR,
		excr_eprocedure_api.proxies.ResTaskFromTaskListJsonObject _resTaskFromTaskListJsonObject,
		excr_resourcemanagement.proxies.ContainerCollectDataContext _containerCollectDataContext,
		java.math.BigDecimal _allocatedTime,
		java.math.BigDecimal _currentValue
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXCR_EProcedure.SUB_Eprocedure_TransactionCollectData");
		builder = builder.withParam("RequestBody", _requestBody);
		builder = builder.withParam("ContainerName", _containerName);
		builder = builder.withParam("DataCollectionName", _dataCollectionName);
		builder = builder.withParam("Comments", _comments);
		builder = builder.withParam("Revision", _revision);
		builder = builder.withParam("UseROR", _useROR);
		builder = builder.withParam("ResTaskFromTaskListJsonObject", _resTaskFromTaskListJsonObject);
		builder = builder.withParam("ContainerCollectDataContext", _containerCollectDataContext);
		builder = builder.withParam("AllocatedTime", _allocatedTime);
		builder = builder.withParam("CurrentValue", _currentValue);
		return builder;
	}

	public static excr_eprocedure_api.proxies.ReqContainerCollectDataRoot sUB_Eprocedure_TransactionCollectData(
		IContext context,
		java.lang.String _requestBody,
		java.lang.String _containerName,
		java.lang.String _dataCollectionName,
		java.lang.String _comments,
		java.lang.String _revision,
		boolean _useROR,
		excr_eprocedure_api.proxies.ResTaskFromTaskListJsonObject _resTaskFromTaskListJsonObject,
		excr_resourcemanagement.proxies.ContainerCollectDataContext _containerCollectDataContext,
		java.math.BigDecimal _allocatedTime,
		java.math.BigDecimal _currentValue
	)
	{
		Object result = sUB_Eprocedure_TransactionCollectDataBuilder(
				_requestBody,
				_containerName,
				_dataCollectionName,
				_comments,
				_revision,
				_useROR,
				_resTaskFromTaskListJsonObject,
				_containerCollectDataContext,
				_allocatedTime,
				_currentValue
			)
			.execute(context);
		return result == null ? null : excr_eprocedure_api.proxies.ReqContainerCollectDataRoot.initialize(context, (IMendixObject) result);
	}
}
