// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject[]} processTimers
 * @returns {Promise.<MxObject[]>}
 */
export async function JS_Calculate_ProcessTimersTime(processTimers) {
	// BEGIN USER CODE
	if (!Array.isArray(processTimers)) {
        console.error("Expected a list of ProcessTimer objects, but got:", processTimers);
        return false;
    }

	const now = new Date();

    function formatTime(daysDiff) {
        const isOverdue = daysDiff >= 0;
        const totalSeconds = Math.floor(Math.abs(daysDiff) * 24 * 3600);
        const days = Math.floor(totalSeconds / (24 * 3600));
        const hours = Math.floor((totalSeconds % (24 * 3600)) / 3600);
        const minutes = Math.floor((totalSeconds % 3600) / 60);
        const seconds = totalSeconds % 60;

        const formatted = `${String(days).padStart(2, "0")}.${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;

        return (isOverdue ? "\u00A0+" : "\u00A0\u00A0\u00A0") + formatted + "\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0";
    }

    // Safely extract float values from timer fields
    function safeFloat(val) {
        return val != null && !isNaN(parseFloat(val)) ? parseFloat(val) : null;
    }

	// cache to avoid duplicating rules
	const dynamicColorClasses = new Set();

	function getOrCreateColorClass(colorHex) {
		if (!colorHex) return "";

		const cleanHex = colorHex.replace("#", "").toLowerCase();
		const processTimerColorClassName = `timer-${cleanHex}`;

		if (!dynamicColorClasses.has(processTimerColorClassName)) {
			const style = document.createElement("style");
			style.innerHTML = `
				.${processTimerColorClassName} {
					background-color: ${colorHex} !important;
				}
			`;
			document.head.appendChild(style);
			dynamicColorClasses.add(processTimerColorClassName);
		}

		return processTimerColorClassName;
	}

    // Convert all creates into promises
    const promises = processTimers.map(timer => {
        return new Promise((resolve, reject) => {
            if (!timer.get("StartTimeGMT") || !timer.get("ProcessTimerName")) {
                return resolve(null);
            }
			try {
				mx.data.create({
					entity: "EXCR_EProcedure.TempProcessTimerDisplay",
					callback: function(obj) {
						const start = new Date(timer.get("StartTimeGMT"));
						const elapsedTime = (now - start) / (1000 * 60 * 60 * 24);

						const processTimerName = timer.get("ProcessTimerName");
						const processTimerRevision = timer.get("ProcessTimerRev");
						const minWarnTime = safeFloat(timer.get("MinWarningTime"));
						const maxWarnTime = safeFloat(timer.get("MaxWarningTime"));
						const minTime = safeFloat(timer.get("MinTime"));
						const maxTime = safeFloat(timer.get("MaxTime"));
						const minWarnColor = timer.get("MinWarningTimeColor");
						const minTimeColor = timer.get("MinTimeColor");
						const maxWarnColor = timer.get("MaxWarningTimeColor");
						const maxTimeColor = timer.get("MaxTimeColor");

						const timeToMin = minTime != null ? -(minTime - elapsedTime) : null;
						const timeToMax = maxTime != null ? -(maxTime - elapsedTime) : null;

						var timeToMinColor = null;
						var timeToMaxColor = null;

						if(timeToMax != null) // elapsedTime + timeToMax = maxTime
						{
							if (timeToMax < 0) { // Negative timeToMax means Timer is not Overdue
								if(Math.abs(timeToMax) <= maxWarnTime) { // if absolute of timeToMax is <= maxWarnTime, show max warn color 
									timeToMaxColor = maxWarnColor;
								}            
							} else { // Positive timeToMax means Timer is Overdue
								timeToMaxColor = maxTimeColor;
							}
						}
						if(timeToMin != null) {
							if (timeToMin < 0) { // Negative timeToMin means Timer is not Overdue
								if(Math.abs(timeToMin) <= minWarnTime) { // if absolute of timeToMin is <= minWarnTime, show min warn color 
									timeToMinColor = minWarnColor;
								}          
							} else { // Positive timeToMin means Timer is Overdue
								timeToMinColor = minTimeColor;
							}
						}

						if(processTimerRevision != null || processTimerRevision != "") {
							obj.set("ProcessTimerNameWithRevision", processTimerName + ":" + processTimerRevision);
						} else {
							obj.set("ProcessTimerNameWithRevision", processTimerName);
						}						
						obj.set("TimeToMinDisplay", timeToMin != null ? formatTime(timeToMin) : "");
						obj.set("TimeToMaxDisplay", timeToMax != null ? formatTime(timeToMax) : "");
						obj.set("TimeToMinColorDisplay", timeToMinColor != null ? getOrCreateColorClass(timeToMinColor) : "");
						obj.set("TimeToMaxColorDisplay", timeToMaxColor != null ? getOrCreateColorClass(timeToMaxColor) : "");

						resolve(obj);
					},
					error: function(e) {
						console.error("Error creating TempProcessTimerDisplay:", e);
						reject(e);
					}
				});
			} catch(e) {
				console.error("Unexpected error:", e);
				resolve(null);
        	}
        });
    });

    // Wait for all objects to be created
    const results = await Promise.all(promises);
	return results.filter(r => r !== null);

	// END USER CODE
}
