// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import "mx-global";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject[]} processTimers
 * @returns {Promise.<void>}
 */
export async function ProcessTimer_Update(processTimers) {
	// BEGIN USER CODE
    const activeTimerNameElement = document.querySelector(".container-header-label.active-timer-name");
    const activeTimerDisplayElement = document.querySelector(".dataField.active-timer-display-text");
    const activeTimerCountElement = document.querySelector(".active-timer-count-display-text");

    if (!activeTimerNameElement) {
        console.warn("No activeTimerNameElement widget found to display Active Timer.");
        return false;
    }

    if (!activeTimerDisplayElement) {
        console.warn("No activeTimerDisplayElement widget found to display Active Timer.");
        return false;
    }

    if (!activeTimerCountElement) {
        console.warn("No activeTimerCountElement widget found to display Active Timer.");
        return false;
    }

    if (!Array.isArray(processTimers)) {
        console.error("Expected a list of ProcessTimer objects, but got:", processTimers);
        return false;
    }

    const now = new Date();

    function formatTime(timeDelta) {
        const isPastTarget = timeDelta >= 0;
        const totalSeconds = Math.floor(Math.abs(timeDelta) * 24 * 3600);
        const days = Math.floor(totalSeconds / (24 * 3600));
        const hours = Math.floor((totalSeconds % (24 * 3600)) / 3600);
        const minutes = Math.floor((totalSeconds % 3600) / 60);
        const seconds = totalSeconds % 60;

        const formatted = `${String(days).padStart(2, "0")}.${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;

        return (isPastTarget ? "+" : "") + formatted;
    }

    function safeFloat(val) {
        return val != null && !isNaN(parseFloat(val)) ? parseFloat(val) : null;
    }

    // Take the first timer
    const activeTimer = processTimers[0];
    if (!activeTimer.get("StartTimeGMT") || !activeTimer.get("ProcessTimerName")) {
        return false;
    }

    const start = new Date(activeTimer.get("StartTimeGMT"));
    const elapsedTime = (now - start) / (1000 * 60 * 60 * 24);

    const activeProcessTimerName = activeTimer.get("ProcessTimerName");
    const activeProcessTimerCount = activeTimer.get("TimersCount");
    const activeMinWarnTime = safeFloat(activeTimer.get("MinWarningTime"));
    const activeMaxWarnTime = safeFloat(activeTimer.get("MaxWarningTime"));
    const activeMinTime = safeFloat(activeTimer.get("MinTime"));
    const activeMaxTime = safeFloat(activeTimer.get("MaxTime"));
    const activeMinWarnTimeColor = activeTimer.get("MinWarningTimeColor");
    const activeMinTimeColor = activeTimer.get("MinTimeColor");
    const activeMaxWarnTimeColor = activeTimer.get("MaxWarningTimeColor");
    const activeMaxTimeColor = activeTimer.get("MaxTimeColor");

    const activeTimeToMin = activeMinTime != null ? -(activeMinTime - elapsedTime) : null;
    const activeTimeToMax = activeMaxTime != null ? -(activeMaxTime - elapsedTime) : null;

    // Timer color
    let activeTimerColor = null;
    if (activeTimeToMax != null) {
        if (activeTimeToMax < 0) {
            if (Math.abs(activeTimeToMax) <= activeMaxWarnTime) {
                activeTimerColor = activeMaxWarnTimeColor;
            }
        } else {
            activeTimerColor = activeMaxTimeColor;
        }
    } else if (activeTimeToMin != null) {
        if (activeTimeToMin < 0) {
            if (Math.abs(activeTimeToMin) <= activeMinWarnTime) {
                activeTimerColor = activeMinWarnTimeColor;
            }
        } else {
            activeTimerColor = activeMinTimeColor;
        }
    }

    // Update widgets
    if (activeProcessTimerName != null) {
        activeTimerNameElement.textContent = activeProcessTimerName;
    }
    if (activeProcessTimerCount != null) {
        activeTimerCountElement.textContent = activeProcessTimerCount;
    }

    const displayTime = activeTimeToMax ?? activeTimeToMin;
    if (displayTime != null) {
        activeTimerDisplayElement.textContent = formatTime(displayTime);
    }
    // Even if color is null, set it to reset the color
    activeTimerDisplayElement.style.backgroundColor = activeTimerColor;

    return true;
	// END USER CODE
}
