// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} widgetName - Specify the widget name where you want to showcase the progress loader.
 * @param {boolean} showLoader - Boolean field to show or hide the loader.
 * @param {"EXCR_Commons.Enum_ProgressLoaderSize.XXSmall"|"EXCR_Commons.Enum_ProgressLoaderSize.XSmall"|"EXCR_Commons.Enum_ProgressLoaderSize.Small"|"EXCR_Commons.Enum_ProgressLoaderSize.Medium"|"EXCR_Commons.Enum_ProgressLoaderSize.Large"|"EXCR_Commons.Enum_ProgressLoaderSize.XLarge"|"EXCR_Commons.Enum_ProgressLoaderSize.XXLarge"} loaderSize - Select the size of the loader to display
 * @returns {Promise.<void>}
 */
export async function WidgetProgressLoader(widgetName, showLoader, loaderSize) {
	// BEGIN USER CODE
    
     var targetElement = document.querySelector(".mx-name-" + widgetName);
 
    if (targetElement)
    {
        // Remove any existing loader
        var existingSpinner = targetElement.querySelector(".loading-spinner");
        if (existingSpinner)
        {
            existingSpinner.remove();
        }
        
        // If showLoader is false, restore full opacity and enable pointer events
        if (!showLoader)
        {
            targetElement.style.opacity = 1;
            targetElement.style.pointerEvents = 'auto';
        }
        else
        {
            // Reduce the opacity of the target section
            targetElement.style.opacity = 0.5;
 
            // Disable pointer events on the target section
            targetElement.style.pointerEvents = 'none';
 
            // Create and append the loading spinner directly to the section
            var spinner = document.createElement("div");
            spinner.className = "loading-spinner";
 
            switch (loaderSize) {
            case "XXSmall":
                spinner.style.width = "16px";
                spinner.style.height = "16px";
                break;
            case "XSmall":
                spinner.style.width = "24px";
                spinner.style.height = "24px";
                break;
            case "Small":
                spinner.style.width = "32px";
                spinner.style.height = "32px";
                break;
            case "Medium":
                spinner.style.width = "48px";
                spinner.style.height = "48px";
                break;
            case "Large":
                spinner.style.width = "65px";
                spinner.style.height = "65px";
                break;
            case "XLarge":
                spinner.style.width = "80px";
                spinner.style.height = "80px";
                break;
            case "XXLarge":
                spinner.style.width = "96px";
                spinner.style.height = "96px";
                break;
            default:
                spinner.style.width = "48px"; // Default to medium size
                spinner.style.height = "48px";
            }
                
            spinner.style.position = "absolute";
            spinner.style.left = "50%";
            spinner.style.top = "40%";
            spinner.style.transform = "translate(-50%, -50%)";
            targetElement.appendChild(spinner);
        }
    }
 
	// END USER CODE
}
