// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_entityfactory.proxies;

public class HttpRequestInfo implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject httpRequestInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EntityFactory.HttpRequestInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServerURL("ServerURL"),
		AccessToken("AccessToken"),
		ContentType("ContentType"),
		Top("Top"),
		Skip("Skip"),
		Filter("Filter"),
		OrderBy("OrderBy");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HttpRequestInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected HttpRequestInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject httpRequestInfoMendixObject)
	{
		if (httpRequestInfoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!httpRequestInfoMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.httpRequestInfoMendixObject = httpRequestInfoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_entityfactory.proxies.HttpRequestInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_entityfactory.proxies.HttpRequestInfo(context, mendixObject);
	}

	public static excr_entityfactory.proxies.HttpRequestInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_entityfactory.proxies.HttpRequestInfo.initialize(context, mendixObject);
	}

	/**
	 * @return value of ServerURL
	 */
	public final java.lang.String getServerURL()
	{
		return getServerURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ServerURL
	 */
	public final java.lang.String getServerURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServerURL.toString());
	}

	/**
	 * Set value of ServerURL
	 * @param serverurl
	 */
	public final void setServerURL(java.lang.String serverurl)
	{
		setServerURL(getContext(), serverurl);
	}

	/**
	 * Set value of ServerURL
	 * @param context
	 * @param serverurl
	 */
	public final void setServerURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serverurl)
	{
		getMendixObject().setValue(context, MemberNames.ServerURL.toString(), serverurl);
	}

	/**
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken()
	{
		return getAccessToken(getContext());
	}

	/**
	 * @param context
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccessToken.toString());
	}

	/**
	 * Set value of AccessToken
	 * @param accesstoken
	 */
	public final void setAccessToken(java.lang.String accesstoken)
	{
		setAccessToken(getContext(), accesstoken);
	}

	/**
	 * Set value of AccessToken
	 * @param context
	 * @param accesstoken
	 */
	public final void setAccessToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accesstoken)
	{
		getMendixObject().setValue(context, MemberNames.AccessToken.toString(), accesstoken);
	}

	/**
	 * @return value of ContentType
	 */
	public final java.lang.String getContentType()
	{
		return getContentType(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentType
	 */
	public final java.lang.String getContentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentType.toString());
	}

	/**
	 * Set value of ContentType
	 * @param contenttype
	 */
	public final void setContentType(java.lang.String contenttype)
	{
		setContentType(getContext(), contenttype);
	}

	/**
	 * Set value of ContentType
	 * @param context
	 * @param contenttype
	 */
	public final void setContentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contenttype)
	{
		getMendixObject().setValue(context, MemberNames.ContentType.toString(), contenttype);
	}

	/**
	 * @return value of Top
	 */
	public final java.lang.String getTop()
	{
		return getTop(getContext());
	}

	/**
	 * @param context
	 * @return value of Top
	 */
	public final java.lang.String getTop(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Top.toString());
	}

	/**
	 * Set value of Top
	 * @param top
	 */
	public final void setTop(java.lang.String top)
	{
		setTop(getContext(), top);
	}

	/**
	 * Set value of Top
	 * @param context
	 * @param top
	 */
	public final void setTop(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String top)
	{
		getMendixObject().setValue(context, MemberNames.Top.toString(), top);
	}

	/**
	 * @return value of Skip
	 */
	public final java.lang.String getSkip()
	{
		return getSkip(getContext());
	}

	/**
	 * @param context
	 * @return value of Skip
	 */
	public final java.lang.String getSkip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Skip.toString());
	}

	/**
	 * Set value of Skip
	 * @param skip
	 */
	public final void setSkip(java.lang.String skip)
	{
		setSkip(getContext(), skip);
	}

	/**
	 * Set value of Skip
	 * @param context
	 * @param skip
	 */
	public final void setSkip(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String skip)
	{
		getMendixObject().setValue(context, MemberNames.Skip.toString(), skip);
	}

	/**
	 * @return value of Filter
	 */
	public final java.lang.String getFilter()
	{
		return getFilter(getContext());
	}

	/**
	 * @param context
	 * @return value of Filter
	 */
	public final java.lang.String getFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Filter.toString());
	}

	/**
	 * Set value of Filter
	 * @param filter
	 */
	public final void setFilter(java.lang.String filter)
	{
		setFilter(getContext(), filter);
	}

	/**
	 * Set value of Filter
	 * @param context
	 * @param filter
	 */
	public final void setFilter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filter)
	{
		getMendixObject().setValue(context, MemberNames.Filter.toString(), filter);
	}

	/**
	 * @return value of OrderBy
	 */
	public final java.lang.String getOrderBy()
	{
		return getOrderBy(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderBy
	 */
	public final java.lang.String getOrderBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderBy.toString());
	}

	/**
	 * Set value of OrderBy
	 * @param orderby
	 */
	public final void setOrderBy(java.lang.String orderby)
	{
		setOrderBy(getContext(), orderby);
	}

	/**
	 * Set value of OrderBy
	 * @param context
	 * @param orderby
	 */
	public final void setOrderBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String orderby)
	{
		getMendixObject().setValue(context, MemberNames.OrderBy.toString(), orderby);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return httpRequestInfoMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_entityfactory.proxies.HttpRequestInfo that = (excr_entityfactory.proxies.HttpRequestInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
