// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excr_entityfactory.proxies;

public class OpDashContainer extends excr_entityfactory.proxies.Container
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXCR_EntityFactory.OpDashContainer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InProcess("InProcess"),
		Status("Status"),
		StatusName("StatusName"),
		CurrentHoldCount("CurrentHoldCount"),
		UseQueue("UseQueue"),
		HoldReasonId("HoldReasonId"),
		ResourceName("ResourceName"),
		ContainerId("ContainerId"),
		ContainerName("ContainerName"),
		Qty("Qty"),
		Qty2("Qty2"),
		ProductId("ProductId"),
		ProductName("ProductName"),
		SpecId("SpecId"),
		SpecName("SpecName"),
		OperationId("OperationId"),
		OperationName("OperationName"),
		WorkflowId("WorkflowId"),
		WorkflowName("WorkflowName"),
		UOMName("UOMName"),
		UOM2Name("UOM2Name"),
		MfgOrderName("MfgOrderName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OpDashContainer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OpDashContainer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject opDashContainerMendixObject)
	{
		super(context, opDashContainerMendixObject);
		if (!opDashContainerMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static excr_entityfactory.proxies.OpDashContainer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new excr_entityfactory.proxies.OpDashContainer(context, mendixObject);
	}

	public static excr_entityfactory.proxies.OpDashContainer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return excr_entityfactory.proxies.OpDashContainer.initialize(context, mendixObject);
	}

	/**
	 * @return value of InProcess
	 */
	public final java.lang.String getInProcess()
	{
		return getInProcess(getContext());
	}

	/**
	 * @param context
	 * @return value of InProcess
	 */
	public final java.lang.String getInProcess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InProcess.toString());
	}

	/**
	 * Set value of InProcess
	 * @param inprocess
	 */
	public final void setInProcess(java.lang.String inprocess)
	{
		setInProcess(getContext(), inprocess);
	}

	/**
	 * Set value of InProcess
	 * @param context
	 * @param inprocess
	 */
	public final void setInProcess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String inprocess)
	{
		getMendixObject().setValue(context, MemberNames.InProcess.toString(), inprocess);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of StatusName
	 */
	public final java.lang.String getStatusName()
	{
		return getStatusName(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusName
	 */
	public final java.lang.String getStatusName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StatusName.toString());
	}

	/**
	 * Set value of StatusName
	 * @param statusname
	 */
	public final void setStatusName(java.lang.String statusname)
	{
		setStatusName(getContext(), statusname);
	}

	/**
	 * Set value of StatusName
	 * @param context
	 * @param statusname
	 */
	public final void setStatusName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String statusname)
	{
		getMendixObject().setValue(context, MemberNames.StatusName.toString(), statusname);
	}

	/**
	 * @return value of CurrentHoldCount
	 */
	public final java.lang.String getCurrentHoldCount()
	{
		return getCurrentHoldCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentHoldCount
	 */
	public final java.lang.String getCurrentHoldCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrentHoldCount.toString());
	}

	/**
	 * Set value of CurrentHoldCount
	 * @param currentholdcount
	 */
	public final void setCurrentHoldCount(java.lang.String currentholdcount)
	{
		setCurrentHoldCount(getContext(), currentholdcount);
	}

	/**
	 * Set value of CurrentHoldCount
	 * @param context
	 * @param currentholdcount
	 */
	public final void setCurrentHoldCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currentholdcount)
	{
		getMendixObject().setValue(context, MemberNames.CurrentHoldCount.toString(), currentholdcount);
	}

	/**
	 * @return value of UseQueue
	 */
	public final java.lang.String getUseQueue()
	{
		return getUseQueue(getContext());
	}

	/**
	 * @param context
	 * @return value of UseQueue
	 */
	public final java.lang.String getUseQueue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseQueue.toString());
	}

	/**
	 * Set value of UseQueue
	 * @param usequeue
	 */
	public final void setUseQueue(java.lang.String usequeue)
	{
		setUseQueue(getContext(), usequeue);
	}

	/**
	 * Set value of UseQueue
	 * @param context
	 * @param usequeue
	 */
	public final void setUseQueue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usequeue)
	{
		getMendixObject().setValue(context, MemberNames.UseQueue.toString(), usequeue);
	}

	/**
	 * @return value of HoldReasonId
	 */
	public final java.lang.String getHoldReasonId()
	{
		return getHoldReasonId(getContext());
	}

	/**
	 * @param context
	 * @return value of HoldReasonId
	 */
	public final java.lang.String getHoldReasonId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HoldReasonId.toString());
	}

	/**
	 * Set value of HoldReasonId
	 * @param holdreasonid
	 */
	public final void setHoldReasonId(java.lang.String holdreasonid)
	{
		setHoldReasonId(getContext(), holdreasonid);
	}

	/**
	 * Set value of HoldReasonId
	 * @param context
	 * @param holdreasonid
	 */
	public final void setHoldReasonId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdreasonid)
	{
		getMendixObject().setValue(context, MemberNames.HoldReasonId.toString(), holdreasonid);
	}

	/**
	 * @return value of ResourceName
	 */
	public final java.lang.String getResourceName()
	{
		return getResourceName(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceName
	 */
	public final java.lang.String getResourceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResourceName.toString());
	}

	/**
	 * Set value of ResourceName
	 * @param resourcename
	 */
	public final void setResourceName(java.lang.String resourcename)
	{
		setResourceName(getContext(), resourcename);
	}

	/**
	 * Set value of ResourceName
	 * @param context
	 * @param resourcename
	 */
	public final void setResourceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resourcename)
	{
		getMendixObject().setValue(context, MemberNames.ResourceName.toString(), resourcename);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final excr_entityfactory.proxies.OpDashContainer that = (excr_entityfactory.proxies.OpDashContainer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
